pagefaultgames/pokerogue

- src/data/move.ts
Thousand Arrows was not hitting flying and levitating targets. Now the logic should be correct. 
If there is a better way to set target tag so that it does not have a turn limit (set to 20 now) then that should be used instead.
> Implement/Fix Thousand arrows

- src/data/move.ts
Flail and Reversal were capped to 40bp due to the easiest to pass case being at the top.
> Fix Flail and Reversal damage

- src/data/move.ts
Implements the two moves that compare weight between user and target.
The guard is there to avoid division by zero if user.getWeight() returns 0 for some reason. Can be removed if deemed unnecessary.
> Implement Heat Crash and Heavy Slam

- src/data/move.ts
Tested these moves with level 50 Blisseys fighting each other with Speed Boost ability. Damage seemed to increase by 100% of the first turn value more or less, as expected. Also tested with Moody ability to make sure negative boosts don't lower the value. As expected the damage went up by around 200% the first turn value, as expected since moody boosts one stat by 2 stages.
Accuracy and Evasion boosts are also counted and I assumed Random BattleStat is never going to be above 0 since it only seems to be used to pass the boosts from a move.
There's no need to add a cap to the damage since apparently there's not one in the games, just a soft cap of 860 since that's how much you can reach with +6 in all stats, per bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Stored_Power_(move)#Trivia …
> Implemented the moves Stored Power and Power Trip

- src/data/arena-tag.ts
Toxic spikes should now be removed by poison types who are statused before they are switched to, instead of ignoring their entry
> Toxic Spikes - Properly removed by statused Poison types

- src/battle-scene.ts
- src/battle.ts
- src/data/move.ts
- src/phases.ts
the battle-scene change was just refactoring duplicate code I saw and removing stale imports
the way money scattered is being calculated is based on the base price for the shop to keep it balanced. 1/5 base cost is essentially enough to buy a potion. 
Pay Day: https://bulbapedia.bulbagarden.net/wiki/Pay_Day_(move)
Make it Rain: https://bulbapedia.bulbagarden.net/wiki/Make_It_Rain_(move)
> Implement Pay Day and Make it Rain

- src/data/arena-tag.ts
Had to add "side" in there too, otherwise the Screens were being set for ArenaTagSide.BOTH and not working (since now they are set in the right side).
> Small fix for Reflect/Light Screen/Aurora Veil

- src/data/battler-tags.ts
- src/phases.ts
Made Recharge its own BattlerTagLapseType called PRE_MOVE that triggers before MOVE, cancelling the move phase.  doMove now checks for this.cancelled before calling on the MOVE lapse tag, which should prevent confusion or infatuation from triggering after the pokemon has already had its move cancelled by the other statuses.  I wasn't able to find any issues with moving the if (this.cancelled) check to end the turn outside of if(!this.followUp && this.canMove()) check, but if need be I can edit those into the if statement, just didn't want to add bloat.
> Fixing Confusion triggering after Sleep, Paralysis, and Recharging

- src/modifier/modifier-type.ts
Battle stat boosters were changed to 5 turns in e5ffc1e2db27b9615183871369ca6e7e2d46a55f, this PR updates the text to match again
> Fix battle stat booster text to match effect again

- src/field/pokemon.ts
Trello Card: https://trello.com/c/Tmhsfkff
Discord Bug Report: https://discord.com/channels/1125469663833370665/1226068395917705216
Guts has an effect that prevents an pokemon w/ the ability from losing Attack when burned. The attribute for this ability was being mistakenly applied to the pokemon being attacked, rather than the pokemon attacking.
> Fix: Guts ability now ignores burn damage debuff

- src/data/ability.ts
- src/phases.ts
Fixed Soul-Heart to always boost whenever a pokemon faints. 
Moved KO stat boosts out of VictoryPhase and into FaintPhase, because VictoryPhase is only called when opponent pokemon faints. This caused opponents KO stat boost abilities to never proc.
I didn't see any issues in doing so in my testing, but FaintPhase is pretty convoluted, so there might be some.
> Properly implement Soul-Heart, Fix Opponent Stage boosts on faints

- src/data/move.ts
Changed Counterdamage attribute to include a multiplier for metal burst and comeuppance. Changed logic for Comeuppance that caused it to always fail, no matter if a physical or special move hit it. Implemented Metal Burst.
> Implemented Metal Burst, fixed comeuppance logic, changed CounterDamage attribute

- src/battle-scene.ts
**Before**
- Input handling allowed for one button press at a time, with an 250ms global delay between presses. Any button could be held down and be triggered on a 250ms loop. This made input selection (particularly around menu navigation) feel clunkier than necessary.
**After**
- Inputs are no longer subject to the 250ms global delay and can now be processed as quickly as the user can press the button.
- Only movement buttons specifically can be held down to fire repeated inputs. Other buttons only fire once per press, to avoid accidental inputs.
- Multiple movement buttons being held down are buffered and the most recently pressed one is prioritized. Releasing one movement button when others are still held down will cause another button to be selected in a fixed order.
> Improvement: update input handling to support quick taps and buffered inputs

- src/data/move.ts
Made toxic skip accuracy check when used by poison type.
Fixed thousand waves failing when used against already trapped opponent.
Made freeze-dry return true when the effect is applied.
Toxic still will not hit semi-invulnerable. (Nor does anything else).
> Toxic accuracy skip, fix thousand waves

- src/data/move.ts
- src/field/pokemon.ts
Aura wheel and Raging bull now switch typing depending on user form. Made Aura wheel fail if used by anything else than Morpeko. (There was no pokemon with Aura Wheel as egg move).
Raging bull is still marked as (P) as it doesn't break screens yet.
> Implement Aura Wheel and Raging Bull types

- src/data/move.ts
- src/field/arena.ts
- src/field/pokemon.ts
Implements Secret sword targeting opponents defense. (Same logic as Psyshock).
Implements Rising Voltage & Psyblade power increase when in electric terrain. Psyblade when user is grounded, rising voltage when target is grounded.
Modified the pokemon.isGrounded() code so that it checks for levitate. This causes levitate to now ignore spikes, sticky webs, terrain effects etc correctly.
Added a arena.getTerrainType() helper to return active terrain.
> Psyblade, Rising Voltage, Secret Sword, Add levitate to grounded check.

- index.css
- index.html
- manifest.json
- service-worker.js
This PR adds basic PWA support for mobile devices, allowing users to "install" the web app onto their device. It also adjusts the controller padding to account for the safe area on iOS when necessary.
If someone is able to confirm that this works on Android before merging, that would be much appreciated as I only have an iPhone. You can test it by opening one of the network hosts that Vite sets up when running `npm run start:dev`, then just open the share sheet and press "Add to Home Screen".
In the future, once there are less frequent changes, this could be adjusted to cache static assets as well.
Here's what it looks like on a iPhone 14 Pro Max:
And the home screen icon:
> Add basic PWA support

- src/data/move.ts
Protection moves did not check if the previous uses were successful.
> Fix protect having a chance to fail twice in a row

- src/data/move.ts
Rapid Spin now removes the tags for trapping moves and seeds rather than having them lapse (this would cause them to trigger an additional time, or clear, depending on how many turns were left).  Re-added the (P) to the move since clearing arena hazards hasn't been implemented yet.
> Rapid Spin now removes traps/seeds, added (P) back on

- src/data/move.ts
- src/field/pokemon.ts
Also lets shell side arm poison, for some reason it didn't have the status associated.
All five moves with this feature are still tagged as partially implemented because they are. Shell Side Arm is probably implemented slightly wrong, this is a basic fix and the move is actually quite complicated, but it also has conditional contact. Tera Blast and Tera Starstorm need support for variable types and stellar, and photon geyser and light that burns the sky need support still for ignoring abilities. This is just here to add support for switching between physical and special.
> Add support for variable category moves

- src/data/ability.ts
Implemented Shed Skin, with a 1/3 chance to remove a non-volatile status condition if inflicted with it at the end of each turn. While doing this I noticed Hydration is the same effect but in Rain/Heavy Rain, so I implemented that too.
Tested on all of the statuses - burn, freeze, both forms of poison, sleep, paralysis. Tested non-volatile and it shouldn't work on those. Tested that it only applies to the person with the ability and doesn't somehow do anything wacky there, and that seems to be in order.
Hydration was implemented through the same mechanisms, just a check for rain or heavy rain before it does the clearing, rather than a chance roll. Figured since these are the same ability just with different conditionals it wouldn't be right not to.
> Implement Shed Skin (and Hydration!)

- src/data/ability.ts
Adds a condition check for the hail weather type for Snow Cloak. Currently it doesn't check for hail in applying it's evasiveness.
> Snow Cloak Conditional Fix

- manifest.json
I think I initially had manifest.json in `src/`, but moved it to the root dir and forgot to update the src property... oops..
> Fix the logo not appearing when installed as a PWA

- src/data/terrain.ts
There was a bug where Psychic Terrain would block protecting moves.
Added an if guard to check for Protected Attribute on the current move that's being used, so Protect, King's Shield, etc. that have increased priority brackets can work as expected. (they are not supposed to be blocked in Psychic Terrain)
> fix for Psychic Terrain blocking Protect Moves

- package-lock.json
- package.json
- src/locales/en/menu.ts
- src/locales/it/menu.ts
- src/phases.ts
- src/plugins/i18n.ts
- The game is written in English, and there's no easy way for people to contribute language translations or have them be used in-game.
- Added i18next, a popular localization framework to the project 
- Followed blog posts [1](https://locize.com/blog/i18next-typescript/) and [2](https://blog.logrocket.com/implementing-safe-dynamic-localization-typescript-apps/) as references
- Added example resource file for English and Italian and replaced main menu strings with i18next calls
- I don't speak Italian so the translations are probably wrong, just added it as an example
- Setup type-safety so that users have features like auto-complete, compile errors if they reference the wrong keys in i18next
- Create resource file namespaces for different categories of text (pokemon names, moves, …
> Add i18next framework to enable further contributions

- src/data/ability.ts
There's a bit of uncertainly in how the ability should behave when you send out a pokemon after double-fainting, e.g. with explosion. The current behavior is that if you summon a download pokemon after the wild pokemon and your pokemon faints, nothing happens, and if you summon a download pokemon after a trainer's pokemon faints, you'll be able to get the stats since they're already summoned by the time you switch in.
The above could justify a (P) potentially, but the move otherwise works as you'd expect (implemented similarly to Intimidate, so it may have some of Intimidate's bugs).
> Implement download

- src/data/move.ts
- src/phases.ts
[Trello issue](https://trello.com/c/TJhxX1iA/11-high-jump-kick-etc-dont-show-miss-message-or-update-battle-info)
[Bulbapedia reference](https://bulbapedia.bulbagarden.net/wiki/Crash_damage)
Changes apply to High Jump Kick,  Axe Kick, Jump Kick, Supercell Slam.
- Renames `halveHpMissEffectFunc` to `crashDamageFunc`  (could keep old name though)
- Changes function to call `damageAndUpdate` method, which fixes issue with no HP damage actually applying (and still shows damage numbers). Added specific crash damage message
- Added new `NoEffectAttr` attribute to be used in `HitResult.NO_EFFECT` case, since crash damage should also apply here
Tested ineffective moves against Ghost-type Pokemon and missed moves against other types.
> Add crash damage message + battle info update for missed/ineffective moves (High Jump Kick etc.)

- src/data/ability.ts
- src/data/move.ts
Adds more nuanced support for ability attributes, correcting the ones already there. This is required for supporting several moves and abilities like mold breaker or skill swap accurately. This updates skill swap with support for the new unswappable tag as well, also fixes a skill swap bug, it should fail if either the user or target has an unswappable ability, not just the target.
This doesn't do much by itself, it'll just make future support for these kinds of effects much easier.
> Update ability attributes

- src/locales/en/menu.ts
- src/phases.ts
Transferred some string literals from `phases.ts` into the localization file. Still a lot more to go in this file alone!
I tried verifying most of the lines live as I went, but that proved impractical really expensive.
While the keys themselves are type-safe (so you can't get them wrong w/o a compile break), it doesn't look like i18next supports strong typing for [Interpolation](https://www.i18next.com/translation-function/interpolation), which means it's possible to typo or get the `{{ }}` keys wrong in-code.
If that happens, the fallback is for the literal string to show up in the text. So for example, `{{pokemonName}}` would show up instead of "Piplup".
> No-op: refactor some string literals into i18next

- src/field/arena.ts
- src/field/pokemon.ts
There was two bugs in checking terrain power multiplier. First the source should be checked if it is grounded, not the target, and secondly the effect was applied when the pokemon was not grounded.
> Bugfix: Terrain power multiplier boost

- src/data/pokemon-species.ts
Removes its powerful coverage options in exchange for losing Slow Start, still gets walled by anything that resists/ignores Normal type moves but is no longer useless for 5 turns
> Gave Regigigas Normalize as a HA following talks about it on Discord

- index.html
Prevents browsers from firing a PWA install prompt that was causing confusion to some users.
Users can still install as an app from the browsers' menu/nav button.
> Prevent install as an app prompt

- src/plugins/i18n.ts
By default, i18next interpolation escapes input values so as to avoid XSS attacks. This turned characters like `&` into `&amp;`, which then got displayed as is in-game.
The text being displayed in this game is code-input only, so we get little value out of XSS protection. Disabling escapes fixes the issue:
> Fix: stop escaping interpolation values in i18next

- src/data/ability.ts
- src/data/move.ts
- src/phases.ts
Adds almost complete support for all ability changing moves and abilities. This covers Role Play, Entrainment, Doodle, Simple Beam, and Worry Seed for moves, and Trace, Wandering Spirit, Mummy, Receiver, Power of Alchemy, and Lingering Aroma for abilities.
Wandering Spirit is currently marked as (P) still because it interacts incorrectly with rock head. It's meant to switch abilities before recoil would apply so that a pokemon with rock head would lose rock head first and still take the recoil, but this is a niche interaction that seemed like it was poorly supported with the current ordering of move and ability attribute application so is not including in this pull request.
> Add support for ability changing effects

- src/ui/egg-gacha-ui-handler.ts
The legendary egg gacha currently removes 1/255 value from common and epic, putting them into rare and legendary. 
This change now properly only removes 1/255 values from common and moves it into legendary as intended.
> Fix bug in legendary gacha that reduced epic egg rates

- src/data/move.ts
- src/field/pokemon.ts
- src/phases.ts
Now fails if the target has already acted or has selected a status move
I've tested this a bit and it seems to work, I also confirmed you can sucker punch a sleeping target that has selected an attacking move so the move doesn't have to be possible as intended.
> Implement sucker punch

- src/data/ability.ts
pokemon with toxic chain have a 30% chance to apply to toxic on hit
tested roost as a self targeting move to prevent poisoning self
> Implement toxic chain

- src/data/ability.ts
- src/field/pokemon.ts
Implemented Rivalry which deals 25% more damage when the user is the same gender as the target and deals 25% less when the user is different genders. Does not work if the user is genderless. Tested by hitting enemies and noting that the damage dealt to same gendered opponents was around 1.6 times that of opposite gendered opponents.
Implemented Quick Feet which boosts speed by 50% when status'd and removes the speed penalty from paralysis. Tested by letting my Pokemon get nuzzle'd and then still outspeeding.
Created the `MoveTypeChangeAttr` which let me implement Liquid Voice and Normalize. Tested by making sure the typing was changed and the damage modification exists.
> Implement Rivalry, Quick Feet, Liquid Voice, and Normalize

- src/data/move.ts
Just doing a bunch of easy improvements here. Fixes Focus Punch, Revenge, Genesis Supernova, Grav Apple, Collision Course, Electro Drift, Clangorous Soulblaze, Gigaton Hammer, Blood Moon, and Tachyon Cutter.
Gigaton Hammer and Blood Moon still have (P) because of niche interactions with encore, but this works the other 99% of the time when you're not encore'd into them.
> Fix a bunch of moves

- src/data/ability.ts
Since Competitive is just Defiant but for SPATK, the code for Defiant was reused with the buff changed to special attack. This should mean the ability works the exact same way as Defiant for it's respective stat.
> Implement Competitive

- src/data/move.ts
The switch case for which move to use became a little cursed, didn't realize how many stages there were lol. Could possibly improve this by expanding upon the Biome class and add groupings that map to the move or something, not sure. 
Note: I took some creative liberties and added Shadow Ball, Dark Pulse, and Aura Sphere in respective environments that make sense thematically. Everything else is based off of Gen 8 and Gen 7. These selections can probably be improved upon, the rule seems to be that the moves are around 80~ power with no extreme extra effects.
> Implements Nature Power

- src/field/pokemon.ts
I was excited to use Shedinja with some of Nincada's egg moves but found that it did not inherit the moveset from Nincada during evolution and instead had it's default level-up moves.
I'm _think_ the expected behavior is that Shedinja inherits the moveset from the Nincada, but let me know if that is incorrect. Thanks for the fun game!
> Copies the moveset of the evolving Nincada to the newly generated pokemon for Shedinja

- src/phases.ts
Previously if a move KO'd the target then post defend abilities like rough skin and mummy were not triggered. I tested that this is resolved, and also that a run ends as expected if the player's last pokemon is KO'd by rough skin after KOing the target. 
Uploading 2024-04-14 19-29-07.mp4…
> Resolves issue with defend abilities not triggering if the target fainted 

- src/data/battler-tags.ts
- src/data/move.ts
- src/data/pokemon-forms.ts
- src/data/weather.ts
- src/field/pokemon.ts
- src/phases.ts
Implements the hasAbility and hasAbilityWithAttr methods onto the pokemon class, which allows much cleaner checking of whether a pokemon has an active ability, accounting for both canApply and passive. This also renames canApplyPassive to hasPassive because the name was misleading.
> Implement check functions for abilities

- src/data/ability.ts
Trace crashed the game if sent out against empty board.
> Prevent crash with trace

- src/data/move.ts
Changed force switch out attribute to be applied after the move is done. Additionally manually typed switch out attacks to be non baton pass moves.
> Fixed switch out attacks trigger contact for the replacement pokemon

- src/modifier/modifier-type.ts
I found a typo so I corrected "Inceases" to "Increases" in the description of the AttackTypeBoosterModifierType constructor.
Found this in the middle of a run and wanted to contribute.
> feat: correct typo in AttackTypeBoosterModifierType constructor

- src/data/ability.ts
- src/data/move.ts
- src/field/pokemon.ts
- src/phases.ts
This significantly reworks how ability suppression works, should also allow for support of gastro acid + core enforcer without much difficulty.
Also includes the ability ignoring effect on the gen 7 signature's moves.
> Fix mold breaker + implement neutralising gas

- src/data/move.ts
Haze should probably have a custom message so it doesn't list every pokemon, but this implements haze, clear smog, and freezy frost resetting stat boosts.
> Implement stat resetting moves

- src/data/move.ts
Fixes two bugs in sleep talk.
Firstly, Sleep talk should not use the PP of the move it selects.
Secondly, Sleep talk used to be able to call itself (and potentially keep chaining more sleep talks). 
Added Ignoresvirtual to make it no longer be able to call itself. Metronome and Assist cannot call Sleep talk either, so usage of the flag should be correct.
> Fix Sleep Talk bugs

- src/data/ability.ts
- src/field/pokemon.ts
This adds the NoFusionAbilityAbAttr attribute to abilities, which prevents them from being applied while fused. There's no warning or sign for this or anything, which may be worth fixing in the future. This is given to all form changing abilities for now.
> Add an attribute to abilities to block while fused

- src/data/pokemon-evolutions.ts
Updated the required biomes for evolutions:
* Alola Marowak
* Galar Weezing
* Alola Raichu
* Alola Exeggutor
There were some suggestions that said the biome restriction for Alolan evolution was hard because the Island biome is rare. Allow Beach as an alternative biome for Island and Slum as an alternative for Metropolis. This now matches with Galar Mr. Mime which has two biomes that let it evolve.
> Relax biome restrictions for regional evolutions

- src/phases.ts
If Wide lens was used with a always hit move (accuracy = -1) it caused the move to have -1 + 5 = 4 accuracy.
Moved the -1 accuracy bypass before applying wide lens.
> Fix Wide Lens

- src/phases.ts
Weather was being randomly rerolled on save load, despite that being loaded from save.
> Stop weather being regenerated on save load

- src/phases.ts
The bug that we fixed with this commit revolved around using charged moves in optimal weather and the text not displaying. For example, if a player used the move Solar Beam when it was Sunny or Harshly Sunny, the Pokemon would bypass the charging turn and use the move immediately. However, when they used this move, there would be no text displayed (i.e. "Bulbasaur used Solar Beam" would not be shown). 
To fix this bug we looked into the ShowMoveText() function in the src/phases.ts file and added logic so that the text would display in the first if statement. This would allow the text box to display moves when the weather is optimal to bypass charging.
QA tests:
OPP_ABILITY_OVERRIDE: Abilities.DROUGHT
MOVE_OVERRIDE: Moves.SOLAR_BEAM
OPP_ABILITY_OVERRIDE: Abilities.DRIZZLE
MOVE_OVERRIDE: …
> Fixed bug where Solar Beam wouldn't display if it was sunny

- src/data/ability.ts
Currently Steam Engine will be triggered by status moves like Rain Dance or Soak when it should only work against attacks
> Fixed Steam Engine activating on all water & fire moves

- src/data/move.ts
Scales from 30% at equal level up to 100% at 0.3x level, similar to the games at level 100. This is linear scaling though as consistent with the previous because we scale way past level 100. Also makes it no longer work on higher leveled targets, same as the games.
Should work.
> Fix OHKO accuracy formula

- src/data/battler-tags.ts
- src/data/move.ts
- src/field/pokemon.ts
Helps balance out dynamax compared to megas by giving them a few of the advantages they had from the games as discussed on the discord. These also apply to eternamax and urshifu's special gigantamax.
> Add dynamax buffs

- src/ui/form-modal-ui-handler.ts
This is a fix for an issue introduced by my last PR : https://github.com/pagefaultgames/pokerogue/pull/244
What happened is that input fields are given a type by their label, either "text" or "password".
That type is given after a check using string.includes and the label of the input.
The difference between those is that "password" type input accepts 64 characters vs 16 for the "text" one.
With my last change introducing localisation in both login and register form, I didn't see that the password input was different because it only checked against the hard coded "Password" string, making inputs impossible to be "password" type in locales where the password input label was changed.
That introduced a breaking change for any non-english locale user with passwords longer than 16 since they …
> Fix password input types for languages other than english

- src/data/pokemon-stat.ts
- src/locales/en/pokemon-stat.ts
- src/locales/es/pokemon-stat.ts
- src/locales/fr/pokemon-stat.ts
- src/locales/it/pokemon-stat.ts
- src/plugins/i18n.ts
I also created files for pokemon stats in other languages using the english stats by default.
For future reference, i've used what we had on gen 1-2-3 for the french shortened stat names, and the last gen for the full ones.
> Implement localisation for pokemon stats & add french locale

- src/data/move.ts
Previously, Triage wouldn't affect Bouncy Bubble, which seems unintentional. This should remedy that.
> Added the triageMove() flag to Bouncy Bubble

- src/data/ability.ts
* Quark Drive was triggering on all terrain instead of just electric terrain
* Moody was not picking random stats every turn. Right now it chooses a pair of stats and those are the only stats it will buff/debuff
* Moody could pick the same stat for buffing and debuffing
* Minor edge case in Moody for when stats are near the cap but I need to do more research and testing it will be easier with the stat change UI update
> Fix Moody and Quark Drive

- src/locales/fr/menu-ui-handler.ts
- Modification of the fr translation for menu-ui-handler in `src/locales/fr/menu-ui-handler.ts`
- Reduction of `MANAGE_DATA` and `LOG_OUT` strings to avoid overflowing the window border
> Before
> After
- Added missing space for `losingProgressionWarning`.
- Inversion of words in `importSlotSelect` and `exportSlotSelect` strings + sentence completion to make it clearer
> Before
> After
> Modification of the fr translation for menu-ui-handler

- src/locales/en/fight-ui-handler.ts
- src/locales/fr/fight-ui-handler.ts
- src/plugins/i18n.ts
- src/ui/battle-message-ui-handler.ts
- src/ui/fight-ui-handler.ts
This is an attempt to modify the layout following a discussion on the Discord, feel free to adjust it if necessary before integrating it 🫶
- Modification of data layout
- Adds `POWER` to visible data
- No longer uses a `command_fight_labels` image, but directly text (_allowing translation by the way_)
- Added i18n
- Creation of `en` and `fr` locales for `fight-ui-handler`
> Modification of the move description window in battle

- src/data/ability.ts
- src/data/arena-tag.ts
- src/data/move.ts
- src/field/pokemon.ts
Tested and functional in the following scenarios:
- Regular damage
- Recoil damage
- Crash damage (i.e. Hi Jump Kick)
- Contact damage (i.e. Rough Skin)
- Entry Hazards
- Aftermath
- Disguise 1/8 recoil damage
It should not work, and does not, in the following scenarios:
- Belly Drum
- Pain Split
- Clangorous Soul/Fillet Away
- Confusion self-damage
It is impossible to trigger in the following scenarios, and so is unimplemented there:
- Burn/Poison
- Other end-of-turn damage (Solar Power, Sandstorm)
It should work for Liquid Ooze damage, but it is impossible to verify this as Liquid Ooze does not currently work.
It is also theoretically implemented for Explosion, but it is currently impossible to survive Explosion even with Reviver Seeds.  If such becomes possible, this should likely work …
> Assurance effect implementation

- src/data/arena-tag.ts
Having Spikes or Stealth Rock on the field when a new wild battle starts no longer crashes the game.
> Fixed entry hazard crash

- src/locales/fr/menu-ui-handler.ts
Captial letter to "Œuf", as it is in the games + "Options" to "Paramètres" being a more situable translation
> Captial letter to "Œuf" + "Options" to "Paramètres"

- src/plugins/i18n.ts
Selects the display language according to the browser language. If this language is not supported, english will be used instead.
> Auto select language implementation

- src/data/battler-tags.ts
Leech seed was checking specifically, but sappy seed was not.
> Make grass types unable to be seeded

- src/data/move.ts
Currently, the game generates a random number from 2 to 3, and pushes the frenzy move to the attacker's move queue _after_ the first hit, meaning these moves actually hit 3-4 times in total. I changed the random number range to 1 to 2, as the first hit should count as one of the 2-3 hits.
> Fix frenzy moves like Outrage lasting 4 turns sometimes

- src/phases.ts
Currently Fake Out will fail after switching out with a move such as U-Turn, Volt Switch or Baton Pass as they enter the field with a turnCount == 1. As Pokemon cannot act on the same turn they are switched in by this method, they are unable to act until their turnCount == 2, meaning Fake Out will always fail. 
This is not the case for hard switches however, as the incoming Pokemon's turnCount is decremented to compensate for this when the switch was caused by `Command.POKEMON`.  This PR extends this to Pokemon switched in with pivoting moves by checking to see if a move with `ForceSwitchOutAttr` was used from the Pokemon's field index on the turn of the switch. 
Additionally, this will greatly simplify the implementation of some other moves and abilities, namely Stakeout and Analytic, …
> Fixed Fake Out + Pivot move interaction

- package-lock.json
- package.json
- src/plugins/i18n.ts
_If you think it's relevant to add (including the fact that the tutorial can be read in the user's default language, for example), I'll let you test on your own that everything's working as it should.
I haven't seen any strange behavior, but you never know..._
- Added `i18next-browser-languagedetector` module to detect the user's browser language
- Added list of supported languages `supportedLngs` in i18n initialization (Filled with languages already fully or partially supported)
- Keeps prLang to override the detected language if necessary
> Add auto detect user language

- src/locales/fr/menu.ts
Updated french translation for new entries in `menu.ts`
Tested locally, works as expected, here is a screenshot :
Regarding "Rankings" translation, it can either be "Classement" or "Classements" (plural). I find singular more accurate, but I'm opened to switch it to plural if you prefer 👍
> feat: added french translation for new entries in menu.ts

- src/data/move.ts
The math on Dire Claw and Tri-Attack is currently incorrect, resulting in vastly higher rates of status effects. These moves make three independent attempts to apply a status effect (each at 50%/20% respectively), leading to Dire Claw having an 87.5% chance to apply a status effect of any kind and Tri-Attack having a 48.8% chance. 
This PR addresses this with a new move attribute `MultiStatusEffectAttr`, which extends `StatusEffectAttr`. The primary difference is that it takes an array of `StatusEffect` and chooses a random one to use for the apply method of `StatusEffectAttr`.
> Fixed Dire Claw & Tri-Attack status chances

- src/locales/de/menu.ts
- src/locales/en/menu.ts
- src/locales/es/menu.ts
- src/locales/fr/menu.ts
- src/locales/it/menu.ts
- src/ui/daily-run-scoreboard.ts
After checking the last changes from #360  were deployed, I noticed an issue with the wording : we had "Daily Classement" instead of "Classement du Jour". 
I digged a bit in the code and found out the translation for `menu:dailyRankings` I put was only used as a placeholder while loading the data. As I couldn't test locally with an API to simulate, I didn't notice the issue until it was on prod, mb.
I changed the logic to make it more accurate : 
- Put `menu:loading` instead of `menu:dailyRankings` as placeholder while loading data from API
- Removed obsolete `menu:rankings` translation
- Added dedicated `menu:weeklyRankings` translation
Tested in all 5 languages to make sure there is no regression. Here are screenshots of the 3 possible states in french (I tested by manually set `DAILY` …
> fix: reworked daily and weekly rankings translations workflow

- src/ui/stats-container.ts
Change to the pokemon stats chart so that the stats are arranged as in the mainline games. I hope you find this useful
> Change pokemon stats chart

- src/data/move.ts
Moves that deal half of a target's HP were not able to deal damage if the target had 1 HP. Used Math.max to ensure 1 is the lowest this value ever evaluates to.
Fixes this issue: https://discord.com/channels/1125469663833370665/1235351188455555092
> Fixed Rounding Error For TargetHalfHpDamageAttr

- src/battle-scene.ts
- src/main.ts
- src/phases.ts
- src/ui/daily-run-scoreboard.ts
- src/ui/title-ui-handler.ts
DO NOT MERGE WITHOUT READING DOWNSIDES
Casual users lacked the data to catch severe bugs in the moment (ex. black screen crashes), and by the time they reported the issue they had already refreshed or left the page. This leads to low signal for difficult to reproduce issues.
Globally uncaught errors or rejected promises (i.e. anything that is not explicitly handled) results in an alert popping up on the user's screen, notifying them of the error and requesting that they open the console to see details. The hope is that this will motivate users to share the error w/ developers so that further debugging is possible.
Also explicitly catches a few places that rely on uncaught API calls to avoid errors propagating.
Ideally, these alerts would trigger a crash report to be sent directly back to …
> Catch global errors and rejected promises and display them in an alert box.

- src/field/pokemon.ts
Shedinja wasn't taking the luck value from Ninjask so when it calculated its luck it just took the entire fused Pokemon's luck somehow. This has been fixed so it takes both the first and second part of the fusion's luck values instead.
Also fixes an issue where Shedinja crashed the game if it was the second part of a fusion combo. Now the correct pokemon species gets checked against and the correct pokemon evolution occurs to create Shedinja.
Nincada by itself
https://github.com/pagefaultgames/pokerogue/assets/13838608/23ce1373-2e27-4229-af3f-851b064da370
Nincada as the primary fusion component
https://github.com/pagefaultgames/pokerogue/assets/13838608/707f7063-5785-41d1-854a-eeca6295e64a
Nincada as the secondary fusion component …
> Fix Shedinja Luck and Crash

- src/data/move.ts
Gyro Ball was getting Speed values with getStat instead of getBattleStat, making it so it didn't take enemy speed increases into account, or having a worse synergy with Curse.
Simply changing the called method seems to have fixed it. Tested with two Steelix, one of them having Speed Boost as ability. Before the change, damage never changed over turns, now it does.
> Fix Gyro Ball only checking base stat

- src/field/pokemon.ts
Fixed having Shedinja share PP usage with the Ninjask it evolved from and vice versa.
The solution was to make a deep copy of each move in the moveset array rather than copying the array itself.
https://github.com/pagefaultgames/pokerogue/assets/13838608/6310de7b-5ca3-44e2-9b9f-ecdf1ad65203
> Fix Shedinja PPused Share

- src/data/move.ts
Adds 1.5x power attribute when hitting a target with items. https://pokemondb.net/move/knock-off
Testing: 
Base power is 65 when hitting target with no item 
Base power is 97.5 when hitting target with item 
*I did not add the item removal effect yet
> Add variable power attribute for knock off 

- src/data/move.ts
Proof that Venom Drench is intended to affect Toxic'd targets via Pokemon Showdown:
In game showing both Toxic and Poison working correctly:
https://github.com/pagefaultgames/pokerogue/assets/13838608/9fd08623-dff0-4195-ab9d-2351a5965c80
> Fix Venom Drench not working on Toxic Status

- src/ui/starter-select-ui-handler.ts
Adds text to the starter screen UI which indicates which Form you are currently selecting. This helps with Pokémon who don't have a sprite change for their form because it doesn't affect them until later.
https://github.com/pagefaultgames/pokerogue/assets/13838608/6c87c9dd-6ef5-4e60-bfe6-18d88f68c685
> Add Form Text to Starter UI

- src/locales/fr/battle.ts
Added "de" to "Pokémon" to make this sentence grammatically correct
> Minor Update to French battle.ts

- src/data/move.ts
Implemented Expanding Force with the following new attributes:
- Power is multiplied by 1.5x on Psychic Terrain. (MovePowerMultiplierAttr)
- Target is changed to ALL_NEAR_ENEMIES on Psychic Terrain, otherwise target is NEAR_ENEMY. (VariableTargetAttr)
Created new attribute: VariableTargetAttr
- Code is based on MovePowerMultiplierAttr, a simple function which sets the parameter fed into it as whatever the conditional logic in the move's initialization returns.
Added code in getMoveTargets() to apply VariableTargetAttr to any moves that have one. Should theoretically be applicable to Tera Starstorm with conditional logic as well. Does not appear to interfere with current move logic (all other moves behave as normal and Expanding Force's behavior was tested with and without terrain) but I …
> Implement Expanding Force

- public/manifest.webmanifest
- src/data/status-effect.ts
- src/field/pokemon.ts
- src/phases.ts
- src/utils.ts
Currently, if a fainted Pokemon gets fused with a non-fainted one then the Pokemon becomes fainted. This can cause tons of issues since it reduces your party size and faints that slot. 
This will balance fusions a bit. The resulting HP is now based on the average percentage each Pokemon was at. So a fainted and non-fainted results in a non-fainted pokemon with 50% HP. Two fainted Pokemon still becomes one fainted. Status effects are also inherited. So if one Pokemon was healthy but the other was Burned, the resulting Pokemon is burned. If both have a status, it chooses randomly between them.
Finally, this also adds some extra error messages in the case that a fainted Pokemon gets sent out at the start of a battle. This isn't intended to be able to happen, so the console now better states …
> Prevent Fusing Status Errors

- src/data/terrain.ts
- src/field/arena.ts
- src/phases.ts
Examples, side Aqua Jet, Prankster Bulk Up will now properly work in Psychic Terrain. This is done by making `isMoveTerrainCancelled` take in the target list and checking if any opponents are being targeted. Fixes https://discord.com/channels/1125469663833370665/1236464078898069504
> Psychic Terrain no longer blocks priority moves targeted at the user's side

- src/data/ability.ts
- src/data/move.ts
Add a new (potential) general-purpose attribute, and 2 move-specific ones for Water Shuriken. 
- `ChangeMultiHitTypeAttr` can be extended to be checked before a multi-hit move is processed, if you want its multi-hit type to be conditional. 
- `WaterShurikenMultiHitTypeAttr` checks if you're a Greninja in Ash-Greninja form with the ability Battle Bond (for good measure...), and changes the move's `MultiHitType` to 3 if you are. 
- `WaterShurikenPowerAttr` does the exact same check, and changes the move's power to 20 if you are. 
All of this should make Battle Bond fully implemented, so its `.partial()` tag is removed as part of this as well.
> Implement Water Shuriken Battle Bond condition

- public/manifest.webmanifest
- src/data/status-effect.ts
- src/field/pokemon.ts
- src/phases.ts
- src/utils.ts
**Fixed the issue in double battles. When searching for a non-fainted Pokemon, only looks at array index higher than the current one. Since Pokemon are sent out from index 0-5, this will prevent a softlock. In situations where you only have one non-fainted Pokemon for a double battle, the entire function never gets called anyway.**
https://github.com/pagefaultgames/pokerogue/assets/13838608/4bbc94fd-8475-42b6-8187-6c77e0c62e06
Currently, if a fainted Pokemon gets fused with a non-fainted one then the Pokemon becomes fainted. This can cause tons of issues since it reduces your party size and faints that slot.
This will balance fusions a bit. The resulting HP is now based on the average percentage each Pokemon was at. So a fainted and non-fainted results in a non-fainted pokemon with 50% …
> Prevent Fusion Status Errors +Fix Double Battle Issue

- src/battle-scene.ts
- src/system/settings.ts
Added a new setting to swap the A and B button on controller. Defaults to off which retains the current behavior on live.
> Add Setting to Swap A and B on Gamepad 

- src/data/move.ts
- src/field/arena.ts
Right now arena trap tags are not having their sides checked for application and overlapping. This makes it impossible to have stealth rocks or another arena trap on both sides.  
This change just looks at their side when considering overlapping and applications.
Let me know if I am misunderstanding something!
> have arena tags check their sides.

- src/field/pokemon.ts
Fixed a bug where a Pokemon would be stuck in a semi-vulnerable state when falling asleep in that state.
Trello: https://trello.com/c/8Lkse4ot
Video: https://capture.dropbox.com/fGtfs63XNvQvoBaX
This is my first time contributing to any open source project so please look it over and let me know if there's anything I missed or anything you want changed.
> Fix Pokemon stuck in semi-vulnerable state after Yawn

- src/phases.ts
Previously, changing 2 stats would display as "Sprigatito's Attack, and Sp. Atk rose!". This isn't proper grammar, as there shouldn't be a comma if there's only 2 subjects. This adds a check so the comma won't show up if there's only 2 stats; so it'll write "Sprigatito's Attack and Sp. Atk rose!", but also "Sprigatito's Attack, Sp. Atk, and Speed rose!"
> Stat change comma fix

- src/locales/es/battle.ts
- src/locales/it/battle.ts
Fixes a small typo when learning a tm. The incorrect escape character was being used and no escape character was being used for Spanish.
> Small Typo when Learning a TM

- src/inputs-controller.ts
Fix for:
https://discord.com/channels/1125469663833370665/1236692838973181992/1236692838973181992
the player.mapping variable should be initialized when a controller is connected or when a controller is already connected.
and then, inputs from gamepad and keyboard are listened and use this variable (this.player.mapping) to know which action need to be done.
For some reason, for some players, the gamepad and keyboard is listened before this variable is initialized.
So i set a condition to check if this variable is initialized before trying to know which action need to be done.
> Fix - Black screen on input for some players

- src/data/move.ts
Condition was unneeded, and caused the move to erroneously fail if the pokemon did not have a status condition.
> Fix take heart

- src/data/move.ts
* Gen 8 curse is always a random opponent target
* Curse recoil damage will always be at least 1 as Shedinja will faint upon using it
* Curse ignores substitute and protect like moves *except* crafty shield but substitute and crafty shield are still (N) right now
> Implement curse

- src/data/move.ts
- src/phases.ts
Mind Blown targets all users and was triggering recoil every time it hit. Changed so that it only applies once after all targets take damage by adding a new MoveEffectTrigger, POST_TARGET. This also fixes an issue where dying to recoil stopped the rest of the damage from hitting the remaining targets.
This change also applies fixes for Steel Beam since they are have the same effect but is single target.
Also added missing messages for Damp and Recoil. All messaging is in line with Pokémon Showdown.
https://github.com/pagefaultgames/pokerogue/assets/13838608/6b7e8d34-03f1-42fa-acb0-0a4fd1ecadce
https://github.com/pagefaultgames/pokerogue/assets/13838608/5b6a4c08-9d4b-44aa-9302-0481cc6521e5
https://github.com/pagefaultgames/pokerogue/assets/13838608/7a566ddc-4065-4051-9a79-1d431812599f …
> Fix HalfSacrificialAttr

- src/data/move.ts
Curse currently uses the gen 7 implementation that always selects a random target. This change adds targeting back to curse as of gen 9. Downside is that non ghost type users have to do another input with the way targeting works right now.
Also ignoring the edge case of using curse on an ally targeting a random enemy because that is utterly incomprehensible and instead uses the older generation version where you can still curse allies.
> Make curse target

- src/data/ability.ts
- src/data/battler-tags.ts
- src/field/pokemon.ts
Previously Protosynthesis and Quark Drive were pretty much (N) abilities, because the tag was not checked in stat calculation, thus causing them to not have any effect, even when they were active.
Secondly, the checking of the highest stat was slightly wrong, causing the tag to boost wrong stat sometimes (especially spdef and speed) because the function was adding into the test value instead of overriding it.
> Fix Protosynthesis and Quark Drive

- src/data/berry.ts
If a pokemon has a status effect and is confused, when it consumes a lum berry it should cure the status effect and confusion. 
https://github.com/pagefaultgames/pokerogue/assets/13306707/ca3c205b-c523-483d-8830-a785e211e6d2
Reported here and I checked on showdown that this is correct: 
https://discord.com/channels/1125469663833370665/1236613326599884820
> Lum berry should cure status and confusion if possible

- src/data/ability.ts
Resolves this issue: https://github.com/pagefaultgames/pokerogue/issues/535
I tested that hunger switch doesn't activate while terastallized and that when the tera shard wears off it starts working again. I also checked the showdown abilities and didn't see any other ones that are fully disabled when you tera.
> Hunger switch shouldn't trigger if terastallized

- src/utils.test.ts
Added Unit test for `padInt` function
How to Test:
- In root, run `npm run test`
> add unit test for util function padInt

- src/modifier/modifier-type.ts
QOL enhancement to show the user how many of the selected Pokeball they have while in the rewards phase.
> Show number of Pokeballs in inventory when selecting a pokeball in the reward phase

- src/data/move.ts
This PR implements hazard removal via Rapid Spin, Defog, Tidy Up, and Mortal Spin. Logic is mostly copied over from screens removal logic. PR does not address Court Change.
I'm having a hard time building this, so if someone could test it out that would be great, but the logic seems to check out.
> add hazard removal for Rapid Spin, Defog, Tidy Up, Mortal Spin

- src/data/ability.ts
- src/field/pokemon.ts
Currently just Intrepid Sword and Dauntless Shield, but this supports easily adding the condition to additional abilities in the future that might warrant it such as disguise.
> Implement once per battle restriction on abilities

- src/modifier/modifier-type.ts
Revives were incorrectly capping their max weight at 3, making them rarer than max revives.
> Fix revive weight cap

- src/data/ability.ts
- src/data/enums/abilities.ts
- src/data/move.ts
Added a new MoveFlags flag 'RECKLESS_MOVE' to make crash and recoil moves in line with other move flag boosting attacks.
Modified how flags were defined so they are easier to maintain.
Added the appropriate flag to all mvoes listed as being affected by Reckless. Steel Beam, Mind Blown, and Struggle do not count according to [source](https://bulbapedia.bulbagarden.net/wiki/Reckless_(Ability)).
https://github.com/pagefaultgames/pokerogue/assets/13838608/e7075cc1-873e-4191-9764-b1a75bbe05ce
https://github.com/pagefaultgames/pokerogue/assets/13838608/574df8d8-e77c-470b-8cc7-643db1293c13
> Fixed Crash Moves and Reckless

- src/data/move.ts
Flare Blitz had the `failOnGravityCondition`, which makes the move fail under Gravity, which isn't accurate to game functionality and doesn't really make any sense.
> Fix Flare Blitz in Gravity

- src/system/settings.ts
In Game Settings, proposal to give languages the names they have in their respective languages, as it is in recent games :
(screenshot from Scarlet and Violet)
> Names of the languages in their respectives languages

- src/data/move.ts
- Changed burning bulwark to be a self status move, in line with other protection moves.
- Added missing sound based flag to alluring voice.
> Small fixes to burning bulwark and alluring voice

- src/field/pokemon.ts
- src/phases.ts
Fixed an issue where if a move failed, it would not use Power Points. This caused soft locks in Endless for some pokemon that could only use moves on the user that failed.
Taking a look at the code, there was no solution I could find that didn't involve adding in some way to differentiate a canceled move from a failed one. Canceled moves don't use PP and there were a lot of reasons why this may happen. Most of them I could account for. That is, except for Truant. There was no simple way to determine if the cause for canceling the move was Truant. At that point it was less destructive to simply add a way to mark a move as failed.
With that said, I added the appropriate property and method to match the 'cancel' method though it isn't used outside of this instance at the moment. Move which …
> Fixed Failed Moves Not Using PP

- src/utils.ts
Apparently when you're loading files from the filesystem, window.location.hostname is an empty string rather than localhost. This PR changes it to also check for empty strings so that offline features like importing properly work in my app.
> Fix offline mode imports in the app

- src/ui/battle-info.ts
This change will update the relative position of the Tera, Splice, and Shiny icons when the Name or Tera Type updates. Fixes #618
> Update spacing of icons upon Name/Tera update

- src/data/move.ts
- src/field/pokemon.ts
1. Charge accidentally had the `failOnOverlap` field as true instead of false which meant you would not gain the special defense boost if you were already charged
2. The charged status was incorrectly trying to be removed on the attacked Pokemon instead of the attacker
> Fix charge

- src/data/battler-tags.ts
- src/field/pokemon.ts
- src/system/pokemon-data.ts
Also saves the rest of the summonData except for transform specific things.
Since this modifies how saving and loading data works someone other than just me should really make sure to test this before it's merged, we 100% do not want this to break in prod. My tests all seemed to work fine, but just to be sure.
> Save battler tags

- src/data/move.ts
We never actually set these to not be choosable with metronome whoops.
> Make max and z moves unable to be chosen with metronome

- src/field/trainer.ts
Difficult to test, but as far as I can tell this is safe. Fixes this longstanding bug by just forcing doubles trainers to have at least two pokemon.
> Prevent doubles trainers generating with one pokemon

- src/data/ability.ts
Tested behavior in Showdown. Water Compaction is not intended to work on any water-type status moves (i.e. Soak, Life Dew, etc.)
> Fix Water Compaction Triggering on Status Moves

- src/data/battler-tags.ts
Weren't loading the multiplier causing weird behavior with them.
> Fix loading protosynthesis/quark drive boosts

- src/locales/de/fight-ui-handler.ts
- src/locales/en/fight-ui-handler.ts
- src/locales/es/fight-ui-handler.ts
- src/locales/fr/fight-ui-handler.ts
- src/locales/it/fight-ui-handler.ts
- src/locales/zh_CN/fight-ui-handler.ts
- src/ui/fight-ui-handler.ts
- src/ui/text.ts
- Adds `accuracy` to the move information in the fight ui
> In a safer way for translations, compared to what was proposed in #702
- Add new locales field `accuracy` in fight-ui-handler with default english value for translation
- Capitalize `accuracy` & `power` fields
> Adds 'accuracy' to the move information in the fight ui

- src/phases.ts
people were saying the level up notification was slower than the normal setting, and of course, i forgot to remove a divider in the speed.
> Level up notification speed up

- src/battle-scene.ts
- src/phases.ts
Sam accidentally added the rich presence support into his main Nuzlocke mode commit so it couldn't easily be cherry-picked over to the main branch. This PR is just those changes and nothing more.
Presumably merging this would mean having to go delete those changes from the Nuzlocke branch, so if this too troublesome or something feel free to close the request; it might be useful for Sam anyways seeing everywhere the code is used.
> Add Nuzlocke Mode's rich presence support to live

- src/data/ability.ts
- src/data/move.ts
- src/overrides.ts
- src/phases.ts
This pull request adds the functionality of ignoring redirects to the move Snipe Shot, and the abilities Propeller Tail and Stalwart. Currently, the only things that can redirect a move, are the abilities Storm Drain and Lightning Rod. If more ways to do so get implemented in the future, these moves and abilities may need to be tweaked further.
> Implement Snipe Shot, and Propeller Tail/Stalwart

- src/data/move.ts
Based on #705 , Tidy Up was only cleaning up hazards on opponents side of the field. This change makes it so hazards are removed on both sides of the field now.
https://github.com/pagefaultgames/pokerogue/assets/85713900/bff81162-40c6-41b2-945a-2fea5e0188d3
> Bugfix: Tidy Up removes hazards from both sides now

- src/field/pokemon.ts
Pokemon with very limited movepools and no damaging moves could sometimes generate with no moves.
> Stop pokemon generating with no moves

- src/field/pokemon.ts
- src/phases.ts
Fixed a long standing issue where two turn charge moves could be paused by status or Truant causing some infinite sequences if not careful.
Also fixes a minor dev issue where moves set by overrides didn't use PP.
https://github.com/pagefaultgames/pokerogue/assets/13838608/7a897730-3b6c-419e-81c6-a8e59bf49665
https://github.com/pagefaultgames/pokerogue/assets/13838608/37c18fcb-7a1c-450e-8759-101074fb0641
https://github.com/pagefaultgames/pokerogue/assets/13838608/b4c61d65-473c-4e6b-aa52-a48da42145a0
> Fix Charge Move Infinites

- src/data/exp.ts
Was scaling with square of level, not cube.
> Fix fluctuating xp curve

- src/data/exp.ts
People were complaining the new formula where it actually has its own curve was too high. You'd need about 25% more exp than medium-fast by level 200. This lowers that to about 14%.
> Lowers xp curve for fluctuating slightly

- src/field/pokemon.ts
We were accidentally using the base pokemon's variant when getting the fused species icon.
> Fix fusion icon variant id

- src/data/move.ts
When using Life Dew, pokemons that use Protect should still be healed from Life Dew coming from an ally.
As per https://bulbapedia.bulbagarden.net/wiki/Life_Dew_(move)
> Add ignoresProtect to Life Dew

- src/field/pokemon.ts
If the pokemon species and form is the same as the second fusion component, then skip the logic to make a fused cry and just use the cry of the primary component. Previously a pokemon spliced with another of the same species and form would not have a cry and would log an error to the console.
Tested with various combinations of pokemon and their mega/gigantamax forms, but _not_ tested with other kinds of forms, like rotom or alcremie.
> Fix cry when pokemon is fused with its own species and form

- src/ui/starter-select-ui-handler.ts
Fixes https://github.com/pagefaultgames/pokerogue/issues/733
Fixes an issue where egg moves could get duplicated onto a starter Pokémon's moveset.
> Fix Duplicate Egg Moves

- src/data/ability.ts
- src/phases.ts
Reusing a lot of code from Aftermath and `PostFaintContactDamageAbAttr`. Passing in lastAttack.damage into the unused `args[]` of `applyPostFaintAbAttrs` since that value is capped by the HP of the fainted Pokemon at the time.
Not sure about the message, but the for aftermath is pretty descriptive so I also reused that.
> Implement innards out

- src/utils.ts
Mixed use of UTC and non-UTC time methods was causing inconsistent results based on time zone.
> Fix getSunday function

- src/data/ability.ts
* Set flinch chance to 100%
* Verified status moves (smokescreen) would trigger flinch
* Verified damage moves (tackle) would trigger flinch
* Made code change
* Verified status moves no longer trigger flinch while damage moves still do
* Set flinch chance back to 10%
> Stench should not trigger on status moves

- src/data/move.ts
- Created a new attribute for boosted healing. It applies a different healing rate if a certain condition is met.
- Implemented floral healing with this attribute. It applies a 2/3 healing ratio if the terrain is grassy, 0.5 if it's not.
> Fully implemented floral healing

- src/data/ability.ts
Went off of the showdown description of "This Pokemon does not take damage from attacks made by its allies."
Wasn't sure if this meant that they were completely immune to the damaging moves, or if they just hit them with 0 damage. Anyone know which it is? This currently just makes them immune to the move as it stands.
Tested and verified to work for both the player side and enemy side with this setup.
> Implements telepathy

- src/data/ability.ts
- src/field/pokemon.ts
Updated Description: Some variable power moves like magnitude and dragon energy were not getting boosted by tinted lens. This PR adds a new class for abilities that boost the damage of moves rather than the base power (currently this appears to just be tinted lens). 
Testing: 
- Magnitude does double damage on a not very effective target when attacker has tinted lens 
- Magnitude does normal damage on a not very effective target when attacker does not have tinted lens 
- Neutral damage move does same damage with/without tinted lens
> Fixes some variable damage moves not working with tinted lens

- src/data/ability.ts
https://trello.com/c/ettVQoKh/66-power-construct-zygarde-reverting-back-to-original-form-mid-battle
Config for reproducing the original bug and testing the fix (overrides.ts file) attached
[reprobug.txt](https://github.com/pagefaultgames/pokerogue/files/15287151/reprobug.txt)
> Fix Zygarge Complete form changing back into 50%

- src/modifier/modifier.ts
This PR prevents item type power boosts from being applied, if base power is less than 1. (For example, when you hit a disguise with multi-lens).
Because the value is Math.floored, applying the boost will cause the move to do no damage at all.
This is Disguise not breaking against Magnet + Multi-Lens Thunderbolt before the fix
https://github.com/pagefaultgames/pokerogue/assets/73663099/986e12d7-2cfe-4f7e-bd1a-ef71b2e8d5c2
The Disguise not breaking bug does not happen with Multi-Lens and no Magnet before the fix
https://github.com/pagefaultgames/pokerogue/assets/73663099/38b63bb9-048e-473b-b339-2794fba9df05
The Disguise breaks properly with Magnets equipped after the fix
https://github.com/pagefaultgames/pokerogue/assets/73663099/9fcdd8cc-85bc-4723-9525-af491a61b0b2
> Prevent applying item boosts when power is <1

- src/modifier/modifier-type.ts
Modifies changes from #636 for compatibility with pokemon with alternate forms that also use evolution items. E.g. sinistea, poltchageist. The alternate forms are treated as formIndex 1 so getFormKey() and comparing against GIGANTAMAX seems more appropriate, see #839.
Since there are no other cases i.e. megas are always final form, eternamax, primal, origin, gignatamax single/rapid all are very limited and only apply to legendaries / one pokemon that don't use evo items I think it's safe to only check GIGANTAMAX (I double checked).
See #839 for main behaviour (antique form can't evolve with chipped pot it just says it will have no effect).
Previous pull changes still working i.e. thunder stone won't apply for g-max pikachu and g-max pikachu fused with other pokemon.
Thunder stone will …
> Evolution item check for g-max form instead of alternate forms (allows sinistea antique form to evolve)

- src/data/egg.ts
- src/utils.ts
Modifies the functionality of the legendary gacha banner to be evenly split between all possible legends, as opposed to a 64 length cycle. This works by creating super cycles where it goes through a shuffled list exactly once before reshuffling and restarting, so it is still random, but each 25 week cycle will always contain every legend exactly once.
Due to the limited seed space this is still technically going to loop, but instead of looping every 64 banners it will loop every 1638400 banners, or specifically every 65536 super cycles which seems more than sufficient.
This is probably retroactive to any eggs anyone currently has but hasn't hatched, but so was the change earlier today to the banner so I'm not sure that's a high concern.
> Modify legend gacha to be even split

- src/data/move.ts
- src/field/pokemon.ts
Gen VII added two things to sheer cold:
- _Ice-type Pokémon are now immune to Sheer Cold._
- _Additionally, the move's base chance of hitting is only 20% if the user is not an Ice-type Pokémon._
I tested it with increased accuracy for the ice immunity. 
I also split the attributes into two, one for accuracy and one for Ice immunity.
https://bulbapedia.bulbagarden.net/wiki/Sheer_Cold_(move)
> Implented Gen VII Sheer Cold Changes

- index.html
Very minor ordering change - just to prevent "é" not being shown correctly for some people
> meta charset should be ordered before any elements containing text

- src/data/daily-run.ts
- src/phases.ts
- src/system/game-data.ts
Rewrote #799 and #808.
Fixes #828 and #791 for example.
- Added Daily run's to offline mode (seed generated based on Date).
- Fixed the freeze that was caused by calling api "savedata/newclear" when offline.
- Implemented a local validation of daily runs to keep the once per day reward.
It's all commented to make things clear
> offline mode - adds daily run and fixes clear freezes

- src/data/biomes.ts
Replacing Cave's Beach link with Lake would weaken the "water loop", a situation where players get continually routed back to Beach, leading to frustration. Lake is a crossroads biome that connects to much of the rest of the game, while still connecting to Beach, making it not a drastic detour.
Infernal Vulpix simulated a hypothetical 10k wave endless run for me to see the difference this change would have on biome frequencies. Odds is old odds, Alt is odds with the link changed to Lake:
```
Odds      Alt
Abyss              1.98%     2.40%
Badlands           3.57%     3.46%
Beach              6.30%     4.06%
Cave               5.87%     5.91%
Construction Site  3.90%     4.83%
Desert             1.70%     1.70%
Dojo               2.05%     2.58%
Factory            2.03%     2.57%
Fairy …
```
> Cave's Beach link changed to Lake

- src/data/ability.ts
Accidentally discarded my [previous commit](https://github.com/pagefaultgames/pokerogue/pull/818), reopening with Xavion's changes.
Status abilities ( Limber, Insomnia, Immunity, Magma Armour, Water Veil, Vital Spirit, Leaf Guard, Sweet Veil, Water Bubble, Pastel Veil, Thermal Exchange, Purifying Salt ) will now show on the left ability/passive pane when they successfully immune a status, and correctly send their chat box message. [Example](https://imgur.com/aJ5aMSj)
The change in the applyPreSetStatusAbAttrs removes the !simulated arg so that the message doesn't get suppressed by .attr.
The change in getTriggerMessage is because after getting the trigger message to actually show, turns out it never worked and just produced undefined. Instead it accesses the immuneEffects array.
One bug …
> Fixes status immunity abilities not showing on UI

- src/locales/de/battle.ts
I started to notice that, you can escape from some Pokemon Battles. Therefore saying that it is impossible _(which it currently does)_ is wrong.
The reason why I translated it like so, is because the original string says, that you _can't_ escape. Which is wrong.
The original Pokemon game says, ``BTL_STRID_STD_EscapeFail``
> You couldn’t get away!
And the corresponding German Translation to it is.
> Flucht gescheitert!
&nbsp;
**The current English one is from** ``BTL_STRID_STD_EscapeProhibit``, but since you **can** escape. "Prohibit" is wrong.
&nbsp;
I could put the Localization Dump from Pokemon Scarlet and Violet on a GitHub repository, it's just the question whether Pokemon and affiliated companies care whether that data is on a GitHub repository or not.
&nbsp;
I do **suggest** …
> DE Correct a translation due to misleading token and source string

- src/field/arena.ts
getTypeForBiome was missing jungle, construction site, and lab which caused crashes. Added those in and also a default failsafe.
> Add missing biomes for camoflauge

- src/data/trainer-config.ts
- src/field/pokemon.ts
This also fixes the weighting to account for the adjusted level ranges because that was mostly destroyed by the level changes.
This also allows the moveset code to know when it's generating for a boss, and prevents rare eggs on bosses. This is done by just regenerating the moveset for a boss after it's marked as a boss.
> Limit rare eggs to e4+

- src/system/settings.ts
Resolves enhancement #810 
EDIT:
If device is not a mobile device and you'd disable the touch controls, it will center the game window.
- this will be ideal for those playing with tablets along with external controller, and handheld devices like steam deck and the likes
- this will technically not matter on large screen devices like laptops and pc, since height of the game window will fill the screen as much as possible keeping the aspect ratio
- we only want this to happen on landscape orientation
If device is mobile device, this will retain the existing behavior- the window should be at the top of the screen.
**MOBILE DEVICES**
- PORTRAIT
- LANDSCAPE
**NON-MOBILE DEVICES**
- With touchscreen capability (please note in screenrecording, it is set to Desktop (touch) to simulate tablet or …
> Automatically center window vertically when playing on landscape

- src/modifier/modifier-type.ts
Recently, I noticed that potions would still appear in the loot pool after battles even if there were no Pokémon that could be healed by them. This seems to be because the current logic for offering potions only checks if Pokémon have low hp, and does not check if they are fainted. This implements a simple check in healing items to make sure that the healing candidates are also not fainted, so that you can't be offered potions because of a fainted Pokémon.
> Fix potions still appearing in loot pool when potion targets have fainted

- src/modifier/modifier-type.ts
Fix the issue where ‘TerastallizeModifierType’ uses the wrong translation key.
> Fix ‘TerastallizeModifierType’ uses the wrong translation key

- src/data/move.ts
Seed flare is supposed to lower the target's Special Defense stat by two stages, but only lowers by one right now. 
https://bulbapedia.bulbagarden.net/wiki/Seed_Flare_(move)
> Change seed flare stat drop to 2 stages

- src/phases.ts
Fixed an issue where targeting the user of a  Semi-Invulnerable move caused the move to cancel. These moves now miss instead.
Fixed an issue where if two users target each other with semi-invulnerable moves, the slower user fails.
No Guard and other accuracy locking moves still function as they were already duplicating their check in hitCheck. Fixed an issue where IGNORE_ACCURACY was checking against the current move for targets instead of Lock-On's target
https://github.com/pagefaultgames/pokerogue/assets/13838608/026d47c0-b9fc-44d7-bf18-1c3aedac219b
https://github.com/pagefaultgames/pokerogue/assets/13838608/ec0d93f7-d25e-43b5-8613-dcb4c4dd4cba
https://github.com/pagefaultgames/pokerogue/assets/13838608/3d7ed2f4-d097-4d90-821f-2c902bdd4da6
> Semi-Invulnerable Hit Checks Count as Miss

- src/locales/fr/pokemon-stat.ts
Added dots after "Atq. Spé." and "Déf. Spé." , as it is in Scarlet and Violet
> Minor Adjustment to French pokemon-stat.ts

- src/data/weather.ts
Implements a fix for #972 
Uses an existing function `getPokemonPrefix()` to determine if 'Wild', 'Foe', or '' is used for the prefix, however the prefix itself is not translated in this existing function, so there is potential for improvement there.
> Use localization for damaging weather messages

- src/ui/battle-info.ts
Issue [here](https://github.com/pagefaultgames/pokerogue/issues/883)
Normally a Pokemon has their hidden ability as abilityIndex 2. However Pokemon with only 1 ability have their hidden ability with abilityIndex 1 instead of 2. This causes a problem when trying to compare the Pokemon's abilityIndex with the starter's abilityAttr where the hidden ability is stored as 4, causing a dark tinted Pokeball to appear even if the player owns the hidden ability.
I added a check so that if a Pokemon only has 1 ability has a hidden ability then it will be treated as being 2 instead of 1. I also went through and renamed some variables to hopefully make the logic a lot more clear and readable.
[Before fix](https://cdn.discordapp.com/attachments/1240069508127789117/1240070681236865155/image.png?ex=664539 …
> Fix tinted caught icon false positive

- src/phases.ts
For whatever reason, this code was changed as a part of the endings commit, and without it, it seems to cause daily runs to freeze at the end.
> Fix daily run freeze

- src/modifier/modifier-type.ts
Implements a fix for #900 
Ether and similar items were improperly checking moves' base PP instead of total PP after accounting for PP Up
> Update ETHER and similar items to use total max PP instead of base PP

- src/data/battler-tags.ts
Ingrain can only be used by Trevenant and Phantump because they are hardcoded. This move should be useable by all Ghost types.
Since we have Splicing, technically any pokemon can learn any move.
Sets Class TrappedTag, method canAdd back to the original of checking if pokemon is not trapped and not ghost instead of having an override for two specific pokemon
Adds method override canAdd to the IngrainTag and it just checks if the pokemon is already trapped since it should be applicable to any pokemon regardless of type.
This does not trap ghost types when they use ingrain. 
PR #998 already added a check to switching pokemon if the trapped tag is applied by move Ingrain and the pokemon switching is ghost.
> Move Ingrain Fix For All Ghosts

- src/field/trainer.ts
Updated the check in place when attempting to play a trainer sprite. Separated it into a separate function to reduce reusing code and to make it easier to exit early when failures occur.
> Updated Logic when Animating Trainer Sprites

- src/data/move.ts
This PR fixes sparkly swirl not curing the status of the party discovered in [#bug-report-chat](https://discord.com/channels/1125469663833370665/1125894949020381285/1241099819078914180)
per [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Sparkly_Swirl_(move))
> Sparkly Swirl deals damage and cures the user, all Pokémon in the user's party, and the user's allies, of all non-volatile status conditions (sleep, poison, paralysis, freeze, and burn). 
Using #238  as a reference, it seems the move is just missing the `.target(MoveTarget.PARTY),` line
Notice that after using Sparkly Swirl, Eevee is still paralyzed.
https://github.com/pagefaultgames/pokerogue/assets/146129103/7cc1083f-3f8c-4f6c-a9b7-7c163c6c77a3
After using Sparkly Swirl, Eevee and her party are no longer paralyzed. …
> Fix Move Sparkly Swirl Cure Status

- src/data/move.ts
- src/phases.ts
Made Entry Hazards bypass the accuracy check as they cannot miss a target. There's still one more bug to fix with this but it requires way more code changes. This change needed to be done anyway, so I'm getting it out first.
https://github.com/pagefaultgames/pokerogue/assets/13838608/96c02cf7-fd6f-4066-9a45-1397469d9d8d
https://github.com/pagefaultgames/pokerogue/assets/13838608/b4109773-d443-4def-b743-0e8af4aa4f69
https://github.com/pagefaultgames/pokerogue/assets/13838608/e441dc1b-4a24-4023-8c36-2f29b5bf1358
> Fix Entry Hazard Miss

- src/data/battler-tags.ts
Changed from 1/2 to 1/3, as games after gen 5 use this value
https://bulbapedia.bulbagarden.net/wiki/Confusion_(status_condition)
> Update confuse chance to modern value (1/3 instead of 1/2)

- src/field/pokemon.ts
Fixes an issue where a missing sprite will cause the game to crash instead of using the base sprite or the Substitute sprite.
Failsafes were already in place to load these backups, this code just allows a graceful fail and a simple error message instead of a crash.
https://github.com/pagefaultgames/pokerogue/assets/13838608/bff8fd6c-7781-49b4-a36d-4d85deb62d7f
https://github.com/pagefaultgames/pokerogue/assets/13838608/b3eb8480-1368-4282-9b45-01f94dd4b4df
> Fix Crashes when Sprites for Pokémon are missing

- src/ui/starter-select-ui-handler.ts
Font resize for French in starterInfoTextSize
- To restore an acceptable space between "Nature :" and the name of the nature
- Avoid the closing parenthesis of Nature effects being a bit off borders in some cases
**Before :**
**After :**
> Font resize for French in starterInfoTextSize

- src/data/move.ts
LMK if you want me to move this condition to its own function since it's not super readable but it's like this for sucker punch so I figured it's probably fine. 
https://pokemon.fandom.com/wiki/Upper_Hand
Testing: 
- Attacks & flinches if target chose a priority attacking move and hasn't moved yet  
- Fails if target chose a non-priority attacking move 
- Fails if target chose a priority status move
*Known issue- Upper hand currently fails if the target is using a non-priority move but the priority is increased due to an ability. I didn't see a good way to fix that so added a TODO for now.
> Implements upper hand (mostly) 

- src/data/ability.ts
- src/phases.ts
@Piefrenzy in Discord
Originally reported in Discord Bug Reports channel, Ghost type Pokemon were being trapped by Shadow Tag as well as moves like Fire Spin/Whirlpool/etc. despite documentation saying [trapping abilities](https://bulbapedia.bulbagarden.net/wiki/Ghost_(type)#Interacting_with_the_Ghost_type) shouldn't work and [trapping moves](https://bulbapedia.bulbagarden.net/wiki/Fire_Spin_(move)#Generation_VI_onwards) shouldn't work.
The function didn't even take in the Pokemon trying to switch/run in the first place, so it now gets passed in and checked to see if it's a Ghost type.
Here is a Ghost type swapping through Shadow Tag and a non-Ghost type getting stuck:
https://github.com/pagefaultgames/pokerogue/assets/85713900/d017534b-fd46-45f5-ae0c-d3d5ca22e414
Ghost type successfully …
> Bugfix - Ghost types are no longer trapped by abilities like Shadow Tag or moves like Fire Spin

- src/ui/summary-ui-handler.ts
This PR resolves https://github.com/pagefaultgames/pokerogue/issues/548, and introduces the ability to view the Pokemon Status screen when learning moves. Previously, the user could only view the stats and moves screens when learning moves. 
**When learning a new move via leveling up:**
https://github.com/pagefaultgames/pokerogue/assets/59787978/b8c07d9c-f209-43bd-ba24-5304da1e3bb4
**When learning a new move via TM:**
https://github.com/pagefaultgames/pokerogue/assets/59787978/5c91ea90-7f67-423a-86c0-cf5dc8aa0561
> Add capability to view Pokemon Status screen when learning moves

- src/data/move.ts
Added a new MoveTarget type, MoveTarget.CURSE especifically for the move, so that it only makes you choose target if you are a ghost type (or tera into ghost). I don't believe many moves with variable targeting will be added so I think it's okay to fix it like this.
This should fix the bugs related to this move, such as the ones mentioned in issues https://github.com/pagefaultgames/pokerogue/issues/537 and https://github.com/pagefaultgames/pokerogue/issues/779
> Fix Curse targeting for non ghost types

- src/system/settings.ts
Fixes #832 
The check for the sound effect can be found in _src/ui/abstact-option-select-ui-handler.ts_:
```
if (option.handler()) {
if (!option.keepOpen)
this.clear();
playSound = !option.overrideSound;
} else
ui.playError();
```
Since `changeLocaleHandler()` does not return anything (undefined), it will always resolve to the else statement.
Fix:
- Add boolean return value from changing locale handler
> Fix the error sound effect when changing language

- src/data/move.ts
- src/field/pokemon.ts
As #1048 highlighted recoil damage isn't calculated correctly. Currently the recoil damage is a certain % of the total damage the user has dealt during the entire turn, so when recoil is activated within the same turn in which damage was already dealt then recoil damage is higher than expected. This change makes it so that recoil damage takes only into account the damage dealt by the recoil move.
> Calculate recoil damage correctly

- src/ui/daily-run-scoreboard.ts
Fixes #933 
Currently, there is no flag to prevent sending multiple requests on the scoreboard. This means users can spam Next/Previous button, resulting to simultaneous requests.
- Added `isUpdating` flag to disable buttons and at the same time prevent requesting from the relevant APIs.
Tested locally only thru frontend simulation for the GET requests, if anyone can verify this on a working server, a comment of such would be highly appreciated.
> Prevent spamming of requests when going over scoreboard pages

- src/modifier/modifier-type.ts
- src/modifier/modifier.ts
- src/system/game-data.ts
The EXP Balance item is not currently functioning as a useful item. This reduces the item's Max Stack Count temporarily until a better solution can be found. Saves with this item will have them reduces to a max of 2 and shops will no longer carry them once you reach this value.
https://github.com/pagefaultgames/pokerogue/assets/13838608/af4b8ffe-1477-432e-8087-71cfc423e18e
https://github.com/pagefaultgames/pokerogue/assets/13838608/116b0094-d7ee-43dd-b410-0cacd4df0ead
> Reduce EXP Balance

- src/phases.ts
- src/ui/confirm-ui-handler.ts
- src/ui/pokemon-info-container.ts
Prevents the yes/no confirm menu from getting in the way when the Pokemon Info screen is open when catching a new Pokemon with a full party. Maybe subjective whether or not this is improved but I think it's nicer this way since you can actually read the ability and nature completely.
Before:
https://github.com/pagefaultgames/pokerogue/assets/9343160/97e62850-970f-4a99-8a40-c73ce9439bbf
After:
https://github.com/pagefaultgames/pokerogue/assets/9343160/3ae328a4-5286-4afd-ae1b-0fab0e99e1fc
> Prevent Pokemon Info screen from being covered up

- src/field/pokemon.ts
The new addition of a variant sacrifice attribute for a few moves wasn't added to the moveset logic, so trainer and boss pokemon weren't getting the reduced rates of these as they were supposed to. Boss pokemon weren't supposed to be able to generate with self KO moves at all.
> Update moveset logic to account for new sacrifice attr

- src/locales/fr/ability-trigger.ts
Proper French translation to Bad Dreams trigger
Image from SM, still up to date in SV
> Correction to French ability-trigger.ts

- src/field/pokemon.ts
Corrects the Event ending time to be same for everyone by using UTC.
> Tie event end date to UTC

- src/data/tms.ts
Really easy fix; just added Scrafty and Scraggy to the TM list for Trailblaze.
Testing for it:
[Video](https://github.com/pagefaultgames/pokerogue/assets/71776311/ab97fe05-7b28-405a-9c65-c4a7e4299371)
> Scrafty line does not have Trailblaze in their TM learnset

- src/data/move.ts
I just removed a comment, nothing else. The TODO refers to the below, but you can also see it was patched the next game. 
> When used during [hail](https://bulbapedia.bulbagarden.net/wiki/Hail_(weather_condition)), Blizzard bypasses [accuracy](https://bulbapedia.bulbagarden.net/wiki/Stat#Accuracy) checks to always hit, unless the target is in the [semi-invulnerable turn](https://bulbapedia.bulbagarden.net/wiki/Semi-invulnerable_turn) of a move such as [Dig](https://bulbapedia.bulbagarden.net/wiki/Dig_(move)) or [Fly](https://bulbapedia.bulbagarden.net/wiki/Fly_(move)). In [Pokémon Diamond and Pearl](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Diamond_and_Pearl_Versions), due to a glitch, when used in hail, it has a 30% chance to hit a target that has used …
> Remove TODO from Blizzard (This was a glitched feature)

- src/ui/unavailable-modal-ui-handler.ts
Exponentially increases the amount of time a client waits before attempting a reconnect up to a set maximum.
> Increases the Amount of Time Until a Reconnect up to a Maximum

- src/field/pokemon.ts
- src/ui/battle-info.ts
- src/ui/target-select-ui-handler.ts
This PR aims at allowing the battle info of the targeted enemy Pokemon to move during double battles. Currently, only the Pokemon itself allows to know the targeted enemy Pokemon, by continuously modifying the opacity. This PR aims at allowing the battle info to move as well.
For the context, I'm referencing this as a `BattleInfo`:
I was inspired by _Pokemon Emerald_ UI on this, where the battle info of the targeted enemy Pokemon moves as well (I actually took inspiration from this video on [Youtube](https://www.youtube.com/watch?v=DIu0hFzxzxQ)).
https://github.com/pagefaultgames/pokerogue/assets/57403591/c8cbb868-026a-41cc-abc2-426c6ef60d46
I'm a big fan of the Pokemon license, but I need to say I wasn't following all the new generations (I probably kinda stopped around gen 5 or 6). …
> Allow BattleInfo to slightly move when Pokemon is targeted in double battles 

- src/battle-scene-events.ts
- src/battle-scene.ts
- src/phases.ts
No functionality changes and no player facing features. All this does is allow for events to fire related to move usage. The event contains data for:
- The ID of the Pokemon who used the move
- The base Move itself
- The amount of PP used during this turn
> Add MoveUsedEvent to Listen For When a Move Gets Used

- src/phases.ts
Running with either pokemon now uses the faster pokemon's speed and checks if either have the ability Run Away
If only one pokemon is alive, just use that one.
> Update running away in Double Battles

- src/battle-scene.ts
- On light coloured biomes this change should be similar readability
- In darker biomes it's has much easier readability
- Now becomes more consistent colour with the rest of the game text which just looks better imo
old text is the grey with yellow drop shadow
> Changing Biome Text Colour

- src/locales/zh_CN/ability.ts
- src/locales/zh_CN/move.ts
- fixed an error in the translation of the _Frisk_ ability.
- fixed an error in the translation of the _As One_ ability for Glastrier.
- swapped the translated description of the _Embody Aspect_ ability when carrying _Teal Mask_ and _Wellspring Mask_.
> Update zh_CN ability.ts and move.ts

- src/phases.ts
Added a check in `EncounterPhase` where if the player is in classic mode and they are past floor 200 it automatically goes to the `GameOverPhase` where the run is treated as a victory and rewards are given.
> Players win if classic and past floor 200

- src/ui/battle-info.ts
This PR aims at fixing the position of the first Pokemon battle info when targeted by an ally.
This has been reported by some players on the [Discord](https://discord.com/channels/1125469663833370665/1243457704861896786/1243457704861896786), and by @bennybroseph on the related PR https://github.com/pagefaultgames/pokerogue/pull/1255#issuecomment-2130317297.
Of course, this was not the intended behavior.
Before, we were offsetting the battle info position if it was the first player Pokemon, while the base position, being used for the UI for the `SelectTargetPhase`, was not.
Now, we make sure to also offset the base position in this case.
Before:
https://github.com/pagefaultgames/pokerogue/assets/57403591/d1c9779c-e6cf-4c59-9112-b85294942931
After: …
> Fix first player Pokemon info being wrongly placed when targeted

- src/locales/zh_TW/move.ts
Fixes https://github.com/pagefaultgames/pokerogue/issues/1282
Fixed typo and restore sensitive words (sinse SW&SH) to their original words same as original game.
> Issue #1282: Fixed Gen1-6 move name in zh_TW

- src/locales/de/berry.ts
- src/locales/de/move.ts
In the German localization I fixed an mistake in the Starf Berry description and localized the effect description of the zippyZap move
> Fixed German localization for Starf Berry description and localized zippyZap effect

- src/data/biomes.ts
This biome is too rare, this is just a temporary change until biomes are redone.
It was also the only biome that rare, despite the specific path needed to get there.
> Made Lab 25% instead of 12.5% to encounter after Factory

- src/data/pokemon-species.ts
- src/ui/battle-info.ts
- src/ui/starter-select-ui-handler.ts
This PR enables selection of starter Formes that both should be selectable as starters, but that also have in-battle Forme changes, which the current starter selection logic filters out (presumably to prevent users from selecting in-battle Formes as their starter base, like having a Mega-Evo starter).
This currently appears to affect 3 Pokemon: Minior (color selection unavailable), Froakie (Battle Bond selection unavailable), and Zygarde (10%/50% Formes and Ability split selection unavailable).
This change only includes override form keys, rather than modifying the PokemonForm constructor, which would require a significantly larger code change, but this does centralize the logic in the PokemonForm class, rather than on the forme initializations, which is maybe less than ideal. Happy to …
> Fix incorrectly unselectable starter formes

- src/phases.ts
Adds a clause in `MoveEffectPhase` that skips user being its own target if the move selected is `MoveTarget.ALL_NEAR_OTHERS`. This encompasses moves like `Discharge`, `Earthquake`, etc. Tried to limit it to the main problem moves being reported in Discord to minimize impact just in case.
It's a bug - unintended behavior. At a bad time too because it means the user only has one Pokemon left 😬 
Right Pokemon no longer hits itself with spread move if it becomes the only Pokemon after left dies before spread move goes off. 
Before change (includes left dying w/ right using spread move which is the problem and right dying w/ left using the spread move which works properly rn)
https://github.com/pagefaultgames/pokerogue/assets/85713900/073d0eb9-46c2-467c-aa80-d4d9d1cf6ac6
After change …
> Bugfix: Right Pokemon no longer hits self when left dies with no replacement when using spread move

- src/ui/menu-ui-handler.ts
Addresses #1404 by changing the previous fork link to the organization GitHub link.
> Bugfix: Change GitHub Link

- public/images/types_zh_TW.json
- src/loading-scene.ts
Test with giving it the german images (for the test) to make sure it doesnt load the zn_CN images instead.
Of course it uses the english images for now
> zhTW Type Images are now correctly loaded.

- src/loading-scene.ts
- src/system/settings.ts
Also now only the current language type image is loaded. If it doesnt exist for a language it will load the english one as a fallback
Tested with all lanugages
Before: (Does not reload titles, trainer classes and names correctly. Loads all type images always)
https://github.com/pagefaultgames/pokerogue/assets/38758606/e17cb595-ad45-4e8a-8088-d5cc22ac72cb
After: (Reloads the whole game so titles, trainer classes and names are correctly localized. Only loads the current type image. (If it doesnt exist it loads the english one)
https://github.com/pagefaultgames/pokerogue/assets/38758606/41bd542b-5137-4216-94ed-65dc1111595b
> When the language is changed the game will complety reload (same as F5).

- src/data/pokemon-level-moves.ts
https://github.com/pagefaultgames/pokerogue/issues/1460
* Phione and Manaphy now both learn Take Heart
* Updated Phione's level 1 learnset [bubble, water sport] -> water gun
* Updated Manaphy's level 1 learnset [bubble, water sport] -> [water gun, heart swap]
References used: [Bulbapedia Phione](https://bulbapedia.bulbagarden.net/wiki/Phione_(Pok%C3%A9mon)#Learnset) [Bulbapedia Manaphy](https://bulbapedia.bulbagarden.net/wiki/Manaphy_(Pok%C3%A9mon)#Learnset)
> Update Phione and Manaphy levelup learnset

- src/ui/starter-select-ui-handler.ts
Fixes a small visual issue where scrolling through a list of Pokémon would not hide a candy if all the following was true:
1. The new Pokémon was not the root species.
2. The previous Pokémon in the same row/column had an upgrade available. 
3. The previous Pokémon in the same row/column *was* the root species.
> Candy Icon Display Bugfix

- src/data/pokemon-evolutions.ts
Removes King's Rock as an evolution requirement for Politoed and Slowking.
Currently, Poliwhirl and Slowpoke evolve into Politoed and Slowking by using a Linking Cord while holding a King's Rock. This requires the player to roll a Rogue tier item and then an Ultra tier item. It's easier to get Archaludon than Politoed. 
This PR simply removes the King's Rock requirement and just requires the player to use a Linking Cord. This is in line with other evolutions that require an evolution item in the main series, such as Kingdra and Slurpuff.
> [QOL] Removed King's Rock requirement for Politoed/Slowking evos

- src/touch-controls.js
To avoid crashes when the DOM is not yet created, especially during tests, we encapsulate the `preventElementZoom` call into a method that can be imported and called as needed.
Stop putting code in the global scope. It's bad practice and can lead to crashes. Instead, encapsulate your code in a method that can be imported and called as needed.
> Fixing Global Scope Issues: Encapsulating preventElementZoom to Prevent Test Crashes

- src/locales/fr/dialogue.ts
Typo in French typos in dialogue.ts
> [Localization] French typos in dialogue.ts

- src/data/pokemon-forms.ts
Currently when you Mega Evolve it says "<Mon\> mega-evolved into <Mega Mon\>!"
It was bugging me, so this uses the official term, "Mega Evolved"
> Fix a typo in post-Mega Evolution message

- src/modifier/modifier-type.ts
Moves with 5 or less max PP now only boost Ether/Elixer rates if they are at less than max PP.
> Prevent useless Ethers

- src/ui/achv-bar.ts
Make achv-bar ui "responsive"
The interface size remains the same as by default.
However: 
- If the title is longer, the width of the interface is increased.
- If the description is longer, the height is increased.
- And of course, if the 2 cases are combined, the interface is enlarged in both height and width.
To facilitate translation and fix problems with some English achievements that were also having trouble displaying correctly
> Before
> After
https://github.com/pagefaultgames/pokerogue/assets/8146474/31af3068-9644-4a08-95d5-2edf2484bae6
I placed achievements directly in the show() method of the `src/ui/menu-ui-handler`
```typescript
...
this.getUi().achvBar.showAchv(achvs._10K_MONEY);
this.getUi().achvBar.showAchv(achvs._100K_MONEY);
...
```
> [QoL] [Localization] Make achv-bar ui resize dynamically based on content

- src/configs/pad_procon.ts
- src/inputs-controller.ts
Added mapping for switch pro controller (Inverted A/B - X/Y)
I tested this on my side and this is working as intended, but i have low experience and i don't know this project well. 
Please test thoroughly
> Added support for Pro Controller mapping

- src/battle-scene.ts
- src/overrides.ts
Add more flexibility in pokemon overrides
Adding possibility to override foe level to have more flexibility in testing different things
Added new option in Overrides to hardcoded foe level
High wave, low levels
You can just set number for variable OPP_LEVEL_OVERRIDE
`export const OPP_LEVEL_OVERRIDE: number | null = 100;`
> [Feature] Add possibility to override foe level

- src/egg-hatch-phase.ts
- src/phases.ts
- src/ui/eggs-to-hatch-count-container.ts
Resolves #1289 
- Window on top left of screen showing number of eggs hatching during hatch phase. This will only show up if there are 2 or more eggs hatching.
- To let the user know how many eggs are queued for hatching, giving an idea how long will it take to finish hatching.
- Added new class container for the hatching eggs count window.
- 1 egg hatching
https://github.com/pagefaultgames/pokerogue/assets/68144167/49ce5c23-f4e1-4f43-ba41-0516ec189e13
- 2 or more eggs hatching
https://github.com/pagefaultgames/pokerogue/assets/68144167/07f4b0f8-29d1-4b30-bcf0-04da27314570
- \> 9 eggs hatching (window will adjust if it reaches <= 9)
https://github.com/pagefaultgames/pokerogue/assets/68144167/b3f2dd02-d182-419b-b678-34b43ec62363
- In `src/system/game-data.ts`, find the code:
```
this.eggs …
```
> Add window showing number of eggs hatching during hatch phase

- src/locales/de/move.ts
- src/locales/de/splash-messages.ts
- Added translations for the moves 'thunderclap', 'wicked/blazing/noxious/combat/magical torque'
- Fixed a typo in the splash message 'achievementPointsDontDoAnything'
Because the translations were missing.
No real need for testing. But if you want to look at the move descriptions and splash message ingame
> [Localization] German translations added for 'thunderclap', 'wicked/blazing/noxious/combat/magical torque' and fixed a typo

- src/locales/de/move.ts
Fixed thunderclap translation for a more literal translation and without leaving out the "attack misses" part.
> [Localization] updated german translation for thunderclap

- src/field/pokemon.ts
- src/overrides.ts
Move Status Overrides into separate PR following [this conversation](https://github.com/pagefaultgames/pokerogue/pull/940#discussion_r1620678708)
Adding this override will make testing moves / abilities that affect / are effected by status easier.
Add a Status override
N/A
Checkout the branch, change the status override inside `src/overrides.ts` and start / load a game
> separate status override to its own branch

- src/field/pokemon.ts
Fixed variant rates
A previous PR accidentally changed variant rates
Variant rates should be 60/30/10 instead of 70/20/10
n/a
`npm run start:dev`
> [Bug] Fix bug with variant rate

- src/ui/starter-select-ui-handler.ts
- Add conditions when moving up or down at the edges of the select starter ui
- Make it easier to navigate in the select starter ui by moving the cursor to the opposing edge
https://github.com/pagefaultgames/pokerogue/assets/12510911/06b218b0-8028-431b-85cf-93d2780d642e
> Starter select - Implement up and down offset navigation

- src/data/ability.ts
Fixes previously broken priority stopping abilities. Before they would stop moves that target your allies when they should not.
The previous implementation was broken. this simply fixes that.
Broken Implementation
https://github.com/pagefaultgames/pokerogue/assets/114428473/a04c1e5d-028c-4443-b5b3-aa0899b12a03
Fixed Implementation
https://github.com/pagefaultgames/pokerogue/assets/114428473/d7e508b9-5af9-4d03-8ffb-0da32bd65008
Just take a Pokemon with a priority move that targets your ally, such as helping hand, into a double battle
> Queenly Majesty/Dazzling/Armor Tail Fix

- src/data/pokemon-species.ts
A quick fix by renaming Palafins forme change to hero-forme in code
fixed a bug introduced in https://github.com/pagefaultgames/pokerogue/commit/dfb089a2b9545d44699d4563ab7ac163efec01f2
that caused zacian and zamazenta to crash
To fix a common crash users are experiencing
Changed the name of the forme used by palafin internally to not overlap with zacian
N/A
I got a session file from someone affected and reproduced the crash
made my changes and no longer got a crash
-  [X] There is no overlap with another PR?
- [N/A] Are the changes visual?
- [N/A] Have I provided screenshots/videos of the changes?
> fix zacian/zamazenta crash

- src/data/pokemon-species.ts
- Fix Toxtricity Lowkey form evo
- Game freezes when evolving Toxel to Toxtricity-Lowkey because genderDiffs was set to true- Toxtricity doesn't have gendered sprites
- Removed gender diffs on lowkey form
- Before the fix, game freezes because of the ff errors:
https://github.com/pagefaultgames/pokerogue/assets/68144167/1c4fc0f8-8a4f-45b7-b6bc-4657ad8ec963
- After fix, Amped form still works
https://github.com/pagefaultgames/pokerogue/assets/68144167/cc8351e2-d6a6-4afa-aa31-b18d435e1595
- After fix, Lowkey form now works
https://github.com/pagefaultgames/pokerogue/assets/68144167/75a0a00b-619a-43df-a9e6-c254adc9360f
- Get Toxel to evolve to Lowkey at lvl 30
> [Bug] Fix lowkey toxtricity evolution

- src/field/pokemon.ts
A Pokemon with the ability Neutralizing Gas no longer suppresses their passive ability (and vice versa).
In its current implementation, Neutralizing Gas suppresses all abilities on the playfield, including the source Pokemon's passive ability (if it has one). However, based on the description for Neutralizing Gas in Gen IX, the source Pokemon's other abilities should not be suppressed.
From a balance perspective, this allows Pokemon like Weezing to have a much larger pool of passive abilities to choose from without the fear of them being suppressed. It also facilitates Neutralizing Gas as a passive ability option for Pokemon with valuable primary Abilities that would otherwise be suppressed.
- `data/pokemon`: `Pokemon.canApplyAbility()` is changed so that when it checks the Pokemon on the …
> [QoL] Neutralizing Gas no longer suppresses the source's abilities

- src/modifier/modifier-type.ts
Updated form change logic. Code lifted from https://github.com/pagefaultgames/pokerogue/pull/826 but added comments
> It uses similar logic to the shop when it chooses if an evolution item should spawn or not.
The shop checks if any current species in party has SpeciesFormEvolution with an evolution item requirement.
This fix checks if the Pokemon you are applying to has a SpeciesFormEvolution with an item or items and maps it to an Array, then checks if the applied item is in that array.
The old process was trying to do this shorthand, but for some reason on Shaymin it was not detecting an evolution item, so I just changed it to use a deeper check.
Fixes Gracidea bug on Shaymin
> This allows an item to be given to valid Species that can use the given item even if not immediately.
> Ex: …
> [Bug] Fix Gracidea

- src/data/ability.ts
The abilities Guts, Marvel Scale and Quick Feet now properly boost the user's stats if it also has the ability Comatose.
The issue https://github.com/pagefaultgames/pokerogue/issues/1639 showed that the interaction between Comatose and other status abilities wasn't working, probably due to the fact that it's not a thing present in main series games, as you can't have more than 1 ability there. The solution seemed pretty easy and straight forward, so I did it.
Simply added an extra condition for the 3 mentioned abilities, instead of checking if `!!pokemon.status` is true, it now checks if `!!pokemon.status` OR `pokemon.hasAbility(Abilities.COMATOSE)` are true. This is the same logic the ability already uses in the [code](https://github.com/pagefaultgames/pokerogue/commit/bfe018ef65aaeb46216 …
> [Bug] Fix status abilities not considering Comatose (fixes #1639)

- src/field/arena-events.ts
- src/field/arena.ts
- src/system/game-data.ts
This adds events when Weather, Terrain, or Tags change in any way. This allows future UI elements to listen for these events and update without needing any update or refresh loop.
This change adds a new file to define all of the events and enums. It also adds events for when the arena's values change including during sessions being loaded.
Since the changes are not visual, you'll need to add breakpoints when each event occurs and trigger them. This can be done by setting up weather/terrain/tags and then saving on the next floor and loading to completely test all events.
> Add Arena Events

- .github/workflows/github-pages.yml
Allows upstream identification of problems such as those that occurred during merge of PR #1567
(_Commit to the doc branch `gh-pages` are disabled during a PR triggering_)
> Trigger the github-pages workflow even during pull requests

- src/modifier/modifier-type.ts
Reworks the flame and toxic orb algorithms, fixing a variety of bugs and simplifying it to be more consistent with other item weights.
The new system gives it a high weight in line with the other highest weight combat items in tier if it has a relevant move or ability and doesn't already have one of the two items.
There were like five different bugs in the previous algorithm and it was literally the highest weight item in its tier.
The anonymous function determining the weight of the two mentioned items was rewritten.
N/A
Run hundreds of games with and without the pokemon?
- [N] Are the changes visual?
- [N] Have I provided screenshots/videos of the changes?
> [Balance] Simplify and fix flame/toxic orb weight

- src/locales/ko/dialogue.ts
Fix Wrong Sentence.
1 letter is missing.
오늘 일은 우리의 마음 속에서 살아갈 `거`야.
Not only add 1 letter, make sentence more-talking-style.
Still awkward, but better than before.
Remove `로` in `절대로` (talking style reducing unnessary postposition)
Convert `살아가다` to `남아있다` (from misunderstanding living-like-a-creature to remaining-like-the-memory)
Old one.
농담이야! 절대로 안 잊어버릴 거야.
오늘 일은 우리의 마음 속에서 살아갈 `거`야.
New one.
농담이야! 절대 안 잊어버릴 거야.
마음 속엔 쭉 남아있을 수 있게. 
Beat classic mode.
Unfortunately, screenshots are tested using "rival_female" instead of "ending_female".
ps. 대사 쓰기 정말 어렵습니다 누가 싹 다듬어줬으면 좋겠습니다..
ps2. Multiple one-line-PR is.. right way? "cannot be split into smaller" is too difficult for me.
> [Localization] Korean rival dialogue very small fix

- src/egg-hatch-phase.ts
- src/system/game-data.ts
- src/ui/egg-gacha-ui-handler.ts
Implements a pity system for eggs.
It's on the roadmap.
You are guaranteed at least one legendary egg every ~412 eggs, one epic every ~59 eggs, and one rare every ~9 eggs. You are guaranteed at least one new species unlocked every 10 eggs of a given tier.
N/A - Not really visible.
Give yourself vouchers, then hatch eggs. It should also track across saving and loading.
- [N] Are the changes visual?
- [N] Have I provided screenshots/videos of the changes?
> Implement Pity System

- src/data/move.ts
Implementing the move Pollen Puff. There was already this PR on this subject but it was incomplete and closed due to inactivity.
Unimplemented move
Pollen puff effect change when used on ally : the ally is now restored 50% of max health instead of taking damage.
Pokemon with Bulletproof or Telepathy are not affected by the heal effect.
As Heal Block is unimplemented, the interraction of pollen puff with heal block isn't implemented.
Pollen puff damaging opponent and healing ally
https://github.com/pagefaultgames/pokerogue/assets/56865723/0f31df5d-44c2-4595-b80a-7b08590f3c73
Pollen puff is innefective on pokemon with Bulletproof
https://github.com/pagefaultgames/pokerogue/assets/56865723/4e8478fe-56e9-41d4-90df-fbed62b45239
Pollen puff is innefective on ally with Telepathy …
> [Move] Implement pollen puff

- src/data/battler-tags.ts
Make curse do at least 1 damage
Shedinja takes no damage from curse currently
Added a Math.max
Before
After
Override a Shedinja for player Pokemon and give the Opponent curse and a ghost type
> [Bug] Curse should do at least 1 damage

- src/battle-scene-events.ts
- src/phases.ts
- src/ui/arena-flyout.ts
- src/ui/battle-flyout.ts
Fixes an issue where Leppa Berries were not reflected in the Moveset Flyout. Also skips tracking for Struggle
This was a bug since the user is notified when an enemy eats a berry and could easily track how much PP was restored.
A new event was added when a berry is used and the BerryModifier is sent along to the listener. 
The flyout finds the first move that has no PP left and restores 10 PP to the tracked version of the move. This mirrors the code of the berry.
https://github.com/pagefaultgames/pokerogue/assets/13838608/b5ede988-4ad7-4314-8547-dec6dc5bae4f
https://github.com/pagefaultgames/pokerogue/assets/13838608/857832e5-0dae-42c9-9d45-12f8e36e6f31
Set overrides to have a pokemon with a shallow move pool and low PP. Add a leppa berry as well. Use moves until the pokemon runs out of …
> [Bug] Fix Leppa Berries not Updating Flyout PP

- src/modifier/modifier.ts
- Added message when quick claw is triggered: _"{{pokemonName}} used its quick claw to move faster!"_
- To avoid confusion when slower pokemon "suddenly" gets the first action, the same way it shows a message when grip claw is triggered.
- Message when quick claw is triggered
https://github.com/pagefaultgames/pokerogue/assets/68144167/1388aab4-3b25-41ea-bd7b-2c2ccd9e0c5a
- set `STARTER_SPECIES_OVERRIDE` to a slow pokemon like Shuckle
- set `STARTING_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [{name: "QUICK_CLAW", count: 1}];`
> [QoL] Show message when quick claw is triggered

- src/modifier/modifier.ts
- prevent quick claw message from showing up when using ball/run/switching pokemon
- quick claw is showing message on ball/run/switch when activated- its because the modifier class is called on TurnStartPhase
- added additional check if command is fight
I added a `console.log('BYPASSED SPEED')` here:
Note that _BYPASSED SPEED_ and _Applied Quick Claw_ were logged but the message no longer appears
https://github.com/pagefaultgames/pokerogue/assets/68144167/cd4d1e21-a706-46b6-9b7c-824389d85e37
Message now only shows when Command is FIGHT
https://github.com/pagefaultgames/pokerogue/assets/68144167/2f89696c-f7af-407b-a8c4-cbd886cd3f85
set your pokemon to a slower pokemon, use ball/run/switch
```
export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.SHUCKLE;
export const …
```
> [Bug] Fix quick claw message showing up if command is not fight

- src/locales/es/pokemon-info-container.ts
- src/locales/es/weather.ts
- Updated weather.ts
- Updated pokemon-info-container.ts
I decided to introduce these changes to improve the overall user experience, particularly for Spanish-speaking players who may not understand English well.
In weather.ts, the phrases were missing spaces between some words.
Translated pokemon info container.
**Before changes**
**After changes**
> [Localization] Phrase fix in weather.ts and pokemon-info-container.ts Spanish translation

- src/data/ability.ts
- src/phases.ts
Fix for #1686 and #1450
Fixed a bug where Dancer activates while a Pokemon with Dancer Ability is charging a 2 turns move. 
Fixed a bug where Dancer activates while a Pokemon with Dancer Ability is on the opponent team but not on the field.
https://github.com/pagefaultgames/pokerogue/assets/11600168/14737303-f159-45ba-ab28-02fb4583245a
https://github.com/pagefaultgames/pokerogue/assets/11600168/209c3a54-93c5-4ce0-9222-ef829216bf3d
Have a pokemon having the Dancer abilty use fly and use a dancing move afterwards.
Have a pokemon having the Dancer abilty on the opponent team but not in the field and use a dancing move.
> [Bug] Fix for Dancer activating when enemy in not on field / using a 2 steps charging move

- src/modifier/modifier-type.ts
Makes luck default to 0 if false-y. This works for NaN, null and undefined.
NaN luck bricks the logic
Add an || 0 to the getPartyLuck function.
N/A
Do anything involving luck.
> Hotfix for NaN luck

- src/data/battler-tags.ts
Fixes a typo in https://github.com/pagefaultgames/pokerogue/pull/1085
Changes confusion chance from 2/3 to the correct 1/3
Used `if(pokemon.randSeedInt(3) === 0)` instead of `if(pokemon.randSeedInt(3))`
n/a
`console.log` the `pokemon.randSeedInt` and see if a Pokemon hits itself
> [Bug] Change confuse chance from 2/3 to 1/3

- src/ui/starter-select-ui-handler.ts
Somehow my changes from a feature I work one sliped into a different branch of mine.Sry
the start label shouldn't say "random"
revert it back to say "start" (localized)
start the game an check the label
> [BUG] whops... revert start-label text to translation

- src/locales/ko/dialogue.ts
This PR is added korean dialogue for Gym leader in Kalos region
칼로스 지방 체육관 관장 ramos(후쿠지), viola(비올라) 대사를
한국어로 번역 및 로컬라이징 작업을 진행하였습니다.
@sodaMelon @Ohmry @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.
Few trainers's dialogue have been translated into Korean yet.
Translated dialogue of ramos, viola to Korean.
칼로스지방 포켓몬 관장 후쿠지, 비올라 대사 번역하였습니다.
포켓몬스터 XY 시리즈 정발 번역을 최대한 참고했습니다.
전체적인 패배 대사+비올라 "Now come at me!"는 정발 말투만을 참고하여 직접 번역하였습니다.
> [Localization] #1761 Korean trainer dialogue (ramos, viola)

- src/field/pokemon.ts
Currently Pokemon with forms (with the exception of forms that had a formKey of "", an empty string) that have shiny variants cannot spawn as Rare or Epic shinies. This change will allow them to properly generate. 
Hoopa and Castform both have a base form that has a key of an empty string, which allowed the old code to evaluate correctly without a formKey and only their species ID, ex: 720 for Hoopa.
Because blue and red shiny good.
[Issue](https://github.com/pagefaultgames/pokerogue/issues/1745)
Adds formKey to the check to see if variantData has a variant for the given Pokemon and its given form.
I just recorded about 12 different tests and all of the files are corrupted so I'm uploading this now and will add them in the morning.
Tested so far:
- Burmy
- Wormadam
- Shellos
- Gastrodon
- …
> [Bug] Fix generateVariant to account for forms

- src/battle-scene.ts
- src/phases.ts
- src/system/settings/settings.ts
Added a Battle Style setting that allows you to stop the "Will you switch Pokemon?" menu from appearing at the start of a battle.
The Switch vs Set Battle Style setting is available in all mainline Pokemon games, and adds QoL enhancement for the Endless game modes.
The `battleStyle` property was added to `battle-scene.ts`.
`phases.ts` was modified to end the `CheckSwitchPhase` if the battle style is Set.
In `settings.ts` `Battle_Style` became a GENERAL setting
https://github.com/pagefaultgames/pokerogue/assets/167576411/3ab42504-a300-4323-b6a6-703d695da6b3
The new Battle_Style setting can be tested by selecting either "Switch" or "Set" in the settings, and then entering a battle and observing one of the following:
- If "Switch" has been selected you should see the "Will you switch …
> [Feature] Added Battle Style setting

- src/locales/zh_CN/modifier-type.ts
- src/locales/zh_TW/modifier-type.ts
Fixed a mistranslation in healing charm for Chinese
Description was wrong
Changed "includes" to "excludes"
n/a
Pull the changes and change locale to Chinese and spawn in a healing charm
> [Localization] Fix typo in healing charm for Chinese localization

- src/field/pokemon.ts
Thunderclap should not let the AI read player inputs
Matching behavior of sucker punch and upper hand
Added thunderclap to the AI move selection portion that's next to sucker punch and upper hand
n/a
Override an opponent with thunderclap and verify their actions are the same between using an attacking and non attacking move
> [Bug] Thunderclap should not let the AI read your inputs

- src/data/move.ts
Added Rototiller, which gives +1 Atk. and Sp.Atk to every grounded plant pokémon on the battlefield.
Singles Example
https://github.com/pagefaultgames/pokerogue/assets/73134872/70e7debe-5a17-42b1-a5af-70786b55c608
Doubles Examples
https://github.com/pagefaultgames/pokerogue/assets/73134872/ea9c5bdc-794c-4416-a166-35351a2a1392
Play a non-grass, grounded grass and ungrounded grass type pokémon, and make any of them use Rototiller.
> [Move] Rototiller implementation

- index.css
The C-Button is now shown on Mobule when selecting a modifier.
The C-Button is required to access additional information for the move a TM teaches.
Adjusted CSS Rule responsible for hiding the button during modifier selection to show the button.
Before:
Now a C Button appears in the bottom right corner, similar to the combat menu.
Enter a fight, end the fight, the button should still be present.
Though, to be more specific:
Change the following override to get a TM as a reward.
`export const ITEM_REWARD_OVERRIDE: Array<String> = [];`
with
`export const ITEM_REWARD_OVERRIDE: Array<String> = ["TM_COMMON"];`
When hovering over the TM, before selecting it, you should be able to press C to view additional information.
> [Bug] Show C-Button on Mobile during Modifier Selection

- src/phases.ts
- src/utils.ts
Speed ties are being refactored to sort then shuffle, preventing browser inconsistency.
Firefox and chrome would produce different results for speed ties sometimes due to the details of the sort function which we relied on being an implementation detail that differed by browser.
The sort function used for speed order no longer also randomises the order on ties, instead after all pokemon have been sorted by speed it goes through and internally shuffles any group of pokemon that are tied on speed.
Produce any fight which involves a speed tie, via overrides or a daily seed. An easy way to test with a daily seed is by forcing the seed `ww72CMRSJYns+1ZuvidsAw==`. Use a pokeball on the first fight, take the great ball, use payback twice, reroll rewards, potion your turtonator, and then you …
> [Bug] Fix speed tie code

- src/data/arena-tag.ts
- src/data/move.ts
- src/field/arena.ts
- src/overrides.ts
Added Court Change into the game. 
The move was unimplemented
Added a swaptagsattr to move.ts. Also added a boolean value named quiet to ignore onAdd and onRemove tags when the move is used in arena-tag and arena.ts
I tested the move through override and the enemy would use on field effects, move works with spikes, toxic spikes, stealth rock,
sticky web, tailwind, light screen, reflect, and mist
I did.
No
Sticky Web:
https://github.com/pagefaultgames/pokerogue/assets/171395666/488d7831-cd10-4c2c-b327-8fab43232ebc
Mist: 
https://github.com/pagefaultgames/pokerogue/assets/171395666/b1a5fce9-d4e9-4156-b066-a026a4e4fd09
Light Screen:
https://github.com/pagefaultgames/pokerogue/assets/171395666/2d027324-7749-446f-9bff-0c898770c8bf
Toxic Spikes: …
> [Move] Implemented Court Change

- src/locales/zh_CN/tutorial.ts
- src/plugins/i18n.ts
- src/system/settings/settings.ts
currently language auto detection is broken,
fixed according to [i18next documentation](https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted)
currently language auto detection is broken for **Simplified Chinese, Traditional Chinese, Portugese Brazilian**
i18next config resource key
----
> [BUG] fix language auto detect

- src/battle-scene.ts
- src/enums/exp-notification.ts
- src/phases.ts
I've moved exp-notification enum into their own files inside src/data/enums
Moving enum to respective files
Avoiding hardcoded magic numbers and replace them with enums
> [Refactor] Move enum ExpNotification into separated file

- src/data/ability.ts
Closes #1715
* Primal weather can overwrite each other
* Primal weather ends upon switching out or fainting
Interactions weren't working before.
If a primal weather was already in effect, it could not be overriden by another -> now it can
Primal weather would not revert upon Pokemon switching out or fainting -> now it does
https://github.com/pagefaultgames/pokerogue/assets/63990624/68eb7021-59a7-48ea-802a-5692f72bb95c
Override ability to Desolate Land, Primordial Sea, or Delta Stream.
> [Bug] Fixed primal weather interaction.

- src/data/move.ts
cf https://bulbapedia.bulbagarden.net/wiki/Sweet_Scent_(move)
This changes the Sweet Scent move to reduce foes' evasion by 2 stages instead of 1, as per Gen6+. This modifies line 5975 of src/data/move.ts
That's it, just a single character change.
> [Bug] Update Sweet Scent to reduce evasion by 2

- src/locales/en/dialogue.ts
Added a missing r
Because it was spelled wrong
I literally added only the r in the word.
Before:
After:
Force Tate (or Liza) to spawn as a double (for example by changing battle.ts)
> Fixed Spelling mistake in Tate & Lizas Double Dialogue

- src/battle-scene.ts
Override battles into single only if not fighting with trainers
Game crashing if double fight with trainer and set override single battles to true
Fix https://github.com/pagefaultgames/pokerogue/issues/1948
Override battles into single only if not fighting with trainers
set SINGLE_BATTLE_OVERRIDE to true
fight with trainer with double fight
> [Bug] Override battles into single only if not fighting with trainers

- src/ui/settings/settings-display-ui-handler.ts
Language option has been shown only English whenever what current locale is it. so that fix to show current locale in setting.
It is bug I think, so it needs to fix.
Change option value to current locale when initialize Language option in `setting-display-ui-handler.ts`
https://github.com/pagefaultgames/pokerogue/assets/13056250/27ee65e4-29d2-4766-b10d-18480c4dd0dc
- Check out this PR.
- Check current language in setting.
- Change language.
- After reload, check language option is current locale in setting.
> [Bug] Fix to show current locale in setting

- src/game-mode.ts
- src/ui/save-slot-select-ui-handler.ts
Localized getModeName and fixed the localization of "Wave"
> [Localization] Fixed the localization of getModeName and "Wave" text

- src/locales/es/menu.ts
Localization changes
Since menu.ts got updates, I wanted to translate it
I translated the "Loading asset" and the disclaimer in menu.ts
Not needed, just localization
Not needed, just localization
- [x ] There is no overlap with another PR?
- [ x] The PR is self-contained and cannot be split into smaller PRs?
- [ x] Have I provided a clear explanation of the changes?
> [Localization][es] menu.ts full Spanish translation

- src/test/abilities/intrepid_sword.test.ts
- src/test/battle/battle-order.test.ts
- src/test/battle/battle.test.ts
- src/test/battle/error-handling.test.ts
- src/test/phases/phases.test.ts
- src/test/ui/starter-select.test.ts
- src/test/utils/errorInterceptor.ts
- src/test/utils/gameManager.ts
- src/test/utils/gameWrapper.ts
- src/test/utils/phaseInterceptor.ts
- src/test/vitest.setup.ts
Refactored phase management in tests to ensure it resolves when the phase's `end()` method is called. Simplified multiple layout complexities and added error handlers to catch errors and halt async calls.
These changes are made to enhance the robustness and reliability of phase management, streamline the application layout, and reduce potential error sources. This refactoring and error handling improvement address issue #123, aiming to improve user experience and system reliability.
- **Before:** Phase management involved multiple layout complexities and lacked robust error handling.
- **After:** Phase management now correctly resolves with the `end()` method, has a simplified layout, and includes error handlers to catch errors and stop async calls.
Test that were passing before are still …
> [Improvement] Refactored Test Phase Management with Error Handling

- package.json
- src/test/utils/mocks/mocksContainer/mockText.ts
added a way to silent the console.log by using the command:
npm run test:silent
+ added a missing property in MockText (style), to fix this:
> [Tests] added silent flag to run tests and added a missing properties in the MockText

- src/data/move.ts
Make switching moves check for challenges.
Switching moves weren't checking for challenges.
Switching moves use isAllowedInBattle instead of !isFainted.
Attempt to use a switching move in a challenge while you've got only illegal pokemon in the back.
- [] Are the changes visual?
- [] Have I provided screenshots/videos of the changes?
> [Bug] Fix switching moves in challenge mode

- src/data/challenge.ts
Victini is in gen 4 partially for UI reasons, this overrides that change but only for monogen challenge runs.
Victini currently counts as gen 4, but they're from gen 5.
Code to treat Victini as gen 5 for monogen challenges in the challenge code.
> [Bug] Fix Victini's generation for challenges.

- src/field/pokemon.ts
Type checking effects that were meant to check only the base types now ignore transform. This most notably means that transform no longer breaks challenge runs, though it also affects pancham's evolution and tera shard type selection.
Transform was violating monotype runs.
ignoreOverride is now passed into the getSpeciesForm and getFusionSpeciesForm functions in getTypes.
Use transform on anything that would violate a monotype challenge.
> [Bug] Make getTypes ignore transform when ignoring overrides

- src/data/move.ts
Makes it so multi-hit drain moves heal based on damage the dealt per hit and not total damage dealt.
If you had a multi-lens and used a drain move like `Absorb`, `Drain Punch`, etc. it would heal you based on your total damage dealt that turn and not the damage the individual hits. This means that if you did 4, 4, and 4 damage you would heal 2, 4, and 6 instead of 2, 2, and 2.
`HitHealAttr` in `move.ts` calcs using `user.turnData.currDamageDealt` instead of `user.turnData.damageDealt`.
How it is on live branch right now (bugged)
https://github.com/pagefaultgames/pokerogue/assets/85713900/1fcb4f01-0c4f-45a0-9323-384413b43cac
With this bugfix:
https://github.com/pagefaultgames/pokerogue/assets/85713900/33c811b3-baa6-4623-90b9-b11ab6e74df3
Chuck these into src/overrides.ts
```
export const …
```
> Bugfix: Fixing multi-hit drain moves so they heal based on individual hit and not total damage dealt

- src/data/trainer-config.ts
Adds duplicate `setMixedBattleBgm` entries for the Gen 1-5 important trainers, as well as one for regular trainers, allowing music to play for them again when mixed music is selected. Fixes #1984
> [Hotfix] Add Mixed Battle BGM entries for the Gen 1-5 trainers

- src/field/pokemon.ts
Fixed a bug where move type multiplier effects (such as Freeze-Dry being super effective against water) is not considered in the type hints and enemy AI.
Currently, moves like Freeze-Dry against water are shown as orange (not very effective) in the type hint, and not prioritized by the enemy, despite being super effective.
Added a single line of `applyMoveAttrs` in `Pokemon.getAttackMoveEffectiveness`.
`getAttackMoveEffectiveness` is only used in
1. `Pokemon.getMoveEffectiveness`, which is used for the text and colour in type hints. 
2. `EnemyPokemon.getNextMove`, using it for assigning move scores.
So it should not affect anything else.
Before:
After:
1. Turn on type hints
2. Use a pokemon with moves that have special type multiplier effects, such as Freeze-Dry and Thousand Arrows.
3. …
> [Bug] Fixed moves with type multiplier effects not being considered in type hints and enemy AI

- src/data/egg.ts
- src/ui/starter-select-ui-handler.ts
Update the starter select UI so, instead of displaying the default egg icon, display the species egg tier.
Zapdos show default egg
Zapdos show ultra tier egg
Helping new players to identify how egg tiers work.
- Added a new function to calculate the egg tier based on species.
- Modified starter selection screen
UI video
https://github.com/pagefaultgames/pokerogue/assets/31145813/84a255c1-db76-4d30-8cdc-1f6acd24e16f
They dont display a egg icon
Staryu costs 4 but cost was reduced to 3 with candy. Display EggTier.GREAT, because the species can only be hatched from these eggs.
Load your session and oper starter selection UI
> [enhacement] Show Egg tier icon on starter UI

- src/ui/fight-ui-handler.ts
This small change adds a color coding to the pp number in the fight UI. The PP number will now appear yellow if only half or less PP are left, orange when a quarter or less is left and red if 0 PP are left.
Color coding the PP in fight UI to fit main line games.
I often didn't realise I was low on PP while playing and thought some color might help here. 
The numbers of used and max PP in the fight UI are now colored according to how many PP are remaining.
Get into a run (preferably with a mon that has a move with 5 or 10 max PP).
Use a move until it has half PP left, a quarter PP left, no PP left.
> [Enhancement] Color code for used PP in fight UI

- src/locales/fr/biome.ts
> [Localization] Fix FR typo 'Desert' instead of 'Désert'

- src/ui/pokemon-info-container.ts
Previously PR #1754 went through to update the pokemon info container, but there was a slight bug where the form label and text will show on a pokemon that doesn't have a form if the previous pokemon had a form. This PR aims to fix that 
The previous PR #1754 that went live recently introduced this display bug, so this fixes that.
Added some logic on the form label to hide if there's no form on the pokemon - previously it would show the form label if the pokemon had a form but that's it; now it should hide the label and text if the pokemon doesn't have a form
The attached video shows catching a pokemon with a form and then a second pokemon without a form, and the form label not showing up 
https://github.com/pagefaultgames/pokerogue/assets/66582645/d336445a-1b31-4e5d-a40e-1aeadc173e00
Use …
> [Bug] Fixed bug where pokemon info container shows form of pokemon that doesn't have it if the previously caught pokemon has a form

- src/ui/fight-ui-handler.ts
- Update default PP color based on ui theme
- Unreadable PP on Legacy Theme
- default pp color based on ui theme
- Default UI theme
- Legacy UI theme
- set UI theme to Default/Legacy, enter a battle and check PP color
> [Bug] Add dynamic default pp color

- src/ui/pokemon-info-container.ts
Moved the label text a bit to the right
The "Habilidade" text was phasing through the container border
Label Text X position
Capture a Pokémon
> [Bug] [Localization] [pt] Small UI fix pokemon-info-container

- src/ui/starter-select-ui-handler.ts
these changes fix a bug where inputs would persist on the ui where they should not
a bug was found where the starter select input prompts would still be visible at the top left of the screen in some cases, this is to fix that
The ui objects are now being appropriately destroyed so that they don't get added the scene without a container 
before my fix 
[pre-inputFix.webm](https://github.com/pagefaultgames/pokerogue/assets/170910983/b0ab378c-c5c4-47c8-b5c8-237b00b947c7)
after my fix 
[post-inputFix.webm](https://github.com/pagefaultgames/pokerogue/assets/170910983/b2e41115-7895-4ea5-843c-3cc145a84e4a)
From my experience, reproducing was as simple as...
- going to the start screen
- selecting a pokemon with some options to cycle (gender, shiny, etc.) 
- moving cursor to the start button 
- …
> [Bug] resolve issue with input text persisting in top left of game screen in certain cases

- src/ui/fight-ui-handler.ts
- src/ui/text.ts
Adjusts the color of the remaining PPs correctly & properly to the theme
Because what has been done, has been done a bit hastily
- Choose colors adapted to provide a contrast that facilitates reading (ratio of 3.0 or more)
> Tool used: https://webaim.org/resources/contrastchecker/
- Refactoring of the condition to avoid unnecessarily assigning variable several times depending on the contents of `ppPercentLeft`
- Use existing TextStyle enumeration to define colors properly
Before:
After:
Do a fight with a TM with few PP, and observe the ui
> _It's out of my control, it's the same 12 tests that fail on `main` 👀_
> [Enhancement][ui] Fix - Adjusts the color of the remaining PPs correctly & properly to the theme + Refactoring

- src/field/pokemon.ts
- ignore ability for type hints
- closes #2025 
- added `ignoreAbility` parameter
- enemy with Volt Absorb
https://github.com/pagefaultgames/pokerogue/assets/68144167/07665f66-1f76-4718-912e-5afdff859605
- enemy with Storm Drain
https://github.com/pagefaultgames/pokerogue/assets/68144167/c4b178b0-013d-4e44-a783-c6b9609c3505
- enemy with Flash Fire
https://github.com/pagefaultgames/pokerogue/assets/68144167/79fe2424-37ae-48ef-84e4-f9d259ae81bc
- enemy with Wind Rider
https://github.com/pagefaultgames/pokerogue/assets/68144167/d68a3e7d-7aea-43ca-84b2-d2971ca55b13
- set opponent ability to ability with class that extends `TypeImmunityAbAttr` or `MoveImmunityAbAttr`
> [Bug] Add check to ignore ability when using type hints

- src/ui/starter-select-ui-handler.ts
this resolves the inputs being present in the top left of the screen
the input lines from the starter select screen were present on the main menu
The input lines are now being properly hidden when they are not actively placed within the starter select instruction container
prior to my change:
after my change:
prior to this change, opening the game at all would show the small lines of text in the top left of the screen, so
- open the game
- ensure the inputs aren't present in the top left
- go to starter select
- choose a starter with forms/gender/etc. to cycle through
- start your new game
- ensure the inputs aren't present in the top left
> [Bug] Fix inputs being annoying again

- src/phases.ts
I'm not sure if this is the best way to solve this since I'm a programming noob (specially when it comes to OOP), but I just figured that if an experienced developer looks at this PR and does it the proper way then that's a win for everyone, so why not give it a go?
Toxic damage increment now resets when you switch out and then back in, as it's intended.
Note that this doesn't address the issue with poison damage being applied twice in some instances: #830 
I ran into the issue myself and lost my daily run to Pecharunt 😢
There's also an open issue about this: #1723 
Added a simple check in the PostSummonPhase: if the pokémon has Toxic status it resets turnCount to 0.
Before:
https://github.com/pagefaultgames/pokerogue/assets/18709552/ad06d1e8-09dd-4431-ba7c-1e99d09ec5cb
After: …
> [Bug] Fix toxic damage increment not resetting upon switching

- src/phases.ts
Speed ties should no longer vary based on reload.
Speed ties currently resolve differently based on how long it's been since a reload.
Previously, speed ties used the default wave rng offset which can vary based on a reload. This changes them to instead seed based on the current turn, making it consistent across reloads.
Turn the rng debugger on then start a battle in a new save, reload in a new tab/session and retry the same battle. Specifically look at the RNG call made after TurnStartPhase, this should be different without this patch and the same with this patch.
> [Bug] Make speed ties seed based on current turn

- src/data/move.ts
Implement the move [Core Enforcer](https://bulbapedia.bulbagarden.net/wiki/Core_Enforcer_(move)).
Core Enforcer lacked its secondary effect of suppressing the target's ability when used after the target in a turn.
Added a new `MoveEffectAttr` called `SuppressAbilitiesIfActedAttr`. This basically just calls `SuppressAbilitiesAttr` under the hood; since this move succeeds regardless of whether the suppression happens, we need to make a separate effect with no extra condition.
Also fixed the text for ability suppression to include `'s` at the start.
Case 1: Core Enforcer is used after the Slaking moves. Slaking's ability Truant is suppressed and it can use a move on the next turn.
https://github.com/pagefaultgames/pokerogue/assets/6374275/1fbb9c50-ee01-4a4e-a1a6-6dac5c553bb6
Case 2: Core …
> [Move] Implement Core Enforcer

- src/locales/zh_CN/challenges.ts
> [localization] fixing typo in zh_cn challenge.ts

- src/modifier/modifier-type.ts
Remove the Map from being found on waves 190-200
This is because you cannot change the biome in those waves anyway
Before vs After
> [QoL] Remove Map item from being the shop on waves 180-200

- src/locales/zh_CN/achv.ts
a new set of zh_cn achv names.
These names are discussed and translated by 4 zh_cn translators.
Jokes and references from original english names are also translated into the new names
adding translation of missing mono-type achv names.
the previous translation is rough and not accurate, missing several monotype achv names.
achv.ts in zh_cn
> [Localization]new proofread zh_cn achv names updated

- src/locales/it/nature.ts
- Changed `Naive : "Ingenuaa"`  to `Naive :"Ingenua"` 
The typo was bugging me
I removed the typo double a at the end of the italian word "ingenua"
Left side is local change, rightside old result
Set language to Italian, select a pokemon with "naive" nature (ingenua)
* Note that intimidate test is not passing, with or without the change
src/test/abilities/intimidate.test.ts > Abilities - Intimidate > INTIMIDATE
AssertionError: expected undefined not to be undefined
❯ src/test/abilities/intimidate.test.ts:50:53
48| 
49| 
50|     expect(game.scene.getParty()[0].summonData).not.toBeUndefined();
|                                                     ^
51|     let battleStatsPokemon = game.scene.getParty()[0].summonData.battleStats;
52|     expect(battleStatsPokemon[BattleStat.ATK]).toBe(0);
> [Localization] naive typo fix (was ingenuaa is now ingenua)

- src/locales/zh_TW/battle.ts
- src/locales/zh_TW/modifier-type.ts
- src/locales/zh_TW/move.ts
Corrected all 只 that should be 隻
There are some cases where Traditional Chinese characters are simplified into the same Simplified Chinese character, such as 隻 and 只 both becoming 只.
These are sometimes not caught by translators like Google Translate when translating from Simplied back into Traditional, leading to incorrect translations. 
This was the case here, localization was done in Simplified first and someone translated it into Traditional without correcting it.
Other cases like 后->后,後 and 里->里,裡 are correctly translated.
Several letters in `src/locales/zh_TW`
> [Localization] Fixed mistranslation of 只 in Traditional Chinese

- src/phases.ts
- src/test/abilities/intimidate.test.ts
Fixed the bug where the opponent would trigger his postSummon abilities at the start of each turn instead of just after he summons.
Before: The opponent's postSummon abilities were triggered at the start of every turn.
After: The opponent's postSummon abilities are now only triggered after he summons, as intended.
To test these changes:
1. Checkout the branch with these fixes.
2. Start a game session and observe the opponent's behavior at the start of each turn and after summoning.
3. Ensure that abilities are not triggered at the start of the turn but only after summoning.
4. Run all unit tests using `npm run test` to ensure no other functionalities are broken.
> [Bug] Fix Opponent Abilities Triggering at Start of Turn instead only after summon

- src/locales/en/achv.ts
Changes the names of monotype achievements.
Several of the names somehow didn't make it in.
The localisation entries for english for the monotype achievement names changed.
> Fix english names of monotype achievements

- src/locales/fr/ability.ts
Changed rKSSystem to rksSystem varable in French ability.ts
rksSystem varable in French ability.ts file was wrong
Corrected rksSystem varable name in French
> Correction to French ability.ts

- src/battle-scene.ts
- src/phases.ts
- src/test/moves/spikes.test.ts
- src/test/utils/TextInterceptor.ts
- src/test/utils/gameManager.ts
This PR introduces a fix to the handling of the PostSummonPhase for abilities like Intimidate and entry hazards. It ensures that the phase is triggered correctly after a Pokémon is switched into battle.
- The PostSummonPhase for the opponent was triggered prematurely, causing issues with ability and entry hazard activation.
- A solution was implemented, but did not work for subsequent switches.
- Introduced a conditional phase execution mechanism.
- The PostSummonPhase is now queued and only executed when specific conditions (like the correct number of Pokémon on the field) are met.
- This ensures abilities like Intimidate and entry hazards trigger correctly after switches.
Run all unit tests (`npm run test`) to ensure no existing functionality is broken.
> [Bug Fix] Correct PostSummonPhase Timing for Abilities and Entry Hazards

- src/data/pokemon-level-moves.ts
Confusion and Metal Claw are level 1 moves, not on-evo moves
To make the data more accurate
Changed from 0 (on evo) to 1
n/a
pull
> [Bug] Metagross level up moveset changes

- src/locales/es/battle.ts
-Updated battle.ts
I decided to introduce these changes to improve the overall user experience, particularly for Spanish-speaking players who may not understand English well.
Translated fainted pokemon.
> [Localization] [ES] Fainted Pokemon localization

- src/battle-scene.ts
- src/overrides.ts
- src/ui/stats-container.ts
The IVs chart is now golden in case all IVs are perfect.
Dynamic colors for the IV chart was already part of a different mod so i thought i might as well as this effectively only requires one line of code to change.
Though the additional code for testing overrides added some more changes...
The IV chart shown for new captures and starters will now appear golden, in case all IVs are perfect (31).
This color change is also animated on the starter selection screen.
For testing purposes the following overrides have been introduced:
- `OPP_IVS_OVERRIDE : integer | integer[]`
This may take an integer to replace all enemy IVs or an array with each element replacing the respective IV.
- `window.perfectIVsChartColor`
This global variable can be set by the user and changes the default golden color …
> [Enhancement] Golden IVs Chart when all IVs are perfect

- src/locales/it/ability-trigger.ts
- src/locales/it/achv.ts
- src/locales/it/menu-ui-handler.ts
Achievements now localized in Italian.
Changed the main menu "Risultati" to "Trofei" as "Risultati" is more akin to "consequences" in Italian.
Context on "Trofei" change
The translation was needed in achv.ts and my professional opinion is that "Risultati" is a bit ambiguous in this instance.
As Achievements is not directly translatable (e.g. Steam keeps it in English) I would advise against using "risultati" here as a user would not know what happens when they select it.
As a professional translator and developer, I'm hoping to be able to contribute to this awesome project, by providing some simple PR for translation before maybe getting involved with some new features in the future. 
Feel free to reach out about it.
All of the achievements in  src/locales/it/achv.ts translated to italian …
> [Localization] Italian achievements (achv.ts)

- index.css
Fix the display size of inputs which is MUCH too small, and should be dependent on screen size rather than a fixed value
Replaces the value in fixed units with a relative unit in `index.css`
> Before
> After
By displaying the login page from this branch
> [Enhancement][ui] Fix the display size of inputs

- src/phases.ts
- not technically caused by the recent type hint change https://github.com/pagefaultgames/pokerogue/pull/2105
- a pokemon's ability outside of battle is being activated - which should have not, thats why battleData is undefined, hence the error
- see [video](https://discord.com/channels/1125469663833370665/1125894949020381285/1250517257642315837)
- **it seems to happen to mons with Scrappy ability**
- hotfixes above bug
- added if condition
(Video)[https://discord.com/channels/1125469663833370665/1125894949020381285/1250519161549885650]
- get to wave 167 https://discord.com/channels/1125469663833370665/1125894949020381285/1250513165339328634
> [Bug] Hotfix type hint

- src/data/ability.ts
- src/test/abilities/sap_sipper.test.ts
- src/test/battle/ability-type-immunity.test.ts
Revival of #240.
Type immunity abilities (such as Levitate and Sap Sipper) apply to non-field status moves, not just attacks.
Fixes #278. The current behavior of these abilities is incorrect.
In `TypeImmunityAbAttr.applyPreDefend()`, instead of just blocking attacks, block any move that does not target the field. Also remove an incorrect check there for `StatusMoveTypeImmunityAttr`, since that attribute applies to types of Pokemon, not types of Moves.
Add tests for Sap Sipper.
The provided unit tests should be enough to verify the functionality. If you want to test it on the current build, consider these overrides:
```ts
export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.BIDOOF;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.SPORE];
export const OPP_ABILITY_OVERRIDE: …
```
> [Move] Fix type immunities granted by abilities only applying to attacks

- src/test/abilities/intimidate.test.ts
- src/test/moves/spikes.test.ts
- src/test/utils/gameManager.ts
Convert `async gameManager.switchPokemon()` to `game.doSwitchPokemon()`
So that the game manager menu utility matches the utilities that do the same thing 
Convert `async gameManager.switchPokemon()` to `game.doSwitchPokemon()`
Add missing `.run()` and `.to()` invokations
npm run test:silent
> [Test] Update gameManager switchPokemon to match other menu utilities

- src/field/pokemon.ts
- Add condition if pokemon with ability `IgnoreTypeImmunityAbAttr` is active/on field
- `IgnoreTypeImmunityAbAttr` is currently being used by abilities `SCRAPPY` and `MINDS_EYE`
[Mind's Eye](https://bulbapedia.bulbagarden.net/wiki/Mind%27s_Eye_(Ability)):
> Outside of battle
> Mind's Eye has no effect outside of battle.
[Scrappy](https://bulbapedia.bulbagarden.net/wiki/Scrappy_(Ability)):
> Outside of battle
> Scrappy has no effect outside of battle. 
- closes https://github.com/pagefaultgames/pokerogue/issues/2148
- added condition before applying `IgnoreTypeImmunityAbAttr`
- Kangaskhan's Scrappy no longer procs outside of battle
https://github.com/pagefaultgames/pokerogue/assets/68144167/9bad84f1-23fe-46b7-92e7-745578dbd464
- import [session …
> [Bug] Add condition before applying IgnoreTypeImmunityAbAttr

- src/field/pokemon.ts
- src/modifier/modifier.ts
The sprite now reloads during instant revive
Fixes #2151
Added an option in `Pokemon.resetStatus` to reload assets
`PokemonInstantReviveModifier.apply` now reloads assets
Not sure if there are still any other cases other than `PokemonInstantReviveModifier` where this is necessary.
When Mew is revived during transform:
Before
After
In `overrides.ts`,
`export const MOVESET_OVERRIDE: Array<Moves> = [Moves.TRANSFORM];`
`export const STARTING_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [{name: "REVIVER_SEED"}];`
And start a game, transform, die, revive.
> [Bug] Fixed reviving while transformed not resetting the sprite

- src/field/arena.ts
A small change to how arenas are initialised to prevent a bug where sometimes the biome pools are initialised before the time of day is.
Sometimes during loading the biome pools will be initialised before the current wave is, causing it to generate biome pools as if you were on wave 0.
Update the biome pools during the initialise function of arenas instead of just the constructor.
You'll need a debugger so you can look at the actual biome pools, but after reload a save the game can be using the wave 0 encounter table instead of the correct table.
> [BUG] Add secondary update to biome pool loading

- src/modifier/modifier-type.ts
Adds a new ability to the list of abilities that spawn Toxic Orb or Flame Orb.
Highly requested addition in the discord and allows for more strategies for players to utilize.
Added Magic Guard to the list of abilities that spawn Toxic Orb or Flame Orb.
Tested with a Pikachu that has Magic Guard
Bring a Magic Guard Pokemon and reroll for an orb
> [Balance] Add Magic Guard to the list of Flame/Toxic Orb Abilities

- src/ui/party-ui-handler.ts
Add a red tint to the quantity of an item in the transfer menu if it's at it's limit
Someone asked for it in the Discord, it makes sense and is visually pleasing
Changed the quantity color from default white to red
Before vs After
```js
export const STARTING_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [
{
name: "BERRY",
count: 2,
type: BerryType.SITRUS
},
{
name: "BERRY",
count: 1,
type: BerryType.LUM
}
];
```
> [QoL] Add red color to the quantity if the item is at it's held limit

- src/ui/settings/abstract-settings-ui-handler.ts
- src/ui/settings/settings-audio-ui-handler.ts
- fixes scroll behavior of audio settings
- closes #2172 
- added condition to check if all rows are filled
- Audio settings 
https://github.com/pagefaultgames/pokerogue/assets/68144167/55e730c6-0007-4204-9eaf-bc685ebf6096
- General and Display settings still work fine
https://github.com/pagefaultgames/pokerogue/assets/68144167/f55bca7e-12ac-40b5-93f8-a181459e3ddb
- go to settings and navigate
> [Bug] Fix audio setting scroll behavior

- src/system/settings/settings.ts
After you switch language or cancel switching language, the option cursor now resets back to being on the language instead of on "change"
The way switching language works right now is, you have to move from your language to change for the options to pop up.
However, after switching languages, the cursor stayed on change, you have to move back to your language then back to change to switch languages again. 
It makes more sense for the cursor to be hovering over the new language instead of on change, and makes it a bit more convenient for people testing localization changes.
`cancelHandler` when setting language
1. Switch languages
2. Go to settings again
> [QoL] Language option cursor resets after cancelling or switching language

- src/ui/game-stats-ui-handler.ts
Fixed mythical pokemon hatched
Mythical pokemon hatched was displaying legend pokemon hatched
Changed legendary -> mythical
n/a
pull
> [Bug] Fix mythical pokemon hatched stat

- src/locales/es/move.ts
- src/locales/fr/move.ts
- src/locales/it/move.ts
- src/locales/ko/move.ts
- src/locales/zh_CN/move.ts
- src/locales/zh_TW/move.ts
Updated bouncy bubble description
It should say 100% of damage dealt as healing instead of 50%
Changed es, fr, it, ko, and both zh localizations for bouncy bubble. Let me know if I've severely butchered anything
n/a
Pull
> [Localization] Fix bouncy bubble description for es fr it ko zh

- public/images/pokemon/variant/exp/666-meadow_2.json
- public/images/pokemon/variant/exp/666-meadow_3.json
Rare and epic shiny Meadow Pattern Vivillon (n666)'s Experimental animations are now appropriate for its spritesheet, instead of taken from the non-shiny spritesheet, and which uses a completely different sprite.
It's been reported! A lot!
https://discord.com/channels/1125469663833370665/1238339524778790922/1250180831469899808
https://discord.com/channels/1125469663833370665/1238339524778790922/1250018721729220668
https://discord.com/channels/1125469663833370665/1238339524778790922/1250018721729220668
And yeah, ideally the animation a Pokemon gets is the right one for its sprite.
Took the animation frame data from Fancy Vivillon (rare), which animates properly and has an identically shaped spritesheet.
This does mean the Texture Packer link is now Not Correct, and a new one was not …
> [Bug] Fix Animation for Variant Exp Meadow Vivillon 

- src/locales/it/achv.ts
Changed most of the achievements' names, added the missing ones
Basically, all of the achievements names were reworked to make more sense in italian
I'm making these changes kinda basing myself on the model of Minecraft Achievements, where they all have funny names based on the achievement, i think that model can work pretty well and since i noticed most of the achievements' names made no sense in italian i figured I'd fix them. 
To test the changes, you can check out the in game achievements' names in italian.
> Update achv.ts [Localization]

- src/ui/starter-select-ui-handler.ts
A QOL improvement on a visual element to see which rarity variant your pokemon sprite is on.
For fun! Plus, I've had personal confusion with not knowing for sure which was the rarer sprite and this helps making my team cooler :P.
Changed so that the trigger variant button would cycle variant color on the variant label based on associated sprite rarity between standard, rare and epic shiny variants.
Made sure that changing pokemon would successfully trigger the correct variant color on immediate change. // this was a pain to understand
https://github.com/pagefaultgames/pokerogue/assets/112661751/bff28e71-29a2-44b4-b532-71953e124d8f
No override changes or automated tests included.
> Variant Label Color Change [QOL]

- src/data/ability.ts
Frisking an ability now sets the revealedAbility flag
Fixes #2233
`FriskAbAttr.applyPostSummon()` now sets flag.
In `override.ts`
```
export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.WATER_ABSORB;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.LIQUIDATION];
export const ABILITY_OVERRIDE: Abilities = Abilities.FRISK;
```
Liquidation should now be x0 once Water Absorb is frisked.
> [BUG] Fixed frisk not setting revealedAbility flag

- src/data/biomes.ts
Simply removes random trailing commas from [src/data/biomes.ts](https://github.com/pagefaultgames/pokerogue/blob/main/src/data/biomes.ts)
As per [NalysArbur's request](https://discord.com/channels/1125469663833370665/1176874654015684739/1251391743916769332)
No functionality changes
> [ESLint] Remove random trailing commas

- src/locales/fr/ability-trigger.ts
- src/locales/fr/achv.ts
- src/locales/fr/battle.ts
- src/locales/fr/challenges.ts
- src/locales/fr/fight-ui-handler.ts
- src/locales/fr/party-ui-handler.ts
- src/locales/fr/pokemon-info-container.ts
- src/locales/fr/trainers.ts
Translate missing translation for the french language.
Because a lot of text isn't translated.
A lot of sentences and words are translated in french.
Select the french language and go in-game.
> [Localization] Fix french translations

- src/data/dialogue.ts
- src/locales/de/dialogue.ts
- src/locales/en/dialogue.ts
- src/locales/es/dialogue.ts
- src/locales/fr/dialogue.ts
- src/locales/it/dialogue.ts
- src/locales/ko/dialogue.ts
- src/locales/pt_BR/dialogue.ts
- src/locales/zh_CN/dialogue.ts
- src/locales/zh_TW/dialogue.ts
1. Add missing dialogue for Alder Champion encounter.
2. Add missing dialogue for Kieran Champion encounter.
1. Alder and Kieran were missing dialogue making their encounters in Classic mode bland (and weird).
1. Now when Alder or Kieran are encountered as the Champion, the dialogue should carry out as normal.
1. overrides.ts:
```export const STARTING_WAVE_OVERRIDE: integer = 190;```
2. Kieran session:
[kieran.txt](https://github.com/user-attachments/files/15799833/kieran.txt)
3. Alder session:
[alder.txt](https://github.com/user-attachments/files/15799964/alder.txt)
> [Feature] Add Missing Champion Dialogue

- src/data/ability.ts
- refactors https://github.com/pagefaultgames/pokerogue/pull/2238 , added to Trace as well
- set `revealedAbility` for traced ability
- set `revealedAbility` for traced ability
- refactor for Frisk
https://github.com/pagefaultgames/pokerogue/assets/68144167/2699e0ae-b503-4c8a-9083-400c8afa7e3d
- `export const ABILITY_OVERRIDE: Abilities = Abilities.TRACE;`
- `export const MOVESET_OVERRIDE: Array<Moves> = [Moves.EMBER];`
- `export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.FLASH_FIRE;`
Ember should be displayed as 0x/grayed out
> [Bug] Add revealedAbility for trace, refactor for frisk

- src/ui/starter-select-ui-handler.ts
Setting cursor to 0 (previously -1).
To fix issue #2260 
this.cursor is set to -1 after quitting the new game UI. When entering this UI again, we use the cursor (-1) to set a variable species on line 1724. species ends up being undefined and this causes the black screen.
The black screen issue is not happening anymore.
Before : 
https://github.com/pagefaultgames/pokerogue/assets/28794446/d9ca52c6-daa0-4af9-81e4-0da710612e23
After : 
https://github.com/pagefaultgames/pokerogue/assets/28794446/5ad4ec2e-cab3-4723-99f1-ebb2c390bce3
1. Go to New Game > Classic
2. Press on X to quit
3. Go to New Game > Classic 
4. No black screen.
> [Bug] Issue #2260 Fix black screen on new game after exiting.

- src/data/ability.ts
- src/data/move.ts
- src/field/pokemon.ts
- src/phases.ts
- src/test/abilities/unseen_fist.test.ts
This implements the effects of the ability [Unseen Fist](https://bulbapedia.bulbagarden.net/wiki/Unseen_Fist_(Ability)).
Unseen Fist isn't currently implemented, and with most (if not all) protection moves now implemented, it's possible to cover all edge cases and fully implement this ability.
- `data/ability`: A new attribute `IgnoreProtectOnContactAbAttr` is added, along with a global (`export`) function that checks if the attribute can be applied. Unseen Fist is now given this attribute.
- `field/pokemon`, `data/move`, and `phases`: All protection checks account for Unseen Fist using the function `data/ability#canApplyIgnoreProtectOnContact()`.
For both test videos below, Pokemon and moves are preset using `src/overrides.ts`
- All battles are forced to be double battles.
- The player's …
> [Ability] Implement Unseen Fist

- src/data/move.ts
Implementing the move poltergeist. This was already coded in [this PR](https://github.com/pagefaultgames/pokerogue/pull/281) but was closed du to inactivity
Unimplemented move
Added AttackedByItemAttr for moves that used opponent's transferable held item (ie not vitamins) to work and added this attribute to poltergeist
The move fails if the opponent has no transferable held item
https://github.com/pagefaultgames/pokerogue/assets/56865723/d8f20516-0fba-470b-8486-ee0cac6d8596
The move works if the opponent has an held item
https://github.com/pagefaultgames/pokerogue/assets/56865723/83fb6d9b-9122-49d0-8e92-adcf2d7f2ab2
You can modify src/overrides.ts to test the move on an opponent with or without item
> [Move] Implement poltergeist

- src/data/move.ts
Friendship-based moves, which do a percentage of their maximum damage based on the user's percentage of friendship level, were previously only friendship-dependent for `PlayerPokemon` 'mons.
Pokemon in wild encounters would instead find their move to have a base power of minus one.
This PR fixes that, by scaling it to the base friendship for that Species. Essentially, the Move will be exactly as powerful during a wild encounter, as it will be immediately after you've caught them.
This bug affects RETURN, FRUSTRATION, PIKA_POW, and VEEVEE_VOLLEY.
The full effects of the bug are not immediately apparent in the level range of the typical Classic run. At those levels, friendship-based moves *will* be insultingly weaker than other moves, but believably so for moves that mention the bond …
> [Bug] Friendship-based moves have Base Power -1 when Pokemon is wild

- src/locales/zh_CN/fight-ui-handler.ts
zh_cn ability fly in text translation
fight-ui-handler,ts in zh_cn
> [localization] zh_cn ability fly in text translation

- src/locales/zh_CN/growth.ts
growth text in zh_cn
the previous translation has mistakes.
The translation of fast/medium fast and slow/medium slow is reversed
> [localization] fixing growth text in zh_cn

- src/data/move.ts
Previously, [Sappy Seed](https://bulbapedia.bulbagarden.net/wiki/Sappy_Seed_(move)), being a Physical Attack, was assumed to be a contacting attack in the absence of a flag indicating otherwise. This meant users might be accidentally placed in harm's way, whether by [Flame Body](https://bulbapedia.bulbagarden.net/wiki/Flame_Body_(Ability)), [Iron Barbs](https://bulbapedia.bulbagarden.net/wiki/Iron_Barbs_(Ability)), etc.
This PR ensures that Sappy Seed is not a contacting attack, and so doesn't trigger those effects.
Players expecting not to receive contact effects will be surprised if Sappy Seed does not behave as it does in other games, particularly given the other projectile-based Seed moves.
It was reported [here](https://discord.com/channels/1125469663833370665/1251886856673558528). …
> [Move] Sappy Seed shouldn't be Making Contact

- src/modifier/modifier-type.ts
`modifierTypes.NUGGET`, `modifierTypes.BIG_NUGGET`, `modifierTypes.RELIC_GOLD` are useless to roll if player is at wave 199.
Remove them from the pool so trainers have slightly better pulls.
Avoid useless items roll to improve  players experienve.
Created `skipInLastClassicWaveOrDefault`to make it easy to configure what items should be skipped in the pool.
**Classic**
I temporarely set NUGGET weight to 5000 to force all GREAT item rolls to be Nuggets
```ts
new WeightedModifierType(modifierTypes.NUGGET, skipInLastClassicWaveOrDefault(5000)),
```
- On wave 198 almost all GREAT tier items are NUGGETs
- On wave 199 we dont have nuggets any more.
https://github.com/pagefaultgames/pokerogue/assets/31145813/d14848f6-281c-431c-b5a8-16092b713070
**Endless**
Endless still gives nuggets on waves …
> [QoL] Skip money rewards on last classic wave

- src/locales/zh_CN/game-mode.ts
zh_cn game-mode text translation
game-mode.ts in zh_cn
> [localization] zh_cn game-mode text translation

- src/locales/ko/dialogue.ts
This PR is added korean dialogue for **Gym leader in Sinnoh region.** (4th Pokemon Games)
@sodaMelon  @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.
@ Ohmry said he never played original Pokemon Game. so I decide to exclude this time.
(he only played Legend Arceus)
A few trainers's dialogue have been translated into Korean.
I did the others.
I translated **Gym leader,Elite-4 and Champion(in Sinnoh, 4th pokemon)battles' dialogues.**
4세대 체육관 관장+사천왕 + 난천(챔피언) 다이얼로그를 번역했습니다.)
말투 교정에는 정발판 4세대 포켓몬스터DP/기라티나버전 
리메이크 브다샤펄 참고했습니다.
( very hard to meet them.... and it's dosen't matter)
It seems there won't be much to test since it's just a translation of an existing .ts file. You can check …
> [Localization] #1761 Korean trainer dialogue (Sinnoh region)

- src/locales/de/dialogue.ts
- src/locales/es/dialogue.ts
- src/locales/fr/dialogue.ts
- src/locales/it/dialogue.ts
- src/locales/ko/dialogue.ts
- src/locales/zh_CN/dialogue.ts
- src/locales/zh_TW/dialogue.ts
The Dialogue will appear in their native languages
Because it is currently only english
Text in DE, FR, Zh_CN, Ko, It
(DE by myself, others by the wiki team)
For the german version:
Alder:
https://github.com/pagefaultgames/pokerogue/assets/38758606/28913987-c4b7-42e4-9f04-f39d7ee59abe
Kieran:
https://github.com/pagefaultgames/pokerogue/assets/38758606/ed8e536c-234c-4e18-a6a3-ade3403afb17
Let them spawn (by changing battle.ts)
> Added the localized dialogue for alder and kieran

- src/data/ability.ts
- src/test/abilities/screen_cleaner.test.ts
- implements screen cleaner
- implements screen cleaner
- new class `PostSummonRemoveArenaTagAbAttr`
Refer to console logs
https://github.com/pagefaultgames/pokerogue/assets/68144167/939a6ba7-4831-4f6e-ba2d-1cee00e85b23
Unit tests passing
- use Reflect/Light Screen/Aurora Veil
- summon pokemon with Screen Cleaner
> [Ability] Implement Screen Cleaner

- src/field/pokemon.ts
Fix Dark Aura and Fairy Aura not applying a damage bonus
Dark Aura and Fairy Aura don't apply a damage bonus when they should
Find a pokemon with an aura on the field and apply the ability to the move
Add overrides for `Abilities.DARK_AURA` and without and see the damage difference
I can write e2e tests if necessary
> [Bug]: fix dark aura and fairy aura not applying to moves

- src/data/ability.ts
- src/data/move.ts
- src/modifier/modifier.ts
- src/phases.ts
- src/test/abilities/serene_grace.test.ts
- src/test/abilities/sheer_force.test.ts
- src/test/abilities/shield_dust.test.ts
- Added `MoveEffectChanceMultiplierAbAttr` to modify additional effect chances with multipliers.
- Added `IgnoreMoveEffectsAbAttr`; this sets to zero the chance of foe's moves additional effects.
- Changed `AddArenaTrapTagAttr`, `AddBattlerTagAttr`, and `StatusEffectAttr` to allow for modified additional effect chance.
- Added `getSheerForceHitDisableAbCondition` applied to abilities that get disable when hit by a Sheer Force boosted move.
- Added conditions to Poison Touch, Toxic Chain and Stench to be ignored by Shield Dust.
- Changed the additional effect chance of certain moves to make them immune or susceptible to chance modification as according to the main games.
Moves not affected by chance modification were changed to -1 because their effects will always apply.
Moves that are …
> Serene Grace, Shield Dust and Sheer Force partially implemented.

- src/data/move.ts
Fixing freeze form moves like Stone Axe when Sheer Force is activated.
Adding return tag && tag.layers < tag.maxLayers;
> Fix Immediate Sheer Force Klevor Freeze

- src/test/abilities/sturdy.test.ts
Adding tests for Abilities.STURDY
Improving test coverage.
No new changes only new test cases
N/A
` npm run test sturdy.test.ts `
> [ability][test] Add tests to sturdy

- src/ui/starter-select-ui-handler.ts
Follow up of  one of my previous PRs
- https://github.com/pagefaultgames/pokerogue/pull/1933
When a Pokemon does not need to display the  candy count the form text remains on the same place, creating a big empty space between the pokeball icon and the text.
This PR just moves the text up to avoid empty space
I forgot this UI detail on my last PR
Starter select UI form text location for pikachu (no other species has forms and cross gen prevolutions)
**Starters for whose we display eggs and candy are unaffected.**
- Open starter select UI and change Pikachu form
> [enhancement] Move up form text when candies and hatched eggs are hidden

- src/data/move.ts
- Implements `AddArenaTrapTagHitAttr` for moves like Stone Axe and Ceaseless Edge. 
`AddArenaTrapTagHitAttr` applies the given ArenaTrapTag when a move with it hits.
This allows for moves that apply ArenaTrapTags to be affected by Sheer Force.
- Fixes chance for selfstatus moves (No Retreat, Tidy Up, ... ) 
https://github.com/pagefaultgames/pokerogue/assets/43686802/f1d299ee-3dbd-44e2-a974-54dd87bfacd3
https://github.com/pagefaultgames/pokerogue/assets/43686802/af2c236d-5d64-4f93-ae68-2d7fce2f4ebd
https://github.com/pagefaultgames/pokerogue/assets/43686802/8d7d5791-7ad3-4c41-9866-a3af694de48f
https://github.com/pagefaultgames/pokerogue/assets/43686802/0c76e162-d9d8-4379-9ef4-a3aa2ff2b981
https://github.com/pagefaultgames/pokerogue/assets/43686802/b149ffb4-050d-45f7-bb5d-37b70fba365f …
> [Bug] Sheer Force interaction fix (Stone Axe and self status moves)

- src/data/move.ts
- src/field/pokemon.ts
This changes the ability [Prankster](https://bulbapedia.bulbagarden.net/wiki/Prankster_(Ability)) to function as it does in Gen VII+ by giving Dark types immunity to Status moves from a source with the ability.
In its current implementation, Prankster functions as in older generations of the main series without a Dark-type immunity. With this change, Prankster is functionally up to date with the main Pokemon games.
- `move`: `Move.isTypeImmune()` now includes the case of Dark types being immune to *Status moves* from *opponents* with the ability Prankster. The parameters to this function were updated to support this case.
- `move`: `CopyTypeAttr` is no longer a self-targeted attribute. This was changed because if a Pokemon with Prankster used Reflect Type against a Dark-type opponent, the …
> [Ability] Add Dark-type immunity to Prankster

- src/modifier/modifier.ts
Fixes a freeze with U-turn and King's rock
Fixes a freeze
Added a temporary check for if `pokemon.getLastXMoves(0)[0]` is undefined
n/a
https://discord.com/channels/1125469663833370665/1125894949020381285/1252699516419965069
> [Hotfix] uturn with kings rock

- src/locales/ko/trainers.ts
Fix of small typo
수연팬티 -> 수영팬티
'Swim' of Swimmer must be translated by '수영' but it was '수연' so I changed.
```typescript
(-)  "swimmer": "수연팬티 소년",
(+)  "swimmer": "수영팬티 소년",
```
Very small change and hard to meet him.
> [Localization] Korean - fix small typo

- src/data/ability.ts
- src/test/abilities/ice_face.test.ts
- fixes ice face bug being immune to all physical hits from multihit move
- ice face OP. closes #2388 
- replaced base class `MoveImmunityAbAttr` with `ReceivedMoveDamageMultiplierAbAttr`
- added unit test for multihit move
unit test should be enough: `npm run test ice_face`
> [Bug] Fix ice face blocking all hits from multihit moves

- src/locales/ko/settings.ts
Translated missing text to Korean at settings.ts
To make localizable text to be Korean.
See title and files changed
(Manually) Change language to Korean, go to Settings menu.
> [Localization] [Ko] Add translate untranslated settings word

- src/data/ability.ts
- src/form-change-phase.ts
- src/test/abilities/ice_face.test.ts
- fixes issue where game crashes upon using dragon tail on ice face eiscue
- fixes [bug report sent on discord](https://discord.com/channels/1125469663833370665/1252857373890969710) (`scene` is undefined when eiscue is force switched out while transforming)
- added optional chaining to `scene`
https://github.com/pagefaultgames/pokerogue/assets/68144167/fb7704e9-a414-4105-a74a-8993e5f7e04e
- single or double battle
- hit eiscue ice face with dragon tail
> [Bug] Fixes dragon tail vs ice face eiscue interaction

- src/locales/ko/battle.ts
Translate ppReduced message
It's not translated so users who is not used to English are hard to understand.
modify src/locales/ko/battle.ts -> ppReduced
(Referred to Sw/Sh for the Korean translation.)
| As-is | To-be |
| --- | --- |
| ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/10f63d7c-2ebe-4304-bd79-1f016ea4e2fc) | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/5d864547-a8fb-496b-8e16-d770173d8ffb) |
- set `overrides.ts`
```typescript
export const MOVESET_OVERRIDE: Array<Moves> = [ Moves.SPITE ];
```
- Run dev and execute moves 'Spite' and check the message.
> [Localization] [ko] Translate battle:ppReduced message

- src/data/battler-tags.ts
Change localized helping hand message logic.
To fix this message issue.
add missed getPokemonNameWithAffix function to pokemon object.
- test with overrides.ts
- ```DOUBLE_BATTLE_OVERRIDE = true;```
- ```MOVESET_OVERRIDE = [ Moves.HELPING_HAND ];```
> [hotfix] fix message when helping hand

- src/locales/fr/battle.ts
A typo in French battle.ts
To remove e typo
French typo removed in battle.ts
> [Localization] French typo battle.ts

- src/data/ability.ts
Added an undefined check on pokemon.scene
Was causing a crash
Added an undefined check on pokemon.scene
n/a
Manually tested with https://discord.com/channels/1125469663833370665/1252713217738801163/1252719579474563203
> [Bug] Fix bug in doubles after 1 opponent is phazed

- src/data/move.ts
- src/test/moves/gastro_acid.test.ts
Add condition to SuppressAbilityAttr to make the attr fail if the target's ability is already suppressed.
Current behavior deviates from games in that ability suppression effects can happen even if the ability is already suppressed. This means repeated uses of Gastro Acid will be successful instead of failing like they should. This doesn't matter except for if they somehow know Stomping Tantrum, but it's slightly annoying for Core Enforcer users to see the suppression message every time the effect activates.
* Add a check to `SuppressAbilitiesAttr` that fails if the target's ability is already suppressed
* Document `SuppressAbilitiesAttr` and add unit tests for Gastro Acid
Expected behavior:
Current behavior:
https://github.com/pagefaultgames/pokerogue/assets/6374275/6221d350-8b6b-4c6a-b57 …
> [Fix] Ability suppression effects not failing correctly

- src/test/moves/follow_me.test.ts
- src/test/moves/rage_powder.test.ts
- src/test/moves/spotlight.test.ts
This fixes an issue where direct assignment to a Pokemon's HP would sometimes cause the Follow Me, Rage Powder, and Spotlight unit tests to fail.
Other unrelated PRs are sometimes failing tests in part due to this issue.
Damage checks in these unit tests are now based on the enemy's max HP.
N/A
`npm run test`
- [N/A] Are the changes visual?
- [N/A] Have I provided screenshots/videos of the changes?
> [Unit Test] Remove HP assignment from Follow Me, Rage Powder, and Spotlight tests

- src/data/move.ts
- src/field/pokemon.ts
Different browsers will no longer treat Minimize differently for the AI.
Minimize was being chosen inconsistently across browsers and causing other moves to also be used inconsistently.
The minimized battler tag now has a score of 0. In addition if a target's score is NaN it'll now be logged in the console and treated as 0 instead.
Give an AI minimize and some other moves, try in firefox vs chrome and notice that the list of moves sorted by score was different without this patch and consistent with this patch.
> [Bug] Fix Minimize AI and add NaN AI score safeguard

- src/ui/arena-flyout.ts
- fixex multiple traps showing because of moves like Stone Axe and Ceaseless Edge
copied from discord
- arena traps fix (UI)
https://github.com/pagefaultgames/pokerogue/assets/68144167/2093d266-e888-48e4-93a7-3d7f38c93f9d
- use Stealth Rock + Stone Axe
- use Spikes + Ceaseless Edge
> [Bug] Fix arena traps on flyout

- src/data/move.ts
- src/test/moves/thousand_arrows.test.ts
This fixes the issue #2464 where a Pokemon with the move Thousand Arrows grounds opponents before using the move.
Thousand Arrows is not applying its effects properly.
- `data/move`: Fixed an issue where Thousand Arrows would apply the `IGNORE_FLYING` battler tag to opposing Pokemon whenever `Pokemon.apply()` was called, even in simulated calls for UI elements.
- `test/thousand_arrows.test`: New unit test to check battler tag behavior and damage against Flying types.
Can be provided upon request.
`npm run test thousand_arrows`
> [Bug] Fix Thousand Arrows grounding opponents before use

- src/ui/settings/settings-display-ui-handler.ts
language setting mismatch error `prlang=ko-KR`
it is very small issue. 
I'm currently in south korea. of course, the game language setting was `korean`.
so I tried to change language setting `korean` to `english` but game setting ui displayed `English`
After Checking Code, I found prLang on localStorage. When the game FIRST running , it's set `prLang='ko-KR'` by `i18n`.
`src/ui/settings/settings-display-ui-handler.ts` is not managed `prLang='ko-KR'` for swtch case. so, setting language ui displayed `English`.
```typescript
export default class SettingsDisplayUiHandler extends AbstractSettingsUiHandler {
/**
* Creates an instance of SettingsGamepadUiHandler.
*
* @param scene - The BattleScene instance.
* @param mode - The UI mode, optional.
*/
constructor(scene: BattleScene, mode?: Mode) { …
```
> [Bug] troubleshooting language setting mismatch error (prlang=ko-KR)

- src/field/pokemon.ts
- fixes received move damage multiplier not appying other power calculations
- fixes [discord bug report](https://discord.com/channels/1125469663833370665/1253055799874293771) , this is not an Eiscue issue but for any abilities that extend `ReceivedMoveDamageMultiplierAbAttr`
- damage calculations were not yet finished before `ReceivedMoveDamageMultiplierAbAttr` is called
- move where `ReceivedMoveDamageMultiplierAbAttr` is called
- set your mon with an ability that extends `ReceivedMoveDamageMultiplierAbAttr`, check if damage calculation is right with moves like Power Trip
- [session data](https://discord.com/channels/1125469663833370665/1253055799874293771/1253061251387494552)
> [Bug] Fix pre defend power multiplier

- src/battle-scene.ts
- src/ui/modifier-select-ui-handler.ts
The wave is no longer displayed under the overlay as it used to be (even before the black overlay ...)
Its previous color just made it harder to see that the text was underneath the overlay
To better distinguish the current wave
> Before
> After
> [Enhancement] - The wave is no longer displayed under the overlay 

- src/data/egg.ts
Bought eggs where always using rare egg move rates from common tier eggs because the correct egg tier of bought eggs get's set AFTER the egg move was rolled
> Hotfix: Rare Egg move rate from bought eggs where always common tier rates

- src/ui/modifier-select-ui-handler.ts
Avoids 'flashbanging' for players playing at x5 speed by making the transition time constant regardless of the speed chosen
> Before (_at x5 speed_)
https://github.com/pagefaultgames/pokerogue/assets/8146474/717be947-c5e8-4841-9f50-79b730313171
> After (_at x5 speed_)
https://github.com/pagefaultgames/pokerogue/assets/8146474/f3da227c-c58a-4440-abd6-32924d86019a
> [Enhancement] Avoids 'flashbanging' for players in Shop UI

- src/data/ability.ts
- src/test/abilities/aura_break.test.ts
Added functionality to make the Aura Break ability work. I also added the changes from #2246 which are needed in order to make this ability work. Aura Break reverses the effect of the Fairy Aura and Dark Aura abilities, lowering the damage of either fairy or dark moves by 25% depending on which ability the opposing pokemon possesses.
The changes in #2246 are vital to the function of this PR and are the main inspiration behind this PR. The bug previously made implementing this ability difficult, as the effect of fairy aura and dark aura was not clear.
Before this PR, Aura Break, Fairy Aura, and Dark Aura were not functional. The lack of functionality in Fairy Aura and Dark Aura was due to a bug, and I added the functionality for Aura Break. 
With Aura Break …
> [Ability]  Implemented Aura Break

- src/ui/party-ui-handler.ts
Moved the Pokemon fusion icon from the left to the right of the gender icon
Fix issue #2458 
The icon moved
Before
After
You can get some DNA Splicers with this override
```js
export const ITEM_REWARD_OVERRIDE: Array<String> = ["DNA_SPLICERS"];
```
> [QoL] Move fusion icon to right of gender icon in party ui

- src/locales/ko/dialogue.ts
This PR is added korean dialogue for four gym leader in Kalos region (olympia, grant, korrina, clemont).
칼로스 지방 체육관 관장 olympia(고지카), grant(자크로), korrina(코르니), clemont(시트론) 대사를
한국어로 번역 및 로컬라이징 작업을 진행하였습니다.
@sodaMelon @Ohmry @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.
Few trainers's dialogue have been translated into Korean yet.
Translated dialogue of four gym leader in Kalos region (olympia, grant, korrina, clemont) to Korean.
칼로스 지방 체육관 관장 고지카, 자크로, 코르니, 시트론 대사 번역하였습니다..
포켓몬스터 XY 정발 번역을 최대한 참고했습니다만..
자료를 찾지 못할 경우 제가 번역했습니다..
- 고지카 승리대사의 경우 향전체육관에서 트레이너가 승리했을시 나오는 대사임을 영문 위키를 통해 확인하였습니다. 향전체육관 승리 대사 정발 번역을 참고하여 작성하였습니다. (느낌이 좀 많이 다르네요..)
- 자크로 승리대사 또한 정발 번역을 참고하였습니다. 문장부호가 좀 …
> [Localization] #1761 Korean trainer dialogue (olympia, grant, korrina, clemont)

- src/locales/en/battle.ts
- src/locales/es/battle.ts
- src/locales/pt_BR/battle.ts
- src/locales/zh_CN/battle.ts
- src/locales/zh_TW/battle.ts
- Adds punctuation to the message that shows after being freed from wrap
- It was missing punctuation and that looked weird
- Added an exclamation point to the end of battlerTagsTrappedOnRemove where it was missing
- Use a trapping move like Wrap or Whirlpool
- Wait for the opponent to be freed
> [Localization] Fixed missing punctuation when being freed from trapping moves

- src/locales/fr/menu.ts
- src/locales/ko/menu.ts
EDIT : Also added Korean on behalf of [returntoice](https://github.com/returntoice)
Transaltion of "Choose a Pokémon." entry in French
To have it in French
"Choose a Pokémon." entry in translated in French locale menu.ts
> [Localization] "Choose a Pokémon." French & Korean translation

- src/phases.ts
- see title
- fixes bug introduced by https://github.com/pagefaultgames/pokerogue/pull/2244
- closes [discord bug report](https://discord.com/channels/1125469663833370665/1253222114874626139)
- added `!this.pokemon.isFainted()` check
- no longer crashes when entering shop
https://github.com/pagefaultgames/pokerogue/assets/68144167/c644491b-12a3-4fef-8df6-a667a6417ec8
- export [session data](https://discord.com/channels/1125469663833370665/1253222114874626139/1254052071032885259)
- to replicate the bug:
1. Switch to sableye
2. attempt to catch smeargle until success
3. bug occurs upon entering shop because its trying to use the move
> [Bug] Prevent attempting to use a move with no pp when pokemon is not on the field

- src/locales/ko/dialogue.ts
This PR is added korean dialogue for **named trainers in Kalos region.** (6th Pokemon Games)
@sodaMelon  @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.
@ Ohmry said he never played original Pokemon Game. so I decide to exclude this time.
(he only played Legend Arceus)
A few trainers's dialogue have been translated into Korean.
I did the others.
(Maybe this job will be ended next PR. There are only a few left.)
I translated **some Gym leader,Elite-4 and Champion(in Kalos, 6th pokemon)battles' dialogues.**
6세대 체육관 관장 2명+사천왕 + 카르네(챔피언) 다이얼로그를 번역했습니다.)
말투 교정에는 정발판 6세대 포켓몬스터 XY 참고했습니다.
(나머지 체육관 관장들은 다른 분이 해주셨습니다.)
Maybe it's because the background is France, the **English version is …
> [Localization] #1761 Korean trainer dialogue (Kalos region)

- src/field/pokemon.ts
Added undefined/null checks to 2 places where `this.scene` is traced back to from the error
Solves issue #2190 
The bug as discussed in issue #2190 is running away from a battle when one of the opponent pokemon's fainted. This bug doesn't happen anymore and transitions to the next battle.
https://github.com/pagefaultgames/pokerogue/assets/39450497/8b08c31b-a315-473f-9cc3-0009466932bb
Reproduce using roar on one pokemon, and trying to run the next turn.
> [Bug] fix softlock/runtime error after roar in doubles

- src/data/battler-tags.ts
- src/data/move.ts
- src/field/pokemon.ts
- src/phases.ts
- src/test/moves/flower_shield.test.ts
- implemented [flower shield](https://bulbapedia.bulbagarden.net/wiki/Flower_Shield_(move))
- unimplemented move
- implemented flower shield
https://github.com/pagefaultgames/pokerogue/assets/68144167/7de33be2-509b-4bcc-a005-78c2e00be661
- give your mon Flower Shield
- have a grass type mon in field
- `$ npm run test flower_shield`
> [Move] Implement Flower Shield

- src/modifier/modifier.ts
Checks the ModifierType#id when attempting to stack Lures
Fix multiple issues #1912 #2523
Added a check for ModifierType#id to the match(Modifier) method inside the DoubleBattleChanceBoosterModifier class
Before vs After
```ts
export const ITEM_REWARD_OVERRIDE: Array<String> = ["LURE", "SUPER_LURE", "MAX_LURE"];
```
> [Bug] Prevent lures from stacking different tiers

- src/locales/de/battle.ts
- src/locales/en/battle.ts
- src/locales/es/battle.ts
- src/locales/fr/battle.ts
- src/locales/it/battle.ts
- src/locales/ko/battle.ts
- src/locales/pt_BR/battle.ts
- src/locales/pt_BR/egg.ts
- src/locales/zh_CN/battle.ts
- src/locales/zh_TW/battle.ts
- src/system/game-data.ts
> Localization: Add "has been added as a starter!" localization

- src/battle-scene.ts
- fixes crash caused by noice eiscue on arena reset
- unit test did not catch this because the error came from the pokemon's cry 
- when the arena resets, the game loads the noice form audio file (875-no-ice.m4a) instead of the 875.m4a
- my best guess is that the game loads the audio first before the `pokemon.formIndex = 0` was called, hence why it cant find the audio and the game crashes
- change manually setting `pokemon.formIndex = 0` to `triggerPokemonFormChange()`
https://github.com/pagefaultgames/pokerogue/assets/68144167/d55f0c16-57d8-4f46-9bb6-ed6ecc3f3f19
- use noice eiscue on wave 4, play to wave 5
> [Bug] Fix noice eiscue crashing on arena reset

- src/battle-scene.ts
- added condition to only trigger form change if eiscue is on noice form
- see title
- added condition
- get eiscue until arena resets
> [Bug] Eiscue changing form regardless of previous form on arena reset

- src/field/trainer.ts
- fixes double battle crashes on challenge mode
- `getPlayerField()` always returns 2 pokemons in a double battle, even in a challenge mode where 1 pokemon is ineligible.
- this means it will run `getMatchupScore()` on a non-fielded (ineligible) pokemon, which then causes the game to crash
- change `!isFainted()` to `isAllowedInBattle()`
- added a `filter` to `getPlayerField()`
- no longer crashes the game
https://github.com/pagefaultgames/pokerogue/assets/68144167/2ed72e06-d991-49c4-a5ec-3d5e085c46db
- import [session data](https://discord.com/channels/1125469663833370665/1125894949020381285/1254593572406300683) and get to wave 26
> [Bug] Fix trainer double battle crash

- src/data/ability.ts
- src/test/abilities/libero.test.ts
- src/test/abilities/protean.test.ts
Commented out the Gen 9 once-per-time-on-field condition for Protean and Libero.
Overall a better change for the player experience, especially with how battles can swap environments constantly.
// Commented out and labelled the .condition for both Protean and Libero
https://github.com/pagefaultgames/pokerogue/assets/21964105/55ea8412-8a6a-4bf9-8374-d62edb997e59
Grab any pokemon with Protean or Libero and spam moves of different types.
> [Balance] Protean / Libero changed to Gen 6-8 Implementation

- src/data/trainer-config.ts
- src/locales/en/dialogue.ts
* Fixed a typo in Archie's dialogue
* Tweaked team strength of evil boss rematch
* Rearranged Pokemon on the evil boss teams for consistency
Players were saying the evil bosses are too easy 😭 
Currently both evil team boss fights use the team comp of RIVAL_5 (1 strong, 4 average, 1 strong).
This change makes the evil team boss rematch use the team comp of ELITE_FOUR (2 average, 3 strong, 1 stronger)
I've also moved the slots of the Pokemon around so the stronger slot should be on the legendary.
TL:DR
Old: 153, 150, 150, 150, 153
New: 150, 150, 153, 153, 153, 159
Player cap: 162
Pull and test
> [Enhancement] Slight tweak to evil boss teams

- src/field/trainer.ts
With https://github.com/pagefaultgames/pokerogue/commit/2bab7d3778f988beafba7f0b93ddac774792ff03 there was a bug introduced causing enemy trainers not to send out pokemons anymore.
I did some debugging and found that there was division `/0` happening which might be causing this issue.
To fix this bug
I've added a length check on the `playerfield` variable before calculating the `score`
- Download [this](https://cdn.discordapp.com/attachments/1176874654015684739/1254993704075133000/sessionData_Guest.prsv?ex=667b8377&is=667a31f7&hm=c9acabd9356c814dde04754b7f2347a7aa6256a1d3d54b26d9a32056fc48ec89&) session file from discord
- Import it into your local instance
- make sure to edit `overrides.ts`
- ```ts
// ...
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.EXPLOSION];
// ...
```
- play …
> Fix enemy trainers not sending out pokemon

- src/data/egg.ts
- src/test/eggs/egg.test.ts
The legendary egg machine does not increase the higher tier egg rate; this PR fixes that issue.
I pulled hundreds of eggs today and noticed that legendary pulls were significantly rarer than they used to be. This prompted me to analyze the related code, where I found a suspicious line causing this behavior.
The egg tier generation is handled by the `rollEggTier` method of the `Egg` class. It determines the tier by referencing a pre-defined value of the `_sourceType` property. The current code defines `_sourceType` after invoking the `rollEggTier` method, causing the generator function to ignore the source gacha machine. I simply swapped two lines in the constructor function so that `_sourceType` is defined beforehand.
You can run a partial unit test with `npm run test -- …
> [Bug] Legendary pull rate fix from Leg. up machine

- src/data/egg.ts
Egg pity should take owned eggs into account when rolling for an unowned speces since you will own that species after hatching.
Bug report from discord.
Within the egg pity function, the species pool gets filtered by species owned from eggs to.
Hard to test. Best would be to have a save with just like 3 pokemon of the same tier left and pulling that tier a bunch of times and see if the pity eggs have no duplicated pokemon
> [BUG] Egg pity should take owned eggs into account if rolled for species

- src/locales/fr/battle.ts
There is an extra '[' in the french message when your pokemon is infatuated
One line of localized text
> [Localization] Fixed typo in infatuation message

- src/locales/ko/dialogue.ts
This PR is added korean dialogue for 3, 7, 9th Elite-4&Champions. 
@sodaMelon  @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.
@ Ohmry said he never played original Pokemon Game. so I decide to exclude this time.
(he only played Legend Arceus)
A few trainers's dialogue have been translated into Korean.
I did the others.
this pr is **last one** for /ko/dialogue.ts. 🙌
I translated **Elite-4 and Champion(in 3rd, 7th, 9th pokemon)battles' dialogues.**
I referred to the official game that released in Korea. (ORAS, SM&USUM, SV)
- 3세대는 정발 ORAS와 대사가 거의 비슷합니다. 
-> (드물게 영문판과 대사 내용이 멀어져있다면,) 정발판 대사를 따라갔다고 봐주세요.
- 7세대는 썬문 울썬문 사천왕&챔피언전 정발판을 확인해보고는 있는데, 영어판 대사 내용이 조금 달라요.
-> 그래서 일단은 영문판에 …
> [Localization] #1761 Korean trainer dialogue (for 3, 7, 9th Elite-4&Champions) 

- src/data/ability.ts
- src/field/pokemon.ts
- src/test/abilities/dry_skin.test.ts
- Fixed Dry Skin's damage during sunlight not applying to Pokemon at maximum health
- Fixed ReceivedMoveDamageMultiplierAbAttr not working for all values != 0 (i.e. it was broken for everything except Ice Face), which fixes the damage modification part of the following abilities: Filter, Solid Rock, Multiscale, Fur Coat, Fluffy, Shadow Shield, Prism Armor, Punk Rock, Ice Scales, Thick Fat, Heatproof, Dry Skin, Water Bubble, Purifying Salt, Disguise
- Added tests for Dry Skin
- Bug fixes
- ReceivedMoveDamageMultiplierAbAttr changes damage instead of power in pokemon.ts
- PostWeatherLapseDamageAbAttr is fixed to damage Pokemon at max HP in ability.ts
- Renamed "power" to "damage" in ReceivedMoveDamageMultiplierAbAttr and friends (checking Bulbapedia, it's indeed appropriate to scale damage …
> [Bug] Fix Dry Skin and ReceivedMoveDamageMultiplierAbAttr abilities

- src/data/ability.ts
- src/test/abilities/disguise.test.ts
- adjusts the damage taken by disguise from flat 1 damage to 1/8 of user's max hp
- damage taken is now consistent to [bulba](https://bulbapedia.bulbagarden.net/wiki/Disguise_(Ability))
- damage taken by disguise
`$ npm run test disguise`
> [Ability] Adjust damage taken by disguise

- src/ui/starter-select-ui-handler.ts
Add back gender/attribute info saving on pokemon when exiting starter loadout.
Accidentally removed on a previous UI Icon rebase
Should only fix the issue with saving information
> [Bug] Add back saved loadout info

- src/ui/starter-select-ui-handler.ts
Fixed persistent Shiny Icon over pokemon that were not shiny.
To fix a bug from https://github.com/pagefaultgames/pokerogue/pull/2372
The shiny Icon was visible on pokemon that were not shiny. Now, that bug should be fixed by using the same logic as the luck sprite does
https://github.com/pagefaultgames/pokerogue/assets/112661751/a176b54b-c8fe-4a13-a51f-b5da0dc2714c
https://github.com/pagefaultgames/pokerogue/assets/112661751/3e4ab1a9-977d-4069-b33a-6ee19439298e
> [BUG] Fixed Persistent ShinyIcon

- src/locales/de/battle.ts
- src/locales/en/battle.ts
- src/locales/es/battle.ts
- src/locales/fr/battle.ts
- src/locales/it/battle.ts
- src/locales/ko/battle.ts
- src/locales/pt_BR/battle.ts
- src/locales/zh_CN/battle.ts
- src/locales/zh_TW/battle.ts
- src/phases.ts
Add the option to localize message text when you receive modifier.
All text should be localizable.
- Change the code for localize.
- Added localization key in each language folders.
- Translated it to Korean.
| Lang | Result |
| :-----: | :---: |
| En | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/0b428d42-bef0-4a8d-931f-94391442df72) |
| De | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/cb718b1b-6fbf-4457-840f-eb64634fd399) |
| Es | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/80526db2-b4dd-4b56-a525-c9e7d50816cf) |
| Fr | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/346d7abd-b99f-4dab-8505-b1a3c18e3f4f) |
| Ko | ![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/b3f98d9d-8445 …
> localize reward message (You received ~)

- src/locales/en/dialogue.ts
Added a period to Cyrus1's dialogue. Removed a comma form Lucian's dialogue.
They are now grammatically correct
Fixes
Before: https://github.com/pagefaultgames/pokerogue/issues/2609
After
Pull and test
> Fix 2 typos in Cyrus and Lucian en dialogue

- src/field/pokemon.ts
- src/system/pokemon-data.ts
add boss-segments to into pokemon-data & load it in EnemyPokemon constructor
I've added the boss segments number to the pokemon-data to persist it throughout reloads
fixes #1697
Previously (as described here: https://github.com/pagefaultgames/pokerogue/issues/1697#issuecomment-2189151817) the boss segments were inconsistent with hard-coded trainers. This should fix it
persisting the segments into the pokemon-data object (which is saved to the session)
https://github.com/pagefaultgames/pokerogue/assets/50131232/da15b8ef-48f1-4770-aa23-985d66420e56
overrides.ts
```ts
export const STARTING_WAVE_OVERRIDE: integer = 145;
```
- Start a new game
- count the boss sections on the first trainer pokemon
- reload
- continue
- check again -> Should be still 2
- **The failing test is a known and not my …
> Fix boss-segment reload issue

- src/test/abilities/quick_draw.test.ts
Optimize the quick draw tests so they don't take so long
Quick draw tests are timing out when run in CI
Stop the phase interceptor right before the faint phase before checking if the ability was applied / the pokemon have fainted
`pnpm test:silent`
> [Test] Optimize Quick Draw tests

- src/modifier/modifier-type.ts
Adjusted Super EXP Charm, Form Change Items, Mega Bracelet/Band, and Voucher Plus (to only drop weight by 1 each reroll, making it take another reroll to disappear)
Super EXP Charms appearing too often, Mega Bracelet/Band still a problem to lead into the form change item changes, and Voucher Plus disappeared too quickly.
Adjustments to last list of changes.
Super EXP Charm - 9 -> 8
Voucher Plus - 3 weight, 2 descending per reroll to 0 -> 3 weight, 1 descending per reroll to 0
Form Change Items - 5 base x wave count multiple of 50 = 20 max -> 6 base x wave count multiple of 50 = 24 max
Mega Bracelet - 8 base x wave count multiple of 50 = 32 max -> 9 base x wave count of 50 = 36 max
Dynamax Band - 8 base x wave count multiple of 50 = 32 max -> 9 base x wave count of 50 = 36 max
Math.
> [Balance] Quick Adjustments to Rogue Tier Items

- src/test/abilities/dry_skin.test.ts
The Dry Skin ability tests no longer fail due to randomness of the generated player Pokémon's ability.
Tests failing due to randomness causes workflow problems.
Add an ability override for the player Pokémon to prevent the test from randomly failing if the test generates a player Pokémon with an ability that modifies the battle state (ie: Drizzle). The change is to line 29 of `src/test/abilities/dry_skin.test.ts`.
`npm run test:silent dry_skin`
> [Bug] Prevent RNG from breaking Dry Skin tests

- src/modifier/modifier.ts
Fixes stat booster held items (evolution and species stat boosters by extension) applying to all party members in battle even if they're not the member holding the item. 
Allowed other members to benefit from another member holding a stat boosting item (i.e., Pikachu would get the stat boost from Light Ball in battle despite another member holding it) which is unintended.
Added a `super.getArgs(args)` call to the overridden `getArgs` function in `StatBoosterModifier`.
N/A
Pick a starting Pokemon that would benefit from any of the stat booster items (Eviolite, Light Ball, etc.) and pick another that doesn't. The choices I used were Pikachu and Geodude with the following override to get Light Ball:
```ts
export const ITEM_REWARD_OVERRIDE: Array<String> = [ "SPECIES_STAT_BOOSTER" ];
``` …
> [Hotfix] Stat Booster Held Items Applying to Entire Party

- src/data/move.ts
Changes make it rain to provide stat changes whenever the move hits multiple times, ie with Multi Lens.
A simple flip from true to false for make it rain, to change "firstHitOnly" to false.
I assume the original intention for making it true was for double battles, to make it so the stat debuff isn't applied twice when you hit two pokemon, however it isn't working this way anyway, and is only effecting when you use the move with Multi-lens.
line 8260, ".attr(StatChangeAttr, BattleStat.SPATK, -1, true, null, true, true)" 
changed to:
line 8260, ".attr(StatChangeAttr, BattleStat.SPATK, -1, true, null, true, false)"
First video shows Make It Rain before this change and it's behavior, I do have Contrary on but I promise it works the same without contrary. …
> [Fix] Make It Rain interaction with Multi Lens

- src/data/battler-tags.ts
- src/field/pokemon.ts
- src/phases.ts
This fixes a bug where a spread move (e.g. Earthquake) from a source holding Multi-Lens only strikes each target once if one of those targets is protected or has an ability that nullifies damage.
This bug was reported in the Discord. You can see Discharge incorrectly stopping in the video below
https://github.com/pagefaultgames/pokerogue/assets/168692175/351fee92-c861-45af-a32a-1654a8437415
The user also provided beautiful artwork of the move's current behavior:
`Pokemon.stopMultiHit()` now has an optional `target` parameter. If `target` is specified, the target is removed from the `targets` list in `MoveEffectPhase` for future strikes of the move.
The video below shows Earthquake hitting the opponents multiple times despite the user's ally using Protect in the same turn. …
> [Bug] Fix multi-hit early stopping on spread moves

- src/test/abilities/dry_skin.test.ts
More instances of potential randomness were removed from the Dry Skin tests.
Further potential for RNG to cause the test to fail was pointed out in Discord.
The player and opponent Pokémon are now manually set, and the random damage roll (normally 85%-100%) is now always the same in the test that checks damage. Also, the opponent was set to a fire-type Pokémon to prevent the Burn status from interfering.
`npm run test:silent dry_skin`
> [Bug] Remove more RNG from Dry Skin tests

- src/data/ability.ts
This fixes a bug where if a Pokemon with Parental Bond uses a spread move (e.g. Dragon Energy), and it KO's the first opponent it hits, Parental Bond will apply a 0.25x damage multiplier when it hits the next opponent.
This bug was reported in the Discord: https://discord.com/channels/1125469663833370665/1255747592348766420
`data/ability`: Parental Bond can no longer apply its damage multiplier on the first hit of a move.
N/A
`npm run test parental_bond`
> [Bug] Fix Parental Bond multiplier sometimes applying during first strike

- src/data/move.ts
Fixes Raging Fury, Barb Barrage, and Triple Arrows, three moves that were making contact when they shouldn't have been making contact.
The moves making contact constituted unexpected behaviour, as events that trigger upon contact would, including Abilities, when they shouldn't have.
The `makesContact` attribute was used to tell the game that those moves do not make contact, despite being Physical Moves.
Overrides can help, by giving Pokemon these Moves, and the target Pokemon an Ability like Iron Barbs.
> [Bug] More non-contacting physical moves

- src/data/move.ts
Tidy up is broken right now.
This should close #2629.
Eventually close #2649 since either of these PRs are a duplicate
Tidy up is being applied to both sides due to the arena-trap clearing but it's also boosting the stats more times then necessary making it extremely strong right now
I've added a condition to the `StatusChangeAttr` to only apply when `user.id === target.id` (since the target is the enemy pkm on the second apply)
https://github.com/pagefaultgames/pokerogue/assets/50131232/af54beb5-83fe-4267-ab82-2e93d809b3d1
```ts
export const MOVESET_OVERRIDE: Array<Moves> = [ Moves.STEALTH_ROCK, Moves.TOXIC_SPIKES, Moves.DRAGON_DANCE, Moves.TIDY_UP ];
```
```ts
export const OPP_SPECIES_OVERRIDE: Species | integer = Species.MAGIKARP;
```
```ts
export const OPP_MOVESET_OVERRIDE: …
```
> [BUG] Fix Tidy-Up boosting stats multiple times right now

- src/data/move.ts
1. Fixes Tidy Up buff to only go up 1 stage as intended.
1. Fixes: https://github.com/pagefaultgames/pokerogue/issues/2629
1. Changes the both sides targeting so that the calculation didn't run twice.
overrides.ts: ```export const MOVESET_OVERRIDE: Array<Moves> = [Moves.TIDY_UP];```
> [Bug} Fix Tidy Up buff

- src/data/move.ts
- src/test/moves/make_it_rain.test.ts
This fixes a bug where if Make It Rain KO's the last of the Pokemon it targets, it will not reduce the user's Sp. Atk. for that hit.
Make It Rain is still bugged after earlier fixes (#2664 ) :(
- `data/move`: The `lastTargetOnlyCondition` used by Make It Rain now accounts for the target fainting from the move's current strike.
- `test/moves/make_it_rain.test`: New test case checking effects for when the target faints.
n/a
`npm run test make_it_rain`
> [Bug] Fix Make It Rain not applying effect on KO

- src/field/pokemon.ts
- src/phases.ts
fix boss segments not being overwritten by some code when loading a session that is a double battle.
closes #2668
Right now when you reload in a double battle the boss segments are reduced after loading back in
remove some odd logic changing the segments on load even though there is a persisted value
https://github.com/pagefaultgames/pokerogue/assets/50131232/0998761e-9cf8-43bc-93a2-1701e8614629
1. import [this](https://cdn.discordapp.com/attachments/1256001530033606772/1256023015234207825/2668_debug-session-data.prsv?ex=667f4216&is=667df096&hm=78631e8d6b25619b83b67acca221425ef85667d33531fb5533864c095862b73e&) session data into a slot
2. Move 1 wave ahead by defeating the previous one
3. Count the boss segments
4. `Esc` and Save & Quit.
5. Load the same session
6. Count the boss segments …
> [Bug] Fix Boss segments for double-battles (in endless?)

- src/data/pokemon-forms.ts
Small fix so that Xerneas can properly switch between it's Neutral form and it's Active form.
It is currently just permanently stuck in Neutral form, even when in battle.
A new entry for Xerneas in the `pokemon-forms.ts` file so it can change forms now.
Start a game with Xerneas and something else. Switch between the two in battle and Xerneas will change forms.
> [Bug] Fix Xerneas not changing from Neutral form

- src/test/abilities/dry_skin.test.ts
The Dry Skin test is modified to disable opponents' berries.
The player Pokémon's ability is set to Unnerve to prevent opponents' randomly spawned berries from activating.
`npm run test dry_skin`
> [Fix] Prevent berries from interfering with Dry Skin tests

- src/data/pokemon-species.ts
Pyroar's hair differs based on gender, similarly to lions in real life. As a result, their icons now reflects this difference.
Pyroar was added to the list of Pokemon where a female-form icon should be used when the Pokemon is female.
Overrides can be used to generate a Pyroar, as well as give them a held item.
> [Sprite] Implement female Pyroar icon

- src/test/abilities/volt_absorb.test.ts
A mocked value in the Volt Absorb test is fixed so that it properly applies.
The hidden ability of Duskull can rarely be rolled and randomly interfere with the test.
The opponent's mocked ability is set to Ball Fetch. The previous value of "None" was equivalent to not setting a mocked ability at all, so the Pokémon's normal abilities would be used instead, causing interference when the hidden ability of Frisk was randomly rolled.
`npm test volt_absorb`
> [Bug] Fix mocked value in Volt Absorb test

- src/data/move.ts
- src/test/moves/purify.test.ts
Changing purify implementation, to match real behavior ([bulbapedia link](https://bulbapedia.bulbagarden.net/wiki/Purify_(move)))
Purify implementation. 
- Move depends on the target status and not on the user status.
- Move cures target status not user status
**Fails when opponent does not have a status**
https://github.com/pagefaultgames/pokerogue/assets/31145813/dedcbbb5-d3a6-4160-8243-47e3c2f6da62
**Works when opponent has a status**
https://github.com/pagefaultgames/pokerogue/assets/31145813/ab3ca94b-b13d-4854-9d14-4ff2bb8b1d4c
**Does not heal user status**
https://github.com/pagefaultgames/pokerogue/assets/31145813/4cf2edc3-ac17-41b1-bf89-c049443d7634
`npm run test purify`
> [move] Fix purify implementation

- src/data/pokeball.ts
- src/modifier/modifier-type.ts
- src/modifier/modifier.ts
There are two places where we check the user shouldn't have more than 99 pokeballs. 
- The Pokeball modifier that adds 5 Pokeballs to your bag.
- The item roll modifier that checks if player has the max ammount of balls in order to avoid rolling this item
This change just makes both of them to use the same variable.
Avoiding hardcoded constants.
NA
NA
NA
> [miscellaneous] Create single variable for max pokeballs

- src/test/moves/tidy_up.test.ts
Adds unit tests for the move Tidy Up.
Increasing test coverage.
Tests for hazard clearing and stat boosting were added, plus a stub for substitute clearing to be finished once that move is implemented.
`npm run test tidy_up`
> [Test] Add tests for Tidy Up

- src/data/move.ts
- src/phases.ts
- src/test/moves/make_it_rain.test.ts
This fixes a bug where if Make It Rain KO's both opponents in a double battle, the user's Sp. Atk. is lowered twice.
Make It Rain is (still) not working as intended.
- `data/move`: Added a `firstTargetOnly` parameter to `MoveEffectAttr`. Make It Rain now uses this parameter for its stat change effect.
- `phases`: Added logic in `MoveEffectPhase` to support the `firstTargetOnly` option. This is basically the old logic for `firstHitOnly` from before general changes to multi-hit logic, so Make It Rain's stat change should now function as it used to before then.
The video below shows how Make It Rain behaves after the changes in two edge cases that cause problems upstream:
1. Player uses Make It Rain, and it KO's both opponents (on main, this sharply reduces the user's Sp. Atk.)
2. In a …
> [Bug] Fix Make It Rain applying stat change twice after KO'ing both opponents

- public/images/pokemon_icons_7.json
Now that all Mimikyu-disguised form sprites are indicated as such in the game files, they should have been changed here too.
When the game can't find `778-disguised`, since those icons are currently named merely `778`, they default to the first sprite on the icon spritesheet, Melmetal.
Icons previously named `778` are now named `778-disguised`.
Look at Mimikyu's icon in Starter Select.
> [Sprite] One more Mimikyu Disguised form tag

- src/modifier/modifier-type.ts
Remove Amulet Coin and Golden Punch from Wave 199 Classic rewards
They were missed in the initial change
Added `skipInLastClassicWaveOrDefault` to `AMULET_COIN` and `GOLDEN_PUNCH`
```ts
export const STARTING_WAVE_OVERRIDE: integer = 199;
```
> [QoL] Remove money modifiers from last wave of classic

- src/field/pokemon.ts
This fixes an issue where multi-hit moves are not cancelled when the user falls asleep or is frozen mid-move (e.g. from the target's Effect Spore)
Multi-hit moves currently continue to hit the opponent even after the user falls asleep or freezes.
`field/pokemon`: `trySetStatus` now stops the user's multi-hit move if it has one in progress when the effect is `SLEEP` or `FREEZE`.
https://github.com/pagefaultgames/pokerogue/assets/168692175/265f328e-98cf-4b6d-8cc7-60deb135cd3c
These steps were used for the test video above:
- `data/ability`: Change `EffectSporeAttr` to only afflict `StatusEffect.SLEEP`.
- `overrides`: Give your starter Population Bomb and Compound Eyes, and set the opponent to a bulky Pokemon (e.g. Snorlax) that only knows Splash.
> [Bug] Fix multi-hit moves persisting after sleep/freeze

- src/test/abilities/parental_bond.test.ts
This changes several of the Parental Bond unit tests to stop before the `BerryPhase` instead of after, stopping random berry spawns from causing the tests to fail.
Some of the Parental Bond tests have randomly failed due to enemies sometimes spawning with Sitrus berries, which threw off damage comparisons.
`test/abilities/parental_bond.test`: Many tests now stop before the `BerryPhase` instead of before the `TurnEndPhase`.
N/A
`npm run test parental_bond`
> [Unit test] Remove random berry effects from Parental Bond tests

- src/field/pokemon.ts
This change fixes a bug where freezing an opponent with a Multi-Lens-boosted attack move (e.g. Ice Beam) would cancel subsequent strikes of the move.
This bug was reported [in the Discord](https://discord.com/channels/1125469663833370665/1256914504844054560).
- `field/pokemon`: `this.stopMultiHit()` now checks that the `MoveEffectPhase`'s source move originated from `this`. As a result, calling `p.stopMultiHit()` for a Pokemon `p` should no longer affect any other Pokemon's moves.
Ice Beam + Multi-Lens' behavior after the changes:
https://github.com/pagefaultgames/pokerogue/assets/168692175/9ec92255-cf10-4ca9-a230-93364898f953
To reproduce the results from the video:
- `data/move`: Set the `chance` field of `Moves.ICE_BEAM` to 100 in `allMoves`
- `overrides`: Give your starter Ice Beam …
> [Bug] Fix multi-hit moves stopping if the move freezes an opponent

- src/field/pokemon.ts
Correct type for move effectiveness
Fix https://github.com/pagefaultgames/pokerogue/issues/2756
Convert incorrect type (Boolean into Number)
Before:
After:
```javascript
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.SHEER_COLD];
export const OPP_SPECIES_OVERRIDE: Species | integer = Species.JYNX;
```
> [Bug] Fix incorrect move effectiveness

- src/ui/starter-select-ui-handler.ts
Display how many ETERNATUS eggs the player has hatched.
Previously Egg count was hidden for ETERNATUS, because it was imposible to hatch Eternatus eggs.
Now that eggs are buyable  with candy ETERNATUS egg count should be visible.
Deleted special logic for handling ETERNATUS icons.
This also fixes:
- https://github.com/pagefaultgames/pokerogue/issues/2693
This PR also reintroduces changes made at:
- https://github.com/pagefaultgames/pokerogue/pull/2359
Since they where unintentionally removed at:
- https://github.com/pagefaultgames/pokerogue/pull/2372
**BEFORE**
**AFTER**
Openning starter select UI
> [bug][ui] Fix eternatus candy count and display hatched egg count

- src/phases.ts
- src/test/abilities/sand_veil.test.ts
- src/test/lokalisation/status-effect.test.ts
This fixes a bug where when a Pokemon uses a spread move in a double battle, the evasiveness multipliers from the first target are applied to all targets.
This bug was reported in the [Discord](https://discord.com/channels/1125469663833370665/1257436464942284880)
- `phases`: `MoveEffectPhase.hitCheck()` now bases evasiveness multipliers off of the `target` argument instead of `getTarget()`, which always returns the first active target.
- `test/abilities/sand_veil.test`: New test to check that Sand Veil applies its effects correctly to the user (and only to the user).
- `test/lokalisation/status-effect.test`: Fixed a broken import that sometimes caused `npm run test` to fail.
N/A
`npm run test sand_veil`
- [n/a] Have I provided screenshots/videos of the …
> [Bug] Fix evasion multiplier in hit check

- .env.beta
- .env.production
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy.yml
- package.json
- src/utils.ts
This commit adds a new GitHub Actions workflow file, deploy-beta.yml, which is responsible for deploying the application to the beta environment.
This commits changes the deploy.yml GitHub Actions workflow file to only trigger a deploy to the production environment when a release is generated.
Adding support for the new beta environment.
Added deploy-beta.yml and changed deploy.yml triggers.
> [Beta] Add deployment workflow for beta environment

- src/form-change-phase.ts
Eternatus was resetting stat stages on changing form.
Per discussion on discord, this is a bug. The reason why it has two buffing moves is its meant to keep the stat boosts.
Remove the stat stage reset on changing form.
KO eternatus at wave 200, without this PR it'll lose the stat boosts its acquired on changing form, with it it'll keep them.
> [Bug] Let eternatus keep stat changes when changing form

- src/locales/ko/modifier-type.ts
I fixed their punctuation position correctly
Asdar(@InnocentGameDev) asked me to check [PR#1696](https://github.com/pagefaultgames/pokerogue/pull/1696) in pokerogue wiki Discord channel.
it's not serious problem, but will look better than previous
Now, punctuation point exist at the end of sentence.
(It doesn't have to put it after the parentheses.)
I just moved punctuation point.
really simple question, so I didn't take it.
You can make those items appear as a reward.
~~- [ ] Are the changes visual?~~
> [Localization] punctuation fix in descriptions in korean modifier-type.ts

- src/data/ability.ts
The ability Magic Guard will block damage from making contact with a pokemon with the Iron Barbs or Rough Skin abilities. 
I saw this issue in the Discord's #bug-reports channel - https://discord.com/channels/1125469663833370665/1258512208762241096 
ApplyPostContactDamageAbAttr now checks if the attacking pokemon's current ability has a BlockNonDirectDamageAbAttr before applying damage. 
Recording #1: Starly has Rough Skin + Bulbasaur has Magic Guard
https://github.com/pagefaultgames/pokerogue/assets/171087428/22ce1669-1be6-447f-9d1b-79ab9e1a7940
Recording #2: Sunkern has Iron Barbs + Bulbasaur has Magic Guard
https://github.com/pagefaultgames/pokerogue/assets/171087428/2dfb138d-1020-4e39-8aba-5ec7a5041430
I changed these settings in overrides.ts 
I am trying to write a test for Magic …
> [Bug] Magic Guard blocks damage from Iron Barbs/Rough Skin

- src/battle-scene.ts
- src/locales/de/common.ts
- src/locales/de/pokemon-info-container.ts
- src/locales/en/common.ts
- src/locales/en/pokemon-info-container.ts
- src/locales/es/common.ts
- src/locales/es/pokemon-info-container.ts
- src/locales/fr/common.ts
- src/locales/fr/pokemon-info-container.ts
- src/locales/it/common.ts
- src/locales/it/pokemon-info-container.ts
- src/locales/ko/common.ts
- src/locales/ko/pokemon-info-container.ts
- src/locales/pt_BR/common.ts
- src/locales/pt_BR/pokemon-info-container.ts
- src/locales/zh_CN/common.ts
- src/locales/zh_CN/pokemon-info-container.ts
- src/locales/zh_TW/common.ts
- src/locales/zh_TW/pokemon-info-container.ts
- src/ui/battle-info.ts
- src/ui/pokemon-info-container.ts
- src/ui/starter-select-ui-handler.ts
- src/ui/summary-ui-handler.ts
Localization of the luck text and the shiny text that appears OnHover
They weren't localized
There was only an existing localization in the pokemon-info-container for the shiny rarities, so I revamped it.
Added entries for each word and, since the shiny and luck texts were used in 3 different files each, I added them to the `common` locale folder.
Check every screen that the text appears.
> Localization: Localize luck indicator text and shiny labels

- src/data/move.ts
Solves the issue of https://github.com/pagefaultgames/pokerogue/issues/2778
Sacrificial moves like final gambit and memento will now check for the move hitting before the sacrifice occurs.
Sacrificial moves should not cause the pokemon to faint if the move is going to fail.
The SacrificialAttrOnHit attribute now uses the HIT MoveEffectTrigger so that the pokemon using the move is not sacrificed if the move does not hit the target.
https://github.com/pagefaultgames/pokerogue/assets/98116601/c4a6596e-41f3-4e91-b20f-5061fc460052
https://github.com/pagefaultgames/pokerogue/assets/98116601/fdc44479-bd7e-4a5f-8f0e-7b8e96127681
https://github.com/pagefaultgames/pokerogue/assets/98116601/96a0afcb-77e7-45a5-bb2e-0dade58f731b
https://github.com/pagefaultgames/pokerogue/assets/98116601/a5da7f86-e6de- …
> [BUG] Fixes SacrificialAttrOnHit attribute so that the pokemon does not faint if the move (final gambit, memento) fails

- src/data/ability.ts
- src/data/battler-tags.ts
Pokemon with Magic Guard should be immune to Spiky Shield damage post-contact. 
Extension of this PR - https://github.com/pagefaultgames/pokerogue/pull/2793
I didn't realize that Spiky Shield wasn't covered by Magic Guard, my bad!
ContactDamageProtectedTag now checks if the attacking pokemon's current ability has a BlockNonDirectDamageAbAttr before applying damage.
Bulbasaur with Magic Guard + Tailow with Spiky Shield
https://github.com/pagefaultgames/pokerogue/assets/171087428/f29d7766-6549-423c-b75e-77b7c9f8da92
I used overrides to force a testable scenario.
> [BUG] Magic Guard-Spiky Shield Fix 

- src/locales/de/battle.ts
- src/locales/en/battle.ts
- src/locales/es/battle.ts
- src/locales/fr/battle.ts
- src/locales/it/battle.ts
- src/locales/ko/battle.ts
- src/locales/pt_BR/battle.ts
- src/locales/zh_CN/battle.ts
- src/locales/zh_TW/battle.ts
- src/phases.ts
It now uses the Gen 9 Format of "attackMissed". (Showing which pokemon was missed). Also localizable
Line from the orignal games:
https://abcboy101.github.io/poke-corpus/#id=sv.btl_set.BTL_STRID_SET_WazaAvoid
Because we in the wiki discord agreed that localizing the Gen 4 Message was not what we wanted.
See Video
Before:
https://github.com/pagefaultgames/pokerogue/assets/38758606/df45c8a2-a811-405e-969c-f846779273c0
After: 
https://github.com/pagefaultgames/pokerogue/assets/38758606/c5222d9e-15d2-41ed-8906-6b3be3a22dad
Use a KO-Move for the single target. 
For Multi Target set accuracy for earth quake for example to 1
- Only with https://github.com/pagefaultgames/pokerogue/pull/2806 which was closed 
- Technically yes. But its pointless to split this up in 2 (making it localizable and the …
> [Localization] Attack missed text is now localizable and uses the Gen 9 format instead of Gen 4 like before

- src/data/move.ts
- src/phases.ts
- src/test/moves/focus_punch.test.ts
This adds a new phase, `MoveHeaderPhase`, which takes place before all moves in a turn and applies all the `MoveHeaderAttr` attributes of a move.
At the moment, the only move that uses a Move Header is Focus Punch for its pre-move message, but the intent is to reimplement Beak Blast and Shell Trap using the new phase and attributes.
For more information, see [this branch's PR for the live branch](https://github.com/pagefaultgames/pokerogue/pull/2716).
> [Enhancement] Add Move Header phase and attributes

- src/ui/fight-ui-handler.ts
- src/ui/summary-ui-handler.ts
This PR makes it so when you go to the summary screen during a battle, it shows you the type effectiveness of moves against the enemy team (if you have the type effectiveness setting on)
I've reused the code from the type effectiveness section for moves during a fight and have put it in the summary screen for moves when you go to switch out pokemon during a battle
Someone suggested to make it, so here we are
I added logic for the move page of the summary screen to check the type effectiveness of each move. It reuses the same logic as the current type effectiveness, so that means it doesn't know about abilities until they're used - as an example, if a pokemon has levitate but you don't know about it yet, using a ground type ability may show as super effective in the right conditions until …
> Type move on pokemon switch

- src/battle-scene.ts
- src/data/pokemon-evolutions.ts
Second attempt at making Gimmighoul's Roaming form available, now with less crashing due to not missing the evolution method anymore.
It was otherwise sitting in the game's files unused, and it's just another flavor form.
Gimmighoul's Roaming form has a chance to appear in the wild now, and will evolve into Gholdengo with the same friendship method.
Either force an encounter with Gimmighoul, or go through the Temple biome until you naturally encounter one. It should no longer cause issues when being automatically evolved up into Gholdengo now.
> [Enhancement] Allow Roaming Form Gimmighoul to be caught

- src/ui/confirm-ui-handler.ts
Github didn't match my changes since it wasn't looking at beta and was looking at main instead. This change is necessary for confirm-ui-handler.ts to work in starter-select
Relevant PRs:
https://github.com/pagefaultgames/pokerogue/pull/2865
https://github.com/pagefaultgames/pokerogue/pull/2862
> [Beta][Bug] Update confirm-ui-handler.ts

- src/phases.ts
Made the screen inversion part of OHKO moves tied to move animations
closes https://github.com/pagefaultgames/pokerogue/issues/2491
The OHKO screen flash is unpleasant to people prone to seizures or epilepsy
Added an `if (this.scene.moveAnimations)` to check that move animations are on before inverting the scene
[![](https://cdn.discordapp.com/attachments/1176874654015684739/1254085546632941638/image.png?ex=667835ae&is=6676e42e&hm=e9d1a11d91b7764a92404db5ef7274b353f98dca1be8f4f967f5a642b3981832&)](https://github.com/pagefaultgames/pokerogue/assets/163687446/311c602d-a6f9-4374-a245-5d7919b179fa)
Override no guard and a OHKO move then turn move animations on and off
> [Accessbility] Remove screen inversion if move animations are off

- src/locales/ko/config.ts
Change import path of Korean locale config
Import path is /es/ so Korean translation of form is not working.
Modify import path
Manually.
> [Hotfix][Localization] Modify wrong import path (ko config)

- src/locales/ko/egg.ts
- src/locales/ko/settings.ts
- src/locales/ko/starter-select-ui-handler.ts
- src/ui/egg-gacha-ui-handler.ts
Changed Korean text 'shiny' and some gacha machine text.
1. Gacha machine text could be resized, so changed the text to be clear for understanding.
2. Modified 'Shiny' translation to be closer to the original game.
1. Changed gacha machine font size, position of text for Korean.
2. Changed 'Shiny' text.
1.
2.
Manually.
1. Go to 'Egg Gacha' menu from title.
2. Go to 'New Game' and select a Pokémon that has both Normal and Shiny Pokémon registered.
> [Localization][ko] Modify Korean 'shiny' and gacha texts to match original

- src/locales/de/config.ts
- src/locales/de/modifier.ts
- src/locales/en/config.ts
- src/locales/en/modifier.ts
- src/locales/es/config.ts
- src/locales/es/modifier.ts
- src/locales/fr/config.ts
- src/locales/fr/modifier.ts
- src/locales/it/config.ts
- src/locales/it/modifier.ts
- src/locales/ko/config.ts
- src/locales/ko/modifier.ts
- src/locales/pt_BR/config.ts
- src/locales/pt_BR/modifier.ts
- src/locales/zh_CN/config.ts
- src/locales/zh_CN/modifier.ts
- src/locales/zh_TW/config.ts
- src/locales/zh_TW/modifier.ts
- src/modifier/modifier.ts
Add the option to localize message text when specific modifier applied.
- survive damage : FOCUS_BAND (10%)
- hit heal : SHELL_BELL
- turn heal : LEFTOVERS
- instant revive pokemon : REVIVER_SEED
- money interest : COIN_CASE (each 10 turn)
- turn held item transfer : MINI_BLACK_HOLE
- contact held item transfer : GRIP_CLAW (10%)
- enemy turn heal : ENEMY_HEAL
All text should be localizable.
In particular, these messages are harder for non-English users to see when messages go by quickly.
- Change the code for localize > src/modifier/modifier.ts
- Added locale files, config, localization keys in each language folders.
- Translated them to Korean.
- Modified hit heal, turn heal English message to match original games.
<details>
<summary>Detail (Click to expand)</summary>
| Case | Result |
| …
> [Localization] localize modifier.ts apply event message & translate in Korean

- src/field/arena.ts
- src/game-mode.ts
- src/test/game-mode.test.ts
Stop trainers from spawning near fixed battles
Players don't want generic trainers spawning too close to fixed trainers
Changed `waveIndex` to `w`
```ts
const fixedWaves = [5,8,25,35,55,62,64,66,95,112,114,115,145,165,182,184,186,188,190,195];
function isWaveTrainer(waveIndex: number, offSetGym: boolean) {
let allow = true;
if ((waveIndex % 30) === (offSetGym ? 0 : 20)) {
return true;
}
const waveBase = Math.floor(waveIndex / 10) * 10;
for (let w = Math.max(waveIndex - 3, waveBase + 2); w <= Math.min(waveIndex + 3, waveBase + 9); w++) {
if (w === waveIndex) {
continue;
}
if ((w % 30) === (offSetGym ? 0 : 20) || fixedWaves.includes(w)) {
allow = false;
break;
}
}
return allow;
}
let x = "";
let y = "";
for (let i = 1; i < 200; i++) {
if (isWaveTrainer(i, true) === false) {
x += i;
x += " …
```
> [Feature] Stop random trainers from spawning near fixed battles

- src/test/abilities/costar.test.ts
Fix Costar test so ability RNG doesn't break the test.
Specify an ability for the opposing Pokémon in the first test so they can't have Arena Trap, Shadow Tag, etc which prevents the switching required for the test.
`npm run test costar`
> [Test] Prevent Arena Trap/etc from breaking Costar test

- src/data/move.ts
#2790
Metronome calling a ChargeAttr move (e.g. Beak Blast) will freeze the game.
Fixes a bug that freezes the game.
I implemented a check to see if the user has the move in their moveset, if not create a dummy PokemonMove for the case of Metronome and pass it into pushMovePhase.
Before fix (game freezes from getMove)
https://github.com/pagefaultgames/pokerogue/assets/62030095/05761910-0c3d-4c66-8d1a-0ac40c5c226e
After fix 
https://github.com/pagefaultgames/pokerogue/assets/62030095/34db36ab-a938-4110-9664-d9e39ca102b0
Give your pokemon Metronome and manipulate the moveId variable in RandomMoveAttr to always use Beak Blast 
``` const moveId = moveIds[585];```
Use Metronome with Beak Blast, see that game continues properly and Beak Blast goes off.
> [BETA] [BUG] Fixes bug with Metronome freezing the game

- src/modifier/modifier-type.ts
- src/modifier/modifier.ts
- src/overrides.ts
- src/phases/select-modifier-phase.ts
- src/ui/modifier-select-ui-handler.ts
This PR is a mirror of both #2266 and #2320 for the `beta` branch.
Both PRs were combined since they're both effectively "new" overrides and are relatively small; as such, the main aim of this PR is to make sure they don't break anything unintentionally.
It's worth noting that because #2824 shifts the `SelectModifierPhase` to its own file, the logic used for the fee waiving overrides was also shifted to this file. This was a relatively straightforward change, but this specifically differs from the `main` branch PRs.
> [Beta] Modifier/Item Override Refactor + Fee Waiving Overrides

- src/locales/zh_CN/move.ts
Fix Zh-CN linebreak again
Some move description text is too long and not fully displayed.
Inserted '\n', considering both punctuation and the length of the sentence.
before:
after:
> [Localization]Fixed Zh-CN linebreak

- src/data/trainer-config.ts
- src/field/pokemon.ts
Opposing trainer Mega/Gmax Pokemon now display names correctly without needing to reload
Names were not accurate
Added `p.generateName()` to all hardcoded Pokemon with special formIndexes
Before:
After:
Override a champion or evil team boss or rival 6 fight
> [Bug] Hardcoded Pokemon should have proper names

- src/field/pokemon.ts
- src/test/battle/battle.test.ts
The damage calc and a related test are updated.
The damage calc contained an off-by-one error.
The random damage roll is changed to be 85-100% instead of 85-99% by changing `randBattleSeedInt(15)` to `randBattleSeedInt(16)` in the damage calc formula, and a related test in `src/test/battle/battle.test.ts` is updated to reflect this change.
Uh... use the developer tools in your browser I guess?
> [Bug] Fix off-by-one error in damage calc

- src/system/settings/settings.ts
- src/ui/bgm-bar.ts
- src/ui/settings/abstract-settings-ui-handler.ts
Found during my previous PR #2603, and pointed out by a user on the Discord [here](https://discord.com/channels/1125469663833370665/1256331738318376960/1256331738318376960)
When the bgm-bar is first initialized, it takes on its maximum size, and remains empty. Most likely a residual behavior from its former mode of operation (when it was supposed to be displayed not only in the pause menu)
I've managed to solve this problem.
I've also made sure that displaying/hiding the bgm-bar is no longer dependent on a reboot.
As well as enabling the bgm-bar by default, as it is now displayed in the pause menu, contrary to what was originally intended when it was disabled by default.
> Before
> After
Activate/deactivate the bgm-bar in the options, and check that the behavior is normal.
> [Bugfix] Fix a bug during bgm-bar initialization

- src/battle-scene.ts
- src/locales/de/settings.ts
- src/locales/en/dialogue.ts
- src/locales/en/settings.ts
- src/locales/es/settings.ts
- src/locales/fr/settings.ts
- src/locales/it/settings.ts
- src/locales/ko/settings.ts
- src/locales/pt_BR/settings.ts
- src/locales/zh_CN/settings.ts
- src/locales/zh_TW/settings.ts
- src/system/settings/settings.ts
- see title
- option is only up to 90%
- some players are still not happy with how dark/light the current opacity is
- adding option instead would allow users to customize their experience
- new Shop Overlay Opacity setting
- Menu
- 90%
- 80% (default)
- 70%
- 60%
- 50%
- 40%
- 30%
- 20%
- 10%
- get to shop phase
- change overlay value and check the change
> [Enhancement][QoL] Add option to adjust shop overlay opacity

- src/data/battler-tags.ts
- src/field/pokemon.ts
- src/test/abilities/parental_bond.test.ts
- src/test/moves/astonish.test.ts
This fixes a bug were some battler tags that don't use the `TURN_END` lapse type would incorrectly get removed at the end of the turn they are applied.
`Pokemon.lapseTags(BattlerTagLapseType.TURN_END)` currently checks all of the Pokemon's battler tags and removes them if their turn count is below 1. This is necessary check for the current implementation of the "flinching" mechanic, but it also creates some nasty side effects for other tag types. Many tags that use a lapse type where `turnCount` is irrelevant set their `turnCount` to 0, 1, or `null`, so when `Pokemon.lapseTags` is called at the end of a turn, it wrongfully detects that those tags have expired and removes them. Spirit Shackle and Thousand Arrows are some examples of moves with effects that incorrectly lapse out.
- …
> [Bug] Fix battler tags lapsing at incorrect times

- src/locales/fr/pokemon-summary.ts
Changed "Resumé" for "Statut" in French pokemon-summary.ts
"Status" translated as "Résumé" in this context is wrong, it has to be "Statut"
**Before**
**After**
Because the current translation is wrong in this context
Open a Pokémon summary in French while having status issue (frozen, fainted, etc...)
> [Beta][Localization] French translation mistake in pokemon-summary.ts

- src/phases.ts
- src/test/utils/gameManager.ts
- src/ui/target-select-ui-handler.ts
- see title
- high upvotes from [discord](https://discord.com/channels/1125469663833370665/1239820415891935232) and QoL that makes sense
- see title
- changed single target highlights to use arrays
- updated some parameter/variable namings and types to be more descriptive/accurate
- SINGLE BATTLE: Moves targeting multiple mons still function the same
https://github.com/pagefaultgames/pokerogue/assets/68144167/92d70882-6819-4ea3-bc11-dbcd320ffa32
- DOUBLE BATTLE: Moves targeting multiple mons now highlight the targets first
https://github.com/pagefaultgames/pokerogue/assets/68144167/39af97fc-71e1-4ea3-be2d-44f6b239784d
- DOUBLE BATTLE: Moves with single target still function the same
https://github.com/pagefaultgames/pokerogue/assets/68144167/6af1793e-c9dc-45ef-82df-c96509cf5703
- `export …
> [QoL] Highlight targets of multitarget moves instead of immediate execution

- src/test/abilities/dry_skin.test.ts
- src/test/abilities/parental_bond.test.ts
Two tests are updated to enable the override that prevents crits.
The tests used some unnecessary RNG workarounds when the problem was crits all along.
`NEVER_CRIT_OVERRIDE` is set to true for the Dry Skin and Parental Bond tests, and the hacky damage roll workaround is removed since it's not necessary.
`npm run test dry_skin` and `npm run test parental_bond`
> [Test] Update tests to enable no-crits override

- src/data/status-effect.ts
- src/enums/status-effect.ts
- src/overrides.ts
Status effect enum was importing i18 and breaking pre tests
Status effect enum was importing i18 and breaking pre tests
Move Status Effect enum into separate file and explicitly state which enums are just used by typescript in overrides.ts
N/A
`npm run test:silent`
`npm run docs`
~~- [] Are the changes visual?~~
> [Test] Separate enum from i18 import

- src/test/moves/octolock.test.ts
Octolock tests did not have the override import changes implemented in #2999, and are currently broken in beta.
This PR just updates the import.
To fix the tests.
`import * as overrides` (old way) -> `import overrides` (new way)
`npm test`
> [Bug] Fix import of overrides in Octolock test

- src/battle-scene.ts
- src/field/arena.ts
Terrains would persist over to trainer battles. This line would clear any terrains upon entering a Trainer Battle.
closes #2018
https://github.com/pagefaultgames/pokerogue/assets/63990624/1eb9cee7-bc56-49b2-b90e-fd834f33ca9d
Override pokemon ability to Psychic Terrain. Activate it on wave 4. Observe it ends before going into the trainer battle on wave 5.
- [Well... none of the errors have to do with this] Are all unit tests still passing? (`npm run test`)
> [Bug] Fix Clear terrains upon Trainer Battle

- src/modifier/modifier-type.ts
Fix item reward overrides going out of bounds
Previous change to override created this error
Iterate over item reward override directly for replacement instead of generated item options
N/A
Get to the item reward screen with an override defined
```ts
ITEM_REWARD_OVERRIDE: ["RARER_CANDY"]
}
```
~~- [] Are the changes visual?~~
> [Bug] Fix item reward overrides going out of bounds

- src/ui/bgm-bar.ts
Prevents the bar from being displayed if `musicText` is completely empty.
This can be the case, for example, when the game's 1st music track takes a long time to reach the client, and the menu is opened before it is played.
Because for the few people with a slow connection, it displays a big ugly rectangle in the menu as long as the music hasn't triggered the `setBgmToBgmBar` method when it starts playing.
Add condition to block display as long as `musicText` is empty
> Before (Current Bêta)
https://github.com/user-attachments/assets/2a08c7d2-f44d-4c2c-a06f-f12062816432
> After
https://github.com/user-attachments/assets/4c467c4b-6d92-432e-a979-9cbf3f896c49
Simply use the browser's "request blocking" mode to block music from the title screen and try to open the menu in this condition after …
> [Fix] BGM Bar display error when the 1st track of the game takes too long to arrive

- src/phases.ts
Fixes bug with Lock-On and Zap Cannon where Zap Cannon misses if Lock-On is the first move on entering battle.
Lock-On should guarantee a hit regardless of when it is used. 
Removed the ```.slice(1)``` call on ```getLastXMoves()``` so that the condition no longer skips over the first turn made.
```getLastXMoves().find(() => true)``` gets the most recent move used in the pokemon's move history.
Before fix
https://github.com/user-attachments/assets/61604fa9-aa54-432a-a6ae-31e14b66b72e
After fix
https://github.com/user-attachments/assets/ac76a790-4e9e-44a6-9f81-2ae97fea80d9
Give your mon Lock-On and Zap Cannon. Go to wave 5 and use Lock-On followed by Zap Cannon. See the result.
Be sure to test multiple times. Lock On should never fail with Zap Cannon.
> [Bug] Fixes bug with Lock-On and Zap Cannon where Zap Cannon misses if Lock-On is the first move on entering battle.

- src/ui/battle-info.ts
Keeps the caught Pokeball indicator and champion ribbon in view when the enemy gets a status effect
Someone asked in [Discord](https://discord.com/channels/1125469663833370665/1258135619247280200)
Added an x offset for the status indicator when Pokeball or Ribbon are shown
Before
After
```ts
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.THUNDER_WAVE]];
```
> [QoL] Offset the status indicator to keep pokeball in view

- src/locales/ko/battle.ts
Mirror #3008 but target changed.
@Tempo-anon
> [Re][Hotfix] Change Korean line-break position of ghost type curse add message

- src/locales/fr/ability-trigger.ts
Correct a typo
I've corrected “Tif Vif” to “Tir Vif”
> Before
> After
> Source
`ability.ts`
`Poképédia`: [Tir Vif](https://www.pokepedia.fr/Tir_Vif)
> [Localization][FR] Fix typo ability-trigger.ts

- src/locales/ko/ability-trigger.ts
is following pr of #3087 
Add Korean translation for trace ability trigger
refered from Pokémon Scarlet and Violet's official translation.
Modify to offcial Korean translation for trace abilities in ability-trigger file to enhance user immersion.
After the PR
Modified a Korean translation for the trace abilities. 
Korean-native players will now see consistent translations, improving their gaming experience and immersion.
[v] There is no overlap with another PR?
[v] The PR is self-contained and cannot be split into smaller PRs?
[v] Have I provided a clear explanation of the changes?
[v] Have I tested the changes (manually)?
[v] Are all unit tests still passing? (npm run test)
> [Localization] Add minor Korean translations to ability-trigger file (trace)

- src/test/moves/multi_target.test.ts
Fixes tests that weren't properly running and removes RNG-based failures from occurring.
The tests randomly failed and messed with my PR. 😢
The player Pokémon's ability is set to Ball Fetch when it's not involved in the tests, and two tests are rewritten so they actually run instead of getting stuck at the Login Phase.
`npm run test multi_target`
> [Test] Fix multi target tests

- src/test/abilities/quick_draw.test.ts
Prevents the Quick Draw tests from randomly failing because the opponent Pokémon happened to gets it's hidden ability Hustle.
Made a PR to fix a test, and this one randomly failed when run in that PR. 😠
The enemy Pokémon's ability is now set to Ball Fetch. Also minor style changes since I was already there.
`npm run test quick_draw`
> [Test] Fix quick draw tests

- src/modifier/modifier.ts
- src/phases.ts
- src/test/items/exp_booster.test.ts
EXP boosting items are changed to stack additively instead of multiplicatively.
#2040
The modifier increments a `modifierBonusExp` variable instead of acting on the gained EXP variable directly, and then after all the bonus modifiers are added to the bonus multiplier variable it's applied to the gained EXP.
`npm run test exp_booster`
Alternatively, defeat a lv5 Gyarados with a lv5 Mewtwo that's holding 1 Lucky Egg and 1 Golden Egg and observe the gained EXP being 456 (2.4x) and not 532 (2.8x) as it is now on main.
> [Bug] Make EXP boosting items stack additively and not multiplicatively

- src/data/move.ts
- src/field/pokemon.ts
- src/phases.ts
- src/test/abilities/wonder_skin.test.ts
- src/test/arena/arena_gravity.test.ts
- src/test/arena/weather_fog.test.ts
- src/test/moves/double_team.test.ts
- see title
- updated Wonder Skin unit tests to use the new method `calculateBattleAccuracy()`
- added unit tests involving the use of `calculateBattleAccuracy()` and `getAccuracyMultiplier()`
- cleaner phases file
- easier unit tests on move accuracy / accuracy multiplier
- more maintainable
- see title
n/a
play the game/run unit tests
> [Enhancement] Decouple move accuracy and accuracy multiplier calculation from phases.ts

- src/ui/starter-select-ui-handler.ts
Fix the bug not changing movesets after adding the pokemon to starter as refered in #1932 
I thought it's pretty simple to resolve but annoying bug.
As mentioned above, it fixes the issue #1932.
Users usually think all the pokemon has same instance, and this bug was being produced because the real code is not.
So this PR changes behavior as predicted.
when chaning the moveset, 
check if there's a moveset in starter entry.
if so, find the latest pokemon seleted and change its movesets to current moveset which is swapped.
I referenced the logic from [this](https://github.com/pagefaultgames/pokerogue/blob/be208d48b64885e8eb04f297900a2c344df1fad1/src/ui/starter-select-ui-handler.ts#L2487)
[스크린캐스트 2024-06-19 15-04-41.webm](https://github.com/pagefaultgames/pokerogue/assets/61226524/c3476117-7f7 …
> [Bug] fix not changing moveset after add to starter

- src/battle.ts
Necrozma's unique battle music can now play for the Dusk Mane, Dawn Wings, and Ultra forms (These forms still cannot be found in the wild normally, but these will play if forced into an encounter).
I previously added their music for some future use, such as if someone wanted to use them as unique boss fights. Since they now play their unique battle themes naturally with this change, it makes the music "used" now.
Necrozma no longer just plays the Solgaleo & Lunala battle theme no matter what. It plays that theme in its base form, plays the Dusk Mane & Dawn Wings theme in those respective forms, and plays the Ultra Necrozma theme in that form.
https://github.com/user-attachments/assets/85cfbb9b-b6b4-4f35-9249-8633a740e537
There isn't a way to force the form index of an opponent at present, …
> [Misc] Allow Necrozma forms to play their special music

- src/field/pokemon.ts
If a Pokémon with their second ability evolves, it will swap to its first ability if the evolution has no second ability, instead of improperly "upgrading" to its hidden ability.
I noticed a bug report about the issue
https://discord.com/channels/1125469663833370665/1254274565627187211
cf [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Ability#Mechanics)
> In technical terms, a species' Abilities may be thought of as having separate slots, with an individual Pokémon's non-Hidden slot determined by its [personality value](https://bulbapedia.bulbagarden.net/wiki/Personality_value). For example, an [Eevee](https://bulbapedia.bulbagarden.net/wiki/Eevee_(Pok%C3%A9mon)) — with two non-Hidden Abilities — has [Run Away](https://bulbapedia.bulbagarden.net/wiki/Run_Away_(Ability)) for its …
> [Bug] Evolution ability fix

- .github/ISSUE_TEMPLATE/bug_report.yml
It's not setting the label properly. 
Cause of the wrong capitalization.
> [Bug] fix label for bug report form

- src/data/ability.ts
- src/test/abilities/hustle.test.ts
- removed unnecessary condition from Hustle
- added Hustle integration tests
- fixes hustle's ATK boost not applying - the `BattleStatMultiplierAbAttr` is not being applied anywhere in `Pokemon.apply()`, thus the condition will always fail because `move` is undefined
- fixes [failing tests on Magnet Rise](https://github.com/pagefaultgames/pokerogue/actions/runs/10047514331/job/27769428030) when opponent gets Hustle as ability
- see above
n/a
`$ npm run test hustle`
or
override ability with Hustle and get physical moves like Tackle, compare `sourceAtk` value in `Pokemon.apply()` with the same mon w/o Hustle
> [Ability] Fix Hustle not applying Attack boost

- src/data/pokemon-species.ts
- src/field/pokemon.ts
- src/test/internals.test.ts
Some non-functional changes are made to improve the readability of the code in `src/field/pokemon.ts` (this code provided by DerTapp on Discord) and `src/data/pokemon-species.ts` (by me).
A convoluted nested ternary was noticed while looking through the code.
Nested ternary replaced with commented if/else blocks in `src/field/pokemon.ts`.
Nested ternaries in `PokemonSpeciesForm.getAbilityCount()` and `PokemonSpeciesForm.getAbility()` changed to if/then blocks in `src/data/pokemon-species.ts`. These weren't that bad, but I'm not a fan of nested ternaries
Uh... play the game? All of the tests still pass and this should theoretically be entirely non-functional changes.
> [Refactor] Code readability update

- src/field/pokemon.ts
Reverts the ability swap portion of #2995
A different bug was introduced causing Pokémon with only Ability1 and a Hidden Ability to lose their HA when evolving.
The code that swaps `abilityIndex` from 1 to 0 for Pokémon that don't have a second normal ability is removed.
Evolve any starter trio Pokémon with its Hidden Ability and observe it doesn't lose its ability upon evolution.
https://github.com/user-attachments/assets/36fc8011-dba3-409b-a35a-65311437df35
> [Bug] Revert evolution ability swap fix

- src/phases.ts
Fixes moves (such as Perish Song) improperly persisting when switching Pokémon after a loading a save game.
Fixes #2982
`resetBattleData()` and `resetSummonData()` are called in `SwitchSummonPhase` to clear any residual data that is improperly persisted.
No switch = Perish Song activates as expected
https://github.com/user-attachments/assets/d5c6c0d4-8021-4e57-8145-1b4bed295046
Current behavior (bugged): Perish Song still activates after switch
https://github.com/user-attachments/assets/f8ea079f-749e-4263-9861-3a52eb8e207c
Behavior after fix: Perish Song no longer activates after switch
https://github.com/user-attachments/assets/340d379c-8177-42f9-b401-29bb1f174dcd
There is unfortunately a bit of RNG involved unless you also modify the encounter logic so that double battles only occur on …
> [Bug] Fix tags not resetting on switch

- src/battle-scene.ts
- src/test/abilities/ability_timing.test.ts
Change on-summon abilities to trigger after the switch check occurs at the start of a battle when playing in "Switch" mode rather than "Set" mode.
The timing was incorrect, letting you nullify an opposing Pokémon's intimidate/etc by switching for free at the start of a battle (as long as you don't reload the game).
The timing of conditional phases was changed from `unshiftPhase()` to `pushPhase()`. Currently the only time conditional phases are used is [exactly once](https://github.com/user-attachments/assets/790b825e-dcde-4d78-829a-0339bfe79a2c), for on-summon abilities at the start of a battle.
Incorrect behavior (on current beta):
https://github.com/user-attachments/assets/f85a6446-24c0-4f95-8958-ec45c8886d39
Correct behavior (after fix): …
> [Bug] Make on-summon abilities trigger after the switch check

- src/data/ability.ts
- src/data/move.ts
- src/field/pokemon.ts
- src/modifier/modifier-type.ts
- src/modifier/modifier.ts
- src/phases.ts
- src/test/abilities/ice_face.test.ts
- src/test/abilities/libero.test.ts
- src/test/abilities/protean.test.ts
- src/test/abilities/sand_veil.test.ts
- src/test/abilities/sturdy.test.ts
- src/test/abilities/wind_rider.test.ts
- src/test/items/leftovers.test.ts
- src/test/moves/gastro_acid.test.ts
- src/test/moves/purify.test.ts
Created a `isFullHp` method to use instead of `pokemon.getHpRatio() === 1`
The code was inconsistent in many places and caused issues such as with leftovers
Fixes #1875 and fixes #1626 and fixes #2234 
```ts
export const STARTING_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [{ name: "LEFTOVERS", count: 1 }];
```
> Sort of? It might conflict with #1877
> [QoL] Create leftovers test and isFullHp method for Pokemon class

- src/system/game-stats.ts
- src/test/items/leftovers.test.ts
This PR addresses the bug reported here: https://github.com/pagefaultgames/pokerogue/issues/3076 
Added a || 0 to the sub-legendary values stored in system/game-stats.ts
I purposely edited game-stats-ui-handler to show all stat names for easier error checking. 
This bug only appears on a completely new user file. 
The tester should immediately go to the 'Game Stats' page in the menu after gender selection.
> [Bug] Game Stats Sub-Legendary NaN bug for new game files

- src/data/pokemon-forms.ts
- src/modifier/modifier-type.ts
- Changes the Dark Stone, Light Stone, N-Solarizer, N-Lunarizer, and the Reins of Unity- all fusion items
- Previously these would show up like any other form change item by simply having Kyurem, Necrozma or Calyrex in your party
- Instead, you will now need to have the appropriate mon (Zekrom, Reshiram etc) registered in the Dex for this item to show up
- It was unbalanced and unthematic that these forms could be accessed without even having encountered the second half
- Frankly it makes no sense for the player to be able to materialize the horses out of thin air
- Adds an extra element of progression in the game by making filling the dex more important
- New function to make a form change condition based on whether a specific species is registered as caught by the player's dex data
- …
> [Balance] Fix N-Solarizer etc appearing without secondary mon registered in dex

- src/phases.ts
In PR #2921 setPokemonCaught(pokemon) was applied before Pokemon Info Container was generated, which meant that the save data would be updated with the new pokemon and so, the game was unable to compare and contrast the newly caught Pokemon to the player's save data correctly. This moves setPokemonCaught to its original location. 
It was my mess. I moved setPokemonCaught upwards for reasons that no longer apply to this PR.
https://github.com/user-attachments/assets/39ccd60e-535d-4396-a978-60286085fe42
Catch Pokemon with a full party / Catch a new Pokemon
> [BUG] Not being able to see new details of caught Pokemon

- src/ui/dropdown.ts
- src/ui/starter-select-ui-handler.ts
This PR fixes the bug between the starter select UI with filter #2916 merged in beta and @Opaque02 's Starter UI selection update #1983 .
Most of the bugs were identified with the help of the previous PR contributor, @Opaque02
[bug discussion thread in discord](https://discord.com/channels/1125469663833370665/1265591426851409973)
The bugs in question range from mildly annoying ones to very dangerous issues, such as being able to select Pokémon that are not unlocked.
The bugs are as follows:
plan to add videos and images
1. When re-selecting the chosen Pokémon, the remove Pokémon menu does not appear.
- before ( bug )
`remove from party` menu doesn't show.
https://github.com/user-attachments/assets/c435d5af-4f4b-459d-9b5f-7e45cf0ab539
- after ( fixed )
`remove from party` menu show and …
> [Bug] Hotfix for Starter select UI with Filter

- src/ui/starter-select-ui-handler.ts
This is a PR that resolves the issue where the shiny dropdown and passive dropdown operate with an "or" condition in the existing unlocks filter.
[related discord thread](https://discord.com/channels/1125469663833370665/1265872164364615680)
The existing method, as shown in the attached photo, operates in a much less intuitive manner.
I modified the conditions that were checked with 'or' in the unlocks filter to be separated into shiny and passive, and processed the two conditions with 'and'.
- before
Both normal Pokémon and passive unlocked Pokémon are searched using an "or" condition. This is non-intuitive.
- after
1.  Only Pokémon that satisfy both normal Pokémon and passive unlocked Pokémon conditions through an "and" condition are searched.
2. works on other cases
> [Bug] fix and condition of unlocks filter in starter select UI

- src/ui/starter-select-ui-handler.ts
When #3030 went into beta, it changed how the form text shows up on the starter select screen. This PR should fix it
With PR 3030, when trying to display the form key on the starter select, it splits the form key (if available) as per [this code](https://github.com/Kiriox94/pokerogue/blob/da262d2eb70adfe45944a4544d3d6a7eb9a27a7f/src/ui/starter-select-ui-handler.ts#L2399). However, "_" should be used to split the pokemon name (for example on line 2401), but the form keys that have a space are actually have a delimiter of "-". This meant when it tried to split by "_" to get the i18 value, it didn't exist, causing issues.
I changed a single instance for a text split to use a delimiter of "_" to use a delimiter of "-".
This is the current behaviour on live (beta) with various pokemon: …
> [Bug] Fixed form names that have a space not showing up correctly in starter select

- src/data/pokemon-species.ts
- src/evolution-phase.ts
- src/field/pokemon.ts
- src/test/evolution.test.ts
- src/ui/starter-select-ui-handler.ts
If a Pokémon with their second ability evolves, it will swap to its first ability if the evolution has no second ability, instead of improperly "upgrading" to its hidden ability.
I noticed a bug report about the issue
https://discord.com/channels/1125469663833370665/1254274565627187211
cf [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Ability#Mechanics)
> In technical terms, a species' Abilities may be thought of as having separate slots, with an individual Pokémon's non-Hidden slot determined by its [personality value](https://bulbapedia.bulbagarden.net/wiki/Personality_value). For example, an [Eevee](https://bulbapedia.bulbagarden.net/wiki/Eevee_(Pok%C3%A9mon)) — with two non-Hidden Abilities — has [Run Away](https://bulbapedia.bulbagarden.net/wiki/Run_Away_(Ability)) for its …
> [Bug] Prevent evolution causing a swap from the second ability to the HA

- src/phases.ts
- src/ui/summary-ui-handler.ts
Modifiers were not displaying on the caught pokemon's summary because of how the game stores and determines possession of modifiers. summary-ui-handler.ts now uses the pokemon's ownership boolean (pokemon.battleInfo.player) to determine where to look for modifiers. 
As a player, I would like to see the modifiers of my caught pokemon + my PR, my responsibility 
- Temporary Pokemon object has tempPokemon.battleInfo.player set to false in phases.ts
- summary-ui-handler.ts uses pokemon.battleInfo.player as an argument in findModifiers()
https://github.com/user-attachments/assets/e12af32d-a687-4d91-954b-2f7bdc1f642f
Catch a wild Pokemon with modifiers with a full party and press the Summary Option
> [Bug] Caught Pokemon Summary-Modifier Display Fix

- src/ui/abstact-option-select-ui-handler.ts
- src/ui/menu-ui-handler.ts
**A** mistake was made
**B** 4 I go on, I want to say sorry if this is needed
**Right**, so there's a small chance the unlock all code made it to live
**Left** to chance, users in live may find the new feature?
**Right** this wrong and merge this PR if need be
**Left** out is the code that unlocks it all
**Down** with bugs!
**Down** the road, if needed, another PR will open to try and fix the unlock all functionality
**Up** until now, we're pretty sure this PR won't be needed, but it's good to have it just in case
**Up** above the world so high
This PR reverses #2967 as even though we tested as much as we could, the unlock all option made its way into live. This is here as an emergency PR in case it's needed.
Even though we tested 2967 as much as we did, we didn't test the unlock all …
> [HOTFIX] Lock unlock all all at once

- src/system/game-data.ts
Pokémon that had their Hidden Ability swapped to their normal ability when loading a save will now have their ability swapped back to their Hidden Ability again after loading the save.
Pokémon were improperly swapping abilities upon loading a save from before the patch.
When loading a session save, check each Pokémon in the party to see if it used to have its Hidden Ability (`abilityIndex === 1`) and swap back to it in the new scheme (`abilityIndex = 2`).
Modify Bulbasaur's second ability to be Ball Fetch (or anything else that's different from its already existing abilities) in `src/data/pokemon-species.ts` and create a new run with a Bulbasaur using that fake ability. Then after exiting to the menu, change Bulbasaur's second ability back to `NONE` and reload the game. Load the save and …
> [Hotfix] Fix Pokemon in pre-patch saves swapping abilities

- src/data/challenge.ts
Make all fresh start starters have 10 IVs in all stats
IVs weren't being reset
Added `    pokemon.ivs = [10, 10, 10, 10, 10, 10]; // Default IVs of 10 for all stats` to `applyStarterModify`
n/a
Pull and test
> [Hotfix] Fix IVs not being all 10 for fresh start challenge

- src/system/game-data.ts
Saves should work again.
There was an off-by-one error. Now there won't be.
Fixed an off-by-one error, saves should load properly now.
Load a saved game.
> [Hotfix] Fix off-by-one error

- src/field/pokemon.ts
- src/ui/battle-info.ts
Fix bug where players would get a tinted Pokeball despite owning the ability, bug introduced in https://github.com/pagefaultgames/pokerogue/pull/3138
Tinted pokeball check was incorrect
Add hasSameAbilityInRootForm function to Pokemon class
Check for if the player owns that ability on the root form for the tinted pokeball check
n/a
Test and pull
> [Bug] Tinted Pokeball for Pokemon with only 1 ability

- src/data/move.ts
- src/field/pokemon.ts
- fixes power and interaction of moves that change type
[this recent change](https://github.com/pagefaultgames/pokerogue/pull/2984/files#diff-1867e67cee517f3348c17ed44e0f02a45a23e59575f38b6e15aacf194768d6dbL1752) caused the relevant moves to only change type [after the typeMultiplier is defined](https://github.com/pagefaultgames/pokerogue/pull/2984/files#diff-1867e67cee517f3348c17ed44e0f02a45a23e59575f38b6e15aacf194768d6dbR1755-R1757) thus not applying the correct type
reference: [discord bug report](https://discord.com/channels/1125469663833370665/1266922986410082344)
- moved the `calculateBattlePower` higher in the code
- updated `calculateBattlePower` to return early with `-1` if move category is of Status
- Normalize now properly works …
> [Hotfix] Fix interactions of moves that change type 

- src/field/pokemon.ts
Wild Pokémon couldn't spawn with their Hidden Ability, now they can.
> [Hotfix] Fix wild spawns not having their HA

- src/data/biomes.ts
`Biome.ABYSS` has the same (English) name as its enum, so it doesn't need a special case for it.
Remove switch case matching `Biome.ABYSS` in `src/data/biomes.ts`.
Language: English
Language: Spanish
`STARTING_BIOME_OVERRIDE: Biome.ABYSS`
Load the game in multiple languages.
> [Misc] Remove unnecessary switch case

- src/test/abilities/intimidate.test.ts
- src/test/utils/gameManagerUtils.ts
- src/test/utils/testUtils.ts
The test randomly fails.
Add a helper function to `testUtils.ts` and use it in the intimidate tests to remove held items from opponent Pokémon.
`npm run test intimidate`
> [Test] Remove held item RNG (white herb) from intimidate tests

- src/test/moves/multi_target.test.ts
There are no user facing tests.
The test randomly fails.
Player Pokémon have the Unnerve passive now.
`npm run test multi_target`
> [Test] Prevent berries from interfering in "multi target" tests

- src/battle-scene.ts
- src/battle.ts
- src/data/ability.ts
- src/data/battle-stat.ts
- src/data/battler-tags.ts
- src/data/challenge.ts
- src/data/move.ts
- src/data/pokemon-forms.ts
- src/data/terrain.ts
- src/data/type.ts
- src/field/arena.ts
- src/field/pokemon.ts
- src/modifier/modifier-type.ts
- src/phases.ts
Gathers most mentioned NITs from #3141 into one PR.
Have all code suggestions under one commit rather than accepting every suggestion one by one; this also has the benefit of verifying suggestions in case of errors as a result of one or more changes.
N/A
N/A
> [Refactor/Documentation] Beta Merge 27/07 Cleanup

- src/locales/ko/achv.ts
- src/locales/ko/battle-info.ts
- src/locales/ko/challenges.ts
- src/locales/ko/modifier-type.ts
I mistakenly closed the existing PR
Translations for achv.ts, challenge.ts, modifier-type.ts and battle-info.ts
Some scripts not translated yet
Simple translations for achv.ts, challenge.ts, modifier-type.ts
I deleted the word "세대" in battle-info.ts because there's already the word "세대" in the {{generation}}
Rare/Rarer Candy script modified
It had been "5세대세대", but now fixed
> [Localization] New Korean translations

- src/data/egg.ts
(I could have sworn I already made a PR for this...)
Users are able to hatch Pokémon with hidden abilities again.
It's not possible to hatch some Pokémon with hidden abilities right now.
Pokemon that should hatch with hidden abilities are properly set to `abilityIndex = 2`.
Enable the egg override(s) and hatch lots of eggs.
> [Hotfix] Allow to hatch pokemon with Hidden Ability again

- src/data/move.ts
Moves like Meteor Mash had their self effects disabled by Shield Dust.
Added a condition to the application of IgnoreMoveEffectsAbAttr.
[Bug report at Discord](https://discord.com/channels/1125469663833370665/1265299187378028586)
Moves with self effects no longer affected by Shield Dust.
> [Bug] Self effect moves fix for Shield Dust

- src/data/battler-tags.ts
Found another redundant `BattlerTag` class that only called its super-class's constructor.
The `ChargingTag` class was removed and its use replaced with use of its super-class instead.
Use Dig or some other move that uses `ChargeAttr`.
> [Misc] Remove redundant `ChargingTag`

- src/data/move.ts
- src/field/pokemon.ts
- src/phases.ts
- src/test/moves/fusion_bolt.test.ts
- src/test/moves/fusion_flare.test.ts
- src/test/moves/fusion_flare_bolt.test.ts
Implemented the power boosting effects to the following moves: [``Fusion Flare``](https://bulbapedia.bulbagarden.net/wiki/Fusion_Flare_(move)) and [``Fusion Bolt``](https://bulbapedia.bulbagarden.net/wiki/Fusion_Bolt_(move)).
The two moves, prior to this PR, were left partially implemented and did not include their secondary effect, doubling their base power if the opposite move was used immediately before the other without any other moves in between. This PR aims to achieve this effect. Note that, on the moves' Bulbapedia pages, the phrase "except perhaps for failed moves" is taken to mean that all failed moves, if any have occurred that turn, are ignored when checking if the opposing move has happened "immediately" before.
For some preliminary context, move order within a turn is …
> [Move] Implement Fusion Flare and Fusion Bolt

- src/ui/confirm-ui-handler.ts
When choosing the Summary option (after catching a Pokemon with a full party), the error sound plays. This does not affect functionality and only impacts player experience. 
It is my PR so I should be responsible for it. I don't play with sound so this was an oversight on my part. 
- ui/confirm-ui-handler.ts : This changes the validity of choosing the summary option so that the sound effect of ui.playSelect() plays, not the one of ui.playError()
https://github.com/user-attachments/assets/e2809dd9-0941-4a4f-9728-6a6641c3e663
Catch a Pokemon with a full party and listen for the correct sound when choosing Summary.
> [Bug] Caught Pokemon-Summary Option Error Sound

- src/data/ability.ts
- src/data/move.ts
Magic Guard now prevents damage from Bad Dreams, Solar Power, Dry Skin, Liquid Ooze, Aftermath, and Innards Out. It should also prevent damage from Gulp Missile but that ability has not been implemented yet.
Recreated from [PR 3029](https://github.com/pagefaultgames/pokerogue/pull/3029)
While working on the Magic Guard test, I noticed these inaccuracies and wanted to update the repo so my test would work according to expectations.
data/ability.ts
PostFaintContactDamageAbAttr
PostTurnHurtIfSleepingAbAttr
PostWeatherLapseDamageAbAttr
data/moves.ts
HitHealAttr
Versus Pokemon with Liquid Ooze/ReverseDrainAbAttr --> HitHealAttr Moves
https://github.com/user-attachments/assets/3f28b96e-0b58-4d1b-abc3-637197df5774
Versus Pokemon with Aftermath/Innards Out (PostFaintContactDamageAbAttr) …
> [Bug] Magic Guard-Ability Interactions

- src/field/pokemon.ts
Crafty Shield should block the effect of Curse performed by a Ghost-type Pokemon.
Referring to https://bulbapedia.bulbagarden.net/wiki/Curse_(move)
> This move is not blocked by [Protect](https://bulbapedia.bulbagarden.net/wiki/Protect_(move)), [Detect](https://bulbapedia.bulbagarden.net/wiki/Detect_(move)), or [Spiky Shield](https://bulbapedia.bulbagarden.net/wiki/Spiky_Shield_(move)), but is blocked by [Crafty Shield](https://bulbapedia.bulbagarden.net/wiki/Crafty_Shield_(move)).
Closes #3161 
Do an extra conditional check that checks if Curse is used after the general conditional protection's (Quick Guard, Wide Guard, etc.) are checked if protection-bypass moves are not used
These changes do not interfere with the Protean/Curse self-inflict …
> [Bug] disallow ghost-type curse to bypass crafty shield

- package-lock.json
- package.json
- src/plugins/vite/vite-minify-json-plugin.ts
- vite.config.ts
> Also updated by #3213 but much cleaner
I had to bump vite up to v5 due to this issue
https://github.com/vitejs/vite/issues/15714
Otherwise `typedoc` would have failed constantly.
Why does `typedoc` suddenly fail?
Because I'm using node types inside my self-written json-minify plugin. To be exact the filesystem `fs` type. vite is "copying" those types but since node v18++ those copied type are out of date. The vite team hasn't migrated that fix into v4 yet and there is no indicator to do that yet.
Duplicate of #3073 
--------------
it minifies all the json files in the given directorties (currently `/dist/images` and `/dist/battle-anim`). That way we can work with the beautified jsons but the users retrieve the minified ones.
Reduce file-size load
Added the `minifyJson` plugin to the …
> [Optimization] Minify json files in build directory (after beta rebase)

- src/data/move.ts
Shield Dust now prevents its user's burn being cured by Sparkling Aria if it is the only target of the attack.
It's one of Shield Dust edge case interactions. With this the ability should be complete, with the exception of Secret Power secondary effect nullification, since Secret Power has not been fully implemented yet.
Added a condition to the class HealStatusEffectAttr, to make it false if all conditions are met: 
Shield Dust user is targeted by Sparkling Aria and it's the only target.
https://github.com/user-attachments/assets/2e7fb004-22ce-49e3-9654-c8131dd80283
https://github.com/user-attachments/assets/aaa3beb5-c7b0-4da8-8f1c-09f9b1923466
https://github.com/user-attachments/assets/dbf7ef66-6d9f-4341-841a-9dddb900198f
With a single target, burn a Shield Dust user, then use Sparkling …
> [Feature] [Ability] Shield Dust and Sparkling Aria interaction

- src/field/pokemon.ts
- src/phases.ts
Changed the condition of Metal Burst redirection when the target faints before the move can hit during a double battle.
Bug report.
Fixed Metal Burst always hitting left target, and the related freeze/crash.
During a double battle make the last opponent to hit the Metal Burst user faint before it, move should redirect to the other non fainted enemy.
> [Bug] [Fix] Metal Burst always hitting left target.

- src/data/ability.ts
- src/field/pokemon.ts
- src/test/abilities/pastel_veil.test.ts
- src/test/abilities/sweet_veil.test.ts
duplicate of https://github.com/pagefaultgames/pokerogue/pull/2626 since beta is broken
- fully implement Pastel Veil
- update Sweet Veil to apply to ally (still partial because the ally should ignore it if it has abilities like mold breaker)
- fixes error from triggering battler tag immunity 
- not fully implemented ability (pastel veil)
- missing immunity to ally (sweet veil)
- error occurs when battler tag immunity is triggered
- changed the existing `StatusEffectImmunityAbAttr` and `BattlerTagImmunityAbAttr` to be base classes for both single/field AbAttrs
[Pastel Veil](https://bulbapedia.bulbagarden.net/wiki/Pastel_Veil_(Ability))
- Overriding ability won't work here since the override will apply to both pokemon on double battle. Instead, you can move Galar Ponyta's second ability …
> [Ability] Fully implement Pastel Veil, update Sweet Veil (after beta fix)

- src/battle-scene.ts
(I'm quite new to contribution so feel free to leave some guidance to me! )
well two lines of code, changing the order of Return & Trainer showing Phase versus Switch Phase. 
[the classic old issue](https://github.com/pagefaultgames/pokerogue/issues/64)
it happens due to having enemy faint faster than player, that then we are triggering ReturnPhase, which is like to trainer battle or to new biome, that phases were: 
Phase: (after both fainting) -> NewBattle -> (Return and trainer show phase) -> Switch
that not just causing display issue but also shows return message of fainted pokemon. 
and pushPhase made it become: 
Phase: (after both fainting) -> NewBattle -> Switch-> Return and trainer show phase
Fix: 
https://github.com/user-attachments/assets/86726e72-e621-4997-96ec-5d7ccf13962c …
> [Bug] fix "Pokemon sprites failing to load after fainting in Gym Leader battle" and related issues

- src/test/abilities/magic_guard.test.ts
This tests if Magic Guard functionality is working as intended. Tests are based on this Bulbapedia article here: https://bulbapedia.bulbagarden.net/wiki/Magic_Guard_(Ability)
Please let me know if there are other cases that should be added to this test while I finish this up. 
Old PR: https://github.com/pagefaultgames/pokerogue/pull/2799
I was working on a bug involving Magic Guard and saw that there wasn't a test for it. Since Magic Guard is an ability with different interactions I thought it would be nice to develop a test to make sure it is working according to expectations.
New File: src/test/abilities/magic_guard.test.ts
npm run test magic_guard
> [Tests] Test for Ability Magic Guard

- src/battle-scene.ts
Fix blinds animation on 2nd++ run. Was broken by #3215.
Closes #3237
Cause I screwed it up in the first place
<details>
<summary>Broken (current) | click to view video</summary>
https://github.com/user-attachments/assets/ffdf8f42-9135-4aee-904f-eee4050b6e19
</details>
https://github.com/user-attachments/assets/12853def-2e20-4402-802b-0e46a7e656fa
1. Start or Continue a run on `beta` branch
2. use `Save & Quit`
- See the odd green thing at the top left
3. Start or Continue a run on this branch
4. Use `Save & Quit`
- blinds animation should work as expected
> [Bug] fix blinds animation (broken after loading-scene delete PR)

- src/ui/starter-select-ui-handler.ts
This uses the existing blockInput flag to prevent inputs from changing the starter when opening the manage moves menu.
addresses these copies of the same bug
https://github.com/pagefaultgames/pokerogue/issues/1879
https://github.com/pagefaultgames/pokerogue/issues/2283
Previously inputs that happened in between the triggering of swap to options mode and before it completed would be handled by the starter select, changing the starter selection. 
a video wouldn't really prove that i'm hitting the buttons as described in the bug ;/
Pull this down, open starter select, pick bulbasaur and very quickly input a right movement action.
Previously bulbasaur's moveset would open with charmander selected
With this branch bulbasaur's moves are shown and bulbasaur remains the selection
> [Bug] block input while waiting for transition to prevent changing starter during move select

- src/overrides.ts
- src/phases.ts
- src/ui/modifier-select-ui-handler.ts
Adds two new boolean overrides: `WAIVE_SHOP_FEES_OVERRIDE` and `WAIVE_REROLL_FEE_OVERRIDE`.
Whenever I'm testing item weights for really rare items and making sure that they actually appear in a "normal" reward fetching context outside of `STARTING_HELD_ITEMS_OVERRIDE` and `ITEM_REWARD_OVERRIDE`, I end up having to either use an all shiny team to bolster luck or set `STARTING_MONEY_OVERRIDE` to a really large number. This usually works if luck comes through, but because reroll prices exponentially grow, you end up running out of money pretty fast and then having to restart to get the `STARTING_MONEY_OVERRIDE` to kick in again. The reroll override directly addresses this by keeping the reroll price at 0 forever, which was the primary motivation.
Alongside the reroll override, I figured I …
> [Enhancement] Add Fee Waiving Overrides

- src/data/move.ts
`EndureAttr` was a single-use move attr that only called its super-class constructor.
`EndureAttr` was removed and its one invocation replaced with the use of its super-class `ProtectAttr`.
Use Endure in a battle.
> [Misc] Remove single-use `EndureAttr`

- src/data/move.ts
General code clean-up.
A switch statement was condensed in `IvyCudgelTypeAttr`.
Ivy Cudgel is currently broken in beta but were it not broken this change shouldn't cause problems regardless.
> [Misc] Consolidate the switch cases in `IvyCudgelTypeAttr`

- src/data/ability.ts
Changes from https://github.com/pagefaultgames/pokerogue/pull/2626/ that were mistakenly excluded in https://github.com/pagefaultgames/pokerogue/pull/3208
- fixes `getDescriptor()` and field application of sweet veil
> [Bug] Add missing changes from sweet veil PR

- src/locales/de/ability-trigger.ts
- src/locales/en/ability-trigger.ts
- src/locales/es/ability-trigger.ts
- src/locales/fr/ability-trigger.ts
- src/locales/it/ability-trigger.ts
- src/locales/ko/ability-trigger.ts
- src/locales/pt_BR/ability-trigger.ts
- src/locales/zh_CN/ability-trigger.ts
- src/locales/zh_TW/ability-trigger.ts
- src/phases.ts
Add the option to localize message text when PreventBerryUseAbAttr(Like Unnerve) prevents use berry.
All text should be localizable.
- Change hard-coded text for localize > phases.ts
- Added localization keys in each language folders. > ability-trigger.ts
- Translated them to Korean.
TBD (After translator's review)
Manually. (Using overrides.ts)
example) preventing 'Sitrus' case
```Typescript
readonly ABILITY_OVERRIDE: Abilities = Abilities.UNNERVE;
readonly MOVESET_OVERRIDE: Array<Moves> = [ Moves.FALSE_SWIPE ]; // Not to make opp pokemon faint.
readonly OPP_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [{name: "BERRY", type: BerryType.SITRUS}];
```
> [Localization] Localize prevent berry ability phase and translate

- src/system/game-data.ts
Removes the ability-swap code from session loading.
It was temporary, also there's a bug anyway.
Check to swap from `abilityIndex` of 1 to 2 is removed from session loading.
Start with a Scatterbug with its second ability, evolve it (and move forward 1 wave to force a save), then reload the session.
> [Misc?] Removes the temporary save-fix code that swaps abilities

- src/phases.ts
I've changed the ordering of adding phase with ToggleDoublePositionPhase, and delete the "|| (this.scene.currentBattle.double && !nonFaintedLegalPartyMembers[0].isActive(true))" that in the end only one summon phase would be pushed if double battle both fainting and only one pokemon in party is alive
some msg in this channel catch my eyes that i guess i am able to reproduce out. 
https://discord.com/channels/1125469663833370665/1263924432813035612/1266796567915008101
here's some video to showcase, some shows sprite and positioning issue, some stucks in pokemon selection menu completely: 
https://github.com/user-attachments/assets/b627fd79-bb9d-402d-87eb-e5ddfcf3297c
https://github.com/user-attachments/assets/a1b1e5d7-fb15-426b-8135-6ef0e2caab30 …
> [Bug] fix double battle edge case stuck/sprite issue when double battle both died and only one bench pokemon not fainted. 

- src/phases.ts
This is simply a mirror of #1333 
We need this fix and the original author isn't responding.
> 
> Here's what changed:
> 
> - I added an extra exception for the switch phase to be skipped if the battle hasn't started yet and you only have 1 Pokemon remaining after a faint in the previous 
> 
> This is what changed from the player's point of view:
> 
> - Player no longer sees the switch menu, meaning they don't know that the next battle is a double battle and they no longer get stuck in an impossible 
> - As a consequence, the player can't pick the final Pokemon in their party before a battle, instead it is sent automatically.
> 
----
⚠️ Make sure to check out #1333 for more details, videos etc.! ⚠️
----
To fix it finally
https://github.com/user-attachments/assets/71287d7d-6e5b-404d-920f-8c …
> [Bug][Mirror] Fixed impossible forced switch

- src/data/pokemon-species.ts
- src/field/pokemon.ts
- src/modifier/modifier.ts
- src/system/game-data.ts
- src/ui/pokemon-info-container.ts
- src/ui/starter-select-ui-handler.ts
- src/utils.ts
May have the effect of improving randomly-generated IV distributions and shiny Pokemon since they were not generated correctly before, but realistically it should have no effect from the user perspective.
A majority of the motivation comes from seeing 2 raised to different powers in order to simulate left bit shifting instead of just using bit shifting directly, adding performance complexity with no benefit. While doing that, more instances were found where bit manipulation would be more performant (see `decToBin` and `binToDec` in `src/utils.ts`), so I aimed to address those as well.
- Refactored `getIvsFromId` such that it uses bit manipulation to extract IVs directly.
- This will be explained a bit more in the Screenshots section.
- Change constants in `trySetShiny` to use bit …
> [Refactor/Bug] Use Bit Shifting & Masking

- src/data/pokemon-forms.ts
- src/data/pokemon-species.ts
- src/locales/de/config.ts
- src/locales/de/pokemon-form.ts
- src/locales/en/config.ts
- src/locales/en/pokemon-form.ts
- src/locales/es/config.ts
- src/locales/es/pokemon-form.ts
- src/locales/fr/config.ts
- src/locales/fr/pokemon-form.ts
- src/locales/it/config.ts
- src/locales/it/pokemon-form.ts
- src/locales/ko/config.ts
- src/locales/ko/pokemon-form.ts
- src/locales/pt_BR/config.ts
- src/locales/pt_BR/pokemon-form.ts
- src/locales/zh_CN/config.ts
- src/locales/zh_CN/pokemon-form.ts
- src/locales/zh_TW/config.ts
- src/locales/zh_TW/pokemon-form.ts
Add the option to localize message text when pokemon battle form is changed.
All text should be localizable.
- Change pokemon-form.ts > getSpeciesFormChangeMessage
- Remove duplicate prefix in form change method (because preName is normally from getPokemonNameWithAffix)
- Change hard-coded key "eternamax" -> SpeciesFormKey.ETERNAMAX
- Change hard-coded message for localize
- Added config, localization keys in each language folders.
- Separated battle form message keys to distinguish between battle form(with item) and pokemon's form.
- Translated them to Korean. (+ each language after review)
<details>
<summary>Click to expand/collapse</summary>
| Case | Result |
| :-----: | :-----: |
| Mega | ![image](https://github.com/user-attachments/assets/520a6a82-80ec-4883-9d1e-ac61a58b479e) |
| …
> [Localization] Localize pokemon form change message and translate

- src/test/moves/octolock.test.ts
Removes enemy held items and abilities from Pokémon.
`npm run test octolock`
> [Test] Remove held items and abilities from octolock test

- src/modifier/modifier-type.ts
- Adjusts the weight of White Herb to not drop as often
- Puts Scope Lens in Trainer item pool in Master tier
- White Herb was perhaps too common in rewards but especially on Trainers and wild mons
- Scope Lens was added but not given to Trainers
- Depends on how many mons in your party have moves or abilities that lower the user's stats
- Previous: 3 if no qualifying mons, 6 if 1 qualifying mon, +1 for each qualifying mon after that
- Changed: 2 if no qualifying mons, 5 if 1 qualifying mon, +1 for each qualifying mon after that
- Drop rate on trainers and wild mons halved
> [Balance] Adjust White Herb weight and add Scope Lens to Trainer item pool

- src/field/arena.ts
Weather will now be reset when arena effects are cleared at the start of trainer battles (unless the weather is from the Biome's permanent weather effect).
Weather should be reset at the start of a new battle, like everything else.
A call to clear the weather is added to `Arena.resetArenaEffects()`.
Permanent biome weather does not get reset:
https://github.com/user-attachments/assets/66aed64e-36de-4db6-88d8-d1cdd1c032cd
Temporary weather gets reset:
https://github.com/user-attachments/assets/d07af01c-08e6-4ad7-8d8d-c6c2b40ecffb
```ts
MOVESET_OVERRIDE: [Moves.RAIN_DANCE, Moves.DRAIN_PUNCH, Moves.THUNDERBOLT, Moves.SUNNY_DAY],
BATTLE_TYPE_OVERRIDE: "single",
STARTING_WAVE_OVERRIDE: 24,
STARTING_LEVEL_OVERRIDE: 100,
STARTING_BIOME_OVERRIDE: Biome.SEA,
```
Start a new run and go to wave 25 …
> [Bug] Weather should be reset upon arena reset

- src/locales/fr/achv.ts
- src/locales/fr/challenges.ts
Added entries related to the Fresh Start challenge that have never been added to French local files
To improve Frenchness
Addition of Fresh Start challenge related entries in French achiv.ts and challenge.ts
> [Beta][Localization] Fresh Start challenge entries added to French locales

- src/data/move.ts
- src/field/pokemon.ts
- src/phases.ts
In a number of places, including `SummonPhase`, `SwitchSummonPhase`, `ForceSwitchOutAttr`, and `TurnInitPhase`, extremely similar logic is performed manually to cause a mon to leave the field. Some of this logic was re-used for player-pokemon switches via `PlayerPokemon#switchOut`, but I refactored the parts relevant to both player and enemy mons into a single function in the base Pokemon class, called `leaveField()`. 
DRY. Also, I think it might partially fix baton pass when used by the AI - notes inline below.
Ideally, very little.
N/A
Run the tests
> Refactor duplicated code into a common Pokemon#leaveField() function

- src/data/egg-moves.ts
- src/data/pokemon-level-moves.ts
Dipplin gets access to Dragon Cheer via Memory Mushroom
Applin's Dragon Cheer Egg Move is changed to Matcha Gotcha
As of right now, players are reliant on the Egg Move to evolve their Applin into the very commitment-heavy Hydrapple (Syrupy Apple is a different rarity from the other Apple items for some strange reason, then to evolve into Hydrapple you would have to luck out and get the TM within the same run which requires you to EVOLVE Applin first since Applin doesn't learn it OR the player must have the Egg Move unlocked. All while Appletun / Flapple can get their evolutions relatively early on and have access to their G-Max Forms.) Stantler currently has Psyshield Bash as a custom level up move when in mainline it is an egg move normally, so initially I would have wanted to make …
> [Balance] [Beta] Give Dipplin Dragon Cheer as a relearn move

- src/data/move.ts
- src/test/moves/belly_drum.test.ts
- src/test/moves/clangorous_soul.test.ts
- src/test/moves/fillet_away.test.ts
Before, Belly Drum was implemented separately from other moves that exchanged HP for stat boosts like Fillet Away and Clangorous Soul. In addition, the implementation of non-Belly Drum moves did not have a fail condition when all affected stats were already maxed out. This merges the two implementations into one and adds a check.
Old PR: https://github.com/pagefaultgames/pokerogue/pull/3039
I thought it would be nice to reduce redundant code + I noticed this while working on some other stuff. 
- Deleted HalfHpStatMaxAttr
- Added to CutHpStatBoostAttr
- Checks for fully-maxed stats
- Additional check for unique single-stat max out message (for Belly Drum specifically)
Stats @ Max Failure Message 1
https://github.com/user-attachments/assets/ecab240c-aa86-40d6-80cb-d2abdc27d2f6
Stats @ Max …
> [Misc] Merged implementation of CutHpStatBoostAttr moves

- src/data/pokemon-species.ts
Correctly locates variant icons when the Pokemon's form has the `FormSpriteKey` alias of `""`.
Reported about [Scatterbug](https://discord.com/channels/1125469663833370665/1238339524778790922/1264464007033651272), [Sinistea](https://discord.com/channels/1125469663833370665/1238339524778790922/1255645697651376159), [Gourgeist](https://discord.com/channels/1125469663833370665/1238339524778790922/1252374971808878812), and [Morpeko](https://discord.com/channels/1125469663833370665/1238339524778790922/1266628290131660870).
These reports all affect a Pokemon with forms, where that form has a `formSpriteKey` of `""`. When an affected Pokemon uses a variant palette, the game displays the Pokemon's common/base shiny icon instead, no matter which tier of shiny it actually should be.
Yes, I added …
> [Sprite] Target FormSpriteKey-labelled sprite assets

- src/ui/starter-select-ui-handler.ts
Fixed an issue where the menu wouldn't open when 6 starter Pokémon were selected.
Previously, this issue prevented the removeFromParty action from being performed through the menu when a 6th Pokémon was added.
Modified the if condition for opening the menu.
before ( can't open menu )
after ( can open menu )
> [Bug] Fix blocking menu when 6 starter selected

- src/data/battler-tags.ts
Stylistic consistency.
Replace `BattlerTagType.BYPASS_SLEEP` with `tagType` on line 1750 of `src/data/battler-tags.ts`.
Use the move Snore while your Pokémon is asleep.
> [Misc] Use `tagType` instead of manually passing `BattlerTagType.BYPASS_SLEEP`

- src/test/abilities/intimidate.test.ts
- src/test/moves/octolock.test.ts
- src/test/utils/gameManager.ts
- src/test/utils/testUtils.ts
Item RNG can sometimes break tests, now this should never happen again.
Held items are removed from enemy Pokémon automatically at the start of every test unless an item override is specified.
`npm run test`
> [Test] Remove held items from all tests when there are no item overrides

- src/test/abilities/power_spot.test.ts
The test can randomly break if Pikachu has a -spd nature and Stonjourner has a +spd nature.
Replaced Pikachu with Regieleki (the Pokémon with the highest base speed stat in the game).
`npm run test power_spot`
> [Test] Fix Power Spot test so Stonjourner always moves second

- src/ui/dropdown.ts
- src/ui/filter-bar.ts
- src/ui/starter-select-ui-handler.ts
This PR enhances the hybrid filters with hovering functionality.
1. The dropdowns of all hybrid filters no longer obscure the Pokémon list.
2. The default setting for hybrid filters is ALL OFF. (In classic mode, the Gen filter defaults to Gen 1 with the cursor hovering over it.)
1. Hybrid filters change the filtered list in real-time with cursor movement, and it is much more useful to not obscure the Pokémon list in hovering mode.
2. The default setting for all hybrid filters should be hovering, as multi-selecting when necessary is the standard usage. Keeping the default settings for type and dex as all selected, as before, is inconvenient since most users will need to clear all selections before using filters effectively.
1. Changed all hybrid windows to appear to the left of the Pokémon …
> [Bug,Enhancement] Fix and improve Starter selector UI

- src/data/ability.ts
- src/test/abilities/sand_spit.test.ts
Sand Spit will only activate when hit with a damaging move.
Fixes #3336
cf https://bulbapedia.bulbagarden.net/wiki/Sand_Spit_(Ability)
An optional condition parameter was added to `PostDefendWeatherChangeAbAttr` which is used by Sand Spit to ignore status moves (though currently Sand Spit is the only ability to use that abattr anyway).
Start a run with Silicobra with Sand Spit, and get hit by various moves.
> [Bug] Sand Spit should only activate when hit with a damaging move

- src/data/pokemon-level-moves.ts
This addresses issue [#2783](https://github.com/pagefaultgames/pokerogue/issues/2783)
This is a mirror of [#2975](https://github.com/pagefaultgames/pokerogue/pull/2975) with merge conflicts fixed. 
The signature moves for the Rotom forms, and the Cosplay Pikachu forms, have been updated to now be selectable as starting moves, rather than having to be relearned using a mushroom. 
These Pokemon should be able to start with their signature moves, as they are supposed to be known by default regardless of level. 
Changed the level of these moves in the pokemon's learn sets from EVOLVE_MOVE (i.e. 0) to 1. Previously these were treated identically, but (apparently) the handling of level 0 vs level 1 moves was changed so that the "starting move" filter misses level 0 moves. 
Previously, electric …
> [Bug] Cosplay Pikachu and Rotom forms not starting with signature moves

- src/modifier/modifier-type.ts
- Look at the rabbits, White Herb...
- The People were not ready
- Offered compassionate care to the White Herb item
> [Balance] "Old Yeller" White Herb

- src/data/move.ts
* Storm moves (Bleakwind, Wildbolt, Sandsear) no longer suffer accuracy drops in sun/sand
* Thunder/Hurricane no longer suffers accuracy drop in sand
Behavior was incorrect
* Created a new `StormAccuracyAttr` used for the storm moves
* Removed the sandstorm check in `ThunderAccuracyAttr`
n/a
Change the weather and use the move
> [Bug] FIx Storm move accuracies in sun

- src/data/egg.ts
- src/ui/starter-select-ui-handler.ts
Allow Phione species-eggs to have a 1/8 chance to hatch Manaphy
Manaphy is obnoxiously hard to obtain right now since it is unaffected by pity.
Added the following in `egg.ts`
```ts
if (this._species === Species.PHIONE) {
pokemonSpecies = getPokemonSpecies(Utils.randSeedInt(MANAPHY_EGG_MANAPHY_RATE) ? Species.PHIONE : Species.MANAPHY);
}
```
Obtained a lot of free 1 wave Phione eggs
Verify Manaphy hatched out
Pull [the commit with the debug features](https://github.com/pagefaultgames/pokerogue/pull/2787/commits/deab6243865fe9eafce58c6226f79762363450a9)
> [Feature] Allow Phione eggs to have a 1/8 chance to hatch Manaphy

- src/data/move.ts
Rebranch of #3013
Prevents Sketch from copying moves that are supposed to be [unsketchable](https://bulbapedia.bulbagarden.net/wiki/Sketch_(move))
To prevent these moves from being sketchable. 
With this change, you can no longer copy the following moves:
- Chatter
- Mirror Move
- Sleep Talk
- Struggle
- Sketch
- Revival Blessing
- Tera Starstorm
- Breakneck Blitz
NOTE: There are other moves that are technically unsketchable. I kept these as sketchable as other pokemon are given some of these moves as egg moves. These include:
- Dark Void 
- Hyperspace Fury 
- Wicked/Blazing/Noxious/Magical/Combat Torque 
Before changes
https://github.com/user-attachments/assets/47d0bfe6-0763-4cfe-8b47-9dc7b51ce56a
After changes
https://github.com/user-attachments/assets/dda8dead-4886-4c9a-880f-6b5b30dea0f …
> [Bug] Fix sketch being able to copy some unsketchable moves

- src/modifier/modifier-type.ts
Marginally better item rolls I guess?
Item reward tier weights were changed (they add up to 1024 now, amazing), and a pointless `Math.min()` statement was removed.
Re-roll item rewards a few million times?
> [Bug] Fix tier weights and remove unnecessary `Math.min()`

- src/data/move.ts
- src/phases.ts
- src/ui/battle-flyout.ts
Rebranch of #3132 
#2347 
Fixes the visual bug with the Moveset Flyout not updating on Spite reductions.
It is a visual bug.
Removed the calculation done within the `BattleFlyout` class. Instead, I send the move's current pp value instead of the pp being used for that turn.
Dispatches a MoveUsedEvent in Spite with the newly reduced pp value. 
Before
https://github.com/user-attachments/assets/405c569f-f0b5-4dea-84fb-00573459bc00
After
https://github.com/user-attachments/assets/37ea19c1-c54f-4b68-8bae-fba6ff106063
Give yourself Spite with src/overrides.ts, test against opponent's moves while checking the battle flyout using V button.
> [Bug] Fixes Moveset Flyout not updating PP from Spite PP reduction

- src/locales/ja/ability.ts
- Changed description of Honey Gather, Ball Fetch and Pickup to properly reflect how they function in PokeRogue.
特性の説明文が正しくポケローグでの効果を示しているように変更しました
> [Ja] [Localization] Update ability.ts 

- src/locales/ja/move.ts
-  Changed some descriptions to correctly describe their function in PokeRogue. 
ポケローグでの特性の効果が正しく説明されているために、いくつかの特性の説明文を変更しました
(Pika Papow can be used by Pichu and Raichu in Pokerogue, so I removed the mention of Pikachu in the description)
ポケローグでは、ライチュウがピカピカサンダーをできるので、説明文からピカチュウの記載を削除しました
- Translated descriptions for the "Torque" moves into Japanese. (Require proof-reading) 
「アクセル」技の説明文を英語版ポケローグから翻訳しました　(構成必要）
See Files changed.
> [JA] Update move.ts [Localization]

- src/data/move.ts
Damaging moves that heal you are fixed.
Damaging moves that heal you were broken.
A variable is changed from `undefined` to `null` to pass a null check properly.
Use an attacking move that heals you based on the damage dealt.
> [Bug] Fix healing modifying the HP stat instead of the Pokemon's HP

- src/ui/abstact-option-select-ui-handler.ts
- src/ui/achvs-ui-handler.ts
- src/ui/awaitable-ui-handler.ts
- src/ui/challenges-select-ui-handler.ts
- src/ui/form-modal-ui-handler.ts
- src/ui/game-stats-ui-handler.ts
- src/ui/loading-modal-ui-handler.ts
- src/ui/login-form-ui-handler.ts
- src/ui/menu-ui-handler.ts
- src/ui/message-ui-handler.ts
- src/ui/modal-ui-handler.ts
- src/ui/outdated-modal-ui-handler.ts
- src/ui/session-reload-modal-ui-handler.ts
- src/ui/settings/abstract-binding-ui-handler.ts
- src/ui/settings/abstract-control-settings-ui-handler.ts
- src/ui/settings/abstract-settings-ui-handler.ts
- src/ui/settings/gamepad-binding-ui-handler.ts
- src/ui/settings/keyboard-binding-ui-handler.ts
- src/ui/settings/settings-audio-ui-handler.ts
- src/ui/settings/settings-display-ui-handler.ts
- src/ui/settings/settings-gamepad-ui-handler.ts
- src/ui/settings/settings-keyboard-ui-handler.ts
- src/ui/settings/settings-ui-handler.ts
- src/ui/ui-handler.ts
- src/ui/unavailable-modal-ui-handler.ts
- src/ui/vouchers-ui-handler.ts
the constructor of ui classes now allows `null` for the mode constructor param.
Extension of #3259 
to get rid of the `mode!`
`mode: Mode` is now => `mode: Mode | null = null`
- tests should still succeed.
- Play the game and nothing should crash
> [Refactor] allow null UI mode (rid of `mode!`)

- src/data/move.ts
Absorb also works again now.
Only some damaging heal moves worked.
Add a missing default value (why did this work before?).
Use Absorb while damaged.
> Fix the other issue with `HitHealAttr`

- src/battle-scene.ts
- src/data/move.ts
- src/field/pokemon.ts
- src/phases.ts
- src/test/moves/dragon_tail.test.ts
Fixed game freezing bug when force-out moves (commonly dragon tail) in doubles and single wild battles.
Bug often report on discord
Previous code was immediately destroying the forced-out pokemon object, causing any further reference to it (eg: showing its ability) to reference undefined and crash the game.
To remedy this I made a few changes:
- delay the destroying of wild pokemon objects until the end of the battle
- added an attribute to track wild pokemon that fled, this is to ensure that (since the fled pokemon's object is still around the `BattleScene` but not marked as `fainted`, it isn't selected by `getEnemyPokemon()` to move animations. Without this the game would sometimes crash, as Phaser would try to animate moves hitting a non-visible pokemon.
- added move auto-redirection …
> [BUG] - dragon tail switchout ability in wild battles proc crashes game

- src/locales/fr/modifier-type.ts
- src/locales/fr/tutorial.ts
French locales missing translations, typos and rephrasing
To have it in French / more clear
Some entries in tutorial and modifier-type French locales
> [Localization] French - Some missing translations, typos and rephrasing.

- src/data/pokemon-evolutions.ts
- src/test/evolution.test.ts
Wild pokemon weren't evolved anymore. 
CAuse they should (if certain criteria is met)
Mostly this inside `SpeciesFormEvolution#constructor`:
```ts
this.wildDelay = wildDelay ?? SpeciesWildEvolutionDelay.NONE;
```
- Download [sessionData_damocleas.txt](https://github.com/user-attachments/files/16537643/sessionData_damocleas.txt) and change the file-extension to `.prsv`.
- import the session data into a slot
- load the session
- play a few waves => all wild pokemon should be evolved properly
> [Bug] no wild evolutions

- src/test/moves/miracle_eye.test.ts
Forgot to mock the turn order when making the test.
The player Pokémon now always moves first in the test.
`npm run test miracle_eye`
> [Test] Mock turn order in Miracle Eye test

- src/field/pokemon.ts
- src/test/final_boss.test.ts
Disables final boss passive in all modes
Before Eternatus (the starter) gets a real passive, disabling passive on the final boss.
Disables final boss passive in all modes
https://github.com/user-attachments/assets/35153f7d-074a-4c8a-a7f3-4a01e67397b9
beta branch, or `npm run dev` locally
> [QoL] Disables final boss passive for starter Eternatus passive changes

- src/data/status-effect.ts
- src/field/pokemon.ts
Fix `getRandomStatus` to check for `null` and `undefined` (not just `undefined`) thus DNA-splicer works again.
`Starkrieg` reported [on discord](https://discord.com/channels/1125469663833370665/1245857678991822879/1271285637278072928) that dna-splicing is broken.
This was caused by the introduction of `strict-null`.
<sub>But this was fixed now</sub>
- Use [sessionData_starkrieg (4).txt](https://github.com/user-attachments/files/16555820/sessionData_starkrieg.4.txt)
session-data (change file-extension to `.prsv`
- Import it into a slot
- Run the game
- try to use DNA-splicer => should work
try the same on `beta` (not PR branch) => console.error
> [Bug] DNA-splicer broken

- src/test/moves/hyper_beam.test.ts
- src/test/moves/purify.test.ts
There is RNG in the tests.
Turn order is mocked in the Purify test, and the enemy is set to level 100 in the Hyper Beam test to prevent it from fainting.
`npm run test hyper_beam`
`npm run test purify`
> [Test] Fix test RNG

- src/data/battle-anims.ts
- src/test/utils/gameWrapper.ts
- src/test/utils/mocks/mockFetch.ts
when loading battle-anim files the content-type of the response is checked too (not just `response.ok`)
Sometimes the local deployment soft-locks the user when trying to load a non existing battle-anim json file. This is annoying.
It now checks the `content-type` of the response. If it doesn't contain `application/json` it's considered FAILED too
idk. Just play and see that it doesn't occur anymore? I'm not sure how to 100% reproduce the issue
> [Bug][Localhost] fix Json parse issue when trying to load battle-anim

- src/data/pokemon-level-moves.ts
Changed all mainline starter's learnset to get access to their respective STAB option at Level 5.
Follow up on my previous PR's that helped other Pokemon's early game learnsets, this aims to allow every starter to get access to their STAB option immediately rather have weird variance between each generation. Makes the game ever so slightly easier for a new player / fresh start player and keeps things equal between the options.
Chikorita/Cyndaquil/Totodile, Turtwig/Chimchar/Piplup, Snivy/Tepig/Oshawott, Grookey/Scorbunny/Sobble all had their learnsets adjusted. Poipole had Dragon Pulse set as a relearn move to not start with Naganadel immediately.
A saddened Cyndaquil that needs to wait until Level 10 for his early game STAB :(
A happy Cyndaquil knowing he is equal to his starter kind :) …
> [Balance] Change Some Mainline Starter's Early Learnset

- src/ui/starter-select-ui-handler.ts
- Now, when a passive ability is unlocked, the passive background is immediately displayed.
- Because I like it. (You do too, right?)
- Upon unlocking a passive ability, `starterPassiveBgs` is now immediately set to visible.
- Previously, this was only updated during a scroll check.
- before ( after unlock passive, update passive background when press up or down key )
https://github.com/user-attachments/assets/a4fc8229-e5d7-40ec-982f-95038e0bf7bb
- after ( update passive background Immediately )
https://github.com/user-attachments/assets/2e0b0d8f-a676-4b13-8f68-1769ffda1692
> [Bug] Immediately update the passive background upon unlocking

- index.css
- index.html
This PR adds the button to open filter in starter select UI on the mobile touchpad
The touchpad layout was also updated in a few other spots
PR #3345 added a shortcut in the starter select UI to open the filters, but the corresponding button was not available in the touchpad layout for that screen.
In some screens like settings and battle some of buttons that did similar things were located in separate containers, making their use less intuitive especially if the button layout is modified thanks to PR #3256  
* Starter Select: Move all 6 "cycle" buttons next to each other and add the Filter shortcut button where the Shiny and Variant cycle buttons were before
* Battle: Move both buttons to show battle info next to each other
* Settings: Move both buttons to navigate the tabs next to each …
> [Enhancement] Add "open filter" button for mobile touch pad

- src/test/moves/parting_shot.test.ts
Adding tests that cover PR #3195 (for parting shot), which originally fix issue #3112: that parting shot still debuffs when the move is supposed to fail
More tests
`npm test src/test/moves/parting_shot.test.ts`
> [TEST] - adding parting shot move test
