pagefaultgames/pokerogue

src/data/challenge.ts, src/game-mode.ts, src/modifier/modifier-type.ts, src/phases.ts
* Starters in fresh start are not hardcoded as 3 cost
* Mini Black Hole disabled in fresh start
* No catching allowed in the last biome in fresh start
Makes fresh start more inline to a true fresh start. Note that there are still some edge cases involving dexAttr which are not easily solved.
* Created 2 new helper functions in game-mode.ts
* Added a fresh start check for mini black hole and eviolite weight
* Added a fresh start check for catching in the last biome
* Change starter costs from 3 and see if it's correctly reflected in fresh start
* Change MBH weight super high and see if it will spawn in fresh start
* Try catching in the last biome in fresh start
=> [Bug] Some fresh start fixes

.github/ISSUE_TEMPLATE/bug_report.yml
Swapped the names of the `Session export file` and `User data export file`
[#3479](https://github.com/pagefaultgames/pokerogue/issues/3497)
Description did not match the name
=> [Bug][3497] bug report fields name swapped

src/test/abilities/flash_fire.test.ts
[Test randomly broke](https://github.com/pagefaultgames/pokerogue/actions/runs/10361460682/job/28681819652?pr=3513).
Enemy ability is now specified/locked in the test.
`npm run test flash_fire`
=> [Test] Fix Flash Fire tests to remove enemy ability RNG

src/data/move.ts
This fixes a bug with No Retreat where the move would fail if the user was already trapped by a move other than No Retreat.
closes https://github.com/pagefaultgames/pokerogue/issues/3459. No Retreat is still supposed to boost the user's stats if the user is already trapped by a move other than No Retreat.
`data/move`: 
- Changed `failOnOverlap` param to `false` for No Retreat's trapping effect
- Added a condition to No Retreat to check specifically for a `TrappedTag` set by No Retreat on the user
No Retreat used before other trapping moves: fails on subsequent uses
https://github.com/user-attachments/assets/75d26569-b515-473f-a5c7-51c3f5e1532b
No Retreat used after other trapping moves: can be used multiple times
https://github.com/user-attachments/assets/de06a4ef-e066-4538-a4e3-aebe1de751 …
=> [Bug] Fix No Retreat failing when trapped by a different move

src/battle-scene.ts, src/modifier/modifier.ts, src/ui/target-select-ui-handler.ts
The held items of the target also flash with the target during the target selection phase. 
It is difficult to tell which Pokemon have which modifiers during double battles especially if they share the same icons. This helps differentiate them, allowing the player to make the same quality of decisions as they do in double battles with different Pokemon. 
- src/modifier/modifiers.ts : Each PokemonHeldItemModifier container (item, Pokemon, stack count) is now named with the pokemon's unique ID. The battle-scene class objects ModifierBar and EnemyModiferBar are made of such containers. This allows for Pokemon-specific interactions with the contents of ModifierBar/EnemyModifierBar without altering the whole container. 
- src/ui/target-select-ui-handler.ts: Functions that incorporate the …
=> [Enhancement] Target Selection also highlights target's held items

src/ui/abstact-option-select-ui-handler.ts
Enable cursor wrap around for some menus that didn't have it
Some menus especially in the starter select UI are starting to have a lot of options and not being able to wrap around quickly to the top or bottom is annoying.
Closes issue #3218 
Update the `AbstractOptionSelectUiHandler` to enable cursor wrap around. All of the following menus that didn't have them now have it (there may be more):
- Opening menu
- Main menu: Manage Data / Import Session / Export Session
- Settings: Language choice / Controller choice
- All Yes/No menus
- Game mode choice
- Starter UI: Pokemon menu
- Starter UI: Manage Nature menu
- Starter UI: Manage Move menus (menu with current moves and menu with moves to pick from)
- Starter UI: Use Candies menu
Note:
Since all menus in the game don't necessarily use that …
=> [QoL][UI] Add cursor wrap around to option select menus

src/data/pokemon-evolutions.ts
- Removes arbitrary delays from evolutions such as Obstagoon, Tyrantrum and Aurorus which are simply regular level evolutions occurring at day or night
- They shouldn't have those delays
- Removed the SpeciesWildEvolutionDelay for those evos
=> [Balance] Remove wild evolution delays from time based level-up evolutions

src/data/pokemon-evolutions.ts, src/data/pokemon-species.ts, src/field/pokemon.ts, src/phases.ts, src/ui/starter-select-ui-handler.ts
It's minor type improvement.
It's better for type safety.
- makes some implicit any to have proper types 
- removes some unnecessary assertions.
=> [Enhancement] improve typing

src/data/pokemon-level-moves.ts, src/field/pokemon.ts
Changed Smeargle to relearn Sketch at levels 11, 21, 31, etc, up to level 91 so that it is in line with its learnset in previous generations, as opposed to the current gen 9 implementation. 
Currently, Smeargle requires a high amount of investment in the form of Memory Mushrooms. This makes Smeargle difficult to use, particularly when obtained early on due to the increased rarity of said Mushrooms at lower levels. This change would make Smeargle more useful early on as a Starter, without impacting its strength or flexibility beyond level 91. 
Smeargle's learn-set has been updated to learn Sketch at levels 11, 21, 31, 41, 51, 61, 71, 81, and 91. 
Pokemon.getLevelMoves() has been updated to narrow the Species level moves by level first, and then filter out any duplicates after, as the other …
=> [Feature] Change Smeargle/Sketch to pre-gen9 implementation

src/modifier/modifier-type.ts
- Adjusts the formula for ether/elixir weights in the item pool to only take a move into account if it has half its PP missing (rounded down). For example, having 4/5 PP on a single move will no longer put Ethers into the reward pool, but 3/5 PP will.
- Currently using a 5 PP move at all will automatically add ethers and elixirs to the reward pool which can take the place of other rewards
- Other healing items are usually to remedy something the player did wrong. Using a move with low PP isn't a bad decision.
- Currently players are discouraged from using low PP moves due to the resulting dilution of the reward pool
- No one is using an Elixir to restore 1 PP on Morning Sun be so fr
- Checks in the weight function for ethers/elixirs if the ppUsed of a move is greater than or equal to the …
=> [QoL] [Balance] Adjust ether weights for lower-PP moves

src/data/ability.ts, src/test/abilities/zero_to_hero.test.ts
Palafin will no longer swap to its Hero form when switching out due to fainting.
The current behavior is incorrect. cf https://bulbapedia.bulbagarden.net/wiki/Zero_to_Hero_(Ability)
The form change checks whether Palafin is fainted or not. Additional tests were also added.
Have Palafin use Memento while in base form (with another Pokémon to switch to in the back) and then check whether Palafin swaps forms after switching to the unfainted Pokémon.
=> [Bug] Palafin should not swap to Hero form when switching due to faint

src/field/pokemon.ts
Added Flamethrower > Dragon Dance on Eternatus Phase 1 Boss.
Meant to change this for a while, no one ever bothered putting a PR up for it.
Dragon Dance on Phase 1 Eternatus -> Flamethrower so both phases have it
Get to the end of a classic run, send out a fairy/steel type, if it uses Flamethrower then it works.
=> [Balance] Added Flamethrower to Phase 1 / Endless Eternatus

src/data/pokemon-forms.ts, src/data/pokemon-species.ts, src/locales/ca_ES/pokemon-form.ts, src/locales/de/pokemon-form.ts, src/locales/en/pokemon-form.ts, src/locales/es/pokemon-form.ts, src/locales/fr/pokemon-form.ts, src/locales/it/pokemon-form.ts, src/locales/ja/pokemon-form.ts, src/locales/ko/pokemon-form.ts, src/locales/pt_BR/pokemon-form.ts, src/locales/zh_CN/pokemon-form.ts, src/locales/zh_TW/pokemon-form.ts, src/test/abilities/flash_fire.test.ts
Allows Meloetta's Pirouette Form to be selectable on the starter select.
Purely QoL change, Meloetta is not able to use Pirouette to its fullest extent due to the nature of how PokeRogue plays so this allows player further options if they would want to use this Pokemon. As well as setting it free from its previous restriction of wasting a moveslot to use the form.
Pirouette as a selectable form
Meloetta no longer changes forms between biome changes or trainer battles.
Pick Meloetta on the starter select
=> [Balance] [QoL] Allow Pirouette Meloetta to be selectable on starter screen

src/ui/menu-ui-handler.ts
Right now, the player cannot close the menu after they export their Game Data. This is because the option lacks a keepOpen: true in its configuration, causing the player to be stuck.
Issue Link: https://github.com/pagefaultgames/pokerogue/issues/3533
It is a straightforward fix that could help with debugging + player experience. 
Export Data's configuration now has keepOpen: true
https://github.com/user-attachments/assets/000c6329-f408-41cd-9fbf-f39fe7ff5de2
Export Data > check for freeze. 
Note: there should be a slight pause as the file is downloaded onto device.
=> [Bug] Export Game Data fix

src/data/pokemon-forms.ts
Makes Gracidea function as any other form change item
While the gimmick is cool in mainline, it makes Shaymin one of the most inconsistent picks of a starter, not worth its starter cost whatsoever (makes balancing the cost even worse) and makes its form not worth the trouble of utilizing with how strict of a restriction it was. This was a popular request from users in the discord who wanted to utilize Shaymin to its full extent just as any other Pokemon as it is the only form change to have such a condition to it. 
Gracidea no longer has a time of day requirement attached to it
Shaymin-Sky active during night time
Use overrides to get Gracidea during night time.
- [] Have I considered writing automated tests for the issue?
=> [Balance] [QoL] Remove Gracidea's Time of Day Restriction

vite.config.ts
Fixing/Updating the existing `vite.config.ts` without changing any of it's behavior
To resolve errors shown in the IDE
Simply adding proper TS types to the objects and fixing the definition object so no more errors are shown in the IDE
1. Open `vite.config.ts`
2. Your IDE shouldn't complain anymore
-----
1. Open `vitest.config.ts`
2. Your IDE shouldn't complain anymore
----
1. open `vitest.workspace.ts`
2. Your IDE shouldn't complain anymore
=> [Bug] fix/update invalid `vite.config.ts`

src/modifier/modifier-type.ts
Reverted changes to map, nothing changes for Classic.
isClassic was removed and allowed it to spawn in Endless.
Reverted line 1574 of src/modifier/modifier-type.ts
Play Beta or slap onto your local.
=> [Bug] Revert Map Item Table

src/phases.ts
This fixes a bug in beta that causes a Pokemon's info flyout to not appear correctly after the Pokemon switches or is returned before a Trainer battle.
closes #3571 
- `phases.ts`: Removed a possible race condition with calls to `Pokemon.hideInfo` in `SwitchSummonPhase` by adding a 50 ms delay
In game:
- Switch Pokemon while quickly mashing inputs
- Enter a Trainer battle (e.g. Wave 5) while quickly mashing inputs
=> [Bug][Beta] Fix Pokemon info flyout disappearing on switch-out

src/modifier/modifier-type.ts, src/phases.ts, src/test/items/lock_capsule.test.ts, src/test/utils/helpers/overridesHelper.ts
Common items now appropriately increase the cost of rerolling if the lock capsule item is being used instead of being free.
It was bugged and making rerolls potentially much cheaper than intended.
A check intended to prevent `null` values is changed to no longer also prevent `0` values.
Base reroll cost:
With fix:
Without fix:
Start a run with the override `STARTING_MODIFIER_OVERRIDE: [{name: "LOCK_CAPSULE"}]` set, then toggle the lock capsule on-off and observe the cost change pre- and post-fix with at least one common tier item in the rewards.
`npm run test lock_capsule`
=> [Bug] Lock Capsule no longer treats common items as free

src/phases.ts
This reverts a change made in PR #3420 to prevent players from catching pokemon in the End Biome in Fresh Start. However, this did the opposite and allowed players to catch Pokemon like Eternatus despite not having a full Pokedex. 
Not intended behavior. 
Try to catch Eternatus/End Biome Pokemon in Fresh Start
=> [Hotfix] Removed isFreshStartChallenge() check

src/field/pokemon.ts, src/phases.ts
This fixes a bug where a Pokemon's info container does not appear correctly after the Pokemon is switched out, then returned to the field.
My last PR on this (#3588) did not fully fix the bug from (#3550) 😔 
- `field/pokemon`: Added a parameter to `Pokemon#leaveField` to make the internal `hideInfo` call optional.
- `phases`: `SwitchSummonPhase` now uses the new `leaveField()` parameter so that `hideInfo` is not invoked twice when returning a Pokemon.
In game (needs testing on different devices, 5x game speed preferred):
- Switch back and forth between Pokemon during a battle.
- Enter a Trainer battle (e.g. Wave 5) while mashing inputs.
- [n/a] Have I considered writing automated tests for the issue?
- [n/a] If I have text, did I add …
=> [Hotfix] Fix Pokemon info not fully appearing after switch-out

src/game-mode.ts, src/phases.ts
Users are unable to catch Pokemon in the End Biome because of a bad conditional + an error in how gameMode.hasChallenge() determines active challenges.
Against user experience. 
gameMode.isFreshStartChallenge() would always return true because gameMode.hasChallenge() would only check for the id of a challenge object and not check if it was activated or not (based on its value). The challenge object regardless of activation would always be present, meaning that isFreshStartChallenge() / hasChallenge() would always return true. This also cleans up the conditional used to block catches for easier reading. 
Fresh Start Uncaught Pokemon
Fresh Start Caught Pokemon
MonoGen Challenge Caught Pokemon
https://github.com/user-attachments/assets/d1038b79-1647-41e3-83f1-43cac1a35a15
MonoGen Challenge …
=> [Hotfix] End Biome Catch Problems 

src/data/pokemon-forms.ts, src/test/abilities/gulp_missile.test.ts
This fixes a bug where Cramorant could be stuck in Gulp Missile form after switching out, effectively stopping the ability from triggering.
This bug was reported [in the Discord](https://discord.com/channels/1125469663833370665/1274440885748367360)
- `data/pokemon-forms`: Added "Active" form change triggers for Cramorant's gulp missile forms --> base form.
- `test/abilities/gulp_missile.test`: Added test to verify Cramorant changes to base form after switching out.
`npm run test gulp_missile`
=> [Hotfix] Fix missing form change logic for Cramorant

src/battle-scene.ts, src/modifier/modifier.ts
The user can no longer steal Eternatus' MBH with Magician/Grip Claw/Pickup.
There's a bug in my room but it's flying too fast for me to swat it so I'm taking out my anger here. 
isTransferrable --> no longer readonly
new setTransferrableFalse() class function to set MBH's isTransferrable() property (private) to false 
https://github.com/user-attachments/assets/9a6d06aa-6c8c-43be-b242-08863cdb51b0
Fight 2nd phase Eternatus with a Pokemon that has Grip Claw / Pickup / Magician
=> [Bug][Hotfix] Final Boss MBH no longer transferrable

src/battle-scene.ts, src/data/ability.ts, src/test/abilities/disguise.test.ts, src/test/utils/phaseInterceptor.ts
Mimikyu and Eiscue will properly revert to their base form when the biome changes.
Bug report https://discord.com/channels/1125469663833370665/1274509830207307897
Added `.bypassFaint()` attribute to Disguise and Ice Face. Tests updated.
Have a fainted Mimikyu in Busted Form and beat wave 10.
=> [Hotfix] Make Disguise (and Ice Face) properly reset form on arena reset when fainted

src/ui/starter-select-ui-handler.ts
Fixed a bug occurring when only single rare/epic variant or a single rare form in Starter UI
If this bug exists, it prevents you from using a particular Pokémon's variant or form as your starting option even if you already possess it.
1. In the `setSpeciesDetails` function, when updating information such as shiny, variant, gender, and form via arguments, it was previously impossible to correct these settings if the default options were invalid or incorrect. Therefore, I added a process to correct these values to valid ones when calling `setSpeciesDetails`.
2. This fix also includes a correction process for gender, so the previous hotfix in #3601 is no longer needed. Executing this correction uniformly with variant, shiny, form at the function's start improves readability, so I will revert …
=> [Hotfix] Fixed a bug occurring when only single rare/epic variant or a single rare form in Starter UI

src/field/pokemon.ts, src/test/moves/rollout.test.ts
Relearner-only moves will now be available again when using the Memory Mushroom item.
It was broken.
Reverted the change to the passed parameters for `this.getLevelMoves()` in `Pokemon:getLearnableLevelMoves()`
Before fix:
https://github.com/user-attachments/assets/48e7fc3f-bf63-4974-8b42-5d5f7ed60eb5
After fix:
https://github.com/user-attachments/assets/56548d05-a05d-4330-85a8-d7bf21f33480
Use a Memory Mushroom item on a Pokémon with relearner-only moves.
=> [Hotfix] Fix Memory Mushroom not showing relearner moves

src/field/pokemon.ts, src/test/ui/transfer-item.test.ts, src/test/ui/type-hints.test.ts, src/test/utils/gameManager.ts, src/test/utils/helpers/settingsHelper.ts, src/test/utils/mocks/mocksContainer/mockContainer.ts, src/test/utils/mocks/mocksContainer/mockText.ts, src/ui/fight-ui-handler.ts
Fixes #3573 
Immune type-hints will be properly displayed again.
I broke it. I have to fix it
- `getTypeDamageMultiplierColor()` no longer returns `undefined` but always a number
- Test coverage for it. 
- New `SettingsHelper` in tests.
- Activate `type-hints` in settings (display)
- Open the moves menu with a dragon-move vs. a fairy (or a ground move vs flying)
- Open the moves menu with a status-move (e.g. growl). 
- https://github.com/pagefaultgames/pokerogue/pull/3597
- ~~[ ] If I have text, did I add placeholders for them in locales?~~
=> [Bug] Fix type-hints for immunity

src/battle-scene.ts, src/phases.ts
The user will not be able to steal MBH anymore. 
Against game design.
Previously, I believed that generateEnemyModifiers() in battle-scene.ts where Eternatus was given its MBH and applied a fix there. However, because generateEnemyModifiers() is random, there is a chance that Eternatus may not receive its MBH from this function and it must be given the MBH through some other function. This MBH does not have isTransferrable set to false.
Instead of chasing down these random functions, I edited the code found in EncounterPhase to remove the faulty MBH and manually add a MBH with a isTransferrable property set to false. This means the code written in generateEnemyModifiers() is useless. 
https://github.com/user-attachments/assets/1df00947-e202-4269-a81d-b6fd021f92c1
Wave X000 - Face …
=> [Hotfix] Steal-able Mini Black Hole Pt 2 

src/data/ability.ts, src/test/abilities/hyper_cutter.test.ts, src/utils.ts
Hyper Cutter (and similar abilities that prevented ATK drops via `ProtectStatAbAttr`) will only prevent the appropriate stat drops now.
`ProtectStatAbAttr` would prevent all stat drops if it was specified to prevent ATK drops only due to a `null` check incorrectly checking for `false`.
The `null` check is fixed to only check for `null` and `undefined`, and a test was added.
Attempt to inflict various stat drops against a Pokémon with Hyper Cutter.
=> [Hotfix] Abilities that prevent ATK drops no longer stop other stat drops

src/modifier/modifier.ts
When Grip Claw activates, the Pokemon's nickname will be used. 
Snailman Bug Report
The pokemon with grip claw's name is retrieved from GetPokemonNameWithAffix() now. 
https://github.com/user-attachments/assets/a9c94a0e-2567-4478-ad3c-d2eeb1d957ef
Use a Pokemon holding Grip Claw against a Pokemon with an held item that is transferrable
=> [Hotfix] Grip Claw activation message uses nickname now

src/data/move.ts
Dark Void from 50% -> 80% accuracy like in Gen 6.
Dark Void was nerfed in gen 7 due to pvp. This is looking to undo that.
A 50 to an 80 for accuracy.
Give something Dark Void, check accuracy.
=> [Balance] Dark Void 80% Accurate

src/test/moves/rollout.test.ts
N/A
The Rollout test can randomly fail if the player Pokémon gets Hustle as its ability.
The ability override is set to `Abilities.BALL_FETCH` to prevent ability interference.
Note that setting the ability override to `Abilities.NONE` is equivalent to disabling the override and letting the Pokémon use their normal abilities.
`npm run test rollout`
=> [Test] Fix Rollout test

src/locales/ko/move-trigger.ts
Users don't see wrong 'N' character anymore.
Line break should be \n but \N was found.
Just replace \N to \n
N/A
=> [Localization][KO] Fix wrong line break character

src/field/arena.ts, src/field/pokemon.ts, src/test/arena/arena_gravity.test.ts
> Closes #524 
> Partially mirrored from https://github.com/pagefaultgames/pokerogue/pull/693
When using `Gravity` the very-effective++ types against flying pokemon will stay very-effective++ instead of being just effective.
Cause grounding a flying pokemon should not remove the flying type. Just ignore the immunity 
Ground attack immunity is now checked at a different spot than before
https://github.com/user-attachments/assets/6c145d19-6d0f-48c6-bab4-7559fe196757
I used these overrides:
```ts
OPP_SPECIES_OVERRIDE: Species.PIDGEOT,
OPP_MOVESET_OVERRIDE: [Moves.SPLASH, Moves.SPLASH, Moves.SPLASH, Moves.SPLASH],
STARTER_SPECIES_OVERRIDE: Species.PIKACHU,
MOVESET_OVERRIDE: [Moves.GRAVITY, Moves.THUNDERBOLT, Moves.EARTHQUAKE, Moves.MAGNET_RISE],
} satisfies …
```
=> [Bug] Fix: Gravity tag removes flying type during damage calculation

src/data/move.ts, src/test/moves/tera_blast.test.ts
Tera blast now changes the type of damage dealt as the same type of the tera type applied to the mon. Tera blast also accounts for if the user is terastalized into Stellar type with increased base damage and dropping ATK/SPATK by one stage.
Tera blast is a commonly offered TM and loses a lot of utility due to the fact it's currently only possible to do Normal type damage. Also gives more incentive to pick up the tera orb, tera shards, and teach tera blast more often.
Added a TeraBlastTypeAttr class to check if the Pokemon is terastalized and if so, change tera blast's dmg to that of the tera type.
Added a TeraBlastPowerAttr class to check for if the user is tera'd into the Stellar type, and if so make the base power of tera blast 200 instead of 100 to account for the missing 2x dmg by …
=> [MOVE] Some more implementation for Tera Blast

src/ui/target-select-ui-handler.ts
The Target Select UI will have a wider range of opacity and so, resolve current complaints about it being too subtle. 
https://github.com/user-attachments/assets/17d6e81b-b4a9-49dd-8078-3905e8536b5e
Some people did not like the current change + I wanted to put it to a vote + have more time for this change to cook in beta.
The opacity cycles through 1 to 0.25. 
Double Battle
=> [UI] Increase Target Select UI Opacitiy

src/system/game-data.ts
The user will be able to export data in live versions of the game.
When I was testing, I mostly stuck to a local environment and I did not realize that Run History's exportation would be treated differently in live b/c of the state of bypassLogin. I apologize for the oversight. 
A ternary is used to determine if the data needs to be decrypted or decoded from Base64 based on whether the datatype is GameDataType.RUN_HISTORY
Use a non-guest account or set bypassLogin to false. You should still be able to export your run history without issue.
=> [Bug] Run history export data patch

src/ui/scroll-bar.ts, src/ui/starter-select-ui-handler.ts
Improves on the scroll bar graphic by making it resize like a proper scroll bar.
The scroll bar is sized differently, to correctly show the size of the starters list.
I simply wanted the scroll bar to reflect the actual size of the window.
Genesect doesn't need its own page, trust me.
Instead of `page` in `scroll-bar.ts`  representing the number of 9x9 windows shown, it represents the number of rows onscreen. When Gen 5 is shown, 10 rows (9 full rows + 1) are visible, so the scroll bar should take up 9/10 of its rectangle.
Other values using `page` are updated to reflect this new value range.
Gen 5 before.
Gen 5 after.
All starters before.
All starters after.
Simply open the starter menu (press New Game). The difference will be immediately apparent.
It's most obvious when filtered to show …
=> [Enhancement] Make the scrollbar cursor size more natural in the starter select UI

src/data/ability.ts, src/test/abilities/disguise.test.ts
If Mimikyu faints due to taking damage from its Disguise breaking, it will no longer faint twice (which would potentially clear 2 waves at once).
Fixes #3676 
The call to `damageAndUpdate()` in `FormBlockDamageAbAttr` now passes `true` to the `preventEndure` and `ignoreFaintPhase` parameters.
https://github.com/user-attachments/assets/779684fa-2c75-448f-b7ae-1af75477e2da
Use a move like Leech Seed or some other damage-over-time status move (not an attacking move) to get an enemy Mimiyku to 1 HP, then hit it with an attacking move to break the Disguise and cause it to faint from the Disguise break damage. Alternatively just console its HP to 1.
=> [Bug] Fix duplicate `FaintPhase` if Mimikyu faints to Disguise damage

src/ui/game-stats-ui-handler.ts, src/ui/text.ts
Add animated arrows at the top of bottom of the Stats screen, and fix the windows broken look
- There is currently no indication that there are more stats to see than the ones shown on screen when opening the menu
- Since PR #2525 made changes to the way window masking worked, the windows composing the stats screen were looking wrong (see screenshots below)
- Add arrows to show if we can scroll up/down the list
- Fix the windows look
- Change the font color for legacy theme as the stats were showing white on white before
Before (current beta/main): 
(For reference, here's how it looked before PR #2525):
After: 
https://github.com/user-attachments/assets/c2acb07b-f404-47e9-a11f-473f66e4adb3
Before, legacy theme:
After, legacy theme:
* Open the stats screen, move up/down and make sure the …
=> [QoL] Add arrows in the Stats screen to show it is scrollable

index.css
Change background-color to black if display-mode is fullscreen, fullscreen which is the mode defined in `manifest.webmanifest`.
Small modification to ensure a totally black background for fullscreen display, allowing the application installed in PWA mode to benefit from all the advantages of an OLED screen when so equipped.
Adds CSS rule to `index.css`.
```css
@media (display-mode: fullscreen) {
body {
background: #000000;
}
}
```
> Before
> After
It is possible to switch to “adaptive view” on the browser, then switch to fullscreen, the background should change from its normal color to black.
=> [QoL] Better support for OLED screens in PWA application mode

src/system/game-data.ts, src/ui/run-info-ui-handler.ts
Money displayed correctly. 
Import message cleaned up a little. 
Japanese text corrected.
Responsive Header Button
Because I'm silly. 
- Money was not being displayed correctly because I misread how Utils.formatMoney() worked when implementing the changes from #3646 - The UI would then show the player 1000 pokedollars regardless of result.
- I noticed the message that warns you about your data being overwritten before import was not localized. I feel like this should be left to a separate PR by the localization team, but because it used the data name - "run_history", it looked awkward so I tried sprucing it up a bit.
- Japanese text was assigned a higher lineSpacing value during its creation if its lineSpacing was less than 12. This patch corrects for it so that Japanese text does not …
=> [Bug] Run History Day 1 patch

src/ui/modifier-select-ui-handler.ts
no longer this:
Cause I broke it 
I've fixed the condition that checks the cursor movement. I put the wrong check into the lock rarities cursor ID
https://github.com/user-attachments/assets/2288f7f8-84f8-43d3-9c26-ba0605bf1262
https://github.com/user-attachments/assets/2400716a-ce49-409f-8494-3f453642092b
Win a wave and move the cursor at the bottom.
to test with the extra button
`src/ui/modifier-select-ui-handler.ts#L145`
```ts
//     const canLockRarities = !!this.scene.findModifier(m => m instanceof LockModifierTiersModifier);
const canLockRarities = true;
```
=> [Bug] Fix lock rarities behavior

src/ui/achvs-ui-handler.ts
The user will see the description of the first achievement or voucher change even if they only pressed the action button and did not move their cursor. 
I fixed this issue when making this PR but when chasing down a different bug, I overlooked what I did to fix this bug and this bug went into the main release. 
this.setScrollCursor(0) gets called twice. this.setCursor is called as this.setCursor(0, pageChange = true) so that the achievement/voucher updates correctly. 
https://github.com/user-attachments/assets/7a73212d-f168-436f-899a-7314d91a1520
Go to Achievements and press the Action button.
=> [Bug] Achievements/Vouchers doesn't update if Cursor doesn't move

src/ui/starter-select-ui-handler.ts
For some Pokemon it was possible to cycle to the Hidden Ability even if it wasn't properly unlocked. This fixes that
In #3138 the way HA is handled for Pokemon with a single ability was changed and for some time before it was fixed it was possible to catch Pokemon with their ability 2, thus unlocking it in the dex attributes
For these specific Pokemon it is now possible to switch to the HA at starter select even if the HA wasn't actually unlocked properly.
Starting the run like this and evolving the Pokemon would then result in the HA getting actually unlocked
This PR prevents starting with an invalid HA in the first place
The Pokemon with this issue have ability 2 marked as unlocked even though it's the same as ability 1.
The code handling cycling through abilities took this into account …
=> [Bug] Prevent being able to start with a hidden ability that's not unlocked for some Pokemon

src/test/eggs/egg.test.ts
N/A
The test file needlessly created a whole new game/scene for every test when it didn't need to.
The test file uses ~75% less memory now by only creating a single game/scene at the beginning, and takes ~10 less seconds to complete too. Also the rest of the test file got auto-formatted by my IDE 🤷.
`npm run test egg -- --logHeapUsage`
Before:
After:
=> [Test] Fix egg tests (memory use: ~2.4G -> ~550M)

src/test/abilities/forecast.test.ts
N/A
One of the Forecast tests could randomly fail. Additionally, due to memory leaks, the Forecast test suite could use up over 2GB of memory.
Consolidated a bunch of tests into one test, removed a test that doesn't belong & randomly fails.
`npm run test forecast`
If you want to view the memory usage of tests you can add `-- --logHeapUsage` to the end of the command.
- ~[ ] If I have text, did I add make it translatable and added a key in the English language?~
=> [Test] Refactor/consolidate Forecast tests

src/field/pokemon.ts, src/test/moves/multi_target.test.ts
Single-target moves won't incorrectly deal reduced damage in double battles.
Damage was being calculated incorrectly in double battles.
`Pokemon:apply()` now takes an additional parameter `targets` which is the number of targets being hit by the move, which is used to calculate the multi-target damage reduction.
`npm run test multi_target`
=> [Bug] Multi-target damage reduction is now properly calculated

src/test/moves/belly_drum.test.ts
n/a
belly drum tests can fail if the player pokemon faints when the enemy mon uses a damaging move
replaced enemy's moveset with splash only
`npm run test belly_drum`
=> [Test] Fix failing belly drum test

src/battle-scene.ts, src/field/pokemon.ts, src/ui/egg-gacha-ui-handler.ts, src/ui/starter-select-ui-handler.ts
The sounds below will be moved from SE to BGM:
- "level_up_fanfare"
- "item_fanfare"
- "minor_fanfare"
- "heal"
- "evolution"
- "evolution_fanfare"
In addition, some sound effects were missing the correct keys. Fusion cries in particular.
I wasn't sure how to classify the above sounds since they are common sounds heard in gameplay. However, after playing in Beta, I realized that these short sounds would be better fit under the category of BGM. 
battle-scene.ts: playSound() has been updated to treat these sounds as BGM. I felt that it was better to stack the various cases instead of resorting to default: b/c developers would be able to easily see which sounds fell under the BGM umbrella. 
key references have their correct categorization added if missing. 
- Tinker with BGM settings and …
=> [Bug] Some Audio changes and adjustments

src/modifier/modifier-type.ts
- Should prevent Pokemon whose form does not match the requisite "pre-form" of a given evolution and form change item from "accepting" those items during reward selection (for example, Cosplay Pikachu forms should not take `Thunder Stone`s or `Max Mushroom`s)
- Should prevent form change items whose requisite "pre-form" is not in the current party from being pushed as a possible item reward
A plethora of bug reports have been filed specifically noting how, if a Pokemon cannot evolve or use a given form change item in any meaningful way, it shouldn't be able to take that item while both doing nothing and preventing the user from getting a different reward; that is, we shouldn't punish players who don't already know the interaction by allowing them to accidentally pick a useless reward that …
=> [Bug] Add Pre-Form Checks for Evolution & Form Change Items

src/battle-scene.ts, src/locales/de/battle.json, src/locales/en/battle.json, src/locales/es/battle.json, src/locales/fr/battle.json, src/locales/it/battle.json, src/locales/ja/battle.json, src/locales/ko/battle.json, src/locales/pt_BR/battle.json, src/locales/zh_CN/battle.json, src/locales/zh_TW/battle.json, src/ui/message-ui-handler.ts
In messages-ui-handler, the category 'se/' was incorrectly prefixed to the audio key and would lead to a freeze/issue when a Pokemon forgot a move during LearnMovePhase.
In addition, the conditional checking for extra loud move sounds wasn't correct. 
This is my responsibility + I believe that this prefix isn't helpful for those who want to add more sound effects to dialogue found in locales. 
- '/se' prefixing removed from message-ui-handler.ts
- Dialogue updated so that it refers to the correct sound key. 
- Conditional updated. 
Have a Pokemon forget a move. The correct sound effect should play during the '1.. 2... 3... and Poof (pokeball-release sound)'
=> [Beta][Bug] Sounds in Dialogue Changes

src/data/move.ts
Decorate will now bypass protect.
So that Decorate follows the intended behavior.
Closes #3843 
Decorate now ignores Protect.
Use Decorate on a Pokemon using Protect.
=> [Bug]: Make Decorate Bypass Protect

src/data/move.ts, src/overrides.ts
Unseen Fist + direct contact moves allow the user to ignore abilities (e.g. Sturdy)
It's a bug
Discord report: https://discord.com/channels/1125469663833370665/1274675083872436235
Adds a break in the switch case, so that it doesn't fall through to `IGNORE_PROTECT` when checking if a move should ignore abilities.
https://github.com/user-attachments/assets/3307af07-dd60-4cf6-accf-c57dd0a7c26b
Give pokemon Unseen Fist + direct contact move. Give opponent Sturdy, see that it no longer KOs through Sturdy
- [n/a] If I have text, did I add placeholders for them in locales?
=> [Bug] Fixes Unseen Fist ignoring abilities

src/data/pokemon-species.ts
When a Pokemon's forms rely on the same variant `_masterlist` entry, instead of having one per form, variant icons will now correctly appear.
Reported [here](https://discord.com/channels/1125469663833370665/1238339524778790922/1275188605316501596) and [here](https://discord.com/channels/1125469663833370665/1229465263532019712/1274491742821027894).
Although #3322 addressed a different set of variant icons not appearing, it in turn caused the current batch of issues.
The way that variant icons work is that the game does not know to load them unless it finds an entry in the `_masterlist` that tells it to. When each form is loaded, the affected code determines the name of the form that the game looks for in the `_masterlist`.
#3322 replaced `formKey` with `formSpriteKey`. This distinction …
=> [Bug] Show variant icons when forms share masterlist entry

src/locales/en/pokemon-summary.json, src/locales/ko/pokemon-summary.json, src/ui/summary-ui-handler.ts
Other language : No changes
Korean : Can see nature as og games. (like curren main, before 3rd beta merged.)
gitlocalize removed Korean translation. https://github.com/pagefaultgames/pokerogue/pull/3773/files
1. Add natureFragment key and value in en, ko > pokemon-summary.json
2. modify summary-ui-handler.ts to call it, not conditional(because condition always return true.)
**Check TRAINER MEMO > nature part.**
* current main
* current beta HEAD (After gitlocalize https://github.com/pagefaultgames/pokerogue/pull/3773)
* after fix
Manually. (Just run game and open pokemon > choose pokemon > go Summary
=> [Fix][Localization] Add missing pokemon summary natureFragment

src/test/utils/gameManager.ts, src/test/utils/helpers/classicModeHelper.ts, src/test/utils/helpers/dailyModeHelper.ts
N/A
Daily Mode was missing a function to run to the start of a battle
Tests for Daily Mode can now start a wave and continue from there.
Write a test using the new functions.
=> [Test] Create the appropriate `startBattle()` functions in the helper classes

src/system/game-data.ts
PokeRogue will no longer freeze when the user hits more than 25/the provided limit of entries in run history. 
My feature, my mistake. 
I swear I fixed this earlier...
The variable timestamps is no longer a constant and is updated at the end of the loop. 
https://github.com/user-attachments/assets/fa5f64a3-8578-456e-99c0-ef2202d1a9c7
- Have a full run history
- Complete a run
- The run should end normally and the run should be logged as expected.
=> [Bug][Beta] Run History Limit-Infinite Loop

src/data/biomes.ts
Users will no longer be stuck in a loop with Plains. 
Damo please give all cat Pokemon OP moves and amazing passives. 
In the function traverseBiome, if the Biome.END is passed to it, a random Biome is picked out of the list of biomes and the game then determines the new path based on that biome. This is achieved by using a while loop with a conditional that the new biome is not Biome.END again. 
https://github.com/user-attachments/assets/901c8289-9540-4da9-99b7-6bac3b705d10
https://github.com/user-attachments/assets/2c236d97-b283-4360-9010-ce5b200e1de5
- Defeat the boss on Wave X50/X00 of Endless
- The biome should be random. (Note: the biomes will never be end / plains / town)
=> [Balance] Randomized Biome after End Biome

src/modifier/modifier-type.ts
- Fixes a bug introduced by #3839 that prevented the use of evolution items on mons without forms
- Big bug introduced by #3839 should be fixed
- The above PR implemented the form check by checking if the evolution had the same form key for pre and post evolution. However, if these were null (as is the case in any SpeciesEvolution), the check would fail.
- Changed that check to be true if the evo's pre form key is null or if the previously used pre/post form key check is true
Before:
After:
Take any mon that evolves with an item into a run. Change the weight of evolution items to 100.
=> [Bug] Fix evolution items not working on mons without forms

src/data/ability.ts, src/phases/command-phase.ts, src/phases/enemy-command-phase.ts
Trapping abilities will once again show failure messages if the user attempts to switch or run away under normal circumstances.
I want the beta to go live and this bug is in the way. 
The changes introduced in #3529 clashed with the changes introduced in #3271 leading to this bug. This merges the two so that the changes from #3271 can actually be used. 
quiet class variable changed to isQuiet for consistency too
https://github.com/user-attachments/assets/4589807e-af15-4cb5-89d5-5a365dfcb8e7
Attempt to switch or run away against a Pokemon with a trapping ability.
=> [Beta][Bug] Fixing Trapped ability messages

src/data/daily-run.ts
In a way... none.
It was possible (though extremely unlikely) for the RNG to generate a 9+ cost Pokémon as the first starter in Daily Run mode, thus causing the third Pokémon to be a 0 cost (which doesn't exist) and crashing the game.
The cost of the first starter in Daily Run mode is now capped at 8.
Start a Daily Run and see that the game doesn't crash. et voilà
=> [Bug] Prevent daily runs from breaking due to very (un)lucky RNG

src/ui/modifier-select-ui-handler.ts
This attempts to fix a bug where the menu can't be opened up in the shop after a trainer battle
Currently you can't open the menu in a shop after a trainer battle
scene has a boolean for disableMenu. During the trainer victory phase, this is set to true, which is then used throughout the shop, disabling the menu. This makes it so whenever the shop is opened, disableMenu is set to false, thus enabling the menu.
This is how it currently is in beta (even when trying to open the menu):
This is how it is with the fix:
Download this PR, get to trainer wave and attempt to open the menu. Also make sure that this doesn't have any negative side effects of allowing the menu to open where it shouldn't. It doesn't open when you go to "check team" - this is intended and separate to this, so that …
=> [Bug] Menu can't be opened in shop after a trainer battle

index.css
Mobile users can access buttons on RunInfo.
My feature. Mobile users may be unable to see the screen but they will have their buttons.
CSS updated to have gamepad buttons visible if Mode = RUN_INFO too.
Go to Run Info with the gamepad open.
=> [Beta][Bug] Run info game pad fix

src/ui/dropdown.ts, src/ui/starter-select-ui-handler.ts
- In the starter select UI, when filtering for mons you don't have the hidden ability of, mons who don't have an HA at all will be excluded
- When filtering for mons you don't have passive or any cost reduction unlocked for yet, starters who don't have candy (Pikachu et al) will be excluded
- The "Hidden Ability- No" option is useful for seeing which mons you haven't found the hidden ability of
- It's redundant and possibly misleading to show the player mons with nonexistent hidden abilities alongside mons with hidden abilities the player just hasn't found
- Same applies even moreso to passives and cost reductions
- This makes the filters more useful for giving an overview of goals for the player
- Adds a speciesHasHiddenAbility check for the HA filter
- The condition for the exclude …
=> [UI] [QoL] [Enhancement] Exclude redundant species from certain filters in starter select

src/data/ability.ts, src/data/move.ts, src/data/pokemon-forms.ts, src/field/arena.ts, src/test/abilities/flower_gift.test.ts
Cherrim should now transform during Harsh Sunlight similar to Castform
Cherrim does not transform on Harsh Sunlight
Added form change conditions - attached to what Forecast is using
Use Cherrim and set weather to Harsh Sunlight/Sunny
=> [Ability] Add form change support for Flower Gift

src/data/pokemon-species.ts
G-Max Butterfree has the correct ability as intended
damo forgor
Change pokemon-species.ts
Override with G-Max Butterfree
=> [Balance] [Hotfix] Butterfree Gmax Ability Fix

src/field/pokemon.ts
RNG will be unaffected by accessing save-slot-select UI, run history UI, or run-info UI.  
Bug Report: https://discord.com/channels/1125469663833370665/1279928555186290698/1280005345321816136 
The RNG calls have been moved until after the Pokemon has been checked for an ability index. Because the PokemonData involved in these UIs already have an ability index, the RNG calls will not be called. This will not affect Pokemon generation for battle. 
Will upload a run tomorrow morning. Sorry, very tired. Feel free to test though.
Start and play a wave (do not complete) --> Save and Quit --> Open Run History/Load Save/Run Info --> Go back to the wave and repeat the same actions.
The second playthrough should be identical in results to the first playthrough.
=> [Hotfix][Bug] Unneeded RNG calls

src/data/battler-tags.ts, src/test/moves/octolock.test.ts
Fix https://github.com/pagefaultgames/pokerogue/issues/3876
User should now appropriately see octolock lowering only spdef for big pecks, and lowering neither stat for white smoke and clear body users
To fix [https://github.com/pagefaultgames/pokerogue/issues/3876](link)
In src/battler-tags.ts, on line 753 
`      pokemon.scene.unshiftPhase(new StatChangePhase(pokemon.scene, pokemon.getBattlerIndex(), true, [BattleStat.DEF, BattleStat.SPDEF], -1));
`
The system incorrectly assumed that octolock was a self targeting move, which was messing with the ability from cancelling out the effect as intended. I changed it to: 
'      pokemon.scene.unshiftPhase(new StatChangePhase(pokemon.scene, pokemon.getBattlerIndex(), false, [BattleStat.DEF, BattleStat.SPDEF], -1));
' …
=>  [Bug] Fix Octolock Ignores Clear Body, White Smoke, Big Pecks #3876

src/field/pokemon.ts, src/modifier/modifier.ts
More shinies!
Shiny threshold doubled from 32 to 64. Shiny Charm effectiveness reduced by half to compensate.
Play the game.
- ~[ ] Are the changes visual?~ yes but no
=> [Balance] Double base shiny odds, adjusted Shiny Charm to match

src/locales/en/challenges.json, src/ui/challenges-select-ui-handler.ts
The user will not able to continue from the Challenges Select UI if no challenges are currently active. The 'Start' button text will only appear if the user has activated a challenge. If the user hasn't, the button text will be set to "None Selected"
pokemon go to school
- new class variable 'hasActiveChallenge' that is a boolean determined by if the user has activated a challenge and determines if the user is eligible to continue into the starter select screen
- new UI behavior that responsively reacts to the user's actions and indicate to them whether a challenge has been selected or not
https://github.com/user-attachments/assets/984a61b7-539f-4925-9d62-f51952ace36d
Try to access the starter select UI without activating a challenge
=> [UI][Misc] Force users to have an active challenge

src/modifier/modifier-type.ts
Ineligible Pokemon will not contribute to luck in a challenge.
Against game design.
Issue #3955
The conditional used in getPartyLuckValue() to filter eligible Pokemon has been changed from p.isFainted() to p.isAllowedInBattle() --> which also checks if the Pokemon is fainted.
The ternary has also been reversed for readability to the below.
p.isAllowedInBattle() ? p.getLuckValue : 0
Video #1 : MonoGen 3 -> numerous shiny ineligible Pokemon were caught with no change to luck
https://github.com/user-attachments/assets/c9483066-34aa-4413-96db-214f3d0ac617
Video #2 : MonoGen 1 --> eligible shiny Weedle caught (Luck up!) + ineligible shiny Bidoof caught (No change to Luck) 
https://github.com/user-attachments/assets/2b79b726-72fd-4947-8f40-6264f11928be
Be lucky like me.
Or use the overrides to …
=> [Bug] Ineligible Pokemon will not contribute to luck in a challenge

src/test/boss-pokemon.test.ts
N/A
The timeout was set too short, causing the test to fail due to running too long.
The timeout for tests in the `boss-pokemon.test.ts` file was changed from 2.5 seconds to 20 seconds.
`npm run test boss-pokemon`
=> [Test] Set boss Pokémon test timeout to 20 seconds instead of 2.5 seconds

src/test/abilities/beast_boost.test.ts
N/A
The test can randomly fail.
The player Pokémon's stats array is mocked so that the test assumptions are always true.
`npm run test beast_boost`
=> [Test] Remove nature RNG from Beast Boost tests

src/ui/command-ui-handler.ts, src/ui/fight-ui-handler.ts, src/ui/party-ui-handler.ts
In the command UI, the cursor will default to FIGHT if the previous cursor position was FIGHT or POKEMON.
In the fight UI, the cursor will default to the upper-left move / first move when a Pokemon has its first turn. Otherwise, it will remember its last position. 
In the party UI, the cursor will default to the first Pokemon.
Seems straightforward. 
The setCursor() is set to 0 when the UI is first displayed + meets the requirements. 
Changed the cursor-based switch statement to use the Command enum instead of integers for better readability.
https://github.com/user-attachments/assets/6f77e0d4-e2f8-419a-8386-bde697c70050
https://github.com/user-attachments/assets/36c46c00-e9d5-4595-aa18-51b3880f32ea
Works for doubles. See below video. …
=> [Misc][UI] Default Cursor Positioning for Command / Fight / Party

src/battle-scene.ts, src/enums/shop-cursor-target.ts, src/locales/de/settings.json, src/locales/en/settings.json, src/locales/es/settings.json, src/locales/fr/settings.json, src/locales/it/settings.json, src/locales/ja/settings.json, src/locales/ko/settings.json, src/locales/pt_BR/settings.json, src/locales/zh_CN/settings.json, src/system/settings/settings.ts, src/test/items/dire_hit.test.ts, src/test/items/temp_stat_stage_booster.test.ts, src/ui/modifier-select-ui-handler.ts
- entering daily run's rewards phase should no longer soft lock when the shop cursor target is set to `Shop`
- changed "Items" label to "Rewards"
- set the default option to `Rewards`
- set the default option to be left-most/first option
Addressing feedbacks:
- P1: Game can softlock if it's set to "Shop" before buyable shop items introduced - in Daily Run mode
- Some of the terms are ambiguous. "Items" can refer to the buyable items, the free ones, or transferring items. Someone suggested "Rewards"
- Move the default option back to the original please (Rewards)
- The default most common option (Rewards) should be the first option
- added an index mapping of options-enum to avoid the risk of mismatching the option keys and the shop cursor targets enum
- added condition to check the current …
=> [P1 Bug][UI/UX] Address shop cursor target feedbacks

src/test/ui/starter-select.test.ts, src/ui/starter-select-ui-handler.ts
Shiny with highest variant being enabled by default on starter select is back!
Since #3373, the starter UI has defaulted to Pokemon being non shiny, and the lowest unlocked variant being selected by default when enabling shiny.
This has caused some frustration and confusion for players especially since the preferred setting is kept only locally, so switching device, deleting cookies or getting a new variant requires to change the setting manually each time. 
* updated `getCurrentDexProps` to return the highest unlocked variant
* updated the logic when enabling / disabling shiny state
* updated starter select test to account for the change
Before:
After: ✨ 
There are (somewhat incomplete) tests for the UI that check for switching shiny and variants:
`npm run test …
=> Starter select defaults to shiny with highest variant again

src/ui/battle-message-ui-handler.ts
The IV scanner properly reveals the highest stats
The logic for showing the highest IVs when using the IV Scanner was lost somewhere along the way during the stats refactoring, this PR fixes that
[full bug report on discord](https://discord.com/channels/1125469663833370665/1280876551247892580/1280876551247892580)
Sort the stats pools by highest IV and return the top stats
Before (current beta), the first IVs would always get shown instead of the highest ones: 
After: 
You can use the save files [from the bug report](https://discord.com/channels/1125469663833370665/1280876551247892580/1280887442307809312) 
Or an override: 
`STARTING_MODIFIER_OVERRIDE: [{name: "IV_SCANNER", count: 1}]`
=> [Bug] Fix getting the highest ivs for the iv scanner

src/locales/en/arena-flyout.json, src/locales/en/arena-tag.json, src/locales/en/move-trigger.json
Safeguard will have English text now.
The English text for Safeguard got removed during the i18n switchover.
English text was added to `en/arena-tag.json` and `en/move-trigger.json` for Safeguard.
Use Safeguard in a battle.
=> [i18n] Re-add lost i18n strings for Safeguard

src/battle-scene.ts
No game crash between biomes b/c a cry was accidentally deleted. 
My mistake, my cheese brain. 
When a player changes biomes, a Pokemon's cries - if missing - are not reloaded. This could lead to a crash if an active Pokemon is missing their cry from the game files. 
The function scene.getActiveKeys() forgot to check and include the bottom-half of fused Pokemon in its white-list of keys. This meant that garbage collection would accidentally deleted it. 
https://github.com/user-attachments/assets/e460bfac-dc9a-4ceb-bb3e-6af607dd0a04
Play game on a Biome Change with a fused Pokemon.
Overrides -> Free Eggs, Instant Hatch
=> [Bug][Beta] Garbage Collection should ignore active cry keys of bottom-half fusions

src/modifier/modifier.ts
mbh activation message will now show the user's nickname
Consistency. Also closes https://github.com/pagefaultgames/pokerogue/issues/4030
changed `pokemon.name` to `pokemon.getNameToRender()` 
```ts
readonly STARTING_HELD_ITEMS_OVERRIDE: ModifierOverride[] = [{name: "MINI_BLACK_HOLE", count: 1}];
readonly OPP_HELD_ITEMS_OVERRIDE: ModifierOverride[] = [{name: "LUCKY_EGG", count: 99}];
```
=> [P3 Bug] Fixed mbh not using the user's nickname

src/test/moves/rage_powder.test.ts
N/A
closes #4034 
`test/moves/rage_powder.test`:
- Added missing calls to `forceEnemyMove`. Exactly one enemy is now forced to use Rage Powder in the test that was failing
- Removed a redundant `starterSpecies` override
N/A
`npm run test rage_powder`
=> [Test] Fix Rage Powder test failing randomly

src/test/abilities/parental_bond.test.ts
N/A
A test for Parental Bond failed randomly in a PR, and the tests could use some cleanup
`test/abilities/parental_bond.test`:
- Magikarp/Feebas are now used as player Pokemon for most of the tests instead of Charizard/Pidgeot to eliminate the risk of unexpectedly KOing enemy Pokemon. Previously, the Wake-Up Slap test would sometimes fail because Charizard had a chance to OHKO the enemy Snorlax if Snorlax spawned with a -Def nature.
- Removed unnecessary checks on whether the player and enemy Pokemon were defined (`battle` tests already cover this)
- Updated deprecated `startBattle` calls to `classicMode.startBattle`
- Removed outdated comments
- Other small style changes
N/A
`npm run test parental_bond`
- [n/a] Have I provided screenshots/videos of the …
=> [Test] Fix random failure in Parental Bond tests

lefthook.yml
Update lefthook config so it isn't as disruptive. 
To open a discussion as to what is the most ergonomic way to use git hooks.
Running eslint every time we merge or rebase the newest changes from main feels bad
Lefthook config options
N/A
Checkout the branch and make some dummy commits / merges / rebases
=> [QoL] Skip pre-commit on merge and rebase, add pre-push

src/locales/de/arena-flyout.json, src/locales/es/arena-flyout.json, src/locales/fr/arena-flyout.json, src/locales/it/arena-flyout.json, src/locales/ko/arena-flyout.json, src/locales/pt_BR/arena-flyout.json, src/locales/zh_CN/arena-flyout.json
Restoring "Safeguard" entries in arena arena-flyout.json of all locales where it existed, like #4024 does with English
To restore them
=> [Localization] Restoring "Safeguard" entries in arena-flyout.json of all locales where it existed

src/data/egg.ts
Higher likelihood of Same-Species Eggs giving shiny pokemon.
- Rates have gone from 1/24 -> 1/12
The MATH ain't MATHING! It might be cooked.
A 24 -> 12
Merge to a local or play on the beta, spam same-species eggs.
Or just do math.
=> [Balance] Same-Species Eggs Shiny Rate Increase

src/data/move.ts, src/test/moves/protect.test.ts, src/test/moves/quick_guard.test.ts
The following moves now fail if the user is last to move, mirroring their behavior in mainline:
- Protect and its offshoots (e.g. Spiky Shield)
- Endure
- Wide Guard
- Quick Guard
- Mat Block
- Crafty Shield
closes #1746 
- `data/move`: New `failIfLastCondition` causes moves with the condition to fail if the user is last to move on that turn.
- `test/moves/protect.test` and `test/moves/quick_guard.test`: New tests checking the new fail condition.
`npm run test protect`
`npm run test quick_guard`
=> [Move] Make protection moves fail when used last in a turn

src/data/move.ts
No functional change, this just removes the (P) tag from Tera Blast
Tera Blast is marked as partial because of "the lack of Stellar offense typing implementation in the typings", but it already WORKS with stellar types - ~it's just that it is not yet obtainable in-game~ it is obtainable in-game
removed `partial()` from tera blast
=> [Misc][Move] Remove partial tag from Tera Blast

src/test/moves/dragon_cheer.test.ts
none
adding tests to https://github.com/pagefaultgames/pokerogue/pull/3959 now that it is possible
dragon cheer test
`npm run test dragon_cheer`
=> [Test] Add Dragon Cheer tests

src/data/ability.ts, src/data/move.ts, src/locales/en/ability-trigger.json, src/test/abilities/aura_break.test.ts
This fixes a bug where Aura Break would apply its power debuff despite Dark and/or Fairy Aura not being present on the field
closes #4050 
- `data/ability`: Changed Aura Break's condition (in its `conditionalAttr`s) to check all active Pokemon on the field for Dark/Fairy Aura instead of a single "target" Pokemon (or, really, just Aura Break's source under a misnamed arg).
- `data/move`: Changed `Move#calculateBattlePower` so that field aura attributes that don't satisfy their conditions from `getCondition()` are filtered out before applying.
- `test/abilities/aura_break.test`: New test covering the case where neither Dark Aura nor Fairy Aura are present.
`npm run test aura_break`
=> [Bug] Fix Aura Break applying without Dark/Fairy Aura present

src/phases/game-over-phase.ts
They will see the actual endless end dialogue
It was only displaying `ending_endless` because the `PGM` prefix was still present
`PGM` prefix was removed. Gender context is now passed
<details>
<summary>📷 Screenshot (Before)</summary>
</details>
https://github.com/user-attachments/assets/f22dc6e3-3b1d-4c9f-9706-9578432ef8bf
```ts
STARTING_WAVE_OVERRIDE: 5850,
OPP_LEVEL_OVERRIDE: 1,
OPP_SPECIES_OVERRIDE: Species.MAGIKARP,
STARTING_LEVEL_OVERRIDE: 10000,
```
=> [Bug] Missing endless end dialogue

.github/workflows/tests.yml, vitest.config.ts, vitest.workspace.ts
Reduce tests runtime hopefully
vitest projects were extended.
the test pipeline was updated to support better parallel testing
=> [Optimization] parallel testing

src/phases/attempt-run-phase.ts
When making the [escape calculation](https://github.com/pagefaultgames/pokerogue/pull/3973), at one point I accidentally changed to using Utils.randSeedInt instead of using something scene related. This has now been updated to use playerPokemon.randSeedInt instead like the old method was.
In my escape calculations I accidentally made it so the random call was using Utils instead of playerPokemon due to various changes in how things were going and didn't realise. Kev pointed out in discord this is wrong and should be using playerPokemon, so this PR updates it
I've changed a usage of Utils.randSeedInt to be playerPokemon.randSeedInt
N/A
Download this PR and attempt to run away
=> [Bug] Escape calculation rand seed fix

src/phases/egg-summary-phase.ts
Fix missing line from egg summary phase. Sets enemy modifiers back to visible after the egg summary ends
Before fix: missing enemy modifiers after egg summary page
WITH FIX:
Hatch eggs after wave 143:
=> HOTFIX show enemy icons after egg summary

src/data/weather.ts, src/field/arena.ts, src/phases/move-phase.ts
This fixes a bug where Harsh Sunlight and Heavy Rain would cancel moves based on their base type rather than their final type after move and ability effects are applied. For example, if a Tera-Water Pokemon uses Tera Blast in harsh sunlight, the Tera Blast will now have no effect.
This type check is done outside of `Pokemon.apply`, so I missed this when updating type effectiveness earlier.
`data/arena` and `data/weather`: The `isMoveWeatherCancelled` functions in these files now take a new argument `user: Pokemon` and use `user.getMoveType(move)` instead of `move.type` in their type checks.
https://github.com/user-attachments/assets/2fec1588-9222-4634-9087-ef043bf19a42
=> [Hotfix] Fix harsh weather cancelling moves based on base type

src/phases/egg-hatch-phase.ts
When hatching regularly (one by one) the setEggMoves() was undefined, this was usually caught by the egg summary page which has a redundancy for setting the dex for the hatchData. However if there is no egg summary (less than 5 eggs) then the egg move is not set or displayed right.
Added a simply adaptation to set the egg hatch phase this.eggMoveIndex variable from the hatchData egg move index variable.
=> [Hotfix] add catch for undefined egg moves

src/ui/form-modal-ui-handler.ts
All forms now allow plain text of up to 20 characters, up from 18
Changed the 18 max length to a 20
This is a screenshot of the admin panel with 20 characters in the username field:
Download PR and check to make sure you can enter 20 characters on the input fields
=> Updated all fields (except passwords) to allow for 20 characters

src/field/pokemon.ts
The enemy will no longer be able to switch if a player Pokemon's trapping ability (Shadow Tag/Arena Trap/Magnet Pull) is applicable.
I rewrote trapping logic in #3936 and introduced this bug
`field/pokemon`: `Pokemon.isTrapped` now checks Pokemon on the opposing side of the field instead of incorrectly always checking the enemy side of the field.
=> [Bug] Fix Enemies ignoring the effects of trapping abilities

src/test/moves/safeguard.test.ts
N/A
The test is broken.
The enemy Pokémon is now damaged before using Rest so that it will properly activate.
`npm run test safeguard`
=> [Test] Fix Safeguard test that relied on a now-fixed bug

src/ui/battle-message-ui-handler.ts, src/ui/move-info-overlay.ts
Adjusted line spacing for move descriptions and level-up stats specifically in the Japanese language.
These changes were requested by the Japanese translation team.
- The code now explicitly sets the line spacing for Japanese (ja) text using `setLineSpacing`. 
- For non-Japanese languages, the original line spacing values are retained to ensure no impact.
Additional Context:
- From the beginning of the Japanese support Pull Request ([PR](https://github.com/pagefaultgames/pokerogue/pull/2771/files#diff-0c7c16933483d4f2435326a1a85bf96441cadd77b72b1110fa6836cd886d6636)), the codebase has accumulated numerous `if` conditions to handle edge cases pertaining to the Japanese language. This PR's changes are a continuation of such special handling.
- Efforts to verify the initial purpose and the …
=> [Bug] Fix line spacing in level up stats and move info for japanese

src/system/version-converter.ts
Lures will no longer "refresh" when reloading save data or refreshing the page after data is saved after a wave finishes.
This was an oversight in the save migration algorithm; it was never intended to run more than once, which is essentially forced by the fact that the version number cannot be incremented past `1.0.4` at the moment.
The reason why lures were being set back to their `maxBattles` on reload is because the initial conversion from old lures to new lures takes the first argument of the `ModifierData` `args` array and setting it to the `battleCount`. This effectively takes the old `battleCount` to the new `battleCount` for accurate conversion. However, a side effect of the version number never incrementing is that the conversion would run again on reload/data parsing. As such, …
=> [Hotfix] Fix Lures Refreshing on Reload

src/ui/egg-summary-ui-handler.ts, src/ui/pokemon-info-container.ts
In egg summary, HA icon is now shown for all Pokemon who hatched with their HA, while before in some cases it wasn't
The icons for unlocks now show on top of the Pokemon sprite as well, while before it could get hidden by the Pokemon sprite or cursor
Fix issue #4134 
TDLR:
* problem 1: for some Pokemon species the HA icon is not showing even if the Pokemon has its HA
* problem 2: for Ferroseed the HA icon is always showing, even if it doesn't have its HA
- Check for the presence of the HA by using the `Pokemon.abilityIndex` instead of calling `Pokemon.hasAbility` which would always return true in the case of Ferroseed since its HA is the same as its normal ability
- (note: this also fixes issue 1, which was caused by the fact that by default `Pokemon.hasAbility` checks that the ability …
=> [Bug][UI] Fix HA icon not always showing in egg summary screen

src/modifier/modifier.ts
Picking up one battle item, lure, or `Dire Hit` will now no longer prevent an item of the same type.
Lapsing modifiers were intended to spawn more items of their same type to make its "refreshing" mechanic useful during runs.
`getMaxStackCount` was set to return `1` purely for getting rid of the stack count text that appears below an item at the top left of the screen, but this was causing lapsing modifiers to have no weighting during reward rolls. To get the best of both worlds, `getMaxStackCount` was set to `2` so that the `m.stackCount < m.getMaxStackCount` boolean doesn't equal `false` during weighting, and `getIconStackText` was overridden to always be `null`, effectively removing the text.
While I was doing that, I also changed a copy-paste typo in documentation. …
=> [Hotfix] Fix Lapsing Modifiers Not Rolling

src/ui/starter-select-ui-handler.ts
If enabled, the icon or animation for available candy upgrade will get updated properly after purchasing eggs, unlike now
Note: I will be referring only to the "candy upgrade icon" in the PR, but it's the same for the "animation" setting
There are two issue with the icon when purchasing candy upgrades currently:
- After purchasing an egg the icon showing that an upgrade is available is not removed even if there is not enough candy left to purchase more
- If the icon setting is set to "passive only", the icon is also not removed after reducing cost, even if there is not enough candy left anymore to purchase the passive
- Movde the code that handles updating the icon/animation to its own function `updateCandyUpgradeDisplay`
- Call it after all successfull candy purchases
Before: purchasing …
=> [Bug][UI] fix candy upgrade icon not updating after purchasing eggs

src/test/utils/gameWrapper.ts, src/test/utils/mocks/mockGameObjectCreator.ts, src/test/utils/mocks/mockVideoGameObject.ts, src/test/utils/mocks/mocksContainer/mockContainer.ts, src/test/utils/mocks/mocksContainer/mockSprite.ts, src/test/utils/mocks/mocksContainer/mockText.ts
N/A
Memory usage and performance of tests is becoming untenable.
Where possible, `vi.fn()` is replaced with `() => null` (or similar) in the various mock objects.
Btw if you had trouble running tests locally before you might be able to run them now.
Before:
After:
`npm run test`
=> [Test] Replace `vi.fn()` with `() => null` whenenver possible

src/field/trainer.ts
That Tate & Liza will have the same pokemon in the "same" run (same seed)
It was brought up here: https://discord.com/channels/1125469663833370665/1283277132235276329
Temp asked me to fix it since i was the one who implemented this unseeded
I used seeded  randomness instead of unseeded one
Screenshots of the error are in the discord link.
"Correct" screenshots would just be a lets play of me doing it. Please review the code and tests it yourself. I tested this like 4 times doing wave 19 and 20 differently and they always had the same pokemon.
Import this save. Do wave 19 and then check the pokemon in wave 20. For me it was solreck and lunala (those are scripted) and then guardevoir so it should also be for you also.
[Daily Run Double Gym Leader …
=> [BUG] Make Tate & Liza have seeded randomness

src/data/move.ts, src/test/moves/baddy_bad.test.ts
Moves like Baddy Bad won't activate their secondary effect if they fail (such as due to the target using Protect).
Fixes #4163 
`AddArenaTagAttr` only applies the arena tag if the move is successful.
`npm run test baddy_bad`
Override the opponent's moveset to Protect and give yourself Baddy Bad or a similar move.
=> [Bug] Baddy Bad shouldn't activate Reflect if the target uses Protect

src/ui/run-info-ui-handler.ts
Users will see accurate nature information. 
Button will not work when not visible.
New ternary. 
New conditional check for held items input
Will test soon. 
Change Pokemon nature with mints.
Lose run.
Pokemon's nature should be the changed one.
=> [Bug] Run History displays Pokemon that have their natures changed during the run

src/data/pokemon-forms.ts, src/modifier/modifier.ts
Implements the form changes when Terastallized, which affects Ogerpon and Terapagos. They will also revert to their non-Tera forms too when the Tera Crystal expires.
These form changes are unimplemented, and were requested fairly often.
Two new form change triggers were added, one for when Terastallized, and one when the Tera lapses. The triggers for these form changes were added in `modifier.ts` to make these new form change methods work.
Additionally, Castform, Cherrim, Cramorant, and Eiscue's form change entries were rearranged to be in the correct order, like the rest of the Pokémon listed in the `pokemon-forms.ts` file. They are otherwise unchanged.
Terapagos changing into it's Stellar form, then reverting to its Terastal form when the Tera Shard expires. …
=> [Enhancement] Implement Tera-based form changes

src/ui/menu-ui-handler.ts, src/ui/modal-ui-handler.ts
That the page does not crash when spamming Save & exit/Log out, interaction bugs when selecting and exiting quickly and optional integration of black background for modals
Fixes https://github.com/pagefaultgames/pokerogue/pull/3084#pullrequestreview-2192059356
Resolves https://github.com/pagefaultgames/pokerogue/issues/3048 by @flx-sta
Incorporating ``` LOADING ``` modal to avoid spam on buttons and I changed the ui.showText to this.showText so that it references the menu correctly, as well as including a showText("",0) to remove whatever may be on the screen before displaying the following.
Additionally i added the black background option to the modals.
[requests.webm](https://github.com/user-attachments/assets/1c28097f-b86f-4e55-bae6-acc621fc4dd5)
_saturation of requests_
[Screencast …
=> [BUG][UI/UX] Correction of errors when ``` Save & Quit``` and ``` Log out```

src/data/move.ts
Sky Drop will be marked with "(P)".
The move is not fully implemented.
Added `.partial()` to Sky Drop's definition.
=> [Move] Mark Sky Drop as partial due to missing effects

src/modifier/modifier.ts, src/test/utils/gameManager.ts, src/test/utils/gameWrapper.ts, src/test/utils/mocks/mockClock.ts
N/A
Improve speed and reliability of tests.
Tests will complete more quickly now.
Tests that give enemy Pokémon held items will not randomly fail because the enemy was given a randomly generated item.
`npm run test`
=> [Test] Speed up tests and make enemy item override remove existing items

src/data/pokemon-forms.ts, src/data/pokemon-species.ts, src/test/moves/relic_song.test.ts
Players can now choose between Meloetta's different forms on the starter select screen.
Additionally, Meloetta will not change forms during a mono-type challenge when using Relic Song nor automatically revert to Aria form on arena reset.
Marked the second form as selectable in `pokemon-species.ts`.
Created `MeloettaFormChangePostMoveTrigger` which extends `SpeciesFormChangePostMoveTrigger` and adds a check for whether a mono-type challenge is currently active.
Removed `SpeciesFormChangeActiveTrigger(false)` which caused Meloetta to revert to Aria form automatically.
Go to the starter select screen and try to change Meloetta's form.
=> [Misc] Allow Meloetta's starting form to be selected

src/ui/starter-select-ui-handler.ts
No more crash when trying to create a new run
Fixes #4208 
At some point in the past the starter UI would register -1 as a preference for a starter's variant if shiny was turned off, which my changes in #3870 did not take properly into account. As a result if someone had such a preference set the game would crash when trying to open the UI and assign that -1 variant to the starter
Updated `initStarterPrefs` to delete the variant preference if its value is -1, as it's just a result of past implementation that is no longer relevant
Before: black screen and crash
After: able to create a new game 
- Load a save with shiny Paldean Tauros unlocked
- Open your dev tools and in Storage > Local Storage, replace the `starterPrefs_Guest` with the contents of  [this …
=> [Bug] fix starter select crash when a variant preference is incorrect

src/data/trainer-config.ts
Gameplay
* Genesect will always be in one of its drive forms in Ghetsis2
* Lusamine2 now leads with Nihilego, Pheromosa now boss
* Swapped Archaludon and Melmetal in Rose2
Aesthetics
* Fixed Wallace's Mega Swampert name
* Made consistent rules for evil team boss Pokemon pokeballs
* * Boss or sublegendary or mythical -> Ultra
* * UB -> Rogue
* * Cover legendary -> Master
Balance changes requested by Blitzy while I was here fixing a P3 bug
Added some more documentation
Mega Swampert name fixed
Barely missed the screenshot even on 1x but it was a rogue ball
Override to a specific wave after setting it in `battle.ts`
```ts
[189]: new FixedBattleConfig().setBattleType(BattleType.TRAINER)
.setGetTrainerFunc(scene => new Trainer(scene, TrainerType.LUSAMINE_2, TrainerVariant.DEFAULT)),
```
=> [Balance] Tweak evil boss teams, fix aesthetic details

src/ui/run-info-ui-handler.ts, src/ui/text.ts
If the user was using legacy UI mode, the 'Victory' text would be white, and as a result, it would blend in with the white background and be impossible to see. This fixes that. 
My feature, my mistake. 
The text style was changed from TextStyle.SUMMARY to TextStyle.PERFECT_IV
Use Legacy UI mode and view a victorious run in Run History
=> [P3] Run Result 'Victory!' Text not displaying correctly in Legacy UI Mode

src/data/battle-anims.ts, src/data/battler-tags.ts, src/phases/faint-phase.ts, src/test/battlerTags/substitute.test.ts
This fixes the following bugs that were introduced with Substitute's release onto beta:
- Sprite pipeline effects (including shiny variants) on the target are ignored during move animations where the target has a substitute.
- When a Pokemon faints while it has a substitute, its position isn't reset correctly.
- Non-damaging trap effects (e.g. Spirit Shackle) are incorrectly removed when the afflicted Pokemon puts in a substitute.
Reported in the Discord: https://discord.com/channels/1125469663833370665/1284249564429160549
- `data/battle-anims`: Fixed a check to apply pipeline effects using an incorrect condition
- `phases/faint-phase`: The fainted Pokemon's battler tags now lapse *after* the faint animation plays and the Pokemon's sprite is reset (while invisible).
- `data/battler-tags`: …
=> [Bug][Beta] Fix bugs from Substitute implementation

src/field/pokemon.ts, src/test/enemy_command.test.ts
Enemies will no longer include moves that are known to fail (e.g. Last Resort before the enemy's other move's are used) in the KO filter when selecting a move.
Enemies spam failing moves too much after #3975 
- `field/pokemon`: The filter for KO moves in `EnemyPokemon` now filters out moves that are known to not meet their conditions. The added logic is identical to a similar check during the move scoring process.
- `test/enemy_command.test`: New test checking that Last Resort is never used when it would fail.
Before the included changes (both Last Resort and Giga Impact KO if they successfully hit):
After the included changes:
`npm run test enemy_command`
=> [Misc][AI] Fix KO filter not accounting for move conditions

src/data/mystery-encounters/encounters/lost-at-sea-encounter.ts, src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts, src/data/mystery-encounters/utils/encounter-phase-utils.ts, src/data/trainer-config.ts, src/test/mystery-encounter/encounters/lost-at-sea-encounter.test.ts
- Winstrate Names are localized
- Titles of "myster challenger" named trainers are capitalized correctly
- SURF and FLY Moves are correctly localized in the lost at sea ME
- They were errors/not working as intended
- I basically invoked i18next at 3 points in the code where it wasnt done
- new function "setLocalizedName" to give named trainers that dont use a "initFor" method a way to have a localized name
- TODO (Will do right after writiing this)
- Lost at Sea BEFORE: 
- Lost at Sea AFTER:
- Winstrates BEFORE:
- Winstrates AFTER:
- Named Trainer Title Mystery Challenger BEFORE: 
- Named Trainer Title Mystery Challenger  AFTER:
Thats the tricky part...You basically need the localization files to test it...
So merge https://github.com/pagefaultgames/pokerogue/pull/4183 locally. And test …
=> [BUG] Fix a couple of bugs regarding MEs and their localization

src/field/pokemon.ts
This fixes a bug where if a Pokemon switches out in a double battle, its info flyout will sometimes appear partially off-screen after switching back in.
This was reported in the Discord. Some screenshots of the bug's effects:
The [Substitute PR](#2559 ) introduced `Pokemon#resetSprite`, a function called in `Pokemon#leaveField` to revert changes to the Pokemon's appearance after using Substitute or applying other effects. Before the changes from this PR, `resetSprite` also "centered" the Pokemon with `setFieldPosition`, which changes the appearance and position of the Pokemon's info flyout. However, the repositioning interfered with the call to hide the info flyout in `leaveField`, potentially because the position was adjusted based on its current position during the `hideInfo` tween …
=> [Bug][Beta] Fix Pokemon info flyouts being offset after switching out from a double battle

src/field/pokemon.ts
The message "A critical hit!" now correctly appears after damage is dealt.
fixes #4251 
`field/pokemon`: The critical hit message generated in `Pokemon#apply` now occurs after the call to `Pokemon.damageAndUpdate` instead of before.
https://github.com/user-attachments/assets/0fa76d87-0d00-4279-b40d-e1c4d058cc1a
1. Give your Pokemon Flower Trick with `MOVESET_OVERRIDE` in `src/overrides.ts`
2. Use Flower Trick
3. The critical hit message should happen after damage animations
=> [Bug][Beta] Fix "Critical Hit" message appearing before dealing damage

src/data/pokemon-species.ts, src/ui/starter-select-ui-handler.ts
Changed the Pokerus starter count from 3 -> 5
3 was too low. Heavily requested to up the count and wanted to start testing, minor change.
Only other change I'd make but cannot do myself is filter so they're all from a different generation, but that can come another time.
Merge to local or play on the beta.
=> [Balance] Pokerus Starter Count 3 -> 5, made pokerus count a constant as to only require one line change

src/data/move.ts, src/test/arena/grassy_terrain.test.ts
* Grassy Terrain halves the power of Earthquake, Magnitude, and Bulldoze like it does in the mainline games.
* This feature was never implemented
* Makes Grassy Terrain more unique
* https://github.com/pagefaultgames/pokerogue/issues/4238
* Added `.attr(MovePowerMultiplierAttr, (user, target, move) => user.scene.arena.getTerrainType() === TerrainType.GRASSY ? 0.5 : 1)` to the three moves
* Fixed some formatting in grassy glide
n/a
Override and test
=> [Refactor] Refactor code for Grassy Terrain halving the power of Earthquake, Magnitude, and Bulldoze

src/system/version-converter.ts
Remaking #4257 with main target to make it a hotfix instead
- For any users who could not load into the game due to an error (Cannot read properties of null) within `applySystemDataPatches`, they should be able to now.
- `Dire Hit` will now be converter properly
- Users were essentially blocked from being able to enter the game due to an null access, forcing them into the "Failed to load system data" screen.
- `Dire Hit` had changed its class and fundamental `ModifierType` when it got decoupled from `TempBattleStat`s and was not properly converted from old saves until now.
- Added more `undefined`/`null` guards to prevent trying to access fields in objects that weren't initialized yet during the save migration process.
- Added an `if-else` block wrapping the conversion done for …
=> [Hotfix] Fix Dire Hit & System Data Conversion Failure

src/data/move.ts, src/test/arena/grassy_terrain.test.ts
Fixing a missed condition in https://github.com/pagefaultgames/pokerogue/pull/4263
I was informed the damage penalty does not apply if the opponent is not grounded or semi-invulnerable
the grounded tag checks for semi invulnerability
n/a
override and test
=> [Move][Beta] Add back grounded condition to ground shaky moves and grassy terrain

src/data/pokemon-forms.ts
Rayquaza no longer requires Dragon Ascent to Mega Evolve
Normally in mainline Pokemon, Rayquaza does not have a mega stone and instead Mega Evolves through knowing the move Dragon Ascent. However in Pokerogue we do have a Rayquazite, but Rayquaza is still forced to know Dragon Ascent to keep the form change despite requiring two rogue tier items. This limits playstyles and options especially in PokeRogue, as the restriction in mainline is mainly due to Rayquaza being allowed an item slot while the other Megas / Primals are forced into holding their respective stones. That restriction is completely nonexistent in PokeRogue however, since Megas / Primals can hold items other than their Mega Stone here. This was also a requested change in the balance feedback threads. 
Change Rayquaza's Mega …
=> [Balance] Remove Dragon Ascent Requirement for Mega Rayquaza

vite.config.ts
- Should be no visible changes to the end user.
- Simplifies the build process for the offline app so it no longer needs github to modify the index.html prior to packaging.
- Simplify the build process for offline
- Get it closer to online state by eliminating modifications needed
- Being explicit for relative paths for vite configuration.
N/A
Build the package & run it
=> [QoL] Being explicit in vite configuration for relative paths

src/overrides.ts, src/tutorial.ts, src/ui/awaitable-ui-handler.ts, src/ui/battle-message-ui-handler.ts, src/ui/egg-gacha-ui-handler.ts, src/ui/evolution-scene-handler.ts, src/ui/menu-ui-handler.ts, src/ui/message-ui-handler.ts, src/ui/starter-select-ui-handler.ts
- All tutorials now have an animated cursor icon to show that player input is needed
- All tutorials now have an overlay that dims the UI to make the tutorial stand out (*)
- It's no longer possible to open or close the main menu during tutorials
(*) except the shop one, because that tutorial is a bit buggy and fixing it seems like it would require a good amount of refactoring that I'll leave for a future PR
A good number of new players make bug reports about not being able to use the menu because they don't see the tutorial or understand that the text needs to be skipped
This PR addresses this issue while also making the overall feel of text messages more consistent across the game thanks to the cursor icon
Until now it was also possible to open the menu while tutorial text was …
=> [QoL] [ui] Make tutorials harder to miss

public/battle-anims/clanging-scales.json
Player pokemon will no longer be offset in position while the opponent uses Clanging Scales. 
Report:
https://discord.com/channels/1125469663833370665/1285201636410654721/1285201636410654721
on file `clanging-scales.json` :
set `"focus": 1` on every object where `"target": 1`
Linking this PR:  [[Bug] Fix Roar & Dragon Tail making enemy sprite disappear #3927](https://github.com/pagefaultgames/pokerogue/pull/3927) 
It is possible that position errors on other move animations have appeared since that change, however it simply means the affected move animations were already set up incorrectly.
https://github.com/user-attachments/assets/b7fafe1f-721b-4304-8c5b-ebd3e419ac31
MOVESET_OVERRIDE: = [Moves.CLANGING_SCALES]
OPP_MOVESET_OVERRIDE: = [Moves.CLANGING_SCALES]
optional: …
=> [Bug]Fix 'Clanging Scales' moving player pokemon out of frame

index.css
Auto center the window vertically when the game is played in landscape format or in portrait format when touch controls are not displayed
It was a request, and an old PR closed in advance in favor of this one (See #1114) (cc @torranx)
CSS modification to achieve alignment without having to tweak any config in the game code directly
> Before
> After
Launch from a mobile or using an adaptive browser view
=> [QoL] Auto center the window vertically

src/data/move.ts, src/field/pokemon.ts, src/test/moves/shell_side_arm.test.ts
[Shell Side Arm](https://bulbapedia.bulbagarden.net/wiki/Shell_Side_Arm_(move))'s variable move category effect now forecasts each category's effectiveness based on base damage instead of just comparing the user and target's stats.
**Note:** Shell Side Arm is still partially implemented after this change because the physical version of the move currently doesn't make contact.
Some stuff I did with simulated damage calcs (#3975 ) made this fairly easy.
- `field/pokemon`: Added a new function `getBaseDamage` for calculating a move's base damage. This is used in `Pokemon#getAttackDamage` and Shell Side Arm's new forecasting logic.
- `data/move`: Updated Shell Side Arm's variable category attribute to make forecasts on the move's base damage as both a physical and special attack with the help …
=> [Move] Improved damage forecasting for Shell Side Arm

src/data/move.ts, src/field/pokemon.ts, src/phases/move-effect-phase.ts
None
Had a 🧀 🧠 moment and requested `HitsTagAttr` to be renamed in #4297 when that was incorrect
* Renamed the tag back to `HitsTagAttr`
* Created a new class `HitsTagForDoubleDamageAttr` that inherits from `HitsTagAttr` but has the doubleDamage flag set to true
n/a
Pull and test
=> [Refactor] Renamed the HitsTagAttr back to how it was

src/ui/title-ui-handler.ts
Won't see any more `NaN battles won`
Using `battleCount` from stats instead of `battlesWon`
it's tricky. You have to launch the server.
I would just trust me and check it on beta
=> [BETA][P3] Fix `NaN battles won`

src/field/pokemon.ts, src/ui/battle-info.ts, src/ui/pokemon-info-container.ts
Makes the caught pokemon-info-container ability highlighting work off the same logic as the tinted ball ability check
This was never merged
Created the `checkIfPlayerHasAbilityOfStarter` helper function that is called in both the tinted ball logic as well as the newly caught pokemon logic
n/a
Pull and test
=> [P3 Bug] Update pokemon-info-container ability highlighting to match tinted ball ability check

src/test/mystery-encounter/encounters/the-pokemon-salesman-encounter.test.ts
The expects didn't account for the possible shiny, which appends a `_shiny` to some dialogue tokens. I've added regexes to account for that possibility
<sub>I've also applied a tiny bit of refactoring</sub>
Run those 2 tests as many times as you can.  
E.g. by replacing `it` with `it.each(Array.from({length: 100}))` which will run the test 100 times (in parallel)
=> [Mystery-Encounter][Tests] Fix `The Pokemon Salesman` tests

src/test/mystery-encounter/encounters/teleporting-hijinks-encounter.test.ts
set enemy passive ability by default to `Ball Fetch` to prevent random passive abilities that raise stats too
Run the tests as many times as you can.
=> [Mystery-Encounter][Tests] fix Teleporting Hijinks tests

src/data/mystery-encounters/encounters/berries-abound-encounter.ts, src/test/mystery-encounter/encounters/berries-abound-encounter.test.ts
The "should reward the player with X berries based on wave" test was failing due to berry max stacks and the party only having 1 pokemone. Increased it to 3 to reduce that probability
=> [Mystery-Encounter][Tests] Make berries abound test more robust

src/field/pokemon.ts, src/test/boss-pokemon.test.ts
no more unwarranted stat boost
Currently a boss Pokemon resisting one shot with sturdy or endure gives it a stat boost as if an extra shield was broken - [See original bug report on discord](https://discord.com/channels/1125469663833370665/1285906331299086420)
- The loop going through boss segments looped one time too many allowing bossSegmentIndex to go down to -1, giving an extra boost. Typically Pokemon die when this happens so the issue was never noticed until now. Anyway, it now properly stops the loop
- added test for this specific case
(the videos are both using endure tokens but the boss having sturdy produces the same results since it's an issue with the boss code, and not sturdy or endure tokens)
Before:
https://github.com/user-attachments/assets/bb2602bf-2eac-48e9-bbf3-555d0776a …
=> [Bug] Fix sturdy and endure causing an extra stat boost to boss Pokemon

create-test-boilerplate.js, src/test/abilities/quick_draw.test.ts, src/test/battlerTags/octolock.test.ts, src/test/battlerTags/stockpiling.test.ts, src/test/boss-pokemon.test.ts, src/test/moves/haze.test.ts, src/test/moves/octolock.test.ts, src/test/moves/spit_up.test.ts, src/test/moves/stockpile.test.ts, src/test/moves/swallow.test.ts
- The `create-test` script now has a 4th type option called `Mystery Encounter`
- Removed some leftover manual `timeout` definitions
```
npm run create-test
```
=> [Qol][Tests] Add "Mystery Encounter" type for `create-test` script + minor timeout fixes

src/field/trainer.ts
Users will no longer have to fight trainers with repeated Pokemon. The game will try to supply unique party members instead. 
Quid-pro-quo
Can't prove definitely that no repeats will occur, but ran through Wave 112 multiple times. 
Console Output: 
Enemy Parties (Wave 112):
A new function was created 'checkDuplicateSpecies' that checks if the Pokemon Species passed is already found in the party. If it is, it prompts the genNewPartyMemberSpecies to reroll again. An infinite loop is already prevented in the code as the game allows up to 10 retries before settling with the Pokemon chosen. 
Choose any trainer that lacks fixed party members. Would recommend Wave 112.
Evil team leaders and the rivals are not a good choice b/c the all/majority of their party is set in stone.
=> [Bug] Preventing Duplicate Species in Trainer Battles

src/data/mystery-encounters/encounters/global-trade-system-encounter.ts, src/test/mystery-encounter/encounters/global-trade-system-encounter.test.ts
The game no longer freezes while trying to generate trade options for an extreme-BST non-legendary Pokemon (e.g., Mega Gyarados) for the GTS encounter.
Fixes https://discord.com/channels/1125469663833370665/1286967624885993473.
When widening the allowed BST range for a trade option, the BST range no longer gets reset, so an infinite loop no longer occurs.
Also added a test for this bug.
https://github.com/user-attachments/assets/90465016-6ad7-4e70-a85a-f4198ce5197f
https://github.com/user-attachments/assets/5b877dc2-80cd-44d2-a250-1cc7b5be1089
1. Import the following session file (it is from the second file in the Discord, played until wave 161).
[20240921 Wave 162 Crash.prsv.txt](https://github.com/user-attachments/files/17084800/20240921.Wave.162.Crash.prsv.txt)
2. Advance to wave 162. …
=> [Bug] [Beta] Fix game freeze from GTS infinite loop

src/modifier/modifier-type.ts
- Lures no longer show up as rewards if you have a lure of the same type and 60% or more of its duration left
- For example, green lures won't spawn if you have a green lure active with a remaining wave count of 6 or more. Once it hits 5 waves remaining, greens will show up again.
- Super Lures will show up with 8 or less waves remaining, and Max Lures with 17 or less.
- Since same-type Lure stacking is dead, it doesn't make sense to get spammed with lures to top off the one you got 3 waves ago
- Adds a new lureWeightFunc to modifier-types.ts
- This is used for all 3 lure types
With change:
Same wave but without change:
- In modifier-types.ts, line 1629, change the 2 to a 20, increasing the weight of green lures 10x
- Pick up a green lure and notice it doesn't spawn more until you hit 5 …
=> [Balance] Don't spawn lures if that lure still has 60% or more of its duration left

src/data/trainer-config.ts
Some Pokemon appear more frequently in grunt pools, reverted Rose change since it was too powerful in practice. Guzma's team has received buffs as he was regarded as one of the lackluster Evil Team leaders in terms of difficulty. Though I'd wager the changes are nothing too major.
Rose's buff was too strong, he is already regarded as one of the more "difficult" bosses so it was a simple revert. Guzma was really lacking in his fight, so I made his Pinsir a boss and put it in the STRONGER template to hopefully give it an edge up in the fight. Grunt pools were minorly adjusted just to make certain Pokemon they use in mainline appear more frequently 
- Removed Bergmite from Team Flare Grunt / Admin pools as it felt unfitting with their theme. (Hisui Avalugg was deliberately kept in the rare …
=> [Balance] Further Minor Adjustments to Evil Teams

src/data/challenge.ts
Reverts pagefaultgames/pokerogue#4355 
1. Evil teams are not necessarily lining up properly https://discord.com/channels/1125469663833370665/1229525892624154684/1287836831597072398
2. End of round rewards from certain floors like 165 do not match the changes to classic
=> [Beta] Revert "[Enhancement] Set appropriate evil team on monogen challenges"

src/loading-scene.ts, src/ui/run-info-ui-handler.ts
Removes ~5 MB of image data (not counting actual heap usage) from being loaded on every session load. These images are already loaded on demand when trainers are spawned, there is no need to keep all of these assets loaded for every session.
https://github.com/user-attachments/assets/bcc05970-703f-4062-a205-55375ae9504e
https://github.com/user-attachments/assets/0b9c7509-2cc4-44fc-a130-a0b1fee7ebc4
https://github.com/user-attachments/assets/4bc9c14d-b30e-4bc8-ac14-c8811b491897
=> [Enhancement] Remove unnecessary loading of trainer sprites in loading scene

src/test/abilities/arena_trap.test.ts, src/test/abilities/illuminate.test.ts, src/test/abilities/no_guard.test.ts, src/test/moves/chilly_reception.test.ts, src/test/moves/heal_block.test.ts
some more sneaked in after changing the default-timeout to 20s. Possibly older PRs.
remove references of setting manual test timeouts
```
npm run test:silent
```
=> [Refactor][Tests] Remove manual test timeouts

src/locales/en/battler-tags.json
Autotomize user will now display name properly
Typo caused name to not display properly
`pokemonNameWIthAffix` -> `pokemonNameWithAffix`
n/a
n/a
=> [Beta][P3 Bug] Fix typo in autotomize add message

src/data/status-effect.ts, src/locales/de/status-effect.json, src/locales/en/status-effect.json, src/locales/es/status-effect.json, src/locales/fr/status-effect.json, src/locales/it/status-effect.json, src/locales/ja/status-effect.json, src/locales/ko/status-effect.json, src/locales/pt_BR/status-effect.json, src/locales/zh_CN/status-effect.json, src/locales/zh_TW/status-effect.json, src/overrides.ts, src/test/localization/status-effect.test.ts
Found this inconvenience for translators with @CodeTappert 
None
Currently there is the necessity in translation of a few empty keys. 
Quite inconvenient and useless. Reason for that is to handle the theoretical situation of `statusEffect:none.<obtain | heal etc.>` <sub>Which realistically never occurs afaik</sub>
1. All `getStatusEffect<...>Text()` methods now check for `StatusEffect.NONE` to simply return an empty-string `""`
2. Removed all those (now) obsolete keys from `status-effect.json` file/s
3. Fixed the tests *(Which ironically will be removed in i18n-lazy-load anyway)*
You can't really. Just set a status and remove it again and see if something odd happens.
```ts
OPP_MOVESET_OVERRIDE: Moves.THUNDER_WAVE,
MOVESET_OVERRIDE: [Moves.REFRESH]
} satisfies …
```
=> [Refactor][Localization] Better handling for `StatusEffect.NONE` with i18n

src/modifier/modifier-type.ts
Eviolite will no longer be offered if the player's only unevolved Pokémon are GMaxed (it has no effect on them).
The spawn weighting change was missed in the Eviolite re-balance PR.
Added `!p.isMax()` check to Eviolite spawn condition. Also added some linebreaks to overly long lines for readability.
Set Eviolite weight to be something like 1000 and reroll a bunch with a GMax Pikachu/Eevee.
=> [Bug] Eviolite no longer spawns for GMax pokemon

src/locales/ko/battle.json
See right item name when user's item stack is full.
Only Korean had wrong parameter case.
change param name -> itemname to itemName
Before
After
Manually. (I tested with ME trash-to-treasure, running 2 waves.)
```Typescript
readonly MYSTERY_ENCOUNTER_RATE_OVERRIDE: number | null = 256;
readonly MYSTERY_ENCOUNTER_TIER_OVERRIDE: MysteryEncounterTier | null = null;
readonly MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType | null = MysteryEncounterType.TRASH_TO_TREASURE;
```
=> [Localization] fix wrong parameter key (itemname -> itemName)

src/locales/ko/modifier-type.json
A minor fix for Korean translation
Currently, it marks as "1 스테이지단계" or "30%단계", but in Korean "단계" means "stage" and "스테이지" is a direct transliteration for the word "stage". So I erased the word "단계".
Just a minor translation fix
=> [Localization] A minor translation fix for Korean locales

src/data/arena-tag.ts, src/data/battler-tags.ts
Torment will stick on the target.
My bug, my mistake.
The lapse condition for Torment should return True if the Pokemon is active on the field, and false if the Pokemon was not active on the field. 
Small typo in Imprison documentation corrected. 
Use torment.
=> [Bug][Beta] Torment Lapse Condition Fix

src/data/move.ts, src/test/moves/substitute.test.ts
This fixes a bug where Sappy Seed incorrectly applies its secondary effect when the target has put in a Substitute.
Reported [in the Discord](https://discord.com/channels/1125469663833370665/1284249564429160549)
- `data/move`: The "seeded" effect now has its own move attribute extending `AddBattlerTagAttr`. It now checks that the move does not hit its target's substitute before adding the tag.
- `test/moves/substitute.test`: New integration test for Sappy Seed hitting into a player Pokemon's substitute.
`npm run test substitute`
=> [P2][Beta] Fix Sappy Seed applying its secondary effect against targets with Substitute

src/ui/egg-list-ui-handler.ts, src/ui/egg-summary-ui-handler.ts, src/ui/hatched-pokemon-container.ts, src/ui/scroll-bar.ts, src/ui/scrollable-grid-handler.ts
- cursor wrap around in Egg List and Egg Summary 
- Egg List and Egg Summary can go past 99 and will have a scrollbar and allow scrolling if so
- Removed egg rarity background in egg summary
With the addition of MEs, some of them give specific eggs as a reward which makes it possible that a player holds more than 99 eggs at the same time.
This PR makes sure the UI still works nicely in this case
The egg rarity background removal in egg summary was discussed and agreed upon a while ago as it is confusing and does not give much useful information, this was a good opportunity to do it
- Created `ScrollableGridUiHandler` class that can handle all cursor update calculations for scrollable grids or lists in the game (other grids in the game will get updated to use this in a future PR)
- For Egg …
=> [UI] Make Egg List and Egg Summary scrollable

src/data/pokemon-species.ts
- Trainers at and above wave 80, except Breeders, will have guaranteed fully evolved mons
- In #4190 I removed a temporary hardcoded 100% chance for trainer mons to be evolved at/above floor 80. I removed it so the change in that PR could be tested as an alternative.
- The underlying issues behind evolution delays are still there, so this led to stuff like Burgh on floor 80 having Karrablast (who has very long evo delay)
- Re-added the previously removed bit that hardcoded mons to evolve by floor 80
=> [Balance] Reinstate temporary evolution delay fix

src/data/challenge.ts
Meloetta can't be sent out into battle if it's the wrong type/form for the current mono-type challenge. Also, wrong type/form Meloetta can't be added to the party in the starter select screen.
The behavior is incorrect.
Meloetta is removed from the static `TYPE_OVERRIDES` array in `SingleTypeChallenge` due to its form change behavior being changed as per #4192. This prevents it from being sent into battle if its in the wrong form for the current mono-type challenge.
Added a static `SPECIES_OVERRIDE` array in `SingleTypeChallenge` which is checked to prevent a Pokémon of the incorrect form/type from being added to the party during starter select. Currently only Meloetta is in the array, pending a rework in the next beta cycle.
<details>
<summary>Incorrect form can't be added to …
=> [Bug][Beta] Fix Meloetta-related bugs in mono-type challenges

src/field/pokemon.ts, src/modifier/modifier.ts
Macho brace won't constantly damage the user's pokemon at the start of every battle.
Macho brace was improperly implemented so wasn't increasing stats correctly.
Macho brace now increases stats during stat calculation, instead of after the fact.
Can't really screenshot this as it'd just show pokemon at full HP.
Give you starter macho brace via overrides, notice its max HP doesn't drop at the start of every wave.
=> [bug] Fix macho brace stat calculation

src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts
Game could crash if the player lost with queued enemy stat change phases leftover in the phase queue. Fixed with this change
https://github.com/user-attachments/assets/2b7f3acf-7229-46be-9c53-1445aac51c34
=> [Bug] hotfix for expert breeder ME

src/data/move.ts
Dragon Tail et al can no longer force bosses (like Eternatus) to flee.
The condition to prevent bosses from fleeing was forgotten when removing GMax immunities.
Added a `.isBoss()` check to `ForceSwitchOutAttr`.
Before fix:
Uploading boss flee bug.mp4…
After fix:
https://github.com/user-attachments/assets/7746e543-c5ac-443d-9ea1-90463484c08b
Give your Pokémon Dragon Tail/etc (and the enemy Splash) and start at wave 200, then use the move.
=> [Hotfix] Prevent bosses from being forced to flee by Dragon Tail/etc

src/phases/mystery-encounter-phases.ts
Fixes MEs that have "start of battle free moves" that the enemy performs (Uncommon Breed, Slumbering Snorlax, Fiery Fallout, etc.)
Instead of lapsing *all* turn end effects (this has severe phase consequences with certain tags), only lapse the ones that were originally intended to be lapsed (flinch, endure).
=> Me battle tag hotfix

src/data/move.ts
Dragon Tail/etc will no longer cause a Pokémon to be switched out if there are no valid switch-in Pokémon.
It's broken.
Added a party check in `ForceSwitchOutAttr`.
Before fix:
https://github.com/user-attachments/assets/b0b00478-473a-4822-891b-861b81556785
After fix:
https://github.com/user-attachments/assets/8a4ea264-a69e-4e09-8804-e424711a5e41
Use Dragon Tail on the last non-fainted Pokémon in a trainer battle (such as wave 5).
=> [Hotfix] Prevent the last valid Pokémon from being forced to switch

src/battle-scene.ts
Server is returning value of `0` for `mysteryEncounterType` on sessions that existed before the update (`0` is a valid ME, but an ME is not valid for the session state) which causes Mysterious Challengers to spawn on old saves.
This removes the early exit on the check for a ME so that it always must succeed on the roll to spawn a ME (which is seed offset, so refreshes/resets should never affect it).
This will *not* completely solve the fact that *if* a ME randomly determines to spawn on that first wave, it will be forced into Mysterious Challengers. There's not really any workaround to that.
=> [Bug] Prevent MEs incorrectly spawning on existing session saves

src/locales/fr/mystery-encounters/training-session-dialogue.json
Right wording in training-session-dialogue.json
The way the description of French **training-session-dialogue.json** was written may likely indicate the opposite of what is happening in reality
None
=> [Localization] [P3 Bug] French hotfix

src/phases/pokemon-heal-phase.ts
This fixes an issue where the game would sometimes softlock after a Pokemon under the effect of Heal Block KOs another Pokemon with a draining move (e.g. Bitter Blade) while at full HP.
P1 bugs are bad
`phases/pokemon-heal-phase`: `PokemonHealPhase.end` now returns when calling `super.end` if the associated healing effect is blocked by Heal Block. Before this change, it was possible for `super.end` to be called twice if the heal target was at full HP and affected by Heal Block, causing two phases to be queued up at the same time.
**Before the change** (courtesy of @PigeonBar )
https://github.com/user-attachments/assets/2c48543d-ddbb-44a0-b200-4c3e242c65c4
**After the change**
https://github.com/user-attachments/assets/83a69063-68b8-47fc-8707-a5f886a02b63
1. Download [this …
=> [Hotfix] Fix desync issue with Heal Block applying to Pokemon at full HP

src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
Fixes exit condition of loop for generating a species in Dark Deal.
Before, if the given starter tiers were 9/10, the while loop would be skipped because the condition of `(min !== 0 && max !== 10)` was not met (`max === 10`).
=> [Bug] Change early exit on Dark Deal species calc

src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
The GTS ME will no longer crash if you try to trade a Pokémon with many forms like "Unown ?".
It's crashing the game.
`tradePokemon.species.forms[pokemon.formIndex].formName` changed to `tradePokemon.species.forms[tradePokemon.formIndex].formName`.
Before fix:
https://github.com/user-attachments/assets/d134ce00-cc98-4c69-80fd-dba33a659ee2
After fix:
https://github.com/user-attachments/assets/a18b4321-6bab-4529-a743-7f4dbabc435b
Load this save file and try to trade the Unown: https://cdn.discordapp.com/attachments/1289762905905958984/1289797958807588915/20240928_GTS_Unown_Softlock.prsv?ex=66fa2174&is=66f8cff4&hm=8597bbd7da060e55c57b2965071ebd3acf06f0996934c8c618ce1f2653e1d792&
- ~[ ] If I have text, did I make it translatable and add a key in …
=> [Hotfix] Fix crash in GTS ME: replace `pokemon` with `tradePokemon`

src/ui/egg-summary-ui-handler.ts
The egg summary no longer fails to show the first Pokemon data
Messed up when making the egg summary scrollable (PR #4391)  so when viewing the egg summary several times in the same play session the details of the first Pokemon would not get updated until the cursor was moved to another Pokemon and back
Make sure cursor is reset correctly in clear() 
Before, first and second time seeing the egg summary in the same session:
After, seeing the egg summary for the second time of a session:
https://github.com/user-attachments/assets/5ba11a5c-b9ab-4fbc-975d-041565e38068
Use overrides and hatch eggs several times in the same session, making sure to leave the cursor in various spots when exiting.
When getting to the summary next the cursor should always be on the first Pokemon and its information …
=> [P3][UI] Fix egg summary not displaying first mon properly

src/data/move.ts
Zippy Zap is no longer erroneously boosted by Sheer Force
Reported [in the Discord](https://discord.com/channels/1125469663833370665/1289296539054903336)
`data/move`: Changed Zippy Zap's `chance` parameter from `100` to `-1`, meaning that Zippy Zap's crit-only effect always triggers but is no longer tied to effect chance (and therefore cannot be modified by Sheer Force)
Add the overrides below to `src/overrides.ts`.
```ts
ABILITY_OVERRIDE: Abilities.SHEER_FORCE,
MOVESET_OVERRIDE: Moves.ZIPPY_ZAP
```
Then use Zippy Zap in a battle. The move should critically hit, and Sheer Force should not activate on the attack
=> [P2] Fix Zippy Zap being boosted by Sheer Force

src/data/battler-tags.ts, src/data/move.ts, src/enums/battler-tag-type.ts, src/locales/en/battler-tags.json, src/test/moves/syrup_bomb.test.ts
Syrup Bomb will have its correct secondary effect of decreasing the afflicted Pokemon's speed once per turn for three turns. 
Shareholder value up!
New Battler Tag for Syrup Bomb
https://github.com/user-attachments/assets/830c0cf3-097d-4c4c-b1e1-e0eb6f4c8c85
Use Syrup Bomb on a Pokemon without Bulletproof.
=> [Moves] Fully Implement Syrup Bomb

src/battle-scene.ts
The game should not generate Pokemon with the same ID anymore
Currently it's possible that the game gives a wild Pokemon the same ID as one of the Pokemon that was brought into the run from starter select
- This leads to issues with the display of the enemy's items and used moves
- This leads to even bigger issues if the mon with duplicate ID is captured and used alongside its counterpart
Pokemon IDs are generated with the "Wave Seed", that is the run's seed shifted based on the current wave.
Currently the game's RNG is not reset properly after losing or winning a run. A new seed is generated when going back to the title screen, but the wave seed gets shifted based on the wave where the run finished. Let's call it wave X
So, when finishing a run and starting a new game immediately the …
=> [Bug] Fix duplicate mon ID / RNG not properly resetting after game over

src/data/ability.ts
This removes the "(P)" marker on Super Luck.
Super Luck was previously marked as a partial implementation because it did not implement the ability's out-of-battle effect from Generation VIII. That effect's implementation (#1624) has since been rejected by the Balance Team for not being practically translatable to this game, leaving no reason for Super Luck to keep the "(P)" marking.
`data/ability`: Removed Super Luck's `.partial()` marking.
See Super Luck's summary description in game. It shouldn't be marked (P) anymore.
=> [Ability] Remove `partial` marker on Super Luck

src/battle.ts
Aether Foundation, Team Skull, Macro Cosmos, and Team Star grunts now have the possibility of generating as a double battle.
They were overlooked when initially added in their respective pull requests.
Simply adding their TrainerType entries to the `evilTeamGrunts` const so they can appear as double battles properly. The relevant locale entries have already been previously added, so nothing new is needed there.
Override the wave to one of the evil team grunt waves to see if you get a double battle.
=> [Balance/Enhancement] Gen 7+ grunts can now be in double battles

src/data/arena-tag.ts, src/data/move.ts, src/enums/arena-tag-type.ts, src/field/pokemon.ts, src/locales/de/arena-tag.json, src/locales/en/arena-tag.json, src/locales/es/arena-tag.json, src/locales/fr/arena-tag.json, src/locales/it/arena-tag.json, src/locales/ja/arena-tag.json, src/locales/ko/arena-tag.json, src/locales/pt_BR/arena-tag.json, src/locales/zh_CN/arena-tag.json, src/locales/zh_TW/arena-tag.json, src/test/moves/plasma_fists.test.ts, src/test/utils/gameManager.ts
This implements the secondary effect of [Plasma Fists](https://bulbapedia.bulbagarden.net/wiki/Plasma_Fists_(move)), which converts all Normal-type moves to Electric type for the rest of the turn.
Less (P)
- `data/arena-tag`: New `PlasmaFistsTag` converts Normal type to Electric type. It is always applied to both sides of the field.
- `data/move`: Added attribute to Plasma Fists that adds a `PlasmaFistsTag` to the field. Plasma Fists is no longer marked with `.partial()`
- `field/pokemon`: `Pokemon.getMoveType` now applies Plasma Fists' field effect after all other type change effects are applied.
- `test/utils/gameManager`: Fixed a bug with `forceEnemyMove` where the function couldn't strictly force the enemy to target the first player Pokemon (`BattlerIndex.PLAYER`)
- …
=> [Move] Fully Implement Plasma Fists

src/data/move.ts
The AI might use Glaive Rush now.
The lack of AI scoring meant the AI would almost never use the move.
The double damage tag is set to `-5`, and the always get hit tag is set to `0`.
Give the enemy Glaive Rush (and other moves like Tackle etc) and check the console logs.
=> [Bug] Add scoring for the Glaive Rush `BattlerTag`s

src/locales/de/mystery-encounters/the-expert-pokemon-breeder-dialogue.json, src/locales/fr/mystery-encounters/the-expert-pokemon-breeder-dialogue.json, src/locales/ja/mystery-encounters/the-expert-pokemon-breeder-dialogue.json, src/locales/ko/mystery-encounters/the-expert-pokemon-breeder-dialogue.json, src/locales/pt_BR/mystery-encounters/the-expert-pokemon-breeder-dialogue.json
Removed **@[TOOLTIP_TITLE]{{{eggs}}}** into only **{{eggs}}** in many locales.
It prevented the Egg type given by the Expert Breeder to be displayed
To have the Egg type given by the Expert Breeder properly displayed
None
**Before**
**After**
=> [Localization] Expert Breeder ME - Egg bug in locales

src/data/trainer-config.ts
Elite 4 will improve very slightly in mon selection, Champions will now have a pool of way more competent Pokemon.
The current minimum BST filter for Champions being 470 was criminally low for an important trainer, who is meant to be a secondary boss to the rival who currently sits with a minimum 540 BST filter in their config. This meant you would see oddities like Champion Red with a Simisear or Wallace with a Leavanny which are extremely unfitting in terms of power. 508 was chosen as a sweet spot in BST that targets slightly more premium Pokemon while fitting in some that aren't at exactly 510 like the Drillbur or Sinistea line. Elite 4 got a +10 BST increase to not limit the pool _too_ much but still cutting out a few weaker tier Pokemon.
damo stepping in, I have a problem and typed …
=> [Balance] Increase Minimum BST Filter for Elite 4 / Champion Teams

src/data/move.ts, src/test/moves/chilly_reception.test.ts
Chilly Reception now works properly for enemy 'mons
Closes issue #4513 (originally from discord)
the move attributes `getCondition()` was trying to set the weather (via `trySetWeather()`) when checking the condition, (instead of just checking the weather)
- beta:
https://github.com/user-attachments/assets/2cdcdd97-b8b6-48f8-ad2c-4202c9a59780
- pr
https://github.com/user-attachments/assets/b133347f-38f5-48e4-a137-cf16ad47ac2f
showing checks for trainer battles too
https://github.com/user-attachments/assets/5556fc38-64eb-44e8-8d6b-1f84ff9e912c
set enemy pokemon moves in overrides
added some more enemy/trainer tests
=> [Bug] Chilly Reception's Snow is called during Enemy AI Move Selection

src/data/ability.ts, src/field/pokemon.ts, src/phases/move-effect-phase.ts, src/test/abilities/tera_shell.test.ts
Tera Shell now correctly reduces the effectiveness of all hits of multi-strike moves instead of just the first hit.
closes #4218 
- `field/pokemon`: Added new `moveEffectiveness` field to `turnData` which caches a move effectiveness value for the current move being used against the associated Pokemon. If not `null`, this value overrides the output of `Pokemon.getMoveEffectiveness(...)`. This field is currently only used for and modified by Tera Shell's effect.
- `data/ability`: Tera Shell now changes `pokemon.turnData.moveEffectiveness` to 0.5 when the ability applies.
- `phases/move-effect-phase`: now resets `target.turnData.moveEffectiveness` for all targets of the phase's move on the move's last strike.
- `test/abilities/tera_shell.test`: New test for Tera Shell covering all hits of a …
=> [P2][Move] Fix Tera Shell to apply to all hits of multi-strike moves

src/phases/weather-effect-phase.ts, src/test/arena/weather_hail.test.ts, src/test/arena/weather_sandstorm.test.ts
Weather damage gets rounded down like all damage in the game
This was missed in PR #3557 
* Use `Utils.toDmgValue` instead of `ceil`
* Updated tests for sandstorm and hail + added missing test for their arena effects (ignoring ability and move related tests as they should probably be tested with the related moves/abilities if they aren't already)
Before, taking sandstorm damage (1/16 max hp) while holding Leftovers (heals 1/16 max hp) could leave you with 1HP missing
https://github.com/user-attachments/assets/ac515813-05ce-403a-8132-b86b4c377d8b
After:
https://github.com/user-attachments/assets/4c144f1e-14d0-4ce2-9f28-cb3e90e338d3
Tests:
```
npm run test src/test/arena/weather_sandstorm.test.ts
npm run test src/test/arena/weather_hail.test.ts
```
Overrides for the scenario in the videos: …
=> [P2] Make weather damage round down for consistency

src/data/move.ts, src/test/moves/scale_shot.test.ts
- Implement Scale Shot
- Cool move
- Adds a `lastHitOnly` parameter to `StatStageChangeAttr` and uses it for Scale Shot
- Adds docstring for StatStageChangeAttr and its apply function
- Adds test for `scale_shot`
Triggers stat change after all hits
Doesn't trigger change multiple times even with Multi Lens
Per Bulbapedia: "Scale Shot is not considered to have additional effects for the purposes of Sheer Force."
- Use Scale Shot (for easy access: Roaring Moon memory mushroom or Dracozolt egg move)
- New test:
- `npm run test scale_shot`
- Tests that stat changes are done after the last hit
- Also tests that it's not boosted by Sheer Force and doesn't have its stat change effect removed by it
=> [Move] Implement Scale Shot

src/modifier/modifier.ts
Using rare candies won't crash the game anymore
I never wanted them to crash the game
`levelCount` `PokemonLevelIncrementModifier.apply()` now has a default value of `new NumberHolder(1)`
<sub> Apparently if multiple levels are increase the modifiers is simply applied `n` times. instead of putting the value into that  `levelCount`. But that's for another time to fix</sub>
https://github.com/user-attachments/assets/57679dbf-d9a2-4889-96c6-7d7f75729679
- Import this session: [sessionData1_bbclover.txt](https://github.com/user-attachments/files/17248329/sessionData1_bbclover.txt)
- Play that session and use the rare-candy
- **Yes and it's awfully complicated**
=> [Beta][P1] Fix rare/-er candy

src/data/pokemon-species.ts
Pokémon animation speeds will function normally after reloading a session that was saved when an enemy Pokémon was asleep.
Fixes #4465
Calling PokemonSpeciesForm.loadAssets will reset the framerate when previously nothing would be done if the sprite was already loaded.
Before:
https://github.com/user-attachments/assets/a1380c69-f779-4d9f-bd46-35985d3ddea7
After:
https://github.com/user-attachments/assets/823e126c-8a86-4991-a884-b6e360c5b882
- Import session using the session data [linked here](https://discord.com/channels/1125469663833370665/1285351284924485713/1289283674986254457)
- Use Spore
- Save + quit
- Load session again
- ~~[ ] If I have text, did I make it translatable and add a key in the English locale …
=> [P3] Fix persisting sleep animation when sprite is already loaded

src/phases/move-effect-phase.ts, src/test/moves/toxic.test.ts
Currently on beta, all Poison-type Pokemon ignore opposing semi-invulnerability due to a bug introduced by my PR #4445. This bug has not yet hit live servers. This PR fixes the issue so that only Toxic bypasses semi-invuln when used by Poison-types, which is the intended behavior.
I broke semi-invuln sorry but this should fix it. Thank you DerTapp, Snailman, and PigeonBar for noticing the bug that I caused and raising it to my attention so quickly on discord.
Previously my check for Toxic Accuracy attr was incorrect. What I intended to do was bypass semi-invuln if the move used has Toxic Accuracy attr and the user is Poison-type. But instead of checking if the move *has* a Toxic Accuracy attr, I got the array of all the move's attrs matching Toxic Accuracy attr. For all moves other than …
=> [Bug][Beta] Fix hit check so Poison-types do not brick semi-invuln.

README.md
- game-wise none
- gh-wise -> updated readme
- files under `docs` directory most esp `comments.md`, which is relevant for devs/contributors in documenting their code, are not well-known
- added a new section `### Documentation` which links the project's [auto-generated docs](https://pagefaultgames.github.io/pokerogue/main/index.html), `enemy-ai.md`, and `comments.md`
- linked `eslint.config.js` in `#### Linting`
=> [Misc] Update README.md to include relevant links

public/images/pokemon_icons_9v.json
Variant Farigiraf now use the correct icons for their tier.
Reported [here](https://discord.com/channels/1125469663833370665/1238339524778790922/1291624197432414230), Farigiraf was defaulting to its non-shiny icon instead.
No mechanical changes, simple data correction.
Spawn in a variant Farigiraf using overrides or evolve a Girafarig by teaching it Twin Beam.
~~- [ ] Have I considered writing automated tests for the issue?~~
~~- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~~
=> [Sprite] Fix variant Farigiraf icon names

src/data/ability.ts, src/test/abilities/ability_duplication.test.ts
If due to fusions you have the same ability as both passive and normal, it'll no longer stack with itself.
Damo asked.
Duplicate abilities don't stack.
This is difficult to test in game, you'd probably have to look at damage rolls or the like. Or just run the unit tests.
=> Make duplicate abilities not stack

create-test-boilerplate.js
N/A
The test creation script would create a test with linting errors due to the recent linting change.
Updated the test creation script to take into account the new linting changes.
Added some extra boilerplate code that is likely to be common across tests.
Updated the test creation prompt to be clearer that you need to enter the name of the move/etc and not the name of the file (since the filename will be derived automatically by the script).
`npm run create-test`
- ~[ ] Are all unit tests still passing? (`npm run test`)~
=> [Test] Update `create-test` script for linting changes

src/field/pokemon.ts
G-Max Pikachu, Eevee, Meowth, and Duraludon should no longer be incorrectly prompted or allowed to evolve.
Reported [on the Discord](https://discord.com/channels/1125469663833370665/1290042404757438494)
`field/pokemon`: `Pokemon#getEvolution` now uses `isNullOrUndefined(evo.preFormKey)` instead of `!evo.preFormKey` to check if an evolution isn't tied to a specific form. Using `!evo.preFormKey` caused issues because the keys for base forms are `""`,  which is also interpreted as falsy.
Easiest way using overrides:
1. Give yourself a Level 28 G-Max Meowth.
2. Clear a wave. Then, from the rewards screen, give your G-Max Meowth a Rare Candy.
3. The Meowth should not be prompted to evolve into a Persian.
=> [P2] Fix evolutions unable to strictly apply to base Pokemon forms

src/ui/modifier-select-ui-handler.ts
Having "Shop" as default cursor row should no longer crash the game in certain scenarios when loading into a shop with 0 items.
Game was crashing in weird edge cases
Resets cursor indexes when the Shop UI handler is cleared.
Before:
After (all row indexing behavior for other options remains the same as well):
Regression for Default Cursor Target "Rewards":
Regression for Default Cursor Target "Reroll":
Regression for Default Cursor Target "Check Team":
Original save for reproducing crash:
[20241002 ME Shop Crash.txt](https://github.com/user-attachments/files/17270313/20241002.ME.Shop.Crash.txt)
=> [P1] Fix Shop Cursor Indexing Crash

src/phases/move-phase.ts, src/test/moves/metal_burst.test.ts, src/test/utils/helpers/moveHelper.ts
Metal Burst will not crash if the target faints before the user moves.
Regression caused by #3974 
The code that accidentally got reverted is put back in, plus tests were added for Metal Burst.
For video example of the crash, see #4576 
`npm run test metal_burst`
=> [Beta][P1] Fix regression in Metal Burst caused by #3974

src/data/mystery-encounters/encounters/weird-dream-encounter.ts, src/test/mystery-encounter/encounters/weird-dream-encounter.test.ts
Incorrect content keys showing in prod because changes were merged in the locales repo before the code changes were deployed to production.
Current production content:
With fix:
=> hotfix content issue for Weird Dream ME

src/data/mystery-encounters/encounters/weird-dream-encounter.ts, src/test/mystery-encounter/encounters/weird-dream-encounter.test.ts
The bug that was reported was in beta, not production as originally thought. So now prod is actually broken.
Rollback changes from the hotfix (not undoing the commit so we don't have to force push)
=> Undo mistaken hotfix to Weird Dream ME

src/field/pokemon.ts, src/test/abilities/sheer_force.test.ts
Fixes #2707. Specifically, if two Pokemon have abilities that can be disabled by Sheer Force, and they attack each other using moves with secondary effects, then the game should no longer softlock.
The list of affected abilities is Color Change, Pickpocket, Wimp Out, Emergency Exit, Berserk, and Anger Shell.
Fixing a crash.
When checking whether a Pokemon has a certain ability, the game now checks whether the ability's ID matches before checking whether the ability is disabled. This way, if both sides have abilities that can be disabled by Sheer Force, then the game detects earlier that neither Pokemon has Sheer Force itself and then exits the recursion accordingly.
Also added a test.
<details>
<summary>Before the changes: Game softlocks (Berserk vs. Pickpocket)</summary> …
=> [P1 Bug] Fix infinite recursion from abilities disabled by Sheer Force

src/data/battler-tags.ts, src/test/moves/obstruct.test.ts
King's Shield/Silk Trap will no longer lower stats if a Pokemon with a protected stat makes contact with the protection. 
A bug a day... #4554 
Changed parameter.
Correct Interaction
https://github.com/user-attachments/assets/74604f42-8e4d-4882-8548-6757dadb8bdf
Normal Interaction
https://github.com/user-attachments/assets/a1617cca-9ed2-48e4-9097-b690465519f7
Use a Pokemon with a stat protection ability and have it attack a Pokemon using King's Shield or Silk Trap with a contact move.
=> [Bug] Obstruct/etc no longer reduce stats through Clear Body/etc

src/data/move.ts, src/test/abilities/battle_bond.test.ts
Base form Greninja will always properly use the base form Water Shuriken (with randomized 2-5 hits), even after transforming into Battle Bond form then returning to base form.
I was investigating reported inconsistencies on Wave 35 of the Oct. 2 daily run guide, and this bug turned out to be the root cause.
`MultiHitAttr` moves now rely on a new attribute `intrinsicMultiHitType` that never gets modified. This allows such moves to return to their original multiHitType when relevant abilities (such as Battle Bond) stop being applied.
Also added a test.
Footage explanation:
1. Wave 189: KO the opponent to enter Battle Bond form.
2. Wave 190: Use Water Shuriken once (this triggers the bug), then KO the opponent.
3. Biome transition: Greninja returns to base form.
4. Wave 191: Spam Water …
=> [Bug] Fix Battle Bond continuing to affect Water Shuriken after Greninja returns to base form

src/data/battler-tags.ts, src/test/moves/syrup_bomb.test.ts
When the Pokémon that used Syrup Bomb leaves the field, the end-of-turn speed lowering effect will no longer occur.
The current behavior is incorrect.
Added a check to `SyrupBombTag` to see if the source Pokémon is still on the field and remove the tag if it isn't.
`npm run test syrup_bomb`
=> [Bug] Syrup Bomb effect is removed when user leaves the field

src/enums/stat.ts
Lowering or raising a stat stage below -6 or beyond +6 will no longer display the wrong message ("X severely fell" or "X drastically rose").
#2699 had replaced the original `getBattleStatLevelChangeDescription`, which incorrectly translated `switch-case` to an `if-else` for the case where stat stages could no longer be lowered/raised. This caused the wrong stat stage change description to get pushed instead of the correct one.
Added `stages > 2` to the boolean that triggers the "X severely fell"/"X drastically rose" messages to prevent it from triggering in the case that `stages` is equal to 0, which indicates that a stat cannot be lowered or raised.
Refer to #4537 for a visual of the bug.
https://github.com/user-attachments/assets/2534e640-fe92-4fa5-9d1d-e8fa4eb0bb78
Use any stat stage …
=> [P3] Fix "Won't Go Any Lower/Higher" Not Appearing

src/battle-scene.ts, src/modifier/modifier.ts
N/A
Prevents some weirdness if you try to give the opponents a Tera Shard in a double battle
The function that removes held items from enemy Pokémon now takes an optional `pokemon` parameter that specifies which Pokémon to remove items from.
(Ignore the random Starf berry on the Roaring Moon, that's a different issue).
Set `OPP_HELD_ITEMS_OVERRIDE` to something and set `BATTLE_TYPE_OVERRIDE: "double"`.
=> [Misc] Enemy item override will now apply to all enemies

src/ui/starter-select-ui-handler.ts
Moving away from a Pokemon while the candy friendship tooltip is shown no longer causes issues
Any tooltip shown when exiting starter select now gets cleared
In start select if you move from a Pokemon detailed view to the filters or the start button, the Pokemon details are cleared. But if you do that while the candy friendship tooltip is shown, everything bugs out instead
- Check for undefined `lastSpecies` when updating the tooltip
- hide tooltips in `clear()`
Before:
https://github.com/user-attachments/assets/1c37933b-b9ef-48ba-bd29-af0474462c85
After:
https://github.com/user-attachments/assets/54f85581-6a6c-4bd5-bea4-1b3f0f3a5834
https://github.com/user-attachments/assets/c5699380-4f73-4016-a492-d672a953f5cb
Place your mouse over the candy icon on a starter and move around the UI in …
=> [P3][UI] Fix tooltip bugs in Starter Select screen

src/data/move.ts
Sheer Cold will no longer show a type hint of "falsex" against Ice-type Pokemon
Sheer Cold's code is old as hell but somehow worked with the new type effectiveness code, so I missed it earlier.
`data/move`: Sheer Cold's `IceNoEffectTypeAttr` no longer interprets the type effectiveness multiplier as a boolean, and now sets the type multiplier to 0 instead of `false`.
1. Use `src/overrides.ts` to give your Pokemon Sheer Cold and set the enemy species to an Ice-type.
2. Start a new game
3. Enable type hints
4. Sheer Cold's type hint should show as "0x" instead of "falsex"
=> [P3] Fix "falsex" type hint for Sheer Cold

src/test/moves/safeguard.test.ts, src/test/mystery-encounter/encounters/an-offer-you-cant-refuse-encounter.test.ts, src/test/mystery-encounter/encounters/berries-abound-encounter.test.ts, src/test/mystery-encounter/encounters/the-pokemon-salesman-encounter.test.ts
N/A
Fixing several known cases of flaky tests (https://discord.com/channels/1125469663833370665/1286833394277421148), which were each occasionally breaking for different reasons.
`an-offer-you-cant-refuse` - Added a proper override to give the ability Intimidate (This test could previously break due to Gyarados having its HA instead of Intimidate).
`pokemon-salesman` - Now checks whether specifically the final Pokemon in the party is the purchased Pokemon (This test could previously break if the purchased Pokemon happens to be the same species as one of the starting Pokemon).
`berries-abound` - For tests where the wild Pokemon is meant to outspeed the party, force the party's speed to be 1 (This test could previously break due to wild Shuckle getting outsped by the party. Truly a Shuckle …
=> [Test] Fix several flaky tests

src/data/move.ts
Certain moves will no longer show up as (P). These include: 
* Torment
* Trick Or Treat
* Forest's Curse
* Freeze Dry
* Sunsteel Strike
* Moongeist Beam
* Photon Geyser
* Stuff Cheeks
* ~~Upper Hand~~
Signature Z moves:
* Sinister Arrow Raid
* Malicious Moonsault
* Oceanic Operetta
* Stoked Sparksurfer
* Pulverizing Pancake
* 10 Million Volt Thunderbolt
* Let's Snuggle Forever
* Clangrous Soulblaze
(P) added to Roar and Whirlwind, Circle Throw and Dragon Tail
A lot of (P) range from no effects to missing a specific edge case. The listed moves above are marked P because they are either missing interactions with unimplemented features or super specific niche ones that are irrelevant and make players concerned about using a (P) move without any documentation.
**PLEASE LET ME KNOW IF ANY OF …
=> [Documentation] Document all (P) moves

src/data/ability.ts
Certain abilities will no longer show up as (P). These include:
* Shield dust
* Serene grace
* Sheer force
* Harvest
* Corrosion
* Wandering spirit
A lot of (P) range from no effects to missing a specific edge case. The listed abilities above are marked P because they are either missing interactions with unimplemented features or super specific niche ones that are irrelevant and make players concerned about using a (P) ability without any documentation. 
**PLEASE LET ME KNOW IF ANY OF THE DOCUMENTATION IS INCORRECT**
* Created a new `edgeCase` internal developer tag for abilities. 
* Documented all `.partial()`'s
n/a
Pull and test
=> [Documentation] Document all (P) abilities

src/field/pokemon.ts
Currently, a player Pokemon's substitute doll does not shift position with the source during transitions between battles of different types (single or double). This change fixes that.
My mistake with the Sub implementation; my fix to make. (Reported [in the Discord](https://discord.com/channels/1125469663833370665/1289496377067438192))
`data/pokemon`: `Pokemon#setFieldPosition` now also applies tweens and position changes to the Pokemon's Substitute Doll (if it has one).
**Before** (courtesy of @Snailman11)
https://github.com/user-attachments/assets/25bf2541-6cf2-4eef-b935-407f59be670a
**After**
https://github.com/user-attachments/assets/b0ab6977-6c2d-4947-b4d9-76e3deeee8ea
To replicate the above videos:
1. Download [Doublebattle.txt](https://github.com/user-attachments/files/17349328/Doub …
=> [P3][Move] Fix Substitute visual bugs on wave transition

src/data/move.ts, src/test/moves/dragon_tail.test.ts, src/test/moves/u_turn.test.ts
Fixes #4219: If a phazing attack KO's a Pokemon holding a reviver seed, it no longer causes a softlock due to the revived Pokemon being removed from the field.
Fixing a softlock.
`ForceSwitchOutAttr` now only removes a Pokemon from the field if it is not fainted.
- If the Pokemon has a reviver seed, it allows the Pokemon to remain on the field.
- Otherwise, if the Pokemon does not have a reviver seed, then it stays fainted, which then correctly forces its trainer to switch.
Also added a few tests.
**NOT FIXED**: If the user of Dragon Tail faints (e.g., due to Iron Barbs), it still forces the opponent to switch out, which is incorrect according to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Dragon_Tail_(move)). There seems to be a separate issue where `MoveEffectPhase` runs all …
=> [P1 Bug] Fix softlock when a phazing attack activates a reviver seed

src/phases/egg-lapse-phase.ts, src/phases/egg-summary-phase.ts, src/ui/abstact-option-select-ui-handler.ts, src/ui/confirm-ui-handler.ts, src/ui/egg-summary-ui-handler.ts
- The Yes/No menu for skipping to egg summary no longer interprets the `Cancel` input as `No`
- That menu also gets a 1 second input delay before a choice can be made
- The egg summary itself cannot be closed for a few seconds after it gets displayed
It is way too easy to skip the egg summary on accident if the Skip Hatch setting is set to "Always"
And if it is set to "Ask" it is also way too easy to pick an unwanted option on accident
- `confirm-ui-handler.ts`: handle the noCancel option and prevent cancelling the input blocking if it is set to `true`
- `egg-lapse-phase`: add 1s input delay to the hatch skip menu + prevent cancelling it 
- `egg-summary-ui-handler`: add 2s input delay if egg hatch setting is set to skip, otherwise to 1 second, for a total of 2 second delay no matter the …
=> [QoL][UI] Add input delay before skipping egg summary

src/phases/move-phase.ts
A duplicate move failure message won't show up.
https://discord.com/channels/1125469663833370665/1295393193029931080
A check for whether the move already failed was added around `resolveFinalPreMoveCancellationChecks()` to restore previous behavior.
<details>
<summary>Before fix (taken from Discord thread)</summary>
https://github.com/user-attachments/assets/29da71c6-1a07-4942-ad94-37ee3c50722b
</details>
<details>
<summary>After fix</summary>
https://github.com/user-attachments/assets/447a15ab-335b-455a-86b3-1feca9941a19
</details>
Use overrides to give the opponent Growl and yourself Metal Burst, make sure the opponent is faster (make them level 50 or whatever), and then use Metal Burst. The failure message should only occur once.
- ~[ ] Have I considered writing automated tests for the …
=> [Bug] Prevent duplicate move failure message

src/data/trainer-config.ts
- Magma Grunts will have a chance to spawn with a Toedscool
- Magma Admins will no longer have a chance to spawn with a Barboach, now has a chance to spawn with Toedscool instead
- Aqua Admins now have a chance to spawn with Barboach
- Flare Grunts and Admins will have a chance to spawn with a Foongus
- Penny now leads with a boss Sylveon in fight 2 instead of a Starmobile
- All admins have had their canonical aces given their canonical genders.
Barboach was meant to be removed from the Magma pool entirely alongside Grunts and instead put in the Aqua pools, this was missed with the admins though so I am replacing it with Toedscool to parallel Team Aqua members getting access to Tentacruel. Originally in the making of this PR Xerosic was able to spawn with two Inkay's due to a quirk with …
=> [Balance] Evil Team Update / Penny Adjustments

src/phases/move-phase.ts
This fixes an issue in beta where "{Pokemon} used {Move}!" would not appear when the move would fail, instead immediately showing "But it failed!"
Reported [in the Discord](https://discord.com/channels/1125469663833370665/1295517833651814472)
`phases/move-phase`:
- Restored a missing call to `showMoveText` when the move being used would fail or be cancelled.
- `resolveFinalPreMoveCancellationChecks` now uses `this.cancel()` instead of directly setting `this.cancelled`.
https://github.com/user-attachments/assets/1e431bfe-7204-4015-bb96-b7642b38d728
1. Download [DOUBLESMEMENTO.txt](https://github.com/user-attachments/files/17370551/DOUBLESMEMENTO.txt) and change the file extension to `.prsv`. Load this file as session data onto a local build
2. On the first turn, use Liquidation on both …
=> [P3][Beta] Fix missing move text when a move fails

src/phases/move-effect-phase.ts, src/test/abilities/volt_absorb.test.ts
This interaction will now work properly. For example, if thunderbolt is used against a pokemon with volt absorb, and that pokemon with volt absorb is in a semi invulnerable state, the attack will just miss instead of triggering the ability. 
related to #4337 
Bug fix
added check in move-effect-phase.ts for if pokemon is in semi invulnerable state
https://github.com/user-attachments/assets/2d704a4f-2116-41cb-b91b-2278f09e9eb4
Override files, run the updated volt absorb test file, and manually change return value of hitcheck() to false. 
- [X ] **I'm using `beta` as my base branch**
- [X ] There is no overlap with another PR?
- [ X] The PR is self-contained and cannot be split into smaller PRs?
- [X ] Have I provided a clear explanation of the changes?
- [X ] Have I considered writing …
=> [Bug Fix] Attacks that miss against pokemon in semi invul state that have abilities such as volt absorb will not trigger while semi invulnerable

src/data/arena-tag.ts, src/data/move.ts, src/field/arena.ts, src/field/pokemon.ts, src/phases/move-effect-phase.ts, src/phases/post-summon-phase.ts, src/phases/stat-stage-change-phase.ts, src/phases/turn-start-phase.ts, src/test/moves/aurora_veil.test.ts, src/test/moves/light_screen.test.ts, src/test/moves/reflect.test.ts
N/A
Simulated calls to arena tags are necessary for the Enemy AI to evaluate turn actions silently, especially when [Infiltrator](#4636) is implemented. With that change, I figured it was also a good time to add type inference to `ArenaTag.apply` along the lines of #4294 
`data/arena-tag`: The signature for `ArenaTag.apply` has changed from
```ts
apply(arena: Arena, args: any[]);
```
to
```ts
apply(arena: Arena, simulated: boolean, ...args: unknown[]);
```
The new `simulated` argument, much like the argument of the same name for abilities' `apply` functions, allows arena tags to be applied without any observable changes to game state. `args` has also been changed to use spread syntax, which allows `overrides` of the function in subclasses to expand `args` into multiple arguments. …
=> [Refactor] Add type inference and support for simulated calls to `ArenaTag.apply`

src/data/move.ts, src/field/pokemon.ts, src/phases/faint-phase.ts, src/test/moves/destiny_bond.test.ts
(Original bug report: https://discord.com/channels/1125469663833370665/1289804691076681728)
If a Pokemon uses Destiny Bond then gets KO'd by certain moves (confirmed examples are Ceaseless Edge, Stone Axe, and Pledge moves), it should no longer cause a crash.
Fixing a crash.
1. Destiny Bond's activation is moved to the Destiny Bond user's FaintPhase so that it occurs after the game applies all move effects. This ensures that the opponent is not fainted yet when applying move effects, which lets us avoid crashes, and also ensures that the move effects are successful, which matches Showdown's implementation:
[20241013 Destiny Bond.html.txt](https://github.com/user-attachments/files/17379272/20241013.Destiny.Bond.html.txt)
2. Certain move effect attributes using `getLastXMoves` now check …
=> [P1 Bug] Fix several Destiny Bond crashes

src/battle-scene.ts, src/data/mystery-encounters/encounters/a-trainers-test-encounter.ts, src/data/mystery-encounters/encounters/absolute-avarice-encounter.ts, src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts, src/data/mystery-encounters/encounters/dark-deal-encounter.ts, src/data/mystery-encounters/encounters/fiery-fallout-encounter.ts, src/data/mystery-encounters/encounters/fun-and-games-encounter.ts, src/data/mystery-encounters/encounters/global-trade-system-encounter.ts, src/data/mystery-encounters/encounters/lost-at-sea-encounter.ts, src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts, src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts, src/data/mystery-encounters/encounters/safari-zone-encounter.ts, src/data/mystery-encounters/encounters/shady-vitamin-dealer-encounter.ts, src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts, src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts, src/data/mystery-encounters/encounters/the-strong-stuff-encounter.ts, src/data/mystery-encounters/encounters/the-winstrate-challenge-encounter.ts, src/data/mystery-encounters/encounters/training-session-encounter.ts, src/data/mystery-encounters/encounters/trash-to-treasure-encounter.ts, src/test/mystery-encounter/encounters/the-expert-breeder-encounter.test.ts
(Original bug report: https://discord.com/channels/1125469663833370665/1289869659297812520)
The Expert Pokemon Breeder's ace should never be invisible.
(Note: The linked bug report also mentioned some crashes when starting the Expert Pokemon Breeder. However, I was never able to reproduce a crash. So, I guess that this PR could also fix the crashes, but we can't know for sure.)
Fixing a bug, potentially fixing a crash.
The ME options for Expert Pokemon Breeder now properly return a Promise so that the game can wait for the Promise to be resolved before starting the battle. This Promise includes loading all assets needed for the battle, so this change should cause the game to wait for all assets to be loaded before starting the battle.
Also updated some tests.
Modify …
=> [Bug] Potential fix for Expert Breeder's Pokemon being invisible

src/ui/party-ui-handler.ts
(Original bug report: https://discord.com/channels/1125469663833370665/1125894949020381285/1296088418387759106)
The party UI will no longer crash from `this.lastCursor` pointing to an empty Pokemon slot without a Pokemon, especially during ME's that take away one of your Pokemon.
Fixing a crash.
Right after sanitizing `this.cursor`, the code now also sanitizes `this.lastCursor` by moving it to the last filled Pokemon slot if it is currently at an empty Pokemon slot.
1. Reach an ME that takes away one of your Pokemon (e.g., Training Session).
2. Move the cursor to the last Pokemon in your party.
3. Press LEFT to move the cursor to the first Pokemon, and select it for the encounter.
4. During the encounter, go to the party UI (e.g., by fainting).
5. Press RIGHT.
Before the changes: …
=> [P1 Bug] Fix party UI crash from unsanitized `lastCursor`

src/data/mystery-encounters/encounters/safari-zone-encounter.ts
The informational comment was accidentally removed when removing the commented-out code below it in #4671
=> [Misc] Restore info comment that was accidentally removed

src/data/ability.ts, src/data/move.ts
Secret Power has a 30% rate of applying a secondary effect. Previously, it was 30%*30% 
oops
- moved effectChanceOverride to the correct attr
- removed edge case tags
Use Secret Power
=> [Bug][Beta] Corrected Secret Power's secondary effect chance + removed edgecase tags

src/ui/modifier-select-ui-handler.ts
1) (beta) No more offset cursor between waves 51 and 90 in shop
2) (all) Slight adjustments to element positioning in shop screen to allow more room for the free rewards description
1) #4555 caused an issue with misaligned shop cursor in some cases
2) Some item descriptions overlap in some languages, so the changes make room for descriptions to potentially take up 2 lines. This PR does not change any item description, only makes room in prevision for future updates that do need it. (for example PR #4065)
- Replace mistaken `>=` by `>` to fix the cursor placement issue
- Add some constants used to place stuff around so UI so that can it be more easily adjusted
- The following placement adjustments were made:
- Move paying items slightly up
- Move Reroll / Lock / Transfer / Party options …
=> [Beta P3][UI] Fix item/cursor placement in shop screen

src/phases/learn-move-phase.ts
Currently, the "fanfare" sound effect for learning a move incorrectly plays at the start of the message sequence when replacing a move instead of upon showing "{Pokemon} learned {Move}!". This fixes that.
Fixing a bug introduced in #3672 .
`phases/learn-move-phase` -- in `learnMove()`:
- Broke up the `showTextPromise` for the full message into 2 calls: 1 for the "pre-learn" messages (if applicable), and 1 for 
"{Pokemon} learned {Move}!"
- Moved the `level_up_fanfare` sound effect so that it plays between the split `showText` calls.
https://github.com/user-attachments/assets/5b9416ee-fe4d-447b-96a1-170d1f10dfea
1. Level up a Pokemon until they are prompted to replace a move with a new move.
2. Replace a move
3. The "fanfare" sound effect should play on "{Pokemon} learned {Move}!"
=> [P3] Fix mistimed sound effect when replacing a move

src/field/pokemon.ts, src/overrides.ts, src/test/utils/helpers/challengeModeHelper.ts, src/test/utils/helpers/classicModeHelper.ts, src/test/utils/helpers/dailyModeHelper.ts, src/test/utils/helpers/overridesHelper.ts
N/A
Random shinies could break certain tests. Also, the shiny override could only force Pokémon to be shiny, but not force them not to be shiny.
The default values of the shiny overrides is now `null` instead of `false`, and setting them to `false` will force Pokémon to not be shiny. The variant overrides now also default to `null`, and will be able to specify the base variant (`0`) of the shiny.
`npm run test`
=> [Misc] Shiny overrides can now force Pokemon to not be shiny

src/data/arena-tag.ts, src/test/moves/toxic_spikes.test.ts
Arena hazards will properly affect the Pokémon that set them (which can happen due to the hazards being swapped with Court Change, for example). This also means Toxic Spikes will be removed if the Pokémon that set them was a poison type and switches in to them.
Fixes #935 
Removed the `this.sourceId === pokemon.id` check in `ArenaTrapTag.apply()`.
`npm run test toxic_spikes`
=> [Bug] The pokemon that set an arena hazard shouldn't ignore it

src/data/battler-tags.ts, src/test/moves/nightmare.test.ts
Fix for  #4691 
Nightmare was just not working properly before and hitting the pokemon on improper turns and twice a turn. This fixes that.
big fix
Changed battler tag for nightmare from working after the move to the end of the turn. 
Just when asleep
https://github.com/user-attachments/assets/e9038948-d6ec-4c1b-aa61-8cb36a768965
It works properly when pokemon wakes up and is put back to sleep
https://github.com/user-attachments/assets/60ab9bf9-dbe8-4657-8102-05cee8a0cfdf
override files, and new nightmare unit test
=> [Bug Fix] Fix for Nightmare does not work properly

src/overrides.ts, src/phases/move-phase.ts, src/test/data/status-effect.test.ts, src/test/utils/helpers/moveHelper.ts, src/test/utils/helpers/overridesHelper.ts
N/A
This allows the testing of more interactions with status effects (specifically Paralysis and Freeze).
#4680 needed a way to test the interaction of Frenzy moves and Paralysis.
Added `STATUS_ACTIVATION_OVERRIDE` to `overrides.ts`.
Added the helper function `forceStatusActivation()` in `MoveHelper` to manipulate `STATUS_ACTIVATION_OVERRIDE` per-move.
Added an example test of the Paralysis status effect to demonstrate usage of `forceStatusActivation()`.
`npm run test status-effect`
=> [Test] Add a way for tests to force activation of Statuses

src/battle-scene.ts
The missing form of Minior will now appear.
One of the forms of minior couldn't appear in the wild.
`6 -> 7`
=> [Bug] All forms of Minior can now spawn in the wild

src/phases/switch-summon-phase.ts, src/test/moves/baton_pass.test.ts
This fixes an issue where binding effects (e.g. Bind, Sand Tomb) and other volatile effects would persist after the source used Baton Pass or Shed Tail to switch out.
This was discussed [in the Discord](https://discord.com/channels/1125469663833370665/1125894949020381285/1298525704723369984). I assumed this interaction was correct when implementing Shed Tail 🤷‍♂️ 
`phases/switch-summon-phase`: The code to remove tags from enemies with the returning Pokemon as the source no longer only runs for the `SWITCH` switch type.
`npm run test baton_pass` (1 new test)
=> [P2] Fix binding, etc. not being removed when switching with Baton Pass

src/data/ability.ts, src/data/move.ts, src/field/pokemon.ts, src/modifier/modifier-type.ts, src/modifier/modifier.ts, src/system/pokemon-data.ts, src/test/abilities/imposter.test.ts, src/test/moves/transform.test.ts
None, hopefully.
PR #3462 makes Transform/Imposter set copied moves to 5 maximum PP by assigning a negative `ppUp` value that can be fractional. In case a negative fractional `ppUp` would break something, this PR replaces the `ppUp` method with a new `PokemonMove.maxPpOverride` property.
NOT CHANGED: The final boss's Recover still uses -4 ppUp (did not want to risk breaking it).
1. Added `maxPpOverride` property to `PokemonMove`.
2. Updated tests to check that Transform/Imposter does not set a negative fractional `ppUp`.
<details>
<summary>After the changes: Transform sets correct max PP</summary>
https://github.com/user-attachments/assets/63441d3b-cb3d-42e9-b6cd-7cdcfed99c5d
</details>
<details>
<summary>After the changes: Imposter sets correct max PP</summary> …
=> [Beta] Stop Transform giving copied moves negative fractional `ppUp`

package-lock.json, package.json, src/phases/turn-start-phase.ts
Lum Berry should now proc before status damage is taken into account.
Reported [in the Discord](https://discord.com/channels/1125469663833370665/1125894949020381285/1299859893322256474)
`turn-start-phase`: Swapped the push-order of `BerryPhase` and `CheckStatusEffectPhase`
- In `overrides`, give your Pokemon Poison and a Lum Berry
- At the end of the first turn, the Lum Berry should be consumed before Poison damage has a chance to trigger.
=> [Hotfix] Fix status damage triggering before berry usage

package-lock.json, package.json, src/main.ts, src/plugins/i18n.ts
Live: if all goes well nothing. If all goes amazing lingering caching/sprite issues could get solved
Offline/local play should work again (potentially needs changes from #4735 to handle locale stuff automatically for non devs)
PR #4327 made the `startGame` function async, which makes the manifest initialization fail. Causing the game to fallback to a catch statement that launches the game a second time
(we failed to notice this because only live has a manifest)
A temporary hotfix was pushed (commit a9a73863e89caf979f28c4e97be61ff160a0116a), but it breaks offline and local play
This PR should fix the problem for good
- Put the manifest as an optional parameter of the startGame() function (thank you flx)
- only call startGame() from the `finally` of the manifest fetch request, so that it …
=> [Hotfix] Fix manifest getting loaded before the game is initialized

package-lock.json, package.json, public/images/pokemon/688.json, public/images/pokemon/back/688.json, public/images/pokemon/back/shiny/688.json, public/images/pokemon/shiny/688.json
Binacle sprites are now fully on screen
Reported [here](https://discord.com/channels/1125469663833370665/1230751815482736640/1300159515634958420). The opportunity was also taken to trim unused fields from the Binacle front .jsons.
No mechanical differences, simple asset data modifications only.
Start a run with Binacle of any rarity.
~~- [ ] **I'm using `beta` as my base branch**~~
~~- [ ] Have I considered writing automated tests for the issue?~~
~~- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~~
=> [Sprite] Hotfix cut off Binacle sprite

package-lock.json, package.json, public/images/pokemon/658-ash.json, public/images/pokemon/658.json, public/images/pokemon/back/658-ash.json, public/images/pokemon/back/658.json, public/images/pokemon/back/shiny/658-ash.json, public/images/pokemon/back/shiny/658.json, public/images/pokemon/shiny/658-ash.json, public/images/pokemon/shiny/658.json
Re-exported json files for static sprites on greninja and ash greninja
using base sprite
shiny sprite
ash greninja base sprite
ash greninja shiny sprite
~~- [ ] **I'm using `beta` as my base branch**~~
~~- [ ] The PR is self-contained and cannot be split into smaller PRs?~~
~~- [ ] Have I considered writing automated tests for the issue?~~
~~- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~~
=> [Sprite][hotfix] Fixed cropping on 658 static greninja and ash greninja

package-lock.json, package.json, src/data/arena-tag.ts, src/phases/stat-stage-change-phase.ts, src/test/moves/mist.test.ts
Stat-stage-decreasing effects should no longer crash the game when applying to a target while Mist is active
Oversight on my end...
`phases/stat-stage-change-phase`: Fixed incorrect arguments in the `applyTagsForSide` call for Mist (there was an extra `false` that was misplaced)
`npm run test mist` (1 new test + 1 new TODO for when Infiltrator is fully implemented)
=> [Hotfix] Fix crash when Mist would block a stat drop

src/data/ability.ts, src/data/move.ts
Last Respects will be marked with `(P)`.
The move implementation is incomplete. cf https://github.com/pagefaultgames/pokerogue/issues/3503#issuecomment-2440608882
Added `.partial()` to Last Respects with a comment explaining why it's partial.
=> [Move] Mark Last Respects as partial

src/data/move.ts
Bouncy Bubble's healing has been reduced from 100% drain to 50% drain to match LGPE's drain (without the increase in power).
By request of Game Design Head and Game Balance Head, a 60bp spread move with 100% drain was way too much on anything that received the move. Even not accounting for egg moves, the move was VERY powerful on Vaporeon and even Eevee. We were using unused data from Gen 8 when implementing these moves in and it was decided by both Megalith and Damo to give the move a more "custom implementation" to make it not the most egregious thing ever.
Changed HitHealAttr on Bouncy Bubble
Added note to indicate custom implementation, fixed Zippy Zap's note
Overrides
=> [Balance] Change Bouncy Bubble's Attributes

src/ui/pokemon-info-container.ts
Currently, if there's a form of a caught pokemon, the pokemon info container shows the form name for pokemon using the getRootSpeciesId. Unfortunately this means that the i18 key (if there's a custom one) can be incorrect. This PR changes it to use the speciesId instead of the root pokemon speciesId
Currently, if there's a form of a caught pokemon, the pokemon info container shows the form name for pokemon using the getRootSpeciesId. Unfortunately this means that the i18 key (if there's a custom one) can be incorrect. This PR changes it to use the speciesId instead of the root pokemon speciesId
Currently, if there's a form of a caught pokemon, the pokemon info container shows the form name for pokemon using the getRootSpeciesId. Unfortunately this means that the i18 key (if there's a …
=> [P3] [Bug] Fixing form name being incorrect for some evolved pokemon

src/data/move.ts, src/test/moves/chloroblast.test.ts
Chloroblast and Struggle won't deal recoil damage if the move fails due to miss or Protect.
The behavior is incorrect.
> **If this move is successful**, the user loses 1/2 of its maximum HP, rounded up, unless the user has the Magic Guard Ability.
- https://www.smogon.com/dex/sv/moves/chloroblast/
Added a check for if the move failed or missed and is a move whose recoil is based on the user's HP and not on the move's damage in `RecoilAttr`.
`npm run test chloroblast`
=> [Bug] Chloroblast & Struggle should not recoil if the move failed

src/data/move.ts
The Enemy AI should no longer favor their allies as targets when using status moves that apply status effects, e.g. Thunder Wave or Sleep Powder
A small bug fix to tide shareholders over before the AI gets reworked
`data/move`: Adjusted scoring functions for `StatusEffectAttr` and related attributes so that negative effect chance values (internally used for guaranteed effects) are interpreted in the same way as a 100% effect chance value.
N/A
1. Use overrides to force double battles and give enemies various status effect moves
2. The enemies should never target each other with said status effect moves
=> [P2][AI] Fix Enemy AI targeting their allies with Status Effect Moves

src/data/balance/pokemon-evolutions.ts
Own Tempo Rockruff will be able to evolve into Dusk Lycanroc.
- Bug report: [Discord](https://discord.com/channels/1125469663833370665/1300970700172951582)
Fixing a bug.
Own Tempo Rockruff's evolution condition now checks for the Rockruff to have form key "own-tempo" instead of "". (This has been broken for a while but did not matter until #4581.)
<details>
<summary> Before the changes: Own Tempo Rockruff cannot evolve </summary>
https://github.com/user-attachments/assets/be1b648b-3ad2-4469-bfc1-cc7106cb1320
</details>
<details>
<summary> After the changes: Own Tempo Rockruff evolves properly </summary>
https://github.com/user-attachments/assets/f10cbb9a-3ebb-4b86-a147-5429598239e8
</details>
<details>
<summary> After the changes: Regular Rockruff evolves properly </summary> …
=> [P2 Bug] Fix Own Tempo Rockruff not being able to evolve

src/ui/target-select-ui-handler.ts
During Doubles, the second Pokemon's target will not default to the first Pokemon's target. This will prevent the accidental knockout of allied Pokemon + bring PokeRogue in line with mainline behavior.
Who hasn't knocked out their only ally in a double because of this?
this.cursor set to -1 upon ui clear()
https://github.com/user-attachments/assets/d1c464f2-40f8-4e37-8b60-437b7f467410
In a doubles battle, the first player pokemon should target an ally. When the second Pokemon chooses a move, the target UI cursor should be on the left-most enemy Pokemon.
=> [UI][QoL] Target Selection Defaults to Left-Most Enemy Pokemon in Doubles

src/battle-scene.ts, src/data/mystery-encounters/encounters/clowning-around-encounter.ts, src/data/mystery-encounters/utils/encounter-phase-utils.ts, src/modifier/modifier-type.ts, src/test/utils/gameWrapper.ts, src/test/utils/mocks/mockTimedEventManager.ts
None / Correct tier displayed for Soothe Bell if it is added as a fixed reward in shop
Event PR #4728 put Soothe Bell in two tiers, Great and Rogue tier. During events Rogue tier weight's is 0 so the item gets treated as Great tier, the rest of the time it is in Rogue tier as before, with weight 0 in Great Tier.
MEs use code that looks for the tier of a given modifier type in the item pool. But this code does not take the weight into account, which makes it think that Soothe Bell is a Great Tier item at all times, even if no event is ongoing.
This has notably caused the Clowning Around ME test to fail
This issue would also cause the Soothe Bell to appear visually as a Great Tier item after the event is done if set as a fixed shop reward by a ME
This PR should address both the issue of …
=> [Bug] Take weight into account when getting the tier of a modifier

src/data/move.ts, src/test/moves/shed_tail.test.ts
Shed Tail and Baton Pass should now correctly fail when used with no available Pokemon in the user's party to switch in
Following up on #4643, which didn't completely fix status moves
`data/move`: Added a new condition for Shed Tail and Baton Pass requiring the user to have at least one available Pokemon in their party and not on the field. Note that `Pokemon.isActive()` also checks for challenge-eligibility, so the new condition will not be met by party Pokemon not allowed in battle.
`npm run test shed_tail` (1 new test)
- [n/a] If I have text, did I make it translatable and add a key in the English locale file(s)?
=> [Move][P2] Add "no switch-in" fail condition for Shed Tail and Baton Pass

src/data/ability.ts
Mold Breaker will interact properly with the abilities Plus, Minus, Beads of Ruin, Sword of Ruin, Shield Dust, and Aroma Veil
Bug Report: https://discord.com/channels/1125469663833370665/1301203120432611398 
Reference Link: https://bulbapedia.bulbagarden.net/wiki/Ignoring_Abilities#Ignorable_Abilities 
.ignorable() tags removed from Plus, Minus, Beads of Ruin, Sword of Ruin
.ignorable() tags added to Shield Dust and Aroma Veil
Mold Breaker should be able to apply effects the ability holder is immune to.
=> [Bug][Ability] Updating abilities that interact with Mold breaker

src/data/ability.ts, src/data/move.ts, src/field/pokemon.ts, src/modifier/modifier.ts, src/test/moves/focus_punch.test.ts
N/A
More precise variable names.
`PokemonTurnData.damageDealt` renamed to `PokemonTurnData.totalDamageDealt`.
`PokemonTurnData.currDamageDealt` renamed to `PokemonTurnData.singleHitDamageDealt`.
`npm run test`
Functionality should remain unchanged though.
=> [Misc] Rename `PokemonTurnData`'s `damageDealt` and `currDamageDealt`

src/data/ability.ts
Illuminate ignores the opponent's evasion stat changes. 
I was looking through old issues I opened and remembered about https://github.com/pagefaultgames/pokerogue/issues/1352
* Added `      .attr(IgnoreOpponentStatStagesAbAttr, [ Stat.EVA ])` to illuminate
* Specified `[ Stat.ATK, Stat.DEF, Stat.SPATK, Stat.SPDEF, Stat.ACC, Stat.EVA ]` for Unaware since right now Unaware also ignores speed (but that's never being called) so there is no difference for users. This is just more accurate data and for future proofing
* Added documentation to `IgnoreOpponentStatStagesAbAttr`
n/a
Pull and test
=> [Ability] Illuminate ignores eva, Unaware does not ignore speed

src/data/move.ts, src/field/pokemon.ts, src/test/moves/round.test.ts
Round is now fully implemented with the power boost and turn order manipulation effects.
less (P) moves pikasmile
- `data/move`: 2 new attributes for Round: one for the power boost from previous Round uses, and the other for manipulating turn order
- `field/pokemon`: New `turnData` field to track if the Pokemon is using Round as a followup to another Pokemon's Round.
- `test/moves/round.test`: New unit test checking turn order manipulation and power boost.
**Both allies using Round in a double battle:**
https://github.com/user-attachments/assets/6f755b67-530e-47eb-a30c-52d4162e3674
Note that Shuckle moves immediately after Voltorb [despite having the lowest base Speed out of any evolved Pokemon](https://bulbapedia.bulbagarden.net/wiki/List_of_fully_evolved_Pok%C3%A9mon_by_base_stats). …
=> [Move] Fully Implement Round

src/field/pokemon.ts
None, hopefully.
#4596 meant to remove unimplemented moves from enemy movesets entirely but part of the change was forgotten.
Add missing check for unimplemented moves in moveset generation code.
=> [Bug][Beta] Enemy pokemon shouldn't get unimplemented moves

src/ui/starter-select-ui-handler.ts, src/ui/summary-ui-handler.ts, src/ui/ui.ts
- (touch) Tooltips should no longer go offscreen
- (touch) Tooltips will show in the top right of the screen when interacting with an element in the top left
- Tooltip titles get centered properly in the tooltip window
- Tooltips for Candy Friendship and Frienship have a bigger hitbox
- Passive / Candy tooltip gets hidden for mons without passive / candy in starter select
Tooltips titles would sometimes show outside of their window
Tooltips are currently awful to use on mobile because:
- they show in the top left corner, so when trying to look at our items in battle they obscure the items.
And if we want to read the tooltip for something in the top left our thumb is in the way, for example when looking at Candy friendship in a Pokemon's summary 
- they actually don't stay properly in the …
=> [P3][UI][QoL] Fix tooltips going out of screen on mobile & other improvements

src/data/ability.ts, src/test/moves/freeze_dry.test.ts
The Player was not able to damage a target with "Wonder Guard" even though the used move forced super effectiveness against the soaked target (forced water type). Now freeze dry damages the target correctly.
I saw the [Issue](https://github.com/pagefaultgames/pokerogue/issues/4744) (#4744 ) and wanted to fix it
Should the Player Pokemon use Freeze Dry (which has the [`WaterSuperEffectTypeMultiplierAttr`](https://github.com/pagefaultgames/pokerogue/blob/13841765f177a2e6626683967457adcfc965b631/src/data/move.ts#L4889-L4903) on a target with the [`NonSuperEffectiveImmunityAbAttr`](https://github.com/pagefaultgames/pokerogue/blob/13841765f177a2e6626683967457adcfc965b631/src/data/ability.ts#L508-L529) it now checks if the target is of Type …
=> [Bug] Fixing Incorrect Freeze Dry Interaction With Soaked Wonder Guard Target

src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
When trading Soothe Bell with no event running, the ME will recognize it as Rogue Tier and give a Master Tier item in exchange
I missed that ME in PR #4775. [Discord bug report](https://discord.com/channels/1125469663833370665/1303136714172399727)
Give the proper parameters to the `withTierFromPool` call
Missed that use of it initially because the modifier didn't have its proper typing so the IDE didn't recognize it as a reference to it. 😔 No more MEs should have this issue now
Before, giving soothe bell would get you an Ultra Tier item:
After, master tier:
Overrides
```
MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.GLOBAL_TRADE_SYSTEM,
MYSTERY_ENCOUNTER_RATE_OVERRIDE: 255,
STARTING_WAVE_OVERRIDE: 11,
STARTING_BIOME_OVERRIDE: Biome.PLAINS,
STARTING_HELD_ITEMS_OVERRIDE: [{ name: …
```
=> [P2][ME] Fix GTS not getting the correct tier when trading items

src/data/ability.ts
The ability [Commander](https://bulbapedia.bulbagarden.net/wiki/Commander_(Ability)) now quadruples the chance of encounters being double battles while the source is on the field in the same way as No Guard, Illuminate, and Arena Trap.
Requested by Balance Team to offer more opportunities for Commander to activate.
`data/ability`: Commander now has a `DoubleBattleChanceAbAttr`.
Start a run with Commander Tatsugiri and pick up a lure from item rewards. The next Wild encounter should be guaranteed to be a double battle.
- [n/a] Have I considered writing automated tests for the issue?
- [n/a] If I have text, did I make it translatable and add a key in the English locale file(s)?
=> [Balance][Beta] Commander now increases double battle chance

src/field/pokemon.ts
Boss pokemon will now heal the expected numerical value regardless of segments. (Grassy Terrain 1/16 * maxHp, Recover - 1/2 * maxHp, etc.)
Probably has a significant impact on difficulty.
Fixes #1488
Corresponding discussion on discord: https://discord.com/channels/1125469663833370665/1176874654015684739/1304274351297659013
Removed EnemyPokemon.heal() overload. Now defaulting to Pokemon.heal()
- Set overrides
```js
OPP_HEALTH_SEGMENTS_OVERRIDE: 3,
OPP_MOVESET_OVERRIDE: Moves.GRASSY_TERRAIN,
}
```
(Should probably get playtested in a normal run)
=> [Bug] Boss segments will no longer block healing

src/data/move.ts, src/test/moves/sketch.test.ts
Sketch should no longer crash the game when it tries to copy a move from a lost turn. 
A bug a day...
See #4610 
Added some conditional checks to SketchAttr, but more research is needed to be done on what Sketch can copy and what it cannot. Throwing into draft.
Will write a test as well.
=> [Bug] Prevents crash from using Sketch against a lost turn 

src/data/ability.ts, src/data/arena-tag.ts, src/data/move.ts, src/data/terrain.ts, src/phases/turn-start-phase.ts, src/test/moves/upper_hand.test.ts
Upper Hand should now work against attacks boosted by Gale Wings, Triage, etc.
More implementation + consolidating some recurring code for move priority calculations
- `data/move`:
- New function `Move.getPriority` returns the move's final priority after applying relevant move and ability attributes (e.g. from Grassy Glide or Prankster)
- Rewrote Upper Hand's condition into a `UpperHandCondition` class such that it now uses the new `getPriority` function and facilitates condition-based effect scoring for future AI plans.
- Rewrote several instances where move priority is independently calculated to use the new `getPriority` function instead.
`npm run test upper_hand` (new)
- [n/a] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [?] Are the changes …
=> [Move][Refactor] Create `Move.getPriority` + Fully Implement Upper Hand

src/data/battler-tags.ts, src/phases/command-phase.ts, src/test/moves/encore.test.ts, src/ui/command-ui-handler.ts
Encore will interact correctly with other Move Restriction moves like Torment and Disable. Previously, it would override them and allow the use of restricted moves. 
A bug a day keeps the shareholders and the triage team happy. 
See #4745 
Because Encore was implemented before the introduction of the MoveRestrictionBattlerTag class, it had a separate implementation from other Move Restriction moves. Encore would override any other move restriction battler tags as result. This PR converts Encore into a MoveRestrictionBattlerTag and removes checkFightOverride() --> which was specifically only used to execute Encore's effects. Now, Encore uses the same 'scaffolding' as move restriction battler tags. 
A test was created for Encore's interactions with other tags of MoveRestrictionBattlerTag. …
=> [Bug] Fixing Encore's interactions with other Move Restriction moves 

src/test/abilities/wimp_out.test.ts
N/A
Test was flaky.
HP is now set within the test.
`npm run test wimp_out`
=> [Test] Fix flaky Wimp Out test

src/field/pokemon.ts, src/phases/switch-summon-phase.ts
A few effects will now correctly persist when the Pokemon switches out, including:
- Rage Fist's power boost upon getting hit by an attack
- Belch's condition requiring the user to have eaten a berry
- A list of abilities applied during battle. This is relevant for Intrepid Sword and similar abilities, which will now only activate once per battle.
`battleData` was being misused so that it was managed in basically the same way as `battleSummonData`. (closes #4708)
Removed `Pokemon.resetBattleData` calls from `Pokemon.leaveField` and `SwitchSummonPhase.preSummon`
=> [P2] Removed incorrect calls to `resetBattleData` on switchout

src/battle-scene.ts, src/field/pokemon.ts, src/phases/check-switch-phase.ts, src/phases/encounter-phase.ts
This fixes several bugs introduced with Commander's implementation:
- **(P1)** Fixed a bug where trying to remove Commander's effects at the end of some Mystery Encounters, even if Commander isn't present, would crash the game.
- (P2) Fixed a bug where self trapping effects including Commander, No Retreat, and Ingrain would not prevent the affected Pokemon from being given a prompt to switch out at the start of battle.
- (P3) Fixed some bugs with Tatsugiri's appearance in a few situations:
- when reloading a game where Tatsugiri is commanding Dondozo at the start of a wave.
- when transitioning from a double battle to a single battle.
These bugs were reported after @damocleas did some stress testing on Commander's implementation. One of the reports is available on the Discord …
=> [Bug][Beta] Fix Commander implementation bugs

src/data/move.ts, src/field/pokemon.ts, src/modifier/modifier.ts, src/test/abilities/sap_sipper.test.ts, src/test/moves/sketch.test.ts
Sketch can successfully sketch Metronome and some other moves that call other moves virtually.
Fixing a bug newly introduced by #4806.
1. `SketchAttr` no longer places a limit on the number of moves retrieved by `getLastXMoves()`. The limit did not properly account for situations where a Pokemon's move history can receive multiple entries in 1 turn. For example, Metronome adds 1 move entry for Metronome itself, then another entry for the randomly selected move.
2. Made `getLastXMoves()` more readable.
3. Added a Sketch test.
a. `RandomMoveAttr` can now have its randomly selected move overridden in tests.
b. Enabled a Sap Sipper test that needed the ability to override `RandomMoveAttr`.
<details>
<summary> Before the changes: Sketch fails (silently) when sketching Metronome </summary> …
=> [P2][Beta] Fix Sketch failing to sketch Metronome et al

src/modifier/modifier-type.ts
Nothing, probably.
Fixes minor things, no one else also undid these and want to make sure they don't cause issues in the future. There are other event specific changes I do not want to touch.
Removed all isEventActive tags from items in the item table
=> [Cleanup] Minor cleaning, Undo Event modifier-type.ts item table changes

src/data/mystery-encounters/encounters/fun-and-games-encounter.ts, src/field/pokemon.ts, src/phases/encounter-phase.ts, src/phases/summon-phase.ts
- No more crash at the start of the Expert Breeder ME when choosing a Pokemon that was caught during the run
- No more crash when trading your only Pokemon in Global Trade System ME
- In general should stop all similar crashes caused by Pokemon obtained during the current play session being sent in battle
Crashes not good, and this one has been reported a lot.
[Main discord thread](https://discord.com/channels/1125469663833370665/1289869659297812520/1300448219708522526). Shoutouts to PigeonBar for figuring out how to reproduce the bug
[Second thread](https://discord.com/channels/1125469663833370665/1303111425161433228/1304157578368122991) with more findings on this, in the context for the GTS ME this time
<details><summary>Crash explanation:</summary>
The crash is caused by this bit of …
=> [P1] Fix crash when newly aquired Pokemon are used in battle

src/@types/PokerogueSessionSavedataApi.ts, src/phases/game-over-phase.ts, src/test/plugins/api/pokerogue-session-savedata-api.test.ts
None.
Telemetry. 
The /newclear request sent in game-over-phase now also sends the result and the game mode as part of the URL. 
See PR [4 ](https://github.com/f-fsantos/rogueserver/pull/4) for server side code. 
Finish a run through winning or losing.
=> [Telemetry][Misc] Client-Side changes to log run results at the end of runs

src/data/ability.ts, src/data/move.ts, src/data/pokemon-species.ts, src/field/pokemon.ts
Transform and Imposter will fail if the user or the target is a fused Pokémon.
When either the user or target of Transform/Imposter is a fused Pokémon, the game tends to crash. With Imposter it can even break a session save because of an Imposter Pokémon immediately trying to transform when reloading a save.
Transform and Imposter now have checks that cause them to fail if either the user or the target is a fused Pokémon.
Start a session of "Endless (Spliced)" with Imposter Ditto and try to use Transform. To test for the player being fused, use these overrides and fuse Ditto as the second Pokémon onto another Pokémon:
```ts
ITEM_REWARD_OVERRIDE: [{ name: "DNA_SPLICERS" }],
MOVESET_OVERRIDE: [ Moves.TRANSFORM, Moves.SURF ]
} satisfies Partial<InstanceType<typeof …
```
=> [Bug] Transform and Imposter will now fail when either Pokemon is fused

src/field/pokemon.ts
The game should correctly wait for a shiny Pokemon's colours to be loaded before starting the battle and displaying the Pokemon.
Fixing a bug recently introduced by #4315.
@podarsmarty You mentioned in your PR #4315 that you "noticed some weirdness with experimental variation loading", would this PR fix those issues?
The code for loading shiny sprites now properly awaits `this.populateVariantColorCache(...)`.
To simulate sprites taking a long time to load, replace the following line of code:
https://github.com/pagefaultgames/pokerogue/blob/f2a2281ff11c5b644698121f6ce33f32830898b0/src/battle-scene.ts#L704
with the following line of code:
`return new Promise<void>((resolve => setTimeout(() => resolve(), 5000))).then(() => fetch(url, init));`
<details>
<summary> Before the changes: The game …
=> [P3][Beta] Fix shiny Pokemon being displayed before shiny colours are loaded

src/test/abilities/zen_mode.test.ts
N/A
The test file is very outdated/questionable.
The Zen Mode tests are more comprehensible (and more accurate?).
`npm run test zen_mode`
=> [Test] Modernize the tests for the Zen Mode ability

src/phases/move-phase.ts
Move Phase should end correctly if the move fails. 
My bug...
Removed the conditional requiring the PP Used to be greater than the move's max PP. 
Situation 1: 
https://github.com/user-attachments/assets/1949709a-4c22-43c9-ad33-5bff3522c799
Situation 2:
https://github.com/user-attachments/assets/ae164a1c-a0ec-4b04-b951-947fe9395833
Situation 1:
1. Faint a Pokemon
2. Progress through the next waves as normal.
Situation 2:
1. Attempt to run away from a double battle with a Pokemon that has the ability run away, but have the first Pokemon use a move.
=> [Beta][Bug] Move Phase not Ending Correctly 

src/data/ability.ts, src/data/move.ts, src/modifier/modifier.ts, src/test/items/multi_lens.test.ts
This restores Multi-Lens' ability to enhance multi-target moves. Parental Bond is unaffected.
Multi-Lens was changed recently with #4831 to function with the same restrictions as Parental Bond. However, the new restriction on multi-target attacks was deemed too detrimental to new and existing Endless runs by the Balance Team and other active community members.
- `Move.canBeMultiStrikeEnhanced` now has a `restrictSpread` parameter which, if true, enforces a restriction on multi-target moves for the associated multi-strike enhancement. This is set to `true` for Parental Bond and `false` (by default) for Multi-Lens
- New test in `test/items/multi_lens.test` showing the item now enhances multi-target moves.
`npm run test multi_lens`
=> [Balance][Beta] Revert Spread Move Restriction on Multi-Lens

src/data/move.ts, src/phases/move-phase.ts
If a charge move fails, the game will correctly display "But it failed!"
#4839 introduced more bugs than we expected.
Charge moves no longer check for `move.getFailedText()` to return a defined value in order to display the failure text. (My understanding is that `move.getFailedText()` is intended to check for custom failure text, and it returns `null` if the move should use the default failure text of "But it failed!".)
For reference, here is the code for `showFailedText()`:
https://github.com/pagefaultgames/pokerogue/blob/4802f512ff7925037ecb90bf4d19505d1831d2a4/src/phases/move-phase.ts#L550-L552
<details>
<summary> Before the changes: Charge move silently fails </summary>
https://github.com/user-attachments/assets/139ee999-4a3d-4038-a4b0-11d0c970ed09
</details>
<details>
<summary> …
=> [P3][Beta] Fix failed charge moves not displaying failed text

src/phases/level-up-phase.ts
Pokémon will now immediately evolve after leveling up, which will also prevent the bug causing evolutions to be rolled back when the player quits immediately after evolving their Pokémon.
Fixes #4039 
The code handling learning new moves and level up evolution is moved to a new `this.end()` function, which calls `super.end()` (which ultimately calls `scene.shiftPhase()`) at the appropriate time instead of in the middle of the phase before it's finished running.
<details>
<summary>Evolution Phase delayed until next wave (current behavior)</summary>
https://github.com/user-attachments/assets/49bf72c6-400e-49b1-acfb-3516ce807998
</details>
<details>
<summary>Evolution Phase immediately after Level Up Phase (PR fix)</summary>
https://github.com/user-attachments/assets/0c90d3df-9efd-4632-8f5b-f …
=> [Bug] Fix level up evolution delay

src/phases/quiet-form-change-phase.ts
- Wild Aegislash fainting will not display their form change message
- Fainting at the same time as a Gulp Missile'd Cram will not freeze the game
Reported bugs
[Aegislash](https://github.com/pagefaultgames/pokerogue/issues/4774)
[Cramorant](https://github.com/pagefaultgames/pokerogue/issues/4552)
I combined the two since they are closely related
- More checks in `QuietFormChangePhase`
- Fainted pokemon that are not the player's will not revert form
<details>
<summary>Aegislash</summary>
https://github.com/user-attachments/assets/7d5d9890-6c0c-4d6c-97b3-6762d0b23b5c
</details>
<details>
<summary>Cramorant</summary>
https://github.com/user-attachments/assets/64804cfe-ccb6-4c22-a71f-56d8c709e645
</details>
<details>
<summary>Cramorant (player)</summary> …
=> [Bug] Battles against wild Aegislash display a message after defeat, Gulp Missile activation freezes the game if both sides faint at the same time

src/data/challenge.ts, src/system/game-data.ts
The default starters will all start with IVs of 15. In addition, Fresh Start Challenge will also respect this change and starters will have IVs of 15. 
Balance Team request. 
game-data.ts and challenges.ts edited for this change. 
https://github.com/user-attachments/assets/60a48ea3-5a30-4606-a20c-945f855c568f
1. Start a new save file + Look at the IVs of the starters in starter-selection
2. Start a Fresh Start run -> IVs of the starters should be all set to 15
=> [Balance] Set the IVs of default starters to 15

src/data/battler-tags.ts, src/data/move.ts
If a Pokemon has FloatingTag because of Telekinesis, it will be under FloatingTag for 3 turns, not 5.
Bug found by @innerthunder + my oversight
FloatingTag now takes in a turn count. The move Magnet Rise now has an explicit minimum turn count of 5.
- Use Telekinesis on a Pokemon and count how many turns it has the FloatingTag.
=> [Bug] FloatingTag now takes a specific turn count

src/data/ability.ts, src/data/move.ts, src/field/pokemon.ts, src/test/moves/freeze_dry.test.ts
1. Freeze-dry will correctly account for Terastallization.
2. Freeze-dry will correctly account for a third type added by Forest's Curse.
#4840 making `FreezeDryAttr` fully recalculate Freeze-dry's type effectiveness is not ideal. Moreover, that PR did not match the usual type effectiveness calculations exactly, leading to the bugs described above.
1. `FreezeDryAttr` now extends a new class `VariableMoveTypeChartAttr` that applies type chart changes to each of the target's individual types.
2. Removed an `.edgeCase()` tag regarding Freeze-Dry's interaction with Tera Shell, since this interaction works correctly. Also added a test for the Tera Shell interaction.
3. Added some more tests.
@geeilhan Sorry for undoing your hard work. You tried your best, and we truly appreciate your work. …
=> [Move][Beta] Freeze-dry Re-implementation

src/data/move.ts, src/test/moves/moongeist_beam.test.ts
N/A
The moves are complete. cf https://github.com/pagefaultgames/pokerogue/issues/3503#issuecomment-2478343286
`.edgeCase()` is removed from some Sunsteel Strike, Moongeist Beam and Photon Geyser.
`npm run test moongeist_beam`
=> [Move] Remove `.edgeCase()` from fully implemented moves

src/data/battler-tags.ts, src/phases/pokemon-anim-phase.ts
This fixes a couple of bugs in Commander's implementation:
- Fixed an issue where the game would crash when transitioning from a double battle to a Trainer battle while a commanded Dondozo is on the field.
- Fixed an issue where Tatsugiri's form was not stored correctly on reload, causing Order Up to raise the wrong stat.
Commander animations are hard to manage :goomed:
- `phases/pokemon-anim-phase`: Added a failsafe to Commander's remove animation to abort the animation if the Dondozo's ally isn't fetched correctly.
- `data/battler-tags`: Added a `loadTag` override to `CommandedTag` to load the stored Tatsugiri form.
**Transition from Double Battle to Trainer Battle**
https://github.com/user-attachments/assets/0dd8388a-c17c-44eb-93f1-476a601b1a71
1. Use the following overrides:
```ts …
```
=> [Bug][Beta] Fix crash when resetting Commanded Dondozo before Trainer battles

src/data/move.ts
Lunar Blessing / Jungle Healing now heal freeze
Snailman request
See bug report on Discord: https://discord.com/channels/1125469663833370665/1293541076510183434 
HealStatusEffectMoveAttr revised to either take a singular status effect or an array of status effects, hopefully cleaning up the code. 
Use Lunar Blessing / Jungle Healing on a frozen ally.
=> [Bug] Lunar Blessing / Jungle Healing now heal Freeze

src/ui/target-select-ui-handler.ts
The cursor will reset its position to the leftmost enemy when:
1) It is the first turn (of the wave) for the Pokemon involved. 
2) A new wave begins
3) The Pokemon used a move that targeted an ally or itself
It will remember its position if it targets an enemy though. 
Changes requested by Beta testers. 
Changes to show() and processInput()
https://github.com/user-attachments/assets/623c9e26-ce07-4cfd-b91d-4df705e78af3
1. Fight in a double battle and check how the user facing conditions are working.
=> [Beta][Misc] Improved cursor memory for target selection in Doubles

src/data/battler-tags.ts, src/enums/battler-tag-type.ts, src/field/pokemon.ts, src/modifier/modifier.ts, src/test/moves/endure.test.ts
In Endless mode, the enemies' Endure Tokens will now only block a single hit when activated, rather than all instances of damage for the rest of the turn.
Requested by Balance Team. Endure Tokens artificially stall the game in a way that is out of the player's control, and they contribute to making Endless an exhausting experience for some. This change should help alleviate players' frustration with the mode and make the mode more fast-paced in general.
Endless Tokens now use an `ENDURE_TOKEN` battler tag type instead of the `ENDURING` type. Both types use the same `EnduringTag` class, but `ENDURE_TOKEN` is different in that it uses the `AFTER_HIT` lapse type. In turn, the enduring effect from Endure Tokens is removed immediately after the affected Pokemon is hit by an otherwise lethal …
=> [Balance] Endure Tokens only endure one hit

src/data/mystery-encounters/utils/encounter-dialogue-utils.ts, src/ui/mystery-encounter-ui-handler.ts, src/ui/run-info-ui-handler.ts, src/ui/text.ts
Readable text in MEs when using legacy theme
Being able to read the game's text is good
Default theme is unchanged
Legacy theme had the following changes, only affecting MEs:
- white text to black
- money text from pale yellow to gold
- option with fulfilled requirement from green to gold
Implementation:
- `encounter-dialogue-utils.getEncounterText` now properly uses the current ui theme when calling `getTextColor`
- `text.ts`:
- added new TextStyles `ME_OPTION_DEFAULT` and `ME_OPTION_SPECIAL` for ME option colors
- Added new TextStyle `MONEY_WINDOW`. Currently the default style for Money is a pale yellow in both themes. That doesn't work when the money has to be displayed in a game window since the themes have different colored windows (dark in default theme, white in legacy theme)
- …
=> [UI] Make ME text legible when using the legacy UI theme

src/field/pokemon.ts, src/modifier/modifier.ts, src/test/abilities/parental_bond.test.ts, src/test/items/multi_lens.test.ts
Multi Lens will apply proper damage reduction to fixed-damage moves.
Affected moves: Sonic Boom, Dragon Rage, Super Fang, Nature's Madness, Ruination, Counter, Mirror Coat, Metal Burst, Comeuppance, Seismic Toss, Night Shade, Psywave.
**Note**: This implementation technically causes `TargetHalfHpDamageAttr` (e.g. Super Fang) to deal slightly less damage if used with Multi Lens.
With 1 Multi Lens, the damage dealt is around 45% (1 - 0.625 * 0.875) of the target's HP.
With 2 Multi Lens, the damage dealt is around 43% (1 - 0.75 * 0.875 * 0.875) of the target's HP.
Requested by balance, due to recent Multi Lens changes now allowing Multi Lens to activate on fixed-damage moves.
1. `PokemonMultiHitModifier` now gets applied to fixed-damage moves.
2. Rewrote `PokemonMultiHitModifier` slightly to …
=> [Balance] Multi Lens damage reduction on fixed-damage moves

src/data/ability.ts
Bug Reported by @PigeonBar 
Video Provided: 
https://github.com/user-attachments/assets/85dbe724-3b7a-4125-b020-e0eeae6c5c9b
Conditional changed from AND to OR. 
1. Fight a boss with Wimp Out/Wimp Out Sr. 
2. The boss should not flee when it hits the activation threshold for the ability.
=> [Bug][P1] Wave 10x Boss Pokemon can no longer flee battles with Wimp Out 

src/field/pokemon.ts
No crash when an arena tag is up and a Pokemon is caught and replaces a Pokemon that was on the field
Closes #4886 
During the fight Imprison is put up, and at the end of the fight the game tries to clear it by calling `removeTag` on Pokemon on the field.
If one of the party members turns out to be a new catch it doesn't have summonData so the game crashes when attempting to access its tags
- Add null check for summonData in `removeTag` and `lapseTags`, which were the last tag-related functions that didn't have it
- Replaced the check in `lapseTag` for style consistency with all other checks
Before:
After: next wave reached properly
Save file [sessionData_jopenmolles.txt](https://github.com/user-attachments/files/17788066/sessionData_jopenmolles.txt)
- Defeat Gholdengo with Arcanine's …
=> [P1] Fix crash caused by removing arena tags on a new catch

package-lock.json, package.json, src/field/pokemon.ts, src/phases/move-effect-phase.ts
The game will no longer crash if a Pokémon that used Future Sight is caught.
Bug report: https://discord.com/channels/1125469663833370665/1307871092261523567
If the user of the move in `MoveEffectPhase` has no turn data and it's a delayed attack (ie: Future Sight), initialize it.
`Pokemon.pushMoveHistory()` checks if the Pokémon is on the field and returns early if it isn't.
https://github.com/user-attachments/assets/c75e426f-fe86-4e02-9933-290f0a4253ac
Use these overrides and start a new run. Stall the first turn so the enemy Pokémon uses Future Sight, then catch it the next turn. In the following turn, do whatever, and get hit by the Future Sight attack. At this point the game should continue on as normal instead of crashing.
```ts
OPP_MOVESET_OVERRIDE: …
```
=> [Hotfix] Prevent crash if enemy Future Sight user is caught

package-lock.json, package.json, src/phases/move-effect-phase.ts
Catching and releasing a Pokemon that used Future Sight on the turn FS was supposed to trigger will no longer freeze the game.
[Discord bug report](https://discord.com/channels/1125469663833370665/1307871092261523567/1308031755420434453)
At the moment FS goes through a move effect phase so it expects the user Pokemon to be around to perform hit checks and other things. For a Pokemon that was caught and released the turn FS would hit a lot of its attributes are gone at this point, causing the checks to crash the game.
One of the undefined attributes is the Pokemon's scene reference, which should get solved in the future with PR #4766 
So hopefully this will just resolve itself with that in the future
As FS is still P and I'm not entirely sure that it should go through hit checks and …
=> [Hotfix] Prevent Future Sight crash with new catches, attempt 2

src/data/egg.ts
Regional forms will no longer appear less often from eggs.
Requested by balance.
damo edit: (to go with #4883)
Removed the "regional" check from egg creation.
=> [Balance] Remove reduced weight for regional species from egg pulls

src/data/ability.ts
Players should once again see Intrepid Sword / Dauntless shield activate multiple times in a battle
The abilities were bugged to work as their Gen 8 variants until the Nov. 17th update that fixed the bug. With Zacian and Zamazenta receiving stat nerfs and multiple Pokemon having it as their passive, it was in an acceptable state to keep in the game so it was decided with Damo's approval to make them their Gen 8 variants as we did other abilities such as Protean. Another thing is the description of the abilities were using the Gen 8 description which does not align with their current implementation so it saves localization team the trouble!
Removed getOncePerBattleCondition from both Intrepid Sword and Dauntless Shield
Overrides
=> [Balance] Make Intrepid Sword / Dauntless Shield their Generation 8 Implementation

src/data/ability.ts
> [!IMPORTANT]
> This balance change requires adjustments to Supersweet Syrup's description and therefore requires Senior Translator approval. The corresponding locale changes are available at https://github.com/pagefaultgames/pokerogue-locales/pull/53
Supersweet Syrup should now activate whenever the source enters the field, not just on the first time in battle.
This was discussed alongside reverting Intrepid Sword and Dauntless Shield to their Gen 8 implementations (see #4902). The once-per-battle condition on Supersweet Syrup is widely lamented even outside of this game, and the Hydrapple line deserves some love.
- `data/ability`: Removed `getOncePerBattleCondition()` from Supersweet Syrup. 
1. Using overrides, give your Pokemon Supersweet Syrup.
2. In battle, switching your Pokemon …
=> [Balance][Ability] Remove Supersweet Syrup's once-per-battle condition

src/data/move.ts
Rage Fist will now be marked "(P)".
> Rage Fist should be marked P in accordance with Balance's Decision on Last Respects, Supreme Overlord, that it should not be resetting per wave as it does currently
- https://github.com/pagefaultgames/pokerogue/issues/3503#issuecomment-2480913593
Added `.partial() // Counter resets every wave instead of on arena reset` to Rage Fist.
=> [Misc] Mark Rage Fist as partial in line with similar moves/abilities

src/data/ability.ts, src/test/abilities/analytic.test.ts
In doubles, Analytic will no longer erroneously boost damage if the target moves before the user and the other Pokémon have not.
Move is bugged, see https://github.com/pagefaultgames/pokerogue/issues/3503#issuecomment-2484728852
The condition function for Analytic is changed.
Tests were added for Analytic.
`npm run test analytic`
- ~[ ] Have I tested the changes manually?~
=> [Bug] Analytic should only increase damage if the user moves last

src/battle-scene.ts, src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts, src/overrides.ts, src/phases/trainer-victory-phase.ts, src/system/achv.ts
> [!IMPORTANT]
> This PR introduces changes that require updates to existing locales, and therefore requires Senior Translator approval.
The "Breeders in Space" achievement will also unlock when beating normal breeders while in the Space biome
Asked by balance. The odds of encountering the Expert Pokemon Breeder while in space are too low and make the achievement unrewarding
Achievement description locale update PR: https://github.com/pagefaultgames/pokerogue-locales/pull/55
- Remove the achievement check from the Expert Breeder Encounter
- Put the check in `TrainerVictoryPhase` just after the Voucher checks for boss trainers
- Added an override to allow achievements to trigger even if they were already unlocked, for easier testing
<details><summary>new english achievement …
=> [Balance] 'Breeders in Space' cheevo unlocks for normal and expert breeders

src/data/ability.ts, src/phases/switch-summon-phase.ts
Can now use Fake Out/First Impression if forced out
This is a reported bug: https://discord.com/channels/1125469663833370665/1308989093048225902/1308989093048225902
Added another `||` where `pokemon.battleSummonData.turnCount` and `pokemon.battleSummonData.waveTurnCount` are decremented for moves like U-Turn. It checks if the last pokemon has the `PostDamageForceSwitchAbAttr` ability attribute and that they are not fainted
https://github.com/user-attachments/assets/4ee16808-534b-4dd4-8b2f-0391f67d481a
Use Fake Out after being forced out due to Wimp Out on turn 1
=> [Bug] Fixed First Turn Move + Wimp Out interaction

src/test/moves/shell_side_arm.test.ts
N/A
The test has a chance to fail.
Added a second turn so the enemy Pokémon gets to +6 def, to guarantee that Def > SpDef.
`npm run test shell_side_arm`
- ~[ ] Have I tested the changes manually?~
=> [Test] Fix flaky Shell Side Arm test

src/phases/egg-lapse-phase.ts
- If the egg skip option is set to "Ask", the prompt will say how many eggs are about to hatch
- Small QoL
- The user might decide differently if they know only 6 eggs are hatching rather than 20
- This PR simply passes the `eggsToHatchCount` variable from `EggLapsePhase` as an argument when the `eggSkipPrompt` locale entry is called, as `eggsToHatch`
- Add `{{eggsToHatch}}` somewhere in the `eggSkipPrompt` entry in a `battle.json` translation file, or check out the linked translation PR
- Implemented in [PR-locale PR#56](https://github.com/pagefaultgames/pokerogue-locales/pull/56)
=> [UI/UX][QOL] Add number of eggs hatching to egg skip prompt

src/data/move.ts, src/test/moves/dragon_tail.test.ts, src/test/moves/whirlwind.test.ts
Phazing moves can no longer randomly choose to force a switch into a fainted/ineligible Pokemon.
Also, phazing moves properly use seeded RNG instead of unseeded RNG.
Bug report: [Discord](https://discord.com/channels/1125469663833370665/1176874654015684739/1312149844797685820)
1. Phazing moves now generate a list of indices of eligible Pokemon to switch into, and then randomly pick an eligible index using seeded RNG.
2. Added tests for Whirlwind and Dragon Tail.
<details>
<summary> Before the changes: Phazing moves can force a switch into a fainted Pokemon </summary>
https://github.com/user-attachments/assets/400bf42b-657b-44fc-ad84-ac7f7a96825f
</details>
<details>
<summary> After the changes: Phazing moves no longer force a switch into a fainted Pokemon </summary> …
=> [P1][Beta] Fix phazing moves forcing switches into fainted/ineligible Pokemon

src/ui/starter-select-ui-handler.ts
Players will see no changes.
Was messing around with a forced party size restriction and realized the value wasn't being used consistently. 
Replaces hardcoded value with `PLAYER_PARTY_MAX_SIZE` constant. 
=> [Refactor] Replace hardcoded party size limit with constant `PLAYER_PARTY_MAX_SIZE`

src/data/ability.ts, src/data/pokemon-forms.ts, src/modifier/modifier.ts, src/test/abilities/serene_grace.test.ts, src/test/abilities/sheer_force.test.ts
If Meloetta happens to have the ability Sheer Force when using Relic Song, she does not transform.  
Serene Grace does not affect King's Rock proc chance anymore (Balance decision).
Shareholder value up!
Conditionals added to MeloettaFormChangePostMoveTrigger that check for Sheer Force. Tests also added. Serene Grace and Sheer Force tests modernized.
1. Use Relic Song with a Meloetta that has the ability Sheer Force
=> [Ability] Fully implement Sheer Force

src/test/abilities/serene_grace.test.ts
None.
My fault. I did not think a Level 5 Shuckle could knock out a Level 10 Biome.TOWN pokemon.
EnemySpecies given a neutral ability, a 4x resistant typing to Flying, and critical hits are disabled. 
npm run test serene_Grace
=> [Test] Added additional safeguards to prevent Serene Grace test flakiness

src/field/pokemon.ts, src/modifier/modifier-type.ts
`Flame Orb` and `Toxic Orb` have had their weight functions adjusted such that they only appear in item reward rolls under the following specific conditions:
- A Pokemon in the party does not already have either orb *AND*...
-  Can be afflicted by the respective status effect *AND*...
- Has any of the relevant abilities or moves that take advantage of obtaining either status effect
- Moves: `Facade` and `Psycho Shift`
- Abilities for `Toxic Orb`: `Quick Feet`, `Guts`, `Marvel Scale`, `Toxic Boost`, `Poison Heal`, and `Magic Guard`
- Abilities for `Flame Orb`: `Quick Feet`, `Guts`, `Marvel Scale`, `Flare Boost`, and `Magic Guard`
- Can not be afflicted by the respective status effect *AND*...
- Has any of the relevant item-switching or -throwing moves that take advantage of holding either …
=> [Balance] Adjust Flame/Toxic Orb Weight Functions

src/data/move.ts, src/phases/move-effect-phase.ts, src/test/abilities/parental_bond.test.ts, src/test/items/multi_lens.test.ts
If a Pokemon with Multi Lens and/or Parental Bond uses Future Sight and then switches out, Future Sight will no longer hit infinitely many times.
<sup>(Technically, according to Bulbapedia, held items and abilities should not be applying at all if the Future Sight user has switched out. But that's a fix for another day)</sup>
Bug report: [Discord](https://discord.com/channels/1125469663833370665/1313094152585613312)
1. `MoveEffectPhase` now resets the attacker`s turn data only if the turn data is undefined. This means that if Future Sight gets used as a multi-hit move, the attacker's turn data no longer gets reset during extra hits, so the game can properly keep track of the number of Future Sight hits.
2. Added unit tests.
3. Updated `.partial()` tags for Future Sight and Doom Desire, …
=> [P1 Bug] Fix multi lens granting infinite Future Sight hits

src/timed-event-manager.ts
If you not play in English and if a translation is available, so the event timer will display in the right language
To have it opened to translation
None
Example in French:
Set an Event in src/timed-event-manager covering you current date to display the timer and then play with the locales
=> [Localization] Localizable Event Timer

CREDITS.md
```diff
diff --git "a/CREDITS.md" "b/CREDITS.md"
index 0fe0a8dc2..9a75020 100644
--- "a/CREDITS.md"
+++ "b/CREDITS.md"
@@ -615,6 +615,6 @@ In addition to the lists below, please check [the PokéRogue wiki](https://wiki.
- roi
-- Ydarissep (RogueDex)
+- Ydarissep (creator of the now defunct "Yda's Dex")
- Admiral-Billy (Offline App - Desktop)
- Red aka StonedModder (iOS App)
```
=> [Misc] Update "Yda's Dex" credit (the tool is now gone)

src/ui/party-ui-handler.ts
If not playing in English, so "Able" and "Not able" when Tranfering an item will be translated
To have these texts translated
None
**Before (French)**
**After (French)**
Play the game not in English an try to transfer an item between waves
Are there any localization additions or changes?
- Already translated, was just missing in this context
=> [Localization] Missing localized "Able" & "Not able" in Transfer option

src/modifier/modifier-type.ts
- TMs won't spawn for mons that can learn the move with a memory mushroom
- Reduces redundancy in TM spawns
- Makes TMs more satisfying to find if they're not just giving you Disarming Voice that you learn at level 6 anyway
- Checks learnable level moves of party members in `TmModifierTypeGenerator`
Before: Level 100 Fuecoco gets TM Snarl, despite learning it at level 21
After (same wave seed): Level 100 Fuecoco gets different TMs offered
=> [Balance] Check previous level moves for redundancy when spawning TMs

src/battle-scene.ts, src/battle.ts, src/data/mystery-encounters/encounters/global-trade-system-encounter.ts, src/system/settings/settings.ts
Music settings options changed from "Consistent/Mixed" to "Gen V + PMD/All Gens".
The existing labels don't tell the user what they do, leading to confusion.
New i18n keys created in `settings.json`: `musicGenFive` and `musicAllGens`.
Labels changed in `settings.ts` to use the new keys.
=> [UI/UX] Change label for music settings

package-lock.json, package.json, src/data/pokemon-forms.ts
Keldeo will no longer be able to change forms in Daily Run mode, preventing a crash.
The game crashes if the player has Keldeo in their starting party in Daily Run mode.
A condition was added to Keldeo's form changes that checks if the mode is Daily Run and prevents the form change if so.
=> [Hotfix] Prevent Keldeo from changing forms in Daily Run

src/battle-scene.ts
Gimmighoul and Eevee eggs will no longer hatch differently depending on what game mode you're playing in when they hatch.
Fixes #5079 
`BattleScene.getSpeciesFormIndex()` added checks for `EggLapsePhase` when selecting the form to generate for Gimmighoul and Eevee.
<details>
<summary>Fixed behavior</summary>
https://github.com/user-attachments/assets/0a2c3319-bff8-4da7-8bc9-f3c3cd4f346d
</details>
Buy a bunch of Gimmighoul species eggs and hatch them during a Classic run. Some of them should be Chest form.
=> [Bug] Gimmighoul and Eevee eggs will now properly randomize their forms

src/modifier/modifier-type.ts
See #5102 for reproducing the bug. With this fix Daily Mode always has Catching Charm at weight 4, regardless of account progress and if you follow the actions in the issue, you should always see a Catching Charm in the shop.
=> [Bug] fix #5102 Catching Charm now always max weight in Daily Mode

src/data/move.ts, src/test/moves/defog.test.ts
Defog will now successfully remove the Safeguard and Mist from the target side.
Fixes https://github.com/pagefaultgames/pokerogue/issues/5086.
~~Added `RemoveSafeguard` and `RemoveMist` classes to `moves.ts`, and has them be called by Defog with both sides set to false.~~ Used `RemoveArenaTagsAttr` for Defog in `moves.ts`. Added `defog.test.ts` as well.
Using defog on an enemy who has Safeguard or Mist active would verify the changes work.
=> [Bug] Fixed defog not removing the target's Safeguard and Mist

src/data/move.ts
Changed behavior of multi-hit moves so that the odds are 35/35/15/15 for 2/3/4/5 hits (gen 5+) instead of 37.5/37.5/12.5/12.5 for 2/3/4/5 hits (gen 1-4).
cf https://bulbapedia.bulbagarden.net/wiki/Multistrike_move#Variable_number_of_strikes
Multi-hit moves don't need to be that bad.
The game now rolls a d20 and assigns the number of hits as follows:
| # rolled | # of hits |
| -------- | --------- |
| 0, 1, 2  | 5         |
| 3, 4, 5  | 4         |
| 6-12     | 3         |
| 13-19    | 2         |
=> [Balance] Multi-hit moves now use gen 5+ behavior

src/battle-scene.ts, src/data/daily-run.ts, src/game-mode.ts
Endless now allows random traverse (random biome from End at every 50th wave) to Island and Laboratory. Also fixed the off by one error that led to the weights not being accurate with the results.
Daily mode now has its own function to get a random biome for its starting biome. It also now uses a custom weight table approved by the Balance Team:
This table is weighted higher for biomes that have a lot of exit paths or lead to a large amount of final paths in general.
It is simply not fun to have biomes be unavailable when there is no balance reason to have them be unavailable. And Daily Mode had no business using a function that was balanced around having 250+ waves.
Another list with biome weights. Which means it would have to be included in the biome rework as well. It is still useful …
=> [Balance] Fix off by one error in Generate random biome and Daily Mode now has its own function

src/battle-scene.ts
N/A
Accidentally replaced `this` with `globalScene` in `BattleScene` before.
Restored usage of `this` in `BattleScene`.
=> [Misc] Replace `globalScene` with `this` in `BattleScene`

src/overrides.ts
N/A
Convenience for people testing with overrides.
ESLint won't enforce type-only imports in `overrides.ts`.
=> [Misc] Disable enforced type-only imports in `overrides.ts`

src/field/pokemon.ts, src/test/data/status_effect.test.ts, src/utils.ts
A Pokémon will no longer be able to be statused if it has 0 HP (aka: is fainted).
Fixes #3585 
`Pokemon.canSetStatus()` now returns `false` if the Pokémon has 0 HP.
`npm run test status_effect`
=> [Bug] Prevent pokemon with 0 HP from being statused

src/modifier/modifier.ts
Miniblackhole will actually work as intended.
Miniblackhole accidentally used the wrong variable name at one point so was working incorrectly.
Slightly changed mbh code.
This is difficult to show because it's a slight change to the randomisation method.
Overrides to give yourself leftovers and a bunch of berries and the opponent miniblackhole, repeatedly start and play runs and it should consistently prefer leftovers to berries.
=> [Bug] Fix miniblackhole

src/modifier/modifier.ts
Reverts pagefaultgames/pokerogue#5169
=> Revert "[Bug] Fix miniblackhole"

src/ui/menu-ui-handler.ts
Users will be able to access the egg list screen from the post battle rewards screen
See #5160 for rationale. I understand why the egg gacha was made inaccessible after an encounter ends, but I believe the egg list screen does not cause any of the same problems and we can safely let people look at their eggs from there.
Excluded menu options for the post battle screen reduced by one.
Win a battle, open the menu.
=> [UI/UX] Allow viewing egg list from rewards screen

package-lock.json, package.json, src/data/mystery-encounters/utils/encounter-phase-utils.ts
Event encounters can now evolve... again
Version bumped to 1.5.2
#5099 checks "blockEvolutions" backwards- it checks that it's not null or undefined. So event encounters weren't evolving.
!isNullOrUndefined(eventEncounter.blockEvolution) -> !eventEncounter.blockEvolution for "allowEvolution" parameter
Before
After
Overrides:
```  MYSTERY_ENCOUNTER_RATE_OVERRIDE: 256,
MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.BERRIES_ABOUND,
STARTING_LEVEL_OVERRIDE: 1000,
STARTING_WAVE_OVERRIDE: 101,
STARTING_BIOME_OVERRIDE: Biome.PLAINS,
SEED_OVERRIDE: "Q9Jun9DCTjUgudOuiOn0Ze1W"
```
=> [Hotfix] Fix blockEvolutions being checked wrong

src/data/move.ts
Healing Wish and Lunar Dance were only checking the player's party to decide how much HP should be healed. As a result, this could lead to very rare scenarios where the opponent using Healing Wish or Lunar Dance would not heal all of their HP. This PR fixes that.
Bugfix.
SacrificialFullRestoreAttr now checks which side is using Healing Wish/Lunar Dance before taking the max HP.
<p>
https://github.com/user-attachments/assets/b01ad5dd-3ba2-48d9-8b3d-3082530d8be7
</p>
</details>
<p>
https://github.com/user-attachments/assets/d1d95bd2-6294-442f-a0be-5599ca41fe0a
</p>
</details> 
Due to the very specific circumstances this bug takes to occur, reproduction was difficult. Here's what I did:
- Set Rival 1's team to Blissey + …
=> [Bug][Move] Opponent's Healing Wish/Lunar Dance now checks opponent's party

src/data/ability.ts, src/test/abilities/shields_down.test.ts
Defeating an enemy trainer that has a minior will no longer cause the game to softlock.
There was a bug report for it on the discord.  
Also it's embarassing for my first PR to have triggered a bug. <sup>Please merge quickly so we can hide the evidence 😅</sup>
In`src/data/abilities.ts/`: added a condition inside `PreSetStatusEffectImmunityAbAttr` 's `applyPreSetStatus` method that prevents the status effect from being cancelled if it is `StatusEffect.FAINT`.
Added a unit test to detect this scenario in `src/test/abilities/shields_down.test.ts`.
<details><summary>Current beta branch</summary>
https://github.com/user-attachments/assets/321ada4c-89f9-4e24-beed-5bd316bbbd4b
</details>
<details><summary>With this PR</summary>
https://github.com/user-attachments/assets/848cef8b-df64-49b7-8bfa-1c …
=> [Bug] Fix softlock caused by shields down

package.json, src/data/move.ts, tsconfig.json
N/A
Prevents annoyances with auto-imports.
VSCode will no longer append `.js` to auto-imports.
`#enums` should now be recognized as a valid import shortcut by VSCode (instead of using `#app/enums`).
=> [Misc] Prevent auto-imports from appending `.js` to imports

package-lock.json, package.json, src/ui/title-ui-handler.ts
Displaying a message on the title page with starting and ending times (as dynamic dates) of the maintenance.
This is to warn users who don't have access or simply do not follow the discord.
Localization is needed. Localized strings will be directly added to `title-ui-handler.ts` without passing through locales.
Screenshots:
<details><summary>English</summary>
<p>
</p>
</details> 
<details><summary>Spanish</summary>
<p>
</p>
</details> 
<details><summary>Italian</summary>
<p>
</p>
</details> 
<details><summary>French</summary>
<p>
</p>
</details> 
<details><summary>German</summary>
<p>
</p>
</details> 
<details><summary>Portugese (missing)</summary>
<p>
</p>
</details> 
<details><summary>Chinese - Simplified</summary>
<p>
</p>
</details> 
<details><summary>Chinese - Traditional</summary> …
=> [Hotfix] Adding warning message for the maintenance

src/data/move.ts
Bouncy Bubble will now properly function like it's (unused) SWSH data - now only targets a single Pokémon, and heals 100% of the damage.
The existing data was inconsistent with both the LGPE and SWSH implementations, mostly due to getting information from (at the time) incorrect sources.
Removed the targeting tag (making it single target only), and increased the hit heal ratio from 50% to 100%.
N/A
Use Bouncy Bubble against targets, see that it can target anything and heals more.
=> [Bug] [Balance] Fix Bouncy Bubble being a spread move, revert back to 100% drain effect

src/data/battler-tags.ts, src/field/pokemon.ts, src/test/moves/telekinesis.test.ts
Most likely none at all. But mega gengar can no longer be baton passed the effect of telekinesis.
Because I was reading code and saw a comment saying this interaction wasn't handled, and knew it would be a one-line fix.
Also because no matter how insignificant the change, I am obsessed with matching cartridge functionality.
Added an automated test to telekinesis' unit tests for this interaction.
Inside of `pokemon`'s `transferSummon` method where it checks if a tag is baton passable, add a check if the tag is telekinesis and the pokemon is mega gengar.
This is too niche. Just run the tests :)
```
npx vitest run src/test/moves/telekinesis.test.ts -t "should not be baton passed onto a mega gengar"
```
- ~~[ ] Have I made sure that any UI change works for both UI themes (default and …
=> [Move] [Bug] Fix super-niche edgecase with mega gengar and telekinesis

src/test/sprites/pokemonSprite.test.ts
N/A
The sprite check test didn't give helpful error messages when something was wrong, now it will.
Changed the `expect()`s to go from checking the length of the error message array to checking that it equals an empty array, which makes it output the error message array to the console if it's not empty.
`npm run test pokemonSprite` after breaking something
=> [Test] Update sprite test to give more useful error messages

eslint.config.js, src/test/abilities/shield_dust.test.ts, src/test/abilities/unseen_fist.test.ts, src/test/data/status_effect.test.ts, src/test/evolution.test.ts, src/test/items/light_ball.test.ts, src/test/items/metal_powder.test.ts, src/test/items/quick_powder.test.ts, src/test/items/thick_club.test.ts, src/test/moves/dragon_rage.test.ts, src/test/moves/fissure.test.ts, src/test/moves/toxic_spikes.test.ts, src/test/mystery-encounter/mystery-encounter-utils.test.ts, src/test/ui/transfer-item.test.ts
N/A
To prevent mistakes in tests from forgotten `await`s.
ESLint will display an error if a promise is misused (ie: an `await` is forgotten, such as someone writing `game.classicMode.startBattle();` instead of `await game.classicMode.startBattle();`). This will reduce mistakes in test writing.
=> [Test] Add eslint rule enforcing proper `await` usage in tests

src/data/mystery-encounters/encounters/safari-zone-encounter.ts, src/modifier/modifier.ts, src/phases/encounter-phase.ts, src/phases/mystery-encounter-phases.ts, src/phases/scan-ivs-phase.ts, src/ui/battle-message-ui-handler.ts
- IV Scanner has max stack of 1 instead of 3
- All 6 IVs will be shown with a single IV Scanner
- Removes the animation when using IV Scanner
- IV Scanner kind of sucks and bloats the Ultra pool. The idea behind it stacking to 3 would be nice if the information it provides was useful, but it's really not.
- Changes max stack count of IV Scanner to 1
- Changes logic for IV Scanner uses to just show all the IVs rather than selecting random ones
- Load a save with 2 or 3 IV Scanners
- Use it
=> [Balance] Change IV Scanner to single stack

src/ui/pokedex-ui-handler.ts
When scrolling thorugh pokémon in the main page of the dex, or opening the form tray, the form label is shown over the name.
This is a cosmetic change that makes the dex experience more pleasant by spelling out what form the user is looking at.
Added one extra text element in pokedex-ui-handler.ts, leveraging the form label logic from #5294 .
In the comments.
Simply open the dex and scroll through.
=> [UI/UX] Show form name on main screen in dex

src/data/pokemon-species.ts, src/ui/pokedex-page-ui-handler.ts, src/ui/pokedex-ui-handler.ts
* Form names are displayed properly
* Form types are shown correctly when scrolling through the tray
* Unobtainable forms are not shown
Added a new isUnobtainable attribute in PokemonForm which can be checked by the dex, so far given to forms of Marshadow, Arceus, Ploteageist and its prevolution.
=> [UI/UX] Fix showing form names and types

index.css, src/data/pokemon-species.ts, src/ui/filter-text.ts, src/ui/pokedex-page-ui-handler.ts, src/ui/pokedex-scan-ui-handler.ts, src/ui/pokedex-ui-handler.ts
Important bug fixes:
- A game-breaking bug that allowed to buy eggs of evolved species from the dex has been fixed.
- Move filters work properly, without crashing when finding egg moves
- Level up moves are displayed correctly for alternate forms
- In case that a save has unobtainable unlocks for evolutions, they are filtered out.
UI/UX fixes:
- The Pokédex buttons now show up as expected on the mobile touchpad
- The filter text now only allow values that can be selected (pokémon, move or ability names) and other selections simply return the default "---".
- When opening a filter text, the cursor goes to the input text without requiring a mouse click.
- Shinyness is maintained when turning pages (this had broken when changing the function of the shiny button).
Visual fixes:
- Fixed a …
=> [Bug][UI/UX] Dex bug fixes 12 feb

src/data/ability.ts
The ( P ) designation is now removed from Quark Drive and Protosynthesis, as #5254 was merged.
There are no GitHub issues mentioning Quark Drive or Prosoynthesis to warrant the (P) designation staying.
The more things without the (P)  and (N) designations, the better. It makes the game feel more complete.
Remove `.partial()` in `src/data/moves.ts` from Quark Drive and Protosynthesis.
<details><summary>before</summary>
</details>
<details><summary>after</summary>
</details>
Look at a mon with quark drive and observe that it no longer has (P) on it.
~~Are there any localization …
=> [Ability][Bug] Remove `partial` designation from Quark Drive and Protosynthesis

package-lock.json, package.json, src/data/pokemon-species.ts
All caught forms are displayed and their data can be accessed.
There was a bug where all forms except the default one would be marked as uncaught. This is now fixed.
The `getFullUnlocksData` function (introduced to filter out impossible unlocks from old save data) was not taking into account the contribution to the `DexAttr.caughtData` bigint from caught forms. This is fixed by looping over forms and adding incremental contributions.
Showing that forms are displayed properly with the hotfix:
=> [Bug][Hotfix] Display caught forms in dex as intended

package-lock.json, package.json, src/data/pokemon-species.ts
Previous hotfix accidentally made all Pokémon without forms show up as uncaught.
This is now fixed by adding the default form to `caughtAttr` again when there are no forms.
=> [Bug][Hotfix] Show caught pokemon correctly

package-lock.json, package.json, src/field/pokemon.ts, src/test/field/pokemon.test.ts
Fusions work as normal again, allowing dual type + monotype with shared primary type to use the first pokemons dual typing.
#5229 accidentally broke this.
Fuse something like pidgey + rattata.
=> [Bug][Hotfix] Fix fusion with dual type + monotype with shared primary type.

src/ui/pokedex-ui-handler.ts
For Pokemon like Roaring Moon the sprite will no longer block the pokemon name
I find it important that the pokemon name is always visible in a pokedex. 
I brought the pokemon name element and the pokemon form text element to the top (over the sprite element)
Before:
After:
Easiest is to play in german, open pokedex, go to roaring moon
=> [QOL] Make the name and formName readable for bigger sprites in pokedex

src/ui/pokedex-ui-handler.ts
Cost reduction filter in the dex works the same as in the starter selection screen.
The filter had been implemented, but the labels in the dropdown had not been updated accordingly, meaning that two options could not be selected.
Added missing label entried to the dropdown. The entries are already in the starter select screen so no locales changes are needed.
https://github.com/user-attachments/assets/e29e2ba7-a663-4e5b-be64-cdbd0cc0d902
=> [Bug][UI/UX] Setting proper labels in cost reduction dropdown filter

src/data/challenge.ts
- Nothing (I hope)
- Starter select used to be separated by gens. Gen 5 has one mon too many to fit on a single screen, so Victini was bumped to gen 4. Monogen challenge had a check for whether a mon in battle is Victini, so it could be considered Gen 5.
- Now that Victini isn't gen 4 anymore, that check can be removed.
- Removes Victini species id check in applyPokemonInBattle for monogen challenge.
This is a gen 5 challenge. Victini is still usable.
=> [Refactor] Remove outdated Victini check for monogen challenge

src/data/trainer-config.ts, src/modifier/modifier-type.ts
Tera Orb will now be given by your rival after the Wave 95 fight, it can no longer be found in Classic's item pool but will appear as normal in Daily / Endless.
With Tera Rework added, we wanted to integrate terastalization as a core mechanic to Pokerogue seeing as it is a gimmick used by many of the important trainers in a run such as your Rival, Gym Leaders, Elite 4, and Champions. It is given to you by your rival as this is the first fight they start using terastalization against you, and is a neat reference to mainline where your rival also gives you the Tera Orb to use. 
Tera Orb added as a reward modifier for RIVAL_4
Tera Orb removed from Classic's item pool
Rival giving you a Tera Orb after being defeated.
Tera Orb still spawning in an Endless save.
Overrides
Are there any …
=> [Balance] Guarantee Tera Orb as a reward from Rival 4, Remove it from Classic Item Pool

src/ui/starter-select-ui-handler.ts
No Nature informations text going out of the textbox on the starter select screen in Spanish
To have something visually pleasing
None
BEFORE
AFTER
Go on the starter select screen in Spanish and cycle Natures
=> [UX/UI] Update Starter Select Screen Spanish text size

src/ui/settings/move-touch-controls-handler.ts
Touch controls configuration now translatable
To have it translatable
None
BEFORE (French):
AFTER (French):
Play on a device with a touch screen and try to reconfigure the position of the touch controls via the Game Settings
=> [Localization] Move Touch controls Localization

src/battle-scene.ts
The message that tells you an item was generated that exceeds the item stack cap has been converted to free Pokeballs is now changed to be on a delay (3 seconds chosen). This prevents the bug where players could not start their Daily Run because the message was stuck in a phase limbo and would ignore all inputs.
Fixing the actual phase/ui handlers would require dev time from someone more familiar with the ui handlers. Fixing that it doesnt exceed item stack is kind of a re-balance and sometimes its really nice to start with extra poke balls. So a fix to just let the message auto complete seems like a better way to 'hotfix' this.
This issue happens roughly once every two weeks in Daily Runs. And causes a lot of players to think the Daily Run for that day is just broken and dont play it.
It …
=> [Bug] Changes Daily Run item stack full message to a delay

src/modifier/modifier-type.ts
`Flame Orb` should not longer get pushed if there is, for example, only a Pokémon who cannot get burned in the party.
This was a mistake introduced in #5070; it was not intended that `canSetStatus` within `Flame Orb`'s weight function would be determined on whether the current Pokémon could be inflicted with `Toxic`.
Switches `StatusEffect.TOXIC` in `Flame Orb`'s weight function to `StatusEffect.BURN`.
N/A
The same testing instructions from #5070 can be used here.
- ~[ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?~
Are there any localization additions or …
=> [Bug/Item] Fix Flame Orb Weight Function

src/ui/settings/move-touch-controls-handler.ts
None
Another key name "reset" already existed in the same locale file, so I renamed some keys related to touch controls
None
Play on a device with a touch screen and try to reconfigure the position of the touch controls via the Game Settings
=> [Localization] Corrections move-touch-controls-handler local key names

src/data/ability.ts, src/modifier/modifier.ts, src/test/battle/damage_calculation.test.ts
Attacks can no longer deal 0 damage (unless they are specifically supposed to e.g. through endure).
This has been requested, and balance team specifically said that tokens should not prevent attacks from doing at least 1 damage. This is also how it works in mainline games.
**By the way** Most damage calculations actually *weren't* rounding to 0, as they were properly using the utils methd `toDmgValue` which computes the floor and min together. However, a few places were incorrectly *not* using this when they should have been, and were instead just calling `min`.
In several places where damage multipliers were erroneously calculated using `Math.min`, they are now calculated using `Utils.toDmgValue`.
<details><summary>Current live</summary> …
=> [Bug] Fix endless tokens allowing attacks to deal 0 damage

src/phases/encounter-phase.ts
N/A
Additional logging when playing on beta or locally for use in development.
At the start of an encounter, more of the enemy pokemon's information will be output to the console.
<details><summary>An example team from wave 195</summary>
<p>
</p>
</details> 
Start any wave and look at the console output.
=> [Misc] Update console logging of encounter pokemon on beta/local

src/ui/pokedex-page-ui-handler.ts
When looking at level up moves in the Pokédex, messages give more information.
Moves learnt on evolution ("lv 0") and only by recall ("lv -1") were not properly explained.
=> [UI/UX] Pokédex - Informative messages for level up moves

src/ui/pokedex-page-ui-handler.ts
BGM flyout will reappear in the menu. 
It wasn't appearing.
The pokedex had created a duplicate bgm bar that was never shown and was overriding the global ui handler to point to it. This was causing the actual bgm bar in the menu to never have its text updated, so it was never appearing.
Open the pause menu with and without this patch.
=> [Bug][UI] Fix bgm bar

src/data/pokemon-species.ts
Giratina swapping between Altered and Origin form with its' Hidden Ability Telepathy, will now properly gain it back when reverting from Origin form.
Closes #5041 
Hidden Ability for Origin Form Giratina
Swap from Altered Giratina with Telepathy -> Origin then back.
=> [Bug] Giratina no longer loses its' Hidden Ability going from Origin back to Altered Form

src/ui/abstact-option-select-ui-handler.ts
Confirm options with a delay show up as grey text for the duration of the delay, again.
This was the behavior before #5083. The changes to the option select ui handler in that PR included a shift to BBCodeText objects. An unwanted consequence of this is that, since BBCodeText objects do not support a setAlpha() method, the method previously used to turn the text grey temporarily does not work anymore.
See bug report [here](https://discord.com/channels/1125469663833370665/1342697356331847802) and [here](https://discord.com/channels/1125469663833370665/1338544047597555772).
The BBCodeText object is wrapped in a new container, and the setAlpha() method of the container is called instead.
https://github.com/user-attachments/assets/70f6d4e3-e560-4f90-a3c1-0636626af648
Start a new run, try to …
=> [UI/UX] Text is grey again in delay confirm option menu

src/data/move.ts
Splash and Celebrate will now have their unique flavor text when used.
I saw that another PR, #5340 , was trying to do the same thing with Splash, albeit through a much more unnecessarily complex method. So I simplified it, and included Celebrate as well, since they are both equally useless moves with unique text.
Creates two attributes for Splash and Celebrate, which simply displays the relevant text. Relocates the existing localized Splash message from the battler tags to the move triggers. Celebrate uses your account name when congratulating the player.
(Celebrate is still missing an attack animation, but works otherwise)
https://github.com/user-attachments/assets/06644f10-3e3a-4add-8a8c-6858184c8e8c
Override the moveset to have Splash or Celebrate.
~- [ ] Have I created new automated …
=> [Move] Add flavor text for Splash and Celebrate

src/phases/encounter-phase.ts
N/A
Fixing a mistake in the passive check.
The passive check was fixed and the nature logging now shows which stats are raised/lowered.
<details><summary>Console Log Example</summary>
<p>
</p>
</details>
=> [Misc] Update Encounter Phase logging nature display and passive check

src/data/mystery-encounters/utils/encounter-phase-utils.ts, src/phases/encounter-phase.ts
N/A
MEs have their own encounter code that doesn't re-use existing encounter code, so the logging needs to be copied over manually.
Logging from `EncounterPhase` copied over to MEs.
<details><summary>Example of logging in Expert Pokemon Breeder ME</summary>
<p>
</p>
</details> 
Start an ME battle, such as the Expert Pokemon Breeder ME (requires 3 pokemon on the player's team).
=> [Misc] Copy Encounter Phase logging to MEs

create-test-boilerplate.js
`npm run create-test` gives an erroneous import, because test/utils was renamed to test/testUtils but it isn't reflected there.
Adding an entire five characters to the gameManager path
=> [Test] Fix gameManager import for the test creator

src/field/pokemon.ts
Dual typed pokemon will have both STABs much more often.
Blitzy asked.
Changes one number.
Just fight trainers with dual type pokemon
=> [Balance] Make dual STABs way more likely

src/data/battler-tags.ts
Taunt now displays a message when it is removed.
Was working on a different pr and noticed that the message is missing.
TauntTag now overrides the `onRemove` method with a message, similar to most other tags.
https://github.com/user-attachments/assets/becbd7d2-3fa4-4542-ae6b-38762161818d
look
- [x ] Have I tested the changes manually?
=> [Move] Add Taunt Removal Message

src/field/pokemon.ts, src/phases/tera-phase.ts
Some parts of the code weren't correctly acknowleding tera type overrides, like terapagos was displaying as tera normal sometimes.
The code accessed tera type directly instead of using getTeraType in a couple of places, this is now fixed.
The code accessed tera type directly instead of using getTeraType in a couple of places, this is now fixed.
Terastallize terapagos. It should say tera stellar.
=> [Bug] Fix tera type access

src/ui/pokedex-page-ui-handler.ts, src/ui/pokedex-ui-handler.ts
The Pokédex now correctly allows to sort by candy.
The sort function was not broken.
Need to hardcode the candy value for Pikachu to 0 due to the exception in `getStarterSpeciesId` (this will be fixed eventually with the Pikachu rework).
=> [UI/UX] Pokédex - Fix candy filter

src/ui/pokedex-page-ui-handler.ts, src/ui/pokedex-ui-handler.ts
When using the left and right arrow on a Pokémon page to scroll to the previous or next mons, filters are now taken into account.
This is a more intuitive behavior and has been requested on discord.
When filtering, a list of species ids of the filtered mons is created. This is passed as an argument when selecting the Pokémon, and taken into account every time left or right is pressed.
https://github.com/user-attachments/assets/361dccde-a205-433d-bca9-31f0ec2f4759
Try different filters or combinations of filters.
=> [UI/UX] Pokedex - Page turning takes filters into account

src/ui/pokedex-ui-handler.ts
Hotfix due to a hidden conflict between #5400 and #5372.
#5372 introduced a reference to filteredPokemonContainers, which have been removed in #5400 . Referencing filteredPokemonData instead.
The Pokédex is not crashing anymore and filters are working as expected.
=> [UI/UX][Bug] Fixing obsolete reference in Pokédex to filteredPokemonContainers

src/data/ability.ts
Unreported bug where onGain abilities could bypass checks, i.e. intimidate could activate under neutralizing gas.
Fix a mistake I made
In #5146 I split `applyAbAttrsInternal` into a second function, `applySingleAbAttrs`. I neglected to move the canApplyAbility check into the inner function. This isn't an issue most of the time, but onGain abilities call  `applySingleAbAttrs` directly (unlike other abilities, a pokemon will often only gain one ability at a time, so it can't loop over passive and normal like `applyAbAttrsInternal` does), so those abilities would skip the check. This fixes that
```typescript
BATTLE_TYPE_OVERRIDE: "double",
ABILITY_OVERRIDE: Abilities.INTIMIDATE,
OPP_ABILITY_OVERRIDE: Abilities.NEUTRALIZING_GAS,
MOVESET_OVERRIDE: Moves.SKILL_SWAP
```
Use skill swap on …
=> [Bug] Fix canApplyAbility check

src/ui-inputs.ts
The arena flyout will go away when you let go of V.
It wasn't going away.
I accidentally removed a key up handler I shouldn't've in the tera update.
Go into a battle, hit the flyout key.
=> [Bug][UI] Fix arena flyout

src/data/ability.ts, test/abilities/neutralizing_gas.test.ts
NG now deactivates when its user faints or is captured, as it should.
Helps with #5422 (not saying "fixes" so it doesn't auto close when this is merged 🙏)
The reason it doesn't fix it entirely is because _no_ PreLeaveField abilities (this and primal weather) correctly end when fleeing from a pokemon. This has been the case since before the NG changes.
I was genuinely just unaware of the `bypassFaint()` addition to abilities. This is necessary because both faint and capture are treated as the pokemon having 0 hp, so this must be added for the ability's` PreLeaveFieldAbAttr` to not be ignored. So, it's my 100th one line change this week.
I also added automated tests to ensure that this doesn't happen again.
https://github.com/user-attachments/assets/e49b0ec4-5d11-4989-8497-f0dd17f0aa65 …
=> [Bug] Fix Neutralizing Gas not Deactivating on Faint and Capture

src/battle-scene.ts
- Trainers with a specialty type (E4, Gym Leaders etc) will have certain species set to a form matching their specialty type
- Affected mons are:
- Rotom
- Ghost, Fire, Water, Grass, Flying, and Ice specialists get the matching form.
- Paldean Tauros
- Fire or Water specialists get Blaze Breed or Aqua Breed respectively
- Oricorio
- Ghost, Fire, Electric, and Psychic specialists get the matching form.
- Wormadam
- Ground, Steel, and Grass specialists get the matching form
- Silvally and Arceus
- Trainers with a type specialty use the appropriate type. Not that this is planned to be used, just here for completeness sake.
- These forms are only set if used by a trainer that specializes in the list of types. Otherwise, their forms are determined by the same method as usual, whether that be …
=> [Balance] [Bug] Set trainer mons to forms matching specialty type

src/data/balance/starters.ts
Starter Cost Change
- 1 Starter Cost Change
- Marshadow 7 -> 8
All changes should be [comparable here ](https://docs.google.com/spreadsheets/d/1KwUnV5xbKSi7af3l4MJPEkQb4AaB3dOphBdXsk72p_4/edit?usp=sharing)
This is a follow up PR to #5416 
Marshadow is an extremely powerful pokemon in and out of the context of this game. This was mostly an oversight that was never brought up again after its' last change and I would rather fit it in a patch where other changes are happening related to starter changes than push it further standalone.
Balance Files
Merge to a local, or play on beta when they are on there.
=> [Balance] Adjust Marshadow Starter Cost

package-lock.json, package.json, src/ui/party-ui-handler.ts
After 1.7.0 the "Transfer -> All" function is broken. The reason seemingly comes from #5283.
Bug report on discord (follow the links to find session data):
https://discord.com/channels/1125469663833370665/1344837990031167499
When transfering all items, the game was checking the list of the items and moving up, with an index going from 0 to the length of the item array. This was fine before, probably due to the actual transfer happening asyncronously. However, with the Promise changes, the length of the array changes after each iteration and at some point the index goes over the length of the array of remaining items.
The solution is the oldest trick in the book, scan the array from the bottom.
https://github.com/user-attachments/assets/1e07a1a7-f118-48d4-ab00-86c78160cc42
Also working …
=> [Bug][Hotfix] Fix bug with transfering all items

package-lock.json, package.json, src/data/ability.ts
Mycelium Might crashes the game if the pokemon does anything except use a move.
Game crashing.
Something in the recent ability changes has caused mycelium might to start firing more, revealing a bug in its code. This fixes the broken conditional.
Use one of the sessions available on discord, it won't crash now when it did before.
=> [Bug] Fix mycelium might softlock

package-lock.json, package.json, src/data/trainer-config.ts
- Trainers can tera their last party member
- Tera slot was wrapping to party length minus 1, causing the last party member to be excluded from consideration
- Uses party.length as the max for Phaser.Math.Wrap when getting tera slot, because max is excluded (was previously party.length-1)
=> [Bug] Fix tera slot wrapping

package-lock.json, package.json, src/ui/pokedex-page-ui-handler.ts
It was pointed out that using candies in the Pokédex during the shop phase can be exploited to dupe rewards for catching mons. #5444 
Introducing a `canUseCandies `condition in the dex which is only `true` in whitelisted phases.
The option does not show up anymore, even though Pidgey has more than enough candies:
=> [Bug][Hotfix] Restrict Use Candies option in the Pokédex

src/ui/pokedex-ui-handler.ts
Fixes a bug reported on discord [here](https://discord.com/channels/1125469663833370665/1338291479449178223/1344979140163670067) which causes the cursor to move to a supposedly empty space and display the Pokémon in the respective container.
This happens in two cases:
1) Going down from the filter bar when only a few Pokémon are being shown, e.g. from the 2nd filter when only 1 Pokémon is shown
2) Going down from the second-to-last row of Pokémon
Added a check to ensure that the cursor index doesn't go above the number of filtered Pokémon. Correctly setting the cursor index when going down from filter bar.
https://github.com/user-attachments/assets/124e2887-27ce-491b-a391-e1c1700c0ff7
Open the dex, select some filters.
=> [Bug][UI/UX] Never select invisible containers in Pokédex

src/ui/pokedex-ui-handler.ts
As reported [on Discord](https://discord.com/channels/1125469663833370665/1339431072152162395/1345177621314670599), icons that indicate egg or tm moves ir passives while filtering are not showing up.
Code to turn the icons visible when needed had not been included after the refactoring in #5400, it is added now.
=> [Bug][UI/UX] Restore egg/tm move and passive icons when using filters in Pokédex

src/ui/pokedex-page-ui-handler.ts
Explicitly checking that gendered form key matches current gender
As reported [on Discord](https://discord.com/channels/1125469663833370665/1345072558751481896), Pokémon with gendered forms such as Oinkologne or Basculegion are displaying information for the opposite gender.
This problem arises because the default gender when opening a dex page is `female`, but the default form of these Pokémon is the `male `one. There is now an explicit check which switches form if it does not match the gender.
Oinkologne displaying the correct abilities:
https://github.com/user-attachments/assets/9bee361f-3625-4d17-8257-e9115edc9d92
Open the Dex and look up a Pokémon with gendered forms.
=> [Bug] Gendered forms display correct information in Pokédex

src/data/move.ts, test/moves/focus_punch.test.ts
Fixes #5442 , also reported [on Discord](https://discord.com/channels/1125469663833370665/1345085765440503920)
After #5341 , the locales string was generated in the code without passing the pokemonName argument, this is now fixed.
https://github.com/user-attachments/assets/8add358c-f674-4a7c-a6ea-61c97553e07d
E.g. with this override:
```
MOVESET_OVERRIDE: [ Moves.FOCUS_PUNCH ],
OPP_MOVESET_OVERRIDE: [ Moves.QUICK_ATTACK ],
OPP_SPECIES_OVERRIDE:  Species.MAGIKARP,
ABILITY_OVERRIDE: Abilities.BALL_FETCH,
OPP_ABILITY_OVERRIDE: Abilities.STURDY,
```
=> [Bug] Display Pokémon name in Focus Punch lost focus message

src/system/game-data.ts
An extension to #5385 which ensures that the correct base form of Zygarde is unlocked upon capturing it. Reported on Discord [here](https://discord.com/channels/1125469663833370665/1344848688610148522).
More hard-coding. Yay!
Before:
https://github.com/user-attachments/assets/a1b1d8ea-f4d3-4f9d-ac35-575b5e7d7c42
After:
https://github.com/user-attachments/assets/23b89a83-18a6-443a-bb0e-af0c3886346b
https://github.com/user-attachments/assets/53e737ba-5efa-4d9d-9b26-b3a435b4dfae
The override is
```
STARTING_WAVE_OVERRIDE: 11,
OPP_SPECIES_OVERRIDE: Species.ZYGARDE,
OPP_FORM_OVERRIDES: {[Species.ZYGARDE]: 4},
POKEBALL_OVERRIDE: {
active: true,
pokeballs: {
[PokeballType.POKEBALL]: 0,
[PokeballType.GREAT_BALL]: 0,
[PokeballType.ULTRA_BALL]: 0,
[PokeballType.ROGUE_BALL]: 0, …
```
=> [Bug] Unlocking correct base form of Zygarde when captured

src/ui/starter-select-ui-handler.ts
As documented in this video, the starter select screen does not account for alternate forms having different abilities:
https://github.com/user-attachments/assets/f8d572e1-a8bd-4790-b71a-05dddeefe851
Explicitly check for the ability of the form, rather than the species, whenever there is more than one form.
After the changes:
https://github.com/user-attachments/assets/bb38efd5-cb05-4829-aa45-831350c534ce
Load a save with all or many unlocks and look around the starter select screen.
=> [Bug][UI/UX] Starter select screen now looks for and displays form-specific abilities

src/ui/pokedex-page-ui-handler.ts, src/ui/starter-select-ui-handler.ts
When the variant button was removed by #5213, a minor bug was introduced which prevents the player from switching between variants if the non-shiny form is not caught. This has been reported on discord e.g. [here](https://discord.com/channels/1125469663833370665/1125894949020381285/1345114255833305181). See also these screenshots (from a save where all three variants of Miraidon are unlocked, but the non-shiny form is not): the "cycle shiny" button does not appear.
`canCycleShiny` is now true if at least two variants are caught. The logic for cycling shiny has been reworked to loop correctly ig the non-shiny form is not caught.
Shiny Miraidon cycling correctly:
https://github.com/user-attachments/assets/0af97659-b7a8-4f84-8eeb-dd4833141760
Proof that the button is still working properly …
=> [Bug][UI/UX] Shiny button can cycle variants even if non-shiny form is uncaught

src/ui/pokedex-page-ui-handler.ts
Discord bug report is [here](https://discord.com/channels/1125469663833370665/1345408533797146685)
This is a bit convoluted. The game keeps track of caught forms for every caught species. For species that have no forms, it still marks the "default form" as caught. Now, it turns out that if you evolve a Sand Cloak or Trash Cloak Burmy into Mothim, the "default form" on Mothim is _not_ marked as uncaught, probably because the game tries to unlock form 1 and 2, respectively, instead. A similar thing happens with Milcery when catching an Alcremie form with formIndex > 0, and there might be other niche cases as well.
This normally has no impact whatsoever, because these mons do not actually have a form to use anywhere in the code. The Pokédex, however, was checking `DexAttr.DEFAULT_FORM`, …
=> [Bug][UI/UX] Fix bug in Pokédex for Mothim and other niche cases

.github/CODEOWNERS
None
Lots of requests for this to happen. Also it's annoying to be put on PRs that I don't really have much business reviewing.
Added the following to `.github/CODEOWNERS` to make art-team and composer-team codeowners of their files.
This rightly means that junior-dev-team is no longer considered code owners for files matching these patterns
```
/public/**/*.png @pagefaultgames/art-team
/public/**/*.json @pagefaultgames/art-team  
/public/images @pagefaultgames/art-team
/public/battle-anims @pagefaultgames/art-team
```
```
*.mp3 @pagefaultgames/composer-team
*.wav @pagefaultgames/composer-team
*.ogg @pagefaultgames/composer-team
/public/audio @pagefaultgames/composer-team
```
Added balance-team to code owners of `src/data/balance`, keeping junior-dev-team as codeowners as it contains real …
=> [GitHub] Update CODEOWNERS to have teams own the files they should

src/ui/starter-select-ui-handler.ts
When looking up IVs on the starter select screen, the tera icon disappears. It then shows up again when closing the IVs diagram. Cycling tera types is disabled while the icon is hidden.
There is currently a minor visual bug which makes the tera icon disappear when pressing "V" while the IVs diagram is shown. More generally, the interaction between these two is not handled in the code. The tera icon overlaps partially with the IVs diagram, so it makes sense to hide it temporarily.
Since toggleStatsMode does not call setSpeciesDetails, it was necessary to copy the check for the tera button to show up or not.
Displaying the new behavior, and confirming that the tera icon does not randomly show up when it isn't supposed to:
https://github.com/user-attachments/assets/623914a0-6eb8-45d5-93b0-e24 …
=> [UI/UX] Hiding tera button when toggling on stats mode

src/field/pokemon.ts, src/ui/command-ui-handler.ts
The player's mega and dynamax pokemon will no longer be able to tera.
Note: This doesn't currently revert existing teras, that's being saved for 1.8.
Damo asked.
A new isMega function to go alongside isMax, and a slight tweak to the logic checking whether a pokemon can tera.
Mega or gigantamax some pokemon.
=> [Balance] Make megas/max player pokemon unable to tera

src/data/ability.ts
Pickup and Honey Gather should no longer be suppressed from Ability Suppression Moves/Abilities like Gastro Acid, and Neutralizing Gas from an ally in a double battle.
This was reported directly in the balance channels, and was not the first time I had heard of the issue, but was previously dismissed.
After testing it seems these do not get suppressed by the opposing pokemon at the end of battle correctly, but your ally can still suppress both in a double battle, making you keep (usually support pokemon) benched in the back of the party to get the effect out of it in double battles.
Added the Unsuppressable tags to Pickup and Honey Gather.
These are notably now the only abilities with this tag that do NOT have the Uncopyable and Unswappable tags
- Set a Pokemon on your side of the field …
=> [Balance] Make Pickup and Honey Gather Unsuppressable

src/ui/run-info-ui-handler.ts
Hitting left will go back to the run history screen from the run info screen.
I have to hit right to get to the run info screen, which makes me intuitively try to hit left to go back, but the left key doesn't go back.
One line added to a switch case and a small comment added
This isn't a very screenshottable change
Go to run info for a run and hit the left key
=> [UI/UX] Make left button also go back to the run history screen from run info

.github/CODEOWNERS, index.html, package-lock.json, package.json, src/data/ability.ts, src/data/battle-anims.ts, src/data/move.ts, src/field/pokemon.ts, src/system/game-data.ts, src/ui/abstact-option-select-ui-handler.ts, src/ui/command-ui-handler.ts, src/ui/pokedex-page-ui-handler.ts, src/ui/pokedex-ui-handler.ts, src/ui/run-info-ui-handler.ts, src/ui/starter-select-ui-handler.ts, test/moves/focus_punch.test.ts
- Mega forms, Gigantamax forms, Primal Forms, and Ultra Necrozma, can no longer Tera
- The :arrow_left: left button now also goes back to the Run History / Load Game screen from Run Info (:arrow_right:)
- Focus Punch now properly displays the name of the Pokémon in its' message
- Checking the pledge moves in summary screen no longer crashes the game
- Pickup and Honey Gather are now Unsuppressable
- Restored the Egg/TM Move and Passive Icons when using filters in the Pokédex
- The player can now no longer select any of the empty space in the Pokédex
- Gendered forms now display correct information in the Pokédex
- The shiny button now properly cycles variants in the Pokédex if you have not caught the non-shiny form
- Certain form independent Pokémon (Alcremie, Dustox/Mothim, etc) now …
=> Minor Release 1.7.6

package-lock.json, package.json, src/system/version_migration/versions/v1_7_0.ts
The game will load.
In some cases due to an unknown bug, something caused a player's account to have some unlock data for pokemon zero. Attempting to actually use that data crashed the save migrator rendering the game entirely unplayable for these accounts.
A small tweak to the save migrator so it doesn't attempt to migrate pokemon zero.
You will need a manually edited save file to introduce the bug or use the console and the debugger to inject the json of one of the faulty saves mid load.
=> [Bug][Hotfix] Fix migration crash

src/data/weather.ts, src/field/arena.ts, src/phases/move-phase.ts
The abilities Desolate Land, Primordial Sea and Delta Stream display the normal weather effect messages instead of special ones (e.g., "the sunlight got hot" instead of
"The sunlight turned extremely harsh!").
Another issue is that if one of these special weathers is active and the opponent uses a move that is ineffective in this weather, it doesn't display a special message but the normal one (e.g., using a Water-type move in Harsh Sunlight).
The message shown when a move has failed due to Desolate Land or Primordial Sea will be more appropriate instead of the default message ("But it failed")
- Added `getWeatherBlockMessage(WeatherType)` in `weather.ts` to return the correct message when a move fails due to Primordial Sea or Desolate Land.
- Called `getWeatherBlockMessage()` in …
=> [Bug] Fix #5159: Harsh Sun, Heavy Rain, Delta Stream Messages Incorrect

src/overrides.ts
N/A
Ease of use for testers/developers.
The ESLint rule `@typescript-eslint/no-unused-vars` was disabled for `overrides.ts` and 5 commonly used imports were added to the file.
=> [Misc] Add some pre-defined imports to `overrides.ts`

src/field/pokemon.ts, src/overrides.ts, src/phases/select-starter-phase.ts
N/A
`OPP_FORM_OVERRIDES` was broken and didn't allow setting form index 0.
The check that `OPP_FORM_OVERRIDES` is not `undefined` now explicitly checks that it's not `undefined` instead of doing a falsy check which erroneously sees a value of `0` as not valid.
Use the following overrides and observe that the opponent is always Unown-A.
```ts
OPP_SPECIES_OVERRIDE: Species.UNOWN,
OPP_FORM_OVERRIDES: {[Species.UNOWN]: 0},
```
=> [Misc] `OPP_FORM_OVERRIDES` now accepts 0 as a valid form index

src/data/ability.ts
No crash with a commander mon out
I somehow reversed the checks when moving Commander stuff around for #5267, so the getAlly() dependent things were getting evaluated before checking if such ally existed
Discord: https://discord.com/channels/1125469663833370665/1350710951791562833
Working again
https://github.com/user-attachments/assets/1c4091ec-2166-468f-9cee-742f749ab82f
Use commander
=> [Bug] Fix Commander crash after 5267

.gitattributes
N/A
This should prevent issues with Biome seeming to change the line endings of files due to Git converting them to `crlf` locally for Windows users.
Added `* -crlf` to `.gitattributes` below `* text=auto`.
=> [Misc] Add `* -crlf` to `.gitattributes`

src/ui/pokedex-ui-handler.ts
This is the intended behavior and was broken accidentally by the container rework.
Slightly reworked the code to make it more compact, now checking for false (has egg move/passive but is locked) vs undefined (no egg move/passive).
Open the dex and mess with filters.
=> [UI/UX] Icons for egg moves and passives show up even when not unlocked

test/moves/tailwind.test.ts
N/A
The test was missing ability overrides.
Both player and enemy pokemon are now set to have the ability Ball Fetch, preventing a random ability from interfering in the test.
=> [Test] Add ability overrides to Tailwind tests

src/phases/message-phase.ts, src/ui/message-ui-handler.ts, src/ui/ui.ts
When the player renames the pokemon to a nickname that contains the following symbols: "@c{}", "@s{}", "@d{}", "@f{}" and "$" the text will appear properly without causing abnormalities such as the name being cut or the game fading into black.
To ensure all nicknames can be used without any abnormalities happening.
Fixes #5082
- on message-ui-handler.ts file I updated the "showTextInternal" function to get the original name of the pokemon or pokemons (in case it's a double battle) saving it in a list named "pokename" and change it in the text for their  correspondent placeholder which is saved in the list "repname" (e.g "#POKEMON1" for the first pokemon and "#POKEMON2" for the second pokemon). After the text is properly modified because of the special characters ("@c{}", "@s{}", "@d{}", …
=> Fix #5082: Nicknames not properly sanitized

test/moves/chilly_reception.test.ts
na
Chilly Reception tests would randomly fail due to abilities not being overridden properly
The abilities were overridden as `Abilities.NONE` (which is equivalent to not overriding at all). Switched them to Ball Fetch
test the test
=> [Test] Fix Chilly Reception Test Ability Overrides

src/field/pokemon.ts, src/phases/summon-phase.ts, src/system/pokemon-data.ts, test/abilities/imposter.test.ts, test/moves/transform.test.ts
Transformed pokémon, either via transform move or imposter ability now persists after reloading
To make sure any status changes on player pokémon during wild waves are consistent with the game roguelite behavior during wild battle waves. This Fixes #5472
I changed 3 src files, `pokemon-data.ts`, `pokemon.ts` and `summon-phase.ts`. 
- when create a `pokemonData` object, it also copies the `speciesFrom` from the source pokemon object
- when creating a pokemon with `toPokemon()`, if there was a `speciesFrom`, runs `getPokemonSpecies(this.summonData.speciesForm.speciesId)`. This ensures that, once the JSON from the server was parsed, we create the `species` object again.
- on `resetSummonData()` now uses `Object.keys(this.summonDataPrimer)` to copy all attributes from the primer into …
=> [BUG] fixes #5472 - transform on reload

src/data/ability.ts
Shield Dust and Gluttony no longer have flyouts.
Mainline behavior + these abilities have/have had problems with random flyouts.
Technically also fixes #4885 
`super()` -> `super(false)`
Use one of them
=> [Bug] Stop Shield Dust and Gluttony from Displaying

src/data/moves/move.ts
Abilities won't randomly activate while the AI is making decisions regarding certain moves it has that have secondary effects. This currently only affects Shield Dust which actually won't be displaying anyway, but it's still a good change to make for the future.
Abilities shouldn't display during simulated calls
`getMoveChance` is called by several implementations of `getTargetBenefitScore` which were correctly passing `showAbility` as false, but that parameter wasn't used properly in the function. It was passed as the fifth arg to an ability attribute that only used two args and not used at all in a second ability attribute call. 
I changed the calls to use `!showAbility` as the value to pass for `simulated` so the abilities will know whether to display or not. …
=> [Bug] Fix Extra Ability Activation Flyouts during AI Decisions

src/data/battler-tags.ts
Flash fire will display a message when activated
Mirror of #4063 kinda
Fixes #4058 
Queues messages from `onAdd` (type boost message) and `onOverlap` (immunity message) of `TypeBoostTag`
https://github.com/user-attachments/assets/8cec498e-9a00-43c7-b318-e916bc734c8c
```typescript
ABILITY_OVERRIDE: Abilities.FLASH_FIRE,
OPP_ABILITY_OVERRIDE: Abilities.FLASH_FIRE,
MOVESET_OVERRIDE: Moves.EMBER,
OPP_MOVESET_OVERRIDE: Moves.EMBER
```
lol
Are there any localization additions or changes? (Locales was merged long ago)
=> [Bug] Fix Flash Fire has No Message

src/data/ability.ts, src/data/arena-tag.ts, src/data/battler-tags.ts, src/data/moves/move.ts, src/field/pokemon.ts, src/phases/stat-stage-change-phase.ts, test/abilities/flower_veil.test.ts
Flower Veil works as it does on cartridge, and is no longer marked (N).
I was commissioned by @Blitz425 
Adds three new ability attributes:
`ConditionalUserFieldStatusEffectImmunityAbAttr `, `ConditionalUserFieldBattlerTagImmunityAbAttr `, and `ConditionalUserFieldProtectStatAbAttr`.
The first two ability attributes conditionally protect the user's field from status effects (or a battler tag), and are modeled off of the non-conditional methods of the same caliber (like UserFieldStatusEffectImmunityAbAttr for sweet veil).
They both take a condition function and, if the condition function returns true, will prevent the status effect immunity.
`ConditionalUserFieldProtectStatAbAttr` works much the same. The difference with this one is that the condition function can't take the source of the …
=> [Ability] Flower Veil implementation

src/data/moves/move.ts
If Metronome (or another move that calls other moves) fails due to there being no targets, a failure message will be displayed. This is a temporary change until the underlying issue can be fixed.
Moves shouldn't fail with no feedback at all.
If `CallMoveAttr` returns early due to there being no targets left, a failure message ("But it failed!") will be displayed to the player and a message logged to the console (on beta/local) explaining what happened.
<details><summary>Fail message</summary>
<p>
https://github.com/user-attachments/assets/122634f7-a1d2-4718-b72a-08d01b468072
</p>
</details> 
```ts
OPP_ABILITY_OVERRIDE: Abilities.PRANKSTER,
MOVESET_OVERRIDE: Moves.METRONOME,
OPP_MOVESET_OVERRIDE: Moves.MEMENTO, …
```
=> [Move] Add message for called moves failing due to no targets

src/data/moves/move.ts, test/abilities/parental_bond.test.ts, test/moves/pollen_puff.test.ts
Users of Pollen Puff with Parental Bond (namely, champion Kieran's Hydrapple) won't crash. This has always been an issue but wasn't possible to encounter until Hydrapple was given the ability
Removing the assumption in `canBeMultiStrikeEnhanced` that `user.getAlly()` will be defined
=> [Bug][Hotfix] Fix Parental bond + Pollen Puff softlock

src/phases/battle-end-phase.ts, src/phases/new-battle-phase.ts, test/abilities/wimp_out.test.ts
Emergency Exit and Wimp Out will no longer open an alternate dimension and skip waves when a pokemon with wimp out's ability triggers in response to a spread move that causes its teammates to faint.
Fixes #5032 
Inside the `start` method of `NewBattlePhase` and `EndBattlePhase`, the first thing that is done after the call to `super()` is to filter out the phase queue (and prependPhaseQueue) to clear out any extra phases that have been added.
This ends up being defensive programming. Rather than adding convoluted checks at the places where `NewBattlePhase` and `EndBattlePhase` occur to determine whether or not they *should* properly occur is 
<details><summary>Fixed Wimp Out</summary>
https://github.com/user-attachments/assets/319e48b8-560f-4767-a967-a698362beee8
</details>
Old behavior on …
=> [Bug][Ability] Fix wimp out and emergency exit skipping waves in double battles

src/phases/move-end-phase.ts, src/phases/move-phase.ts, test/abilities/dancer.test.ts, test/abilities/mold_breaker.test.ts
Mold breaker will now no longer suppress abilities when its user uses a move with its last pp.
I was asked to look into this odd interaction with mold breaker
In `move-phase`'s `end` method, `MoveEndPhase` will *always* be unshifted, instead of only if the move was not called via a follow up and an erroneous check to the `canMove` call (which would previously return `false` after the move's pp had been deducted, as the `canMove` check also looks at the remaining pp).
Instead, `this.followUp` is now passed as an argument to the `MoveEndPhase` constructor which is called  unconditionally by `end`.
 
`MoveEndPhase` takes a new optional parameter - `wasFollowUp` that is checked before lapsing `BattlerTagLapseType.AFTER_MOVE`.
I don't know the interactions that would cause this lapse to need …
=> [Bug][Ability] Fix mold breaker effect lingering if the user's move runs out of PP

.github/workflows/tests.yml
N/A
Part of the test refactor (sort of). We do not need to re-run tests in commits that only change files that cannot impact tests (e.g. the README file). These tests are long running.
In summary, the test github action will only re-run when source code files, test files, any file that can impact the build, or the test workflow file itself has changes.
Accomplished by added the following [paths filter](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to `.github/workflows/tests.yml`
```yaml
paths:
- "src/**"
- "test/**"
- "public/**" # PLEASE REVIEW -- Does it make sense to include this? Can modifying these break tests? (REMOVE COMMENT AFTER REVIEW)
- ".github/workflows/test*.yml"
- …
```
=> [GitHub] Add path filters to avoid unnecessarily re-running tests

src/data/ability.ts, src/field/pokemon.ts, test/abilities/super_luck.test.ts
Super luck will now actually increase the crit stage
The ability was effectively not even implemented.
Fixes #5480
- Removes the erroneous guard for `applyAbAttr` inside the pokemon class's `getCritStage` 
- Replaces `BonusCritAbAttr`'s use of a boolean holder with a number holder, so applying the ability now directly increases the crit stage
N/A
``npm run test:silent -- test/abilities/super_luck.test.ts``
=> [Bug] Fix super luck implementation

src/data/ability.ts, src/data/moves/move.ts, src/phases/move-effect-phase.ts, src/phases/move-phase.ts
Technically, this fixes an unreported bug where moves called by metronome would improperly not ignore abilities if the user had mold breaker.
@Wlowscha and I had a long discussion in discord about the fact that the `checkFlags` method inside moves was confusing.
This class is the ideal place, adhering to the Separation of Concerns design principal, for moves to check whether a flag of theirs can be applied in a given situation (given that the existing structure of the code does not have move instances for moves that are in flight).
However, the name of the method is potentially confusing, and has likely contributed to the method not being used in cases where it probably should be (note, refactoring those uses is not in the scope of this PR). 
The signature of the method was also changed …
=> [Refactor] [Docs] Minor refactor of `move.checkFlags` into `move.doesFlagEffectApply`

package-lock.json, package.json, src/@types/SessionSaveMigrator.ts, src/@types/SettingsSaveMigrator.ts, src/@types/SystemSaveMigrator.ts, src/system/version_migration/version_converter.ts, src/system/version_migration/versions/v1_0_4.ts, src/system/version_migration/versions/v1_1_0.ts, src/system/version_migration/versions/v1_7_0.ts, src/system/version_migration/versions/v1_8_3.ts
N/A
Making it easier for developers to write save data migrators in the future.
Version comparison for the data migrators is now handled automatically, developers only need to write the migrators (in `src/system/version_migration/versions/vA_B_C.ts` like before, but also assign them a version now) and then add them to the appropriate array in `src/system/version_migration/version_converter.ts` (if it hasn't been done already).
All the classes were removed and replaced with a set of functions.
An example is provided in `src/system/version_migration/version_converter.ts`.
Load an old save file.
=> [Refactor] Re-implement save migration system

src/phases/select-biome-phase.ts
The chance of reaching certain biomes should no longer erroneously become 0 depending on the number of lures the player has.
Fixes #5627 
Removed the `executeWithSeedOffset` calls in `SelectBiomePhase`.
<details><summary>Code to add in Title Phase</summary>
<p>
Add this to the `TitlePhase` class (L36):
```ts
testRNG() {
const results = {};
const lures = [
() => globalScene.RemoveLures(),
() => globalScene.InsertLure(),
() => globalScene.InsertSuperLure(),
() => globalScene.InsertMaxLure(),
]
const startingBiome = Biome.CAVE;
for (let i = 0; i < 10000; i++) {
globalScene.setSeed(`${i}averyrandomseed:)`);
// console.log("Seed:", globalScene.seed)
globalScene.resetSeed();
globalScene.newArena(startingBiome);
globalScene.newBattle(10);
for (let j = 0; j < 4; j++) {
globalScene.resetSeed(); …
```
=> [Bug] Fix Biome selection RNG

.github/workflows/github-pages.yml
N/A
The pages workflow was the only one not using the `.nvmrc` file.
```diff
-         node-version: 22
+         node-version-file: "pokerogue_docs/.nvmrc"
```
=> [GitHub] Use `.nvmrc` for pages workflow

src/field/pokemon.ts, test/moves/struggle.test.ts
Struggle will no longer be impacted by stab.
Fixes #5490
Did some minor cleanup of ``pokemon.getAttackDamage`` while I was editing the file.
Extracted out the calculation of stab effectiveness into its own method that is called by `getAttackDamage`. The first thing the method does is check if the move has the typeless attribute. If it does, the method immediately returns with 1.
There's not a good way of providing a screenshot for this.
`npm run test:silent test/moves/struggle.test.ts`
=> [Bug][Move] Struggle no longer gets STAB

src/data/abilities/ability.ts, test/abilities/healer.test.ts
The user will no longer see a message saying that healer attempted to heal a status effect of a fainted ally
Fixes #4981 
Adds the following check to the `canApplyPostTurn` of healer's attribute:
```ts
const effect = this.target?.status?.effect;
return !!effect && effect !== StatusEffect.FAINT;
```
Adds a test file for healer along with 3 tests, one of which is marked as TODO (healer healing the status before end of turn status damage).
There's no way to upload a video for a negative, as it's a chance interaction anyway.
`npm run test:silent test/abilities/healer.test.ts`
- ~~[ ] Have I tested the changes manually?~~ No way to do this
- ~~[ ] Have I made sure that any UI change works for both UI themes (default …
=> [Bug][Ability] Fix healer queueing its message when its ally is fainted

src/field/pokemon.ts
Game will no longer hang due to a race condition when loading some battles
I can't launch the game with certain overrides set.
In `pokemon#loadAssets`, the `globalScene.load.once` call that resolves the promise is now created _before_ calling `globalScene.load.start()`.  Essentially, what was happening before was the await statement that awaits that promise was creating the call to start the loading. This ended up causing a race condition, where the asynchronous execution of the load might have finished before the event listener that allows the promise to resolve was added.
N/A
Use the following override set with the everything save, and ensure the game starts when selecting bulbasaur and charmander.
```ts
OPP_SPECIES_OVERRIDE: Species.ABRA,
BATTLE_TYPE_OVERRIDE: …
```
=> [Bug] Prevent game from hanging when loading in a new battle

src/data/abilities/ability.ts, src/data/battler-tags.ts, src/field/pokemon.ts, src/phases/faint-phase.ts, src/phases/move-effect-phase.ts, test/moves/beak_blast.test.ts
Beak Blast will now burn the attacker if the beak blast user faints.
Moves and abilities that proc an effect on contact damage will now consider things like long reach.
Fixes #5518
Fixes #4974 
Searched for all instances where the `move.hasFlag` method was being used to check for contact damage and replaced them with `move.doesFlagEffectApply`, so they will now properly consider whether long reach should apply.
Created a `ContactProtectedTag` class to deduplicate the logic applied by tags for baneful bunker, burning bulkwark, obstruct, etc., that apply some effect to an attacker that makes physical contact.
Removed the `ContactPoisonProtectedTag` and `ContactBurnProtectedTag` and replaced them with a `ContactSetStatusProtectedTag` that takes an argument specifying which status effect to …
=> [Bug] Fix beak blast: not applying if user faints and not respecting long reach

src/pipelines/glsl/spriteFragShader.frag, src/pipelines/glsl/spriteShader.vert, src/pipelines/sprite.ts, src/utils.ts
Desktop users will now see the variant recolors as intended
In #5592, we introduced fuzzy matching for our recolorings in order to allow mobile players to view the rare variants. This fuzzy matching was conservative, but was based on the hope that there would be no pokemon colors that were within 2 RGB values in each channel. Unfortuantely, there were.
Fixes #4844 (actually the last one did this but I didn't tag to close).
The color comparison between the pixel being recolored and the color we want to replace is now done with the float values. 
`baseVariantColors` and `spriteColors` are now computing their normalized color values in javascript before being sent to the shader, and their respective types have been changed from `ivec4` to `vec4`.
I applied the same changes to the fusion …
=> [Bug][Sprite] Use float values for variant shader recolor comparison

src/data/moves/move.ts
Supercell Slam now
- Does double damage to targets who have used Minmize
- Cannot miss against targets who have used Minimize
Was missing attributes
https://bulbapedia.bulbagarden.net/wiki/Minimize_(move)#Vulnerability_to_moves
Two attributes added to Supercell Slam that are applied to all moves that Minimize is vulnerable to
Overrides, use Supercell Slam against a Minimize target
=> [Bug] [Move] Supercell Slam now hits Minimized targets for double damage and can't miss

src/overrides.ts, test/abilities/illusion.test.ts
N/A
An extra import was accidentally committed to the `overrides.ts` file.
Unused import removed from `overrides.ts` and "organize imports" applied.
Unnecessary imports removed from `illusion.test.ts` and "organize imports" applied.
`npm run test:silent`
Start the game and see if it boots up.
=> [Dev] Fix imports in `overrides.ts` and `illusion.test.ts`

src/data/pokemon-species.ts
In the pokedex, back sprites will now show the recolors
The fix for #5664 was not being applied to back sprites, as it would always assume the front sprite was loaded. This applies the same fix that #5664 did to show variant colors.
Added `back` as a parameter to specify that back sprites will be loaded to `PokemonSpecies#loadVariantColors`
Too lazy
=> [Bug][Sprite] Fix variants not using recolors for back sprite

src/battle-scene.ts, src/data/abilities/ability.ts, src/data/moves/move.ts, src/phases/attempt-run-phase.ts, src/phases/mystery-encounter-phases.ts, src/phases/select-biome-phase.ts, src/phases/switch-biome-phase.ts, src/phases/victory-phase.ts, test/abilities/disguise.test.ts
Lures now have no effect on which Biomes are offered.
PRs #5645 and #5648 were aimed at removing the RNG issues that biome selection had. However this opened up an old buried issue where the amount of Lures (for the double battle rng roll) influence what biomes you will travel to or get as map options.
The only solution I could find, was to make sure the biome selection happens before the double battle roll. It is not possible to seed offset the double battle roll, as that will completely change how 2 lure encounters are generated and would be an even worse solution.
This is only a minor issue in Classic (you could redo the last wave and end with/without a lure ability mon to see if the map options are now more favourable). But it is a huge issue in Daily mode. Since it uses the same seed …
=> [Bug][Misc][Beta] Moved SelectBiomePhase in front of NewBattlePhase

src/data/moves/move.ts
Eternatus will use dynamax cannon more often.
Damo asked.
Removes one move attribute.
Go fight eternatus.
=> [Balance] Remove Dynamax Cannon being discouraged on Eternatus

package.json, src/plugins/api/pokerogue-system-savedata-api.ts, src/system/game-data.ts
When trying to load system data from the server and it returns an error `404` status code, the user will now be able to continue.  This reflects a change on the server side the error message changed from a string. We are now instead relying on the number.
This fixes an urgent error related to new users being unable to login.
`pokerogue-system-save-data-api#get` can now return a number in the case that the response did not send an `ok`. If this happens, then the error message logged to the console.
In the `game-data` method, we now check against the return type being a number. If it is a number, then we check if it is 404. A 404 error is benign, meaning that no save data exists on the server, which is expected for new accounts. Before, we were relying on the message string. However, the …
=> [Bug] Hotfix 1.8.5

src/data/mystery-encounters/utils/encounter-phase-utils.ts, src/phases/encounter-phase.ts
N/A
To aid in development of battles.
Added logging of enemy Pokémon levels in `EncounterPhase` and `encounter-phase-utils.ts`.
Open the browser devtools and observe the console log when starting a new wave.
=> [Dev] Add enemy pokemon level to encounter logging

src/field/pokemon.ts, test/field/pokemon.test.ts
Trainer pokemon will all have minimum IVs based on the current wave (`floor(wave/10)`).
Request from balance team.
In the `EnemyPokemon` constructor, a new set of IVs are generated using `floor(wave/10)` as the minimum value and the existing IVs array is overwritten with the new array.
<details><summary>Rival 195 fight</summary>
<p>
</p>
</details> 
<details><summary>Wild pokemon wave 194</summary>
<p>
</p>
</details> 
Check the console logs that show the enemy pokemon on various waves and encounter types.
=> [Balance] Trainer pokemon now have minimum IVs of `wave/10`

package.json, test/abilities/illusion.test.ts
N/A
Axew can have Mold Breaker which causes the tests to randomly fail.
Replaced Axew with Feebas in most of the Illusion tests.
Also fixed the test command in `package.json`.
`npm run test illusion`
=> [Test] Replace Axew with Feebas in some Illusion tests

src/data/moves/move.ts, src/field/pokemon.ts, src/modifier/modifier.ts
User will no longer be spammed with the "you are already burned" message and similar.
Fixes a bug introduced in #5533.
Adds a new parameter, `quiet`, to `pokemon#trySetStatus`, that defaults to true. The only instance where this called with `false` is in the move attribute that sets a status: `StatusEffectAttr`. Effects that are not moves should not show the messages for status immunities.
This prevents, for instance, flame orb from constantly showing the "But ... is already burned!" message or w/e it shows.
<details><summary>Gen 9 interaction</summary>
https://github.com/user-attachments/assets/3bf32ee6-8a1a-4695-a629-012dd6ab720d
</details>
Use the override to give your mon a flame orb, and then have it apply, and then use it.
- ~~[ ] Have I created new automated tests (`npm run …
=> [Bug][Item] Only moves will now show the explicit status immunity effect.

.github/pull_request_template.md
None
Ever since #5566, we have been using `--no-isolate`. The recommended way to test is therefore to run `--no-isolate`.
Makes the pr template instruct the author to use `npm run test:silent` instead of just `npm run test`
N/A
N/A
=> [GitHub] Update pull request template to say test:silent instead of just test

src/data/abilities/ability.ts
Shell armor and battle armor will now prevent crits instead of guaranteeing them.
Fixes a bug introduced in #5678 where shell armor and battle armor always caused crits instead of preventing them.
`blockCritAttr`'s apply method now uses the boolean holder for `isCritical` consistently with the other crit attributes rather than using it to cancel the crit.
Will wait for #5684 to add the test, as we would like the crit override to have a good test file for this.
I used these overrides:
```ts
ABILITY_OVERRIDE: Abilities.SHELL_ARMOR,
MOVESET_OVERRIDE: [Moves.SPLASH],
OPP_MOVESET_OVERRIDE: [Moves.FLOWER_TRICK],
```
- ~~[ ]~~ Have I created new automated tests (`npm run create-test`) or updated existing tests related to the …
=> [Bug][Ability] Fix shell armor not blocking crits

src/data/abilities/ability.ts
Illusion no longer works (crashes) on a fused Pokemon.
The game hard locks when trying to switch in an Illusioned fused Pokemon.
Added .attr(NoFusionAbilityAbAttr) to Illusion
Overrides
=> [Bug] Disable Illusion in Fusions

src/data/moves/move.ts, test/moves/order_up.test.ts
Order Up is now boosted by Sheer Force again, this is an extremely specific interaction that you probably will never see.
Followup to #5515 
Revert removal of a part of the Order Up test
Overrides
=> [Move] [Beta] Undo Order Up Sheer Force change

src/system/pokemon-data.ts
The game will no longer crash if you load a save with a statused Pokémon and take a turn with that Pokémon.
https://discord.com/channels/1125469663833370665/1367989572813979648
Save data loading code for statuses reverted to pre-#5655
<details><summary>Video of fix</summary>
<p>
https://github.com/user-attachments/assets/63482366-f86f-4516-9184-a70522c6066e
</p>
</details> 
Have a Pokémon that's afflicted with a status effect (like Poison) do something and pass the turn.
=> [Bug] Fix crash when loading a save with a statused Pokemon

src/data/moves/move.ts
Something like Zap Cannon into an electric type will no longer play "It doesn't effect ...".
Mainline behavior
The `quiet` argument for `can/trySetStatus` calls from `StatusEffectAttr` is now `move.category !== MoveCategory.Status` instead of always false. This makes the assumption that all status moves should play the messages and all non-status moves should not. This seems to generally be correct, but edge cases can be ironed out later.
<p>
https://github.com/user-attachments/assets/06d28560-8194-49d8-8f5c-c8cba737de29
</p>
</details> 
<p>
https://github.com/user-attachments/assets/5739c84b-1371-437d-b5eb-58ca11533835
</p>
</details> 
My overrides file is:
```ts
ABILITY_OVERRIDE: Abilities.NO_GUARD, …
```
=> [Bug][Hotfix] Secondary effects no longer trigger status immunity messages

src/phases/move-effect-phase.ts
Moves that don't cause a faint will properly play hit result messages
https://discord.com/channels/1125469663833370665/1368485009492676729
https://discord.com/channels/1125469663833370665/1368639571910328471\
This block
```ts
if (user.turnData.hitsLeft === 1 && target.isFainted()) {
this.queueHitResultMessage(result);
}
```
was changed to or instead of and
<p>
https://github.com/user-attachments/assets/ef2ccbfe-8df7-44cd-ae0f-e524abad59e8
</p>
</details> 
<p>
https://github.com/user-attachments/assets/e32a3be1-1df4-4bb3-923f-34b1f29cc7e3
</p>
</details> 
Use any move that does not faint the opponent and does not do neutral damage
=> [Bug][Hotfix] Always show hit result message

src/system/pokemon-data.ts
Whether a fusion is shiny and what variant it is are saved correctly.
In some circumstances, fusions were incorrectly saving as the wrong variant.
This is really just reverting some of the changes the illusion implementation made to the save/load code.
=> [Bug] Fix shiny save bug

src/ui/pokedex-ui-handler.ts, src/ui/starter-select-ui-handler.ts
Pokemon will now consistently play their hop animation in starter select / pokedex when candy upgrade is set to `animation`.
Fixes a bug reported in: https://discord.com/channels/1125469663833370665/1368563798088355850/1368563798088355850
Inside `pokedex-ui-handler` and `starter-select-ui-handler`, after creating the tween that causes the pokemon to hop, we forcibly call the `.play()` method on said tween. It is unclear to me precisely why the tweens required this to be set, even in the case that the tweens were not starting paused.
I also changed the call to `.resume()` to a .`play()` because this will ensure the tween that was created in a paused state will start. Calling `resume` will not do this.
<details><summary>Proper candy hopping in starter select</summary> …
=> [Bug][UI/UX] Ensure pokemon hop when animations are selected

src/system/pokemon-data.ts
Saving pokemon data will now ignore the pokemon's illusion
Fixes a bug during serialization of a pokemon not properly respecting illusion.
#5780 did not actually fix this issue.
Respect the true shiny / variant result.
N/A
- ~~[ ] **I'm using `beta` as my base branch**~~ Hotfix
=> [Bug] Ensure shiny and variant status respects illusion properly

src/data/egg.ts
Certain types of corrupt eggs (those with species who don't have an associated `EggTier` because they're not supposed to be in eggs) will no longer crash the game.
Fixing a P0 bug.
If an egg is somehow a species that doesn't have an associated egg tier (such as Pikachu), `Egg#getEggTier` now falls back to `EggTier.COMMON`
<details><summary>Pikachu Egg</summary>
<p>
</p>
</details> 
Load this save data and look at the egg list, the first egg should be a Pikachu egg. Without the fix, the game should crash; with the fix, it should show in the egg list as a common egg.
[data_DemoCinderace98 - egg bug.prsv.txt](https://github.com/user-attachments/files/20061165/data_DemoCinderace98.-.egg.bug.prsv.txt)
=> [Bug] Prevent some corrupt eggs from crashing the game

src/field/pokemon.ts, src/system/version_migration/versions/v1_9_0.ts
If a Pokémon has moveset data stored in summon data (e.g. the moveset was altered by a Mystery Encounter or the Pokémon is transformed), the game will no longer crash when loading that data.
Fixing a P1 bug.
A section for loading movesets is added to the `PokemonSummonData` constructor (which shouldn't be a class in the first place but alas).
Load this session data
[sessionData1_RealSaltyDog.prsv.txt](https://github.com/user-attachments/files/20083915/sessionData1_RealSaltyDog.prsv.txt)
=> [Bug] `PokemonSummonData` movesets will now be loaded correctly

src/phases/select-biome-phase.ts
Depending on the last actions on every wave x0, it would change the biome options rng roll. Now the seed is reset, which means the biome options are independent of your actions on the last wave.
This messes up Daily Mode a lot, since everyone is on the same seed but they cant go to the same biomes if they have a slightly different action. It would also allow a player to sit on the last wave and keep trying different actions until the Map shows the biome that they want.
Generally not a good thing. 
ResetSeed used to be done by the NewBattlePhase, but that is now happening after the SelectBiomePhase, so the latter now has to reset it themselves.
Attacking vs Running video
Override:
```ts
SEED_OVERRIDE: "lokaisdhjfklhj",
STARTING_WAVE_OVERRIDE: 10, …
```
=> [Bug] Fix seed not being reset now that Select Biome Phase goes before New Battle

src/field/pokemon.ts, test/abilities/illusion.test.ts
Sending out an illusion Pokemon with neutralizing gas active will result in the illusion not being activated
https://discord.com/channels/1125469663833370665/1369015872424775720
`canApplyAbility` checks if an ability is PreSummon, and if so ignores the check that the pokemon must be on the field for neutralizing gas to apply (because PreSummon abilities are still suppressible even though they activate before being sent out - it's the equivalent of activating the ability then immediately suppressing it on summon, without the overhead). 
It's likely that the `isOnField()` check as a whole is unnecessary, but that's not a can of worms to open for a hotfix
<p>
https://github.com/user-attachments/assets/621a3f10-c002-4e48-a654-cb646f31dfb5
</p>
</details> …
=> [Bug][Hotfix] Suppress Illusion if NG is already active

src/phases/move-effect-phase.ts
Move effects like hyper beam's recharge will now
Fixes a bug: https://discord.com/channels/1125469663833370665/1369623154900734012/1369623154900734012
Inside the `onFaintTarget` method, if the move was multi hit and the phase's `lastHit` method was not already marked as true, then force `lastHit` to be true. This will allow the POST_TARGET effects responsible for adding the tags from outrage, hyper beam, etc., to continue.
<details><summary>Proper hyper beam recharge</summary>
https://github.com/user-attachments/assets/39167837-eb31-4fac-ab88-c83d3d279f29
</details>
Here are the overrides I used:
```ts
MOVESET_OVERRIDE: [
Moves.HYPER_BEAM,
Moves.DAZZLING_GLEAM
],
ITEM_REWARD_OVERRIDE: [
{ name: "MULTI_LENS"},
],
OPP_SPECIES_OVERRIDE: Species.MAGIKARP, …
```
=> [Bug][Move] Fix move effects not applying with multi-lens

src/phases/move-effect-phase.ts
Using a move like Make it Rain in doubles will no longer cause effects to happen once per target.
Fixes https://discord.com/channels/1125469663833370665/1370729720035016775/1370729720035016775
Add a `firstTarget` parameter to the `applyMoveEffect` in the move effect phase.
Added a boolean to `applyToTargets` that starts true and is set to false after the first successful hit against a pokemon.
Go to the linked discord bug report to see the "before" behavior.
<details><summary>Fixed Make it Rain</summary>
https://github.com/user-attachments/assets/c7bfd862-f7f1-46e0-8cd8-7c0897853ea9
</details>
```ts
MOVESET_OVERRIDE: [
Moves.MAKE_IT_RAIN,
],
OPP_SPECIES_OVERRIDE: Species.CACNEA,
STARTING_LEVEL_OVERRIDE: 100,
BATTLE_STYLE_OVERRIDE: "double",
} satisfies …
```
=> [Bug] [Move] Fix KO causing effects to occur twice

src/field/pokemon.ts, src/system/game-data.ts
A transformed pokemon at the lead of the party will display the correct sprite when loading a save. Hopefully also prevents a related phaser crash
Should fix https://discord.com/channels/1125469663833370665/1368847213224132618
Similarly to icons, the code for grabbing the atlas and the code for grabbing the sprite key weren't synced in terms of their use of `ignoreOverride`, so one would grab the transformed species and the other would grab the base species (i.e. ditto), leading to mixups. No idea how it ever worked correctly, in all honesty.
As an example, `loadAssets()` is called when generating pokemon from save data with no arguments, and `ignoreOverride` defaults to true in that method. `ignoreOverride` is then passed (as `true`) when getting the atlas, but *not* passed (defaulting …
=> [Bug][Hotfix] Fix Transformed Sprites not loading properly

src/phases/move-effect-phase.ts
Field moves will now no longer forcibly play the animation
Fixes a bug introduced by the MEP refactor.
Discord post: https://discord.com/channels/1125469663833370665/1368305137424007239/1368305137424007239
I had misunderstood the `playOnEmptyField` argument of the "play" method responsible for animations. This parameter actually forces an animation to _always_ play. I removed the modifications I did to the play animation to skip this.
<details><summary>Properly not displaying field move animation</summary>
https://github.com/user-attachments/assets/58cd3975-95f4-452f-8d45-b7b08b714229
</details>
Load up a save and use a field move with the animations disabled.
- ~~[ ] **I'm using `beta` as my base branch**~~ Hotfix 1.9.4
- ~~[ ] Have I created new automated tests (`npm run create-test`) …
=> [Bug] Fix field moves always playing their animations

src/phases/message-phase.ts
Messages like those in fiery fallout will no longer display `s{item_fanfare}` improperly.
Fixes https://discord.com/channels/1125469663833370665/1357159700130566185/1357159700130566185, a bug that was caused by an oversight in #5537 
The bug was caused by the `#POKEMON` placeholder being inserted before finding the index of the `$` character, and then re-inserting the pokemon _before_ actually splitting the string. This caused issues where the index that the page was supposed to be split at would be different, if the pokemon's actual name was not 9 characters.
To remedy this:
Right after finding the page separator, I create the two pages with the text (page0 and page1), splitting the text as it was done already.
After it is split, _then_ we re-insert the pokemon names. We do this on both …
=> [Bug][UI/UX] Fix fiery fallout message bug

src/ui/ball-ui-handler.ts
"Cancel" button in Poké Ball selection menu is now localizable
To have it translatable
None
BEFORE (French)
AFTER (French)
Play the game in a language where it is translated (ideally in French, to be sure) and open the Ball menu during a battle
=> [Localization] Localizable "Cancel" text in Ball selection menu

src/ui/egg-gacha-ui-handler.ts
Latam Spanish Egg Gatcha texts adjusted
To have these texts properly sized
None
BEFORE
AFTER
Play the game in LATAM Spanish
=> [UI/UX] [Localization] Text ratio adjustment for es-MX Egg Gatcha

src/ui/starter-select-ui-handler.ts
Korean players will have a bigger starter information text
Text optimization for a better readability and an optimal use of the available text area in Korean
None
BEFORE
AFTER
Go to the starter select screen while playing in Korean
=> [UI/UX] [Localization] Update Korean starterInfoText

src/ui/ball-ui-handler.ts
None
Moved the location of the "Cancel" in a more logical locale file
None
No visual change
Just play the game and check if the "Cancel" button in Ball menu is properly displayed
=> Moved Ball "Cancel" label to a different locale file

biome.jsonc, src/data/mystery-encounters/encounters/the-pokemon-salesman-encounter.ts, src/data/trainers/TrainerPartyTemplate.ts, src/field/pokemon.ts, src/phases/revival-blessing-phase.ts, src/ui/login-form-ui-handler.ts
N/A
All TypeScript files should be checked with Biome. Performance is not significantly impacted by parsing the file.
- `src/field/pokemon.ts` removed from Biome's ignore list and Biome was applied to it.
- A rule to disallow the use of the `integer` type alias was added.
=> [Dev] Enable Biome checking of `pokemon.ts`

src/field/pokemon.ts, src/main.ts, src/typings/phaser/index.d.ts, src/ui-inputs.ts, src/ui/battle-flyout.ts, src/ui/battle-info/battle-info.ts, src/ui/battle-info/enemy-battle-info.ts, src/ui/battle-info/player-battle-info.ts, src/ui/fight-ui-handler.ts, src/ui/pokemon-info-container.ts, src/ui/summary-ui-handler.ts, src/utils/common.ts, test/testUtils/mocks/mockGameObject.ts, test/testUtils/mocks/mocksContainer/mockContainer.ts, test/testUtils/mocks/mocksContainer/mockGraphics.ts, test/testUtils/mocks/mocksContainer/mockRectangle.ts, test/testUtils/mocks/mocksContainer/mockSprite.ts, test/testUtils/mocks/mocksContainer/mockText.ts, test/testUtils/testFileInitialization.ts
N/A
There are mumblings of wanting to change parts of the battle ui. I took a look at the ui file to try to get an understanding of what is going on there, and it's in quite poor shape.
Created a new directroy, `src/ui/battle-info`.
Moved the old `battle-info.ts` file into it.
Converted `BattleInfo` into an abstract class, as it should never be instantiated itself.
I did not change any code logic. This was entirely just moving things around and cleaning up poor syntax to replace with equivalent code:
I didn't even clean up suspicious logic, such as this:
```ts
const baseVariant = !doubleShiny ? pokemon.getVariant(true) : pokemon.variant;
```
As that is not the point of this PR
- Made it so all methods now pass the `cognitiveComplexity` biome lint, by splitting up methods into smaller …
=> [Refactor][UI/UX] Cleanup battle-info ui code

test/testUtils/mocks/mocksContainer/mockText.ts
None
Fixes the signature and implementation of a few methods of the mock text object to reflect the actual signature of phaser's text object.
This is needed because I am using the method chaining functionality of Phaser to cleanup our ui files.
Makes mock text's `setVisible` and `setWordWrapWidth` return `this`, same as the method that they mock.
N/A
N/A
=> [Test] Fix mock text to make it compatible with method chaining

src/ui/battle-info/battle-info.ts, src/ui/battle-info/enemy-battle-info.ts
Fixes missing texture images for enemy boss battle bars
Fixes an oversight from #5696 
Fixes the improper images caused by the wrong key name being used.
Also fixes a missed use of posParams in the constructor.
The buggy image
Start up a run and get to a boss wave, and ensure that the boss hp bar renders properly.
=> [Bug] Fix improperly named sprite key for enemy boss' battle info bar

src/data/abilities/ability.ts, test/abilities/good_as_gold.test.ts, test/moves/alluring_voice.test.ts, test/moves/chloroblast.test.ts, test/moves/powder.test.ts, test/testUtils/gameManager.ts, test/testUtils/helpers/field-helper.ts, test/testUtils/helpers/moveHelper.ts
N/A
Improve test framework.
- Add `FieldHelper` which has methods to mock a pokemon's ability or force a pokemon to be Terastallized
- Add `MoveHelper#use` which can be used to remove the need for setting pokemon move overrides by modifying the moveset of the pokemon
- Add `MoveHelper#selectEnemyMove` to make an enemy pokemon select a specific move
- Add `MoveHelper#forceEnemyMove` which modifies the pokemon's moveset and then uses `selectEnemyMove`
- Fix `GameManager#toNextTurn` to work correctly in double battles
- Add `GameManager#toEndOfTurn` which advances to the end of the turn
<br>
- Disable broken Good As Gold test and add `.edgeCase` to Good As Gold
- Fix Powder test
- Update some tests to demonstrate new methods
=> [Test] Update test utils

.github/workflows/test-shard-template.yml, .github/workflows/tests.yml
None
Because until https://github.com/orgs/community/discussions/13261 is addresed, skipped jobs don't evaluate job names.
Reduced shards to 5 and changed job names.
Status checks requirements should now look like:
Run Tests (1) / Shard
We want to keep the skipped status as it is better than having the job just run and pass if it wasn't needed (as this can be confusing if something goes wrong and suddenly PRs that _should_ run tests are having tests skip).
=> [GitHub] Change total shard numbers and change job name

src/system/settings/settings.ts
If applicable, the Game Speed values in a number format more suited to their language (if not playing in English)
To allow to adapt values of Game Speed to the format of each language
None
BEFORE (French):
AFTER (French):
Play the game in another language, (currently preferably in French) and check the Game Speed values
=> Translatable Game Speed values

src/ui/fight-ui-handler.ts
Moves in the move selection menu during a battle are a bit more spaced (by the equivalent of 2 characters)
To equilibrate the space on both sides, and allow newly added languages to better fit when displayed on the left column. (because some have names way longer than any existing languages)
None
BEFORE
AFTER
Play the game and go the move selection menu during a battle
- [] Are all unit tests still passing? (`npm run test:silent`)
=> [UI/UX] Moves menu position adjustments

src/ui/settings/abstract-settings-ui-handler.ts
See the Screenshots/Videos section.
Requested by @Adri1 
In `abstract-settings-ui-handler`, we replace the concatenation of the i18nkey with the "Reload Required" localization with an asterisk, and set a variable indicating whether any setting requires reload.
Then, when adding items to the container, if any setting had reload required, then we add the text object to the page.
</details>
</details>
<details><summary>Before (Legacy)</summary>
</details>
<details><summary>After (Legacy)</summary>
</details>
Open up the settings page, and navigate to the display / audio pages.
=> [UI/UX] Move Reload Required text to bottom of settings

biome.jsonc, src/phases/move-effect-phase.ts
N/A
The ignore was forgotten to be removed.
Biome will now lint `src/phases/move-effect-phase.ts`.
=> [Dev] Enable Biome linting of `move-effect-phase.ts`

scripts/create-test/test-boilerplate.ts
=## What are the changes the user will see?
the newline in the test boilerplate script bothered me and @DayKev agreed
removed the demon within our ranks - the hideous extra newline has been vanquished
=> [Nit] Remove extra newline in test-boilerplate.ts

src/battle-scene.ts
Family of three Maushold and three-segment Dudunsparce will be available in the wild and on trainers.
Maushold and Dudunsparce forms were never available in the wild, while being available in mainline. This is probably an oversight due to their forms being added later in development. 
The forms were still available to the player evolving their Tandemaus and Dunsparce. 
The chance of 1/4 matches current evolve chance. 
Just two new form species data in battle-scene.ts
Both Maushold forms in the wild
Both Dudunsparce forms in the wild
```
OPP_SPECIES_OVERRIDE: SpeciesId.DUDUNSPARCE,
STARTING_LEVEL_OVERRIDE: 1000
```
Replace Dudunsparce with Maushold. Play the game and encounter both forms. 
Are there any localization …
=> [Balance] Add wild encounter chance to Maushold and Dudunsparce forms

src/data/moves/move.ts
Fog will now properly decrease the healing of Morning Sun/Synthesis/Moonlight and half the power of Solar Blade/Beam
Incorrect behavior.
https://bulbapedia.bulbagarden.net/wiki/Fog
Added Fog to two weather lists
Overrides
=> [Bug] Fix Fog interactions with Morning Sun/Synthesis/Moonlight and Solar Beam/Blade

src/data/mystery-encounters/encounters/fun-and-games-encounter.ts
User pokemon will no longer be stuck unable to move during the Wobuffet ME
Fixes https://discord.com/channels/1125469663833370665/1373765846458962083
In #5829 `resetSummonData` was split into two functions because of issues revealed by the Cud Chew PR. Because of code duplication, F+G had a `resetSummonData` call left over which needed to be `fieldSetup`. The actual reason for the zombie behavior is that `switchOutStatus` was not reset
Override to wave 10 with the Fun and Games encounter; ensure that after clearing the wave and advancing to the ME that it works as expected
=> [Bug] Fix zombie pokemon in Fun+Games ME

src/plugins/i18n.ts
An update to the locales submodule is included as it is necessary.
Our code linter + formatter (Biome) expects that any file named "biome.json" is a config file, but our locales had files named "biome.json" that were not config files for Biome. They have been renamed "biomes.json" to prevent them from being erroneously considered as config files.
There should be no change to the development experience, "biome" should still be a valid locales namespace as it has been mapped to the file rename to prevent the need for any change from developers.
Load up any run to ensure the biome name is still properly localized.
=> [i18n] Map "biome" namespace to the filename change to "biomes"

src/utils/common.ts
See abbreviations transalated
To have these translatable
None
BEFORE (French)
AFTER (French)
```
readonly STARTING_MONEY_OVERRIDE: number = 1520000000;
```
=> [i18n] Large Numbers Abbreviations Translation

src/phases/evolution-phase.ts, src/phases/form-change-phase.ts, src/system/game-speed.ts, test/testUtils/gameWrapper.ts, test/testUtils/mocks/mockVideoGameObject.ts
If I did everything right, none. Maybe a slightly smoother evolution sequence (idk if it's the video quality in the examples below but the original looks choppier).
I was trying to find the source of the memory leak that causes evolution assets to stick around (or whatever causes the slew of errors that sometimes happen after vigoroth evolves). I came across the evo-phase file and it is in poor shape and need of a refactor.
<details><summary>Also to avoid this that happens due to callback hell</summary>
</details>
Cleanup of the evolution phase and form-change-phase, primarily making proper use of phaser's `tweenChain` instead of adding the next tween after the previous one's `onComplete` method.
Note that I did not change the behavior of anything, other than to add a `canCancel` …
=> [Refactor] Refactor evo phase

biome.jsonc
N/A
Improved developer experience.
Biome's `lint/style/useBlockStatements` rule will automatically be applied without the developer needing to manually apply the fix (either in the IDE or by adding the `--unsafe` flag when running Biome from the command line).
Put `if (globalScene) console.log("test");` in some file and run `pnpm biome` (or `pnpm exec biome check --write path/to/file.ts`). If you have your IDE configured to automatically apply Biome on saving a file then it should automatically be modified without you needing to run Biome from the command line.
```ts
// this
if (globalScene) console.log("test");
// should become this
if (globalScene) {
console.log("test");
}
```
=> [Dev] Mark the fixer for Biome's `useBlockStatements` as "safe"

src/data/abilities/ability.ts
Shields down no longer blocks status setting in non-Red Core Forms
Shields Down no longer shows reset popup when it shouldn't 
Bugfix
Fixed conditionla to be less jank
Also cleaned up power construct `conditionalAttr`s (dw, it's around 4 locs)
DAMO PLS HALP IM ON MOBILE 
HALP I'M ON MOBILE
=> [Bug] Fix Shields Down blocking status in Core Form, unnecessarily resetting before battle

CONTRIBUTING.md
Slightly nicer docs
Linking to docs >> simply saying "clone the repo".
Replaced the "clone the repository" portion of the `CONTRIBUTING.md` procedure with a bullet point containing links to GitHub Docs pages for forking and cloning a repository.
=> [Docs] Add links to `CONTRIBUTING.md` for forking/cloning

test/testUtils/helpers/overridesHelper.ts
<## What are the changes the user will see?
N/A
Console log reverse mapping on `Weather` instead of `WeatherType`
Fixed issue
=> [Test] Fix incorrect reverse mapping in `overridesHelper.ts` log message

src/system/pokemon-data.ts
Some saves that were stuck on "loading" are now able to be loaded.
Partially addresses #6037; saves where a pokemon has no moves will no longer cause the run to be corrupted.
When the bug in #6037 is triggered, during serialization, the pokemon's moveset is written as null/undefined, causing it to be omitted from the json output.
To fix, all we have to do is add nullish coalescing and a default when loading from pokemon data. Specifically, in `src/system/pokemon-data.ts`:
```diff
-    this.moveset = source.moveset.map((m: any) => PokemonMove.loadMove(m));
+    this.moveset = source.moveset?.map((m: any) => PokemonMove.loadMove(m)) ?? [];
```
<details><summary>Successfully loading a previously broken save</summary>
https://github.com/user-attachments/assets/61026d88-1c7e-4546-b080-269de60ba …
=> [Bug] Prevent save corruption when loading a pokemonData that has no moves

src/data/battle-anims.ts
Less memory usage over time as waves progress
Memory leaks are a huge problem, and cause players, particularly on mobile devices, to crash after progressing through waves.
Plugging memory leaks will reduce the memory footprint of the game and reduce the frequency of these crashes.
Hopefully, this leak fixes most of the 
The `animationUpdate` event listeners are now removed from sprites during the `cleanUpAndComplete` method defined in the sprite's `play` method.
The listeners for `animationUpdate` were keeping references to several parts of the `EnemyPokemon`. This meant that an `EnemyPokemon` and all elements related to it would linger around in memory and not be garbage collected.
Every single enemy pokemon that was created (or player pokemon that were since released) would linger …
=> [Bug][Performance] Plug memory leak related to enemy pokemon lingering around

src/ui/text.ts
Text positon for header texts adjusted
[Japanese Text edits PR](https://github.com/pagefaultgames/pokerogue/pull/6026) introduced a padding for header texts in all languages while it was meant only for Japanese, it is now fixed
None
Aimed result (as it is still currently in main repo) :
Current state in beta:
Result after fix:
Check the game sections headers while visually comparing it to the current beta
=> [UI/UX] HEADER_LABEL TextStyle Fix

src/field/pokemon.ts
The caught indicator will no longer be greyed out for genderless pokemon, regardless of anything missing in the Pokédex
Fixes https://github.com/pagefaultgames/pokerogue/issues/5757 without introducing a new `DexAttr` field.
See #5935
Guard the `|=` for the `getDexAttr` to not incorrectly set `DexAttr.MALE`.
Previously, this was just checking if the solely if the mon was Female. If it wasn't, then it would set the bit flag for `Gender.MALE`. When checking against `dexAttr` to determine pokeball tint, it would check against the pokemon's gender. If genderless, this would never match.
```diff
-    ret |= this.gender !== Gender.FEMALE ? DexAttr.MALE : DexAttr.FEMALE;
+    if (this.gender !== Gender.GENDERLESS) {
+     ret |= this.gender !== Gender.FEMALE ? DexAttr.MALE : DexAttr.FEMALE;
+ …
```
=> [Bug] Fix grey caught indicator for genderless pokemon

biome.jsonc
N/A
Benjie mentioned wanting to disable the rule.
We use promises sparingly enough that the places where we _do_ use await in a for loop, there's usually a pretty good reason.
Also it becomes an especially large nuisance in tests (since advancing to phases is asynchronous)
Disabled rule
N/A
N/A
=> [Dev] Disabled biome `noAwaitInLoop` rule

src/@types/arena-tags.ts, src/@types/type-helpers.ts, src/data/arena-tag.ts, src/data/terrain.ts, src/data/weather.ts, src/enums/arena-tag-type.ts, src/field/arena.ts, src/field/pokemon.ts, src/system/arena-data.ts, src/system/game-data.ts
Wish is now usable, and persists across session saves.
#5932 broke wish due to a minor oversight.
This PR fixes that.
Fixes https://discord.com/channels/1125469663833370665/1348446393261621299/1348446393261621299
It also allows, for the first time, wish to work properly across saves.
Also lets neutralizing gas work properly across saves.
- Added missing implementations for `loadTag` to the SuppressAbilitiesTag and WishTag.
- Added many new types and type helpers for the purposes of type-safe parsing of arena data.
- Added a lengthy description at the top of `ArenaTags` that discusses changes
- Added a new abstract class, `SerializableArenaTag` to mark arena tags that should persist in save data.
- Simplified the body of `ArenaData`'s constructor to be more readable.
-  When creating an …
=> [Bug][Refactor] Fix loading arena tags

src/data/arena-tag.ts
Really quick PR, fixes a minor oversight from #6110 where `!targetIndex` was being used instead of `isNullOrUndefined`, meaning tags aimed at the player would be dropped. Mostly benign, but should still be fixed.
=> [Bug] Appropriately load future sight / doom desire when target index was player

.github/workflows/test-shard-template.yml, package.json
> [!NOTE]
> Copied from https://github.com/Despair-Games/poketernity/pull/1296/
N/A
Better testing - failed tests will now output console logs
Value is somewhat minimal with our GODAWFUL logging system ATM, but this at least paves the way for future improvements.
Changed package json to add command
N/A
Run tests and CI?
=> [Dev] test:silent now passes --silent='passed-only' to Vitest

src/data/balance/biomes.ts, src/init/init.ts, src/loading-scene.ts, test/test-utils/game-manager.ts, test/test-utils/helpers/overrides-helper.ts, test/test-utils/test-file-initialization.ts, test/vitest.setup.ts, vitest.config.ts
- **Removed `sanitizeOverrides`**
- **Moved initialization code to its own file**
N/A
It is nice to have all our init code in 1 place.
Also `sanitizeOverrides` did nothing as we mocked the module via vitest
Removed santize overrides
Moved init code to new file
Made a few internal interfaces in biomes.ts internal for reasons
N/A
Test the game?
=> [Dev] Remove `sanitizeOverrides`, consolidate initialization code into 1 file

test/moves/assist.test.ts, test/test-utils/helpers/move-helper.ts
N/A
To prevent mistakes when writing tests.
The helper function used to manually modify a Pokémon's moveset in tests will now disable the matching override.
=> [Test] `MoveHelper#changeMoveset` disables moveset overrides

src/@types/illusion-data.ts, src/data/abilities/ability.ts, src/field/pokemon.ts, src/phases/evolution-phase.ts, src/system/pokemon-data.ts, src/ui/party-ui-handler.ts, src/ui/summary-ui-handler.ts, test/abilities/illusion.test.ts
None, for the most part.
Players with existing sessions that had an active illusion out on the field, when loading in, will technically have the new fields missing from illusionData. However, nullish coalescing is used when checking against the fields anyway, so this is benign.
Illusion was overwriting some fields of the actual pokemon structure, and then holding onto the `basePokemon` inside of its data.
This was overly invasive, and was the cause of numerous bugs when illusion was first released.
Also, @Fontbane specifically asked devs to look into this. So I did :)
This change is also mandatory for the save migrator rewrite.
- Removed the `basePokemon` field from illusion, and added fields to illusion to replace them.
- When setting up an illusion, none of the pokemon's properties …
=> [Refactor][Bug] Illusion no longer overwrites data of original Pokemon

src/battle-scene.ts, src/system/settings/settings.ts, src/ui/summary-ui-handler.ts
New setting inside the Display section "Hide Username" that will change the username shown in the Pokémon summary next to "OT" from your real username to the name of the character you're playing (Amber / Kayle), as well as removing the ID No.
Pokérogue was designed to be accessible. Accounts can be created with just a username and password. Because of this simplicity, many players use insecure usernames and passwords. Additionally, usernames are displayed on the summary screen of your Pokémon under “OT.”
This often leads to people unintentionally “doxing” themselves when sharing screenshots of their Pokémon, posting videos, or streaming gameplay.
While some users choose a username unrelated to their real identity, others may use their regular online handle. Every year, numerous data …
=> [UI/UX] Added "Hide Username" Setting

src/@types/type-helpers.ts, src/data/pokemon/pokemon-data.ts
Smaller sizes of saved session data.
Writing the entire structure of `pokemonSpecies` when serializing data is completely unnecessary, as the data for a species is static. All we need are enough fields to reconstruct.
Also, this simplifies the zod schemas for the save migrator rewrite.
Added a `toJSON` method to `PokemonSummonData` that does a few things
- Null fields are replaced with undefined
- Fields that used `PokemonSpeciesForm` instead serialize an object containing the species ID and the particular form index.
- Fields (specifically `illusionData.fusionSpecies` serializes to just the speciesID.
- A new type helper, `CoerceNullProperitesToUndefined` was added.
No UI changes, and a video for this is sorta cumbersome.
Load up an old save that had a pokemon that would have serialized …
=> [Refactor] Prevent serialization of entire species form in pokemon summon data

src/utils/strings.ts
Challenge keys will look ok again
I did an oopsie with camel case-ing strings
Fixed the bug
TODO
go onto beta?
=> [Bug] Fix camel case bug in strings.ts

src/field/pokemon.ts, src/field/trainer.ts, src/modifier/modifier.ts, tsconfig.json
🤷 (Most likely no visible changes, maybe better performance)
Ability to use features from ES2021-ES2023.
All features of ES2021-ES2023 are now available for use (such as `Object.hasOwn()`, `Array#toSpliced()`, top level `await`, etc).
=> [Dev] Change `target` to `ES2023` in `tsconfig.json`

src/data/challenge.ts, src/system/achv.ts
- Expands the Fresh Start category of Challenges:
- True Fresh Start: The one you're used to, allows for only the first set of starters as if you're on a new account
- No Legendaries: Restricts starters to those in Common or Rare Egg tier
- Any Starter: Any starter can be selected, including legendaries
- All versions of this Challenge have these restrictions on starters:
- No Egg Moves, Passives, or Hidden Abilities. Mons with 2 non-hidden abilities can switch between them normally.
- Nature set to Hardy (neutral)
- All IVs set to 15
- No shinies, luck set to 0
- Tera type set to primary type
- The following species are locked to their base form:
- Pichu, Pikachu, Eevee
- Rotom
- Meloetta
- Froakie, Rockruff
- Zygarde can only be in one of its Aura Break forms
Are there any localization …
=> [Balance][Challenge] Added expanded Fresh Start options

src/phase-manager.ts, src/phases/check-biome-end-phase.ts, src/phases/check-interlude-phase.ts, src/phases/turn-end-phase.ts, src/phases/turn-start-phase.ts, test/phases/check-biome-end-phase.test.ts
When you defeat the final Pokémon at the end of a biome (waves 10, 20, ...), the battle will end immediately, meaning end of turn triggers (weather damage, berries, etc) won't occur. This prevents berries from being wasted when your party is about to be automatically healed anyway.
Requested by balance team.
A new phase (`CheckBiomeEndPhase`) is queued along with the other "end of turn" phases from within `TurnStartPhase` which removes the end of turn effect phases and sets a new field `TurnEndPhase#endOfBiome` to `true` on the currently queued `TurnEndPhase`, which causes most of the triggers to be skipped in that phase.
Defeat the last Pokémon of a biome (wave X0) with end of turn triggers that should occur (opponent's Future Sight, weather damage, Aqua Ring, etc) and observe that they …
=> [Balance] End of turn triggers won't occur when you end a biome

src/@types/arena-tags.ts, src/@types/battler-tags.ts, src/data/arena-tag.ts, src/data/battler-tags.ts
None
I found out that the signatures I chose for the `loadTag` methods in #6129 and #6110 was written in a way that typescript expected the `getters` to be present on the serialized tags. They aren't.
I found a relatively nice way of getting the object shape we are after that preserves type safety.
- Converted the leading comment in `arena-tags.ts` to an `@module` tsdoc.
- Rewrote the signature of `ArenaTagTypeData` to depend on the parameter of the arena tag's `loadTag` method.
- The serialized type essentially depends on the type that the tag's `loadTag` method expects, which is *precisely what we want*
- Added `BattlerTagTypeData` that mirrors `ArenaTagTypeData` for ArenaTags (this was forgotten in #6129)
N/A. There are no functional changes to the code.
N/A
- ~~[ ] Have I created new …
=> [Misc] Improve type signatures of serialized arena/battler tags

src/data/moves/move.ts, src/enums/move-flags.ts, test/moves/order-up.test.ts
Sheer force no longer boosts Electro Shot or Order Up
Sheer Force now boosts Thousand Waves (in-line with other trapping moves)
Life Dew and Jungle Healing now have the `.triageMove()` flag set
damo told me to
did what i was told
also documented the `makesContact()` flag bc wai not
=> [Balance] Updated SF/Triage interactions for moves

src/data/arena-tag.ts, src/data/battler-tags.ts
None
When working on Zod schemas, I found that permitting the `NonFunctionProperties` shorthand in `loadtag` methods messes with type inference (even though, in theory, it shouldn't. Thanks typescript).
Remove mentions of the third form of `loadTag` in the arena-tag and battler-tag comments.
Replace `NonFunctionProperties` in the signatures of `BattlerTags` with the other, "Pick" format.
N/A
N/A
=> [Misc] Disallow using NonFunctionProperties in loadTag methods

package.json
N/A
To make it easier to find and fix linting errors that can't be autofixed.
`--diagnostic-level=error` added to the `biome` command in `package.json`.
=> [Dev] `pnpm biome` will now only display errors by default

src/@types/battler-tags.ts, src/data/battler-tags.ts, src/field/pokemon.ts
Technically, saves which had an active dragon cheer that was at +2 will now be at +1. Though this is so niche it doesn't matter (and will be resolved once Zod schemas come in).
Apparently, I forgot to mark the `tagType` for some of the battler tags in #6129.
Also, I needed a way to get TypeScript to differentiate between battler tags that were using the generic battler tags for serialization. So, I created an interface for this.
- Adds additional type helpers to the battler tag type
- Adds the missing `tagType` field to all classes that didn't have one.
- Removed `DragonCheerTag`, instead reusing the `CritBoostTag`
- Rather than adding a save migrator (which has been deemed unnecessary for fleeting tags like this), added a new serialized field to the crit tag that tracks the number of …
=> [Misc] Fix missing types in battler tags and remove DragonCheerTag

src/phase-manager.ts
Exiting out of starter select screen will no longer hang the game.
Bugfix
Remove setting currentPhase to null
Trust
Open starter select, then try to leave it.
=> [Bug] [Beta] Remove setting currentPhase to null in clearAllPhases

src/data/balance/biomes.ts, src/data/balance/pokemon-evolutions.ts
Cosmog now evolves by high friendship (Requires 40 friendship, which is roughly 7 Rare Candies) instead of Level 23, and Cosmoem now won't spawn in the Flutes until it reaches Level 23. Buneary also sees a slight decrease in the amount of friendship required to evolve (70 Friendship -> 50 Friendship, roughly 8-9 Rare Candies rather than about 12 Rare Candies). 
damocleas edit:
In continuation with #6084, Cosmog has also had its evolution delayed to match the earliest it can be found. At level 60, it is forced from Cosmog to be Cosmoem
Cosmog, despite being given a custom evolution method in PokeRogue still has the issue of being deadweight on a team for a 7 cost Pokemon. While a player with full unlocks may not have the same trouble, players are typically given 3 more points to work with …
=> [Balance] Adjust Cosmog / Cosmoem Evolutions, Lower Buneary Friendship requirements

src/field/pokemon.ts
Enemy animations will show for users that play using local overrides.
Fixes #5871 
In `pokemon.ts` function `getMoveset` when returning `this.moveset` for enemy Pokemon, will return the new array created by the override.
Before:
https://github.com/user-attachments/assets/7325c813-2a90-492d-a586-102b0d743c38
After:
https://github.com/user-attachments/assets/fc22ee62-033e-4e75-979d-e56221d4fd16
```typescript
const overrides = { OPP_MOVESET_OVERRIDE: [MoveId.LIQUIDATION], MOVESET_OVERRIDE: [MoveId.SPLASH] } satisfies Partial<InstanceType<OverridesType>>;
```
Use Splash and then watch enemy use Liquidation.
- [] ~~Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?~~
=> [Bug] Fix override move animations not loading for enemy Pokemon

src/ui/party-ui-handler.ts
Players should now be able to release any fainted Pokémon in the "POKÉMON" party menu during a battle.
While testing https://github.com/pagefaultgames/pokerogue/pull/6186, @Blitz425 found out that fainted Pokémon couldn't be released from the in-battle party menu, which is cumbersome in a mode like Permanent Faint centered around having fainted Pokémon. The text that displays ("X has no energy left to battle!") also implies that this isn't intended behavior and only meant for trying to switch fainted Pokémon in.
The `if` block handling the release behavior was moved above the filtering code, which was using the `FilterNonFainted` callback preventing fainted Pokémon from being released.
https://github.com/user-attachments/assets/be2cdf91-d20a-43d7-9531-eb9578c59b50 …
=> [Bug] Release Fainted Pokémon in Switch Menu

src/ui/starter-select-ui-handler.ts
Changing forms after swapping a moveset and then starting the game will no longer cause that starter to have an empty moveset (#6037).
Pokemon with formes requiring multiple pokemon (Calyrex, Kyurem, Necrozma, and Hoopa) can now swap the positions of two moves that are in the moveset (#3937).
Fixes #3937 and the rest of what is needed for fixes #6037
Also, giving the SSUI the same treatment I have been giving other files (minor cleanup this time, the rest is too much of a behemoth).
- Code cleanup of SSUI (the "minor refactor" part)
- Use Phaser method chaning (i.e. replacing `var.method1(); var.method2()` with `obj.method1().method2();`)
- Condense multiple calls to `Container.add(child)` into a single `Container.add([child1, child2])`
- Misc cleanup (like using `x ||= y` instead of `x = …
=> [Bug][UI/UX][Refactor] Fix empty movesets related to starter forms and general SSUI cleanup

src/ui/starter-select-ui-handler.ts
One-liner PR to remove an extra `/ 6` which had been mistakenly added while merging conflicts for #6165 .
=> [UI/UX][Bug] Removed extra division by 6 in starter-select-ui-handler.ts

src/ui/save-slot-select-ui-handler.ts
Sessions in the session slot selection will once again show the pokemon icons.
Fixes a minor oversight.
Restore the accidentally deleted call to `setupWithData`
Go to load game and observe the team preview for the slot
=> [Bug] [UI/UX] [Beta] Fix icons not showing in save slot selection

package.json, pnpm-lock.yaml, src/account.ts, src/plugins/api/pokerogue-session-savedata-api.ts, src/system/game-data.ts, src/ui/run-info-ui-handler.ts, src/ui/save-slot-select-ui-handler.ts, src/utils/data.ts
Renaming a run will now work properly.
Fixes a bug in #5978 that prevented runs from being renamed when running on rogueserver (bug does not appear during local testing).
This actually *did* need changes to rogueserver: https://github.com/pagefaultgames/rogueserver/pull/63
- Added the `@types/crypto-js` package as a dev dependency to give proper typescript hints for the crypto-js dependency
- Cleaned up the `encrypt` and `decrypt` methods' bespoke logic.
- Fixed the `encrypt` function to call `toString` on the returned data. Before, it was not doing this, and the method was actually returning an object. Before #5978, the existing uses of this method were always being passed directly to `localStorage#setItem`, which calls `toString` on its argument anyway, bypassing this bug.
- De-nested a …
=> [Bug] [Beta] Fix renaming runs

test/mystery-encounter/encounters/the-pokemon-salesman-encounter.test.ts
nonononono
The recent surge of camel case renaming has caused test errors in tests checking for camel cased strings.
I dislike flaky tests.
destroyed the flakes
test flakes
=> [Test] Hopefully fixed salesman ME flaky test

src/phases/command-phase.ts
Pressing "Action" while the cursor is over a moveslot that does not have an occupied move in the moveset will no longer cause the game to hang indefinitely.
Fixes P1 Bug
Modify `queueFightErrorMessage` to take the move instead of computing it.
<details><summary>No more crash</summary>
https://github.com/user-attachments/assets/450052fb-8c42-4b43-a130-650299f461f4
</details>
Go into a game with a starter that has fewer moves available than 4. Probably on a fresh save.
Click fight, then try to press `ACTION` on one of the moves not in the user's moveset.
=> [Bug] [Beta] Prevent crash when attempting to select a move not in the user's moveset

src/data/arena-tag.ts, src/data/moves/move.ts, test/moves/aurora-veil.test.ts, test/moves/light-screen.test.ts, test/moves/reflect.test.ts
A 0.01% buff to the multipliers of Screens and Collision Course/Electro Drift (jk)
We need no game freak int precision jank in our codebase
Made numbers consistent with about every other effect that does this stuff
no
PLASE NOE
=> Removed last vestiges of `/ 4096` from codebase

.github/workflows/github-pages.yml, .github/workflows/linting.yml, .github/workflows/tests.yml
N/A
Some workflows that should be running on PRs to the `release` branch weren't running.
Updated GitHub workflow files to run on `release` branch and PRs to `release` branch as appropriate.
=> [GitHub] Workflows will now run on `release` branch

src/ui/starter-select-ui-handler.ts
This fixes a bug due to #6277 . The bug causes all iv unlocks to be permanently capped at 15 when opening starter select in fresh start and saving the game.
In this PR, a copy of `dexData` is made and overridden with the fresh start limitations.
When unpacking `dexEntry`, ivs are still being passed as a reference due to being an array, so they need to be unpacked individually. Not doing so caused the bug.
```ts
export interface DexEntry {
seenAttr: bigint;
caughtAttr: bigint;
natureAttr: number;
seenCount: number;
caughtCount: number;
hatchedCount: number;
ivs: number[];
ribbons: RibbonData;
}
```
```ts
export interface StarterDataEntry {
moveset: StarterMoveset | StarterFormMoveData | null;
eggMoves: number;
candyCount: number;
friendship: number;
abilityAttr: number;
passiveAttr: …
```
=> [Bug] Fresh start does _not_ override iv unlocks

src/data/battler-tags.ts, src/data/moves/move.ts
Title
Sheer Force no longer boosts Fickle Beam
Focus Energy gives +2 crit stages instead of +1
bugfix
moved a chance parameter outside of the `chance` field and into the function 
Fixed an inverted conditional for dragon cheer and co.
no
use dragon cheer
=> [Bug] Sheer Force no longer boosts Fickle Beam; Focus Energy gives +2 crit instead of +1

src/data/battler-tags.ts
When the leech seed user faints, the check to lapse the leech seed tag happens before the new user switches in---therefore, `source` does not exist at that time. Returning `false` causes the tag to be removed, we need to return `true` instead.
Example override to test:
STARTING_LEVEL_OVERRIDE: 1000,
MOVESET_OVERRIDE: [MoveId.LEECH_SEED, MoveId.MEMENTO],
Not sure if there are any edge cases where we would want to return false; the tag should stick there until the seeded pokemon leaves the field anyway, or some other effects removes it.
=> [Hotfix] Leech Seed does not get cleared when user faints

src/data/phase-priority-queue.ts, src/field/pokemon.ts, src/phase-manager.ts, src/phases/check-switch-phase.ts, src/phases/switch-phase.ts, test/abilities/intimidate.test.ts, test/test-utils/helpers/classic-mode-helper.ts
Intimidate and simlar abilities now trigger exactly once during an initial switch or page refresh with 1 party member. 
Not twice, not 0 times, ONCE.
Helping fix bugs
Fixes #6219 
Fixes #6249
The implementation is not clean at all, but our switch system really needs to be reworked eventually.
Added helper to start battle with initial switch
Added some emergency code to remove extra `PostSummonPhase`s and `ActivatePriorityQueuePhase`s upon confirming a force switch. \
Is it jank? Maybe. \
Does it work? Yeah
Added intimidate test that mirrors the found information
N/A
Enable the intimidate test and see that it does indeed fail instead of timing out
=> [Bug/Ability] Fixed bugs with Intimidate triggers after reload/initial switch 

src/ui-inputs.ts
The speedup and speed down buttons will now properly speed up / slow down the game.
Notably, the speedup button no longer sets the speed to 1x
Bugfix
Refactored `buttonSpeedChange`:
- No longer computes an i18nkey to determine setting to change to.
- Reduces code duplication
- General cleanup
<details><summary>After the bugfix</summary>
https://github.com/user-attachments/assets/fe2346fa-01af-4682-924b-29cd1afa51dc
</details> 
Go into game, look at settings. Press page up / page down. See the value change.
=> [Bug] Fix speedup/slowdown buttons not working properly

src/ui/battle-info/enemy-battle-info.ts, src/ui/battle-info/player-battle-info.ts
When a pokemon gains a third type (usually from trick or treat / forest's curse), the type icon will no longer be missing and in the wrong position.
Fixes a bug: https://discord.com/channels/1125469663833370665/1409134651120947280/1409134651120947280
Adjusted the texture name used for the type icon, and fixed its placement in `enemy-battle-info-ui`
https://github.com/user-attachments/assets/e43e2811-24d0-45b9-bba3-68d91802ee71
</details> 
https://github.com/user-attachments/assets/b25a4098-4442-4c27-aa24-e023d9767c0a
</details> 
```ts
MOVESET_OVERRIDE: MoveId.TRICK_OR_TREAT,
ENEMY_SPECIES_OVERRIDE: SpeciesId.SPEAROW,
```
- ~~[ ] Have I made sure that …
=> [Bug] [Sprite] Fix third type icon missing texture

src/data/abilities/ability.ts
Trace will now no longer always copy the same ability when used on the same wave.
Note that the original bug report seems to be slightly incorrect. Trace will not always copy the same slot. Rather, it will copy the same slot on the same wave. Meaning, if you switch out and in, the same pokemon was always selected.
Fixes #6396 
Kinda hard to show
Swap in / out with trace a bunch of times on the same wave
=> [Bug] [Ability] Fix trace's RNG

src/data/abilities/ability.ts
Cute Charm will once again properly cause the target to 
Fixes #6373 
The `addTag` method in the `PostDefendContactApplyTagChanceAbAttr` was erroneously passing the attacker as the source id. Fixed this. Also renamed some parameters.
<details><summary>Bugfix</summary>
https://github.com/user-attachments/assets/7fb52df2-ff90-4290-b510-5f1c7d1f021c
</details> 
See #6373
=> [Bug] [Ability] Fix cute charm

src/field/pokemon.ts
- Some mons encountered before they learn damaging STAB moves are now correctly guaranteed to have a damaging move
- This includes Trainer mons that are either too low level to learn TMs or don't learn a damaging STAB TM
- #5801 deleted a block of code that guarantees a damaging move for wild mons. This was because all mons were guaranteed a damaging STAB move now.
- However, there was an oversight with the way this was done. Originally, if a Trainer/boss mon didn't have a STAB damaging move in its movepool yet, it would just continue moveset gen without guaranteeing a damaging move.
- Now, the code block is restored, which is run if the `stabMovePool` is empty.
- This means every mon is now guaranteed to generate with a damaging move (if one exists in its movepool)
- Stated above
Are …
=> [Bug] Fix oversight where mons aren't guaranteed damaging moves if none are STAB

package.json
The version will display 1.10.5 on the homepage.
It turns out not bumping the version when we tweak something isn't the best idea, because we don't know if users are on the right version.
ran `pnpm update-version:patch`
=> [Misc] Bump version to 1.10.5 to main

src/field/pokemon.ts
An enemy pokemon is more likely to have low level moves, and trainer pokemon are more likely to have egg and TM moves.
Proposal with balanced, discussed on discord.
Currently there is a base linear weighting based on level primarily during moveset generation, meaning a move learned at level 60 is 60x more common than a move learned at level 1 before other factors are accounted for. This change increases the base weight to 20, meaning a level 60 move is only 4x as common as a level 1 move. This less directly boosts the frequency of TM and egg moves because they also utilise the same weighting system.
Too RNG heavy to really show.
The only way to truly see this is via utilising the console to generate hundreds of tests, the large influence of RNG in moveset generation means that any …
=> Adjust moveset generation weighting.

.github/workflows/create-release.yml, .github/workflows/deploy-beta.yml, .github/workflows/deploy.yml, .github/workflows/github-pages.yml, .github/workflows/linting.yml, .github/workflows/post-release-deleted.yml, .github/workflows/test-shard-template.yml, .github/workflows/tests.yml
N/A
Prevent workflows (tests specifically) from running for excessively long periods of time.
Workflows now have a time limit of 10 minutes (a couple of the simpler ones are set to 5).
=> [GitHub] Workflows will now time out after 10 minutes

src/phases/command-phase.ts
The root of this bug is an "oversight" from #5873 , where the line
`const targetPokemon = globalScene.getEnemyField().find(p => p.isActive(true));`
was replaced by
`const targetPokemon = globalScene.getEnemyPokemon();`
Due to the weirdness surrounding these functions, `isActive` can be `true` even if the mon is not on the field, which is why it was called with the parameter `onField` set to `true`. Similarly, `getEnemyPokemon` must be called with the parameter `false`, otherwise it also considers mons that have switched out.
This is relevant in the case of trying to catch a boss in the second party slot, after phazing out the boss in the first slot. This caused a bug reported in [this discord thread](https://discord.com/channels/1125469663833370665/1409970865415651511): even after the …
=> [Bug] Pokemon not on the field can't be caught

src/ui/battle-info/enemy-battle-info.ts
The ribbon will no longer overlap with the status effect, when the pokémon hasn't been caught
[Discord report](https://discord.com/channels/1125469663833370665/1238339524778790922/1411013791168336068)
The ribbon icon x position will be adjusted if there is no owned icon.
THe status effect already did that, which lead to the overlap
Before:
<details><summary>Without owned icon</summary>
<p>
</p>
</details> 
After:
<details><summary>Without owned icon</summary>
</details>
<details><summary>With owned icon</summary>
</details> 
Set the enemy pokémon to one, which has a ribbon, but hasn't been caught
```ts
ENEMY_STATUS_OVERRIDE: StatusEffect.SLEEP,
ENEMY_SPECIES_OVERRIDE: SpeciesId.GALLADE
} satisfies Partial<InstanceType<Overr
```
~~- [ ] Have I created new automated …
=> [Bug] [UI]Fix ribbon and status effect overlap

src/battle-scene.ts
Using tera during the e4 actually uses up tera.
Damo asked
Remove the check for being in wave 181-190 in classic from the tera code.
Tera during waves 181-190 and see if it uses up your tera.
=> [Balance] Make e4 not automatically recharge tera

src/data/challenge.ts
Monotype challenge desc no longer is jank
Removes snake case jank
Made the `getValue` call use the standard type i18n key
N/A
Do monotype challenge
=> [Bug] Fix monotype challenge using unlocalized type names

src/battle-scene.ts, src/data/battle-anims.ts, src/data/pokemon-species.ts, src/field/pokemon.ts, src/phases/egg-hatch-phase.ts, src/phases/evolution-phase.ts, src/phases/party-heal-phase.ts
The game should no longer occasionally crash when it's failed to load a sound file that it tries to play.
It was crashing in rare circumstances. https://discord.com/channels/1125469663833370665/1409451631740846120
Changes playSound to return null instead of returning the argument when it errors while playing the sound, as this caused multiple pieces of error handling code to fail. This caused multiple other functions to have to be changed to this new return signature, and adds several new checks throughout the codebase for failed sounds which should prevent similar errors in other places.
The easiest way to fake a sound failing to load is to delete the sound file. To test the specific bug which caused this delete the cry for a pokemon then faint that pokemon.
Are there any localization …
=> Sound error handling improvement

src/data/challenge.ts
The image when selecting a monotype challange will correctly show the type again
#6438 Localized the value for monotype challenges, which lead to them not matching the frame names.
[Bug report](https://discord.com/channels/1125469663833370665/1125894949020381285/1412432524482711573)
Replaced the localization with a `toLowerCase()`
There is no need to localize the monotype values, since they are only used for the image, which by itsself is already localized
</details> 
</details> 
Change the type in the challenge selct ui
~~- [ ] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?~~
=> [Bug] Fix monotype selector image

package.json, src/utils/common.ts, src/utils/utility-vars.ts
N/A
Simplify code (which will hopefully help the build process remove unnecessary code from production).
- The constant `isLocal` now checks to see if `import.meta.env.MODE` is `"development"` (which it is when running via `pnpm start:dev`) instead of checking what URL is being used to access the client (e.g. `"localhost"` or an IP address).
- Removes `start` from `package.json` and replaces it with `start:prod` (which runs `vite --mode production`) and `start:beta` (which runs `vite --mode beta`).
|   Command    | `isBeta` | `isLocal` |
| ------------ | -------- | --------- |
| `start:prod` | `false`  |  `false`  |
| `start:beta` | `true`   |  `false`  |
| `start:dev`  | `false`  |  `true`   |
- Removes obsolete/unused `localServerUrl` and `apiUrl` constants.
=> [Dev] Simplify `isLocal` and add `start:prod`/`start:beta`

src/data/mystery-encounters/encounters/training-session-encounter.ts, src/data/mystery-encounters/utils/encounter-dialogue-utils.ts, src/data/nature.ts, src/phases/scan-ivs-phase.ts, src/ui/abstract-option-select-ui-handler.ts, src/ui/admin-ui-handler.ts, src/ui/ball-ui-handler.ts, src/ui/battle-info/battle-info.ts, src/ui/battle-info/enemy-battle-info.ts, src/ui/battle-message-ui-handler.ts, src/ui/egg-gacha-ui-handler.ts, src/ui/fight-ui-handler.ts, src/ui/filter-bar.ts, src/ui/filter-text.ts, src/ui/form-modal-ui-handler.ts, src/ui/menu-ui-handler.ts, src/ui/modifier-select-ui-handler.ts, src/ui/pokedex-page-ui-handler.ts, src/ui/pokedex-ui-handler.ts, src/ui/pokemon-info-container.ts, src/ui/run-info-ui-handler.ts, src/ui/settings/abstract-binding-ui-handler.ts, src/ui/settings/abstract-control-settings-ui-handler.ts, src/ui/settings/abstract-settings-ui-handler.ts, src/ui/starter-select-ui-handler.ts, src/ui/stats-container.ts, src/ui/summary-ui-handler.ts, src/ui/text.ts, src/ui/ui-handler.ts, src/ui/ui-theme.ts
This method of `UiHandler`:
```ts
getTextColor(style: TextStyle, shadow = false): string {
return getTextColor(style, shadow, globalScene.uiTheme);
}
```
is just used to all the `getTextColor` utility function passing the ui theme, this is not necessary anymore since the utility functions can directly access `globalScene`.
There were a few more functions across the code which needed to pass `globalScene.uiTheme` as a parameter, which is not needed.
Reduce cluttering in the code.
The `getTextColor` utility function in `text.ts` does not need `globalScene.uiTheme` as a parameter anymore, this propagates to a few other functions that call it.
The `UiHandler.getTextColor` method has been removed.
Additionally, a few places where `globalScene.uiTheme` or `!globalScene.uiTheme` was used as a …
=> [UI/UX][Refactor] Remove redundant references to globalScene.uiTheme

src/battle-scene.ts, src/data/battle-anims.ts, src/data/positional-tags/positional-tag.ts, test/moves/delayed-attack.test.ts, test/test-utils/phase-interceptor.ts
Delayed attacks used by wild pokemon will not crash if the source is caught before the attack is released
Fixes a regression from the future sight PR.
Added the ye olde `?.scene` checks to the FS condition function
Added a test to make sure it was fixed
Added TODOs mentioning how we really need to get this shit together
N/A
run the new test in `delayed-attack.test.ts`
=> [Bug] Future Sight no longer crashes after catching the user

typedoc-plugins/typedoc-plugin-rename-svg.js
Docs site will not have broken link
broken link bad
Fixed the plugin that renames the SVG to only rename the `href` for the svg file.
N/A
`REF_NAME=beta pnpm typedoc --skipErrorChecking`
=> [Misc/Docs] Fix Typedoc workflow to not break the "go to main" link

src/phases/egg-hatch-phase.ts, src/phases/egg-summary-phase.ts
Reduced memory usage
Was looking at https://github.com/Despair-Games/poketernity/pull/882 and saw this would be easy.
Call `destroy` on the pokemon created in egg hatch phase and egg summary phase when their UIs are closed.
=> [Bug] Fix memory leak in egg hatch

src/touch-controls.ts, src/ui/settings/move-touch-controls-handler.ts, test/inputs/inputs.test.ts, test/test-utils/inputs-handler.ts
The changes can potentially make the mobile version of the game more accessible, including to devices which are not capable of sending "touch" events but still use some kind of point-and-click system, e.g. eye-tracking devices.
Difficult to test this (whether it still works as normal on phones, and whether there are any improvements on other devices) until the changes are on beta. So either we merge it and test directly on beta, or this PR can serve as a base to discuss alternative solutions.
=> [UI/UX] Use pointer events instead of touch events in `TouchControl`

src/battle-scene.ts, src/data/arena-tag.ts, src/data/battler-tags.ts, src/modifier/modifier.ts, src/phases/move-effect-phase.ts, src/phases/obtain-status-effect-phase.ts, src/phases/pokemon-phase.ts, test/battler-tags/substitute.test.ts
N/A
Needed to port another pr
Also returning `null` from a field pokemon getter is absolutely BORKED
Made function not return `null` and removed unneeded optional chains
=> [Refactor] Made `BattleScene.getPokemonById` return `undefined` instead of `null`

src/field/pokemon.ts
Bosses that have a trainer will no longer receive a random stat boost when a boss segment breaks.
Requested by balance
Inside `EnemyPokemon`'s damage method, the call to `handleBossSegmentCleared` is additionally predicated on `!this.hasTrainer()`. Note that, despite the method's poor name, it is only responsible for providing the stat boost). The boss segments are still cleared inside the damage method.
Go into a fight against a trainer that has a boss pokemon. Maybe Ivy.
=> [Balance] Trainer boss Pokémon no longer gain a stat boost when a boss segment is broken

src/data/balance/pokemon-evolutions.ts, src/field/pokemon.ts
Fusions with a secondary pokemon that is gender locked will now evolve properly based on the gender of the fusion pokemon instead of the gender of the base pokemon.
Fixes a bug reported: https://discord.com/channels/1125469663833370665/1414159874039873566/1414159874039873566
Actually use the `forFusion` parameter when checking fusions evolutions.
<details><summary>Magearne evolving with lechonk fusion</summary>
https://github.com/user-attachments/assets/9bab1d28-9628-4b36-819e-5d60d0b6e382
</details> 
```ts
STARTER_SPECIES_OVERRIDE: SpeciesId.MAGEARNA,
STARTER_FUSION_OVERRIDE: true,
STARTER_FUSION_SPECIES_OVERRIDE: SpeciesId.LECHONK,
ITEM_REWARD_OVERRIDE: [
{ name: "RARE_CANDY"},
],
STARTING_LEVEL_OVERRIDE: 100
``` …
=> [Bug] Secondary fusions with gender evo condition can now evolve

src/data/arena-tag.ts, src/data/terrain.ts, src/data/weather.ts, src/events/arena.ts, src/field/arena.ts, src/system/arena-data.ts, src/system/game-data.ts, src/ui/containers/arena-flyout.ts
After reloading the game the arena flyout will now correctly show the max duration of the effect, instead of just the remaining one.
> [!NOTE]
> For effects from already existing saves, the remaining duration will be shown. 
> The max duration is only saved for NEW effects
fixes #6521
- Weather, terrain and tags got an `maxDuration` property.
- The arena events also got this added and used when loading a session
<details open><summary>Video</summary>
https://github.com/user-attachments/assets/8acc4426-2330-467b-a11f-92d13d061355
</details> 
Use an ability/move that adds a weather/terrain/tag with a duration. then play the wave so the duration decreases and then reload and make sure the flyout still shows the max duration.
I mainly used these overrides to test:
```ts …
```
=> [UI/UX] Show correct max duration in flyout

package.json, pnpm-lock.yaml
None
Typedoc finally updated, so we can fix the bug that required us to hold it back.
Changed `typedoc` version to `^0.28.3` and then ran `pnpm up typedoc`
N/A
`pnpm typedoc`
=> [Deps] Bump typedoc version

src/data/abilities/ability.ts
Rivalry will no longer show any flyouts when it boosts damage.
This does not happen on cartridge. It's also annoying.
Removed the `true` argument that was being passed to `MovePowerBoostAbAttr`.
This is what I used.
```ts
ENEMY_ABILITY_OVERRIDE: AbilityId.RIVALRY,
ENEMY_GENDER_OVERRIDE: Gender.FEMALE,
STARTER_SPECIES_OVERRIDE: SpeciesId.ILLUMISE,
ENEMY_MOVESET_OVERRIDE: MoveId.FALSE_SWIPE
```
=> [Bug][Ability] Remove flyout for rivalry

src/@types/damage-params.ts, src/field/pokemon.ts
N/A
Cleanup docs for consistency
- Fixed up documentation to use the hyphen required by tsdoc
- Added missing doc to many methods/parameters
- Added `public` and `private` visibility specifiers to many mehtods
- Moved some types into the `@types` folder.
<details><summary>Showcase of docs appearing on destructured parameters</summary>
</details> 
`pnpm typedoc`, then open up the docs for pokemon in `typedoc/classes/src_field_pokemon.Pokemon.html`
=> [Docs] Cleanup docs in pokemon.ts

test/@types/vitest.d.ts, test/setup/matchers.setup.ts, test/test-utils/helpers/modifiers-helper.ts, test/test-utils/matchers/to-equal-unsorted.ts, test/test-utils/matchers/to-have-key.ts, test/test-utils/matchers/to-have-terrain.ts, test/test-utils/matchers/to-have-weather.ts
- **Added `toHaveKey` matcher + fixed imports**
- **Broke up the test matchers into multiple smaller interfaces**
- **Added restricted typing on matchers**
N/A
Map matcher: Benjie wanted it
Type safety: I wanted it
1. Added a matcher, `toHaveKey`, which takes a Map and asserts that its keys contain the given value.
2. Re-organized `vitest.d.ts` into sub-interfaces based on the category.
3. Added a utility type, `RestrictMatchers`, to restrict available matcher types based on the type of the assertion. This ensures that all matchers that _don't_ match the given argument will resolve to `never` (so you can't do `expect(1).toHaveFullHp()` or `expect("foo").toEqualArrayUnsorted([1, 2, 3])`).
4. Fixed the type declaration for `toEqualArrayUnsorted` to not be borked
N/A
Write some tests?
=> [Test] Added Map key matcher; enforced strong typing on matchers

src/field/pokemon.ts
The HP bar will update synchronously with the damage animation instead of immediately
Self explanatory probably
`updateInfo()` is called in the `DamageAnimPhase` already, so the call in `damageAndUpdate` is removed.
<p>
https://github.com/user-attachments/assets/821200ed-81f5-40cd-8b83-9a675b12a308
</p>
</details> 
<p>
https://github.com/user-attachments/assets/ee37c04e-e573-49fd-9ce9-8e406dfa12aa
</p>
</details>
=> [UI] Avoid prematurely updating HP bar when applying damage

src/dynamic-queue-manager.ts
Exp phases are no longer ordered by speed, no crash with `ShowAbilityPhase`s being queued after the turn (need to figure out why this is happening in the first place)
Parity
Add to array
Run tests
=> [Misc] Blacklist more dynamic phases

src/phases/encounter-phase.ts, src/phases/mystery-encounter-phases.ts
Switch prompt will appear on new waves as well as after summon
Fixing a bug I introduced with dynamic order
Simple code change, I had originally just neglected to account for the case that the pokemon is already on the field
Beat a wave on switch mode and ensure the prompt appears
=> [Bug] Fix `CheckSwitchPhase` not appearing on new wave

src/ui/handlers/login-form-ui-handler.ts
When clicking on the "show usernames" gear icon on the login screen, users will now see up to 7 sessions before getting the `ERR P02`
Requested by the helpers.
- Cleaned up the logic in `login-form-ui-handler.ts`
- Created a new constant `MAX_SAVES_FOR_USERNAME_PANEL` that is set to 7, instead of 2.
Don't even need dev server for this one. Just set `VITE_BYPASS_LOGIN=0` in `.env.development`, then spin up the server. Click on the gears.
=> [UI/UX] Show username now works with up to 7 local user accounts instead of 2

global.d.ts, scripts/create-test/create-test.js
N/A
I like cli args and this makes creating many tests easier
Added a few locs to the `create-test` CLI script that allow passing a single argument for the test type (skipping the interactive prompt entirely).
N/A
Run da script
=> [Dev] Added ability to pass in test type to `create-test` script from CLI

src/ai/ai-moveset-gen.ts, src/constants.ts, src/data/moves/move.ts, src/modifier/modifier-type.ts, src/ui/handlers/command-ui-handler.ts, src/utils/pokemon-utils.ts
Moves with dynamic types whose type change is intrinsic to the move and its user will now resolve to that type for the purposes of determining which type boosting item to spawn
Notably, this impacts these moves:
- Revelation Dance
- Same type as revelation dance would be when considering the user's real types (e.g. not a temporary one from Protean)
- Hidden Power
- Aura Wheel on Morpeko (will always allow both blackglasses and magnet)
- Techno Blast on Genesect - type of its current form instead of always normal. Normal on other mons
- Ivy Cudgel on Ogerpon
- Raging Bull on Paldean Tauros
- Judgement on Arceus
- Multi Attack on Silvally
- Tera Blast, allows both Tera Type and normal
- Will only consider tera type on mons that are allowed to Terastallize
- Player must have Tera Orb
As an …
=> [Bug][Balance] Make type boost items consider moves that have a variable type when rolling one for rewards

src/field/pokemon.ts, test/field/pokemon.test.ts, test/test-utils/helpers/field-helper.ts
Enemy trainer Pokémon will now have friendship based on the current wave.
Request from balance team.
Within the constructor for `EnemyPokemon`, the Pokémon's friendship value will be set based on the following formula if the fight is a trainer battle: `round(max friendship * (current wave / 200))` where the max friendship value a Pokémon can have is `255` and `current wave / 200` represents a % value based on how far in the game you are (e.g. on wave `100` the pokemon will have `50%` of the max friendship value: `round(255 * (100 / 200)) = 128`).
`pnpm test:silent pokemon`
=> [Balance] Enemy trainer Pokemon will have friendship based on the wave

src/field/pokemon.ts, test/abilities/gorilla-tactics.test.ts, test/moves/disable.test.ts
N/A
Simple + resolves TODO
Renamed method and added TODO to remove from codebase (since it's only use ATM is for tests)
N/A
Typecheck
=> [Misc] Rename `Pokemon.isMoveRestricted` to `hasRestrictingTag`

src/battle-scene.ts, src/data/abilities/ability.ts, src/data/moves/move.ts, src/field/pokemon.ts
None
(A miniscule less amount of data for ability instances due to flags being condensed into one field)
I dislike seeing these methods on abilities that are only meant to be used during initialization whenever I'm looking at them and accessing their parameters. This will clean up the intellisense for methods in 90% of the codebase.
- Renamed the `Ability` class inside of `abilities.ts` to `AbBuilder`, then created a new class, `Ability` to replace it.
- Renamed the is[...] properties to discard the `is`, and use `getters` that check a new `flags` field on the ability class
- Created a `build` method on `AbBuilder` that calls Ability's private constructor
- Removed the `implements localizable` field, which is a silly way of localizing fields when we can really just be using accessors.
N/A …
=> [Refactor] [Ability] Initializing abilities now uses a builder class

src/battle-scene.ts, src/data/mystery-encounters/encounters/safari-zone-encounter.ts, src/data/pokemon/pokemon-data.ts, src/phase-manager.ts, src/phases/check-switch-phase.ts, src/phases/encounter-phase.ts, src/phases/game-over-phase.ts, src/phases/init-encounter-phase.ts, src/phases/mystery-encounter-phases.ts, src/phases/post-summon-phase.ts, src/phases/summon-phase.ts, src/phases/title-phase.ts, src/queues/post-summon-phase-priority-queue.ts
`PostSummonPhase`s run properly in all situations (checkswitch + switch, checkswitch + no switch, new waves, reload, ...)
I was trying to bandaid over the terrible encounter system (see the 4 files of duplicated code) to avoid upsetting things before 1.11, but at a certain point it's too much. If all is well this should be much more robust. 
Do note that `InitEncounterPhase` is still working around a terrible system and is likely not the ideal solution. It's good enough for now and can be revisted later when refactors make it to this area.
`InitEncounterPhase` is pushed after the last `CheckSwitchPhase` and queues PSPs for all pokemon where it's necessary (summoned this turn or an enemy). This means I also undid a lot of the previous changes I had made around `CheckSwitchPhase` in …
=> [Bug] Use InitEncounterPhase to queue PSPs for new encounters
