pagefaultgames/pokerogue

src/data/ability.ts

implement_hustle_ability

---

src/data/ability.ts

implement_sand_rush_ability

---

src/data/ability.ts
src/pokemon.ts

Implement solarpower

---

src/data/move.ts

Makes a bunch of basic generation 7 through 9 moves functional. Also gives PLA and generation 9 moves their descriptions.

Implement moves with basic functionality

---

src/data/move.ts
src/field/pokemon.ts

Implement Freeze-dry hitting super-effectively against Water types. 
VariableMoveTypeMultiplierAttr is probably redundant as i cant recall a single move that would function similarly to Freeze-dry but maybe it can be used for something else too.

Implement freezedry

---

src/data/move.ts

Foul play uses target attack as its own.

Implement Foul Play

---

src/data/move.ts
src/field/pokemon.ts
src/phases.ts

These moves ignore opponents defense and evasion stat changes

implement Darkest Lariat, Chip Away and Sacred Sword

---

src/data/ability.ts

Tested Stamina to make sure that it activates on Physical and Special moves, but not on Status ones. It also activates multiple times when hit by multi-hit moves, as specified in the wiki: https://bulbapedia.bulbagarden.net/wiki/Stamina_(Ability)
Also tested Weak Armor, only activates on Physical (can be contact or not) moves (not Special nor Status) and still activates mutliple times from multi-hit moves, as long as they are Physical. https://bulbapedia.bulbagarden.net/wiki/Weak_Armor_(Ability)

Implemented the abilities Stamina and Weak Armor

---

src/data/ability.ts
src/data/move.ts

Implements Regenerator.
Also made it so that forced switching also activates PreSwitchOut abilities such as Natural Cure and Regenerator.

implement Regenerator

---

src/egg-hatch-phase.ts

scene wasn't clearing game objects between hatches when there were multiple
hopefully will fix crashes/slow down from too many hatches

Hatch Cleanup

---

src/data/ability.ts

Implemented many easy to implement abilities, where framework already existed. All have been tested as working as expected. 
Multiscale and Shadow Shield get announced if hit by fixed damage move while at full hp, but correctly do not reduce the incoming damage.

Implement Multiscale, Solid Rock, Filter, Justified, Water Compaction, Soul-Heart, Shadow Shield, Prism Armor

---

src/data/ability.ts

Implemented Ice Scales using the fur coat logic changed for special moves. Tested for and confirmed working

Implement Ice Scales

---

src/ui/starter-select-ui-handler.ts

it was assuming that the starterMoveData wouldn't have a property for the form but when I checked, it had the property and it as never updating that array

Fix Calyrex Rider uanble to change starter moves

---

src/data/ability.ts
src/field/pokemon.ts

Added type changing abilities: Pixilite, Refrigerate, etc.

Add type change abilities

---

src/ui/starter-select-ui-handler.ts

moved it to its own function so it was easier for me to read

Additional Move Change Fixes

---

src/data/ability.ts
src/data/move.ts

Implements priority increasing abilities Triage and Gale Wings. 
Added a custom move flag for a move that is affected by Triage.

Implement Triage and Gale Wings

---

src/data/move.ts

Support both type changing and power boosting

Add support for weather ball

---

src/data/move.ts

I wanted to use it, so I coded it.

Fillet Away

---

src/data/dialogue.ts
src/data/trainer-config.ts

Implemented lines for every unique trainer and some lines for generic trainers

Trainer Dialogue

---

src/data/pokemon-species.ts

Diancie is gender unknown, so I've removed its gender.

Remove Diancie's gender

---

src/data/move.ts

Comprehensively testing this is hard, but it seems to work from a few random tests.

Add support for hidden power

---

src/data/move.ts

Updated ForceSwitchOutAttr

---

src/data/ability.ts
src/field/pokemon.ts

Tested in localhost with a Murkrow, was applying the crit increase correctly with Super Luck, and didn't increase without it

Added support for Super Luck with BonusCritAbAttr

---

src/data/ability.ts
src/phases.ts

Does not proc from self targeted stat reductions, like the games.

Defiant implementation

---

src/data/move.ts

Also Lava Plume -> Flamethrower, single target

Fixes Nature Power random targeting.

---

src/data/ability.ts

Added Thermal Exchange's effect of increasing attack after being hit by a fire move. Removed (P) as it should be complete now.

Implement Thermal Exchange

---

src/data/move.ts

Unique Nature Power move for all biomes, no overlap with terrains

Nature Power move for all biomes

---

src/data/move.ts

I missed this one, this should be all of them now. 
https://bulbapedia.bulbagarden.net/wiki/Fly_(move)

Smack down should hit target charging fly

---

src/battle-scene.ts

Just added this line for the actions handled by shoulder buttons.  `tsthis.setLastProcessedMovementTime(Button.TYPE);`

Fix shoulder buttons not working issue

---

src/data/move.ts
src/field/pokemon.ts

The override is to ensure that any move that makes it to this point in the damage calculation with a power <= 0 will do 0 damage.

Present implementation, adds a 0 dmg override for 0 power moves.

---

src/field/pokemon.ts

Fix paralysis speed drop

---

src/data/move.ts
src/locales/en/move.ts
src/locales/fr/move.ts
src/plugins/i18n.ts

Started implementing i18n for Pokémon moves, with the aim of providing translations to French.
Additionally, I've noticed some laggy autocomplete TypeScript behavior, I am doing this the right way ?

i18n for Pokemon moves

---

src/data/move.ts

Edited Electro Shot to raise stat before attacking

---

src/data/move.ts

- Implemented Payback.
- Power doubles if the target moves before you or uses an item.

Implemented Payback

---

src/data/move.ts
src/data/type.ts
src/field/pokemon.ts
src/ui/battle-info.ts

Updates the UI and type effectiveness to support three types, and makes old moves that change types update the UI.

Implement Soak, Forest's Curse, and Trick-or-Treat

---

src/data/move.ts

Gyro ball has its own damage calculation formula instead of just using the inverse of Electro ball's

Fix gyro ball base power

---

src/field/pokemon.ts

Turns out this is how it's meant to work

Make it so you can't freeze in sun

---

src/data/move.ts

Added Freeze Shock's charge turn

Fixed Freeze Shock

---

src/data/pokeball.ts
src/locales/en/pokeball.ts
src/locales/fr/pokeball.ts
src/plugins/i18n.ts

The names of the pokeball were hard coded, I edited that to use i18n and I added the french translation for the pokeball.

pokeball: implement i18n on pokeball name and add french translation

---

src/data/move.ts

Implemented Stomping Tantrum

---

src/data/ability.ts

Checked it works when the defender faints and when the defender is hit by a multi hit move.
Checked it works for both player and opponent.
First PR and first time touching JS/TS so I may well have done something dumb.

Implemented Toxic Debris

---

src/data/ability.ts

Adds a simple PostSummonAllyHealAbAttr, pretty unique to the case of hospitality I think.

Implements hospitality

---

src/ui/fight-ui-handler.ts

Adds the move category sprite next to the move type sprite on the Fight UI as a QoL change

Added the move category icon to the Fight UI

---

src/battle-scene.ts
src/data/ability.ts
src/locales/en/ability.ts
src/locales/es/ability.ts
src/locales/fr/ability.ts
src/plugins/i18n.ts

I did it in the same way moves were done.

Support localization of Pokémon abilities

---

src/ui/fight-ui-handler.ts
src/ui/summary-ui-handler.ts

-Pressing Button.LEFT now shows the stats summary page
-Pressing Button.RIGHT goes back to move selection page

Added a way to see the pokemon stats in the Learn Move Phase

---

src/data/ability.ts
src/data/move.ts
src/field/pokemon.ts

Split off from #159 (the other part is in #231)
Implements:
- Damp
- Explosive move attribute
- Mind Blown and Steel Beam have behavior different from recoil where they take the half damage even if the move doesn't hit
- Misty Explosion powers up in Misty Terrain

Implemented explosive moves and Damp

---

src/data/move.ts
src/field/pokemon.ts

ExplosiveAttr was erroring if the target died and mind blown/steel beam were never reducing HP.

Fix mind blown/explosion moves

---

src/locales/fr/move.ts

Switched all apostrophes ' to ’ , being to one used in the games

Update apostrophes in move.ts

---

src/data/move.ts

adds missing brackets to psycho shift attribute to fix unreachable condition

Psycho Shift Unreachable Code Warning Fix

---

src/locales/fr/move.ts

Fix issue #312 -> set proper french name for move "smog"

---

src/locales/fr/move.ts

French moves typos

---

src/phases.ts

Idea as mentioned on discord, tested every scenario I could think of.

Fix end catching

---

.gitignore
src/battle-scene.ts
src/field/arena.ts
src/field/pokemon.ts
src/game-mode.ts
src/overrides.ts
src/phases.ts

Puts all the overrides into a single file, should make things much more resilient to accidentally merging overrides.

Refactor overrides

---

src/locales/de/menu.ts
src/locales/en/menu.ts
src/locales/es/menu.ts
src/locales/fr/menu.ts
src/locales/it/menu.ts
src/ui/daily-run-scoreboard.ts
src/ui/title-ui-handler.ts

Added missing menu translations.
- Rankings
- Daily Rankings
- No Rankings
- Loading...
- Players Online

Added missing menu translations

---

src/ui/starter-select-ui-handler.ts

- Fix Pokerus tutorial condition in `src/ui/start-select-ui-handler.ts`

Fix Pokerus tutorial condition

---

src/locales/fr/tutorial.ts

- Fix the length problem of some strings that aren't readable in the game
> ![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/58cd3448-3f52-4680-9954-896a799b1433)
- Fix a few typo errors
---
Based on PR #348

Fix tutorials translation fr

---

src/ui/battle-message-ui-handler.ts
src/ui/text.ts

add a new color SUMMARY_GREEN in text.js, add the green color if the iv of the pokemon is better than the iv on the starter of that pokemon

Add color for the IV scanner

---

src/modifier/modifier-type.ts
src/phases.ts
src/ui/party-ui-handler.ts

When selecting a move through the party UI (like using an ether) the current PP and the max PP for each move shows up.

Select Move UI Shows PP

---

src/data/move.ts
src/field/pokemon.ts

Currently scales from 0-5 items

Implement Acrobatics

---

src/locales/fr/tutorial.ts

Translation of "statChange" + some remaning typos

Updated French transaltion for tutorial.ts

---

src/data/move.ts

Fixes this bug: https://discord.com/channels/1125469663833370665/1235920954828521555

Bugfix: Ensure direct stat modifying moves update both pokemon's stats

---

src/data/ability.ts

Each time your mon drops below half HP, the stat effect activates, giving them either +1 Atk/SpA/Spe and -1 Def/SpD for Anger Shell, or +1 SpA for Berserk.
This is my first time contributing, so lemme know if I fucked up anything :)

Implement Anger Shell and Berserk

---

src/data/move.ts

Fixes https://discord.com/channels/1125469663833370665/1236055454405234799

Bugfix: Ensure recoil moves always do at least 1hp in recoil

---

src/ui/summary-ui-handler.ts

Fixed the bug where longer descriptions scroll stuck shorter ones

Longer descriptions don't stuck shorter ones anymore

---

src/locales/fr/tutorial.ts

Changes made after in game test

Update French tutorial.ts

---

src/field/pokemon.ts

The AI couldn't decide who to target with CounterDamageAttr  moves which don't need a target. This change makes an exception. Now functions the same as when the player selects one of these moves.
https://github.com/pagefaultgames/pokerogue/assets/13838608/eec01947-2407-4fe2-986d-c1f431728b9d

Fix Enemy Counter Moves

---

src/data/ability.ts

Must have gotten lost while I was resolving conflicts

Add in missing import

---

src/field/pokemon.ts

Realized there was an enum for the -1 value which should help clear up confusion if someone has to mess with this code later

Removed Hardcoded Values

---

src/data/move.ts

Tickle, Tearful Look and Decorate caused the second stat to be changed to "stack" on itself causing it to reduce/increase the stat multiple times.

Bugfix Tickle, Tearful Look, Decorate

---

src/data/ability.ts
src/phases.ts

Adds `StatChangeCopyAbAttr`, copying any positive stat changes that happen on the opponent's side and applying them to the ability user as well.

Implement Opportunist

---

src/phases.ts

Fulfills this suggestion https://discord.com/channels/1125469663833370665/1206721468160024597/1236456011951247370

PP Up/Max now show current PP on the move select

---

src/system/settings.ts

Remove code intended only for debugging.

Remove Debug Code

---

src/data/ability.ts

Fix [483](https://github.com/pagefaultgames/pokerogue/issues/483)

Issue-483: Fix contact effects after death

---

src/data/ability.ts

Fixes https://discord.com/channels/1125469663833370665/1236694210959118466 in a balanced way

1hp Sturdy mons no longer display their ability tag

---

src/data/move.ts

Fixes https://discord.com/channels/1125469663833370665/1236710869874770012, amongst others.

Fix issue with self switch moves causing softlocks

---

src/data/move.ts

Take Heart currently does not cure the Sleep condition, which misses the edge case of the move waking up the user when called by Sleep Talk.

Implement Take Heart Sleep Talk edge case

---

src/data/ability.ts
src/data/move.ts
src/phases.ts

Fixes https://discord.com/channels/1125469663833370665/1176874654015684739/1236735272113147944

Fix blank fail text on switch out moves

---

src/inputs-controller.ts
src/ui/menu-ui-handler.ts

Fix - stop repeating key when focus is lost

---

src/inputs-controller.ts

Fix for:
https://discord.com/channels/1125469663833370665/1236706378350067762
this behaviour before was a bug, but players got used to it, so i kinda tried do the same things, it's not perfect, but it's better than nothing i guess.
context:

Inputs - Allow 2 buttons to be pressed at the same time

---

src/locales/de/move.ts

updated move.ts with german translation

updated move.ts german translation

---

src/field/pokemon.ts
src/locales/de/battle.ts
src/locales/en/battle.ts
src/locales/es/battle.ts
src/locales/fr/battle.ts
src/locales/it/battle.ts
src/phases.ts

Fixed an issue where moves marked as (N) would prevent you from being able to Struggle.
Also fixes messaging so that a message shows when you are out of PP, Disabled, or trying to use an unimplemented move consistently.
https://github.com/pagefaultgames/pokerogue/assets/13838608/22522dbe-ce8d-4185-9dcc-b1986462fe9a
https://github.com/pagefaultgames/pokerogue/assets/13838608/fde6c524-af9b-44cb-b1ec-0c1f8e3b6803
https://github.com/pagefaultgames/pokerogue/assets/13838608/bdd8fd94-6d96-4b3d-8b3a-b7f10ed132a8
https://github.com/pagefaultgames/pokerogue/assets/13838608/4f83baba-667f-45ea-85b8-a81e97845c83

Fixes Struggle Softlock

---

src/locales/de/config.ts
src/locales/en/config.ts
src/locales/es/config.ts
src/locales/fr/config.ts
src/locales/it/config.ts
src/plugins/i18n.ts

the imports are going to quickly become more overwhelming if it continues as is
this keeps all imports within their locale file and makes the i18n file much smaller and easier to look at

I18n import cleanup

---

src/battle-scene.ts
src/field/pokemon.ts
src/overrides.ts

add override to force double battles.
add override for passive abilities.

double battle and passive overrides

---

src/data/ability.ts
src/field/pokemon.ts

- change the attribute apply to more properly use the cancelled param
- apply the attribute for active and passive abilities
- mark minds eye as partially implemented

fix scrappy and mindseye working as passive ability

---

src/locales/fr/battle.ts

Fix after global edit to "notDisabled"

Fix French battle.ts

---

src/battle-scene.ts
src/field/arena.ts
src/field/pokemon.ts
src/game-mode.ts
src/modifier/modifier.ts
src/overrides.ts
src/phases.ts

Also made the move overrides be the full set in case you want to set all 4

Cleanup overrides and imports

---

src/locales/de/starter-select-ui-handler.ts
src/locales/de/tutorial.ts

Tutorials and UI Buttons into German
All translation done by discord user larus21
All tutorials tested and adapt to the layout

German - Tutorials and UI Buttons

---

src/data/move.ts

Switches the values in 2 arrays to switch the stat changes.
[Example](https://cdn.discordapp.com/attachments/1238648346999259239/1238779634569580596/firefox_yn5xF45Azn.gif?ex=664086f0&is=663f3570&hm=7f5ad13606b24dcf051fcb41bbcfcabd57097b4b5b3f3c8f7da9cb4f8b2b3b11&)

Heart Swap implementation.

---

src/field/pokemon.ts

Hopefully this causes less use of getAbility in PRs.

Add tsdoc comments for ability getters

---

src/field/pokemon.ts

Added a check for grounded battle tag in the isGrounded method.

Fix Roost doesn't ground correctly.

---

src/data/ability.ts

Technician considers variable power moves

---

src/field/pokemon.ts

Update isGrounded check

---

src/battle-scene.ts
src/overrides.ts
src/system/game-data.ts

added override check into loading session and reset so it can be done on new game or continuing an existing save

add pokeball override

---

src/data/ability.ts
src/locales/de/ability-trigger.ts
src/locales/de/config.ts
src/locales/en/ability-trigger.ts
src/locales/en/config.ts
src/locales/es/ability-trigger.ts
src/locales/es/config.ts
src/locales/fr/ability-trigger.ts
src/locales/fr/config.ts
src/locales/it/ability-trigger.ts
src/locales/it/config.ts
src/locales/zh_CN/ability-trigger.ts
src/locales/zh_CN/config.ts
src/plugins/i18n.ts

Adds the base files needed to start translating Ability trigger messages. Provides one as an example.

Added Ability Triggers Localization

---

src/data/move.ts

Addresses [Bug report](https://discord.com/channels/1125469663833370665/1239239877514498101)
Also corrects comeuppance's power to --- in UI.

Fix Comeuppance doing no damage with multi-lens

---

src/field/damage-number-handler.ts

corrected u turn and flip turn crash

---

src/locales/de/ability-trigger.ts

An example sentence.
> Glumanda wurde durch Steinhaupt vor Rückstoß geschützt!
But you could also do
> Steinhaupt von Glumanda schützte es vor Rückstoß!
Unsure if this is a string from the original game, I'll have to view the other game files later.

Recoil Translation DE

---

src/data/move.ts

Added comments to a few base classes in move.ts. Did a lot of experimentation in order to do so. Will be making some kind of write-up about it to explain the reasoning for things. 
I also spent about 5 hours fixing all of the errors in order to get typedoc working and when it finally generated html documentation it had nothing in it. This commit obviously doesn't contain these changes, but I just wanted to mention it.

Added Comments to Base Classes

---

src/locales/de/battle.ts
src/locales/en/battle.ts
src/locales/es/battle.ts
src/locales/fr/battle.ts
src/locales/it/battle.ts
src/locales/pt_BR/battle.ts
src/locales/zh_CN/battle.ts
src/phases.ts

Resolves #875
Translations for:
- _"1, 2, and ... ... ... Poof!"_
- _"And..."_
**Tested on local**

Add missing translation for learning move

---

src/locales/de/modifier-type.ts
src/locales/en/modifier-type.ts
src/locales/es/modifier-type.ts
src/locales/fr/modifier-type.ts
src/locales/it/modifier-type.ts
src/locales/pt_BR/modifier-type.ts
src/locales/zh_CN/modifier-type.ts

Fixed the issue with the incorrect translation key for ‘Never-Melt Ice’.

Fixed the incorrect translation key for ‘Never-Melt Ice’

---

src/locales/de/starter-select-ui-handler.ts

- added uncaught
- corrected ability

Update GER translations starter-select-ui-handler.ts

---

src/locales/de/weather.ts

added translations for each weather-type

Added weather.ts GER translations

---

src/data/trainer-config.ts

i18 was not initalized correctly (to late). So i added that i checks that before starting (like it does for titles etc)

Fixes that brocks name is undefined

---

.gitignore
src/data/move.ts

Adjusted all existing comments in move.ts to match. This should help when new Pull Requests are made as there are multiple examples to work from.
There are no functionality changes here, it's all comments.

Adjust all Existing Comments to Match

---

src/locales/fr/weather.ts

Added missing verb in this sentence.

Added missing word in /locales/fr/weather.ts

---

src/locales/de/config.ts
src/locales/en/config.ts
src/locales/es/config.ts
src/locales/fr/config.ts
src/locales/it/config.ts
src/locales/zh_CN/config.ts

Fixed issue #975 and organized config files. ptBR will be fixed later with another PR.

Organized localization configs and fixed chinese config

---

src/data/berry.ts
src/locales/de/berry.ts
src/locales/de/config.ts
src/locales/en/berry.ts
src/locales/en/config.ts
src/locales/es/berry.ts
src/locales/es/config.ts
src/locales/fr/berry.ts
src/locales/fr/config.ts
src/locales/it/berry.ts
src/locales/it/config.ts
src/locales/pt_BR/berry.ts
src/locales/pt_BR/config.ts
src/locales/zh_CN/berry.ts
src/locales/zh_CN/config.ts
src/plugins/i18n.ts

Implements localization for BerryType.

Implements localization for BerryType

---

README.md

ok that's the change
now I am seeking the UI function like explanation, yep
help
thanks
do not ask for if UI supports controller, that doesn't help me, cuz if it doesn't support controller basically if you'd draw one of those mindmaps, I'd draw thousands of arrows that point back to --> Aslong I don't understand the UI functions, how one gonna make UI work right
I mentally died going through them, maybe if I give it ago another time, maybe I can figure out, but for now, no.
Hmmmmmm
Check out other great posts:
https://github.com/pagefaultgames/pokerogue/issues/1075
Channel is not named vote anymore or never was. I was seeking for vote but I didn't find vote, so feature-vote

#vote to #feature-vote

---

src/data/move.ts
src/data/pokemon-species.ts

This PR implements the move Beat Up. It's a pretty unique move with mechanics not found anywhere so a lot of this code is tightly coupled together.
[How Beat Up works](https://pokemondb.net/move/beat-up)
https://github.com/pagefaultgames/pokerogue/assets/59787978/fd0c4692-1b64-4488-ab5a-9ffc58a33e93

Implement Beat Up

---

src/locales/de/config.ts
src/locales/de/voucher.ts
src/locales/en/config.ts
src/locales/en/voucher.ts
src/locales/es/config.ts
src/locales/es/voucher.ts
src/locales/fr/config.ts
src/locales/fr/voucher.ts
src/locales/it/config.ts
src/locales/it/voucher.ts
src/locales/pt_BR/config.ts
src/locales/pt_BR/voucher.ts
src/locales/zh_CN/config.ts
src/locales/zh_CN/voucher.ts
src/plugins/i18n.ts
src/system/voucher.ts
src/ui/vouchers-ui-handler.ts

Locales for Voucher names + Voucher rewards

---

src/data/ability.ts
src/data/move.ts
src/phases.ts

Made new move attribute `IncrementMovePriorityAttr`

Implement Grassy Glide

---

src/data/move.ts
src/field/pokemon.ts
src/phases.ts
src/ui/party-ui-handler.ts

If an enemy trainer uses it, for now it picks a random dead pokemon on their team that is not a boss and revives it
Tested on singles and doubles with enemy trainers, but there's probably some edge cases where it breaks

Implement Revival Blessing

---

README.md

Added selstar to the credits for Pokemon sprite animations
Example of work: [Decidueye](https://www.deviantart.com/selenaff/art/Decidueye-BW-Style-740694079) [Vikavolt](https://www.deviantart.com/selenaff/art/Vikavolt-Animated-Sprite-BW-Style-625199396)

Add selstar to credits

---

src/plugins/i18n.ts

[link](https://www.i18next.com/overview/configuration-options)

Fixed warnings that triggered with ptBR and zhCN

---

src/locales/de/ability-trigger.ts

Source: Pokémon ORAS (Probably the same in S/V but i dont have a dakrai there)

Fixed german localization of bad dreams

---

src/ui/text.ts

Adding support for x,y axis on dropshadow and adjusting the values to be less bad
and renamed the constants to actually make sense

Drop Shadow Adjustments

---

src/battle-scene.ts
src/utils.ts

Money with abbreviated form

---

src/field/pokemon.ts

- https://github.com/pagefaultgames/pokerogue/issues/680
- https://github.com/pagefaultgames/pokerogue/issues/358
- https://github.com/pagefaultgames/pokerogue/pull/783
This PR aims at fixing the order of messages when a pokemon faints because of a non-neutral effective physical/special move or because of a physical/special move that hit critically.
> [!NOTE]
> This **PR only aims at fixing the order of the messages**. The messages themselves are not changed (I know we are for instance missing the multi hit counter when the pokemon faints, etc.).
I am doing these changes because I want to get rid of this wrong order for the messages. That's not crucial to play, just been bugging me since I started playing the game.
Before, the messages were displayed in the following order:
- The pokemon …

Allow to explicitly ignore faint phase when damaging

---

src/field/pokemon.ts

Hotfixes the problem where smart AI cheats with sucker punch and upper hand by just not checking conditions for those moves.

Hotfix Sucker Punch and Upper Hand AI

---

src/locales/de/voucher.ts

Added German Localization to Voucher.ts

---

src/data/ability.ts
src/phases.ts

save berry in variable instead of trying to access it directly from the berriesEaten array which changes because of `Array.splice`

hotfix creating undefined berry

---

src/locales/de/modifier-type.ts
src/locales/en/modifier-type.ts
src/locales/es/modifier-type.ts
src/locales/fr/modifier-type.ts
src/locales/it/ability.ts
src/locales/it/modifier-type.ts
src/locales/pt_BR/modifier-type.ts
src/locales/zh_CN/modifier-type.ts

* A lot of Italian abilities were all mixed up but I fixed them
* https://github.com/pagefaultgames/pokerogue/issues/992
* https://github.com/pagefaultgames/pokerogue/issues/1258

Update wrong Italian ability localizations and berry pouch

---

.gitignore
README.md
docs/linting.md
package-lock.json
package.json
src/battle-scene.ts
src/system/game-data.ts

money formatter disappeared, human error
README updated with new node version for everyone to use
package-lock update and package engine updated as well
and finally made it so you can see the overwrite message for importing data. finally

Update README and package, re-add money formatter

---

src/ui/battle-info.ts

Fixed champion ribbon boss segments.

---

.github/workflows/deploy.yml

Added if statement to deploy.yml stopping local builds failing.

---

src/phases.ts

Reverts pagefaultgames/pokerogue#1336

Revert "Update running away in Double Battles"

---

src/phases.ts

Update running away in Double Battles

---

src/locales/en/menu.ts

Updates Save Loading Error Text

---

src/locales/de/menu.ts

Since the new Text is even shorter then the text before i think i dont need to provide a screenshot

German Loc for the menu.ts change

---

src/locales/de/ability.ts

After the changes in https://github.com/pagefaultgames/pokerogue/pull/1360 the ability was in english. (Because how it worked changed).
I relocalized it into german with the new effect.

localized Honeygather again

---

src/battle-scene-events.ts
src/battle-scene.ts
src/phases.ts

Adds a few new events for the `BattleScene`  `eventTrigger`.

Adds New BattleSceneEventTypes

---

src/locales/fr/modifier-type.ts

The French translation of CHILL_DRIVE and DOUSE_DRIVE where wrong

Fix French translation of Genesect's Drive

---

src/locales/fr/biome.ts

After a debate with Sangara on Discord and a pool in  the French channel, we came up with these edits

Update French biome.ts

---

src/data/trainer-config.ts

Simply changing Marshal(an elite four member) to have 2 evolved pokemon on his list rather than their unevolved forms, just in case there's another hiccup like with Iris having an Aron on her champion team.
also this is my first PR, I'm pretty sure I did everything correctly!

Small update for Marshal's Elite Four team.

---

src/overrides.ts
src/phases.ts

[Link to demo](https://youtu.be/hjeWvwGLAls)

Add flag for immediate hatching eggs

---

src/data/ability.ts
src/data/move.ts

Implement comatose ability following [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Comatose_(Ability)).
- Pokemon is inmune to non volatile status effects.
- Pokemon cant use REST
- Pokemon can use Snore
- Pokemon is inmune to drowzy effect
- Pokemon gets double damage from HEX and WAKE UP SLAP

Implement Comatose

---

src/data/trainer-config.ts

Readded import for i18next to trainer-config.ts

---

src/locales/zh_CN/trainers.ts

new translation for duo trainers

Update trainers.ts for zh translation

---

src/data/ability.ts

Just made Steely Spirit behave the same as Steelworker, rather than doing nothing

Partially implemented Steely Spirit

---

src/battle-scene.ts

Changed the gradient colors in the SSS luck value to something with a little more life

Tweaked SSS luck value color

---

src/locales/en/dialogue.ts
src/phases.ts

Remove endless crash

---

src/overrides.ts

Fix gender override

---

src/locales/fr/modifier-type.ts

Terminology harmonisation for some items between the game and the wiki, after deliberations with Sangara on Discord, French wiki lead

Update French modifier-type.ts

---

README.md

Removed trello reference.

---

src/main.ts

This fixes ~100 errors in VS Code due to a missing reference
The global function setPositionRelative is now defined properly as an extension method and is therefore recognized by the IDE
Open the Summary Screen during an Endless Fused run. The Fusion Icon calls this function.

Fixes setPositionRelative Errors

---

src/system/game-speed.ts

This resolves ~35 errors due to a union type not being able to access a property
Union types were cast to an appropriate subset of Union types or a single one that can perform the requested actions
Since these are animation related, everything gets called multiple times during normal gameplay, including at launch. Simply placing breakpoints at the changed lines will reveal they are still getting called and no console errors or crashes occur.

Fix Error with Typecasting

---

src/inputs-controller.ts

This fixes ~30 errors in inputs-controller.ts due to assumed runtime type checking
This change explicitly specifies types where possible before runtime to remove errors.
SInce this file deals exclusively with Gamepad management, you'll need to plug in a controller and navigate through the various menus using this control scheme.

Fix assumed runtime type checking errors in inputs-controller.ts

---

src/ui/summary-ui-handler.ts

The localized type icons where not shown when learning a new move (see Screenshots below)
Well because it is a bug and was missing -> it would look weird/inconsistent
Add the same call for the localized type icons at the place where this type icon is loaded
Before:
After:
Get a pokemon with 4 moves and have it level up to learn a new one (or use a memory mushroom to realearn a move)

[Bug] Type Icons are now also localized when learning a new move

---

src/ui-inputs.ts

This fixes ~30 errors in ui-inputs.ts caused by using an interface incorrectly.
This commit changes the interface into a Record of Button keys and functions values. This commit also uses BattleScene as the base scene type since that's all that this class can use and the only type that gets passed in.
Since this change affects all inputs, simply try each input individually to confirm that they are functional.

Fix Errors in ui-inputs.ts

---

src/data/move.ts

This change fixes ~4 errors in move.ts
Removes an unnecessary toString() call, an invalid return value, and a function call that was missing an unused argument
Since this change deals with localization for the largest change, you can simply place a breakpoint in the changed line and observe on game start that each move still translates properly in the appropriate language.

Fix move.ts Errors

---

package-lock.json
package.json

This change fixes almost all of the node_module errors. Devs will need to run `npm install --save-dev @types/node` on their end to facilitate this change. We are missing this package which we should have installed already since we are using Typescript and these are all type definitions.
This changes the package and package-lock to add @types/node
1. Observe the errors in VS Code
2. run `npm install --save-dev @types/node`
3. Close VS Code and reopen it
4. Observe the errors in VS Code after the project fully loads

Add @types/node to the package lock to resolve most node_module errors

---

src/data/trainer-config.ts
src/field/trainer.ts

This takes things from https://github.com/pagefaultgames/pokerogue/pull/1399/files that are bug fixes that are needed and makes it their own pr
- Double Battle Trainers will now have Pokemon that scale in strengh (no first stage pokmeon at wave 150 anymore)
- If a double battle trainer is a derived type (like LANCE_CHAMPION), it does not correctly use the base TrainerType sprite (LANCE). This fix retrieves the derived trainer type (in this case, LANCE).
The first change is a bug found by players. The second one i saw in developing #1399
The double battle trainer now have pokemon that scale by level. 
Before:
After:
- Spawn Marnie & Piers at Like Wave 150 or so (with override.ts and battle.ts)
- No, it was a part of #1399 but works on its own 
- No. I could still split those two changes …

[Bug] Double Battle Fixes

---

index.html

Fixes Refactor Typo with Mobile Controls and the new Flyout Menu.

Fix Mobile Controls

---

src/test/fontFace.setup.ts
src/test/vitest.setup.ts

I've added a `FontFaceMock` that is loaded for vitest 
Thank you to `glifa` for finding and reporting this on discord
Currently the tests are failing on the main branch: 
The vitest setup
Run `npm run test`

[BUG] Add fix for failing tests: FontFace

---

src/touch-controls.ts

People noticed that the double-tab zoom issue from #1326 now also happens on the action pad (A, B etc. buttons)
I want people to be able to fat-finger without the fear of zooming and having to restart the game/browser
I've called the existing `preventElementZoom` on the `#apad` element too
https://github.com/pagefaultgames/pokerogue/assets/50131232/8433e699-6c7d-4015-89d1-b367cf6aa28e
Open pokerogue.net on your phone and start tapping like wild around this area:
Then switch to the this PR version and try reproducing it: won't be able to
- [] ~~Are the changes visual?~~

[QOL] prevent double-tab zoom on action pad

---

src/locales/fr/tutorial.ts

Edit / adding news lines to French tutorials.ts
Added translation to this file after the new additions made in PR #1377 
New lines to tutorial.ts in French

[Localization] Update French tutorial.ts

---

src/locales/es/modifier-type.ts

Added translations for the bottom of the file, which was still without. Also capitalized a lot of stuff for consistency across the board and with the English version, and fixed some minor typos.
Better user experiences for the españolos and latameros of the world.
Following up on some changes at https://github.com/pagefaultgames/pokerogue/pull/1600 that didn't make it before the merge. My bad for giving the thumbs up when I missed an entire file.

[Localization] Spanish modifier-type.ts changes (translations and typo fixing)

---

src/inputs-controller.ts
src/plugins/i18n.ts
src/touch-controls.ts

This change fixes all but one error remaining in the project.
i18next requires a valid default namespace to be defined, so I did so. I also fixed a type constraint issue for mobile controls.
Since this deals with localization and mobile, boot the game up on any two languages on mobile and navigate to a save file.

Fix i18next and mobile errors

---

src/locales/ko/ability-trigger.ts
src/locales/ko/dialogue.ts
src/locales/ko/menu.ts

Locale update for Finn and Ivy, and the spoiler one.
Additionally, 2 missing locales. (Setting on main, BadDreams Ability Trigger)
Emotion flow of rival is little bit impressive for me.  
It worth to partial-translate (without other trainers).
Korean locale files are translated.
dialogue.ts : Battle to rivals, and wave 200.
ability-trigger.ts: Battle with Darkrai and sleep move.
menu.ts: Turn on the game with Korean locale.

[Localization] Update Korean rival dialogue

---

src/data/move.ts

Implementing the move Punishment. This was already coded from [this pull request](https://github.com/pagefaultgames/pokerogue/pull/373), but was closed due to no documentation and inactivity.
Unimplemented move.
The move punishment now works, as well as making  `countPositiveStats` as a function. As I said previously, the code itself was already there, all I did was add documentation and tested. 
Video to show that it makes contact on hit:
[Video](https://github.com/pagefaultgames/pokerogue/assets/71776311/d1f5b26e-8341-411e-95f1-0222613b2796)
Video to show that the power does increase based on the opposing stat increases:
[Video](https://github.com/pagefaultgames/pokerogue/assets/71776311/bbae3deb-fc0c-47cd-9277-1770b7b29f5e)
You can simply add the code, and change the opposing Pokemon's …

[Move] Implement Punishment

---

src/data/berry.ts
src/field/pokemon.ts
src/modifier/modifier-type.ts
src/modifier/modifier.ts

Reverts pagefaultgames/pokerogue#1112

Revert "Added Confusion to be healed with Full Heals and Full Restores"

---

.gitignore
.vscode/settings.json

The repository is currently versioning VS Code settings. This commit removes it and instead adds it to the `.gitignore` so that everyone can modify their settings as they please.
Removed VS Code settings from the repo and added it to the `.gitignore`

[QoL] Remove VS Code Settings

---

src/system/voucher.ts
src/ui/vouchers-ui-handler.ts

Fix the description of the first voucher
The description was bugged
We created a getAchievementDescription and a localizationKey parameter. The first voucher used a simple achv.description, so I needed to update it to the newest method
Just check if all vouchers' descriptions are correct

Fixed the first voucher's description

---

src/locales/es/achv.ts
src/locales/es/weather.ts

- Updated achv.ts
- Updated weather.ts
I decided to introduce these changes to improve the overall user experience, particularly for Spanish-speaking players who may not understand English well.
Translated all descriptions of the achievements.
Translated all name of the achievements.
Translated weather.

[Localization] Weather and Achievements ES translations

---

src/data/pokemon-forms.ts
src/locales/de/modifier-type.ts
src/locales/en/modifier-type.ts
src/locales/es/modifier-type.ts
src/locales/fr/modifier-type.ts
src/locales/it/modifier-type.ts
src/locales/ko/modifier-type.ts
src/locales/pt_BR/modifier-type.ts
src/locales/zh_CN/modifier-type.ts
src/locales/zh_TW/modifier-type.ts

Ensures that the Lustrous Globe is named that throughout the code and localisation, avoiding confusion with a separate item with a similar name.
The item that changes Palkia between their standard and Origin formes is the Lustrous Globe, and mistakenly referring to it as the Lustrous Orb causes confusion, since that is a different, pre-existing item with separate effects.
This also allows the game to find the correct sprite, since the Lustrous Orb is not implemented, and no sprite of that name currently exists.
Sections of the code that refer to the LUSTROUS_ORB now correctly reference the LUSTROUS_GLOBE instead, and where necessary, localisations that assumed "Lustrous Orb" were correct are now updated to match.
Before:
An intermediary step pre-localisation showing the sprite is now …

[Bug] Lustrous Globe named Lustrous Orb

---

src/battle-scene.ts
src/data/daily-run.ts
src/field/pokemon.ts
src/overrides.ts
src/phases.ts

Reverts pagefaultgames/pokerogue#1643

Revert "[Feature] Add possibility to override whole user party"

---

src/locales/pt_BR/game-stats-ui-handler.ts
src/locales/pt_BR/menu.ts

Translated disclaimer text
Self-explanatory
Disclaimer text in portuguese
Check the loading screen

[ptBR] Translated text

---

src/field/pokemon.ts
src/loading-scene.ts
src/utils.ts

Api calls won't be attempted if a local server isn't connected
I'm tired of seeing errors for api calls when I'm well aware my local game is not connected to the server
checks during the loading sequence if a local server is connected
(also setting fusionLuck as an additional fix to the earlier issue) 
Run the game `npm run start:dev` without running the rogueserver locally and see if errors come up

dont make api calls when no server is connected in local

---

src/locales/pt_BR/modifier-type.ts
src/locales/pt_BR/tutorial.ts

Minor translations
TM text and some instructions

[ptBR] Translated new TM text

---

src/modifier/modifier.ts

Fixes a bug where tokens would not update in old saves to reflect their new values from #1733 
The tokens would not update in old saves to reflect their new values from #1733 
Issue was reported on Discord [here](https://discord.com/channels/1125469663833370665/1247951276801785898/1247951276801785898)
Hardcode the chance values for the rebalanced endless tokens in the constructor. The healing and damage tokens were doing this already. This forces the tokens to reflect the intended chance values.
- On line 929 of src/system/game-data.ts, in the part of the `initSessionFromData` function which adds enemy tokens to the scene, insert the line: `console.log(modifier);`
- Load an endless save with at least one of every token
- Check the console to make sure the tokens reflect intended values

[BUG] Fix some tokens in existing saves not updating after rebalance

---

src/locales/pt_BR/modifier-type.ts

Reduced Nature Mint text
Text was too big
One translation

[ptBR Localization] Minor nature mint text fix, text was too big

---

index.css

The changes modify the visibility of certain control buttons during battle scenes in the game.
Before:
After:
To test these changes, run the game and navigate to a battle scene. Verify that the specified control buttons are displayed during the battle, but hidden in other UI modes as intended.

fix display touch control V in battle

---

src/locales/pt_BR/battle.ts

[ptBR Localization] Translated new battle.ts texts

---

src/locales/pt_BR/battle.ts

Removed capital letters from the text

[ptBR Localization] Removed capital letters battle.ts

---

src/ui/summary-ui-handler.ts

Sort items on summary screen.
Addendum to 1188, somehow I overwrote the changes I made to the summary screen when I made my commits. 
Reference PR 1188
Before:
After:
Open summary screen and verify items are in order.

Sort items on summary screen changes.

---

src/system/voucher.ts

The title of a trainer is now included in the popup on first defeat and in the overview
A lot of people were confused why they didnt get a voucher if they defeated marnie (they had a empty spot for it in the list).
But the empty spot was for marnie E4 and not marnie Gym Leader which they just fought
Just added their title behind the name
Ingame on defeat
https://github.com/pagefaultgames/pokerogue/assets/38758606/41fca85d-1e59-42ba-939b-2fd6f2abac86
List
https://github.com/pagefaultgames/pokerogue/assets/38758606/25ee8338-b405-400b-a20d-cf5509f40183
Works of course in all languages:
Look at the voucher list. And or defeat one of them which you didnt fight yet

[Qol] The title will now be displayed in the voucher overview (and flyout)

---

src/locales/ko/modifier-type.ts

Correcting the description of Multi Lens in Korean locales .ts file.
The current translation is a mistranslation. It says "depending on the number of Multi Lens you have, pokemon attacks more with 60/75/82.5% power."
I corrected the description with a correct meaning.
No need to test it, because it's just a simple translation correction

[Localization] Korean Multi Lens description translation correction

---

src/inputs-controller.ts

My changes are just increasing the time to hold the button needed to be detected as a repeating key to avoid unwanted double inputs.
To enhance user experience by preventing accidental double inputs.

Fix - double inputs

---

src/data/move.ts

Documentation
Documentation is good
Nothing, just comments

[Documentation] documentation of move.ts

---

src/data/move.ts

added a check in the move to target only enemies
Closes issue #1727 
Before: Snorlax was forced to target teammate when no enemies are available
https://github.com/pagefaultgames/pokerogue/assets/39450497/ad87fd24-ef60-4930-9904-763d4db387eb
After: Now simply shows the move as "failed"
https://github.com/pagefaultgames/pokerogue/assets/39450497/f9514486-6058-48e4-afb1-0adb04f795e5
What worked best was having enemies use spore, have your mons with damage dealing moves + sleep talk

[Bug] fix sleep talk targeting issue #1727

---

src/locales/ko/dialogue.ts

[Localization] #1761 Korean trainer dialogue (some unnamed trainers)
This PR is added korean dialogue for some unnamed trainers
@sodaMelon @Ohmry @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.
Few trainers's dialogue have been translated into Korean yet.
I translated **some nonamed trainer battles' dialogues.**
Also I checked their appearances that exist in [repository](https://github.com/pagefaultgames/pokerogue/tree/main/public/images)
랜덤이름 언네임드 트레이너 다이얼로그를  몇명 번역했습니다.
(scientist. school_kid, artist, guitarist, worke, rworker_female, worker_double)
말투에는 최근 정발판 스칼렛+레포지토리에 존재하는 트레이너 스프라이트 이미지 참고했습니다.
부자연스럽다면 편하게 Suggestion 주세요!
( very hard to meet them.... and it's dosen't …

[Localization] #1761 Korean trainer dialogue (some unnamed trainers)

---

src/data/ability.ts

Harvest no longer replenishes berries above the max stack limit for that berry.
Fixes a bug brought up [here] (https://discord.com/channels/1125469663833370665/1248464586152214588/1248464586152214588) where Harvest will replenish berries above the stack limit
Harvest now checks the max stack count of the berry type before replenishing berries
- Give a Harvest mon 2 Lum Berries while you have 3 Berry Pouches
- Use Rest to trigger the Lum Berry
- Try this several times to ensure you won't get more than you should be able to carry

[Bug] Fix Harvest not checking stack limits for berries

---

src/locales/de/dialogue.ts

See title
So that they arent displayed in english for a german user
Translated the dialogue
None
Select German, Force Spawn the trainer class, Look

[Localization] Added missing german dialogue for sailor and firebreather

---

src/battle-scene.ts
src/modifier/modifier-type.ts
src/ui/game-stats-ui-handler.ts
src/ui/modifier-select-ui-handler.ts
src/utils.ts

lets money format setting effect reroll cost and shop costs text as well 
updates money rewards (nugget, big nugget, relic gold) to display the number after its been multiplied by amulet coin
It looks nicer and its annoying to pick a money reward and not really know how much you're getting
Added a utils function for formatting money and applied the amulet coin modifier before displaying money reward text
also money that's abbreviated and has no decimal places will not display decimal places
turn money format setting to Abbreviated and get to any between battle shop instance

[QoL] Cleanup Money format and Show correct value for money rewards

---

src/loading-scene.ts
src/system/voucher.ts
src/test/vitest.setup.ts

adds initVoucher to preload
vouchers have been getting init with CLASSIC_WIN undefined for whatever reason
changed the initialization of vouchers to an exported function
the second I start a new run on an account that has the classic win achievement it rewards the voucher

[BUG] Init Vouchers on Preload

---

src/ui/starter-select-ui-handler.ts

Hotfix for a bug introduced with challenge mode.

[bug] Fix endless starter points

---

src/locales/ko/move.ts

Fix typo in skill name (비검천충파 -> 비검천중파, Ceaseless Edge)

[Localization] Fix typo in korean skill name (비검천충파 -> 비검천중파)

---

src/locales/fr/menu.ts

Translations for the discalmer for when the game is booting up
To be understandable for French speakers
French discalmer for when the game is booting up
Booting up the game in French

[Localization] French update the menu.ts

---

src/locales/es/battle.ts

- fix es translation
- temp force labor
- added missing curly brace
- n/a
-n/a
- ~[] Are the changes visual?~

[Bug] add missing curly brace

---

src/field/trainer.ts

Fix: #2001 
Save file to reproduce the issue:
https://file.io/5Ia4pF0pc5HL
Before:
[screen-capture (14).webm](https://github.com/pagefaultgames/pokerogue/assets/44787002/1bf47d3d-2b2e-456f-ab5a-09df32dcf329)
with this fix:
[screen-capture (13).webm](https://github.com/pagefaultgames/pokerogue/assets/44787002/19bca2de-9ae8-4188-892d-12c4d68e6942)

revert changes in trainer.ts to fix an issue induced by #1986

---

src/locales/pt_BR/achv.ts

Localized and translated achievements.ts like the english one

[ptBR Translation] Added new achievements.ts translation

---

src/locales/pt_BR/trainers.ts

Fixed typo in Ace Trainers' names

[ptBR Localization] Fixed typo in Ace Trainers' names

---

src/locales/pt_BR/achv.ts

[ptBR Localization] Added female achievements

---

src/locales/ko/challenges.ts

Fix typo in singlegen gen4 desc
"4세대의 포켓몬만 사용할 수 있습니다r" -> "4세대의 포켓몬만 사용할 수 있습니다."
test in local

[Localization][ko] Fix minor typo in challenges

---

src/locales/ko/dialogue.ts

There is a minor typo in korean, Hiker's victory dialogue.
"적어도 BMI에 대하서는 질 수 없습니다!"
-> "적어도 BMI에 대해서는 질 수 없습니다!"

[Localization][ko] Fix minor typo

---

src/test/battle/battle.test.ts
src/test/battle/error-handling.test.ts
src/test/utils/gameManager.ts
src/test/utils/mocks/mocksContainer/mockText.ts

Replace `new Promise(resolve, reject => ...)` with async / await.
Remove `phaseInterceptor.to` calls from `gameManager.do` functions since testers should control that behavior
:spaghetti: 
All relevant tests are passing
```
✓ src/test/settingMenu/rebinding_setting.test.ts (33)
❯ src/test/sprites/pokemonSprite.test.ts (15)
❯ check if every variant's sprite are correctly set (15)
✓ data should not be undefined
✓ check root variant files
✓ check female variant files
✓ check back female variant files
✓ check back male back variant files
✓ check exp back variant files
✓ check exp female variant files
✓ check exp male variant files
✓ look over every file in variant female and check if present in masterlist
✓ look over every file in variant back female and check if present in masterlist
× look …
```

[Test(refactor)]: Refactor tests game manager

---

src/ui-inputs.ts

Fixes #2061 
Fixes #1797 
Fixes #1547 
Fixes #1736 
Fixes #1392 
Fixes #54
This PR introduces restrictions on menu opening in specific game modes and modifies the gamepad behavior in the select-starter menu. This is mainly to fix soft-lock issues.
- Restricted menu opening in the following modes:
- `Mode.TITLE`
- `Mode.COMMAND`
- `Mode.MODIFIER_SELECT`
- Modified the behavior in the select-starter menu on gamepad: pressing start now prompts the user to confirm if they want to start the run instead of opening the menu.
1. Check out the branch containing these changes.
2. Verify that the menu does open only in the restricted modes listed above.
3. In the select-starter menu, press the start button on the gamepad and confirm that it prompts to start the run instead of opening the menu.

[Bug] Restrict Menu Access to Specific Game Modes + Gamepad Start Button in Select-Starter Menu

---

src/locales/zh_CN/achv.ts

This PR mainly focuses on improving the simplified Chinese localization content of the application.
1.Added Missing Simplified Chinese Translations
2.Optimized Localization Content
achv.ts

[Localization] Improve Simplified Chinese Localization Content ( achv.ts )

---

src/locales/ko/dialogue.ts

[Localization] #1761 Korean trainer dialogue (villain)
This PR is added korean dialogue for villain
@sodaMelon @Ohmry @returntoice now participating in https://github.com/pagefaultgames/pokerogue/issues/1761 translating project.
Few trainers's dialogue have been translated into Korean yet.
I translated **the  villain trainer battles' dialogues.**
(It hasn't been released yet in game)
빌런 (로켓단, 마그마단, 갤럭시단..........들)의 스크립트를 번역했습니다.
아직 게임에서 등장하지는 않았지만 아침에 ice님 PR 보고 해도 되겠다 싶어서 번역했어요~. 
천천히 보시고, 부자연스럽다면 편하게 Suggestion 주세요!
( very hard to meet them.... and it's dosen't matter)
It seems there won't be much to test since it's just a translation of an existing .ts file. You can check it when you meet the respective trainers.
- ~~[ ] Are the changes …

[Localization] #1761 Korean trainer dialogue (villain)

---

.github/workflows/tests.yml
src/test/inputs/inputs.test.ts

I've added a GitHub Action to run `npm run tests:silent` in PRs to the main branch.
Reviewers can verify the changes by creating a PR to the main branch and ensuring the GitHub Action runs `npm run tests:silent` successfully.

[CI] Add GitHub Action to Run Silent Tests on PRs to Main

---

src/locales/ko/dialogue.ts

Fix of small typo
concert must be translated by '콘서트' but it was '큰서트' so I changed
큰서트->서트
very small change and hard to meet them

[Localization]fix small typo

---

index.html

Added some meta tags that might help with SEO. 
Certain users have reported that in some regions, the other fake websites appears before pokerogue.net.
There aren't much we can do for a website that literally only have a canvas, but it doesn't hurt to add a few more meta tags.
Some twitter and open graph meta tags. 
Meta keywords, which probably doesn't do much in 2024.
I doubt this helps much if at all, but gotta try.

[Enhancement] Minor Search Engine Optimization

---

src/data/move.ts

It seems that move 'hyperspace fury' is a non-contact move (https://www.serebii.net/attackdex-swsh/hyperspacefury.shtml).
Bug fix
Added ```makesContact(false)``` to the move info code.

[Bug] Fix move 'Hyperspace Fury' to non-contact

---

src/locales/pt_BR/battle.ts

Translated the fainted dialogue

[Localization] [pt] Fainted Translation

---

src/locales/pt_BR/achv.ts

Shorter achievements and capitalized them to be like the english ones

[Localization] [pt] Updated pt-br achievements

---

src/locales/fr/battle.ts

Add French translation for "regainHealth" and "fainted" that was still in english
Did this change to have a fully french translation for the game
This : 
"regainHealth": "{{pokemonName}} regained\nhealth!",
"fainted": "{{pokemonNameWithAffix}} fainted!"
Become :
"regainHealth": "{{pokemonName}} a récupéré\ndes PV!",
"fainted": "{{pokemonNameWithAffix}} est tombé KO!"

[Localization] [FR] Update battle.ts

---

src/ui/form-modal-ui-handler.ts

fix form modal bug about unexpected modal position. (when clicking submit button rapidly)
it goes up infinitly
i think unexpect behavior in form ui makes user confused
store tween and remove it when handler clear().
- before change
https://github.com/pagefaultgames/pokerogue/assets/29995264/9613af63-2b6b-4e06-8166-a89213efe62c
- after change
https://github.com/pagefaultgames/pokerogue/assets/29995264/615c1b0d-d5cb-41d8-adba-ca39671d3783
1. edit login bypass to test login phase
2. see it works with login ui and registration ui.

[Bug] Fix unexpected modal position in login and registration ui

---

src/locales/pt_BR/trainers.ts

Updated Team Members and Leaders
pt_BR\trainers.ts now has the same number of lines of the english one

[Localization] [pt] Updated trainers.ts

---

src/locales/fr/dialogue.ts

I add the french translation for the swimmer's encounter and victory message.
Some translations might not be literral but I tried to use some French expression that could match the situation
Make the game 100% available in french

[Localization] [FR] Update dialogue.ts

---

index.css

As stated by a user on discord [here](https://discord.com/channels/1125469663833370665/1250473750491562044) right now it's almost impossible to log in on iOS due to the interface zooming into the input elements. I've fixed that by applying a css `font-size: 16px` (cause that's the threshold)
So users can more easily/at all log in on iOS
it no longer zooms into the input
https://github.com/pagefaultgames/pokerogue/assets/50131232/a5c2b37c-07e3-46a9-ac7d-ce2c057983bd
https://github.com/pagefaultgames/pokerogue/assets/50131232/0f60a8ff-2ee7-471e-a30d-99a8dbf070e6
1. Own an iOS Device
2. Run it on your machine exposed to your local network
3. Make sure to disabled login-bypass in the `.env` files
4. Open the page on your iOS device
5. click on the login inputs and see if it zooms in (it …

[Bug] prevent iOS input-auto zoom by adding font-size: 16px to inputs

---

src/locales/pt_BR/fight-ui-handler.ts

Added portuguese translations to the Passive Ability Fly In
It is quite similar to the spanish one that has already been approved: #2136

[Localization] [pt] Translated Ability Bar

---

src/data/pokemon-species.ts

Changed Dipplin to be erratic instead of slow
It was wrong. Also causes it to lose levels when evolving
dipplin's exp rate
n/a
pull

[Bug] Dipplin should be Erratic instead of Slow

---

src/locales/ko/dialogue.ts
src/locales/ko/modifier-type.ts

1. changed a description for "Sacred Ash".
2. fixed Koga's dialogue 
1. description for "Sacred Ash". : it's not clear to understand.
- 후반부에 등장하는 "성스러운 분말"입니다. 
기존 설명은 [자신의 포켓몬의 HP를 기절해버렸더라도 모두 회복한다.]인데요.... 
타겟을 설명하는 단어가 불분명해서 그런가..지인들도 많이 헷갈려하더라구요. 
그래서 한국어판 포켓몬 위키 보고 고쳤습니다.
2. fixed Koga's dialogue : it has typo. ( I did it past in past.. because sleepy......)
- 이건 제가 지난 번에 했던 작업인데 새벽에 졸면서 쳤더니 실수를..ㅎㅎ;;
1. description for "Sacred Ash". : i changed it to better reveal the target
2. fixed Koga's dialogue : i fixed it.
I have only current images witch have problem... (it will fix this PR but i don't have images, bacause it's very hard to meet them...)
1. for Sacred Ash : 
4. for koga's : 딘순히 -> 단순히
It's just a word replacement, so you don't have to do that.

[Localization] Modified item description (by korean)

---

src/locales/pt_BR/achv.ts
src/locales/pt_BR/move.ts

Corrected the description of Boouncy Bubble and fixed achievements

[Localization] [pt] Fixed Bouncy Bubble description and updated achievements

---

src/ui/party-ui-handler.ts

Reverts pagefaultgames/pokerogue#2117

Revert "[QoL] Add red color to the quantity if the item is at it's held limit"

---

package-lock.json
package.json
vite.config.js

No user perspective changes.
To help out
Fixes tsconfig.json paths in vite
`npm run build`
`npx serve dist`

fix tsconfig paths importing

---

src/data/egg.ts

Changes the manaphy egg rate back to 1/256. It wasn't 1/256 because the egg first needs to roll common and after that the 1/255 check was done.
To set the intended rate.
just one line for the manaphy egg generation.

[Bug] Fixes manaphy egg rate back to 1/256

---

src/locales/it/achv.ts

Fixed a couple of achievements' names in IT.
I changed monotype bug and fairy achievements' names to make them more fitting.
The previous names weren't really funny nor fitting, so they would've not worked too well.
Complete monotype bug or monotype fairy challenge.

Update achv.ts [Localization]

---

src/locales/it/battle.ts

Translated every sentence and fixed a few ones
Translation of 7 sentences from EN to IT
I'm doing them as my full translation of the game in Italian, and they're useful since you battle all the time so having battle dialogues translated surely helps.
By doing certain actions in any battle in pokerogue.

Update battle.ts [Localization]

---

src/locales/it/game-mode.ts

Translated game modes' names from EN to IT
I've translated all the gamemodes' names from EN to IT
To complete the full translation in italian of Pokerogue
Try to start a new run and see what name is shown.

Update game-mode.ts [Localization]

---

src/locales/it/fight-ui-handler.ts

Translated things regarding "passive"
The way passive abilities are visualized
Because the previous version still was in english.
Trigger an HA in Pokerogue.

Update fight-ui-handler.ts [Localization]

---

src/locales/pt_BR/achv.ts

Chenged all lines of achievements in the portuguese localization
Due to a failed commit (PR: #2129 / [commit](https://github.com/pagefaultgames/pokerogue/commit/d6a83945039de9b665a16c138edf5db54d508a4d)) the achievements are incorrect in-game, so I'm intentionally changing them. After this is approved, I'll make a PR with the correct ones.
Translations

[Localization] [pt] Intentionally changed all achievements' names due to commit bug

---

src/locales/pt_BR/ability-trigger.ts

Updated portuguese ability-trigger.ts
Changed it to be the same as the english file

[Localization] [pt] Updated ability-trigger.ts

---

src/locales/pt_BR/achv.ts

[Localization] [pt] Fixed achievements

---

src/locales/pt_BR/achv.ts

Got the female achievements to work in #2235, now fixing the male ones as well

[Localization] [pt] Fixed male achievements as well

---

src/locales/fr/ability-trigger.ts
src/locales/fr/achv.ts
src/locales/fr/battle.ts
src/locales/fr/challenges.ts
src/locales/fr/party-ui-handler.ts
src/locales/fr/pokemon-info-container.ts
src/locales/fr/splash-messages.ts
src/locales/fr/trainers.ts

Corrections of French translations
Because the previous ones were either inaccurate, too litteral and/or full of typos
Some French translations files

[Localization] Many corrections of recent French translations

---

src/data/pokemon-species.ts

Changing Goomy's Passive from Drizzle to Regenerator
Per [the documentation](https://docs.google.com/spreadsheets/d/1bX15Rnd7QFF9LOlr6t3H1BafVF-pObqep2JkTqIPbBo/edit?gid=1281624451#gid=1281624451), Goomy was supposed to get Regenerator as a Passive in the big Passive update, but it didn't. I checked with the Discord and this was indeed a mistake, not an intentional change:
Drizzle->Regenerator
Double-check I didn't misspell "Regenerator"
- [-] Are the changes visual?
- [-] Have I provided screenshots/videos of the changes?

[Balance] give Goomy Regenerator

---

.github/workflows/github-pages.yml

Removes unnecessary install of typedoc in workflow file. This is already inside of devDependencies
This properly pins the version of typedoc to the workflow to prevent future releases causing errors.
Removed a line from a workflow
The workflows should succeed if it worked.

remove unnecessary typedoc install in workflow

---

src/phases.ts
src/system/game-data.ts

Changed the endpoints to conform with the new server endpoints.
Because things should be up to date. 👍
Endpoints should fall in lane with what's expecting in the master branch of the rogueserver.

[Misc] Adjust System and Session endpoints to the new server structure

---

src/phases.ts
src/system/game-data.ts

Fix API endpoints for saving and retrieving system and session data

---

src/locales/it/save-slot-select-ui-handler.ts

Everything regarding save slot handling has now been translated in IT too.
To make things clearer for italians.
Try overwriting a save file in Pokerogue after setting the game on Italian.

Update save-slot-select-ui-handler.ts [Localization]

---

src/locales/it/pokemon-info-container.ts

Pokemon info related vocabulary has been translated from EN to IT.
So that everybody can read their pokemon's info in IT too.
Check a pokemon in your team after changing the language to italian.

Update pokemon-info-container.ts [Localization]

---

src/locales/it/party-ui-handler.ts

Translated all of the party handler sentences
All of the party handler commands have been translated to italian
To complete the full translation in italian of pokerogue
Enter Pokerogue in italian and try to work with your team.

Update party-ui-handler.ts [Localization]

---

src/data/battle-stat.ts
src/data/temp-battle-stat.ts
src/locales/de/modifier-type.ts
src/locales/en/modifier-type.ts
src/locales/es/modifier-type.ts
src/locales/fr/modifier-type.ts
src/locales/it/modifier-type.ts
src/locales/ko/modifier-type.ts
src/locales/pt_BR/modifier-type.ts
src/locales/zh_CN/modifier-type.ts
src/locales/zh_TW/modifier-type.ts
src/plugins/i18n.ts

The X Items now correctly have localized stat names
They were english
See screenshots
Before:
After:
Set your game to german (its also noticable for dire hit in english) and find an X-Item in the shop.

Localized the statname in the X Item description

---

src/locales/it/pokeball.ts

Fixed a wrong translation
Fixed a wrong translation for a ball's name
Because the translation was wrong.
Luxury ball isn't translated to "Chich Ball" anymore, but to "Chic Ball".
Buy a Luxury Ball and change the language to italian.

Update pokeball.ts [Localization]

---

src/locales/pt_BR/modifier-type.ts

[Localization] [pt] Updated modifier-type

---

src/test/lokalisation/battle-stat.test.ts

removed duplicate code from the depcruise merge that was added after the pr was made
to fix tests
tests now pass
`npm run test`

remove the duplicate document.fonts code

---

src/egg-hatch-phase.ts
src/ui/egg-counter-container.ts

Checks to make sure egg counter text data exists before updating the text and allowing a skip
Checks to make sure the data for the counter text is set before trying to change the phaser frame
Hatch some eggs and look at the console

fix egg skip console error

---

src/locales/it/voucher.ts

Everything about eggs has been translated.
To fully translate the game in italian.
Open the eggs gacha menu in pokerogue upon setting the language on italian.

Update voucher.ts [Localization]

---

src/locales/it/pokemon-info.ts

A couple of words have been translated.
To have the game fully translated in italian.
Accuracy -> Precisione
Evasiveness -> Elusione
Boot up the game in italian and check the terms.

Update pokemon-info.ts [Localization]

---

src/locales/it/tutorial.ts

The tutorial translations have been reworked to make more sense in italian.
Because the tutorials need to be pretty clear and understandable, so their translations must be accurate and logical for everybody. 
Open the game for the first time and set the language in italian, then check out the tutorials.

Update tutorial.ts [Localization]

---

src/account.ts
src/phases.ts
src/system/game-data.ts
src/ui/unavailable-modal-ui-handler.ts

The server is now timing out the session cookie properly, so the client needs to handle that by kicking the user back to the login screen.
The users are currently stuck and have to manually delete their cookies in order to login back once more to regain a valid cookie.
Added validations around updateUserInfo to handle 401 cases.

[Bug] Unauthorized 401 error fix

---

src/loading-scene.ts

Cleaned up the code for loading scene a little and allowed for mobile to see the intro video and disclaimer
General cleaning and found out mobile cant see the intro
added playsinline for mobile users seeing the intro video and used loading plugin event constants for event listeners
Open the game as usual
Use dev tools in chrome to look at the game from a mobile size to see that the intro does in fact load on mobile

[QoL] clean loading scene and let mobile see intro

---

src/locales/pt_BR/starter-select-ui-handler.ts

[Localization] [pt] Update start-select-ui-handler.ts

---

src/ui/menu-ui-handler.ts

Added a Reddit link on the Community tab.
Let's show some love to the reddit community.
Added a link to the Reddit community on the Community tab above the back button.

[Community] Add Reddit link to menu UI

---

src/ui-inputs.ts

Fix the buggy game speed.
To fix a bug introduce while the setting translation.
Fix the bug.
I can't take a video right now.
Go into the game setting change the game speed and play.

[Bug] Fix game speed

---

src/ui/summary-ui-handler.ts

Modification some code about nature in Pokémon summary for localization.
Although translated nature information is available, the nature  in Pokémon summarry were only in English. so that it needs to modify that.
Nature in Pokémon summary have been translated.
- before 
- after

[Localization] Modified code for nature in Pokémon summary

---

src/locales/fr/battle.ts

Tranlsation of an untranslated entry
To have this sentence translated in French
A sentence in battle.ts translated in French

[Localization] Missed entry in French battle.ts

---

src/locales/ko/starter-select-ui-handler.ts

Add missing manageNature entry in Korean for starter-select-ui-handler.ts
The manageNature entry was missing only in the Korean translation file
- before
- after

[Localization] Add missing manageNature entry in Korean for starter-select-ui-handler.ts

---

src/locales/ko/battle.ts

This is a similar fix to the following pull request.
https://github.com/pagefaultgames/pokerogue/pull/2412
https://github.com/pagefaultgames/pokerogue/blob/1ee89501b654582022820c60bf01391ccd06cafe/src/locales/en/battle.ts#L96
https://github.com/pagefaultgames/pokerogue/blob/1ee89501b654582022820c60bf01391ccd06cafe/src/locales/ko/battle.ts#L96
Changed the binding code for "BattlerTagsEncoreOnAdd" from "sourcePokemonNameWithAffix" to "pokemonNameWithAffix" to prevent the binding code from being output as plain text.
`{{sourcePokemonNameWithAffix}}` is printed in plain text in the game in Korean mode.
Changed binding code in below from
https://github.com/pagefaultgames/pokerogue/blob/1ee89501b654582022820c60bf01391ccd06cafe/src/locales/ko/battle.ts#L96
to  `"battlerTagsEncoreOnAdd": …

[Localization][Bug] Fix binding code of "battlerTagsEncore" in Korean

---

src/test/abilities/battery.test.ts
src/test/abilities/power_spot.test.ts
src/test/abilities/screen_cleaner.test.ts
src/test/abilities/unseen_fist.test.ts
src/test/moves/follow_me.test.ts
src/test/moves/rage_powder.test.ts
src/test/moves/spotlight.test.ts

Unit tests for the following abilities and moves have been optimized to finish much faster:
- Unseen Fist
- Follow Me
- Rage Powder
- Spotlight
- Battery
Because of issues with how I originally wrote them, these tests take a much longer time than needed.
- `unseen_fist`, `follow_me`, `rage_powder`, and `spotlight`: Fixed an issue where some tests would unnecessarily trigger the `FaintPhase`.
- `battery`: Fixed an issue where tests unnecessarily run through the `TurnEndPhase`
N/A
`npm run test`. Compare the runtime between this branch and `upstream/main`.
- [N/A] Are the changes visual?
- [N/A] Have I provided screenshots/videos of the changes?

[Enhancement] Optimize Unit tests

---

src/test/abilities/wind_rider.test.ts

- wind rider unit tests
- wind rider unit tests
- wind rider unit tests
`$npm run test wind_rider`

[Enhancement] add wind rider unit tests

---

src/test/abilities/wind_power.test.ts

- wind power unit tests
- wind power unit tests
- wind power unit tests
$ npm run test wind_power

[Enhancement] add wind power unit tests

---

src/test/moves/tailwind.test.ts

- tailwind unit tests
- tailwind unit tests
- tailwind unit tests
`$ npm run test tailwind`

[Unit Test] add tailwind unit tests

---

package-lock.json

It's in the title
Running `npm audit fix`

[Enhancement] Fix high severity vulnerability

---

index.html
src/main.ts
src/plugins/i18n.ts
src/ui/text.ts

adding unifont to emerald and pkmnems to keep consistent with korean font addition
consistency and hopefully to help with chinese players not seeing font correctly on some browsers/proxy
unifont has been removed as its own font family and instead added as a font face to existing families with specific unicode ranges for CJK Unified Idoegraphs
Korean unicode range has been updated to include other Hangul related compatibilities 
change to one of the chinese language settings

[UI] more specific font unicode ranges and add unifont to existing families

---

src/data/move.ts

Mountain Gale does not make contact according to [smogon](https://www.smogon.com/dex/sv/moves/mountain-gale/) and [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Mountain_Gale_(move))
It was incorrect
.makesContact(false)
Pull

[Bug] Mountain Gale does not make contact

---

src/ui/menu-ui-handler.ts

Make wiki link change to accommodate active translations of the wiki
a wiki user asked
menu ui handler checks language and can reassign wiki link if needed
change language to german, french, korean, or chinese and use the wiki link in the community tab

[Feature] Update wiki link

---

src/test/abilities/ice_face.test.ts

This fixed issue #2479 where the Ice Face test "takes no damage from the first hit of multihit physical move and transforms to Noice" was sometimes failing. The initial thought was it could be from a critical hit, but it seemed to be from a speed tie causing Eiscue to sometimes go first and so Ice Face wouldn't be down after the first hit.
The test was inconsistently passing
Level of Eiscue was changed to 1 to prevent the speed tie.
Test failed consistently when bringing the Eiscue's level to 20.
`npm run test ice_face`

[Bug] Fix Ice Face Test where speed tie was sometimes breaking multi-hit test

---

src/test/abilities/sturdy.test.ts

- intermittent failing -> when Aron uses sitrus berry
- intermittent fail + optimization
- changed phases
- cut down test runtime by 6 seconds
Before
After

[Bug][Unit Test] fix and optimize sturdy unit tests

---

src/locales/pt_BR/dialogue.ts

[Localization] [pt] Updated dialogue.ts

---

src/data/move.ts
src/field/pokemon.ts
src/test/moves/thousand_arrows.test.ts

This fixes a bug where Thousand Arrows doesn't bypass Ground immunity from Levitate
Thousand Arrows isn't hitting Pokemon with Levitate when it should.
- `data/move`: `NeutralDamageAgainstFlyingTypeMultiplierAttr` now checks the target for Levitate along with the Flying type.
- `field/pokemon`: Now applies `NeutralDamageAgainstFlyingTypeMultiplierAttr` after type immunity ability checks.
- `test/move/thousand_arrows.test`: New unit test to check behavior against Pokemon with Levitate.
N/A
`npm run test thousand_waves`

[Bug] Fix Thousand Arrows not hitting Pokemon with Levitate

---

src/locales/pt_BR/egg.ts
src/locales/pt_BR/starter-select-ui-handler.ts

[Localization] [pt] update egg and starter-select

---

src/data/egg.ts

Hotfix for:
- Wrong variants getting generated if they are pulled from same species eggs
- Some common eggs where displayed as manaphy eggs
- Manapy counter got increased by every common egg pull because egg id was still undefined.

Hotfix: Override varaint tier if species was given. Fixed that some common egg where displayed as manaphy egg and wrong manaphy egg counter

---

src/locales/ko/egg.ts
src/locales/ko/starter-select-ui-handler.ts

[Localization] [ko] update egg and starter-select

---

src/data/arena-tag.ts
src/test/moves/aurora_veil.test.ts
src/test/moves/light_screen.test.ts
src/test/moves/reflect.test.ts

- lots of copy pastas removed
- lots of documentations added
- lots of unit tests added
- i dont like copy pastas
- uses base class instead of overriding apply()
- use Light Screen, Reflect, Aurora Veil

[Enhancement][Unit Test] Refactor + Unit Tests for Light Screen, Reflect and Aurora Veil

---

src/ui/egg-gacha-ui-handler.ts

Check that applies the guaranteed egg tier does apply a guaranteed common egg on single egg pulls.
Just a single line

Fixed that a single voucher pull will always be common

---

src/data/egg.ts

It will fix that legendary egg pity does increase after each pull
created another line so the logic isn't as confusing anymore and that fixed the error that causes that always 0 gets added to the counter

Fixed that legendary egg pity doesn't increase

---

src/locales/ko/ability.ts
src/locales/ko/achv.ts
src/locales/ko/battle.ts
src/locales/ko/game-mode.ts
src/locales/ko/modifier-type.ts
src/locales/ko/move.ts
src/locales/ko/settings.ts

Some typo and mistranslation corrections and terminology standardization
They had to be corrected.
Some minor changes on the locales folder.
No need to test since they are already made in the folder.

[Localization] Some minor changes on Korean locales

---

src/data/arena-tag.ts

Adds documentation for the classes missing it in `arena-tag.ts`.
It was missing some documentation, even something basic describing them.
All classes (except the base ArenaTag class) now have at least some basic documentation to go along with them.
N/A
No changes to test, it's just documentation

[Documentation] Update arena-tag.ts documentation

---

src/locales/pt_BR/ability-trigger.ts

[Localization(pt)] Updated costar and trace translations

---

src/locales/pt_BR/modifier-type.ts

[Localization(pt)] Updated modifier-type.ts

---

src/locales/de/ability-trigger.ts
src/locales/de/menu.ts

Some Keys were not localized
So all is german someday
See code (localized some of them)
No
Play in german

Added missing german localization

---

src/test/abilities/aura_break.test.ts
src/test/abilities/battery.test.ts
src/test/abilities/power_spot.test.ts
src/test/abilities/wonder_skin.test.ts

- renamed some functions to be more accurate/descriptive to what it does
- adjusted documentations accordingly
- removed redundant `multiplier` variable
- to avoid confusions with the functions
- see above
`$ npm run test`

[Enhancement] Unit tests cleanup

---

src/data/egg.ts
src/test/eggs/egg.test.ts

Moved one line so `this._sourceType` is available within the function to check if `sourceType` is from legendary gacha.
Added a few more unit tests to check for bugs that happened after the egg update.
Also fixes a bug that some bought common eggs (1/204) will increase the manaphy egg counter.
The function that increases the egg pity checks if the current egg sourceType is set to legendary gacha so it can increase the legendary egg pity by 2. Currently sourceType is not defined because it will get set after the function is called. I moved the line where sourceType is set up so it will be available within the function.
Added unit tests:
```
✓ should increase egg pity
✓ should increase legendary egg pity by two
✓ should not increase manaphy egg count if bulbasaurs are pulled
✓ should …
```

[BUG] Legendary egg pity & manaphy counter fix + Egg unit tests

---

src/locales/pt_BR/egg.ts

[Localization] Update Portuguese translation for egg.ts

---

src/locales/pt_BR/move.ts

Localization: Update "Snarl" move effect in pt_BR translation

---

src/ui/save-slot-select-ui-handler.ts

When overwriting a slot, now we delete the session from the database instead of relying on the update call.
Fixing the broken daily run that uses the same seed across multiple sessions.
When overwriting a session, now the session is explicitly deleted from the server.

[Bug] Add logic to delete session data when overwriting a save

---

src/locales/pt_BR/battle.ts

Localization: Fixed typo in battle.ts "addedAsAStarter"

---

src/locales/fr/dialogue.ts

French Evil Team dialogues
To have Evil Team dialogues in French
French Evil Team dialogues

[Localization] French Evil Team dialogues

---

src/locales/es/dialogue.ts

Title is self-descriptive enough this time around. It's dumping some Spanish into mostly a sea of English dialogues, but tackling everything at the same time is just too monumental of a task. It's good that at least the new features ship fully translated.

[Localization] Dialogue translations for ES for Evil Teams

---

src/locales/pt_BR/modifier-type.ts

Localization: added Eviolite for pt_br

---

src/locales/fr/dialogue.ts

[Localization] Correction of a typo in a french dialogue

---

src/locales/pt_BR/modifier-type.ts

Localization (pt): Added new items' translations

---

src/field/pokemon.ts
src/test/abilities/parental_bond.test.ts

This fixes a bug where Parental Bond would weaken every other hit of a Multi-Lens-boosted spread move (e.g. Earthquake) when the ability shouldn't apply.
This bug was reported in the Discord: https://discord.com/channels/1125469663833370665/1125662770629709935/1255635890533957644
- `data/pokemon`: `apply` now accounts for the number of targets before changing the `twoStrikeMultiplier`.
- `test/abilities/parental_bond.test`: New unit test for spread moves with Multi-Lens.
N/A
`npm run test parental_bond`

[Bug] Fix Multi-Lens/Parental Bond interaction for spread moves

---

src/data/move.ts

This fixes a bug where frenzy moves (e.g. Outrage) would permanently lock the player into using the move if they have Multi-Lens equipped.
This bug was reported in the [Discord](https://discord.com/channels/1125469663833370665/1125894949020381285/1255808184505991169).
- `data/move`: `FrenzyAttr` now uses the `lastHitOnly` attribute of `MoveEffectAttr`
Outrage's behavior after the change:
https://github.com/pagefaultgames/pokerogue/assets/168692175/30acf7dc-3a50-4b96-81b7-1cbc81d0b463
Tested via overrides

[Bug] Fix multi-hit frenzy moves permanently locking the user

---

src/data/move.ts
src/test/abilities/parental_bond.test.ts
src/test/moves/make_it_rain.test.ts

This fixes a bug with Make It Rain where it would apply its effects once for each target (i.e. in a double battle, a single use of Make It Rain would scatter money and lower the user's Sp. Atk. twice).
Make It Rain is currently bugged, as seen in #2641 
- `data/move`: A new `MoveConditionFunc`, `lastTargetOnlyCondition`, adds the condition that the target of the move is the last in the list of targets of the current `MoveEffectPhase`. This condition is added to `MoneyAttr` and Make It Rain's `StatChangeAttr`.
- `test/moves/make_it_rain.test`: New unit test to check if Make It Rain's effects only apply once in a double battle
n/a
`npm run test make_it_rain`

[Bug] Fix Make It Rain applying effects for each target

---

src/locales/de/menu.ts
src/locales/en/menu.ts
src/locales/es/menu.ts
src/locales/fr/menu.ts
src/locales/it/menu.ts
src/locales/ko/menu.ts
src/locales/pt_BR/menu.ts
src/locales/zh_CN/menu.ts
src/locales/zh_TW/menu.ts
src/ui/unavailable-modal-ui-handler.ts

Localization and translation
https://i.ember.zone/jac3ZDJoiy2b7zfV.png
Add this to start() in LoginPhase
```ts
// ...
start(): void {
super.start();
this.scene.unshiftPhase(new UnavailablePhase(this.scene));
super.end();
return;
// ...
```

Localization: Localized error message for server connection issue

---

src/locales/fr/bgm-name.ts

BGM name French name
Haing it in French
The name of tha track

[Localization] Update French bgm-name.ts

---

src/locales/ko/ability-trigger.ts

Quickdraw message to Korean
Quickdraw message is not localize into Korean.
Modified the quickDraw in the `src/locales/en/ability-trigger.ts` file.

[Localization] Quickdraw message to Korean

---

src/locales/zh_CN/modifier-type.ts

Add line break for chinese TM item name
When you have many Golden Poké Balls, the Chinese names of TMs may be too long and could overlap with other item names.
- before
- after
roll a TM

Add line break for chinese TM item name

---

src/field/pokemon.ts
src/phases.ts

Added some inline documentation about the boss segments logic
As requested [here](https://github.com/pagefaultgames/pokerogue/pull/2672#pullrequestreview-2146713105)
Just code comments
- ~~[] Are the changes visual?~~

[Docs] Add some inline docs for boss segments logic

---

src/locales/pt_BR/ability.ts
src/locales/pt_BR/battle.ts
src/locales/pt_BR/move.ts

Localization (pt): Fixed translation inconsistencies for critical hit messages

---

src/locales/pt_BR/ability-trigger.ts
src/locales/pt_BR/menu-ui-handler.ts

Localization (pt): Added missing translations

---

src/data/ability.ts
src/field/pokemon.ts
src/test/abilities/steely_spirit.test.ts

- implements steely spirit
- fully implement steely spirit
- changed `FieldMoveTypePowerBoostAbAttr` as base class `PreAttackFieldMoveTypePowerBoostAbAttr`
`$npm run test steely_spirit`

[Ability] Fully Implement Steely Spirit

---

src/modifier/modifier.ts
src/phases.ts
src/test/items/grip_claw.test.ts

This fixes a bug where Grip Claw could steal from either enemy at random in a double battle after a successful hit.
Grip Claw is not working the way it's supposed to.
- `modifier/modifier.ts`: Added `getTargets` method to `HeldItemTransferModifier` to help differentiate which Pokemon are affected within the modifier's subclasses (Mini Black Hole and Grip Claw).
- `phases`: The call to apply Grip Claw's modifier is updated to reflect the new args passed to `getTargets`
- test/items/grip_claw.test`: New unit test to check that attack moves boosted by Grip Claw only steal items from their target.
N/A
`npm run test grip_claw`

[Bug] Fix Grip Claw sometimes stealing from the wrong enemy

---

src/field/pokemon.ts

- Do not double the amount of friendship you lose from fainting if you're in classic mode
- Friendship bonuses shouldn't apply to decreases that's so messed up
- This will make getting candy less of a grind
- Balance team approves
- Before the multiplier for classic mode is applied, it first checks if the friendship change is an increase
- Put a log statement on line 3075 of src/field/pokemon.ts: `console.log(starterAmount.value)`
- Faint in classic
- You should have lost 10 friendship not 20

[Balance] Don't apply Classic bonus to friendship decreases

---

src/locales/pt_BR/nature.ts

Translation was the same as "Relaxed"

Localization (pt): Fix translation for "Lax"

---

src/locales/zh_CN/move.ts

Change the 12-character line in the moves description to a 15-character line
Due to the font changes, the previous 12-character line display now looks strange
Enter a Pokemon summary page

[Localization]Fix line break for zh-cn abilities

---

src/data/pokemon-level-moves.ts

replaced magic numbers with descriptive constansts in `pokemon-level-moves.ts`
makes it more clear what the numbers are user for
if it builds & runs all good

[QoL][Refactor] replace `-1` with `RELEARN_MOVE` and `0` with `EVOLVE_MOVE`

---

src/locales/de/egg.ts
src/locales/en/egg.ts
src/locales/es/egg.ts
src/locales/fr/egg.ts
src/locales/it/egg.ts
src/locales/ko/egg.ts
src/locales/pt_BR/egg.ts
src/locales/zh_CN/egg.ts
src/locales/zh_TW/egg.ts
src/ui/egg-gacha-ui-handler.ts
src/ui/text.ts

Localized the names of the gacha machines.
They weren't localized yet.
Localization and the names of the gachas.
See if the Gacha Machine name fits in the Gacha Menu.

Localization: Localized Gacha Machine Names

---

src/locales/ko/bgm-name.ts

I fixed some BGM titles right _in src/locales/ko/bgm-name.ts_
They have wrong boss name. ( team Magma,  tem Galactic)
@EnochG1 look up them in Korean Pokemon Corpus , (I asked about it) but it has wrong information. (by  machine translation)
BGM titles are much clear than previous.
N/A
N/A
~~- [ ] Are the changes visual?~~

[Localization] fixed PR#2797 about boss's name right at BGM title

---

src/locales/zh_CN/party-ui-handler.ts

fix zh-cn typo in party-ui-handler
'接触' -> '解除'

[Localization]fix zh-cn typo in party-ui-handler

---

src/locales/ko/party-ui-handler.ts

updating Korean UI message when learning move 
previous Korean translation is different with original game version text. and also has bad readability.
change korean translation of learning move UI's texts `able` and `notAble`
original pokemon sun/moon in game screenshot of learning move UI
previous version
changed version

[Localization] update korean translation on learning move UI

---

src/data/ability.ts

This change adds an ability bar popup for Parental Bond to display when the ability applies.
Parental Bond currently doesn't have a visual indicator for when it enhances a move. This has led to confusion over why enemy Pokemon are hitting more times than usual with their moves, especially in the case where a boss Pokemon has Parental Bond as a passive.
`data/ability`: Parental Bond's `AddSecondStrikeAttr` now shows the source ability when multiplying the number of hits in a move.
https://github.com/pagefaultgames/pokerogue/assets/168692175/757d0b8f-5f43-424b-9f24-1f54bd993044
1. Give your Pokemon Parental Bond via `src/overrides.ts` > `ABILITY_OVERRIDE`
2. `npm run start:dev`, then start a game.
3. See the pop-up display when your Pokemon attacks.

[Enhancement] Add ability bar popup for Parental Bond

---

src/data/ability.ts
src/test/abilities/costar.test.ts
src/test/utils/gameManagerUtils.ts

Change ability application so it uses an iterator instead of recursion
:spaghetti: 
Change ability application so it uses an iterator instead of recursion
N/A
Check if the ability application order is the same as on main

[Beta] Refactor ability internals

---

src/battle-scene.ts

Fixes the issues caused by merging the beta branch and the PR branch

[Beta] Fix issues from merging Disguise changes

---

src/battle-scene.ts
src/locales/de/settings.ts
src/locales/en/dialogue.ts
src/locales/en/settings.ts
src/locales/es/settings.ts
src/locales/fr/settings.ts
src/locales/it/settings.ts
src/locales/ko/settings.ts
src/locales/pt_BR/settings.ts
src/locales/zh_CN/settings.ts
src/locales/zh_TW/settings.ts
src/system/settings/settings.ts

https://github.com/pagefaultgames/pokerogue/pull/2622

[Beta] #2622 Enhancement shop overlay

---

src/phases.ts

https://github.com/pagefaultgames/pokerogue/pull/2710

[Beta] #2710 add semi invulnerable state check

---

src/ui/confirm-ui-handler.ts

This is my guess for what is causing the error at the moment but I'm not 100% sure.
PR: https://github.com/pagefaultgames/pokerogue/pull/2862

[Beta][QoL] Summary Option Quick-Fix

---

src/locales/en/weather.ts

https://github.com/pagefaultgames/pokerogue/pull/2806

[Beta] #2806 add missed en messages

---

src/data/move.ts
src/test/moves/hard_press.test.ts

Hard Press has the wrong listed base power and PP
Data was incorrect
Hard Press BP is supposed to be -1 like crush grip and wring out
Hard Press max BP is 100 unlike the other two
Hard Press has 10 pp instead of 5
n/a
Pull and override

[Bug] Fix hard press bp and pp

---

src/overrides.ts

Remove value mistakenly added to `overrides.ts`

[Beta] Fix overrides.ts

---

src/field/pokemon.ts
src/system/pokemon-data.ts

This PR is a mirror of #2482 for the `beta` branch.

[Beta][Enhancement] Allow Starters to Remember Egg Moves

---

src/data/move.ts
src/phases.ts

https://github.com/pagefaultgames/pokerogue/pull/2899

[Beta] Decouple move accuracy calculation from phases.ts

---

src/locales/de/settings.ts

Correction of a translation error into German (Settings -> Keyboard -> Stats)
Because the translation doesn't fit and is confusig. In the menu, "Stats" is translated as "statistiken", which is correct, as the user can certainly view their stats there. However, "Stats" is also translated as "statistiken" in the keyboard settings, which is not correct in the context of what the button actually does (display the modifiers of the status values in battle). A more appropriate translation would be "Statuswerte(veränderungen)"  according to the official Terms in Germany.
old
new
Start the Game and go into the Keyboard settings

[Localization] fixed tranlastion error in germany

---

src/locales/pt_BR/ability-trigger.ts
src/locales/pt_BR/biome.ts

Localization(pt): Fixed some translations

---

src/battle.ts
src/locales/de/battle.ts
src/locales/en/battle.ts
src/locales/es/battle.ts
src/locales/fr/battle.ts
src/locales/it/battle.ts
src/locales/ko/battle.ts
src/locales/pt_BR/battle.ts
src/locales/zh_CN/battle.ts
src/locales/zh_TW/battle.ts

Localized moneyPickedUp message
Localized the message "You picked up ₽______!".
before:
after:
Use "Pay Day" or "Make It Rain".

Localized moneyPickedUp message

---

src/test/abilities/costar.test.ts

No more random Gengars or Dugtrios breaking the test. 👍

[Beta] Prevent Arena Trap/etc from breaking Costar test

---

src/test/moves/ceaseless_edge.test.ts

Fixes Ceaseless Edge's third test which allowed for random encounters (possibly flying types or levitate mons)
This test will occasionally fail due to encounters which avoid spike damage (flying types/levitate)
Remove random encounters (set to Rattata), remove random abilities (set to run away).
```npm run test:silent .\src\test\moves\ceaseless_edge.test.ts```

[Test] Prevent flying types/levitate from breaking Ceaseless Edge test

---

src/data/move.ts
src/field/pokemon.ts
src/phases.ts
src/test/moves/fusion_bolt.test.ts
src/test/moves/fusion_flare.test.ts
src/test/moves/fusion_flare_bolt.test.ts

This PR is a mirror of #1774 for the `beta` branch.

 [Beta][Move] Implement Fusion Flare and Fusion Bolt

---

src/locales/it/common.ts

Update common.ts (Italian)

---

src/locales/it/ability-trigger.ts

A couple of abilities were localized in italian.
because there were few abilities not translated in italian
use the abilities in pokerogue upon setting the language in italian

Update ability-trigger.ts (Italian)

---

src/data/ability.ts

- see title
- misleading docs
- docs
- check references/usages for `TypeImmunityAbAttr`

[Misc] Fix inaccurate docs for TypeImmunityAbAttr

---

src/data/challenge.ts
src/locales/en/challenges.ts
src/phases.ts
src/system/game-data.ts
src/ui/challenges-select-ui-handler.ts
src/ui/starter-select-ui-handler.ts

Adds the fresh start challenge. This also includes the underlying challenge refactor to make challenges much more extensible in the future, 
Challenge refactor needed to come, the fresh start challenge is invaluable for testing.
This is mostly a refactor of the challenge system to make the code more robust and better documented.
Try game and challenges, note that everything still works despite major rewrites.

Refactor challenges and add fresh start

---

.github/workflows/github-pages.yml

Make gh-pages workflow use install typedoc package
We were using the lastest package before
use local npm package instead of upstream npx package
N/A
N/A

update gh-pages workflow

---

src/test/moves/hard_press.test.ts

Fixed `Hard Press`'s unit test such that it no longer succeeds or fails non-deterministically.
`Hard Press`'s unit test would cause PRs to "fail" during the `test` check. 
`hard_press.test.ts` was re-written such that it no longer is indeterminate or errors due to `undefined` enemy `Pokemon`. Additionally, the unit test was separated into several tests within the file to have both set scenarios and a wildcard scenario to effectively test the intended behavior of the move.
N/A
Enter `npm run test hard_press.test.ts` into a terminal sourced at the `pokerogue` folder to run the test file.
- https://github.com/pagefaultgames/pokerogue/pull/2984

[Test] Fix/Extend Unit Tests for Hard Press

---

src/locales/ko/dialogue.ts

I fixed some unnecessary typo in Bertha's Korean dialouge.
It's not serious problem! 
I realized it while playing games all night yesterday.
When I translated them in the past, might have made a mistake😅
It will be have right sentence without typo.

[Localization] fixed some typo in Bertha's Korean dialouge

---

src/test/moves/dynamax_cannon.test.ts

Updates `Dynamax Cannon`'s unit tests to reflect the changes made in #2984.
Now that power calculation for moves is done separately as a result of #2984, the unit tests can now also more accurately test the variable power of the move in practice rather than in a vacuum by manually applying `VariablePowerAttr` via a helper function.
Got rid of `checkBasePowerChanges` in favor of spying directly on the move's `calculateBattlePower` calls alongside replacing any instances of direct stat manipulation and `vi.fn()` with spies.
N/A
Enter `npm run test dynamax_cannon.test.ts` into a terminal sourced at the pokerogue folder to run the test file.

[Refactor/Test] Update Dynamax Cannon Unit Tests

---

src/phases.ts

When multi-target moves miss in a single battle, the move is not pushed to the move history, so Encore grabs the next most recent move instead.
These changes push the move to the move history even if it misses.
This is a bug.
I added a call to `pushMoveHistory` when a multi-target move misses. I placed this outside of the condition that the MoveResult is pending, as we still need to track the example of *hits first target, misses second target*.
Before fix (Encores Air Slash)
https://github.com/user-attachments/assets/e1436a05-e2cc-4e04-9eb9-408340edf190
After fix (Encores Heat Wave)
https://github.com/user-attachments/assets/ee823a61-719b-42cf-b6b0-61e8afa41f19

[Bug] Fixes Encore bug with multi-target moves missing

---

.github/pull_request_template.md

----
Add item to checklist for writing automated tests 
Cause ppl need to consider writing some for their issue.
updated the PR template checklist m

[Enhancement] Add tests checklist item to pull_request_template.md

---

src/locales/pt_BR/move.ts

Localization(pt): Updated move.ts

---

src/data/ability.ts

No longer adds the enemy's berry to the user's inventory side when Harvest triggers.
This is a bug.
Adds the conditional check for if the user is a player or an enemy and uses the appropriate `addModifier` function depending on the case.
Before (adds enemy's berry icon to player's inventory)
https://github.com/user-attachments/assets/192b332c-3deb-4f5d-aa93-58c32fb45bf9
After (adds enemy's berry icon to enemy's inventory)
https://github.com/user-attachments/assets/74e09a65-f69f-43e2-8777-25ce8526386b
Give the opponent Harvest and a berry. Trigger the berries effect (preferably in Sunlight so Harvest is guaranteed). See that the berry is added back to the opponent's items instead of the player's

[Bug] Enemy pokemon's Harvest creates berry icons on the player's side when triggered

---

src/data/move.ts
src/field/pokemon.ts
src/test/moves/thousand_arrows.test.ts

This fixes a bug where Thousand Arrows cannot hit targets who are under the effects of Magnet Rise.
This bug was reported [in the Discord](https://discord.com/channels/1125469663833370665/1258239366682247180)
- `field/pokemon`: `Pokemon.getAttackTypeEffectiveness` now supports specific moves as arguments (in addition to just the move's type). If a move is passed, and the move's target has a battler tag that grants it immunity to the move's type, the move is checked for a `HitsTagAttr` which has a matching tag type.
- `data/move`: Added a `HitsTagAttr` to Thousand Arrows to allow it to hit Pokemon with the `MAGNET_RISEN` tag.
- `test/moves/thousand_arrows.test`: Added a test for Thousand Arrows hitting into a Pokemon with Magnet Rise.
N/A
`npm run test thousand_arrows`
- [n/a] Are the …

[Bug] Fix Thousand Arrows not hitting targets under the effects of Magnet Rise

---

.github/pull_request_template.md

Add check item for using the correct base branch

Update pull_request_template.md : add base branch checklist item

---

src/test/moves/thousand_arrows.test.ts

There was an `overrides` variable in use. But it was changed to `Overrides`
So tests don't fail consistently anymore
See [`Files changed`](/pagefaultgames/pokerogue/pull/3111/files) tab
`npm run test:silent`

[Bug] Fix thousand arrows test

---

src/test/moves/rollout.test.ts
src/test/moves/spit_up.test.ts
src/test/moves/stockpile.test.ts
src/test/moves/swallow.test.ts
src/test/utils/testUtils.ts

Added a test for the rollout move
Coverage
I added the rollout test.
I had to fix some existing tests. Dunno how that got through but now it's fixed
`npm run test:silent`

[Test] Add test for rollout move

---

src/data/move.ts

- Implements Jungle Healing and Lunar Blessing's effect of healing status of the user and allies
- This (should) mean they're fully implemented
- The less (P) the better
- Added HealStatusEffectAttr to the moves, once for self and once for target
After using Jungle Healing
- Set a status effect override, double battle override, and then a move override for one of these moves

[Feature] Fully implement Jungle Healing/Lunar Blessing status heal

---

src/data/move.ts

This PR is for fixing bug of water shuriken did not hit 3 guaranteed hits in battle bond form.
it looks already implemented before, but in the previous code, assigning multi hit condition is missing.
so, water shuriken always hit 2-5 times even if in battle bond form.
this will make water shuriken 3 guaranteed hits in battle bond form.
add code for assigning multiHitType with hitType.value after ChangeMultiHitTypeAttr function.
```
applyMoveAttrs(ChangeMultiHitTypeAttr, user, target, move, hitType);
this.multiHitType = hitType.value;
hitTimes = this.getHitCount(user, target);
```
to debugging, I added temporary log message and changing power of water shuriken when battle bond 20-> 1 when i recording following videos.
- before fix ( + debug codes )
water shuriken not hit 3 times ( …

[Bug] Fix the water shuriken did not hit 3 guaranteed hits in battle bond form.

---

src/system/game-stats.ts
src/test/items/leftovers.test.ts

This updates leftovers.test.ts to match changes made re: testing in Beta. 
This is so other PRs stop failing.

[Tests] Updating Leftovers test

---

src/locales/pt_BR/battle.ts
src/locales/pt_BR/config.ts
src/locales/pt_BR/modifier-type.ts
src/locales/pt_BR/modifier.ts
src/locales/pt_BR/settings.ts
src/locales/pt_BR/starter-select-ui-handler.ts
src/locales/pt_BR/weather.ts

[Localization] Translated missing portuguese entries and some fixes

---

src/data/egg.ts
src/data/pokemon-species.ts
src/test/eggs/egg.test.ts

Changed PokemonSpecies hasVariants() function to also check for pokemon with forms.
This function is used when creating an egg to check if the pokemon has variants or not.
I also added an check that prevents rare/epic variants from happening if the egg was pulled from a legendary gacha and rolled as that legendary if this pokemon has no variants.
To fix bugs. It isn't possible to pull a rare/epic miraidon (or other pokemon with forms) from eggs.
https://discord.com/channels/1125469663833370665/1259323885191692419
https://discord.com/channels/1125469663833370665/1259359879429361684
The `hasVariants()` function. It uses the same logic as the function that changes the variant of wild pokemon.
And a small check that sets the variant tier to common if the banner legendary from the gacha got …

[BUG] Fixes bug that prevents pokemon with froms from hatching as rare/epic shiny variant and preventing illegal variants from legendary gacha

---

src/test/abilities/intimidate.test.ts

[BUG] reduce rng on initimidate test

---

src/data/pokemon-species.ts

Review comments from the beta merge PR.
`PokemonSpeciesForm.getAbility()` and `PokemonSpeciesForm.getAbilityCount()` are updated to account for the changes introduced in #3138
`npm run test`?

[Misc] Update `getAbility()` and `getAbilityCount()` for the ability changes

---

src/system/game-data.ts

Fix save bug again, finally, for real this time. Alolan(/etc) Pokémon should work now.

[Hotfix] Use `getPokemonSpecies()` instead of `allSpecies[]`

---

index.css
index.html
src/ui/menu-ui-handler.ts

Disclaimers

---

src/locales/pt_BR/achv.ts
src/locales/pt_BR/battle.ts

Translations
Remake of PRs #3152, #3171 and #3172

[Localization] Update achievement and battle translations in pt_BR locale

---

index.css
index.html

chore: Update TNC links layout and position in index.html

---

src/data/battler-tags.ts

Remake of #3154 with fixed git history.

[Misc] Remove redundant BattlerTag sub-classes

---

src/data/move.ts

Remake of #3155 with fixed git history.

[Misc] Remove redundant `AddBattlerTagAttr` sub-classes

---

src/ui/starter-select-ui-handler.ts

Due to the significant changes in the base beta of the previous PR https://github.com/pagefaultgames/pokerogue/pull/3133 , it has become difficult to merge it.
Therefore, I have checked out from the current beta branch and created a new PR by cherry-picking only necessary commits from the previous PR https://github.com/pagefaultgames/pokerogue/pull/3133.
Please refer to the previous PR https://github.com/pagefaultgames/pokerogue/pull/3133 for detailed information.

[QoL] Update on the requested code changes related to the Starter select UI (new)

---

src/data/egg.ts

Saw a typo, fixed a typo.
Three typos in comments were fixed.
Look at the code.

[Misc] Fix typos in `src/data/egg.ts` comments

---

index.css

chore: Update TNC links font size in index.css

---

src/data/move.ts
src/test/moves/beat_up.test.ts

This fixes a bug where the additional hits given to Beat Up from the user's Multi-Lens would deal no damage (more specifically, the hits would register as dealing `NaN` damage)
closes #2767 
- `data/move`: `BeatUpAttr` now cycles through the eligible party members when the user's total `hitCount` for the turn is more than the eligible party's size.
- `test/moves/beat_up.test`: Three new integration tests for the move Beat Up
- "should hit once for each healthy player Pokemon"
- "should not count player Pokemon with status effects towards hit count"
- "should hit twice for each healthy player Pokemon if the user has Multi-Lens"
N/A
`npm run test beat_up`

[Bug] Fix Beat Up dealing NaN damage with Multi-Lens

---

src/modifier/modifier-type.ts

Removed the reviver seed from trainer modifier pool so Ivy's Rayquaza can't say tee hee I actually revived so you have to fight me again
As per head of balance:
The seed was removed from the trainer modifier pool
- Fight a bunch of trainers and rejoice as none will have the seed of sorrow

Remove Reviver Seed from trainer modifier pool

---

src/locales/it/ability.ts

Honey Gather has been implemented.
So that all abilities are fully translated.
Honey Gather's description has now been translated.
Look at the info of a pokemon with honey gather.

Update ability.ts [Localization(it)]

---

index.css
src/data/egg.ts
src/data/move.ts
src/field/pokemon.ts
src/system/game-data.ts

Sync's beta up to main
Makes PRs to beta not as messy
Just merging
n/a
n/a

Sync beta with changes to main

---

src/data/move.ts
src/test/moves/flame_burst.test.ts

duplicate of https://github.com/pagefaultgames/pokerogue/pull/3131 after beta fix
- implement flame burst
- unimplemented move
- new class `FlameBurstAttr`

[Move] Implement Flame Burst (after beta fix)

---

src/plugins/vite/vite-minify-json-plugin.ts

Fix minify JSON plugin running in vite serve mode
apply minify JSOn vite plugin only in build. Not in serve
It isn’t breaking anything but it’s sub-optimal
added `apply: “build”`

[Bug] Update vite-minify-json-plugin.ts

---

src/locales/fr/modifier.ts

Correction of French `bypassSpeedChanceApply` in modifier.ts
To have a correct sentence
French `bypassSpeedChanceApply` in modifier.ts

[Beta][Localization] Update errors French modifier.ts

---

src/locales/de/ability-trigger.ts
src/locales/de/arena-tag.ts
src/locales/fr/move-trigger.ts
src/locales/pt_BR/ability-trigger.ts
src/locales/zh_CN/ability-trigger.ts

- I added } to all strings that hasnt had it
-  
- because the placeholders were not correctly replaced
- 
- They were missing i added them
None. Just do code review
Use the affected moves in the certain languages

Add missing } in the all localization strings

---

src/field/pokemon.ts

This is in addition to https://github.com/pagefaultgames/pokerogue/pull/3265

[Bugfix][Part 2] Add missing changes from sweet veil PR 

---

src/ui/starter-select-ui-handler.ts

Optimize updateScroll to update only the container within the screen.
After adding a filter and scroll that allows seeing all Pokémon at once in the starter UI, 
some users, especially mobile users, have experienced scroll lag.
[related discord msg link](https://discord.com/channels/1125469663833370665/1176874654015684739/1268111784196440186)
Optimize the part of the `updateScroll` function in `starter-select-ui-handler.ts` that updates the filtered Pokémon information to work only for the Pokémon within the screen and skip those outside the screen.
FYI. timestamp code is not committed in this PR.
before (When switching the entire screen or initializing, it takes ~23 milliseconds. On average, scrolling takes about 4 milliseconds. ) …

[Enhancement] Optimize updateScroll function in starter select UI 

---

src/ui/starter-select-ui-handler.ts

Fixes the bug where the `starterCursor` and `pokerusCursor` are not cleared when scrolling off-screen.
FYI. it happens after merging #3268
If not fixed, many people will see odd behavior in the cursor movements.
Added `starterCursor` and `pokerusCursor` to the section that sets newly off-screen containers to visible(false). Additionally, removed the unnecessary if condition in the main loop. Also, as suggested by temp in the PR comments, replaced hardcoded numbers with variables.
(+ I fix `onScreenLastIndex` too. it was `onScreenLastIndex` + 1 before )
https://github.com/user-attachments/assets/6bba86a4-0494-4d22-8abd-ead1b99ad10f
scrolling with `starterCursor` and `pokerusCursor`

[Bug] Fix remaining pokerus and starter cursor on scrolling in stater select UI

---

src/ui/starter-select-ui-handler.ts

Fixes a bug where newly added filtered Pokémon are not correctly sorted by cost after performing a cost sort for the first time.
it's because there is uninitialized cost at first filtering timing.
FYI. it is already fixed in [ancient old chaos for beta PR](https://github.com/pagefaultgames/pokerogue/pull/2950/commits/cb9cc38156a768762f754265ca49236d69ce9054)  about 2 weeks ago. but it is missing current beta. sorry my bad
Although performing a cost sort again fixes the issue, it's odd and inconvenient.
Added a line of code to initialize the cost value of each container in the filter function loop.
This ensures that the bug caused by uninitialized cost values is fixed.
before fix ( current beta )
https://github.com/user-attachments/assets/1e4e9c7e-b27a-484d-90a7-fadf168e0d02
after fix …

[Bub] Fix `sort` by `cost` bug in starter select UI 

---

docs/enemy-ai.md
src/field/pokemon.ts
src/phases.ts

This adds a new doc `enemy-ai.md` which includes details on the algorithms used to determine the enemy AI's actions within the `EnemyCommandPhase`. This also includes comments for the relevant functions within `field/pokemon.ts` and `phases.ts`, and fixes an issue in `Pokemon.getMatchupScore` where Speed comparisons were having the opposite of the intended effect on matchup scores.
In its current implementation, the Enemy AI decision-making algorithm is fragmented and difficult to understand. Because of this, it can be difficult for new contributors to get a complete frame of reference for the benefit score functions when adding new move attributes. The new documentation should help make the AI's functionality easier to understand and analyze.
-`docs/enemy-ai.md`: New document covering …

[Documentation] Document `EnemyCommandPhase` and Enemy AI functions

---

src/ui/starter-select-ui-handler.ts

Fixed a sprite bug that occurs when selecting a Pokémon with an unimplemented frame or texture (like an Epic Shiny Luvdisc), then selecting a different Pokémon, and performing the "remove from party" action.
Refer to the relevant [Discord bug thread](https://discord.com/channels/1125469663833370665/1267269278302732370).
Although this sprite bug does not actually allow the player to start the run with an incorrect Pokémon, it can cause confusion for users.
Updated the `popStarter` function to include the missing `checkIconId` operation.
before
https://github.com/user-attachments/assets/15cdeb26-ab8a-46ed-85cb-8c8cbf8b63dd
after
https://github.com/user-attachments/assets/d4d262f4-cc71-4f9d-911d-ba95b666048a
you can reproduce like video

[Bug] fix sprite bug when remove from party in starter select UI

---

src/overrides.ts
src/test/battle/double_battle.test.ts
src/test/utils/gameManager.ts

added a revive function in game manager that is currently for player use only. 
added a test of double battle that is related to my last PR. 
one requested an auto test from 
[my last PR](https://github.com/pagefaultgames/pokerogue/pull/3266)
A test related to double battle double fainted and reviving.
if anyone needs it to work on enemy team feel free to implement it.
if anyone planning to do a refactoring of revive modifier, you may want to modify doRevivePokemon() as well
npm run test double_battle.test.ts

[Test] added revive function in gamaManager & a double-battle test

---

src/locales/fr/challenges.ts

Updating translations from localization team.  (https://github.com/pagefaultgames/pokerogue/pull/3305#discussion_r1702313969)

[localization] Update fr locales in challenge

---

src/data/challenge.ts
src/data/pokemon-species.ts

Made sure that Victini, a Gen 5 Pokémon temporarily placed in Gen 4, is correctly filtered as a Gen 5 Pokémon.
Victini, a Generation 5 Pokémon that was being filtered under Generation 4, is now correctly filtered under Generation 5.
Since the addition of scroll functionality to the starter UI, 
there's no longer a reason to incorrectly place Victini in Gen 4. 
This can also cause confusion among users.
- Updated Victini's species Gen information from 4 to 5.
- Removed the no longer necessary workaround code for Victini in the challenge checks.
- However, since Victini's icon sprite is still included in Gen 4, I've added a temporary workaround to map it correctly. (This code should be removed once the Victini icon sprite is moved to Gen 5. ) …

[QoL] Move victini to gen 5

---

src/locales/de/starter-select-ui-handler.ts
src/locales/en/starter-select-ui-handler.ts
src/locales/es/starter-select-ui-handler.ts
src/locales/fr/starter-select-ui-handler.ts
src/locales/it/starter-select-ui-handler.ts
src/locales/ko/starter-select-ui-handler.ts
src/locales/pt_BR/starter-select-ui-handler.ts
src/locales/zh_CN/starter-select-ui-handler.ts
src/locales/zh_TW/starter-select-ui-handler.ts
src/ui/starter-select-ui-handler.ts

Currently, pressing the cancel key immediately exits the starter select screen. To prevent accidentally exiting the UI, a confirmExit popup has been added.
This is one of the features we discussed implementing in the starter select UI in [discord thread](https://discord.com/channels/1125469663833370665/1267339517371875361/1267873483807916073).
Added the confirmExit popup logic to the existing condition for exiting with the cancel key.
Uploading Screen Recording 2024-08-03 at 6.52.15 PM.mp4…

[Enhancement] Add confirm exit popup in starter select UI

---

src/phases.ts

Reverts pagefaultgames/pokerogue#3288

Revert "[Bug][Mirror] Fixed impossible forced switch"

---

src/phases.ts

duplicate of Pr #3135 
---
When parting shot fails, the debuffs no longer apply
Closes #3112 
Added check in move workflow that doesn't apply a move's attributes when a move fails
- `beta`
https://github.com/user-attachments/assets/d4922730-e09f-4654-9d3e-7ab213b9a73f
https://github.com/user-attachments/assets/837e7ae6-c58f-402c-a2aa-0ed25b18578e
- `pr`
https://github.com/user-attachments/assets/05395f98-8365-47b5-81a3-a699db4c8d63
https://github.com/user-attachments/assets/5dc9342b-2747-47b3-a9a6-305e7e6d4518
Using overrides, the 2 cases were:
- user of parting shot has ability Prankster and the opponent is a dark type
- opponent has the ability Good as Gold

[BUG] - Re: Parting shot debuff applies even if move fails

---

.github/pull_request_template.md

Mirror of https://github.com/pagefaultgames/pokerogue/pull/3302
Updating the pull request template
```
From: "## What are the changes?`
To:   "## What are the changes the user will see?"
From: "## What did change?"
To:   "## What are the changes from a developer perspective?"
Added: - [ ] If I have text, did I add placeholders for them in locales?
```
n/a
n/a

New pr template

---

src/locales/de/filter-bar.ts
src/locales/en/filter-bar.ts
src/locales/es/filter-bar.ts
src/locales/fr/filter-bar.ts
src/locales/it/filter-bar.ts
src/locales/ko/filter-bar.ts
src/locales/pt_BR/filter-bar.ts
src/locales/zh_CN/filter-bar.ts
src/locales/zh_TW/filter-bar.ts
src/ui/filter-bar.ts
src/ui/starter-select-ui-handler.ts

Rename the `Dex` filter to `Caught`.
Before adding filters like HA (Hidden Ability) and Pokerus, we planned to include filters like HA, gender, and Ability within the current Dex filter, hence the name Dex.
However, after several tests, it became apparent that implementing these filters in such a manner was challenging. [related discord message](https://discord.com/channels/1125469663833370665/1267339517371875361/1269680312330358918)
As a result, the HA filter was added to the Misc filter, and the other filters will also likely not be included in the Dex filter in the future.  
To prevent confusion for users using or developing this filter further, we are changing the name from Dex to Caught. This ensures that the current functionality of the Dex filter does not overlap with the …

[QoL] Change Dex filter name to Caught

---

src/locales/en/filter-bar.ts
src/ui/starter-select-ui-handler.ts

I will change the filter name from "Normal" to "Not Shiny" in English. 
Additionally, I will remove the "no pokerus" option from the pokerus filter.
Multiple people suggested a more natural English translation. 
Given the nature of the pokerus filter, there is hardly any reason to use the "no pokerus" option.
The English filter name translation has changed from "Normal" to "Not Shiny." 
The "no pokerus" option has been removed from the pokerus filter.
https://github.com/user-attachments/assets/7f4e6a19-1b71-43f4-820f-39beb098fadc

[QoL] update requested changes on Starter UI

---

src/locales/ja/weather.ts

ja/weather.ts translations
All Japanese locales can be translated.
Translate Weather, Terrain (Japanese)
N/A
N/A

[Localization][JA] Translation of weather.ts

---

src/ui/text.ts

Font is now different for german
I already had this added but someone removed this again (as an error i guess)
See screenshots
Before:
After;

Fixing the German stats page

---

src/battle-scene.ts
src/modifier/modifier.ts
src/phases.ts
src/test/items/exp_booster.test.ts
vite.config.ts

Reverted egg exp multiplier from additive to multiplicative and fixed the endless biome rotation at every 5 waves instead of randomly.
Reverted egg exp multiplier from additive to multiplicative and fixed the endless biome rotation at every 5 waves instead of randomly.
Play endless, biome should rotate every 5 waves

Drawing motivated egg additive exp calculation revert + endless wave rotation fixed at every 5 waves

---

src/test/abilities/serene_grace.test.ts
src/test/abilities/sheer_force.test.ts
src/test/abilities/shield_dust.test.ts
src/test/abilities/zen_mode.test.ts
src/test/items/leek.test.ts
src/test/items/scope_lens.test.ts
src/test/moves/fusion_flare_bolt.test.ts
src/test/moves/gastro_acid.test.ts
src/test/utils/testUtils.ts

- no functional changes, only changes the util name + improve docs
naming convention
function name
n/a
`$ npm run test`

[Dev] Update changeTurnOrder name to mockTurnOrder (naming convention)

---

src/test/abilities/hustle.test.ts
src/test/abilities/libero.test.ts
src/test/abilities/magic_guard.test.ts
src/test/abilities/parental_bond.test.ts
src/test/abilities/protean.test.ts
src/test/abilities/sweet_veil.test.ts
src/test/utils/testUtils.ts

- adds util for mocking hitCheck
- easier way to mock hitCheck()
- removes code redundancy in multiple test files
- new util `mockHitCheck`
n/a
`$ npm run test`

[Dev] Add mockHitCheck util

---

src/locales/de/ability-trigger.ts
src/locales/de/ability.ts
src/locales/de/pokemon-info-container.ts
src/locales/de/pokemon-info.ts

I added 2 keys that were in english but not german and fixed a space that was too much
To have it up to date with english
2 new keys, 1 change to a existing one
None
Code review.

[Localization] German missing keys

---

src/locales/ja/challenges.ts

Discordでこの質問を聞きましたが、ここでも聞いて置きます:
"Starters" をどう翻訳しましょうか？一番合ってる公式の用語は「最初のパートナー」だと思いますが、ちょっと長いです。

[JA] [Localisation] Translate challenges.ts

---

src/locales/ja/achv.ts

I added translations to all achievement descriptions and titles. In all honesty, all the titles are just first drafts based on my own sense of humor. Definitely need proofreading/brainstorming with a native speaker.
実績の説明文と名前を翻訳しました。実際に、今は名前がただ個人的なギャグセンスから思いついた例文です。ご時間があれば、ぜひ校正または意見やギャグのおすすめをお願いします！

[JA] [Localization] First draft translated achv.ts

---

src/test/final_boss.test.ts

fix strict null for test
test broke with strict null
test

fix strict null broken

---

src/phases.ts
src/system/game-data.ts
src/ui/rename-form-ui-handler.ts
src/ui/starter-select-ui-handler.ts

In the starter select UI, it is now possible to set nicknames for Pokémon!
Many users have requested this feature (myself included!).
1. Added a rename menu for setting nicknames.
2. Included a nickname attribute in the starter settings, which will be used during the `tryStart` process.
3. Assigned this feature to integrate with the current nickname functionality.
( so, The rename settings in the start UI are only used for initializing the starter party in a new run. )
https://github.com/user-attachments/assets/0c6ebf96-b9a2-4bda-844e-cff7d8dc5c44

[Enhancement] Allow nickname assignment in the starter select UI.

---

.github/pull_request_template.md

cf #3360 and #3302
Silly temp transposed the changed of the first section into the second section.

[Github] Update Pull Request template

---

src/phases.ts

Removing the `.destroy()` calls, more testing needed to make sure no adverse affects
Addressing #3453 which was originally caused by #3346 
After fix, doubles dragon tail fix still seems ok
https://github.com/user-attachments/assets/4b298cc5-8329-48cc-bb8c-ecdf806f1745
https://github.com/user-attachments/assets/b64f0a27-29d3-47f6-9cd1-424ddb35fdf3
https://github.com/user-attachments/assets/f49cb55c-9068-477f-9961-9cbb5c475337

[Bug][Hotfix] - Calling destroy() on enemy pokemon after BattleEndPhase breaks endless

---

src/locales/ja/voucher.ts

Need to be consistent with names of vouchers in [modifiers.ts].

[JA] [Localisation] Translated voucher.ts

---

src/field/pokemon.ts
src/test/endless_boss.test.ts
src/test/final_boss.test.ts
src/test/utils/gameManager.ts
src/test/utils/gameWrapper.ts
src/test/utils/mocks/mockTextureManager.ts
src/test/utils/mocks/mocksContainer/mockTexture.ts

updates the boss passive changes to include endless/spliced endless Eternatus
previously was only disabled for Classic
updates disable to work in endless
Endless 250
https://github.com/user-attachments/assets/b6a8cea9-d668-4307-9aff-6b1c06aba210
Endless 1000
https://github.com/user-attachments/assets/15845081-a3e1-4f0d-8a9c-3c911103a824
Endless Spliced 250
https://github.com/user-attachments/assets/e6a13577-99c2-4dd7-82dc-d8ad54422543
Endless Spliced 1000
https://github.com/user-attachments/assets/2497865c-7d58-439a-99a6-e5659e3c9da6

Disable endless boss passives

---

src/test/abilities/libero.test.ts
src/test/abilities/sand_spit.test.ts
src/test/battle/double_battle.test.ts
src/test/battle/error-handling.test.ts
src/test/moves/foresight.test.ts
src/test/moves/miracle_eye.test.ts
src/test/moves/tailwind.test.ts

Might as well make sure the test names are correct.
Changed some test names to match what's being tested.
`npm run test`

[Test] Fix test names that weren't changed from copy/pasting

---

src/test/utils/gameManager.ts
src/test/utils/testUtils.ts

no functional changes, just moves removeEnemyHeldItems to gameManager.ts
- I feel like testUtils should be used for general utils and not game/battle-specific. 
- The function is directly related to game state which the GameManager class describes `manage the game state and transitions between phases`
- the function could then be directly accessible to the `game` instance instead of manually importing it ie `game.removeEnemyHeldItems()`
This removes:
- phases imports
- parameter `game` from the function
no functional change
n/a
`$ npm run test`

[Dev] Move function from testUtils.ts to gameManager.ts (3/3)

---

src/modifier/modifier-type.ts

- Removes Ability Charm from the reward pool on and after wave 189 in classic
- Paradox mons don't have hidden abilities
- It sucks to roll a Rogue tier item that's functionally useless
- Changes Ability Charm's weight function to use the skipInClassicAfterWave function
- Otherwise has the same weight

[QoL] [Balance] Skip Ability Charm in rewards after classic wave 189

---

src/locales/ja/save-slot-select-ui-handler.ts

"Wave" needs special coding to look correct in Japanese.

[JA] [Localisation] Translated save-slot-select-ui-handler.ts

---

src/data/ability.ts
src/field/pokemon.ts
src/test/abilities/flash_fire.test.ts

baton pass no longer pass it. 
ability still activated if user is frozen. 
(and a test file for it. )
according to : https://bulbapedia.bulbagarden.net/wiki/Flash_Fire_(Ability)
As stated above, I mean changes in code are straight forward. 
Delete some code, move some code. 
https://github.com/user-attachments/assets/3cc7b083-3c0a-41f9-9476-1536285fb74c
test locally.

[Bug][Test] Fix minor bug of ability Flash Fire, added test file

---

src/ui/starter-select-ui-handler.ts

Set the initial filter setting to include all Pokémon except uncaught ones.
For new users, almost all Pokémon are in the uncaught state, and for users who have played for a while, it's inconvenient to use the Gen1 filter as the initial setting.
[Link to related Discord discussion thread](https://discord.com/channels/1125469663833370665/1267339517371875361/1272423623621349417)
In modes other than the Challenge mode,
Previously, the initial setting involved hovering over the Gen1 option in the gen filter.
Now, it has been changed to hover over the Gen All option in the gen filter and to select options other than the uncaught option in the caught filter in all modes!
https://github.com/user-attachments/assets/c49be69c-3179-498e-9e1e-555be500067f

[Enhancement] update initial filter setting when not in challenge mode

---

src/modifier/modifier-type.ts

Kind of an expansion on #3477 
- Skips the following rewards in classic wave 199:
- Lure
- Super Lure
- Max Lure
- Exp All
- Exp Balance
- Exp Charm
- Super Exp Charm
- IV Scanner
- Candy Jar
- Lock Capsule
- All these items are useless against the final boss:
- Lure items obviously have no effect on the final boss
- Experience items are useless because you're not getting XP from the final boss
- IV scanner is redundant because the final boss has set perfect IVs
- Candy Jar and Lock Capsule buff your rewards in future waves, but this is the last reward for the run so it's useless
- Used the "skipInLastClassicWaveOrDefault" function for these items
- On another branch I have a function written to be used for Mega Ring, Tera Orb and a couple other items that have weight functions, but I …

[QoL] [Balance] Skip useless rewards in last classic reward wave

---

src/data/pokemon-level-moves.ts

- Replaced some of our custom starting moves with equivalent canon moves
- Some mons have a custom starting move so they have moves to use early game, this replaces some of those
- Moved Psybeam on Misdreavus so you can start with it and hit Normal-types
- So movesets mesh with main series slightly better
- Replaced Throh's Karate Chop with Rock Smash (learns by TM/HM)
- Gave Turtwig Leafage at level 5 and Growth at level 10 as in BDSP
- Moved Flutter Mane's Psybeam from level 7 to level 1
- Replaced Giratina's Twister with Dragon Breath, gave it Ominous Wind instead at level 7 (these both match USUM)
- Replaced Magearna's Fairy Wind with Disarming Voice (learns by TM)
- While I was there, gave it Gear Up and Crafty Shield, 2 dexited level 1 moves

[Balance] Replaced some custom starting moves with equivalent canon moves

---

src/battle-scene.ts
src/battle.ts
src/data/ability.ts
src/data/battle-anims.ts
src/data/daily-run.ts
src/inputs-controller.ts
src/messages.ts
src/phases.ts

There are a lot of `//TODO: Is this bang correct?` comments from the `strict-null` adaption PR. #3259 
I've resolved some of those.
To get rid of those TODO.
Nothing game-wise. There was one `=== undefined` that I changed to `!var` since it would have caused havoc otherwise (the variable will never be `undefined` but `null`)
- Run the tests successfully
- Run the game successfully

[Refactor] resolve some open `strict-null` TODOs

---

src/data/pokemon-forms.ts
src/data/pokemon-species.ts
src/locales/ca_ES/pokemon-form.ts
src/locales/de/pokemon-form.ts
src/locales/en/pokemon-form.ts
src/locales/es/pokemon-form.ts
src/locales/fr/pokemon-form.ts
src/locales/it/pokemon-form.ts
src/locales/ja/pokemon-form.ts
src/locales/ko/pokemon-form.ts
src/locales/pt_BR/pokemon-form.ts
src/locales/zh_CN/pokemon-form.ts
src/locales/zh_TW/pokemon-form.ts

Reverts pagefaultgames/pokerogue#3537

Revert "[Balance] [QoL] Allow Pirouette Meloetta to be selectable on starter screen"

---

src/phases.ts
src/ui/party-ui-handler.ts
src/ui/ui.ts

Don't allow the UI flyouts to lock out users when `class UI method showText()` is called
The game is unplayable.
https://discord.com/channels/1125469663833370665/1273029028210671748/1273128441012686858
https://discord.com/channels/1125469663833370665/1273029028210671748/1273130314465546261
Remove problematic if statement and made appropriate refactors
Tutorial 
[tutorial.webm](https://github.com/user-attachments/assets/d6a9d93c-fc4f-48e7-bf55-891e83046f4d)
Arena Trap
[arena-trap.webm](https://github.com/user-attachments/assets/4984651c-df50-4c3c-9040-bcfe69d41a0d)
Ingrain
[ingrain.webm](https://github.com/user-attachments/assets/2c93ac66-c7da-4588-ad22-10f77fef14a3)
Unfuse Pokemon
[unsplice.webm](https://github.com/user-attachments/assets/b01c2c73-c6de-4785-96b9-8aa70d385268)
Release …

[Bug] [Beta2] Fix flyout freeze

---

src/ui/starter-select-ui-handler.ts

- Fixed a bug where Pokémon with only rare/epic shiny but no common shiny were unable to use cycle shiny.
- Hotfix.
- The existing canCycleShiny condition was only checking for common shiny, which caused the bug where Pokémon with only rare/epic shiny could not use cycle shiny. 
- This has been fixed by modifying the condition to check for common/rare/epic shiny using an OR logic, allowing Pokémon with any type of shiny to use cycle shiny.
-before
-after

[Hotfix] Fixed the bug where Pokémon with only rare/epic shiny but no common shiny were unable to use cycle shiny

---

src/system/game-data.ts

- Fixed a bug where Unown would get stuck in the Z form during cycle form.
- Otherwise, we would be stuck using only the Z form Unown forever.
- In the existing getFormAttr function, cast the value to BigInt to prevent overflow.
- before
- after

[Hotfix] fix Unown Z Form stuck bug

---

src/ui/starter-select-ui-handler.ts

- Kangaskhan and Latias are now correctly displayed as female again.
- Hotfix.
- This bug likely occurred due to changes in previous dex-related default settings.
- The conditions for displaying gender were corrected to ensure they are not incorrectly selected.
- before
- after

[Hotfix] Fix Male only bug on female only pokemon

---

src/field/pokemon.ts

- Fixes an oversight where egg moves are relearnable in daily runs
- Egg moves would impact scoring
- Adds a check if it's a daily run before adding egg moves to relearnable moves
Phione has all egg moves unlocked:
I put in an item reward override for memory mushroom, here's what it looks like using it:
Main (daily run):
Fixed (daily run):
Still works as intended in Classic
Still works as intended in Fresh Start
- [] If I have text, did I add placeholders for them in locales?

[Bug] Fixed egg moves being relearnable in daily runs

---

src/ui/battle-message-ui-handler.ts

There was a change with the... stat enum that made HP now be 0. This meant that in some cases where the HP enum was being called in a condition for checking top IVs, it would trigger as falsy and cause issues. This PR fixes that
There's a discord thread about this bug [here](https://discord.com/channels/1125469663833370665/1274420818465525760)
Due to a stat change enum, this line of code (which would previously get the highest stat to show for the IV scanner) could now have a shownStat of 0, which is HP:
```if (shownStat) {```
Due to this, if HP is the highest stat, instead of continuing the if statement to get the highest stat, it would skip the if check and go to the next stat. However, since the next stat would be HP, it would fail again, and end up showing ??? for all stats instead of …

[Bug] Fixed issue with falsy issue within condition to get a stat for IV scanner

---

src/phases.ts

This change fixes a bug where if an enemy KO's both of the player's active Pokemon in a double battle, leaving the player with exactly one legal, non-fainted Pokemon in their party, the player would then not be prompted to switch in their last Pokemon, leaving the enemy Pokemon to repeatedly use moves until they softlock the game with no usable moves left.
Smashing obscure bugs is my passion (also closes #3609 )
- `phases`: The logic for generating phases within a player Pokemon's `FaintPhase` has been rewritten (and documented), and now correctly accounts for the currently bugged sequence
The following videos show how the game handles player faints in different scenarios after the rewrite.
https://github.com/user-attachments/assets/b5a1abe9-b0c4-4404-bbf6-2204c8ef5a43 …

[Hotfix] Fix softlock when the Enemy KO's 2 out of 3 player Pokemon at the same time

---

.github/ISSUE_TEMPLATE/feature_request.yml

Fix auto labels for feature requests

[Hotfix] Update feature_request.yml

---

src/locales/it/achv.ts

Some achievements have been localized
Because some achievements weren't localized
Achievements for the fresh start challenge and the bring your child to work thingy have been translated to IT.
- Fresh start will now be translated to "Un nuovo inizio" (quite literally the translation of it)
- Bring your child to work is now translated to "Alternanza scuola-lavoro" (it's a thing we have in italy were high school students are brought into workplaces to learn some actual job related stuff, thought that was fitting)

Update achv.ts (IT)

---

src/locales/it/challenges.ts

Some stuff regarding challenges has been localized
to localize everything in IT
Fresh start has been localized with "Un nuovo inizio", and the sentence appearing when a pokemon turns into another pokemon not eligible for the challenge has been localized as well.

Update challenges.ts (IT)

---

src/locales/it/battler-tags.ts

translated last missing things
because it was needed
last things in battler-tags.ts have been localized in italian as well

Update battler-tags.ts (IT)

---

src/locales/it/menu-ui-handler.ts

localized the you're not hatching any eggs at the moment text
because it was yet to be localized
that text is now localized in italian

Update menu-ui-handler.ts (IT)

---

src/locales/it/modifier-type.ts

everything about various objects has been localized in italian
to localize everything
white herb's description and the hold c or shift for more info text have been localized

Update modifier-type.ts (IT)

---

src/locales/it/modifier.ts

everything left in this file has been localized in italian
some stuff couldnt be found on official sources, hence why i tried my best to stick to whatever i could find from official stuff and made up some little adjustments.

Update modifier.ts (IT)

---

src/locales/it/move-trigger.ts

localized two missing sentences
to localize everything
all stat changes were eliminated and identified sentences were localized in italian

Update move-trigger.ts (IT)

---

src/locales/it/move.ts

zippy zap was localized
because it wasnt localized yet
zippy zap is now localized in italian
check zippy zap's description in italian

Update move.ts (IT)

---

src/locales/de/battler-tags.ts
src/locales/de/starter-select-ui-handler.ts

4 lines are now shown correctly in german instead of english
They are not yet translated
I just changed localization files for german. No other code changes
The screenshots only show AFTER
Play in german. Do the things (no clue how to describe it better?)

[Localization] Brought DE Loc up to date

---

src/data/ability.ts
src/test/abilities/moody.test.ts

Moody will no longer increase/decrease the same stat
It's a bug
The `MoodyAbAttr` was not using the proper Array when selecting a stat to decrease. I replaced `selectableStats` with `decreaseStatArray` which filters out the increased stat before selecting a stat to decrease.
Before fix (Only SpAtk rose on second turn):
https://github.com/user-attachments/assets/d785e68c-d5ac-4af0-a89f-b35d73b1c3eb
Give your mon moody, see that it no longer selects the same stat.
- [n/a] If I have text, did I add placeholders for them in locales?

[Bug] Fixes Moody increasing and decreasing the same stat

---

src/data/pokemon-species.ts

The player can now use a male or female Dipplin. 
Daily bug hunting.
Bug report: https://discord.com/channels/1125469663833370665/1276372031243423754/1276372031243423754
Dipplin somehow had a null for its malePercent variable when it should have been 50. 
Male Dipplin
Female Dipplin
Starter Select Dipplin - Gender is now choosable
Go to Starter Select and choose a Dipplin, or fight a Dipplin.

[Bug] Giving gender to Dipplin

---

src/ui/starter-select-ui-handler.ts

Remake of #2808 and #3279 lmao
Reworked the Candy Upgrade Notification logic to take account of the new "Buy Egg" option.
A new mechanic was implemented (Buying Eggs).
The logic of the 'On' setting and added some constants to make the code more readable.
Test if the candy icon appears whenever you can buy eggs.

[QOL] Candy Upgrade Notification Rework

---

src/test/abilities/disguise.test.ts

N/A
The test used the old function which no longer exists.
Fixes the Disguise test.
`npm run test disguise`

[Test] Update new disguise test with test framework changes

---

src/inputs-controller.ts
src/main.ts
src/typings/phaser/index.d.ts

move module declaration to .d.ts files
remove jsdoc annotations as it doesn't take effect
eliminate any type in main

centralize module typing overrides

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md
src/battle-scene.ts
src/ui/menu-ui-handler.ts
src/ui/ui.ts

Main to Beta sync

---

src/data/move.ts
src/test/moves/lunar_blessing.test.ts

Fixes the bug with Lunar Blessing healing the user twice and not its ally.
It's a bug
Sets the `selfTarget` boolean to false for the `HealAttr`. Removes redundant lines of code from Lunar Blessing and Jungle Healing
Before change
https://github.com/user-attachments/assets/fd3f63a7-d7c3-4c79-8592-7c2b0e4033bb
After change
https://github.com/user-attachments/assets/1d654873-4470-4b20-b40f-1e6b30e86fea
Give your pokemon Lunar Blessing, give both your pokemon a status effect in a double battle, have both pokemon take damage, see that Lunar Blessing heals and cures both.
- [n/a] If I have text, did I add placeholders for them in locales?

[Bug] Fixes Lunar Blessing only healing twice on the user instead of ally

---

src/data/pokemon-evolutions.ts

None. This does not change anything to the user
Because this was not clear from reading the code. (For example scatterbug is clear because pre and post have the same form key)
I basically just wrote in the code that spiky pichu can only evolve into partner and non spiky into non partner (like it already is)
None
Evolve pichu in both forms and see the outcome

[Dev] Clarify Pichu Evolution behaviour in code

---

src/test/utils/helpers/dailyModeHelper.ts

N/A
The test could fail if some items got turned into Ultra Balls, which would cause an unexpected `MessagePhase` to occur.
`phaseInterceptor.run()` changed to `phaseInterceptor.to()` in the daily mode helper class.
`npm run test daily_mode`

[Test] Fix daily mode test being unreliable

---

src/battle-scene.ts
src/field/pokemon.ts
src/overrides.ts

none
no existing override for opponent's forms + `integer` type phase out in `overrides.ts`
new override `OPP_FORM_OVERRIDES`, moved other overrides to `EnemyPokemon` class
use similar to `STARTER_FORM_OVERRIDES`

[Dev] Cleanup some opponent overrides + add new opp form override

---

src/ui/ui.ts

None :)
Previous merge of #3846 accidentally had a bad merge with beta branch and the enum location was out of order with the rest of the handlers, breaking run history, run info and the admin panel. See [here](https://discord.com/channels/1125469663833370665/1176874654015684739/1278725434703614102) for it
Moved Mode.ADMIN enum to be in line with the handler
Current screenshots of beta. In this, I am going to menu->run history:
It's a black screen because it doesn't work
Current screenshot of the broken admin panel in beta:
It doesn't exist because I don't have an admin account, but trust me it's broken
Current screenshot of run history with this fix:
Current screenshot of the admin panel (with a fake admin account) with this fix:
Download this PR and try to open the run history and admin …

[Bug] Moved Mode.ADMIN enum to be in line with the handler

---

src/timed-event-manager.ts

Banner should display correctly upon refresh. 
my bad
this.event.bannerKey no longer directly modified. 
title page

[Beta][Bug] Fixing banner error upon refresh

---

src/locales/en/achv.json
src/locales/en/dialogue-double-battle.json
src/locales/en/dialogue-final-boss.json
src/locales/en/dialogue.json

none
GitLocalize does not seem to like `null` values on keys!
I removed all `"<key>_female": null` entries in `locales/en`
check the file changes 
Just play basically. Especially dialogues.

[Localization] remove all `"<key>_female": null` entries in `locales/en`

---

create-test-boilerplate.js
package.json

none
As someone having written a bunch of tests for moves/abilities, the least fun process is:
- looking for the test directory
- manually creating the test file
- copying from another test file
- pasting to the new file
- (sometimes forgetting to rename the description)
- cleaning up the file to have a "fresh template"
This PR aims to automate the above and possibly add more options in the future for the resulting file.
new script to automatically create and fill a move/ability test
`npm run create-test move test_move`

[Dev] add script to create test boilerplate file

---

src/test/abilities/hustle.test.ts
src/test/abilities/wind_rider.test.ts
src/test/moves/fake_out.test.ts
src/test/moves/gigaton_hammer.test.ts

N/A
One of the Hustle tests could rarely fail due to rounding.
One of the Wind Rider tests was missing an override call to give the Pokémon the Wind Rider ability. :plains:
The Fake Out and Gigaton Hammer tests were using outdated functions.
The tests no longer fail. 🎉
`npm run test [testname]`

[Test] Update/fix some tests

---

src/phases/switch-summon-phase.ts

- Fixes oversight where the game will say "<Trainer> withdrew Foe <Mon>!" instead of "<Trainer> withdrew <Mon>!"
- Awkward wording
- Called pokemon.getNameToRender instead of getPokemonNameWithAffix
Before:<img width="761" alt="Screenshot_861" src="https://github.com/user-attachments/assets/6c21375e-3f9a-4bae-885b-81efd9c9dd3e">After:<img width="762" alt="Screenshot_862" src="https://github.com/user-attachments/assets/396b719e-1bc3-4053-a569-dce620d8e9d5">
- Change line 62 in enemy-command-phase.ts to if(true) to make enemies always switch, then go to the wave 5 battle

[Bug] Fix affix used when enemy trainer withdraws

---

src/data/dialogue.ts

Rood will now use his dialog lines.
The lines were left out of `dialog.ts`, meaning they were never shown to the player.
Added Rood's dialog keys to the array in `dialog.ts`.
Set him to be a fixed encounter by editing `classicFixedBattles` in `battle.ts`.

[Misc] Add dialog lines for Rood to `dialog.ts`

---

src/locales/de/pokemon-form-battle.json

See Screenshots
So it is localized
Just localized the key
https://github.com/user-attachments/assets/4c418a06-1465-4a7b-b47a-cc88758bfc0a
Start with the pkm and get hit

[Localization] [DE] DisguiseChange

---

src/locales/es/pokemon-form-battle.json

Removed an extra tab added by GitLocalize
Approve and merge 🙏

[Localisation] [ES] Bugfix pokemon-form-battle.json

---

src/field/pokemon.ts
src/modifier/modifier.ts
src/phases/learn-move-phase.ts
src/system/pokemon-data.ts

- Player mons will be able to relearn TM moves previously taught to that mon during the run
- This will, of course, only track the TMs used after this patch is applied
- Adds a "fromTM" boolean parameter to the LearnMovePhase constructor (I imagine this would be very useful for other purposes too)
- Adds a "usedTMs" array to Pokemon data
After teaching Trick Room to Mewtwo, then forgetting Trick Room for another move, then using a Memory Mushroom:
- Add TMs and Memory Mushroom to item reward overrides
- Use a TM
- Forget the move you learned from that TM
- Use Memory Mushroom

[Balance] [QoL] [Feature] Allow mons to track and relearn used TMs

---

index.css
index.html
src/locales/en/menu-ui-handler.json
src/ui/menu-ui-handler.ts

Removed the cookies from the html and added a Donations link on the community page (with guidance from Walker)
https://github.com/user-attachments/assets/801ef4b5-1f59-4ebb-9799-a9ba558ca18c
Open game menu > Community > Donate
Should lead to https://github.com/sponsors/patapancakes
~~- [ ] Have I considered writing automated tests for the issue?~~
~~- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~~

Added Donate Link to Community Page

---

src/test/moves/freeze_dry.test.ts

N/A
There were no tests.
Type effectiveness tests were added for Freeze-Dry (including 2 disabled tests, 1 due to a bug and 1 due to an unimplemented move).
`npm run test freeze_dry`

[Test] Add tests for Freeze-Dry

---

src/locales/de/battle.json
src/locales/de/challenges.json
src/locales/de/menu-ui-handler.json

See screenshots (the egg skip one is not yet in beta so i checked out the egg skip branch for that)
They are missing in the localization
New Keys added to german loc
Have the text pop up ingame

[Localization] [DE] Added missing keys in DE

---

src/locales/en/dialogue.json

Error reported by issue #4018 
Added a missing word in one of Ariana's lines
To have a correct sentence

[Localization] [EN] Ariana dialogue fix

---

src/system/game-data.ts
src/system/modifier-data.ts
src/system/version-converter.ts

Ideally, none; existing run history and sessions should retain all their existing modifiers and held items when transitioning from the existing `main` branch to the incoming `beta` branch.
Because of #2699 and #4032, vitamins, battle items, lures, and `White Herb` would break any outdated sessions on parse and load; this PR essentially aims to coalesce save migration into a set of functions called once for migrating over old data into new formats, naming schemes, etc.
Essentially created three separate functions that follow `SessionSaveData`, `SystemSaveData`, and the `settings` object respectively on load. Each function uses a `switch-case` block intentionally with no `break`s to let patches apply from the top-down in order of older to newer versions. By the end of that block, all …

[Dev] Save Data Version Migration

---

src/field/pokemon.ts
src/test/battle/inverse_battle.test.ts

Scrappy, Mind's Eye abilities and the moves Foresight, Odor Sleuth, Miracle Eye no longer make moves that should deal 2x damage instead deal 1x damage in inverse battle.
These abilities and moves no longer affect type matchups in inverse battles!
In Inverse Battles, these moves and abilities should not nullify type immunities (e.g., Normal -> Ghost, Psychic -> Dark), so they should have no effect. ( which are already 2x damage in inverse battle )
However, the existing code caused these moves and abilities to forcibly make the attacks deal 1x damage against these types, which is a bug.
The code has been modified so that these moves and abilities do not alter type effectiveness in Inverse Mode. 
Additionally, new test cases for Inverse Battles have been added ( + including tests to confirm …

[Bug] Fix scrappy (+ some immunity move and ability) in inverse battle

---

src/system/version-converter.ts

For any users who could not load into the game due to an error within `applySystemDataPatches`, they should be able to now.
Users were essentially blocked from being able to enter the game due to an `null` access, forcing them into the "Failed to load system data" screen.
Fixed an oversight where `data.gameVersion` was checked in an `if` block for existence instead of `data.starterData`.
N/A
The best way would be to use the system data provided in [this bug report](<https://discord.com/channels/1125469663833370665/1282387337162264626>), place it into your own local storage `user_Guest` data, and make sure the data is decrypted during parsing. The game should load as normal without any hitch. 
Errors in the process may include JSON parsing errors (not decrypting the incoming data), …

[Hotfix] Fix System Data Conversion Failure

---

src/data/move.ts

none
accessing `undefined` tag, a `null` check is present but a tag is `undefined` if there was no retrieved tag
converted the condition to check for truthy values instead
Before fix:
https://github.com/user-attachments/assets/3af22c61-740b-4197-932d-9b192beacf01
After fix:
https://github.com/user-attachments/assets/6e4ef947-967d-46a9-a095-b51d5008c657

[Bug] Fix console error from undefined stockpilingTag

---

src/field/pokemon.ts
src/phases/learn-move-phase.ts

Fixes issue #4107 
- For some reason usedTMs is not initialized by starter select
- There was a stray usedTms in PlayerPokemon structure
- Checks if usedTMs is a thing before pushing to it, if not it initializes it

[Hotfix] Fix crash when teaching TM to starter in new run

---

src/battle-scene.ts
src/data/mystery-encounters/mystery-encounter-pokemon-data.ts
src/field/pokemon.ts
src/phases/game-over-phase.ts
src/system/game-data.ts
src/test/mystery-encounter/encounters/absolute-avarice-encounter.test.ts
src/test/mystery-encounter/encounters/an-offer-you-cant-refuse-encounter.test.ts
src/test/mystery-encounter/encounters/field-trip-encounter.test.ts
src/test/mystery-encounter/encounters/lost-at-sea-encounter.test.ts
src/test/mystery-encounter/encounters/uncommon-breed-encounter.test.ts

update tests for MEs

---

create-test-boilerplate.js
src/test/moves/power_shift.test.ts
src/test/moves/tar_shot.test.ts

none
obsolete util
removed util from tests

[Test] Remove obsolete SPLASH_ONLY

---

src/test/abilities/gorilla_tactics.test.ts
src/test/moves/throat_chop.test.ts

none
Gorilla Tactics
- `expect(enemy.hp).toBe(enemy.getMaxHp());` - will always resolve to true because splash is used
Throat Chop
- `expect(game.scene.getPlayerPokemon()?.getStatStage(Stat.ATK)).toBe(0);` - this should check the enemy, not the player pokemon
replaced `expects`

[Test] Fix oversights from Throat Chop and Gorilla Tactics tests

---

src/phases/quiet-form-change-phase.ts

Very minor, fixes the Transform sound effect not playing on quiet form changes.
While attempting to get the tera-based form changes working, I noticed that the sound effect on quiet form changes wasn't playing, so I fixed it.
Correctly points the file to the new location of the Transform sound effect now.
Before
https://github.com/user-attachments/assets/1eb2b54a-d1de-469d-9cf0-1c99b913b989
After
https://github.com/user-attachments/assets/215142e1-8f76-482f-9457-8f2919377ec7
Simply use a Pokémon with a quiet form change. Terapagos is easiest as it immediately changes form.

[Bug] Fix Transform SFX not playing on quiet form changes

---

src/data/egg.ts
src/test/eggs/manaphy-egg.test.ts

Implements the correct rare egg move and species rates for Manaphy eggs, as requested by damo:
https://discord.com/channels/1125469663833370665/1176874654015684739/1278204045328257025.
1. Manaphy eggs from the gacha now have a 1/8 chance (instead of the bugged ~1/4 chance) of hatching Manaphy.
2. Phione species eggs still have a 1/8 chance of hatching Manaphy.
3. Manaphy eggs have a base rare egg move rate of 1/12 (matching epic eggs), regardless of whether the hatched species is Phione or Manaphy.
Requested by damo (see above).
1. When checking whether or not to upgrade a Phione egg to a Manaphy egg, the code now checks whether the Phione egg was bought with candies (as opposed to being pulled from the gacha).
2. `rollEggMoveIndex()` now has a special case for Manaphy eggs.
N/A
Hatch a …

[Balance/Bug] Rare egg move and species rates for Manaphy eggs

---

src/ui/starter-select-ui-handler.ts

- The starter ui will play the CH-CHING!! buying sound when you unlock a passive on a starter
- It makes the experience of buying a passive much more satisfying
- Plays the buy sound effect after passive unlock like after cost reduction and egg purchase

[UI/UX] Make "CH-CHING!" sound when unlocking passive

---

src/system/version-converter.ts

For any users who could not load into the game due to an error (reading `caughtAttr` on `undefined`) within `applySystemDataPatches`, they should be able to now.
Users were essentially blocked from being able to enter the game due to an null access, forcing them into the "Failed to load system data" screen.
Added more `undefined`/`null` guards to prevent trying to access fields in objects that weren't initialized yet during the save migration process.
N/A
Similar to #4123, the best way would be to use the latest system data provided in [this bug report](https://discord.com/channels/1125469663833370665/1282387337162264626), place it into your own local storage `user_Guest` data, and make sure the data is decrypted during parsing. The game should load as normal without prompting any console …

[Hotfix] Fix System Data Conversion Failure 2

---

src/ui/run-info-ui-handler.ts
src/ui/ui.ts

Xbox and DualShock gamepad users can now see appropriate instructions in the run history UI!
It's impossible to press the appropriate buttons if you're looking at keyboard instructions while using a gamepad. (Is it just me?)
added logic to update icons based on the gamepad option. (Mobile touchpad still uses keyboard instruction icons)
added a getGamepadType function to allow quick checks of the gamepad option at various points in the code.
- before ( using an Xbox controller, but the instructions are shown for the keyboard )
- after ( The correct instructions for the Xbox controller are displayed )

[Enhancement] Update instruction for gamepad in run history UI

---

src/ui/starter-select-ui-handler.ts

N/A
More cleanup from the `strict-null` update.
Removed some unnecessary `!`, marked that `setTypeIcons()` can accept `null` values.
There are no functional changes.

[Misc] `setTypeIcons()` explicitly handles `null`, mark it as such

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

- To introduce a new `Triage` label to mark issues that haven't been "triaged"/confirmed/checked.
- Simplify and streamline the bug-template which has been overloaded with information req. for a while now
Start creating a new issue in my fork
https://github.com/flx-sta/pokerogue/issues
I have the branch set as default right now which allows to preview it

[Misc] Update issue/feature template

---

src/data/move.ts

N/A
More docs is more good (usually).
Add tsdocs to a couple fields and some enum values.
Replace nearby instances of `integer` with `number`.
Utilize default values in a couple of fields.
`npm run test`

[Misc] Add some tsdocs to `move.ts`, also some misc cleanup

---

src/ui/modal-ui-handler.ts

- Nothing probably
- Linter issue merged into beta making every PR fail lint check
- Added spaces after commas

[Bug] Fix linter issue

---

src/test/moves/roost.test.ts

None
Just updating a few roost tests to be consistent, like fixing turn order between oppenent and user to get proper 
interactions every time and reduce chance of RNG affecting test outcomes
related to #4164
Using set turn order
npm test roost
- [X ] **I'm using `beta` as my base branch**
- [X ] There is no overlap with another PR?
- [x ] The PR is self-contained and cannot be split into smaller PRs?
- [ x] Have I provided a clear explanation of the changes?
- [X ] Have I considered writing automated tests for the issue?
- [x ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x ] Have I tested the changes (manually)?
- [x ] Are all unit tests still passing? (`npm run test`)

[Unit Test] Update roost tests, related to #4164

---

src/test/mystery-encounter/encounters/uncommon-breed-encounter.test.ts

[Test] Disable broken ME tests for now

---

src/field/pokemon.ts

Sometimes when using the golden punch it picks it up as NaN money to add to your score, which breaks your money and doesn't let you buy stuff. Looks like this was added accidentally in #3975 
In [main](https://github.com/pagefaultgames/pokerogue/blob/main/src/field/pokemon.ts), the damage field here is a number holder, whereas in [beta](https://github.com/pagefaultgames/pokerogue/blob/beta/src/field/pokemon.ts#L2665) it's a number. This means sometimes when the golden punch is being applied, it would use 95 and try convert it to a number holder, which fails and returns NaN during the [apply calculation](https://github.com/pagefaultgames/pokerogue/blob/beta/src/modifier/modifier.ts#L2418) when trying to convert `args[1] as Utils.IntegerHolder`
I changed pokemon.ts for the golden punch …

[Bug] Golden punch bug fix

---

src/field/pokemon.ts

`"It doesn't affect {{pokemonName}}"`
will now show correctly show as
`"It doesn't affect ${getPokemonNameWithAffix(pokemon)}"`
I broke the message with #3975 haha
Added a missing key replacement to the "No Effect" message in `Pokemon#apply`

[Bug] Fix missing key in "No Effect" message

---

src/locales/es/menu.json

Added a line-break to the server connection error in Spanish
Added a line breaks so it will fit the box.

[Localization] Update menu.json

---

src/locales/en/mystery-encounters/trash-to-treasure-dialogue.json

The description of the selection changes to match the actual effect.
I'm ME tester and translator. 
When work, i found that the scripts were mixed up.
here is the discussion [in Discord](https://discord.com/channels/1125469663833370665/1229525892624154684/1284957065759948861)
↓This is the effect the item currently has. (It used to be a different effect, so I think it's less modified.)
```
"MYSTERY_ENCOUNTER_BLACK_SLUDGE": 
{ "name": "Black Sludge",
"description": "The stench is so powerful that shops will only sell you items at a steep cost increase." },
```
just fixing an incorrect description.
in english script
none.
Run that event by overrides

[Bug]fixed ME event ```trash to treasure``` wrong descriptions of the choices

---

src/ui/abstact-option-select-ui-handler.ts
src/ui/achvs-ui-handler.ts
src/ui/scroll-bar.ts
src/ui/settings/abstract-control-settings-ui-handler.ts
src/ui/settings/abstract-settings-ui-handler.ts
src/ui/starter-select-ui-handler.ts

- The scrolling in Achievements/Vouchers, settings and other menus now resets on exit/re-entry
- The Achievements/Vouchers menu navigates like the starter select grid
- The Achievements/Vouchers menu has a scrollbar
- The Settings have scrollbars when needed
- The achievements menu would sometimes break when exiting and coming back: #4112 
- Similarly the settings scrolling would not reset properly when exiting, leading to confusion when exiting the settings and later coming back
- The achievements menu wouldn't allow scrolling down if there wasn't an achievement just below the cursor, even if there was still another row to show
- For both achievements and settings it was hard to know exactly where we were at in the list of elements, the scrollbar fixes that issue
- For `AchvsUiHandler`, …

[Bug][UI] Fix scrolling UIs not resetting properly and add Scrollbars

---

src/phases/egg-lapse-phase.ts

no more double candy when hatching eggs
Having `Egg Skip` setting set to `Ask` and choosing to not skip to summary results in both the EggHatchPhase and EggSummaryPhase to award the candy, resulting in double candy gains
If choosing not to skip to Egg Summary, just don't show the summary at all after hatching.
This was discussed with damo and makes the most sense right now considering:
- When the `Egg Skip` setting is set to `Never` the summary is not shown, so this is more consistent
- When hatching then going to the summary the summary doesn't actually show properly the new unlocks like egg moves (this can be seen in the before video, Squirtle gets its rare move during hatching but it doesn't show as new in the summary). So until this gets fixed showing the egg summary after the hatch …

[Bug] Fix double candy from eggs when not skipping to summary

---

src/data/challenge.ts

The evil team you face in monogen challenges will now be determined by what generation you choose.
Being able to set evil teams like the Elite Four/Champions is a desired change.
The set waves on 35, 62, 64, 66, 112, 114, 115, and 165 are now split nine ways to accommodate the nine generations of teams. Team Rocket is intentionally duplicated to handle both generation 1 and 2 monogen, and the teams in generations 3 and 7 are merged together for this purpose as well.
https://github.com/user-attachments/assets/d430aa17-e469-4ae5-ad49-1a21bb24999a
Do some monogen challenge runs. You can also override the waves to the evil team fights to immediately test them.

[Enhancement] Set appropriate evil team on monogen challenges

---

src/data/trainer-config.ts

New Evil Team's Lead Pokemon in Fight 2 will now be able to pull their signatures more reliably
The signature would never spawn on the forms
Reordered the config to put FormIndex over Move Generation
Overrides

[Bug] Fix Revavroom Config

---

src/data/dialogue.ts

That other lines then line 1 can actually spawn
Because they were missing
I added the rest of the keys in dialogue.ts
None
Play against team star (fixedBattles for example)

[BUG] Add enough keys in dialogue.ts for team star

---

src/test/mystery-encounter/encounters/teleporting-hijinks-encounter.test.ts

Tests where being flaky because of e.g. `Download` ability.
Make default ability `BALL-FETCH` too
```
npm run test:silent
```

[Tests][Mystery-Encounter] Teleporting hijinks fix flakyness

---

src/locales/es/move.json

Translated Zippy to Spanish
Needed translating since it got changed.

Update missing translation in Spanish move.json

---

src/data/trainer-config.ts

Ghetsis2 will no longer crash
Genesect's form change could be out of bounds
Utils.randSeedInt is silly
n/a
Pull and test

[Beta][Bug] Fix out of bounds Genesect in Ghetsis_2

---

src/locales/fr/mystery-encounters/a-trainers-test-dialogue.json
src/locales/fr/mystery-encounters/absolute-avarice-dialogue.json
src/locales/fr/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
src/locales/fr/mystery-encounters/berries-abound-dialogue.json
src/locales/fr/mystery-encounters/bug-type-superfan-dialogue.json
src/locales/fr/mystery-encounters/clowning-around-dialogue.json
src/locales/fr/mystery-encounters/dark-deal-dialogue.json
src/locales/fr/mystery-encounters/field-trip-dialogue.json
src/locales/fr/mystery-encounters/fiery-fallout-dialogue.json
src/locales/fr/mystery-encounters/fun-and-games-dialogue.json
src/locales/fr/mystery-encounters/lost-at-sea-dialogue.json
src/locales/fr/mystery-encounters/mysterious-challengers-dialogue.json
src/locales/fr/mystery-encounters/mysterious-chest-dialogue.json
src/locales/fr/mystery-encounters/part-timer-dialogue.json
src/locales/fr/mystery-encounters/slumbering-snorlax-dialogue.json
src/locales/fr/mystery-encounters/the-expert-pokemon-breeder-dialogue.json
src/locales/fr/mystery-encounters/the-strong-stuff-dialogue.json
src/locales/fr/mystery-encounters/the-winstrate-challenge-dialogue.json
src/locales/fr/mystery-encounters/training-session-dialogue.json
src/locales/fr/mystery-encounters/uncommon-breed-dialogue.json
src/locales/fr/mystery-encounters/weird-dream-dialogue.json

ME French text corrections
To exterminate typos in French ME
None

[Localization] ME French Typos

---

src/locales/en/mystery-encounters/the-expert-pokemon-breeder-dialogue.json

Reverts the issue with missing dialogue tokens
Fixed:

[Beta/Bug] Fix Breeders ME Dialogue Token Issue

---

src/ui/starter-select-ui-handler.ts

Pikachu's form label will always show in starter select
When moving directly from the filters to Pikachu or when Pikachu is the first Pokemon to get shown in starter select its form label currently does not show up
There was an oversight that made the form label visible only for Pokemon without pre-evolutions, moved the line that makes it visible outside of the if statement it was in so that it's visible for all starters
Before:
https://github.com/user-attachments/assets/3e5ab86c-2330-441a-a2ef-a4d3c378eb49
After:
https://github.com/user-attachments/assets/01ea366d-32a3-4ae7-9882-74dda7ddb022
- Start a new game and filter type to electric Pokemon, or start a mono-electric challenge
- Pikachu's form label should show properly when you move from the filters to Pikachu
- All other starter's …

[P3] Fix form name not always showing in starter select

---

package-lock.json
src/system/version-converter.ts

Reverts pagefaultgames/pokerogue#4429

Revert "Bump rollup from 4.18.1 to 4.22.4"

---

src/locales/fr/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
src/locales/fr/mystery-encounters/part-timer-dialogue.json

Typo corrections
To correct typos typos
None

[Localization] [Bug] Tiny French typos

---

src/locales/es/mystery-encounters/department-store-sale-dialogue.json
src/locales/es/trainer-names.json

Corrected a Typo and put a $ to fit the text into dialogue box 
Typos/Corrections

[Localization] Minor Spanish Typo Corrections

---

src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts

Prevents the Bug-Type Superfan from having a dupe species in her 160+ team.

[Beta][Bug] Fix bug-type superfan's team on waves 160+

---

src/locales/de/battler-tags.json

Param is now correctly shown
Because it is wrong
Changed spelling of param

[Localization] [DE] Battler tags fix

---

src/data/pokemon-evolutions.ts
src/modifier/modifier.ts

Reverts pagefaultgames/pokerogue#4463

Revert "[Bug] [Balance] Gimmighoul evolution adjustments/fixes"

---

src/modifier/modifier.ts
src/phases/mystery-encounter-phases.ts

This fixes a case of the user having a noninteger amount of money which bricks the save file because saving/loading does not work with noninteger money

Black sludge hotfix

---

src/data/move.ts

[Hotfix] Swap switch out check from `isBoss` to `wave % 10`

---

src/phases/game-over-phase.ts
src/system/game-data.ts
src/system/version-converter.ts

Handles any accidental corrupted saves with non-integer money values and sanitizes the value before saving to server.

sanitize all money when saving session data to server

---

src/locales/fr/mystery-encounters/bug-type-superfan-dialogue.json
src/locales/fr/mystery-encounters/uncommon-breed-dialogue.json
src/locales/fr/settings.json

Typos / corrections
Typos / corrections
None

[Localization] [P3 Bug] French hotfix

---

src/locales/zh_CN/modifier-type.json

Gimmighoul zh-CN Treasure desc fix
Gimmighoul zh-CN Treasure desc fix

[Localization] [P3 Bug] Gimmighoul zh-CN Treasure desc fix

---

src/locales/en/move-trigger.json
src/locales/es/move-trigger.json
src/locales/fr/move-trigger.json
src/locales/it/move-trigger.json
src/locales/ja/move-trigger.json
src/locales/ko/move-trigger.json
src/locales/pt_BR/move-trigger.json
src/locales/zh_CN/move-trigger.json
src/locales/zh_TW/move-trigger.json

See screenshots
It was wrong in all languages but german
changed placeholder name
(English as example) 
Before:
https://github.com/user-attachments/assets/e21313d7-c8d2-47ec-88cd-f8a32a4d0de1
After:
https://github.com/user-attachments/assets/46ac0674-d74e-4313-a18c-1b5567a09f75
Use the move

[Hotfix] Fixing Placeholder in afterYou

---

src/modifier/modifier.ts

Fixes session data for Black Sludge item missing its shop modifier.

fix Black Sludge on session reload

---

src/phases/turn-start-phase.ts

No change
@flx-sta [request this in trick room challenge](https://github.com/pagefaultgames/pokerogue/pull/4343#discussion_r1768937206) updates.
but that [challenge should be merged later](https://discord.com/channels/1125469663833370665/1288886843995324548/1289265289158066279) after release#7 
so, I bring this optimization code here first
remove reverse function when applying trick room challenge and order it once with `const speedReversed`

[Refactor] Optimize trick room ordering code

---

src/field/pokemon.ts

- None
- Makes it easier/more accessible to adjust them or possibly move them to another file
- Added `const BASE_SHINY_CHANCE` and `const BASE_HIDDEN_ABILITY_CHANCE` to src/field/pokemon.ts
- Used these instead of previously-used magic numbers inside functions

[Refactor] Move base shiny and HA chance to consts outside functions

---

src/phases/game-over-phase.ts

N/A
Having redundant identical functions increases the potential for future bugs.
A redundant function is removed from `game-over-phase.ts` and replaced with the one from `game-data.ts`.
Game over I guess.

[Refactor] Remove redundant session data function

---

src/data/move.ts

N/A
The parameters serve no purpose and are entirely unused. Also noticed the tsdocs were formatted incorrectly so I fixed those at the same time.
A bunch of unused parameters were removed, so there's effectively no noticeable impact.
`npm run test`

[Refactor] Remove unused parameters in move flag functions

---

src/ui/egg-gacha-ui-handler.ts
src/ui/starter-select-ui-handler.ts
src/ui/test-dialogue-ui-handler.ts

some code was hard-wired with  locales having to be present. This is no longer the case now

[Bug][external-locales] fix locales hard wiring

---

src/ui/egg-gacha-ui-handler.ts
src/ui/starter-select-ui-handler.ts

N/A
Some now obsolete comments were missed in a previous PR #4529.
Removed the obsolete comments.

[Misc] Remove obsolete comments

---

create-test-boilerplate.js

none
outdated docs + hardcoded message
updated docs, made message dynamic based on `typeChoices`
`npm run create-test`

[Dev][Misc] Cleanup test boilerplate script

---

.github/workflows/deploy.yml

N/A
Allow default repository branch to be changed from `main` to `beta`.
Connected Github issues can be automatically closed by merged PRs instead of requiring manual closure (or waiting for the `beta -> main` merge).
- ~[ ] Are all unit tests still passing? (`npm run test`)~

[Github] Change deploy script to specify "main" instead of `default_branch`

---

src/ui/starter-select-ui-handler.ts

The game will start correctly after revisiting the challenge select screen.
Fixes #4520
Exiting starter screen to challenge selection screen and title screen with the challenge mode selected will result in the same phases queued. 
Before:
https://github.com/user-attachments/assets/2c6e58b7-d4be-4154-af1a-a742aa4fd18e
After:
https://github.com/user-attachments/assets/658b86ec-9290-448a-bbfd-a36dec91ee16
Use the steps given in the original bug report:
- Add `ITEM_UNLOCK_OVERRIDE: [Unlockables.ENDLESS_MODE]` to overrides
- Create new Challenge
- Pick the challenge you want, validate
- Once in starter select, go back to the challenge selection menu
- Validate the selected challenge again
- Add Pokemon to the team
- Start the run, pick the save slot
- ~~[ ] Have I considered writing automated …

[Bug] Challenge mode crash fix

---

src/field/pokemon.ts
src/phases/level-up-phase.ts
src/system/achv.ts

Damage Achievements trigger properly again
[Discord bug report](https://discord.com/channels/1125469663833370665/1291512239085588490/1291512239085588490) / Got broken with #3975 
- Wrap the damage value in the expected `NumberHolder` when validating the achievement
- Also added check for `NumberHolder` type of the argument in the achievements that use it, to avoid similar issues in the future
For before pics, see the [discord bug report](https://discord.com/channels/1125469663833370665/1291512239085588490/1291512239085588490)
After:
https://github.com/user-attachments/assets/ba1ead6d-5175-4c70-aa11-db1306d38dc4
- Use a private window / new account to make sure achievements are not unlocked
- Load up [sessionData2_10kdmg.txt](https://github.com/user-attachments/files/17292468/sessionData2_1 …

[P2] Fix damage achievements

---

src/phases/title-phase.ts

Pokemon in the 1st wave of a daily can no longer have the same ID as one of the starters
Closes #4621 
When fixing the seed used to generate starters for other modes in PR #4505 I couldn't recreate the same issue for daily mode so assumed it was fine, which was wrong
Shift the seed by 0 instead of 1 when generating daily mode starters, like for other modes. This way wave 1 enemies are not generated using the same seed as the starters at all. More detailed explanations in PR #4505 
(Like the original PR this does not fix already existing saves with the issue)
Before, wild Pokemon in first wave of oct 7th daily shared ID with starter Skorupi, leading to shennanigans similar to the ones described in PR #4505 
After, using the same seed, all different IDs:
- In `title-phase.ts`, change line …

[Bug] Prevent generating Pokemon with duplicate IDs in daily mode

---

src/phases/move-phase.ts

The battle info flyout will properly show how much PP has been used by the enemy again.
Fixes #4622 
Fixed line 229 to use `this.move.ppUsed` instead of `ppUsed`.
<details>
<summary>After Fix</summary>
</details>
Enter a battle and have the enemy use the same move at least twice.

[Bug] Fix enemy used PP flyout

---

src/ui/save-slot-select-ui-handler.ts

(Beta only) No more weirdness when clicking "Load Game" with slow network
(Beta only) Fix slot not always being reverted to the right place when moving the cursor
In PR #4410 the way session slots were displayed while loading was altered in a few problematic ways:
- the save slots would only get shown once they have finished loading instead of showing an empty slot with "loading" message
- during loading it was still possible to move the cursor (like it was before), but due to the above point it would cause visual issues and bugs
- the save slots would get loaded sequentially instead of in parallel
This is especially visible when playing on a device with slowish internet connection, and wasn't noticed before because our testing was made locally
This PR reverts some of these changes to get …

[P3 Beta][UI] Fix loading behavior introduced with save preview

---

src/battle-scene.ts
src/phase.ts

N/A
Currently, phases get logged in the console only if they call `super.start()` sufficiently many times. This causes the console to be missing a few phases, which could sometimes cause confusion during debugging.
Moved the `console.log()` statement so that it gets called right before any phase is started in `battle-scene.ts`.
Before the changes:
After the changes (We can see that, for example, the reviver seed starts a `PokemonHealPhase`):

[Misc] More complete phase logging

---

src/ui/run-info-ui-handler.ts

None.
Ease of Development. 
Developers no longer have to worry about editing run-info-ui-handler when creating a new challenge
Start a run with Fresh Start on.

[Misc][UI] Default Case for Challenge Rules

---

src/data/mystery-encounters/encounters/safari-zone-encounter.ts

N/A
Requested by senior devs: https://discord.com/channels/1125469663833370665/1288886843995324548/1296117657199706156, in relation to #4661.
Deleted some commented code.
N/A
N/A
- ~~[ ] Have I tested the changes (manually)?~~

[Misc] Clean up commented safari zone code from #4661

---

src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts

The Expert Breeder Mystery Encounter will now have a chance to use Smoochum until wave 60 like most other baby Pokémon in their species pool, instead of always being Jynx.
It was inconsistent with all the other baby species in the Pokémon species pools.
Jynx was changed to Smoochum, and a `BreederSpeciesEvolution` entry was given to it for it to evolve into Jynx.
Set the Mystery Encounter override to the Expert Breeder, and fight. It may take a few battles to see it due to the randomness.

[P2 Bug] Fix Expert Breeder species entry for Jynx not using baby species

---

src/battle-scene.ts

N/A
(To the best of my knowledge, this crash should have no effect whatsoever for users who are not using overrides.)
So that this crash does not cause false alarms during testing.
In the code for loading the ME type, if `canBypass` is true (i.e., the function is being called by save preview), it also returns the ME type early if the override is on, which avoids the crash.
Before the changes:
After the changes:
1. Have a session file that is currently at an ME.
2. Activate `MYSTERY_ENCOUNTER_OVERRIDE`.
3. Load the save preview for the session file from Step 1, and observe that no crash occurs.

[Misc] [Beta] Fix crash when loading save preview with Mystery Encounter Override active

---

src/battle-scene.ts

N/A
This code was missed when #4231 was made.
Replaced an instance of duplicate code with the function that is supposed to replace it.
Try to get into a double battle I guess?

[Refactor] Replace duplicate code with `getDoubleBattleChance()`

---

src/ui/pokemon-info-container.ts

New abilities properly show up as blue in the egg summary screen
Got broken with PR #4307 - [discord bug report](https://discord.com/channels/1125469663833370665/1297844832256917578)
Use the provided starterEntry instead of getting it from the data directly since by that point in egg summary it has already been updated with the hatch information
Before:
https://github.com/user-attachments/assets/1692c9da-3b7d-4a08-b51d-d8c98d364e40
After:
https://github.com/user-attachments/assets/1268dd21-671c-4417-9f5e-81b8e7c7a2b1
Overrides, hatch eggs, view egg summary
```
EGG_IMMEDIATE_HATCH_OVERRIDE: true,
EGG_FREE_GACHA_PULLS_OVERRIDE: true,
FREE_CANDY_UPGRADE_OVERRIDE: true
```
~~- [] Have I considered writing automated tests for the issue?~~
~~- [] If I have text, did I make it translatable and …

[P3][UI] Fix Egg Summary not showing new abilities in blue

---

src/system/pokemon-data.ts

fix oversight with save migration

---

package-lock.json
package.json
src/data/balance/species-egg-tiers.ts
src/data/egg.ts
src/test/eggs/egg.test.ts

- Eternatus eggs (bought using candies) will be Legendary eggs instead of Common eggs.
- Bug report: [Discord](https://discord.com/channels/1125469663833370665/1125894949020381285/1299930698479702088)
It's a bug.
1. In `species-egg-tiers.ts`, changed Eternatus' egg tier to Legendary.
2. Added a check in `egg.ts` to prevent Eternatus from showing up in the Legendary Gacha as a result of the above change.
3. Added tests in `egg.test.ts`.
After the changes:
Buy an Eternatus egg using candies, and observe that it is a Legendary egg.
- ~~[ ] **I'm using `beta` as my base branch**~~

[Hotfix] Fix Eternatus egg tier

---

src/modifier/modifier-type.ts

- None
- Refactoring janky code
- Removing `getAttackTypeBoosterItemName` function which looks like this:
- And is only used here:
- This was probably done before localization was formalized. Having a switch statement for hardcoded names which then have to be regexed into usable names is ???
- An enum could have multiple uses
- Removes `getAttackTypeBoosterItemName` function from `src/modifiers/modifier-types.ts`
- Adds AttackTypeBoosterItem enum, currently local to that file
- Uses that instead
- Has no bearing on localization
As you can see it does not mess things up

[Refactor] Change attack type booster names to enum

---

src/ui/menu-ui-handler.ts

Donation Link will go to PagefaultGames
Thinking of the poor hamsters...
Link goes somewhere else.
Link goes to a different page.

[UI][Misc] Update Donation Link 

---

src/data/ability.ts

none
- missing edgeCase flag for gulp missile
- added `edgeCase()` to gulp missile
n/a

[Doc] Add `edgeCase()` flag for Gulp Missile

---

src/data/balance/pokemon-evolutions.ts

- Maybe Solgaleo/Lunala show up earlier?
- Removes evolution level parameter from Cosmoem's evolutions
- Does not affect player's ability to evolve it
- Cosmoem is an item evolution and not meant to have a level parameter
- Changed evolution level from 53 to 1

[Balance] Fix Cosmoem having an evolution level

---

src/plugins/api/api-base.ts

none
This was added with the API refactor, but may result in people accidentally sharing stuff they shouldn't when trying to troubleshoot
removed log

[Dev] Remove logging for api requests

---

src/data/mystery-encounters/encounters/weird-dream-encounter.ts

Fixes #4669 
Taking the "Quickly Leave" option in the weird dream encounter reduces your party's levels by 10%. 
Before this change, your party's levels would _visually_ stay at their prior levels in the main battle view until they surpassed their original level.
Now, the visual levels will immediately match the true, decreased levels.
It confused me so I figured I'd change it.
One-liner fix to call the setLevel function on the pokemon battleInfo, updating the level visual
https://github.com/user-attachments/assets/3f4d7d50-1229-46b3-b231-e5508f48c1e2
Use overrides.ts to force the weird dream encounter, pick the level decreasing option, make sure it's visually updated

[Bug] Fix visual bug with pokemon level decrease in weird dream encounter

---

src/phases/game-over-phase.ts
src/test/phases/game-over-phase.test.ts
src/test/utils/phaseInterceptor.ts

Local builds will not softlock when the player loses a run.
Fixing a bug introduced by #4834.
1. Added back a missing `else { doGameOver(false); }`.
2. Moved the `this.handleUnlocks()` check into `if (this.isVictory && newClear)` (the currently available unlocks all require winning a run).
3. Added some basic tests for `GameOverPhase`.
<details>
<summary> Before the changes: Losing a run causes a softlock </summary>
https://github.com/user-attachments/assets/0408d381-f11b-4166-ae1c-6ea6c1a81704
</details>
<details>
<summary> After the changes: Losing a run no longer causes a softlock </summary>
https://github.com/user-attachments/assets/e22dce91-4220-4479-8399-c21732c318cf
</details>
1. Turn off your server (typically localhost:8001), and set `VITE_BYPASS_LOGIN=1` in `.env.development`. …

[P1][Beta] Fix softlock when losing a run on local build

---

src/system/game-data.ts

No more lost accounts from the `null to BigInt` error (hopefully)
A player [reported this error](https://discord.com/channels/1125469663833370665/1229525892624154684/1305310276631138365) which was caused for them by a single starter's `caughtattr` being null. Losing access to an account because of a single Pokemon's data getting corrupted somehow is not great.
This PR doesn't fix the cause of the corruption which is currently unknown but makes sure there is proper fallback and the data still loads
When parsing starter data replace null attributes with 0 before converting it to BigInt
<details><summary>Before: Data fails to load and is reset</summary>
</details>
After:
- Download [corrupted-data.txt](https://github.com/user-attachments/files/17758679/corrupted-data.txt)
- Run the game
- …

[P1] Prevent losing saves from null dexData attributes

---

src/modifier/modifier.ts

- Gimmighoul's evolution counter increases more based on what kind of treasure item the player picks up:
- 1 for Nugget
- 2 for Big Nugget
- 3 for Relic Gold
- Requested by balance
- Changes the apply method for MoneyRewardModifier for increasing evoCounter
`readonly ITEM_REWARD_OVERRIDE: ModifierOverride[] = [{ name: "NUGGET" }, { name: "BIG_NUGGET" }, { name: "RELIC_GOLD" }];`
- *PTSD flashbacks*

[Balance] Increase Gimmighoul's evo counter more with Big Nugget/Relic Gold

---

src/data/ability.ts
src/test/abilities/wimp_out.test.ts

Follow up to #4899 with test from @PigeonBar + some comments 
Test added for checking that Wimp Out behaves correctly in this situation. 
npm run test wimp_out

[Misc] Follow up to Wimp Out bug fix

---

.github/pull_request_template.md

<details>
<summary>Full text without diff view in the way (updated)</summary>
```md
```
</details>

[GitHub] Overhaul GitHub pull request template

---

src/data/ability.ts

N/A
Gulp Missile had received an `.edgeCase()` due to a bug. Since then, #4859 fixed the bug but forgot to remove the `.edgeCase()`.
Title.
N/A
`npm run test gulp_missile`

[Misc] Remove obsolete `.edgeCase()` from Gulp Missile

---

README.md

Github main readme will have updated credits
ME and starmobile artists were not credited
Just updating markdown text
n/a
n/a

[Docs] Update artist credit

---

package-lock.json
package.json
src/ui/login-form-ui-handler.ts

New button that users to download saves they have locally stored. 
The beta server got wiped so this is a last hail mary attempt at rescuing data from players.

[Feature] Add save download functionality with JSZip integration

---

src/ui/login-form-ui-handler.ts

No difference.
Just added the extensions to files to make the import process easier to understand by the average user.

[Misc] Append .prsv to data recovery file names to prevent user confusion

---

src/field/pokemon.ts

- You no longer lose candy progress (aka candy friendship) when your Pokémon faints
- The candy loss from fainting is pretty much anti-QOL, and it's odd to have a way for a player to lose meta progression
- Part of the effort to alleviate the candy grind seen in #4947 
- I previously adjusted this in #2552 
- Removed the block in the `PlayerPokemon.addFriendship` function in `pokemon.ts` that adjusts candy friendship when the `friendship` parameter (the friendship to be added/subtracted) is less than 0
- Because it's no longer used in that else block, the function has been cleaned up a little so that all starter-based code is moved inside the if block (which only runs if the friendship change is positive)
A fresh Weedle
Weedle after fainting
Weedle if it wins instead of faints
Are there …

[Balance] Remove candy friendship loss from fainting

---

src/constants.ts
src/data/splash-messages.ts
src/test/data/splash_messages.test.ts
src/ui/title-ui-handler.ts

Reverts pagefaultgames/pokerogue#5009

Revert "[UI/UX] Refactor and enable seasonal splash messages"

---

src/data/balance/tms.ts

- Annihilape can learn Tera Blast by TM

[Balance] Fix Annihilape Tera Blast Compatibility

---

src/timed-event-manager.ts

Allows Stantler spawned from the event in mystery encounters to evolve
Fixes missing attribute which led to unintended prevention of Wyrdeer spawn 
Adds `allowEvolution: true` to Stantler’s event encounter entry

[Balance] Allow event Stantler to evolve

---

package-lock.json
package.json
src/data/mystery-encounters/encounters/berries-abound-encounter.ts
src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts
src/data/mystery-encounters/encounters/uncommon-breed-encounter.ts

- Hotfix error causing crashes, softlocks, and incorrect encounters due to event encounters

[Hotfix] Fix off-by-one error for event encounters

---

package-lock.json
package.json
src/data/pokemon-forms.ts

Merge main (1.4.2) into beta

---

src/data/balance/starters.ts
src/data/mystery-encounters/encounters/delibirdy-encounter.ts
src/data/mystery-encounters/mystery-encounters.ts
src/phases/trainer-victory-phase.ts
src/test/mystery-encounter/encounters/delibirdy-encounter.test.ts

- Fully reverts changes meant for the event which are not automatically reverted by TimedEventManager
- Includes:
- Friendship gain from battle 4->3
- Delibird Amulet Coin Price 1.5x Relic Gold -> 2x Relic Gold
- Delibirdy Common Tier -> Great Tier
- Delibirdy max 4 encounters per run -> max 2 encounters per run
- Gym Leaders etc. previously fought reward Voucher Plus->reward Voucher
- Department Store Sale and Part Timer Mystery Encounters re-enabled
- Field Trip and An Offer You Can't Refuse remain disabled
- TimedEventManager handles many aspects of the event but not all of them, some things needed manual reversion
- Field Trip and Offer are widely considered dud encounters and will stay disabled pending reworks in consideration of community feedback
- Delibirdy test now expects it to …

[Misc] Undo winter holiday event changes

---

package-lock.json
package.json

Version bump from `1.4.2` to `1.4.3` with synced locales.
N/A
N/A
N/A
N/A
- ~[ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?~
- ~[ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?~
- ~[ ] If so, please leave a link to it here:~
- ~[ ] Has the translation team been contacted for proofreading/translation?~

[Misc] `1.4.3` Version Bump + Locales Update

---

package-lock.json
package.json
src/battle-scene.ts
src/battle.ts
src/data/balance/starters.ts
src/data/mystery-encounters/encounters/delibirdy-encounter.ts
src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
src/data/mystery-encounters/mystery-encounters.ts
src/field/pokemon.ts
src/phases/command-phase.ts
src/phases/trainer-victory-phase.ts
src/system/settings/settings.ts
src/test/evolution.test.ts
src/test/mystery-encounter/encounters/delibirdy-encounter.test.ts

- Added Cursor Memory Option to settings
- Off = Defaults to Move Select
- On = Remembers what battle option you ended the previous battle on
- Replaced the label for music settings to be more accurately named
- Fixed Shedinja to be genderless upon evolution
- Fixed event changes, kept two Mystery Encounters disabled (An Offer You Can't Refuse and Field Trip)

Minor Release 1.4.3

---

src/ui/dropdown.ts
src/ui/starter-select-ui-handler.ts

- The player can now sort the starter select screen by the amount caught or hatched for each species
- Useful information for the player
- Adds the CAUGHT and HATCHED options to the SortCriteria enum
Sorting by caught count
Sorting by hatched count
- Open starter select

[UI/UX] Add sort by caught/hatched count to starter select

---

package-lock.json
package.json

Updates game version to 1.5.0.

[Misc] Update version to 1.5.0

---

src/phases/trainer-victory-phase.ts

The rival will give event charms regardless of event type
Decided by balance that the charms should be kept even in non shiny events
Reverts change from timed event update to trainer victory phase

[Balance] Rival gives charms in any event

---

src/timed-event-manager.ts

Fixes the event banner not appearing 
Adds the array of available languages for the banner, which was empty initially so it wouldn’t crash while we waited for the banners to be made. From now on we’ll probably use placeholders instead.

[Hotfix] Fix year of the snake event banner

---

package-lock.json
package.json

[Misc] Update version number to 1.5.1

---

src/ui/ui.ts

- The arena flyout will now show up when the button is pressed while selecting a target in double battles
Fixes #5209
Adds Mode.TARGET_SELECT to the list of modes where this flyout can show up
Before
After
Have flyouts enabled, select a move in double battle that makes you select a target. While in the target selection phase, hit the button to show the arena flyout (defaults to V on keyboard).

[Bug] [UI/UX] Allow arena flyout during target selection

---

src/battle-scene.ts

Rapid Strike Urshifu is now able to be encountered in the wild and on any trainers that may have an Urshifu.
It was brought to my attention that only the Single Strike form could be encountered in the Dojo, and this was an easy fix.
One new entry in the `getSpeciesFormIndex` for Urshifu, letting the game randomly pick from Single Strike or Rapid Strike forms, but _not_ the Gigantamax forms.
Force a wild encounter with Urshifus, and you will see that it will randomly choose between the two forms.
~- [ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?~
~- [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~

[Bug] Fix Rapid Strike Urshifu not appearing in wild and on trainers

---

package.json

This command updates the locales submodule to the latest remote commit from https://github.com/pagefaultgames/pokerogue-locales
After use, you then `git commit` the changes like normal.
Commandline example:

[Misc] Add `update-locales:remote` command to `package.json`

---

package-lock.json
package.json
src/ui/title-ui-handler.ts

Reverts pagefaultgames/pokerogue#5263
To be merged after the server is back up.

Revert "[Hotfix] Adding warning message for the maintenance"

---

src/ui/summary-ui-handler.ts

Revert "[UI/UX] Show IVs on stats page of summary (#5172)"
Caused hanging upon leaving a save on beta forcing a reload, read the discord chat from 4am EST

Revert "[UI/UX] Show IVs on stats page of summary (#5172)"

---

src/ui/summary-ui-handler.ts

Reverts pagefaultgames/pokerogue#5284
seems like it was a pokedex issue..... guess that's another to the list

Reapply [UI/UX] Show IVs on stats page of summary (#5172)

---

src/test/moves/tera_blast.test.ts

N/A
The test sometimes fails because the enemy pokemon faints.
Gave the enemy sturdy and increased its level to 50.
`npm run test tera_blast`

[Test] Fix Tera Blast test

---

package-lock.json
package.json

Version screen will now show 1.6.0
We just got a new update!!! :D
increment version number to `1.6.0` in `package-lock.json` and `package.json`
(I just ran npm run update-version:minor)
<details><summary>Title Screen</summary>
</details>

[Misc] Increment version number

---

src/battle-scene.ts
src/battle.ts
src/data/ability.ts
src/data/challenge.ts
src/data/move.ts
src/data/mystery-encounters/encounters/safari-zone-encounter.ts
src/data/mystery-encounters/encounters/weird-dream-encounter.ts
src/field/pokemon.ts
src/modifier/modifier-type.ts
src/phases/money-reward-phase.ts
src/phases/pokemon-heal-phase.ts
src/phases/select-modifier-phase.ts
src/test/achievements/achievement.test.ts
src/ui/modifier-select-ui-handler.ts
src/utils.ts

None
#5250 replaced all instances of Integer with number. There is no reason to use integer holder anymore. I have removed it and replaced all references to it with number holder.
The deprecated `IntegerHolder` has been removed and all references replaced to `NumberHolder`
N/A
N/A
~~Are there any localization additions or changes? If so:~~
- ~~[ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?~~
- …

[Refactor] Replace integer holder with number holder

---

package-lock.json
package.json
src/system/version_migration/version_converter.ts

The version number needs to be higher on beta than main for any migration code to actually run, as the game doesn't migrate saves within a version.
Version number updated.

Update version number for beta

---

src/test/abilities/wimp_out.test.ts

N/A
The test doesn't work properly.
The broken test is disabled.

[Test] Disable broken Wimp Out test

---

src/field/pokemon.ts

Pokemon with a significant difference between stats are much less likely to generate with off-stat moves.
Came up in balance chat.
Small tweak to moveset generation making whether a move matches the higher attacking stat non-linear, it's now less impactful when they're very close and *much* more impactful when there's a significant difference. In particularly extreme cases off-stat moves can now be four to five times less likely to generate than they were before.
N/A
Play dozens of runs against trainers with lopsided pokemon to see?

[Balance] Make stat a much larger factor in moveset gen

---

src/ui/starter-select-ui-handler.ts

This has been requested by players multiple times.

[UI/UX] Pokédex - Move Pokédex option up the starter select screen menu

---

src/test/utils/gameWrapper.ts

None
I am tired of having these error messages display in all of the logs in tests.
You can run tests without seeing these darn error messages everywhere.
Inside of the test's `GameWrapper.ts`, I imported the BBCodeText and modified the destroy method for its prototype to do literally nothing. This is probably a bandaid fix and technically leaks memory since it's... not destroying anything? I don't know, I don't fully understand the class. It's just for tests though so it shouldn't matter anyway.
I think a better solution would be to figure out how to mock the BBCodeText class to inherit from our Phaser.GameObject.Text mock, maybe? I'm not entirely sure. I sort of followed the style for what was done with our other rex plugin.
The issue stems from the fact that our textures are mocked. …

[Misc] Fix bbcode test error

---

src/field/pokemon.ts

- Fixes a bug where Gimmighoul's evo counter would be reset if it was selected as the second mon in a fusion
- Fusions now take the higher evo counter value between the two mons
- Evo counter also copies over to Shedinja if a Nincada-Gimmighoul fusion evolves
[Bug reported here](<https://discord.com/channels/1125469663833370665/1343649829821091902>)
- Sets evo counter to max(this, other) when fusing
Collect a nugget, then fuse Gimmighoul to another mon

[Bug] Maintain evo counter when fusing

---

src/data/ability.ts

Revert pr causing issues with tests

[Misc] Revert "[Bug] Fix canApplyAbility check #5413"

---

src/loading-scene.ts

Fixed the event banner not displaying for pkmnday2025event
Wasn't showing up
Event Banner updated in loading-scene
Before
After

[Misc] Event Banner Fix

---

package-lock.json
package.json
src/data/trainer-config.ts

Penny will no longer have two Zamazenta erroneously.
Penny was given Zamazenta twice in (https://github.com/pagefaultgames/pokerogue/pull/5233)
Remove extra Zamazenta slot from Penny_2
Overrides

[Bug] [Hotfix] Remove Penny's Extra Zamazenta

---

index.html

Requested by @Xavion3 [here](https://discord.com/channels/1125469663833370665/1176874654015684739/1345279892362756177) to fix the bug reported on discord [here](https://discord.com/channels/1125469663833370665/1344863240353484901) and [here](https://discord.com/channels/1125469663833370665/1345048222481125405).
Use the correct key name.
Before:
https://github.com/user-attachments/assets/0b15ecab-d9c6-4378-add6-bd800712353e
After:
https://github.com/user-attachments/assets/2aae4701-1f7a-4937-885f-df96f60f0c4b
Turn on the phone emulator in your browser and mash that V button.

[Bug][UI/UX] Restore V button in battle

---

src/data/move.ts

According to [this bug report on Discord](https://discord.com/channels/1125469663833370665/1345435527461077022), trying to access the move list of a Pokémon who knows a Pledge move crashes the game (whether from the summary, or teaching a new move).
I was able to replicate the game crashing locally, using this override:
```
MOVESET_OVERRIDE: [Moves.FIRE_PLEDGE, Moves.WATER_PLEDGE, Moves.GRASS_PLEDGE],
```
and starting a run with two Pokémon. In particular, I got this error
The root of the bug seems to be this line in moves.ts, which is called to determine the type of the move when accessing the summary:
Adding ?s to check whether `turnData` exists is enough to solve the issue.
I'm unsure why the bug is showing …

[Bug] Pledge moves in summary do not break the game

---

CREDITS.md

[Misc] Add Wlowscha and SirzBenjie to credits

---

src/modifier/modifier-type.ts

Players should now be able to pick up `Mystical Rock` from the rewards screen without crashing the game.
Picking up the item was not intended to crash the game.
Changes the `modifierTypes` entry callback to give a `PokemonHeldItemModifierType` instead of a `ModifierType`.
N/A
Have a Pokémon fulfilling any of the conditions listed in #4799 and keep rolling for the item. Grabbing it should no longer crash the game.
- ~[ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?~
- ~[ ] Has a locales PR been created …

[Bug] `Mystical Rock` Crashing on Selection

---

lefthook.yml

N/A
We already have a lefthook for commits that is doing the same thing. We don't need a pre-push lefthook, as all this does is mess with files that you didn't yourself change.
Remove the pre-push from lefthook.yml
N/A
N/A
- ~~[] Have I provided screenshots/videos of the changes (if applicable)?~~

[Misc] Remove pre-push lefthook

---

src/data/ability.ts

Flower gift flyout doesn't appear forever
It was queueing the flyout itself instead of letting it happen normally. no idea why

[Bug][Hotfix] Fix Flower Gift/Forecast flyout

---

package-lock.json

See #5601 
See #5601
Includes the proper changes to package-lock.json to fix the visual bug on clients
<details><summary> After change </summary>
</details>
`npm install` then `npm run start:dev`

[Misc] Rollback phaser update (package-lock.json)

---

src/modifier/modifier-type.ts

Mystical Rock didnt check for Drought abilities, now it does.
Cause it should have it.
Mystical Rock had Drizzle listed twice and no Drought.

[Bug] Mystical Rock modifier missing Drought check

---

src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
src/field/trainer.ts
src/system/trainer-data.ts

Non-English languages won't crash when encountering trainers
There are two issues that can happen:
1. The locales file is incomplete, so a trainer class has the `MALE` key but not `FEMALE` existing. This is fixed by going through `i18next` for everything instead of handling objects directly so fallbacks are respected properly.
2. Trainer names are saved in `GameData` which results in non-latin alphabet languages crashing when trying to encode the data. This is fixed by storing the locales key for the trainer name instead of the name itself. This also means that trainer names will properly change when switching languages.
Encounter a trainer

[Bug][Hotfix] Fix crash when pulling trainer names for (certain) non-English languages

---

package-lock.json
package.json

Sync locales and update version to 1.8.4

---

src/data/pokemon-species.ts

Shiny variants will now show their sprites
Fixes a regression introduced in #5592 where the sprite recolor for variants would not show for many sprites when exp sprites were enabled.
Inside `pokemonSpecies#loadAssets`, we add these lines:
```ts
const baseSpriteKey = this.getBaseSpriteKey(female, formIndex);
// Force the variant color cache to be loaded for the form
await populateVariantColorCache(
"pkmn__" + baseSpriteKey,
globalScene.experimentalSprites && hasExpSprite(spriteKey),
baseSpriteKey,
);
```
which force the color cache to be populated.
I also added a `getBaseSpriteKey` to `PokemonSpecies` to extract out the logic for computing the base sprite key for a pokemon (as this is what we need to use to use as the cache key). I modified the `getSpriteId` method to call this.
I believe …

[Bug][Sprite] Fix experimental variant sprites not being loaded in starter select screen

---

src/field/pokemon.ts
test/abilities/illusion.test.ts

- [x ] **I'm using `beta` as my base branch**

[Bug] Pokemon with illusion imitate the cry of the illusion

---

src/data/pokemon-species.ts

Nothing unless they're in the habit of opening the console
Fixes an oversight introduced in #5664 where variant recolor jsons were trying to be loaded even if none existed, causing incessant console spam:
`variantData` for the species will now be checked for the presence of a `1` (which indicates if variants are recolored from a json) before trying to load the variant json
N/A
Open the game, go to starter select, and hover over squirtle, pidgey, etc.

[Bug][Sprite] Fix variant loading console spam

---

src/data/abilities/ability.ts

Transistor will see a slight reduction in damage. (1.5 boost to 1.3 boost as in Pokemon S/V)
Balance Team Decision, the ability being the previous iteration went unnoticed.
Slight changes to ability.ts
Thunder Shock now has 52 expected BP (40 x1.3) instead of 60 BP (40 x1.5)
Overrides

[Balance] Update Transistor to Gen IX version

---

package.json
src/plugins/api/pokerogue-system-savedata-api.ts
src/system/game-data.ts

Mirror of #5715 pointing at beta in order to test the API changes.

[Bug] API / Save data hotfix

---

src/data/moves/move.ts

None
To document an interaction. See https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/
Just added `.edgeCase()` and a comment to transform.
N/A
N/A
- ~~[ ] Are all unit tests still passing? (`npm run test`)~~

[Misc][Move] Add edge case to transform

---

package-lock.json
package.json

Up version 1.8.5 -> 1.9.0

---

src/timed-event-manager.ts

[Misc] More Spring

---

src/system/version_migration/versions/v1_9_0.ts

N/A
NightKev forgot to remove a duplicated line of code from the constructor after fixing illusion crash.
Removed 1 extra line of code.
srsly broh
just don't

[Tiny] Removed unused loc in v1_9_0.ts

---

src/data/trainers/TrainerPartyTemplate.ts

- Fixes issue where evil team grunts would use the wrong party template, notably on wave 35 having 6 mons
- Bug introduced in #5689 

[Hotfix] Fix evil grunts using wrong template

---

public/battle-anims/psychic.json
src/system/game-data.ts

1.Game stopped with this error, read #2614 ;
2.File name error

[Bug] Fix local save encoding crash and Psychic anim

---

package-lock.json
package.json
src/data/egg.ts
src/field/pokemon.ts
src/modifier/modifier-type.ts
src/phases/select-biome-phase.ts
src/system/version_migration/versions/v1_9_0.ts
test/abilities/illusion.test.ts

PR for hotfix version 1.9.2 to main

Hotfix 1.9.2 to Main

---

package-lock.json
package.json
src/battle-scene.ts
src/field/pokemon.ts
src/phases/move-effect-phase.ts
src/system/game-data.ts
src/system/pokemon-data.ts

PR for hotfix version 1.9.3 to main
Note: Do a locales sync before merging.

Hotfix 1.9.3 to main

---

src/ui/egg-counter-container.ts

None
I'm going through all UI files and cleaning up logic.
Almost nothing. There were only a few instances where I could apply method chaining.
N/A
N/A

[Refactor] Cleanup egg-counter-container

---

package-lock.json
package.json

Was forgotten to be done in the last hotfix/update.

Update version to 1.9.5

---

src/data/balance/pokemon-evolutions.ts
src/modifier/modifier-type.ts

- Fixes Pikachu and Eevee not spawning evo items
- Fixes issue introduced by evo refactor reported [here on Discord](<https://discord.com/channels/1125469663833370665/1176874654015684739/1384213740538564650>)
- `isValidItemEvolution` was accidentally checking the wrong form key
- This meant those evolutions weren't considered when generating evo items
- Now checks the fusion form key if it's checking for a fusion and the regular form key if not, as opposed to the other way around
- Fusion evo items use `isValidItemEvolution` check too
Pikachu spawning evo stones
Cosplay Pikachu does not

[Bug] Fix incorrect form key being checked for evo items

---

test/moves/gastro_acid.test.ts

who cares
FLAKY TEST aaaaaaaaa
DIE DIE DIE
no thx
just no

[Test] Fix flaky gastro acid test

---

CONTRIBUTING.md

Docs marginally neater
typofix
Fixes typo
> reach out reach out
N/A
N/A

[Docs] Fix typo in CONTRIBUTING.md

---

src/data/mystery-encounters/encounters/training-session-encounter.ts
src/field/anims.ts
src/field/arena.ts
src/modifier/modifier-type.ts
src/system/settings/settings.ts
src/ui/egg-gacha-ui-handler.ts
src/ui/game-stats-ui-handler.ts
src/ui/pokedex-ui-handler.ts
src/ui/starter-select-ui-handler.ts
src/ui/stats-container.ts

N/A
`new Array(n).fill(...).map(...);` is dumb.
Replaced most instances of `new Array(n).fill(...).map(...)` with `for` loops.

[Refactor] Replace `.fill().map` "loops" with real `for` loops

---

src/items/held-item.ts
src/items/held-items/accuracy-booster.ts
src/items/held-items/attack-type-booster.ts
src/items/held-items/base-stat-booster.ts
src/items/held-items/base-stat-flat.ts
src/items/held-items/base-stat-total.ts
src/items/held-items/baton.ts
src/items/held-items/berry.ts
src/items/held-items/bypass-speed-chance.ts
src/items/held-items/crit-booster.ts
src/items/held-items/damage-money-reward.ts
src/items/held-items/exp-booster.ts
src/items/held-items/field-effect.ts
src/items/held-items/flinch-chance.ts
src/items/held-items/friendship-booster.ts
src/items/held-items/hit-heal.ts
src/items/held-items/incrementing-stat.ts
src/items/held-items/instant-revive.ts
src/items/held-items/item-steal.ts
src/items/held-items/multi-hit.ts
src/items/held-items/nature-weight-booster.ts
src/items/held-items/reset-negative-stat-stage.ts
src/items/held-items/stat-booster.ts
src/items/held-items/survive-chance.ts
src/items/held-items/turn-end-heal.ts
src/items/held-items/turn-end-status.ts
src/items/trainer-item.ts

Adds destructuring to the modifier's apply methods

Add parameter destructuring

---

.github/workflows/deploy-beta.yml

N/A
The `if` statement was broken, causing it to always evaluate to `true`. Thanks GitHub.
Replaced `${{ ... }}` with `(...)`.

[Dev] Fix `if` statement in beta deploy script

---

.github/workflows/github-pages.yml

WE HAVE TYPEDOCS FOR BETA 🎉 
https://pagefaultgames.github.io/pokerogue/beta/index.html
I _wanted_ to test that changing the `deploy-docs` action to work on pushes/commits to beta wouldn't break anything... but apparently `act` just pushed to the branch regardless despite running within a Docker container.
Oops!
Fixes #6049 
Updated the workflow to also trigger on pushes to `beta`, creating docs in the `beta` folder.
LOOK AT THE SIDE
READ IT WITH YOUR EEEYEES

[Dev] Added typedoc deployments for Beta

---

src/phases/command-phase.ts

None
This is another part of the work to cleanup the phase files and make them more maintainable and easier to understand.
All of the methods in command phase now pass the cognitive complexity lint.
Broke up the mega methods inside of command phase into small, purposeful parts without changing any of the logic.
Added documentation to each part.
N/A
Just play the game and ensure that the game runs as before.
I played ~25 waves or so.
I went through all of the logic to ensure everything was called just as it was before.
Brittle mechanics that are sensitive to breaking:
Switching via the baton item works as normal
Attacking / target selection in double battles continues as normal
Fleeing / Switching under the effects of a trapping effect continues to work as normal
- ~~[ ] Have I created new …

[Refactor] Refactor command phase

---

src/data/challenge.ts
src/phases/select-starter-phase.ts

- Removes non-Legend Fresh Start challenge option from #6162 
- Fixes an issue where starters chosen in Fresh Start would have their moves set to their first 4 level-up moves, even if another had been chosen (for starters with more than 4 moves by level 5)
- Fixes an issue where a shiny starter modified by the Fresh Start challenge would still show the shiny icon when first sent out
- Non-legend tier was unnecessary and could conflict with a future challenge making that restriction
- Fresh start has max value of 2, does not check for Legendaries on mode 2
- Calls updateInfo in starter select phase if a starter was modified by a challenge

[Balance] [Beta] Remove non-Legend Fresh Start option, fix starting movesets

---

src/data/balance/pokemon-evolutions.ts

Update to https://github.com/pagefaultgames/pokerogue/pull/6198, Cosmog will now require 43 friendship (previously 40) to evolve while Cosmoem can now spawn in its evolution items as early as level 13 (previously 23).
damo request and prime numbers
Change to pokemon-evolutions.ts
Overrides

[Beta] [Balance] Further Cosmog Evolution Readjustments

---

src/data/pokemon/pokemon-data.ts

Fix a nasty oversight introduced by #6145 
Adds missing continue statements.
Use transform, save & quit, ensure data persists.

[Bug] [Beta] Fix serialization with transform

---

src/data/balance/pokemon-evolutions.ts

To evolve Petilil into Hisui Lilligant, players will now need to use a Dawn Stone instead of a Shiny Stone.
Purely flavor, also only 2 lines currently use Dawn Stone so they could use the company. :) 
The actual logic to this change is the Dawn Stone being heavily tied to Sinnoh, and Hisui Lilligant being a form from Sinnoh aligns with Kirlia/Snorunt also turning into Sinnoh Pokemon. Now that the stone has been included it would be nice for something other than just 2 lines to use it.
Changes to pokemon-evolutions
Overrides

[Balance] Hisui Lilligant Evo Method Change

---

public/battle-anims/common-wind.json

The Fog weather will now visually have a background, like the Essentials animation it is supposed to pull from.
Fog only had an audio cue for it's effect, and no visuals, so now it has one.
An animated background was added to Fog's common animation.
https://github.com/user-attachments/assets/25ac2693-f8df-4291-ae48-e8007a13790d
Override the weather to Fog.
~~- [ ] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?~~
~~- [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

[Animation] Update fog animation to use strong winds BG

---

src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts

This PR disallows the Expert breeder encounter while doing a Hardcore Challenge.
It is being discussed, but I'm putting the PR up so it can be merged quickly if the decision is made.

[Challenge] No hardcore breeder

---

tsconfig.json

None
I inadvertently pushed a commit to `hotfix-1.10.4` that was meant to go in a pull request. It ended up breaking typedoc.
Added `public/service-worker.js` to the files excluded from typedoc. 
``pnpm exec typedoc --out /tmp/docs --githubPages false --entryPoints ./src/``
(once done, `rm -rf /tmp/docs`)

[Bug] Fix typecheck bug

---

package.json
public/service-worker.js
src/data/balance/pokemon-evolutions.ts
src/data/mystery-encounters/encounters/weird-dream-encounter.ts
src/enums/pokemon-type.ts
src/field/pokemon.ts
src/phases/turn-start-phase.ts
src/ui/starter-select-ui-handler.ts
src/utils/data.ts
test/evolution.test.ts
tsconfig.json

Hotfix 1.10.4 to main

---

src/ui/starter-select-ui-handler.ts
src/utils/data.ts
test/utils/data.test.ts

* Prevent an empty starterpreferences object from being saved
* Fix ssui nullish coalescing
* Update src/utils/data.ts
* Fix starter preferences clearing, add tests
---------

Fix starterpref reset (#6430) to main

---

src/data/moves/move.ts

Will show the type and not the key
#6439 forgot to make `type` lowercase
Fixed locales key
use soak

[Bug] Fix soak message type

---

.github/workflows/github-pages.yml

Fixing a small mistake from the Typedoc PR.
Inverted the conditional and re-added the `git add`.

[GitHub] Fix Typedoc workflow

---

.github/workflows/github-pages.yml

N/A
fixes workflow
Made the GH pages workflow compare against string `'false'` instead of boolean `false`

[Dev] Fix GH pages workflow to push docs correctly

---

typedoc.config.js

4TH TIME PLEASEEEE
@SirzBenjie maybe i should use act to debug this shit

[Dev] Fix typedoc.config.js

---

README.md

[Misc] Update README.md svg to actually go to discord

---

.github/workflows/github-pages.yml

[Dev] Update github-pages.yml to maybe add the files right

---

src/loading-scene.ts

None, other than a couple errors no longer appearing in the console.
This file was renamed and moved in PR #6433 so this loadImage is no longer needed here.
Removed one single loadImage instance, This stops the console errors related to these files being missing in the directory it was expecting.
Before
After
Load the game and look at the console while loading.
~~- [ ] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?~~
~~- [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

[Misc] [Bug] Remove `summary_overlay_shiny` from loading scene

---

src/ai/ai-moveset-gen.ts
src/data/balance/moveset-generation.ts
src/vite.env.d.ts
test/ai/ai-moveset-gen.test.ts

Enemy ditto will no longer crash the game
Fixes a P1 Bug
- Added a protection against `null` when generating TMs to prevent an attempt to iterate over undefined
- Added a bunch of unit tests for the methods
- Adjusted `vite.env.d.ts` to remove biome's warning for unused interfaces in `vite.env.d.ts`
- Added the `NODE_ENV` environment variable to the MetaEnv, which is always defined during build, since vite uses node to build
- Created an export that, when run with vitest, allows unexported functions inside of `ai-moveset-gen` to be exported *just for tests*
- Created a constant for `BASE_LEVEL_WEIGHT_OFFSET` and put it in the balance folder, along with lots of documentation (This is included here as the stuff was dirty)
<details><summary>Ditto with this PR</summary> …

[Tests][Bug][Beta] Fix ditto bug and add unit tests

---

src/data/balance/biomes.ts
src/data/balance/pokemon-evolutions.ts

Certain Pokémon with an evolution level _and_ evolution delay were evolving _much_ later than intended in the wild and on Trainers, this has been fixed.
The affected Pokémon were: Mantyke, Pancham, Sliggoo, Cosmoem, Hisuian Sliggoo, Tangela, Lickitung, Aipom, Yanma, Girafarig, Dunsparce, Stantler, Steenee, and Primeape.
The listed Pokémon evolving too late made battles unintentionally too easy.
The evolution level threshold wasn't applying correctly to the biome entries of Pokémon that evolved via evolution items (so anything with a level 1 "requirement"), this has been fixed.
The evolution delay for certain Pokémon has been lowered, as it was compounding with their existing level requirements, making their evolutions take way too long to happen. The values were lowered to match the …

[P2 Bug] [Balance] Fit initBiomes incorrectly getting evo level threshold

---

test/abilities/liquid-ooze.test.ts

N/A
I didn't want to block the pr from being merged earlier
Fixed up tests to use updated utils
Added a few TODOs for other tests we need
N/A
`pnpm test liquid-ooze.test.ts`

[Test] Improved liquid ooze test file to use updated test utils
